### ISSUE TITLE
Android: Application rotate to landscape mode even if auto-rotate in disabled system wide. 

### ISSUE THREAD

**Issue by Hagfjall** [mattermost/mattermost-mobile#1007]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
If auto-rotate screen is disabled system wide the Mattermost application ignores that and rotate to landscape mode if device is rotated. 

#### Environment Information

- Device Name: LG G6
- OS Version: Android 7.0
- Mattermost App Version:  1.3.0
- Mattermost Server Version: -

#### Steps to reproduce
Rotate the device to landscape mode 

#### Expected behavior
Application should stay in portarit mode regardless of the device's current orientation.

**Comment by enahum** [comment]
This should be fixed by #1006
