### ISSUE TITLE
[Help Wanted] Render images uploaded from newer iOS devices

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#1015]
iOS is using a new standard (HEVC and HEIC) for images and video on iPhone 7+. These are currently not rendered in Mattermost.

Proposed fix: We should be able to convert HEVC and HEIC to a jpg or mp4 file before uploading so the preview will render properly in Mattermost.

---
Jira ticket: https://mattermost.atlassian.net/browse/RN-355
Original report: https://forum.mattermost.org/t/heic-format-not-supported-by-mobile-app/3876/5

**Comment by enahum** [comment]
done
