### ISSUE TITLE
Side-scrolling of wide performatted text blocks doesn't work on Android app

### ISSUE THREAD

**Issue by ringerc** [mattermost/mattermost-mobile#1017]
#### Summary

Display of wide fixed format text blocks on Android is unusable because side-scrolling generally doesn't work.

#### Environment Information

- Device Name: Nexus 5x (but reported by peers on other devices)
- OS Version: Android 8.0
- Mattermost App Version: 1.0 build 39
- Mattermost Server Version: 4.2.0

#### Steps to reproduce

Post a block of wide text to a chat. In my case, PostgreSQL logs are the typical challenge. Preformat it with triple-backticks, or four left-leading spaces. If it matters, the text is often being written from the web client.

Visit the chat in the mobile app. Try to scroll sideways in the chat block by touching and dragging, two-finger drag, pinch, etc. Most likely you'll land up focusing the message/conversation instead.

With the message focused, try again to side scroll by dragging. Often it'll work the *first* time you scroll. Subsequent attempts to scroll around it will instead cause the whole message to be highlighted, but no movement in the fixed-width area. Or the "flag" pop-up will appear.

#### Expected behavior

Touch-and-drag should side-scroll blocks of preformatted text, either in the main chat listing or when focused on a specific thread.

#### Observed behavior

Per above: side-scrolling sometimes works the first time you attempt to scroll a given message, only when zoomed in thread view. But after that scrolling attempts have no effect, or pop up the "flag" dialog instead.

**Comment by enahum** [comment]
Hi @ringerc this is already available with version 1.3 build 57

**Comment by ringerc** [comment]
@enahum Ah... I appear to have been confused by the existence of "Mattermost Beta", "Mattermost Classic" and "Mattermost" apps; it looks like the appstore search decided not to find, or I didn't see, the one named simply "Mattermost".

If "Mattermost Beta" is no longer actually newer than "Mattermost" is it possible to remove it from the Play Store? Or push an update that deprecates it and asks users to switch?

**Comment by ringerc** [comment]
Issue invalid, closing, thanks.

Please do consider cleaning up the appstore contents.
