### ISSUE TITLE
Android app hangs on resume after the device wakes up from sleep  

### ISSUE THREAD

**Issue by ywongweb** [mattermost/mattermost-mobile#1018]
#### Summary
Android app hangs at white screen on resume after the device wakes up from sleep  

#### Environment Information

- Device Name:  Galaxy S8, Nexus 6P
- OS Version: 7.0 and 8.0
- Mattermost App Version: 1.3.0
- Mattermost Server Version: 4.2

#### Steps to reproduce
Start the app  
Minimise it  
Use your app as normal  
After an hour or two, wake phone up and resume the mattermost app by pressing the icon  
Hangs on white screen  

#### Expected behavior
App should launch

**Comment by uusijani** [comment]
Reproducible here on a Galaxy Tab 4 (SM-T530), Android 5.0.2.

**Comment by enahum** [comment]
This should be fixed by #1027

**Comment by vimmerru** [comment]
> This should be fixed by #1027

Are there any plans to release this changes? It causes a very bad UX of the android app.

**Comment by enahum** [comment]
We release every month on the 5th

**Comment by lfbrock** [comment]
Hi @vimmerru - v1.4 is now released, going to close this issue but if you see it happening still please re-open
