### ISSUE TITLE
Android: Notifications cause stack trace when pressing 'Clear All' after latest update

### ISSUE THREAD

**Issue by Shygar** [mattermost/mattermost-mobile#1037]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
If you have one or more notification from a channel, you will get a Close or Send Feedback type stacktrace error on the device when you press the 'Clear All' button to clear the notifications.

#### Environment Information

- Device Name: Galaxy S8
- OS Version: 7.0
- Mattermost App Version: 1.3.0 build 57 (still happens on 1.4.1 build 64)
- Mattermost Server Version: 4.0.0 (4.0.3)

#### Steps to reproduce
1. Receive a notification on your android device.
2. Bring down your notifications by swiping down from the top.
3. Click 'clear all'.
4. Observe the Mattermost app crashing and requesting you to close or send feedback

#### Expected behavior
No crash should happen

#### Observed behavior
Crashes

#### Possible fixes
Not sure, but I submitted feedback many times. So whoever is in charge of publishing your app to Google Play can see those stacktraces and know what is going on.

**Comment by lfbrock** [comment]
Hi @Shygar - we fixed some errors related to this in the latest release (v1.4.0), would you be able to try upgrading and let us know if you still see the issue?

**Comment by Shygar** [comment]
Hi @lfbrock ,
I did get the latest and I am still seeing the issue. I tried clearing data/cache but I noticed again today that I'm still getting a crash. It does not appear to happen all of the time. I'm not certain but I feel like it happens more when I read/contribute to a channel via the desktop app on my laptop, then go and clear the notifications.

I submitted the feedback again so if you can check the google play account you should be able to see it.

Let me know if there's anything else I can check.

**Comment by Shygar** [comment]
Hi, I was wondering if you had a chance to look at this one.

**Comment by Shygar** [comment]
This appears to be fixed in the latest build 72. Thanks!
