### ISSUE TITLE
Notification and badge never clear on Android

### ISSUE THREAD

**Issue by vincent-dravert** [mattermost/mattermost-mobile#1038]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Notification and badge never clear on Android

#### Environment Information

- Device Name: Galaxy S7 and multiple other Android mobiles of my colleagues
- OS Version: Android 6
- Mattermost App Version: 1.2.0 (build 49) & 1.3.0 (build 57)
- Mattermost Server Version: 4.1.0

#### Steps to reproduce
Receive a message and whether you read it or not, badge and notification stay

#### Expected behavior
Notification and badge counter related to read messages should disappear

#### Observed behavior
MM notifications keep adding on the mobile notification feed and need a manual process to be cleared out

#### Possible fixes
Notifications should be bound to the source message and be cleared when the message is read. Badge should be decremented as well.

#### Stack trace
Current User Id: ucsjqnmwm3raukanotsjxy5krr
Current Team Id: xshr7ij3njbx8kxjuy8johpwnh
Server Version: 4.1.0 (Build 4.1.0)
App Version: 1.2.0 (Build 49)
App Platform: android

Errors:
Date: Wed, 30 Aug 2017 09:52:18 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Wed, 30 Aug 2017 09:52:18 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Wed, 30 Aug 2017 09:52:18 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Wed, 30 Aug 2017 09:52:35 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Wed, 30 Aug 2017 09:52:35 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Wed, 30 Aug 2017 09:52:35 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Wed, 30 Aug 2017 09:52:35 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Wed, 30 Aug 2017 09:52:35 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Wed, 30 Aug 2017 09:52:35 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:47:59 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:47:59 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:47:59 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:47:59 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:47:59 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:47:59 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:48:00 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:48:00 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:48:01 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:48:01 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:48:02 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:48:02 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 31 Aug 2017 00:48:02 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Mon, 04 Sep 2017 23:31:18 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:423:13650
value@index.android.bundle:413:1505
value@index.android.bundle:412:6938
value@index.android.bundle:412:3518
index.android.bundle:412:9990
value@index.android.bundle:331:1372
value@index.android.bundle:318:3012
index.android.bundle:318:953
value@index.android.bundle:318:2413
value@index.android.bundle:318:925
[native code]

Date: Thu, 07 Sep 2017 01:25:26 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:26 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:26 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:26 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:26 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:26 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:28 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:28 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:28 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:29 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:29 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

Date: Thu, 07 Sep 2017 01:25:29 GMT
Message: Network request failed
Stack trace:
onerror@index.android.bundle:431:13650
value@index.android.bundle:421:1505
value@index.android.bundle:420:6938
value@index.android.bundle:420:3518
index.android.bundle:420:9990
value@index.android.bundle:339:1372
value@index.android.bundle:326:3012
index.android.bundle:326:953
value@index.android.bundle:326:2413
value@index.android.bundle:326:925
[native code]

**Comment by lfbrock** [comment]
Hi @vincent-dravert - are you using the apps from the Google play store, or building them yourself? 

We've been trying to reproduce this but haven't had much luck, when a channel is read we send a special notification that lets us clear the other ones. It seems to be working when we test it out, so not sure what's happening here.

**Comment by vincent-dravert** [comment]
Hi,

yes I am using the app from the Play store and actually all my team (about 20 people in various mobiles) all have the same issue, and also online, people are posting the same issue on blogs. I will test again with the new version released this week on Android, as I disabled notifications so far.

Thanks for your investigation

Vincent

**Comment by lfbrock** [comment]
Hi @vincent-dravert - just wanted to follow up on this issue, are you still having problems with this?

**Comment by koxen** [comment]
this is still not working on android

**Comment by koxen** [comment]
code looks fine. not sure why this doesn't work. 
https://github.com/mattermost/mattermost-mobile/blob/master/android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java#L312

**Comment by dbrgn** [comment]
For me, when I open the mobile app, the mobile notifications are cleared.

What I'm missing though is that notifications on the mobile are cancelled when I read the messages using the web chat. Is that out of scope?

**Comment by koxen** [comment]
> What I'm missing though is that notifications on the mobile are cancelled when I read the messages using the web chat. Is that out of scope?

do you mean they are getting cleared or NOT cleared?

**Comment by dbrgn** [comment]
- When I read messages in the app, the app notifications are cleared. (Custom Android build, about 2 weeks old based on a tagged release)
- When I read messages in the browser, the app notifications are not cleared. This would require a new push notification to cancel the old notifications. (At least on Android, AFAIK it's not possible to delete notifications from a push handler on iOS.)

**Comment by kopurando** [comment]
same on app for iOS (latest version) and MM 4.6 bundled with GitLab. Using http://push-test.mattermost.com with TPMS. Mobile notifications are not cleared when reading messages on OSX /  Web client.

**Comment by bkarlson** [comment]
Still experiencing this issue on MM EE 4.9 (https://push.mattermost.com) with latest iOS app

**Comment by koxen** [comment]
@bkarlson @kopurando we've been digging into it since, the mobile app logic is OK but a server-side fix is underway in mattermost-server PR - hopefully it will make it into 4.10

**Comment by rnestler** [comment]
I experienced it also the other way around: I read a message on the phone, but it still showed up as new and unread on the Desktop client.

**Comment by lindy65** [comment]
@koxen - can you add a link for tracking purposes please?

> a server-side fix is underway in mattermost-server PR

**Comment by koxen** [comment]
@lindy65 https://github.com/mattermost/mattermost-server/pull/8477

**Comment by koxen** [comment]
fix has been merged. probably didn't make it into mattermost release yet though

**Comment by amyblais** [comment]
Hi all, closing this Issue since the PR and associated Jira ticket have been resolved and tested internally. The fix will be available in 5.4 release,
