### ISSUE TITLE
Screen rotation can not be locked on Android

### ISSUE THREAD

**Issue by hanyihong0324** [mattermost/mattermost-mobile#1039]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Screen rotation dose not obey system setting

#### Environment Information

- Device Name: Sony Xperia X Compact
- OS Version: Android 7.1.1
- Mattermost App Version: 1.3.0 (Build 57)
- Mattermost Server Version: 4.3.0

#### Steps to reproduce
1. Set screen to PORTRAIT mode and auto-rotation to OFF
2. Open Mattermost app, turn your phone to landscape

#### Expected behavior
The screen layout should obey the system setting (to be portrait only)

#### Observed behavior
The screen changes to landscape

![screenshot_20171019-152652](https://user-images.githubusercontent.com/17589280/31757131-9790099e-b4e2-11e7-95df-65f0c14a50f8.png)

![screenshot_20171019-152730](https://user-images.githubusercontent.com/17589280/31757132-97b5d5a2-b4e2-11e7-8025-f9e0744b8e66.png)

**Comment by hanyihong0324** [comment]
I think this issue is related to the Tablet Support feature introduced on version 1.3.

**Comment by Hanzei** [comment]
Duplicate of #1007. It should be fixed with #1008

**Comment by enahum** [comment]
Thanks @Hanzei I'm going to close this issue, feel free to re-open if needed
