### ISSUE TITLE
Android: App crash when accessing Notifications menu

### ISSUE THREAD

**Issue by eyew** [mattermost/mattermost-mobile#1045]
#### Summary
App crash when access the 'Mobile' sub-menu in Settings->Notifications.

#### Environment Information

- Device Name: Google Pixel
- OS Version: Android 8.0.0 (Build OPR3.170623.008)
- Mattermost App Version: 1.3.0
- Mattermost Server Version: 4.3

#### Steps to reproduce
Open Mattermost Android app, go to Settings->Notifications->Mobile -- app crashes at this point

#### Expected behavior
Expected behavior is the mobile notifications settings menu opening

#### Observed behavior
App crash with "Unexpected error occurred"

Stack trace:

Current User Id: w3ecghws13bb7krhngnkhc8kdo
Current Team Id: hryqjhogh3y97mz1byyb66em4y
Server Version: 4.3.0 (Build 4.3.0)
App Version: 1.3.0 (Build 57)
App Platform: android
Errors:
Date: Wed, 18 Oct 2017 22:07:16 GMT
Message: [React Intl] An `id` must be provided to format a message.
Stack trace:
o@index.android.bundle:627:276
x@index.android.bundle:671:4115
x@[native code]
value@index.android.bundle:988:1182
_renderValidatedComponentWithoutOwnerOrContext@index.android.bundle:452:15266
_renderValidatedComponent@index.android.bundle:452:15495
performInitialMount@index.android.bundle:452:9885
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
Me@index.android.bundle:451:13003
perform@index.android.bundle:452:3484
He@index.android.bundle:451:13166
perform@index.android.bundle:452:3484
batchedUpdates@index.android.bundle:452:18575
Ce@index.android.bundle:451:10516
renderComponent@index.android.bundle:452:17604
ra@index.android.bundle:452:29420
a@index.android.bundle:602:118
run@index.android.bundle:598:605
runApplication@index.android.bundle:598:2036
value@index.android.bundle:353:2986
index.android.bundle:353:285
value@index.android.bundle:353:2436
callFunctionReturnFlushedQueue@index.android.bundle:353:257

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by bj0rj0h** [comment]
[Possible duplicate](https://github.com/mattermost/mattermost-mobile/issues/1014)

**Comment by enahum** [comment]
This crash is fixed by https://github.com/mattermost/mattermost-mobile/pull/1020

the ticket referred by @bj0rj0h is actually another issue fixed by https://github.com/mattermost/mattermost-mobile/pull/1022

both will be available with the 1.4 version being release next month

**Comment by enahum** [comment]
also see #1052 going to close this issue,, feel free to re-open if needed
