### ISSUE TITLE
Unable to collapse or expand previews

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#1046]
#### Environment Information

- Mattermost App Version: 1.3.0
- Mattermost Server Version: 4.3.0

#### Steps to reproduce
Have collapsed set up in web client
Use the mobile client
See the system messages saying the previews are collapsed
Write `/collapse` in mobile client

#### Expected behavior
If previews are collapsed in web/desktop, they should be in mobile too
Writing `/collapse` or `/expand` should do the same thing as in web/desktop

#### Observed behavior
Previews are not collapsed in mobile client
Writing `/collapse` or `/expand` on mobile will actually post `/collapse` or `/expand` string in chat

**Comment by enahum** [comment]
Hi @licaon-kter this feature has not been implemented yet nor handling slash commands
