### ISSUE TITLE
No notifications on Andriod App

### ISSUE THREAD

**Issue by C5205568** [mattermost/mattermost-mobile#1052]
#### Summary
No notification received on Andriod App

#### Environment Information

- Device Name: One plus 5
- OS Version: Android Nougat
- Mattermost App Version: Latest
- Mattermost Server Version: Latest

#### Steps to reproduce
How can we reproduce the issue?
1. Ask someone to send a message and you will see no notification. Open mattermost and you will see new message.
2. Go to Settings - Notifications - Mobile Notifications. And the app crashes
![screenshot_20171021-194824](https://user-images.githubusercontent.com/25245204/31933158-efb28f70-b8c5-11e7-8f4b-ad98fb86709b.jpg)
![screenshot_20171021-194816](https://user-images.githubusercontent.com/25245204/31933159-efed236a-b8c5-11e7-89c2-ecfca3f807f5.jpg)

**Comment by kamilgrzegorczyk** [comment]
Same here

Error log:
`
Server Version: 4.3.0 (Build 4.3.0)
App Version: 1.3.0 (Build 57)
App Platform: android

Errors:
Date: Tue, 24 Oct 2017 13:34:28 GMT
Message: [React Intl] An `id` must be provided to format a message.
Stack trace:
o@index.android.bundle:627:276
x@index.android.bundle:671:4115
x@[native code]
value@index.android.bundle:988:1182
_renderValidatedComponentWithoutOwnerOrContext@index.android.bundle:452:15266
_renderValidatedComponent@index.android.bundle:452:15495
performInitialMount@index.android.bundle:452:9885
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
mountChildren@index.android.bundle:452:26288
initializeChildren@index.android.bundle:452:28045
mountComponent@index.android.bundle:452:28855
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
performInitialMount@index.android.bundle:452:10038
mountComponent@index.android.bundle:452:8938
mountComponent@index.android.bundle:452:1935
Me@index.android.bundle:451:13003
perform@index.android.bundle:452:3484
He@index.android.bundle:451:13166
perform@index.android.bundle:452:3484
batchedUpdates@index.android.bundle:452:18575
Ce@index.android.bundle:451:10516
renderComponent@index.android.bundle:452:17604
ra@index.android.bundle:452:29420
a@index.android.bundle:602:118
run@index.android.bundle:598:605
runApplication@index.android.bundle:598:2036
value@index.android.bundle:353:2986
index.android.bundle:353:285
value@index.android.bundle:353:2436
callFunctionReturnFlushedQueue@index.android.bundle:353:257
`

**Comment by kamilgrzegorczyk** [comment]
As a temporary workaround you can turn on mobile notifications in your account settings of DESKTOP app and it should be applied for mobile (works for me)

**Comment by enahum** [comment]
This issues have been resolved via #1030,  #1022 and #1020  and will be deployed with the 1.4 release

**Comment by devTomek** [comment]
There are no notification at all on any kind of smartphone

**Comment by enahum** [comment]
@devTomek do you have the push notification service enabled on the server?

**Comment by lfbrock** [comment]
@C5205568 - v1.4 is now released, I'm going to close this issue but if you see it happening still please re-open? 

@devTomek - if you're still seeing issues, please feel free to open a new issue with more details about your set up
