### ISSUE TITLE
v1.3.0 builds are crashing

### ISSUE THREAD

**Issue by syamgk** [mattermost/mattermost-mobile#1061]
#### Summary
Mobile version 1.3.0 is crashing while account login

#### Environment Information

- Device Name: LYF LS-4503
- OS Version: 5.1.1
- Mattermost App Version: 1.3.0
- Mattermost Server Version: 4.3.0

#### Steps to reproduce
How can we reproduce the issue?
I did the build using the below mentioned dockerfile 
https://github.com/syamgk/mm_builder/blob/master/Dockerfile
once the container is built, run it.
$ docker run -it <IMAGE ID> bash

inside the container 
```
# cd /opt/mattermost-mobile-1.2.0/
# make
# export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.144-0.b01.el7_4.x86_64/
# cd android/keystores/
# keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000
```
then,
1. verify/edit the variable names on android/app/build.gradle under signingConfigs code block

2. update the google-services.json file which got generated from firebase console at android/app/google-services.json

3. edit android/app/src/main/AndroidManifest.xml and change `gcmSenderId" android:value` to the Sender ID generated from firebase-console

4. edit assets/override/config.json and replace the url { "DefaultServerUrl": "http://xxxx.com" }
then go back to android directory and run 
```
# ./gradlew assembleRelease
```
#### Expected behavior
the login process should happen properly.

#### Observed behavior
Once the login page comes, entered the credentials and tap on login
then the app crashes and gets to the below screen
![error](https://user-images.githubusercontent.com/5830238/31983922-0fa30654-b97d-11e7-81f4-4529885f69fe.png)

**Comment by enahum** [comment]
Hi @syamgk 

I think your docker file is wrong, is trying to install the dependencies with npm instead of `yarn` and then how are you building the app? you need to make sure the react-native packager is running

**Comment by syamgk** [comment]
here in the doc it says install using npm 
https://github.com/mattermost/mattermost-mobile/blob/master/README.md#detailed-configuration

but after installing the dependencies using `yarn`
the app is working fine for me 

thanks a lot @enahum
