### ISSUE TITLE
Last word from line becomes first word in textbox

### ISSUE THREAD

**Issue by tareko** [mattermost/mattermost-mobile#1068]
Hello all,

#### Summary
The last word from a given line becomes the first word of the next line when trying to type in the textbox.

#### Environment Information

- Device Name: Samsung Galaxy S7 Edge
- OS Version: Android 7.0
- Mattermost App Version: 1.3
- Mattermost Server Version: 4.2.0

#### Steps to reproduce
Type messages as per usual. Hit 'send'. Type the next message.

#### Expected behavior
Only the typed text should be in subsequent messages. No words should be carried over.

#### Observed behavior
The last word of the previous line is carried over to the current line being typed. In this example, the word "can" is automatically prefixed to the next line after the message is sent while user "Helen" is typing the next word.

![UX bug](https://user-images.githubusercontent.com/1128840/32018576-4af6f826-b998-11e7-9b38-dfd4ac66b941.jpg)

#### Possible fixes
None proposed.

**Comment by avillat** [comment]
Having the same issue

**Comment by lfbrock** [comment]
Hi @tareko @avillat - does this happen every time you send a message, or only sometimes? 

We're trying to reproduce but haven't been able to so far

**Comment by tareko** [comment]
The user reports that it happens after a while of use, and continues until she restarts. Recently, the other thing that is starting to happen is the whole sentence being reproduced. However, this is only sometimes.

Please let me know if there's anything else we can do to help debug.

tarek : )

**Comment by lfbrock** [comment]
@tareko - Actually, can the user: 

1. Upgrade to the latest version (v1.4.0)
2. If the issue shows up again, go to the app settings > Report a problem, and copy any errors that show up there to this GitHub issue
3. Try App Settings > Advanced > Reset Cache, to see if the issue fixes itself after that

**Comment by tareko** [comment]
After approximately 24 hours of use with the 1.4.0 app, this issue is resolved for our users. Thank you. I will close, but would welcome others reopening if 1.4.0 does not solve it for them.
