### ISSUE TITLE
Improve Cold Start on Android 

### ISSUE THREAD

**Issue by divanikus** [mattermost/mattermost-mobile#1079]
I know it could sound harsh, but current MM apps on both Android and iOS performs like... Well, even on flagship devices they are slow, opening is slow, switching between channels is slow, typing is slow. Sometimes they just stuck at blank page and nothing happens without stopping and restarting app. React Native variant is better than the classic one, but still hardly passes "usable" line. Using current version is still too painful to withstand it, forcing most of our team to avoid it as much as possible. 

Even though we have a pretty solid experience with Desktop&Web clients, mobile apps are still pushing us back to Slack. 

Please consider making fully native apps or use something faster than React Native.

**Comment by minchenkov** [comment]
+1
React Native version on iOS works well only few days after install (1000+ messages per day using). Than becomes slower, slower and slower, hanging on any action.

**Comment by lfbrock** [comment]
Hi @divanikus @minchenkov 

Thanks for the feedback - we've actually been working really hard on performance in the React Native apps for the past month, and are hoping to have a new version released sometime next week that is faster. 

Would love to get feedback from you on the release candidate we have with the performance fixes to see if it's better or if you're still seeing issues - you can sign up to test it out here before we release it to the app store: https://github.com/mattermost/mattermost-mobile#testing

**Comment by divanikus** [comment]
Hi @lfbrock 

I have tested the Beta for a while. Well, cold start is still very slow. For example, I left my phone on the desk for several hours, later I have picked up it and see I have 3 mentions in MM. I tap the icon and wait for like 7-10 seconds until it draws the chat. In contrast if I tap WhatsApp or Telegram, they do appear immediately. 

The UI is more responsive than the current version, kind of like near native experience, but still sometimes lagging for 0.5-1 sec. Also I got one blank screen - white page and nothing happens until I close the app and restart it. 

Also switching between channels I got "No internet connection" message, but I was able to send messages and see them in the web client. Also got strange behaviour with sending messages. One of my messages stuck grayed and stayed so for 20 seconds or so. Must be somehow related with the "no internet connection" I got previously. But I didn't experienced such problems with Desktop client running in the same WiFi network.

I'm on Android 7.1, Sony Xperia XZ with latest firmware.

**Comment by enahum** [comment]
Hi @divanikus 

Indeed Android has an issue for cold start that is taking between 7-10 seconds and it looks like is has something to do with one of our dependencies, we will be looking into that for the 1.5 release which is scheduled by Dec 5th (that is the same reason why you see a white screen for the same amount of time when your app has been in the background for a while)

as for the No internet connection it might have been that for a short time you were actually disconnected or the connection was very slow or intermittent? that would be the reason why the post you sent was grayed out for a short period of time

**Comment by divanikus** [comment]
Hi @enahum 

As for No internet connection. I got this message during switching between channels. And it won't go away until I closed and reopened app. I was able to see updates and post new messages. I've tried to pull chat history to force update, but it was no go, message was still there.
As for grayed message, well, I can believe that I had a short disconnect.

**Comment by enahum** [comment]
@jarredwitt can you look into the "no internet connection" thing, looks like is a bug

**Comment by divanikus** [comment]
You should consider fixing long cold start and reopening ASAP, because I could say it is one of the most annoying things actually.

**Comment by lfbrock** [comment]
Renamed this issue to "Improve Cold Start on Android" since it seems to be the major remaining issue

**Comment by tareko** [comment]
Hello all. Members of our teams have also noticed the long cold-start times for the mobile app (especially android as more of us use that). For those of us who use MM as mobile-first, this is a particular problem. I understand December would have been a slow development month, however has any more progress been made on this issue?

Thank you!

**Comment by enahum** [comment]
We’ve been looking into this but it seems the issue has to do with the way react-native and rect-native-navigation bootstraps the app.

We are constantly looking for alternatives but if anyone has some experience with native development and want to help out with this that would be awesome

**Comment by tareko** [comment]
I am not a RN developer, so I understand that I have limited perspective. In doing some web searches, I don't see other apps taking as long as MM to boot, with many apps talking about 2s load times (MM on my Nexus 5X typically takes 6-7s to show a network load screen).

I looked [here](https://code.facebook.com/posts/895897210527114/dive-into-react-native-performance/) and saw that some devs use profiling as a main technique to identify slowdowns.

Considering that cold starts are the pain, is it feasible to keep the application running in background and/or start on boot? Or is this outside the control of the app?

Also, perhaps those of us with a bit of money within our orgs can create a joint bounty / fund for performance enhancement?

tarek : )

**Comment by dbrgn** [comment]
The long cold start times (5-10s) are also one of the main pain points for me.

**Comment by hmhealey** [comment]
FYI, we're working on this right now and hoping to have it added to the app for the next release. You can track this issue in more detail [here](https://mattermost.atlassian.net/browse/MM-10314)

**Comment by tareko** [comment]
Great to hear! This pain point is getting worse over time as it grates on more and more of our users... Thank you for working on this.

**Comment by amyblais** [comment]
The ticket linked above has been resolved and the PRs related to the improvement have been merged, so I will close off this issue for now
