### ISSUE TITLE
Android app crashes on screen splitting on Android 7

### ISSUE THREAD

**Issue by pokamest** [mattermost/mattermost-mobile#1097]
#### Environment Information

- Device Name: Nokia 6
- OS Version: Android 7.1.2
- Mattermost App Version: 1.3.0 build 57
- Mattermost Server Version: 4.3.0 build 4.3.1

#### Steps to reproduce
While in an app, hold down on the Recent Apps button. Screen will be split and app will freeze

**Comment by lfbrock** [comment]
Hi @pokamest - we just released v1.4.0 of the Android app which contained some fixes for Android app crashes, can you check and see if this issue reproduces on the new version?

**Comment by lindy65** [comment]
Hi @pokamest,

Could you upgrade to the [latest version](https://about.mattermost.com/download/#mattermostApps) and check whether this is still an issue for you?

**Comment by Hanzei** [comment]
This is still a problem with version 1.7.1

**Comment by koxen** [comment]
yes seems to me like an issue with react-native-navigation

**Comment by lindy65** [comment]
Thanks @Hanzei 

I've created [this ticket](https://mattermost.atlassian.net/browse/MM-10281) to track the issue.

**Comment by koxen** [comment]
I am not able to find anything interesting in logcat when it happens...but a funny fact is is that it won't crash if it's started initially in splitscreen mode

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the above-linked ticket.
