### ISSUE TITLE
App crashes when I go to settings->notifications->mobile

### ISSUE THREAD

**Issue by dmitriydementor** [mattermost/mattermost-mobile#1109]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

#### Environment Information

- Device Name: Asus Zenfone 2 ZE551ML
- OS Version: Android 6.0.1 Marshmallow
- Mattermost App Version: 1.4.0 build 63
- Mattermost Server Version: 4.3.0 

#### Steps to reproduce
How can we reproduce the issue?
1. Login via account
2. Open settings -> Notifications -> Mobile

#### Expected behavior
Describe your issue in detail.
App crashes

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
https://drive.google.com/file/d/1_01ago7lDCLRJs2HY5HBYAULdt2HMOxB/view?usp=sharing

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
Can you try this, give the app permission to access storage and try again.

Please let us know if that helps.

**Comment by dmitriydementor** [comment]
no, the app has full permissions but error keeps appearing

**Comment by enahum** [comment]
I'm trying to repro this on a Samsung J5 with an Android 6.0.1 but it looks like is working just fine for me.

Any chance that you can use logcat to see if you are able to get more info?

**Comment by dmitriydementor** [comment]
Here is the error from logcat:



Full trace:


11-09 15:30:55.720 5774-9097/?
E/io.sentry.android.event.helper.AndroidEventBuilderHelper: Error getting
Proguard UUIDs.

               java.io.FileNotFoundException: sentry-debug-meta.properties

                   at android.content.res.AssetManager.openAsset(Native
Method)

                   at
android.content.res.AssetManager.open(AssetManager.java:318)

                   at
android.content.res.AssetManager.open(AssetManager.java:292)

                   at
io.sentry.android.event.helper.AndroidEventBuilderHelper.getProGuardUuids(AndroidEventBuilderHelper.java:157)

                   at
io.sentry.android.event.helper.AndroidEventBuilderHelper.helpBuildingEvent(AndroidEventBuilderHelper.java:73)

                   at
io.sentry.RNSentryModule.buildEvent(RNSentryModule.java:274)

                   at
io.sentry.RNSentryModule.captureEvent(RNSentryModule.java:233)

                   at java.lang.reflect.Method.invoke(Native Method)

                   at
com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)

                   at
com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)

                   at
com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)

                   at android.os.Handler.handleCallback(Handler.java:739)

                   at android.os.Handler.dispatchMessage(Handler.java:95)

                   at
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)

                   at android.os.Looper.loop(Looper.java:148)

                   at
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)

                   at java.lang.Thread.run(Thread.java:818)​

**Comment by enahum** [comment]
@hmhealey thoughts on this?

**Comment by hmhealey** [comment]
Not sure. I found an old issue filed with Sentry about that file not being generated ([link](https://github.com/getsentry/react-native-sentry/issues/137)), but I'm not sure why it wouldn't exist here.

@dmitriydementor Where did you install the app from? Did you use the Play Store, one of the apks from here (and if so, was it the signed or the unsigned one?), or did you compile it yourself

**Comment by dmitriydementor** [comment]
I installed it from Play Market. Maybe I can check if this specific file
exists on my device?

**Comment by hmhealey** [comment]
I think the file is supposed to somewhere be in the apk, but I wasn't able to find where exactly. It wasn't in any of the apks that we have hosted on GitHub though. It's odd that we're still getting error reports from other users, so I'm not sure what the issue here would be. Are there any other errors showing up in Logcat around that time? Maybe that stack trace isn't actually the one causing the app to crash.

**Comment by Silvood** [comment]
Hello,
Same problem for me, but with different Hardware ^^
Environment Information
    Device Name: Sony XPeria XA1 G3112
    OS Version: Android 7.0
    Mattermost App Version: 1.4.0 build 63 (from google play)
    Mattermost Server Version: 4.3.1
    "Mattermost Edition Entreprise"
    Database: mysql

The error log of the app in the 2 screenshot (wasn't able to copy/paste on my phone)
![screenshot_20171115-162823](https://user-images.githubusercontent.com/5123279/32844345-6ebb84c6-ca22-11e7-93a1-6ae230be9dc6.png)
![screenshot_20171115-162829](https://user-images.githubusercontent.com/5123279/32844346-6ee2f97a-ca22-11e7-89d1-f43aaa03445e.png)

Will be happy when resolved, I can't stand the vibration of private messages ^^
thanks :)

**Comment by brs17** [comment]
I downloaded the app last night (tried both the beta and the normal version and had the above mentioned issue happen consistently. 

My specs:

Environment Information
Device Name: Nexus 5x
OS Version: Android 8.0
Mattermost App Version: 1.4.0 build 63 (from google play)
Mattermost Server Version: 4.0.0(Build 4.0.1)
Database: postgres

**Comment by Silvood** [comment]
Same as #1184 and #1166, I hope the team can investigate on this issue quickly as we are more and more to have this problem :)

**Comment by fantast7** [comment]
Same error message as user Silvood.
My mobile: HTC M7

**Comment by lfbrock** [comment]
Hi @fantast7 @Silvood @brs17 @dmitriydementor 

Sorry for the delay on this, we thought we had the issue fixed in v1.4.1 but it seems it didn't work for everyone. If you're still seeing the issue, would you be able to help us test out a beta build that has a new fix in it? 

You can sign up for beta testing following the instructions here: https://github.com/mattermost/mattermost-mobile#testing

And then just install the beta app and see if the notifications settings are working now.

**Comment by fantast7** [comment]
Hi,
I installed the beta app. Unfortunately the same error occurs.
Next I uninstalled both mattermost apps, restarted my HTC M7 with
Android 5 and installed the beta app again. Same thing, same message.
Sorry.
Cheers from Vienna, Austria
Am Mittwoch, den 29.11.2017, 15:24 +0000 schrieb Lindsay:

**Comment by enahum** [comment]
can we give this a try

in the webapp go to your notification settings to something different, and then try seeing if you can access that screen on the app.

Anyway we'll investigate further

**Comment by enahum** [comment]
also can you try and check if the app has permissions to storage?

![screenshot_1511976507](https://user-images.githubusercontent.com/6757047/33389441-988d61b2-d511-11e7-87a3-ef2d7e277207.png)

**Comment by fantast7** [comment]
The screen on Android 5 looks different, but it does/should have access to storage.

**Comment by enahum** [comment]
Guys I have a custom build and I'm looking for anyone who is having this issue if you can test an apk to confirm that the fix works

anyone?

**Comment by fantast7** [comment]
I should be able to install it.

**Comment by enahum** [comment]
cool @fantast7 I'll be sending you a link in about 20 mins

**Comment by enahum** [comment]
@fantast7 can you try this apk and see if the issue is resolved, I'm not 100% as I had to guess what the issue might be as I cannot reproduce it in my phone or using the android emulator.

can't wait to hear back good news ;)

[Mattermost-beta.apk.zip](https://github.com/mattermost/mattermost-mobile/files/1515199/Mattermost-beta.apk.zip)

**Comment by fantast7** [comment]
works!!! Sent a test notification. No crash anymore.

**Comment by enahum** [comment]
awesome, great to hear, I've just submitted a PR to included it for the next scheduled release

**Comment by Silvood** [comment]
Yeah, the apk works for me too :) thanks @enahum (note: nothing else you suggested had work ^^)
Did you find the real origin of this problem? (I'm always curious ^^)

**Comment by enahum** [comment]
@silvood I had to guess what it was and made some code changes you can take a look at the PR to see what was changed and it all worked
