### ISSUE TITLE
Mattermost 1.4.0 on iOS 11.1 not showing channels and crashing.

### ISSUE THREAD

**Issue by robbyandrews** [mattermost/mattermost-mobile#1123]
#### Summary
After updating to 1.4.0,  the Mattermost Application on iOS hangs with a spinning loading icon, preventing any navigation or ability to chat.  Push notifications still come through, but there's no ability to reply.

#### Environment Information

- Device Name: iPhone 7 Plus
- OS Version: iOS 11.1
- Mattermost App Version:  1.4.0
- Mattermost Server Version: 4.2.0

#### Steps to reproduce
On iOS 11.1, install the 1.4.0 version of Mattermost, enter server information, login information, and then proceed to login. 

#### Expected behavior
Application should show the channel summary and normal home screen for Mattermost
#### Observed behavior
No ability to configure or use the app.
![image](https://user-images.githubusercontent.com/33102078/32632905-39627d06-c55a-11e7-92d2-97018cc79796.png)

Then after a force close of the app, it will launch an error to relaunch, which then brings back to the spinning.  

![error](https://user-images.githubusercontent.com/33102078/32633088-fb092eb4-c55a-11e7-8fb0-0c84bf359d2d.png)

I've also deleted and reinstalled the app to no avail.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
@robbyandrews i left you a comment in the forum thread, let me know if that helps

**Comment by robbyandrews** [comment]
i replied, still not loading. let me know if you need any additional info.

**Comment by robbyandrews** [comment]
1.4.1 has fixed this issue.
