### ISSUE TITLE
Unable to download attached files from IOS 10.x

### ISSUE THREAD

**Issue by muirdok** [mattermost/mattermost-mobile#1126]
#### Summary
Subj. It works for Mattermost Classic  but doesn't work for 1.4.0

#### Environment Information

- Device Name: iphone 5c
- OS Version:  10.3.2
- Mattermost App Version: 1.4.0
- Mattermost Server Version: 4.3.0  (4.3.1)

#### Steps to reproduce
* Send any file (e,g. .docx)
* Open file frim app

#### Expected behavior
It opens preview\icon of file and "DOWNLOAD" button is presented

#### Observed behavior
It opens ONLY preview\icon of file but unable to open\download file

#### Possible fixes
Add download button

**Comment by lfbrock** [comment]
Hi @muirdok - what type of file was this for? 

I think on iOS we only support image files right now, although with iOS 11 we can look at adding it for additional file types. 

If there's a typical place to store files we could look at doing it for older iOS versions as well - where would you expect it to be downloaded to?

**Comment by muirdok** [comment]
Hi. IOS 11 has "special" storage for downloaded files. I calls "Files" :). Try to open any .PDF file for example even you have PDF reader installed
