### ISSUE TITLE
On iOS, it is impossible to copy a URL from a message.

### ISSUE THREAD

**Issue by clonezone** [mattermost/mattermost-mobile#1148]
#### Summary

There is no way to copy a URL from a message on iOS.

#### Environment Information

- Device Name: 
- OS Version: iOS 11.1.1
- Mattermost App Version: 1.4.0 (Build 63)
- Mattermost Server Version: 4.3.0 (Build 4.3.1)

#### Steps to reproduce

1. Post or view and existing message with a URL in it in the iOS client.
1. Touch and hold on the URL.

#### Expected behavior

The iOS share sheet should pop up.

#### Observed behavior

Message-level control menu pops up, instead, with "Flag", "Add Reaction", etc.

**Comment by lfbrock** [comment]
Hi @clonezone - we have this feature merged into master, it should be in the next release in a couple weeks!

https://github.com/mattermost/mattermost-mobile/pull/1069

**Comment by clonezone** [comment]
Not the ideal solution. The native share sheet should be used.

**Comment by lfbrock** [comment]
@clonezone - we're working on improving files next, and a part of that will be looking into adding the native share sheet.
