### ISSUE TITLE
Can't enter username on re-login due to form switching back to server selector

### ISSUE THREAD

**Issue by soletan** [mattermost/mattermost-mobile#1155]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Can't enter username on re-login due to form switching back to server selector

#### Environment Information

- Device Name:  Apple iPhone 6s Plus
- OS Version: iOS 11.0.x
- Mattermost App Version: 1.4.0
- Mattermost Server Version: 

#### Steps to reproduce
Cause session expiration for client requesting to re-login.

#### Expected behavior
Client shall properly ask for input of username and password waiting for the user to finish open input.

#### Observed behavior
After choosing the one and only Mattermost server used before the app was asking for username and password, but I've never completed entering mail address as user name for the form returned to server selector after a few seconds while typing. Even w/o typing the view returned to server selector.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by lfbrock** [comment]
Hi @soletan - we made some changes to the login screen on the latest app version (v1.5.1), can you let us know if you're still seeing this issue?

**Comment by soletan** [comment]
Hi, tried to reproduce the bug, but having problems w/ proper session timeout causing me to re-login.

# Set Session Timeout for Mobile Applications to 1.
# Logged out manually on iOS device.
# Logged in again.
# Reverted Session Timeout for Mobile Applications to previous value so other user's won't be bothered unnecessarily.
# Waited a whole day, then got the Push notification on session having expired. Opened mattermost app and was logged in instantly again. Maybe it was due to app still running but that doesn't seem okay when my session has expired actually.

So, couldn't reproduce the scenario I was encountering the bug in before and thus can't tell if it's fixed.

**Comment by lindy65** [comment]
This issue is fixed in the [latest version](https://about.mattermost.com/download/#mattermostApps).  Please feel free to open a new issue if the problem still exists after upgrading.
