### ISSUE TITLE
Mobile Notification Button causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ramonaerne** [mattermost/mattermost-mobile#1166]
#### Summary
Pressing on the button `Mobile` inside Settings/Notifications causes the app to crash 

#### Environment Information

- Device Name: Nexus 5x
- OS Version: Android 8.0.0
- Mattermost App Version: 1.4.0 (Build 63)
- Mattermost Server Version: 4.3.0 (Build 4.3.0)

#### Steps to reproduce
Click on Settings -> Notifications -> Mobile

#### Expected behavior
Button click should cause another settings view.

#### Observed behavior
App crashes with  `java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds: node has no children`
![screenshot_20171116-194914](https://user-images.githubusercontent.com/966318/32909702-7f6132cc-cb07-11e7-833e-4682b5c89f98.png)
![screenshot_20171116-194930](https://user-images.githubusercontent.com/966318/32909703-7f80e2b6-cb07-11e7-97a1-6b0918626b1e.png)

**Comment by danleepw** [comment]
I am having the same issue in 

App Version: 1.4.1 (Build 64)
Server Version: 4.2.0 (4.2.1)

**Comment by Silvood** [comment]
Same as #1109 and #1184, I hope the team can investigate on this issue quickly as we are more and more to have this problem :)

**Comment by enahum** [comment]
closed via #1233
