### ISSUE TITLE
Clicking on attachments does nothing...

### ISSUE THREAD

**Issue by Patriccarver** [mattermost/mattermost-mobile#1168]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
I'm noticing when I'm using Mattermost on iPhone, if Danielle sends a Word file or a PDF file, I can't launch or open the Word doc or PDF file. This is pretty limiting.

#### Environment Information

- Device Name: Iphone 5SE
- OS Version: 11
- Mattermost App Version: Most recent
- Mattermost Server Version: unknown

#### Steps to reproduce
Try to open an attachment from a mattermost chat

#### Expected behavior
The attachment should open in the default handler for that file type.

#### Observed behavior
Nothing happens, no errors or anything.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by lfbrock** [comment]
Hi @Patriccarver - we're working on adding previews for other file types, and will also be looking into adding sharing files to other apps, and downloading files to iOS devices (download is already supported on Android). 

Pull request is here with the start of the work: https://github.com/mattermost/mattermost-mobile/pull/1170
