### ISSUE TITLE
Screen to switch teams

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#117]
Add the option to switch teams to the main menu (ticket for main menu is https://github.com/mattermost/mattermost-mobile/issues/55).

When clicked, it should open a simple screen to select teams from. 

Example screenshot from existing apps for reference: 

<img width="346" alt="screenshot 2016-12-09 17 23 46" src="https://cloud.githubusercontent.com/assets/9354841/21066552/22808796-be34-11e6-9538-f7d0ee2d53c5.png">

**Comment by thomchop** [comment]
Implemented by #139
