### ISSUE TITLE
App crashes when navigate to Settings > Notifications > Mobile

### ISSUE THREAD

**Issue by zakatsv** [mattermost/mattermost-mobile#1184]
#### Summary
App crashes when navigate to Settings > Notifications > Mobile

#### Environment Information

- Device Name: 
- OS Version: Nexus 5
- Mattermost App Version: 1.4.1 build 64
- Mattermost Server Version: 4.3.0 build 4.3.1

#### Steps to reproduce
Navigate to Settings > Notifications > Mobile

#### Expected behavior
I expected to find settings menu to turn off vibration for notifications on mobile phone

#### Observed behavior
When I navigate to Settings > Notifications > Mobile, an unexpected error pops up and a prompt to restart the app appears.

**Comment by Silvood** [comment]
Same as #1109 and #1166, I hope the team can investigate on this issue quickly as we are more and more to have this problem :)

**Comment by enahum** [comment]
Closed via #1233
