### ISSUE TITLE
integration w habit tracker

### ISSUE THREAD

**Issue by bobavery** [mattermost/mattermost-mobile#1198]
I am looking to integrate a chat app with a habit tracker.  Any documentation or suggestions you can point me to?

Specifically would like users to be able see how people are doing on habits and communicate around it

**Comment by lfbrock** [comment]
Hi @bobavery - no suggestions, our developer documentation is available at the following links but we don't have anything around habit tracking.  
- https://api.mattermost.com/
- https://developers.mattermost.com/
- https://docs.mattermost.com/guides/developer.html
