### ISSUE TITLE
@mention autocomplete

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#120]

**Comment by lfbrock** [comment]
@asaadmahmood can you help with a mockup for this?

**Comment by jarredwitt** [comment]
![screen](https://cloud.githubusercontent.com/assets/5090577/22786048/93dc6714-ee9c-11e6-9609-f750c9f6e010.jpg)
![screenp](https://cloud.githubusercontent.com/assets/5090577/22786051/955d4ef0-ee9c-11e6-8a68-d17f731bc9e0.jpg)
