### ISSUE TITLE
support@exemple.com ?

### ISSUE THREAD

**Issue by mrleblanc101** [mattermost/mattermost-mobile#1204]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Replace the placeholder support email adresse with the real support email address of Mattermost or remove the feature from the app.

#### Environment Information

- Device Name: iPhone X
- OS Version: 11.2
- Mattermost App Version: 1.4.1
- Mattermost Server Version: 4.0.2

#### Steps to reproduce
Open the app
Tap settings
Tap report a problem
The email for has a placeholder email adresse that does not work (support@exemple.com)

**Comment by enahum** [comment]
This looks to me that the admin on your server set that email address as the feedback address in the server configuration

**Comment by mrleblanc101** [comment]
So the in-app button to report a problem is not to report a problem about the app ? But the report a problem about the mattermost server ? That seems very weird and confusing... I guess i’ll Just post my problem here or on uservoice and expect nothing to change.

**Comment by enahum** [comment]
Actually it is to report problems with the app to the server administrator if the admin changed the feedback email, if the feedback email used is the default then the email should go to feedback@mattermost.com, perhaps you should talk to your server admin about this :)

**Comment by lfbrock** [comment]
Going to close this issue, to summarize for anyone else running into this issue: 

The default feedback email address for servers is `feedback@mattermost.com`. System Administrators can choose to change that email if they would prefer the support and feedback requests go to them.
