### ISSUE TITLE
Push notifications on Android 

### ISSUE THREAD

**Issue by atkozhuharov** [mattermost/mattermost-mobile#1208]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Push notifcations are not working with the Android app built from source

#### Environment Information

- Device Name: Samsung S8
- OS Version: 7.0.1
- Mattermost App Version: Latest
- Mattermost Server Version: Latest

#### Expected behavior
I have a local Mattermost server and I built the Android app to test the push notifications. The app was built with the GCM ID from my Google project in the AndroidManifest.xml 

#### Observed behavior
I'm getting the following errors in the mattermost log on the server:
[EROR] Device push reported as error for UserId=mp8by7rewfrfxxfkh17sfub85h SessionId=dstu5uhq63dsdxmhxreikumqwa message=unknown transport error
[EROR] Device push reported as error for UserId=mp8by7rewfrfxxfkh17sfub85h SessionId=m14atoe8sjg5u8jub999tgbbpe message=unknown transport error
2017/11/27 17:57:53 EET] [EROR] Device push reported as error for UserId=mp8by7rewfrfxxfkh17sfub85h SessionId=k94sk38stbr1dfjj988tgjowko message=unknown transport error

From this error I can't tell if the problem is with the authentication with GCM or with the receiving end(the android app).

**Comment by enahum** [comment]
Dide you deploy your own mattermost-push-proxy and set you server to use that one?

**Comment by atkozhuharov** [comment]
@enahum - yes, the mattermost proxy is on the local server:
{
    "ListenAddress":":8066",
    "ThrottlePerSec":300,
    "ThrottleMemoryStoreSize":50000,
    "ThrottleVaryByHeader":"X-Forwarded-For",
    "EnableMetrics": false,
    "ApplePushSettings":[
        {
            "Type":"apple",
            "ApplePushUseDevelopment":false,
            "ApplePushCertPrivate":"/opt/mattermost-push-proxy/config/chat.pem",
            "ApplePushCertPassword":"",
            "ApplePushTopic":"***"
        },
        {
            "Type":"apple_rn",
            "ApplePushUseDevelopment":false,
            "ApplePushCertPrivate":"/opt/mattermost-push-proxy/config/chat.pem",
            "ApplePushCertPassword":"",
            "ApplePushTopic":"****"
        }
    ],
    "AndroidPushSettings":[
        {
            "Type":"android",
            "AndroidApiKey":"AIzaSy***"
        },
        {
            "Type":"android_rn",
            "AndroidApiKey":"AIzaSy***"
        }
    ]
}

**Comment by enahum** [comment]
and do you get the push notifications on iOS?

**Comment by atkozhuharov** [comment]
Nope, I don't get any push notifications (tried on with the stock iOS app).

**Comment by enahum** [comment]
@coreyhulen any ideas on this one?

**Comment by coreyhulen** [comment]
Not sure.  Android pushes are working for our version of the mobile app in the store.

What OS are you running the push proxy on?  What version of go did you compile the push proxy with?

Do you have the latest code from the repo?  The error should look something like "Failed to send GCM push ..."

**Comment by atkozhuharov** [comment]
Centos 7.4 - the push proxy and server are both on the same machine. 
As per the version of Go - I downloaded the archive from downloads.
Do I have to compile the source ?

**Comment by coreyhulen** [comment]
You shouldn't have too.  What version push proxy did you download because the logging message format looks old.  Could you try with the latest from https://github.com/mattermost/mattermost-push-proxy/releases/tag/v4.4

**Comment by atkozhuharov** [comment]
No luck - reinstalled the proxy and I'm still getting the errors. The first log was from mattermost server, here is from the proxy:
Nov 30 18:21:23 chat mattermost-push-proxy[1305]: 2017/11/30 18:21:23 INFO Sending android push notification for type=android_rn
Nov 30 18:21:23 chat mattermost-push-proxy[1305]: 2017/11/30 18:21:23 INFO Sending android push notification for type=android_rn
Nov 30 18:21:23 chat mattermost-push-proxy[1305]: 2017/11/30 18:21:23 INFO Sending android push notification for type=android_rn
Nov 30 18:21:23 chat mattermost-push-proxy[1305]: 2017/11/30 18:21:23 INFO Sending android push notification for type=android_rn
Nov 30 18:21:23 chat mattermost-push-proxy[1305]: 2017/11/30 18:21:23 ERROR Failed to send GCM push sid=e587r9ky4ffe5fiqmnqtfnbwtr did=fbxwW12wLDI:APA91bEMW_r8DXORJsK1zivcKOohLbkYVhBQLUMgjardl7HCtAVjLJYArM5aD1Tx5prDQ8-_NRG--1DGCfAngKhhQbNZ2a11IoS
Nov 30 18:21:23 chat mattermost-push-proxy[1305]: 2017/11/30 18:21:23 ERROR Failed to send GCM push sid=e587r9ky4ffe5fiqmnqtfnbwtr did=dWumsO1QdAs:APA91bHx0wO5Iy-gFMaXGd2yEET7uvzZ8pYB01ZwaRyLa3Vi7Qj0NjSymGBChVYZciLPRNIAkX6l8Z-C9A-j45M57vtvJQ5o99L
Nov 30 18:21:23 chat mattermost-push-proxy[1305]: 2017/11/30 18:21:23 ERROR Failed to send GCM push sid=e587r9ky4ffe5fiqmnqtfnbwtr did=ebIGVcvA0rE:APA91bHswwyLMBOgjwfMF249uVH9B9LXXelALYWNBtKCei_mGg3uDcTGj5FlKnBlssvhw6addhn6HCTczNaa5TH7V3nG7upmpXs
Nov 30 18:21:23 chat mattermost-push-proxy[1305]: 2017/11/30 18:21:23 ERROR Failed to send GCM push sid=e587r9ky4ffe5fiqmnqtfnbwtr did=dCd0pZZvz_g:APA91bHpd1WLyY9nclvNnsywK1x9jWNVhKqRS4YHaEy2OF5EHTPNYhbWjuCfvzAYuavbdkhQ1cxa8e9pZ-YQJ7DdYAzM79WNY-L
lines 682-754/754 (END)

**Comment by enahum** [comment]
one question, did you modify/update the `google-services.json` file inside `<project-dir>/android/app/` folder before compiling the apps, right?

**Comment by atkozhuharov** [comment]
I replaced just the key. How should I proceed - register a whole new app here(https://developers.google.com/mobile/) and replace the entire google-service.json ?

**Comment by enahum** [comment]
you should register the app here https://console.firebase.google.com/ and then replace the entire `google-services.json` file, that should do it

**Comment by atkozhuharov** [comment]
I registered the app and added my new google-services.json. Now building fails like this:
error: bundling failed: NotFoundError: Cannot find entry file index.js in any of the roots: ["/home/user/mattermost-mobile"]
    at DependencyGraph._getAbsolutePath (/home/user/mattermost-mobile/node_modules/metro-bundler/src/node-haste/DependencyGraph.js:305:11)
    at DependencyGraph.getDependencies (/home/user/mattermost-mobile/node_modules/metro-bundler/src/node-haste/DependencyGraph.js:283:4236)
    at Resolver.getDependencies (/home/user/mattermost-mobile/node_modules/metro-bundler/src/Resolver/index.js:129:5)
    at /home/user/mattermost-mobile/node_modules/metro-bundler/src/Bundler/index.js:642:39
    at Generator.next (<anonymous>)
    at step (/home/user/mattermost-mobile/node_modules/metro-bundler/src/Bundler/index.js:13:1336)
    at /home/user/mattermost-mobile/node_modules/metro-bundler/src/Bundler/index.js:13:1496
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
I deleted the whole thing, installed all dependencies from scratch with pre-run(only complains about cocoapods), but to no avail. Any ideas?

**Comment by enahum** [comment]
are you building from master?

try the following:
* make clean
* make pre-run
* build you app the way you are doing it

**Comment by enahum** [comment]
Hi @atkozhuharov  can I ask you to please join our [Mattermost pre-release server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and then join the channel [Native Mobile Apps](https://pre-release.mattermost.com/core/channels/native-mobile-apps) so we can talk about this in a more dynamic form as I really want to understand what is going on and how to solve it.

Thanks

**Comment by enahum** [comment]
Hi @atkozhuharov did you ended up fixing this?

can you share your feedback on how you solved it so others can find it?

and please once you do feel free to close the issue ;)

**Comment by atkozhuharov** [comment]
@enahum - yes the issue was resolved and thanks a million for your help. Here is some guidance for future reference:
First of all - the contribute guide has a reference on how to set up your machine for building the apps.
1) Make sure to register your app in Google - https://developers.google.com/mobile/add. You will have to name the app for example com.somename.mattermost
2) After the registration download the google-services.json and replace the one from the repo
3) Add the project ID from the json file to the AndroidManifest.xml (gcmSenderId value) 
4) Create a new directory structure in mattermost-mobile/android/app/src/main/java/com/ - in the example case it will be mattermost-mobile/android/app/src/main/java/com/somename/mattermost/
5) Move all the .java files from mattermost-mobile/android/app/src/main/java/com/mattermost/rnbeta to the new directory
6) Change the package name in each .java file you moved to the new package name

With this it should be ready to take off.
