### ISSUE TITLE
Non-standard vibration pattern

### ISSUE THREAD

**Issue by alexrashed** [mattermost/mattermost-mobile#1216]
#### Summary
The vibration pattern for Android push notifications is unusual and distracting / non-standard.

#### Environment Information
- Device Name: Nexus 5X
- OS Version: 8.0.0
- Mattermost App Version: 
- Mattermost Server Version: 4.4.1

#### Steps to reproduce
- Enable notifications with vibrations
- Trigger a notification on your Android device

#### Expected behavior
The vibration on push notifications should just use the default vibration pattern.

#### Possible fixes
I guess the vibration pattern is set here: [CustomPushNotification.java#L269](https://github.com/mattermost/mattermost-mobile/blob/master/android/app/src/main/java/com/mattermost/rnbeta/CustomPushNotification.java#L269)
Maybe useful Android SDK docu: [Notification.html#DEFAULT_VIBRATE](https://developer.android.com/reference/android/app/Notification.html#DEFAULT_VIBRATE)

**Comment by enahum** [comment]
Hi @alexrashed are you willing to make a PR for that?

**Comment by alexrashed** [comment]
I don't have an Android toolchain set up, so I could look into it next week.

**Comment by enahum** [comment]
Thanks @alexrashed that'll be highly appreciate it

**Comment by enahum** [comment]
your PR has been merged
