### ISSUE TITLE
Beta IOS signup isn't working for me

### ISSUE THREAD

**Issue by sadsfae** [mattermost/mattermost-mobile#1245]
I am reporting an issue with the Heroku-hosted IOS MatterMost mobile beta signup webapp.

#### Summary

When hitting submit on the [IOS beta signup](https://mattermost-fastlane.herokuapp.com/) I get the following error:

```
Something went wrong, please contact the application owner: <?xml version="1.0" encoding="UTF-8"?> <String>There is no route for the path 'user/internalTesters/1256258630/'.</String>
```

Issue in one concise sentence.

#### Environment Information

- Device Name: Firefox 57 and Chrome on Linux
- OS Version: Fedora 26
- Mattermost App Version: N/A
- Mattermost Server Version: N/A

#### Steps to reproduce

Fill out the form, press submit.

#### Expected behavior
Describe your issue in detail.

#### Observed behavior

![screenshot_2017-12-02_03-42-56](https://user-images.githubusercontent.com/3940978/33511482-3b257966-d713-11e7-9a77-c1280c8d4ffd.png)

**Comment by enahum** [comment]
Hi @sadsfae I've updated the beta signup page, can you please try again and let us know if the issue has been resolved?

**Comment by sadsfae** [comment]
@enahum thanks I'm all sorted now, works for me.
