### ISSUE TITLE
New IOS client (1.4.1) sends malformed Upgrade Origin for Websocket

### ISSUE THREAD

**Issue by alecisec** [mattermost/mattermost-mobile#1263]
Android is unaffected (both Classic and new client) and IOS Classic client works fine, however the new IOS client 1.4.1 sends an incorrect Origin during the websocket upgrade request.

if Site URL on the server is set to 'https://blah.com' it will reject an upgrade request from new IOS client as the client sets the upgrade origin to 'wss://blah.com:443' 

a workaround is to set a CORS entry for 'wss://blah.com:443' 

result is the client constantly displays 'connecting....' bar and the System Console on the mattermost server will show the error -

[2017/12/05 04:27:01 UTC] [EROR] websocket connect err: websocket: 'Origin' header value not allowed
[2017/12/05 04:27:01 UTC] [EROR] /api/v4/websocket:connect code=500 rid=oyztka5smbrkbe1gp77uinjjsw uid=68hoc9ne7bdrdehpyono5pqrra ip=48.148.11.232 Failed to upgrade websocket connection [details: ]

**Comment by enahum** [comment]
Wondering if the problem is the `http://blah.com` instead of https

Looks to me that the origin set in the websocket for an https url is correct.

**Comment by alecisec** [comment]
I used Burp suite to MitM the iPhone traffic and could see the origin in the GET request

**Comment by enahum** [comment]
have you tried setting your siteURL with https?

**Comment by alecisec** [comment]
It is, my post has a typo, fixed now.

**Comment by enahum** [comment]
that's weird then cause is doing exactly what I expect, and that is working just fine with any other server out there, perhaps @hmhealey or @jarredwitt can pitch in cause I can't really say what might be going wrong here

**Comment by billybob2017** [comment]
get this man a mattermost coffee mug @alecisec @it33

**Comment by alecisec** [comment]
I've capped a couple of GET requests here, the top is from the IOS app and the bottom from Firefox (desktop) https://i.imgur.com/xrvGyhQ.png
