### ISSUE TITLE
[Help Wanted] Preview text files 

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#1265]
Jira ticket: https://mattermost.atlassian.net/browse/RN-528

We currently support viewing most file types in the app (video, word docs, PDFs, etc), but we still need to add support for previewing text files. 

The expected behaviour should be similar to other files: 
- Tapping on the file thumbnail downloads the file
- The file opens in the previewer so it can be viewed

For text files, the previewer can look similar to the code block preview.

**Comment by gajananpp** [comment]
working on this
