### ISSUE TITLE
[Help Wanted] Add text to the "Report a Problem" email 

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#1267]
Jira ticket: https://mattermost.atlassian.net/browse/RN-247

Currently the "Report a Problem" email only contains information about the errors and app version. Many people just send the email without adding a description of the problem. 

Proposed Change: Add help text at the beginning of the email saying "Please share a description of the problem:". Follow the new text with a few blank lines, and then show the information about app version and errors.

**Comment by cpanato** [comment]
I guess we can close this ticket
