### ISSUE TITLE
[Help Wanted] Improve the animation on the "Jump to..." channel screen 

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#1268]
Jira ticket: https://mattermost.atlassian.net/browse/RN-510

Repro: 
1. Open the channel sidebar 
2. Tap the search box saying "Jump to..." 

Observed: The animation as the sidebar expands is not very smooth (see video in Jira ticket)

Expected: The animation should be smoother

**Comment by enahum** [comment]
fixed
