### ISSUE TITLE
[Help Wanted] Improve emoji autocomplete filtering

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#1269]
Steps to reproduce:
1. Login to RN app
2. Open a channel
3. In the text input box start typing the name of a unique emoji, for example`:1st_pla`

Observed: Shows the emoji for `:1st_place`, but also shows other results that do not match the search text.

Expected: Only the results that match the emoji name appear in the results list.

**Comment by ebouJ** [comment]
I could not reproduce this. Is it fix?

**Comment by enahum** [comment]
this is fixed.

thanks
