### ISSUE TITLE
Allow sharing of images/videos directly from gallery

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-mobile#1277]
#### Summary
Would be nice to have the ability to share images/videos directly from the gallery.

#### Environment Information

Android 7.1.1

#### Steps to reproduce
Try sharing an image from your phones gallery and Mattermost won't appear as a destination to send images to (like you can share into Telegram etc)

#### Expected behavior

Mattermost should appear as a destination to which an image or video can be sent to.

**Comment by enahum** [comment]
This is planned for the 1.6 release

**Comment by arjitc** [comment]
Perfect! Thanks. I'll close this issue now 👍
