### ISSUE TITLE
[Help Wanted] Add a "+" button to make it easy to add Emoji Reactions

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#1293]
Jira ticket: https://mattermost.atlassian.net/browse/RN-576

Description: 

When a post has existing emoji reactions, add a "+" button to the end of the list of emoji reactions.
When tapped, it should open the emoji picker so people can easily select an emoji to add.

<img width="99" alt="screenshot 2017-12-11 15 22 41" src="https://user-images.githubusercontent.com/9354841/33852097-2bd706ca-de87-11e7-9944-312cb19643de.png">

**Comment by cpanato** [comment]
working on this

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/mattermost-mobile/pull/1455
