### ISSUE TITLE
Cannot connect to server on mobile. 

### ISSUE THREAD

**Issue by Neusaric** [mattermost/mattermost-mobile#1294]
**Environment Information**

- Device Name: LG Stylo 3
- OS Version: Android 7.0
- Mattermost App Version: 1.5.1
- Mattermost Server Version: 4.3.0 (Build 4.3.1)

**Steps to reproduce**
Unable to reproduce. Only one occurrence. 

**Expected behavior**   
When I input the server address it throw an error: "Cannot connect to the server. Please check your server URL and internet connection." The URL is correct, the internet is fine. This issue is only happening to me. The server admin and I have tried various troubleshooting step but nothing has worked. I have reinstalled the app. I have cleared all data related to the app and reinstalled it. ~~I have tried the beta app. i have tried the Mattermost Classic app~~. I can, however, connect to the prerelease mattermost server.

**Observed behavior**
Here is a screencap of the error: https://i.imgur.com/nUWSKpI.png

**Comment by Neusaric** [comment]
I just tried the Mattermost classic app again, it appears to work.

**Comment by Darkman** [comment]
I'm the admin for the server in question. I've checked all the logs I can think of and haven't been able to find any clues as to why @Neusaric can not connect.

Other people including myself seem to be able to connect just fine, though a different person is getting "Invalid or expired session" when trying to log in with the current and beta app, though the classic app also works fine for the other person.

I can provide any redacted configs for nginx and mattermost if requested.

**Comment by enahum** [comment]
can you please check your SSL certificate with ssllabs.com to see if you have any issues with the certificate, it is known to have this kind of behavior.

**Comment by Darkman** [comment]
ssllabs.com gave an A+ with the only yellow property being DNS CAA = No.
The only simulated handshakes that failed were:

- Android 2.3.7
- IE 8 / XP
- Java 6u45
- Java 7u25

**Comment by enahum** [comment]
Could you share you server url?

**Comment by Darkman** [comment]
https://chat.darkman.io

**Comment by enahum** [comment]
I just tried with a Nexus 5 running Android 7.1.1 and I can connect just fine

![screenshot_1513115769](https://user-images.githubusercontent.com/6757047/33910647-3bad347e-df6e-11e7-98bb-aa966270eeb9.png)

**Comment by Darkman** [comment]
Any other ideas why the classic app would work for him but not the current/beta?

**Comment by enahum** [comment]
does he have a custom ROM?
I just tried on an Android 6.0.1 Samsung J5 and it also works just fine.

**Comment by Darkman** [comment]
No custom ROM. I thought it might be an IPv6 thing since my server doesn't support it and he was getting an IPv6, but he tried connecting through a VPN and no luck either.

**Comment by rid3re** [comment]
I have the same issue.

Device: Samsung GT-I9300
OS: LineageOS
Android: 7.1.2
Mattermost App: 1.5.1
Mattermost Server: 4.4.0 (Build 4.4.5)

**Comment by Neusaric** [comment]
You know, thinking about it, it might be a custom ROM. It's a Virgin Mobile phone, So it they might have done something.

**Comment by enahum** [comment]
Yeah looks like a custom ROM thing, cause with stack ROMs everything seems to run fine :S I have no ideas

@hmhealey or @jarredwitt thoughts?

**Comment by Neusaric** [comment]
For clarity, When @Darkman said "No custom ROM. I thought it might be an IPv6 thing since my server doesn't support it and he was getting an IPv6, but he tried connecting through a VPN and no luck either." he was referring to me.

Also, I really don't know if Virgin changed anything buy I've heard that the prepaid phone companies do.

**Comment by Darkman** [comment]
Coincidentally, we have another friend that just tried to connect to the server and got the same error with the same type of phone (LG Stylo 3). Is there any other debugging we could try to narrow this down as to why the type of phone would be causing an issue?

**Comment by Darkman** [comment]
Is there a chance this could be an issue with the SSL ciphers I have set in NGINX?
I currently have this:
`ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";`

Could that be too strict? @Neusaric was able to connect to the prerelease mattermost server with the app, just not mine.

**Comment by Darkman** [comment]
@enahum I've finally been able to narrow down the setting that is causing this.

It's the ssl_ecdh_curve parameter in nginx that I currently have set to:
`ssl_ecdh_curve secp384r1;`

**Comment by enahum** [comment]
That is great to hear, I don’t have much knowledge about ssl curves, but this seem like a good candidate to add in our trobleshooting section, mind making a PR to the docs repo?
