### ISSUE TITLE
Announcement Banner isn't displayed on mobile

### ISSUE THREAD

**Issue by torgeirl** [mattermost/mattermost-mobile#1296]
#### Summary
Announcement banner isn't displayed in mobile client.

#### Environment Information
- Device Name: Sony Xperia Z-something
- OS Version: Android 7.1.1
- Mattermost App Version: 1.5.1
- Mattermost Server Version: 4.4.x

#### Steps to reproduce
Set an announcement banner (System Console > Policy; requires E10 or higher) the next time you're planning to take down the server for maintenance (1+ time a month), and look after indications for that the service is going down in your mobile app (hint: there isn't any).

#### Expected behavior
Some banner, popup or anything in the mobile client with the content of the announcement banner.

#### Observed behavior
None.

**Comment by lfbrock** [comment]
Thanks @torgeirl, created a ticket here to support the announcement banner: https://mattermost.atlassian.net/browse/RN-579
