### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by MamoulianDelacroix** [mattermost/mattermost-mobile#1297]
👋 hello together,
I'm quite new in app-development.
I have a sticky problem compiling the mattermost-mobile-app and sadly I can't find a clue what's going wrong.
I download the source files via git.
cd into 'mattermost-mobile' and execute 'npm install'. After that I cd into 'android' and execute './gradlew assembleRelease ' to get an apk-File.
Sadly I get the following error
`15:45:27.243 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
15:45:27.245 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command '/home/fries/Android/Sdk/build-tools/23.0.1/aapt'.
15:45:27.248 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
15:45:27.248 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/home/fries/Android/Sdk/build-tools/23.0.1/aapt'' finished with exit value -1 (state: FAILED)
15:45:27.250 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':jail-monkey:processReleaseResources'
15:45:27.250 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :jail-monkey:processReleaseResources FAILED
15:45:27.250 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :jail-monkey:processReleaseResources (Thread[main,5,main]) completed. Took 0.058 secs.
15:45:27.251 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 2.184 secs, idle: 0.006 secs
15:45:27.265 [ERROR] [org.gradle.BuildExceptionReporter]
15:45:27.267 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:45:27.267 [ERROR] [org.gradle.BuildExceptionReporter]
15:45:27.267 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:45:27.267 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':jail-monkey:processReleaseResources'.
15:45:27.267 [ERROR] [org.gradle.BuildExceptionReporter] > com.android.ide.common.process.ProcessException: Failed to execute aapt
15:45:27.267 [ERROR] [org.gradle.BuildExceptionReporter]
15:45:27.267 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
15:45:27.267 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
15:45:27.267 [LIFECYCLE] [org.gradle.BuildResultLogger]
15:45:27.267 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
`

**Comment by enahum** [comment]
Hi @MamoulianDelacroix have you followed https://docs.mattermost.com/developer/mobile-developer-setup.html ?

**Comment by MamoulianDelacroix** [comment]
@enahum : Thanks a lot I will take a look at it.
But I'm a bit confused the instructions look quiet different from the one from here
https://github.com/mattermost/mattermost-mobile

**Comment by MamoulianDelacroix** [comment]
Hmm 🤔
Now I used your instructions and the error pictures has changed:
`fries@fries-virtual-machine:~$ git clone https://github.com/mattermost/mattermost-mobile.git
Cloning into 'mattermost-mobile'...
remote: Counting objects: 15039, done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 15039 (delta 73), reused 95 (delta 59), pack-reused 14894
Receiving objects: 100% (15039/15039), 11.45 MiB | 3.12 MiB/s, done.
Resolving deltas: 100% (9876/9876), done.
fries@fries-virtual-machine:~$ cd mattermost-mobile/
fries@fries-virtual-machine:~/mattermost-mobile$ make pre-run
* daemon not running; starting now at tcp:5037
* daemon started successfully
error: no devices/emulators found
Getting Javascript dependencies
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > commonmark-react-renderer@4.3.3" has incorrect peer dependency "commonmark@^0.27.0 || ^0.26.0 || ^0.24.0".
warning " > react-native@0.49.5" has incorrect peer dependency "react@16.0.0-beta.5".
warning " > react-native-doc-viewer@2.4.9" has incorrect peer dependency "react@16.0.0-alpha.6".
warning " > react-native-doc-viewer@2.4.9" has incorrect peer dependency "react-native@0.44.0".
warning " > react-native-svg@6.0.0" has incorrect peer dependency "react-native@>=0.50.0".
warning " > react-redux@5.0.6" has unmet peer dependency "redux@^2.0.0 || ^3.0.0".
warning " > redux-persist-transform-filter@0.0.16" has unmet peer dependency "redux-persist@^3.4.0 || ^4 || ^5".
warning " > redux-persist-transform-filter@0.0.16" has unmet peer dependency "redux@>3.0.0".
warning " > chai-enzyme@0.8.0" has unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x || 1.0.0-rc.1".
warning " > chai-enzyme@0.8.0" has incorrect peer dependency "enzyme@1.x || ^2.3.0".
warning " > chai-enzyme@0.8.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0".
warning " > chai-enzyme@0.8.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-0".
warning "chai-enzyme > react-element-to-jsx-string@5.0.7" has incorrect peer dependency "react@^0.14.8 || ^15.0.1".
warning "mocha-react-native > react-native-mock > react-addons-create-fragment@15.1.0" has incorrect peer dependency "react@^15.1.0".
warning "mocha-react-native > react-native-mock > react-addons-linked-state-mixin@15.1.0" has incorrect peer dependency "react@^15.1.0".
warning "mocha-react-native > react-native-mock > react-addons-perf@15.1.0" has incorrect peer dependency "react@^15.1.0".
warning "mocha-react-native > react-native-mock > react-addons-pure-render-mixin@15.1.0" has incorrect peer dependency "react@^15.1.0".
warning "mocha-react-native > react-native-mock > react-addons-test-utils@15.1.0" has incorrect peer dependency "react@^15.1.0".
warning "mocha-react-native > react-native-mock > react-addons-update@15.1.0" has incorrect peer dependency "react@^15.1.0".
warning " > react-addons-test-utils@15.6.2" has incorrect peer dependency "react-dom@^15.4.2".
warning "react-native-mock > react-dom@15.6.1" has incorrect peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
$ make post-install
make[1]: Verzeichnis „/home/fries/mattermost-mobile“ wird betreten
error: no devices/emulators found
PASS Inject RemoteDev server into React Native local server.
PASS Inject RemoteDev monitor into React Native debugger.
Cloning into 'PerformanceBezier'...
remote: Counting objects: 241, done.
remote: Total 241 (delta 0), reused 0 (delta 0), pack-reused 241
Receiving objects: 100% (241/241), 123.76 KiB | 443.00 KiB/s, done.
Resolving deltas: 100% (139/139), done.
yarn run v1.3.2
$ babel src --out-dir .
src/action_types/admin.js -> action_types/admin.js
src/action_types/alerts.js -> action_types/alerts.js
src/action_types/channels.js -> action_types/channels.js
src/action_types/emojis.js -> action_types/emojis.js
src/action_types/errors.js -> action_types/errors.js
src/action_types/files.js -> action_types/files.js
src/action_types/general.js -> action_types/general.js
src/action_types/index.js -> action_types/index.js
src/action_types/integrations.js -> action_types/integrations.js
src/action_types/jobs.js -> action_types/jobs.js
src/action_types/posts.js -> action_types/posts.js
src/action_types/preferences.js -> action_types/preferences.js
src/action_types/search.js -> action_types/search.js
src/action_types/teams.js -> action_types/teams.js
src/action_types/users.js -> action_types/users.js
src/actions/admin.js -> actions/admin.js
src/actions/alerts.js -> actions/alerts.js
src/actions/channels.js -> actions/channels.js
src/actions/emojis.js -> actions/emojis.js
src/actions/errors.js -> actions/errors.js
src/actions/files.js -> actions/files.js
src/actions/general.js -> actions/general.js
src/actions/helpers.js -> actions/helpers.js
src/actions/integrations.js -> actions/integrations.js
src/actions/jobs.js -> actions/jobs.js
src/actions/posts.js -> actions/posts.js
src/actions/preferences.js -> actions/preferences.js
src/actions/search.js -> actions/search.js
src/actions/teams.js -> actions/teams.js
src/actions/users.js -> actions/users.js
src/actions/websocket.js -> actions/websocket.js
src/client/client.js -> client/client.js
src/client/client4.js -> client/client4.js
src/client/fetch_etag.js -> client/fetch_etag.js
src/client/index.js -> client/index.js
src/client/websocket_client.js -> client/websocket_client.js
src/constants/alerts.js -> constants/alerts.js
src/constants/files.js -> constants/files.js
src/constants/general.js -> constants/general.js
src/constants/index.js -> constants/index.js
src/constants/posts.js -> constants/posts.js
src/constants/preferences.js -> constants/preferences.js
src/constants/request_status.js -> constants/request_status.js
src/constants/stats.js -> constants/stats.js
src/constants/teams.js -> constants/teams.js
src/constants/websocket.js -> constants/websocket.js
src/reducers/entities/admin.js -> reducers/entities/admin.js
src/reducers/entities/alerts.js -> reducers/entities/alerts.js
src/reducers/entities/channels.js -> reducers/entities/channels.js
src/reducers/entities/emojis.js -> reducers/entities/emojis.js
src/reducers/entities/files.js -> reducers/entities/files.js
src/reducers/entities/general.js -> reducers/entities/general.js
src/reducers/entities/index.js -> reducers/entities/index.js
src/reducers/entities/integrations.js -> reducers/entities/integrations.js
src/reducers/entities/jobs.js -> reducers/entities/jobs.js
src/reducers/entities/posts.js -> reducers/entities/posts.js
src/reducers/entities/preferences.js -> reducers/entities/preferences.js
src/reducers/entities/search.js -> reducers/entities/search.js
src/reducers/entities/teams.js -> reducers/entities/teams.js
src/reducers/entities/typing.js -> reducers/entities/typing.js
src/reducers/entities/users.js -> reducers/entities/users.js
src/reducers/errors/index.js -> reducers/errors/index.js
src/reducers/index.js -> reducers/index.js
src/reducers/requests/admin.js -> reducers/requests/admin.js
src/reducers/requests/channels.js -> reducers/requests/channels.js
src/reducers/requests/emojis.js -> reducers/requests/emojis.js
src/reducers/requests/files.js -> reducers/requests/files.js
src/reducers/requests/general.js -> reducers/requests/general.js
src/reducers/requests/helpers.js -> reducers/requests/helpers.js
src/reducers/requests/index.js -> reducers/requests/index.js
src/reducers/requests/integrations.js -> reducers/requests/integrations.js
src/reducers/requests/jobs.js -> reducers/requests/jobs.js
src/reducers/requests/posts.js -> reducers/requests/posts.js
src/reducers/requests/preferences.js -> reducers/requests/preferences.js
src/reducers/requests/search.js -> reducers/requests/search.js
src/reducers/requests/teams.js -> reducers/requests/teams.js
src/reducers/requests/users.js -> reducers/requests/users.js
src/selectors/entities/admin.js -> selectors/entities/admin.js
src/selectors/entities/alerts.js -> selectors/entities/alerts.js
src/selectors/entities/channels.js -> selectors/entities/channels.js
src/selectors/entities/emojis.js -> selectors/entities/emojis.js
src/selectors/entities/files.js -> selectors/entities/files.js
src/selectors/entities/general.js -> selectors/entities/general.js
src/selectors/entities/integrations.js -> selectors/entities/integrations.js
src/selectors/entities/jobs.js -> selectors/entities/jobs.js
src/selectors/entities/posts.js -> selectors/entities/posts.js
src/selectors/entities/preferences.js -> selectors/entities/preferences.js
src/selectors/entities/teams.js -> selectors/entities/teams.js
src/selectors/entities/typing.js -> selectors/entities/typing.js
src/selectors/entities/users.js -> selectors/entities/users.js
src/selectors/errors.js -> selectors/errors.js
src/store/configureStore.dev.js -> store/configureStore.dev.js
src/store/configureStore.prod.js -> store/configureStore.prod.js
src/store/helpers.js -> store/helpers.js
src/store/index.js -> store/index.js
src/store/initial_state.js -> store/initial_state.js
src/utils/channel_utils.js -> utils/channel_utils.js
src/utils/deep_freeze.js -> utils/deep_freeze.js
src/utils/delayed_action.js -> utils/delayed_action.js
src/utils/emoji_utils.js -> utils/emoji_utils.js
src/utils/event_emitter.js -> utils/event_emitter.js
src/utils/file_utils.js -> utils/file_utils.js
src/utils/helpers.js -> utils/helpers.js
src/utils/key_mirror.js -> utils/key_mirror.js
src/utils/post_utils.js -> utils/post_utils.js
src/utils/preference_utils.js -> utils/preference_utils.js
src/utils/team_utils.js -> utils/team_utils.js
src/utils/theme_utils.js -> utils/theme_utils.js
src/utils/user_utils.js -> utils/user_utils.js
Done in 10.57s.
make[1]: Verzeichnis „/home/fries/mattermost-mobile“ wird verlassen
Done in 37.51s.
Generating app assets
Copying assets/base/config.json from base to dist/assets/config.json
Copying assets/base/i18n/de.json from base to dist/assets/i18n/de.json
Copying assets/base/i18n/en.json from base to dist/assets/i18n/en.json
Copying assets/base/i18n/es.json from base to dist/assets/i18n/es.json
Copying assets/base/i18n/fr.json from base to dist/assets/i18n/fr.json
Copying assets/base/i18n/it.json from base to dist/assets/i18n/it.json
Copying assets/base/i18n/ja.json from base to dist/assets/i18n/ja.json
Copying assets/base/i18n/ko.json from base to dist/assets/i18n/ko.json
Copying assets/base/i18n/nl.json from base to dist/assets/i18n/nl.json
Copying assets/base/i18n/pl.json from base to dist/assets/i18n/pl.json
Copying assets/base/i18n/pt-BR.json from base to dist/assets/i18n/pt-BR.json
Copying assets/base/i18n/ru.json from base to dist/assets/i18n/ru.json
Copying assets/base/i18n/tr.json from base to dist/assets/i18n/tr.json
Copying assets/base/i18n/zh-CN.json from base to dist/assets/i18n/zh-CN.json
Copying assets/base/i18n/zh-TW.json from base to dist/assets/i18n/zh-TW.json
Copying assets/base/images/gitlab.png from base to dist/assets/images/gitlab.png
Copying assets/base/images/icon.png from base to dist/assets/images/icon.png
Copying assets/base/images/icons/audio.png from base to dist/assets/images/icons/audio.png
Copying assets/base/images/icons/code.png from base to dist/assets/images/icons/code.png
Copying assets/base/images/icons/excel.png from base to dist/assets/images/icons/excel.png
Copying assets/base/images/icons/generic.png from base to dist/assets/images/icons/generic.png
Copying assets/base/images/icons/image.png from base to dist/assets/images/icons/image.png
Copying assets/base/images/icons/patch.png from base to dist/assets/images/icons/patch.png
Copying assets/base/images/icons/pdf.png from base to dist/assets/images/icons/pdf.png
Copying assets/base/images/icons/ppt.png from base to dist/assets/images/icons/ppt.png
Copying assets/base/images/icons/video.png from base to dist/assets/images/icons/video.png
Copying assets/base/images/icons/webhook.jpg from base to dist/assets/images/icons/webhook.jpg
Copying assets/base/images/icons/word.png from base to dist/assets/images/icons/word.png
Copying assets/base/images/icons/youtube-play-icon.png from base to dist/assets/images/icons/youtube-play-icon.png
Copying assets/base/images/logo.png from base to dist/assets/images/logo.png
Copying assets/base/images/menu.png from base to dist/assets/images/menu.png
Copying assets/base/images/profile.jpg from base to dist/assets/images/profile.jpg
Copying assets/base/images/send.png from base to dist/assets/images/send.png
Copying assets/base/images/video_player/fullscreen@2x.png from base to dist/assets/images/video_player/fullscreen@2x.png
Copying assets/base/images/video_player/fullscreen@3x.png from base to dist/assets/images/video_player/fullscreen@3x.png
Copying assets/base/images/video_player/pause@2x.png from base to dist/assets/images/video_player/pause@2x.png
Copying assets/base/images/video_player/pause@3x.png from base to dist/assets/images/video_player/pause@3x.png
Copying assets/base/images/video_player/play@2x.png from base to dist/assets/images/video_player/play@2x.png
Copying assets/base/images/video_player/play@3x.png from base to dist/assets/images/video_player/play@3x.png
Copying assets/base/images/video_player/replay@2x.png from base to dist/assets/images/video_player/replay@2x.png
Copying assets/base/images/video_player/replay@3x.png from base to dist/assets/images/video_player/replay@3x.png
Copying assets/base/themes.json from base to dist/assets/themes.json
fries@fries-virtual-machine:~/mattermost-mobile$ make unsigned-android
error: no devices/emulators found
Checking for style guide compliance
Starting React Native packager server
Building unsigned Android app
/bin/sh: 1: bundle: not found
Makefile:215: die Regel für Ziel „do-unsigned-android“ scheiterte
make: *** [do-unsigned-android] Fehler 127
fries@fries-virtual-machine:~/mattermost-mobile$ [RemoteDev] Start server...
--------------------------------------------------------------------------------

   [Busy] Launching SocketCluster
   [Active] SocketCluster started
            Version: 6.8.0
            Environment: dev
            WebSocket engine: uws
            Port: 5678
            Master PID: 1657
            Worker count: 1
            Broker count: 1

--------------------------------------------------------------------------------
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /home/fries/mattermost-mobile


React packager ready.

Loading dependency graph, done.

fries@fries-virtual-machine:~/mattermost-mobile$

`
Do I need a virtual device in order to make a apk file?

Greetings

**Comment by enahum** [comment]
the documentation should have all the steps to build an apk, doesn't it?

**Comment by prateekpandey44** [comment]
@enahum 
this is the issue that I faced after the command :- 


make check-device-android


/bin/sh: 2: @echo: not found
/bin/sh: 3: @exit: not found
Makefile:116: recipe for target 'check-device-android' failed
make: *** [check-device-android] Error 127

**Comment by enahum** [comment]
@prateekpandey44 we’ve made some changes to our Makefile and this should not happen now when running `make check-device-android`

**Comment by mawen7** [comment]
@MamoulianDelacroix @enahum
```
apt-get install bundler

cd fastlane

bundle install
```

was necessary for me to fix "bundle: not found".


```
apt-get install lib32stdc++6 lib32z1
```

was necessary to get aapt working (from https://stackoverflow.com/a/28231767)

**Comment by lindy65** [comment]
[This documentation](https://docs.mattermost.com/developer/mobile-developer-setup.html#build-your-own-app-from-source) might help resolve your issue.
