### ISSUE TITLE
built iOS app keeps crashing

### ISSUE THREAD

**Issue by atkozhuharov** [mattermost/mattermost-mobile#1298]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

#### Environment Information

- Device Name: iPhone 5S
- OS Version: iOS 11.2
- Mattermost App Version: Latest
- Mattermost Server Version: Latest

#### Steps to reproduce
Fetched the latest version from the main branch and built the iOS app with my apple dev's certificate.
Steps:
1) Add account details to the project
2) Build it using the correct name
3) Add it via Xcode to the device
4) Try to launch it

#### Expected behavior
I built the iOS app for release and installed it via Xcode on the iphone. However it keeps crashing as it takes too long to load. Here is the crash report:
```Incident Identifier: DE0A8C76-A512-42B9-AB0F-6FD1C1B1B736\
CrashReporter Key:   651f1a91fa0a237e06a073767f54ae5fd08fd582\
Hardware Model:      iPhone6,2\
Process:             Mattermost [447]\
Path:                /private/var/containers/Bundle/Application/24320CFA-B21C-4A0A-9260-8F03A3904423/Mattermost.app/Mattermost\
Identifier:          com.com.chat.system\
Version:             74 (1.5.1)\
Code Type:           ARM-64 (Native)\
Role:                Foreground\
Parent Process:      launchd [1]\
Coalition:           com.com.chat.system [535]\
\
\
Date/Time:           2017-12-13 16:26:48.9179 +0200\
Launch Time:         2017-12-13 16:26:28.4115 +0200\
OS Version:          iPhone OS 11.2 (15C114)\
Baseband Version:    8.30.01\
Report Version:      104\
\
Exception Type:  EXC_CRASH (SIGKILL)\
Exception Codes: 0x0000000000000000, 0x0000000000000000\
Exception Note:  EXC_CORPSE_NOTIFY\
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d\
Termination Description: SPRINGBOARD, scene-create watchdog transgression: com.chaosgroup.chat.system exhausted real (wall clock) time allowance of 19.02 seconds |  | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 3.940 (user 3.940, system 0.000), 25% CPU", | "Elapsed application CPU time (seconds): 0.008, 0% CPU" | )\
Triggered by Thread:  0\
\
Filtered syslog:\
None found\
}
```

**Comment by enahum** [comment]
Have you followed the docs? https://docs.mattermost.com/developer/mobile-developer-setup.html

Also if you run it in debug mode you need to have the react native packager running somewhere reachable in your network

**Comment by atkozhuharov** [comment]
@enahum  - exactly does docs. It isn't for debug - I built the app for release with our cert and our apple account. The packaging part went fine, but after installing it locally on the iPhone the app won't start fast enough(it gets killed).

**Comment by enahum** [comment]
@atkozhuharov would you be able to join our [pre-release server](https://pre-release.mattermost.com)  and join the [Native Mobile Apps](https://pre-release.mattermost.com/core/channels/native-mobile-apps) channel so we can discuss there more fluently what are you doing, what's going on so we can find a way to fix it for you?

**Comment by atkozhuharov** [comment]
@enahum - thank you for your time and patience :)
Thanks to you I managed to build the app:
1) Prepare all necessary certs in developer.apple.com(in my case for ad-hoc in house testing)
2) Clean the build tree
3) Archive(not build for running) - this is for production release
4) Export the ipa and then install it via Xcode to the device.
