### ISSUE TITLE
Unable to resolve module `app/mattermost`

### ISSUE THREAD

**Issue by ayehuda** [mattermost/mattermost-mobile#1301]
#### Summary
[fatal][tid:main] Unable to resolve module `app/mattermost` from `/Users/avi/src/mattermost/mattermost-mobile-master/index.js`: Module does not exist in the module map
#### Environment Information

- Device Name: A6iPad
- OS Version: iOS 11.0.2
- Mattermost App Version: N/A 
- Mattermost Server Version: N/A

#### Steps to reproduce
npm install and run the resulting xcode project

#### Expected behavior
App should run as expected on iOS

**Comment by enahum** [comment]
@ayehuda are you following the [docs](https://docs.mattermost.com/developer/mobile-developer-setup.html) on how to set your environment, compile and run the app?

**Comment by enahum** [comment]
@ayehuda, were you able to solve it?

**Comment by lindy65** [comment]
I'll close this issue off here for now as there has been no feedback so we assume your issue is resolved.  Please feel free to open a new issue if you are still experiencing a problem and we'll gladly help troubleshoot!
