### ISSUE TITLE
Able to download mattermost-mobile apk from your site.

### ISSUE THREAD

**Issue by FelixDefrance** [mattermost/mattermost-mobile#1312]
Hi, 

Is it possible to provide a direct download link in "https://about.mattermost.com/download/" for Android based OS ?

Some people like me don't have google account..

Thanks for us.

**Comment by enahum** [comment]
you can download them from here https://github.com/mattermost/mattermost-mobile/releases

**Comment by FelixDefrance** [comment]
Sweet ! Maybe you could make a link in front of your site? It will be more easy.
