### ISSUE TITLE
List enumeration render difference between mobile and desktop app

### ISSUE THREAD

**Issue by th-joerger** [mattermost/mattermost-mobile#1338]
#### Summary
Enumerated lists are treated differently in Desktop app and mobile client

#### Environment Information

- Device Name: LG G4 - H815
- OS Version: 6.0.0
- Mattermost App Version: 1.5.1 (Build 74)
- Mattermost Server Version: 4.3.0 (Build 4.3.2)

#### Steps to reproduce
Post the following to a channel:
```
0. Zeroth point of enumeration
1. First point
2. Second point
```

#### Expected behavior
This should render the same in desktop app and mobile app.

#### Observed behavior
In mobile app, this renders to:
```
1. Zeroth point of enumeration
2. First point
3. Second point
```
In desktop app, this renders to:
```
0. Zeroth point of enumeration
1. First point
2. Second point
```

#### Possible fixes
No idea.

**Comment by hmhealey** [comment]
Hi @th-joerger,

The behaviour in the desktop app is correct. I've filed a ticket [here](https://mattermost.atlassian.net/browse/MM-10266) to go look at it for the mobile app

**Comment by hmhealey** [comment]
Hi @th-joerger, I'm not able to reproduce this issue on the latest beta version of the app available from the Play Store. I think it was fixed with https://github.com/mattermost/mattermost-mobile/pull/1304. Do you still see the issue if you upgrade your app to latest?

**Comment by th-joerger** [comment]
Hey @hmhealey, I can confirm it as fixed on my device (on which I discovered the bug) with Mattermost Android App version 1.7.1 (Build 92). Thank you!
