### ISSUE TITLE
Crash on resuming (Android 1.5.2 Build 77)

### ISSUE THREAD

**Issue by alecisec** [mattermost/mattermost-mobile#1355]
Upon resuming (from background) the app commonly stops responding and needs to reopen/relaunch.
This occurs on app version 1.5.2 (and earlier) on Stock-firmware Nexus 5x (Android 7.1.2, 8.0 and 8.1 tested)
Likely due to background process caching as this is a somewhat low-memory device (2GB RAM)

**Comment by enahum** [comment]
Hi @alecisec we have had reports like this, and we are currently investigating, but haven't been able to determined what is causing the problem.

you can follow this ticket to track the progress of the issue https://mattermost.atlassian.net/browse/ICU-592

**Comment by enahum** [comment]
Resolved by https://github.com/mattermost/mattermost-mobile/pull/1403 and it will be available for 1.7
