### ISSUE TITLE
No Github release nor Tag

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#1356]
1.5.2 - But it's already on https://play.google.com/store/apps/details?id=com.mattermost.rn

**Comment by licaon-kter** [comment]
Thanks

**Comment by licaon-kter** [comment]
And again for 1.10.0

**Comment by licaon-kter** [comment]
And for 1.11.0 again

Fixing #566 would help 👉👍

**Comment by amyblais** [comment]
@enahum

**Comment by enahum** [comment]
published

**Comment by enahum** [comment]
https://github.com/mattermost/mattermost-mobile/releases/tag/v1.11.0

**Comment by licaon-kter** [comment]
And for 1.18.0 ?

**Comment by amyblais** [comment]
@enahum?

**Comment by enahum** [comment]
release for 1.18 https://github.com/mattermost/mattermost-mobile/releases/tag/v1.18.0

**Comment by licaon-kter** [comment]
And again for 1.22.0...

**Comment by licaon-kter** [comment]
Yet again for 1.29.0...

**Comment by licaon-kter** [comment]
bump
