### ISSUE TITLE
Cannot paste images on input text box iOS

### ISSUE THREAD

**Issue by jcarrillo7** [mattermost/mattermost-mobile#1358]
#### Summary
Input text field for conversations does not accept pasting images/screenshots. 

#### Environment Information

- Device Name: iPhone X
- OS Version: iOS 11
- Mattermost App Version: 1.5.2
- Mattermost Server Version: 4.1

#### Steps to reproduce
Take screenshot
Edit screenshot in new iOS 11 screenshot UI
Copy screenshot to clipboard
Delete screenshot
Go to mattermost app
Attempt to paste screenshot from clipboard

#### Expected behavior
Expected to be able to paste screenshot without having to save it to my image library first. 

#### Observed behavior
Was not presented with the option to paste by iOS.

**Comment by enahum** [comment]
Hi @jcarrillo7 this functionality is not available in the app, are you interested in submitting a PR to add the functionality?

**Comment by lindy65** [comment]
Hi @jcarrillo7, we haven't received an update so we'll close this issue off for now.

Please feel free to add a feature request to our [forum](https://mattermost.uservoice.com/forums/306457-general?category_id=158667) where it can be upvoted by you and others.
