### ISSUE TITLE
Cannot 'make stop'

### ISSUE THREAD

**Issue by phuihock** [mattermost/mattermost-mobile#1359]
#### Summary
`make stop` does not stop RN packager server.

#### Environment Information

- Device Name: N/A
- OS Version: Ubuntu Linux 16.04
- Mattermost App Version: master
- Mattermost Server Version: N/A

#### Steps to reproduce
Run `make stop` command

#### Expected behavior
In Linux, `ps -e` used in `make stop` task produces only the process name without the argument. Should use `ps -ef`

#### Observed behavior
Running `make stop` always produce:
```
Stopping React Native packager server
No React Native packager server running
```

#### Possible fixes
https://github.com/mattermost/mattermost-mobile/blob/master/Makefile#L97
Possible fix:
```
-       @if [ $(shell ps -e | grep -i "cli.js start" | grep -civ grep) -eq 1 ]; then \
-               ps -e | grep -i "cli.js start" | grep -iv grep | awk '{print $$1}' | xargs kill -9; \
+       @if [ $(shell ps -ef | grep -i "cli.js start" | grep -civ grep) -eq 1 ]; then \
+               ps -ef | grep -i "cli.js start" | grep -iv grep | awk '{print $$2}' | xargs kill -9; \
```

**Comment by enahum** [comment]
@phuihock feel free to submit a PR ;)

**Comment by phuihock** [comment]
Done :)
