### ISSUE TITLE
Text sometimes cut at message's end

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-mobile#1367]
#### Summary
Text messages can be cut and thus not displayed entirely.

#### Environment Information

- Device Name: Galaxy A3 (2016)
- OS Version: Android 7.0
- Mattermost App Version: 1.5.2 (Build77)
- Mattermost Server Version: 4.6.0

#### Steps to reproduce
Write some messages.

#### Expected behavior
All text should be visible.

#### Observed behavior
The text can sometimes be cut, whether it's my own messages or someone else's :
**Example 1 with small text trimming (only the bottom of the letters)**
![image](https://user-images.githubusercontent.com/8834237/35218130-c17fcf66-ff6d-11e7-9fa1-146467a52ded.png)

**Example 2 with a complete line disappearing**
![image](https://user-images.githubusercontent.com/8834237/35218094-a3b6c098-ff6d-11e7-81e9-9d5bd9a8733d.png)
When I open the thread of the faulty message, there's also some trimming but much less :
![image](https://user-images.githubusercontent.com/8834237/35218032-7cddccb4-ff6d-11e7-8dd5-e44e1d2b2a61.png)

**Comment by enahum** [comment]
Hi @moussetc I've created a ticket to keep track of this https://mattermost.atlassian.net/browse/ICU-640

Thanks for the report

**Comment by stephenkiers** [comment]
Hey @moussetc I was wondering if you could send me your theme information? I am unable to reproduce and I would like to make my environment as close to yours as possible.

thanks

**Comment by moussetc** [comment]
Sure! Is the following JSON what you need?

`{"sidebarBg":"#262626","sidebarText":"#ffffff","sidebarUnreadText":"#ff0000","sidebarTextHoverBg":"#525252","sidebarTextActiveBorder":"#7e9949","sidebarTextActiveColor":"#ffffff","sidebarHeaderBg":"#363636","sidebarHeaderTextColor":"#ffffff","onlineIndicator":"#99cb3f","awayIndicator":"#b8b884","dndIndicator":"#f74343","mentionBj":"#ffffff","mentionColor":"#ffffff","centerChannelBg":"#ffffff","centerChannelColor":"#444444","newMessageSeparator":"#90ad58","linkColor":"#90ad58","buttonBg":"#90ad58","buttonColor":"#ffffff","errorTextColor":"#fd5960","mentionHighlightBg":"#54850c","mentionHighlightLink":"#ffffff","codeTheme":"monokai","mentionBg":"#7E9949"}`

**Comment by stephenkiers** [comment]
yeah. Hopefully that helps. :)

**Comment by stephenkiers** [comment]
Hmm... still unable to reproduce. 
1) Are there any other customizations or settings that may be different than the default installation? 
2) Have you changed any Android settings for text size, etc?  
3) are you able to reproduce consistently, or is it more of a random error? 
4) is anyone else on your team experiencing the issue?
5) is the issue new with the latest upgrade, or has it been happening for a while?

Thanks

**Comment by moussetc** [comment]
1. I can't think of any.
2. No.
3. I'v done some quick testing and it looks like emojis might be the issue here:
    The bottom of the 'y' in 'ty :p' is cut while 'ty' is displayed correctly. I tried several type of emojis and the issue is also present.
4. I'v asked, I'll get back to you on that point. Alas, since we haven't yet managed to install our notifications server&build our own version of the app, I might be the only one using it right now since no notifications make the app less useful.
5. I have the problem since the first weeks of use, and I made my first install soon after 2d december 2017.

Thanks

**Comment by stephenkiers** [comment]
I think I reproduced with your hint in 3
Lets see if I can fix

**Comment by stephenkiers** [comment]
I have started a discussion on what to do here : https://pre-release.mattermost.com/core/pl/wchehqs4w3yspycke5nq6mk85r

**Comment by moussetc** [comment]
Hi again, I just had the issue on a message that did not contain any emoji :S A line was missing at the end, I tapped the message and it then appeared completely. I restarted the app and the message was displayed correctly.
I tried writing the same message again, but the issue was not present this time.

**Comment by enahum** [comment]
Question, was it really missing? Scrolling up and down disn’t show the full message?

**Comment by moussetc** [comment]
Uh, I don't understand the question. Messages above and below were fully visible, there should have been no need to scroll.

**Comment by stephenkiers** [comment]
PR submitted : https://github.com/mattermost/mattermost-mobile/pull/1402 
For all reproducible issues. I am hoping they will also fix your non-reproducible issues. 

Otherwise we will need a new issue report after next release, or consistent repro steps for the current version to test beforehand.

Thanks @moussetc

**Comment by moussetc** [comment]
Hi, thank you for your work, alas the issue is still present using the 1.6.1 version. 
On my phone, I can always reproduce it by typing "yay :P" and the bottom of the text is cut, as well as the very top of the emoji:
![image](https://user-images.githubusercontent.com/8834237/36200663-b6df308e-117d-11e8-99f5-ea5ad922d7c3.png)
