### ISSUE TITLE
Allow View/Modify of Account Settings

### ISSUE THREAD

**Issue by csduarte** [mattermost/mattermost-mobile#138]
The RN app should allow basic Accounting Settings in-app, with specific regard to Notification Settings.

**Comment by it33** [comment]
@csduarte could you help share the settings you're looking for in priority order? 

E.g. for notifications, a sequence might be: 

1. Channel Header > Mark Channel Unread

2. Account Settings > Mobile push notifications 

3. Account Settings > Words that trigger mentions

Just need to figure out how to sequence the work to arrive at what's needed most.

**Comment by csduarte** [comment]
Suggested Priority:
 
Notifications > Mobile Push Notifications
Notifications > Trigger words
Notifications > Reply Notificiations
Notifications > Email Notifications

General > Name, Username, Email
General > Profile Picture

Security > Password
Security > View Access History

Display > Clock
Display > Language
Display > Link previews
Display > Message Display

Advanced > Join Leave Messages
Advanced > Enable Post Formatting

!Display > Channel Display Mode
!Advanced > Ctrl + enter
!Notifications > Desktop Notifications

**Comment by lfbrock** [comment]
Breaking this out into separate tickets: 

[Channel Settings > Notifications](https://github.com/mattermost/mattermost-mobile/issues/238)
[Account Settings > Notifications](https://github.com/mattermost/mattermost-mobile/issues/237)
[Account Settings > General](https://github.com/mattermost/mattermost-mobile/issues/235)
[Account Settings > Profile Picture](https://github.com/mattermost/mattermost-mobile/issues/236)

**Comment by enahum** [comment]
Closing this will keep track with the jira tickets
