### ISSUE TITLE
Text in code blocks doesn't wrap like on the desktop client

### ISSUE THREAD

**Issue by Bortseb** [mattermost/mattermost-mobile#1393]
#### Summary
Text in code blocks doesn't wrap on mobile like on the desktop client

#### Environment Information

- Device Name: 
- OS Version: Android 7.0
- Mattermost App Version: 1.5.2
- Mattermost Server Version: 4.3.0

#### Steps to reproduce
Write text that is long enough to wrap when on mobile between the code blocks formatting, i.e. ``` , then view on mobile.

#### Expected behavior
When I view my messages with code block on my desktop, and resize the window, the text adapts and wraps so that each full line is always in view.

#### Observed behavior
The code block on mobile is visible, but I need to click into it to be able to scroll my screen to see all the code, even when I click into the code block it still doesn't wrap.

**Comment by saturninoabril** [comment]
@Bortseb Thanks for the report! I filed a ticket here https://mattermost.atlassian.net/browse/ICU-677.
I'm closing this issue; tracking will be on the filed ticket.
