### ISSUE TITLE
Mattermost mobile apps can't connect to server 4.6 with new SSL certificate (Thawte RSA CA 2018)

### ISSUE THREAD

**Issue by chumbalum** [mattermost/mattermost-mobile#1404]
#### Summary
Mobile apps won't connect anymore after upgrading server to 4.6 and usage of a new ssl certificate. The ssl certificate was issues by Thawte RSA CA 2018.

#### Environment Information

- Device Name: Nexus 5X / IPhone 5
- OS Version: 8.1.0
- Mattermost App Version: 1.5.2 / 3.10.0 (classic) / 1.6.0 (Beta)
- Mattermost Server Version: 4.6

#### Steps to reproduce
Use Mattermost Server with a certificate issued by Thawte RSA CA 2018

#### Expected behavior
App should connect to the server

#### Observed behavior
In the current mobile app on android, there is a generic error message that the connection could not be established. In the classic app it says "Mattermost server unreachable, incompatible or SSL is not properly configured". In Chrome on the mobile device, the server is normally reachable.

#### Possible fixes
Maybe the problem is that our certificate is issued by a new CA (Thawte RSA CA 2018) ?

**Comment by chumbalum** [comment]
I just installed the CA certificate on my device and it resolved my issue.

https://search.thawte.com/support/ssl-digital-certificates/index?page=content&id=INFO1384

So I don't know if this is an issue of the app or must be resolved by the OS.

**Comment by enahum** [comment]
Looks like this is an OS issue

**Comment by enahum** [comment]
Were you able to solve this? Did you look at your certificate using a tool like ssllabs.com?

**Comment by lindy65** [comment]
Hi @chumbalum,

It seems you've resolved your issue so I'll close this off here for now.  Please feel free to open a new issue if you are still experiencing problems.

Thanks!
