### ISSUE TITLE
E2E Crypto support

### ISSUE THREAD

**Issue by cybershambles** [mattermost/mattermost-mobile#141]
For personal messages in particular and maybe even private chats.

I'd love to be able to offer this service and NOT be able to read what my clients are saying to each other :)

**Comment by lfbrock** [comment]
Hi @cybershambles - is this something you would want on just mobile, or desktop apps too? 

The new mobile apps are in the early stages right now, so were focusing on adding the basic functionality first - would you be able to move this to the [feature request forum](https://mattermost.uservoice.com/forums/306457-general) so others can upvote if it's something they're interested in too?

**Comment by enahum** [comment]
This topic have been without discussion for a while, so im going to close ir. Feel free to re-open to resume any discussion on this
