### ISSUE TITLE
Build date in about dialog incorrect

### ISSUE THREAD

**Issue by dbrgn** [mattermost/mattermost-mobile#1412]
#### Summary

In the about dialog, the build date seems wrong.

#### Environment Information

- Device Name: Fairphone 2
- OS Version: Android 6.0.1
- Mattermost App Version: master (c4ad99d)
- Mattermost Server Version: 4.4.0 (Build 4.4.5)

#### Steps to reproduce

- Build the current master version of the Android app with `make build-android`
- Deploy to device, open app, log in
- Go to Settings > About Mattermost
- In my case I built the app on 2018-02-04, but the build date shown is 2017-12-07.

#### Expected behavior

The build date should be updated during the build process.

**Comment by enahum** [comment]
@dbrgn the build date in the About screen is referring to the build date for the server, perhaps is not that clear?

actually the Build Hash also refers to the server one, @esethna thoughts?

**Comment by dbrgn** [comment]
@enahum ah, I see 🙂 No, it was not clear to me, I assumed that was the build date of the app.

**Comment by enahum** [comment]
@dbrgn is it ok to close this issue?

**Comment by dbrgn** [comment]
Yes, although I still think putting the build date (ideally the build commit id) of the app in the about dialog would make sense :)
