### ISSUE TITLE
What is the appropriate way to use custom theme?

### ISSUE THREAD

**Issue by alizainkazmi** [mattermost/mattermost-mobile#1413]
I just want to know if there is a way defined to use a custom theme?

**Comment by enahum** [comment]
@hmhealey thoughts?

**Comment by hmhealey** [comment]
Hi @alizainkazmi,

At this time, you can only configure your theme through the Mattermost web app, but the theme you set there should apply to the mobile app when logged in.

**Comment by lindy65** [comment]
I'll close this issue off here for now.  Feel free to open a new issue if you're still needing help :)
