### ISSUE TITLE
Image fails to load when viewing 'Developers' Channel info on Android

### ISSUE THREAD

**Issue by jimbothree** [mattermost/mattermost-mobile#1454]
#### Summary
When viewing the channel info for the 'Developers' Channel, in the Header section of channel info I received an error message 'Image failed to load: codecov'

#### Environment Information
- Device Name: Droid Turbo 2
- OS Version: Android Version 7.0
- Mattermost App Version: 1.6.0 (Build 75)
- Mattermost Server Version: 4.7.1 (Build 4.7.1-rc1)

#### Steps to reproduce
(Only confirmed on Android)
Login to Mattermost mobile app -> enter https://pre-release.mattermost.com as the server URL
Click Hamburger Icon in top left to display Channel List
Click '+' Next to Public channel
Join the 'Developers' channel
Tap Channel Name at top of screen to view channel info
Channel info is displayed, under Header section is an error message 'Image failed to load: codecov'

#### Expected behavior
Viewing the 'Developers' Channel info in the Desktop version displays the 'codecov' image properly.
On the mobile app I would expect that the 'codecov' image would be present when viewing 'Developers' channel info

#### Observed behavior
When Viewing 'Developers' Channel info, Purpose is present and links under 'Useful links' are working..however red error message 'Image failed to load' is present under Header.

**Comment by lindy65** [comment]
Hi @jimbothree 

Thanks for your feedback :)

I believe this issue has been resolved... Please upgrade to the [latest version of the app](https://about.mattermost.com/download/#mattermostApps) as well as Mattermost server (v4.9 released today - April 16th).

Thanks!
