### ISSUE TITLE
User online statuses are never updated

### ISSUE THREAD

**Issue by koxen** [mattermost/mattermost-mobile#1460]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
User online statuses are never updated.
This has been an inssue since forever...

#### Environment Information

- Device Name:  Samsung s7
- OS Version:  android 7.0
- Mattermost App Version:  master
- Mattermost Server Version: master

#### Steps to reproduce
How can we reproduce the issue?
Open DM with someone on mobile app, let that person change status to offline.
The online status will be never updated unless you hit clear cache in mattermost settings

#### Expected behavior
User online statuses are updated as soon as websocket is reconnected, when the app is opened.

#### Observed behavior
User online status is never updated unless you clear cache.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by lindy65** [comment]
Hi @koxen 

Thanks for your feedback :)

I believe this issue has been resolved... Please upgrade to the [latest version of the app](https://about.mattermost.com/download/#mattermostApps) as well as Mattermost server (v4.9 released today - April 16th).

Thanks!
