### ISSUE TITLE
Channel is not refreshed after clicking a notification

### ISSUE THREAD

**Issue by koxen** [mattermost/mattermost-mobile#1461]
#### Summary
After clicking a notification that brings you to the channel, the new messages are not loaded unless you force a channel refresh by swiping from down.

#### Environment Information
Tested on samsung s7 and iphone 6.
- Device Name:  
- OS Version: 
- Mattermost App Version: <s>master</s> latest app store
- Mattermost Server Version: master

#### Steps to reproduce
How can we reproduce the issue?
1. Open mattermost on channel X and switch to another app.
2. Change your status to away and ask someone to write in channel X
3. Click mobile notification that brings you to the channel.
4. The new messages are not loaded or are loaded with a very long delay

**Comment by miker** [comment]
I've seen this behavior as well. It seems in the last update this is sorta fixed. The channel does seem to refresh and load new comments eventually. It seems to be slow though and I've noticed that it sometimes causes the app to hang. Either "refreshing" forever and I'm unable to do anything until I go to the recent apps and kill matter most, or properly loading new comments.

**Comment by koxen** [comment]
@miker are you running ios?

**Comment by lindy65** [comment]
Hi @koxen @miker 


Thanks for your feedback :)

I believe this issue has been resolved... Please upgrade to the [latest version of the app](https://about.mattermost.com/download/#mattermostApps) as well as Mattermost server (v4.9 released today - April 16th).

Thanks!
