### ISSUE TITLE
The team sidebar is not working after clicking on post profile picture.

### ISSUE THREAD

**Issue by cometkim** [mattermost/mattermost-mobile#1463]
#### Summary
The team sidebar is not working after clicking on post profile picture.

#### Environment Information

- Device Name: 
- OS Version: Android 7.1.1
- Mattermost App Version: 1.6.1
- Mattermost Server Version: 4.7

#### Steps to reproduce
1. Join multiple teams to use team sidebar.
2. Click on any profile picture in channel view.
3. Close user profile modal, try to use team sidebar.

#### Expected behavior
Should works as expected.

#### Observed behavior
Select team button and swiping are not working.

**Comment by lindy65** [comment]
Hi @cometkim 

Thanks for your feedback,

Please try upgrading to the [latest version of the app](https://about.mattermost.com/download/#mattermostApps) as well as the Mattermost server (v4.9 released today - April 16th) to see whether this fixes the issue for you?

**Comment by cometkim** [comment]
@lindy65 It looks already fixed in a previous version 👍 
now it looks fine to me.

**Comment by lindy65** [comment]
Perfect @cometkim 👍
