### ISSUE TITLE
After taking down the upstream server - the app halts at "Refresh"

### ISSUE THREAD

**Issue by madflow** [mattermost/mattermost-mobile#1466]
#### Summary

After taking down the upstream server - the app halts at "Refresh"

#### Environment Information

- Device Name: iphone6
- OS Version: 11.2.6
- Mattermost App Version: 1.6.1
- Mattermost Server Version: 4.3.1

#### Steps to reproduce

I have initially configured the app with the server https://my.server.com. Then we took this server "down" and changed the new server to https://my-new-server.server.com.

The app just show a "Refresh" Symbol

#### Expected behavior

I should be able to configure a new server.

**Comment by sherifelgafary** [comment]
I have the same issue i'm using the demo server 
https://pre-release.mattermost.com/
and after logging in with my credentials it's stuck at refreshing only

**Comment by lukeallister** [comment]
This happened to me also. I reinstalled the app, which did not fix it. I switched to the mattermost beta app, which is working correctly for me.

**Comment by lindy65** [comment]
Hi @madflow @sherifelgafary @lukeallister 

Thanks for your feedback! 👍 

Please try upgrading to v1.7.1 of the app and v4.9 of the Mattermost server (released today - April 16th) which should fix the issue for you.
