### ISSUE TITLE
Markdown Inline SVG Images not showing up

### ISSUE THREAD

**Issue by madflow** [mattermost/mattermost-mobile#1481]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary

Markdown Inline Images with an absolute URL not showing up. The do show up in the "Web-App"

#### Environment Information

- Device Name: iphone6
- OS Version: 11.2.6
- Mattermost App Version: 1.6.1
- Mattermost Server Version: 4.3.1

#### Steps to reproduce

Copy paste into a chat:

```MARKDOWN
[![Mattermost](https://about.mattermost.com/wp-content/uploads/2017/08/Mattermost-Logo-Blue.svg)](https://github.com/mattermost/mattermost-server)
```

#### Expected behavior

Show up

#### Observed behavior

They do not show up

**EDIT**:

Like @enahum said - it is indeed related to the svg format.

**Comment by enahum** [comment]
I think the problem is the svg file type that is not supported for inline images.

@hmhealey can you take a look?

**Comment by hmhealey** [comment]
I think we could look into it, but we'd need to see if the SVG library that we have can display arbitrary SVGs or if it needs them built out of its own components.

I filed a ticket [here](https://mattermost.atlassian.net/browse/MM-9746)

**Comment by lindy65** [comment]
I'll close this issue off for now and we can track via the above-linked ticket.
