### ISSUE TITLE
iOS build issues with signing

### ISSUE THREAD

**Issue by nicolinuxfr** [mattermost/mattermost-mobile#1522]
#### Summary

I think the iOS build process does not always take into account the variables from .env file for the signing part. I have an error during signing, since the build is trying to use the default profile instead of mine. 

#### Environment Information

I'm using macOS Sierra, latest version of Fastlane (2.85.0) and I cloned the project at this commit : https://github.com/mattermost/mattermost-mobile/commit/1f7ec077860a040e23303481d086939b90e60f75

#### Observed behavior

When I want to build the app, the process will fail when signing with these errors : 

```
[16:05:47]: ▸ Code Signing Error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't include signing certificate "iPhone Developer: Nicolas furno (********)".
[16:05:47]: ▸ Code Signing Error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the App Groups capability.
[16:05:47]: ▸ Code Signing Error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the group.******.mattermost App Group.
[16:05:47]: ▸ Code Signing Error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the com.apple.security.application-groups entitlement.
[16:05:47]: ▸ Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 11.2'
```

When opening the project in Xcode just after these error, here's what I noticed : the default app ID is used, instead of the one I used in my `.env` file.

![capture d ecran 2018-03-19 a 16 09 16](https://user-images.githubusercontent.com/2078386/37603878-e823d984-2b8f-11e8-9daf-0bc6f40965f7.png)

If I edit manually the `project.pbxproj` file to search all default values and replace these with mine, the build is working fine. 

I guess there is a bug somewhere, that prevents the build process to extract the correct values during the build ?

Let me know if you need more information.

**Comment by enahum** [comment]
Have you set up match? I'm almost sure that match should be run in order to sign correctly for iOS.

Probably there is something else we missed for env vars that is used by `gym` that is being set by match.

**Comment by enahum** [comment]
for more you can check the fastlane script under `fastlane/Fastfile` to better understand what's going on

**Comment by nicolinuxfr** [comment]
Yes, I did set up Match. And I think it works as intended, but it’s my first Fastlzne experience so…

**Comment by jnbt** [comment]
I've encountered the same problem, because the Xcode project was still set up to "Automatically manage signing" which didn't worked for me.

From Fastlane: 
> In most cases, fastlane will work out of the box with Xcode 9 if you selected manual code signing, and chose a provisioning profile name for each of your targets (see Xcode 8 section).

After deactivating the automatic code signing and selecting the profile generated by fastlane's match for the main and share target it worked.

Maybe it would make sense to include the `disable_automatic_code_signing` [action](https://docs.fastlane.tools/actions/automatic_code_signing/) in the `Fastfile`?

**Comment by enahum** [comment]
@jnbt feel free to make a PR if that helps, later on I can review + test.

The one thing is to try and use the current ENV vars.

Thanks

**Comment by koxen** [comment]
> After deactivating the automatic code signing and selecting the profile generated by fastlane's match for the main and share target it worked.
Maybe it would make sense to include the disable_automatic_code_signing action in the Fastfile?

I did already implement that for myself, I can share the code. Had the same issue as you

**Comment by nicolinuxfr** [comment]
Please, share, I’m interested. :-)

**Comment by koxen** [comment]
```
    ## MANUAL SIGN HACK ##
    ## + gym codesigning identity in env
    disable_automatic_code_signing(path: './ios/Mattermost.xcodeproj')
    update_project_provisioning(
      xcodeproj: './ios/Mattermost.xcodeproj',
      profile: ENV["sigh_#{ENV['IOS_MAIN_APP_IDENTIFIER']}_appstore_profile-path"],
      build_configuration: "Release",
      target_filter: /Mattermost\z/, # matches name or type of a target
  )

  update_project_provisioning(
      xcodeproj: './ios/Mattermost.xcodeproj',
      profile: ENV["sigh_#{ENV['IOS_EXTENSION_APP_IDENTIFIER']}_appstore_profile-path"],
      build_configuration: "Release",
      target_filter: "MattermostShare", # matches name or type of a target
  )


    ### HACK END ###
    
    
    gym(
        # Default to clean: false
        clean: ENV['IOS_BUILD_CLEAN'],
        # can't use skip_archive because we need the IPA... 
        # skip_archive: !ENV['IOS_BUILD_CLEAN'],
        scheme: 'Mattermost',
        configuration: config_mode,
        workspace: './ios/Mattermost.xcworkspace',
        export_method: method,
        xcargs: '-parallelizeTargets -jobs 4'
    )
  end
```

+ set GYM_CODESIGNING_IDENTITY env :)

**Comment by koxen** [comment]
this took 2 days of debugging to find a combination that works... 🤦‍♂️

**Comment by nicolinuxfr** [comment]
Thanks @koxen !

I'm a Fastlane newbie (first try ever), so I'm not sure I'm doing the right think. I added your code inside the `Fastfile`, replacing the gym part where there the gym function was, and adding the rest above. I also added in my `.env` file the code signing identity.

But when I build, I have this error :

```
[17:01:46]: ▸ Code Signing Error: Provisioning profile "match AppStore com.XXXX.mattermost.Share" has app ID "com.XXXX.mattermost.Share", which does not match the bundle ID "com.mattermost.rnbeta.MattermostShare".
```

So I guess I did something wrong, somewhere ? Could you point me in the right direction ?

Thanks, again. :-)

**Comment by koxen** [comment]
can you paste your env? something stopped fastlane script from updating bundle ids to what you have in ENV

**Comment by nicolinuxfr** [comment]
Here it is :

```
export LC_ALL="fr_FR.UTF-8"
export SYNC_IOS_PROVISIONING_PROFILES=true
export IOS_BUILD_FOR_RELEASE=true
export IOS_REPLACE_ASSETS=true
export MATCH_GIT_URL=git@xxxx.xxxx:xxxxxxxxx.git
export MATCH_USERNAME=xxxxxx@me.com
export IOS_BUILD_EXPORT_METHOD=app-store
export MATCH_TYPE=appstore
export IOS_APP_NAME="MacGermost"
export IOS_MAIN_APP_IDENTIFIER=com.xxxxxxxx.mattermost
export IOS_EXTENSION_APP_IDENTIFIER=com.xxxxxxxx.mattermost Share
export IOS_APP_GROUP=group.com.xxxxxxxx.mattermost
export MATCH_APP_IDENTIFIER=com.xxxxxxxx.mattermost.Share,com.xxxxxxxx.mattermost
export FASTLANE_TEAM_ID=XXXXXXXX
export PILOT_USERNAME=xxxxxx@me.com
export GYM_CODESIGNING_IDENTITY=xxxxxx@me.com
```

Every `xxxxxx@me.com` is the same email address, the one I also used for Fastlane's Match.

Thanks for your help !

**Comment by jnbt** [comment]
@nicolinuxfr I think whitespace is not supported for app or extension identifiers, e.g.  `IOS_EXTENSION_APP_IDENTIFIER`:

```
export IOS_EXTENSION_APP_IDENTIFIER="com.xxxxxxxx.mattermost.Share"
```

**Comment by nicolinuxfr** [comment]
@jnbt you're right, but the file is right, it's a typo error when I redacted this line.

**Comment by koxen** [comment]
you can also paste your fastlane logs, it should make it pretty clear why it didn't update the bundle id 🤔

**Comment by nicolinuxfr** [comment]
This ?

[Mattermost-Mattermost.log](https://github.com/mattermost/mattermost-mobile/files/1894499/Mattermost-Mattermost.log)

**Comment by koxen** [comment]
no, not this..are you building without fastlane? you need to run fastlane, and not compile via xcode

**Comment by nicolinuxfr** [comment]
Of course not ! I'm using the `make build-ios` command which uses fastlane behind the scene. This log is suggested after the error, I don't know where to find other logs ?

**Comment by koxen** [comment]
you need to pipe it like 
make build-ios &> fastlane.log

**Comment by nicolinuxfr** [comment]
OK then : 
[fastlane.log](https://github.com/mattermost/mattermost-mobile/files/1898624/fastlane.log)

**Comment by koxen** [comment]
ah yes I remember.
you need to patch this attribute in info.plist files :D
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
^ change to this

**Comment by koxen** [comment]
> export GYM_CODESIGNING_IDENTITY=xxxxxx@me.com
this is not correct, this shuld be "iPhone Distribution: Nicolas furno (XXXXXX)" and not email
also for some reason it's important for it to be distribution and not developer

in case of more errors do a `match nuke` please, before rebuild

**Comment by nicolinuxfr** [comment]
Done and done, but same thing… 😞 

Maybe it's a profile configuration error, but if I automatically sign the project in Xcode, it works perfectly.

**Comment by enahum** [comment]
Have you followed the docs for this?

Did you create an app group for your appID, and did you associated it with it? you can use XCode to do it for you. Also remember that you need to set the env var for the app group as well

**Comment by nicolinuxfr** [comment]
I think I did follow the doc, but maybe I missed something.

Everything is correct for the app group and appID, since I can compile the app without problem in Xcode. 

However, I'm not sure for your last point. Here's the redacted content of my `.env` file, do you think it misses something ?

https://github.com/mattermost/mattermost-mobile/issues/1522#issuecomment-379992246

**Comment by amyblais** [comment]
Hi @nicolinuxfr! Did Elias' note above help?

**Comment by nicolinuxfr** [comment]
Sorry, I did not have time to try.

So, I started with a fresh copy of mattermost, and even a different Mac to be sure. I used your `.env` file and changed values as needed. I also copied the release folder with my custom images and configuration.

I did a `make pre-run` and then `make build-ios` and I'm immediately stuck with this error :

```
Could not find aws-eventstream-1.0.0 in any of the sources
Run `bundle install` to install missing gems.
make: *** [build-ios] Error 7
```

I tried to do a `bundle install` from the fastlane folder, but it didn't help. Am I missing something ?

**Comment by enahum** [comment]
@nicolinuxfr you need to install `fastlane`.

ensure that you have ruby installed on your mac, cd into the `fastlane` directory and run `bundle install`

**Comment by nicolinuxfr** [comment]
@enahum 

I already have fastlane installed :

```
fastlane -v
fastlane installation at path:
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.96.1/bin/fastlane
-----------------------------
[✔] 🚀
fastlane 2.96.1
```

As for `bundle install`, here's the result : 

```
bundle install
Using CFPropertyList 3.0.0
Using public_suffix 2.0.5
Using addressable 2.5.2
Using atomos 0.1.2
Using aws-eventstream 1.0.0
Using aws-partitions 1.87.0
Using aws-sigv4 1.0.2
Using jmespath 1.4.0
Using aws-sdk-core 3.21.1
Using aws-sdk-kms 1.5.0
Using aws-sdk-s3 1.12.0
Using babosa 1.0.2
Using bundler 1.16.1
Using claide 1.0.2
Using colored 1.2
Using colored2 3.1.2
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using declarative 0.0.10
Using declarative-option 0.1.0
Using unf_ext 0.0.7.5
Using unf 0.1.4
Using domain_name 0.5.20180417
Using dotenv 2.4.0
Using emoji_regex 0.1.1
Using excon 0.62.0
Using multipart-post 2.0.0
Using faraday 0.15.1
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.6
Using faraday_middleware 0.12.2
Using fastimage 2.1.3
Using gh_inspector 1.1.3
Using jwt 2.1.0
Using little-plugger 1.1.4
Using multi_json 1.13.1
Using logging 2.2.2
Using memoist 0.16.0
Using os 0.9.6
Using signet 0.8.1
Using googleauth 0.6.2
Using httpclient 2.8.3
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using uber 0.1.0
Using representable 3.0.4
Using retriable 3.1.1
Using google-api-client 0.21.2
Using json 2.1.0
Using mini_magick 4.5.1
Using multi_xml 0.6.0
Using plist 3.4.0
Using rubyzip 1.2.1
Using security 0.1.3
Using naturally 2.1.0
Using simctl 1.6.4
Using slack-notifier 2.3.2
Using terminal-notifier 1.8.0
Using unicode-display_width 1.3.2
Using terminal-table 1.8.0
Using tty-screen 0.6.4
Using tty-cursor 0.5.0
Using tty-spinner 0.8.0
Using word_wrap 1.0.0
Using nanaimo 0.2.5
Using xcodeproj 1.5.9
Using rouge 2.0.7
Using xcpretty 0.2.8
Using xcpretty-travis-formatter 1.0.0
Using fastlane 2.96.1
Using fastlane-plugin-android_change_package_identifier 0.1.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.2
Using fastlane-plugin-android_change_string_app_name 0.1.1
Using fastlane-plugin-find_replace_string 0.1.0
Bundle complete! 6 Gemfile dependencies, 75 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by enahum** [comment]
@nicolinuxfr right, but very often we do update `fastlane` and it will update the dependencies for fastlane as well, so you may not be having a new dependency or the right version number, that is why you'll have to run that command

**Comment by nicolinuxfr** [comment]
I tried without transferring assets (setting the `IOS_REPLACE_ASSETS` parameter to false in the .env file). The previous error disappears, of course, but then I'm back to the beginning, with the same error described [in the fist post](https://github.com/mattermost/mattermost-mobile/issues/1522#issue-306504457).

**Comment by nicolinuxfr** [comment]
Let me correct my previous statement, the error is different since it involves automatic signing, which is disabled by the `.env` file : 

```
[14:24:22]: ▸ === BUILD TARGET MattermostShare OF PROJECT Mattermost WITH CONFIGURATION Release ===
[14:24:22]: ▸ Check dependencies
[14:24:22]: ▸ Code Signing Error: No profiles for 'com.XXXXXX.mattermost.MattermostShare' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching '
'com.XXXXXX.mattermost.MattermostShare'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
[14:24:22]: ▸ Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 11.3'
```

The profile 'com.XXXXXX.mattermost.MattermostShare' is indeed wrong, I checked the configuration, and it is supposed to be 'com.XXXXXX.mattermost.Share'. Maybe it's an error the build process code ?

**Comment by amyblais** [comment]
Hi @nicolinuxfr - Giving you an update here that the engineer who has been helping you with this recently (enahum) has been off for the last few days and I'll ping him again to take a look at this when he is back next week.

**Comment by nicolinuxfr** [comment]
Thanks for the update ! :-)

No worry, I can manually build the app in the meantime.

**Comment by amyblais** [comment]
Hi @nicolinuxfr! Giving you an update here that we will test this on v1.9 (released this Friday) to see if we have the same or similar issues.

**Comment by nicolinuxfr** [comment]
OK great ! Let me know if I can help in any way…

**Comment by enahum** [comment]
@yakimant this is really helpful, actually I'm making some changes to the fastlane script and I'm about to include this one question:

What value do you set for `PROVISIONING_PROFILE_SPECIFIER`?

I'm assuming the value for `CODE_SIGN_STYLE`  is `Manual` right?

**Comment by nicolinuxfr** [comment]
Well, it's strange, I have the issue on the first post again today : 

```
[13:45:36]: ▸ ❌  error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the App Groups and iCloud capability. (in target 'MattermostShare')
[13:45:36]: ▸ ❌  error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the group.Com.macgeneration.mattermost App Group. (in target 'MattermostShare')
[13:45:36]: ▸ ❌  error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the iCloud.com.mattermost.rnbeta.MattermostShare iCloud Container. (in target 'MattermostShare')
[13:45:36]: ▸ ❌  error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the com.apple.developer.icloud-container-identifiers,
[13:45:36]: ▸ ❌  error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the App Groups, iCloud, and Push Notifications capability. (in target 'Mattermost')
[13:45:36]: ▸ ** ARCHIVE FAILED **
[13:45:36]: ▸ ❌  error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the group.Com.macgeneration.mattermost App Group. (in target 'Mattermost')
[13:45:36]: ▸ ❌  error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the iCloud.co.macg.mattermost iCloud Container. (in target 'Mattermost')
[13:45:36]: ▸ ❌  error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the aps-environment,
```

It seems the variables in the `.env` file inside fastlane folder are not taken into account. I haven't changed my configuration, and it worked fine the last time I built a custom iOS version (it was after the last App Store version, 1.12.0). 

To be sure, I even deleted everything and started fresh, but the error is still there every time when I u se `make build-ios`.

**Comment by enahum** [comment]
@nicolinuxfr env vars have changed take a look at https://developers.mattermost.com/contribute/mobile/build-your-own/

**Comment by nicolinuxfr** [comment]
@enahum OK, sorry about that, I had missed the changes.

I did apply the new vars in the file and it's better, even if I stumble on a different error? I don't think this is related to this issue, so I can open a new one if you want.

```
▸ Compiling strtod.cc

❌  error: Build input file cannot be found: '/Users/nicolas/Git/apps/mattermost-mobile/node_modules/react-native/third-party/double-conversion-1.1.6/src/strtod.cc'


▸ Compiling fixed-dtoa.cc

❌  error: Build input file cannot be found: '/Users/nicolas/Git/apps/mattermost-mobile/node_modules/react-native/third-party/double-conversion-1.1.6/src/fixed-dtoa.cc'


▸ Compiling fast-dtoa.cc

❌  error: Build input file cannot be found: '/Users/nicolas/Git/apps/mattermost-mobile/node_modules/react-native/third-party/double-conversion-1.1.6/src/fast-dtoa.cc'


▸ Compiling double-conversion.cc

❌  error: Build input file cannot be found: '/Users/nicolas/Git/apps/mattermost-mobile/node_modules/react-native/third-party/double-conversion-1.1.6/src/double-conversion.cc'


** ARCHIVE FAILED **
```

**Comment by enahum** [comment]
Seems to me that you’ve updated XCode to version 10, there is a known issue where react native fails to build unless you switch your build process to legacy mode

**Comment by nicolinuxfr** [comment]
Indeed, since it's the latest stable version.

What do you mean by legacy mode ?

**Comment by enahum** [comment]
@nicolinuxfr take a look at this thread https://github.com/facebook/react-native/issues/19573

**Comment by maxsdw** [comment]
@enahum in the .env file, should I use `export IOS_EXTENSION_APP_IDENTIFIER=` or `export EXTENSION_APP_IDENTIFIER=`, in https://developers.mattermost.com/contribute/mobile/build-your-own/ it says it is "EXTENSION_APP_IDENTIFIER", but now I'm confused.

**Comment by enahum** [comment]
@maxsdw, the second one `EXTENSION_APP_IDENTIFIER` as in the doc

**Comment by maxsdw** [comment]
Thanks @enahum , with the adjustment I could advance almost till the end of the process, but now gym is returning this error:

error: Build input file cannot be found: '/Users/maxsdw/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native/third-party/double-conversion-1.1.6/src/strtod.cc'

same for files: fixed-dtoa.cc, fast-dtoa.cc, double-conversion.cc

Any ideas?

**Comment by maxsdw** [comment]
@enahum  NVM, I just saw someone else already posted the same issue.

**Comment by maxsdw** [comment]
I modify gym config within Fastfile to use: xcargs: "-UseNewBuildSystem=NO" and now it works, thanks!.

**Comment by yakimant** [comment]
> What value do you set for `PROVISIONING_PROFILE_SPECIFIER`?
PROVISIONING_PROFILE_SPECIFIER = "match Development com.XXX.mattermost"
> I'm assuming the value for `CODE_SIGN_STYLE` is `Manual` right?
Yes

I'm trying to switch to use `make build-ios` and included Fastlane. The goal is to only have `.env` file.
Looks like it's not possible to sign with `Distribution` profile using only `.env` changes.

**Comment by yakimant** [comment]
@enahum, I have tried your Fastlane config with following env variables set:
- BUILD_FOR_RELEASE
- MAIN_APP_IDENTIFIER
- EXTENSION_APP_IDENTIFIER
- IOS_ICLOUD_CONTAINER
- IOS_APP_GROUP
- IOS_BUILD_EXPORT_METHOD
- FASTLANE_TEAM_ID

This was not enough for Enterprise Distriution signing / export.

The following changes are needed additionally:
- Change ```CODE_SIGN_IDENTITY``` to ```iPhone Distribution```
- Change ```CODE_SIGN_STYLE``` and ```ProvisioningStyle``` to ```Manual```
- Set ```PROVISIONING_PROFILE_SPECIFIER``` for both app and extension (```match InHouse MAIN_APP_IDENTIFIER``` and ```match InHouse EXTENSION_APP_IDENTIFIER```)
- Add ```provisioningProfiles``` to ```gym``` ```export_options```

**Comment by uni-x** [comment]
@yakimant 
> 
> The following changes are needed additionally:
> 
> * Change `CODE_SIGN_IDENTITY` to `iPhone Distribution`
> * Change `CODE_SIGN_STYLE` and `ProvisioningStyle` to `Manual`
> * Set `PROVISIONING_PROFILE_SPECIFIER` for both app and extension (`match InHouse MAIN_APP_IDENTIFIER` and `match InHouse EXTENSION_APP_IDENTIFIER`)

is it all in env file?

> * Add `provisioningProfiles` to `gym` `export_options`

What do you assign to provisioningProfiles for gym?

**Comment by nicolinuxfr** [comment]
After many months without any issue, I have the same problem of signing now : 

```
❌  error: Provisioning profile "match AppStore Com.macgeneration.mattermost.NotificationService" doesn't include signing certificate "Apple Distribution: MacGeneration (HRFVS4SXZ2)". (in target 'NotificationService' from project 'Mattermost')
❌  error: "MattermostShare" requires a provisioning profile with the App Groups feature. Select a provisioning profile in the Signing & Capabilities editor. (in target 'MattermostShare' from project 'Mattermost')
❌  error: Provisioning profile "match AppStore Com.macgeneration.mattermost" doesn't include signing certificate "Apple Distribution: MacGeneration (HRFVS4SXZ2)". (in target 'Mattermost' from project 'Mattermost')
❌  error: Provisioning profile "match AppStore Com.macgeneration.mattermost" doesn't support the iCloud.com.macg.mattermost iCloud Container. (in target 'Mattermost' from project 'Mattermost')
❌  error: Provisioning profile "match AppStore Com.macgeneration.mattermost" doesn't match the entitlements file's values for the com.apple.developer.ubiquity-container-identifiers and com.apple.developer.icloud-container-identifiers entitlements. (in target 'Mattermost' from project 'Mattermost')
```

I'm using macOS Catalina with latest stable Xcode (11.2.1). I rewrote my `.env` file based [on the example](https://github.com/mattermost/mattermost-mobile/blob/master/fastlane/env_vars_example), so I don't think there are issues here.

Let me know if you need more information.

**Comment by chetanyakan** [comment]
I am also facing a similar issue with `enterprise` provisioning profiles.
Each time I want to run the build with `make build-ios`, it fails until I manually make the following changes in Xcode:
1. Select the provisioning profiles
2. Update code signing identity from the build settings.

It seems to be an issue with more recent versions of the mattermost-mobile app as I did not need these changes every time for previous versions (e.g. v1.20, v1.21).

**Comment by gppcff** [comment]
In my case (version 1.27.0) the problem was in the list of bundleids indicated in the variable MATCH_APP_IDENTIFIER, it did not allow the correct execution of the cycle shown below and the consequent execution of the "update_project_provisioning":

fastfile fragment:
```
    ENV['MATCH_APP_IDENTIFIER'].split(',').each do |id|
      target = 'Mattermost'
      if id.include? 'NotificationService'
        target = 'NotificationService'
      elsif id.include? 'MattermostShare' 
        target = 'MattermostShare'
      end
      . . .
      . . .
      update_project_provisioning(
          xcodeproj: './ios/Mattermost.xcodeproj',
          profile: ENV["#{profile}_profile-path"], # optional if you use sigh
          target_filter: ".*#{target}$", # matches name or type of a target
          build_configuration: 'Release',
          code_signing_identity: 'iPhone Distribution' # optionally specify the codesigning identity
      )
    end
  end
```
my new bundleid did not include the word 'MattermostShare' and did not perform the 'update_project_provisioning'.

I hope this is useful :)

**Comment by nicolinuxfr** [comment]
@gppcff 

My bundleid does not include MattermostShare, so I guess this code can not work for me either.

I tried to change this line to adapt the file to the name of my `EXTENSION_APP_IDENTIFIER` but it still did not work.

What did you do on your side ?

**Comment by kishori-shipcom** [comment]
@nicolinuxfr 
We are facing the same issue with Manual CodeSign and Provisioning Profile doesn't support the Groups & Entitlements. Any luck with this ?

> After many months without any issue, I have the same problem of signing now :
> 
> ```
> ❌  error: Provisioning profile "match AppStore Com.macgeneration.mattermost.NotificationService" doesn't include signing certificate "Apple Distribution: MacGeneration (HRFVS4SXZ2)". (in target 'NotificationService' from project 'Mattermost')
> ❌  error: "MattermostShare" requires a provisioning profile with the App Groups feature. Select a provisioning profile in the Signing & Capabilities editor. (in target 'MattermostShare' from project 'Mattermost')
> ❌  error: Provisioning profile "match AppStore Com.macgeneration.mattermost" doesn't include signing certificate "Apple Distribution: MacGeneration (HRFVS4SXZ2)". (in target 'Mattermost' from project 'Mattermost')
> ❌  error: Provisioning profile "match AppStore Com.macgeneration.mattermost" doesn't support the iCloud.com.macg.mattermost iCloud Container. (in target 'Mattermost' from project 'Mattermost')
> ❌  error: Provisioning profile "match AppStore Com.macgeneration.mattermost" doesn't match the entitlements file's values for the com.apple.developer.ubiquity-container-identifiers and com.apple.developer.icloud-container-identifiers entitlements. (in target 'Mattermost' from project 'Mattermost')
> ```
> 
> I'm using macOS Catalina with latest stable Xcode (11.2.1). I rewrote my `.env` file based [on the example](https://github.com/mattermost/mattermost-mobile/blob/master/fastlane/env_vars_example), so I don't think there are issues here.
> 
> Let me know if you need more information.

**Comment by nicolinuxfr** [comment]
@kishori-shipcom 

Frankly, I have given up at this point. I usually start with the automated building, and when it fails, I open Xcode and finish the work there.

Usually, I have to activate the automated signing process, correct an error or two sometimes. It's pretty easy, but manual, so I hope a better solution can be found but until then, it works at least.

**Comment by UpriseNate** [comment]
To get match working and automated building, the two things that hung me up were: 

1) making sure each (NotificationService, MattermostShare, and the app) have provisioning profiles in the same app group

2) make sure each of those 3 are listed in MATCH_APP_IDENTIFIER so that match actually gets their provisioning profiles

I'm new to iOS build systems and certainly new to match, so maybe these are obvious. In general, I think the build docs could better describe how to setup match

**Comment by jjercx** [comment]
I fixed this by removing the check of automatically manage sign in and manually selecting from the dropdown the profiles created by match.

**Comment by AustinFuller** [comment]
Unselecting the automatic signing within Xcode resolved this problem for me as well...

**Comment by larkox** [comment]
Closing this issue due to its age and that seems to be solved. If you still see the issue, feel free to reopen it.
