### ISSUE TITLE
Time is pushed out when user name long enough to line wrap.

### ISSUE THREAD

**Issue by Hyeongmin-Kwon** [mattermost/mattermost-mobile#1524]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Time to the right of the name is pushed out when name long enough to wrap.

#### Environment Information

- Device Name: Samsung Galaxy Note Fan Edition / SM-N935K
- OS Version:  7.0
- Mattermost App Version: 1.6.1 (Build 86)
- Mattermost Server Version: 4.8

#### Steps to reproduce
1. Make long name until line wrapping.
2. Send message.
#### Expected behavior
- Time will show on next line.

#### Observed behavior
![image](https://user-images.githubusercontent.com/31919589/37637255-fb751b5a-2c49-11e8-9340-7afb5d44aecb.png)
(Profile image hided)

- Time is pushed out of the screen.
- Also thread button is obscured by time.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by Hyeongmin-Kwon** [comment]
Hello @lindy65, thanks for reply. I tested again today as you said.

<img width="539" alt="screenshot_20180420-124026" src="https://user-images.githubusercontent.com/31919589/39029717-3dfe7c9e-4498-11e8-8c49-99410054f306.png">

I'm on v1.7.1 of the mobile app, and v4.9 of Mattermost server. However, the same issue occur. 
Thanks.

**Comment by lindy65** [comment]
Hi @Hyeongmin-Kwon,

Thanks for your feedback and for testing again...

This is fixed in v1.8 of the app which we are hoping to release on April 26th.

**Comment by lindy65** [comment]
Hi @Hyeongmin-Kwon 

v1.8 has released and your issue should be resolved.  If you're still seeing problems, please feel free to open a new issue and we'll investigate.
