### ISSUE TITLE
Insert gif in message crashs app

### ISSUE THREAD

**Issue by prodigy7** [mattermost/mattermost-mobile#1532]
#### Summary
When I want send over my swiftkey keyboard in the android app a gif as message, the application crashs reproducable.

#### Environment Information

- Device Name: HTC 10
- OS Version: Android 8.0.0 Security Patch-Level 1st Dec. 2017, 3.16.401.2
- Mattermost App Version: 1.6.1 (Build 86)
- Mattermost Server Version: 4.8.0

#### Steps to reproduce
Open channel or private chat and send gif over swiftkey keyboard

#### Expected behavior
Can insert gif as image into channel/private chat

#### Observed behavior
"Critical Error Occured!"
"This is embarrassing. We sincerely appologize for this."

Details -> "java.lang.IllegalArgumentException: column '_data' does not exists at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333) at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:92) ....

By the way ... it should be possible, send the error message directly to you over "Report error" button or copy text and send. Currently error details can only be show without mark and copy.

#### Possible fixes
I don't know

**Comment by miker** [comment]
I ran into a similar issue not 100% if it's the same. I am using SwiftKey as well though not sure if that's relevant. 

I'm trying to share a png and it crashes the server. Will try to get some logs later. I was trying to share a screenshot of another issue I'm having. This is the image https://filebin.pw/FzAKF/ I crashed the mm server 3 times in a row. 

Let me know if I should open a new bug.

**Comment by miker** [comment]
I am able to consistently crash the server upon trying to upload a png from a picture taken on my Galaxy S7 Edge. This is **not** gif dependent.
Issue persists after updating to the 3/27 release.
Happy to do more testing/troubleshooting.

**Comment by enahum** [comment]
Looks like the way SwiftLey Keyboard shares the data is not expected by the app thus crashing.

The app is actually expecting a local file and not a remote one.

**Comment by miker** [comment]
I'll test with the standard Samsung keyboard when I get a chance. I can upload images using swiftkey right after the crash/restart. Then it seems after a few uploads the issue starts happening again.
