### ISSUE TITLE
Share Extension freezes running program

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/mattermost-mobile#1553]
#### Summary
When opening the new share extension in the latest Ios version in the app store it just freezes the program that the extension was called from and nothing shows. 

#### Environment Information

- Device Name: Iphone 6 and Ipad Air 2
- OS Version: 11.2.6
- Mattermost App Version:  1.7.0 (Build 91)
- Mattermost Server Version: 4.8.0

#### Steps to reproduce
Try to send something via the Share extension.

#### Expected behavior
Share extension opens.

#### Observed behavior
Running program freezes and has to be closed.

**Comment by koxen** [comment]
have you tried waiting a few seconds for it to load? like say 10 seconds max

**Comment by Twilek-de** [comment]
Yes I waited several minutes and the Safari on an Ipad that froze this morning was still frozen when I reactivated it this afternoon about 9 hours later.

**Comment by koxen** [comment]
I might have an idea. Could you try with Mattermost Beta first?
https://mattermost-fastlane.herokuapp.com/ <- invite link

**Comment by koxen** [comment]
if it works on Mattermost Beta for you, then I know why, will PR a fix then

**Comment by Twilek-de** [comment]
I enrolled in the Beta Program and installed the beta but the error is still there

**Comment by koxen** [comment]
just to be sure...and you are actually clicking "Mattermost Beta" on the share screen and it still makes a freeze?

**Comment by Twilek-de** [comment]
Yep sorry, I especially paid attention to that.

**Comment by Twilek-de** [comment]
I also just checked that other share extensions work, so it´s not some general error with my ios setup.

**Comment by koxen** [comment]
I don't have an iphone to test right now, but it works fine on my custom build since my company is deploying a customized one.
AFAIK my coworker just told me the same yesterday about the "app store" build and that it works fine on our build

Share extension will freeze if app group is incorrectly set or provisioning profile was incorrect.
AFAIK currently the official app store version is manually deployed from one of developer's Mac, so the issue might be with his environment

**Comment by Twilek-de** [comment]
My Ios devices are all private vanilla. There is no customization and no company provisioning.

**Comment by koxen** [comment]
I understand, just wanted to add more context that share works if I compile mattermost-mobile myself.
I will pass that this to @enahum when he's back as he is currently on a leave.
(the app store version is being deployed from his Mac)

**Comment by koxen** [comment]
@Twilek-de the fix was commited to master, but I don't know when next beta/release will be pushed so you can use it

**Comment by Twilek-de** [comment]
I will keep my eyes peeled and report back when some new version is released.

**Comment by Twilek-de** [comment]
I will keep my eyes peeled and report back when some new version is released.

**Comment by enahum** [comment]
Release 1.7.1 includes a fix for this, waiting on Apple’s approval

**Comment by Twilek-de** [comment]
Seems to work alright now thanks!
