### ISSUE TITLE
File upload only for photo and Video 

### ISSUE THREAD

**Issue by fuedhdf** [mattermost/mattermost-mobile#1559]
#### Summary
Fileupload is only available for photo and video. 

#### Environment Information

- Device Name: Mate 9
- OS Version: Android 8
- Mattermost App Version: Beta
- Mattermost Server Version: 4.8

#### Steps to reproduce
Try to upload a file
#### Expected behavior
I have only the option to take a photo and upload a video or photo

**Comment by enahum** [comment]
Have you tried sharing the file from another app into mattermost?

**Comment by lindy65** [comment]
Hi @fuedhdf,

As there hasn't been any feedback on this issue, I'll close it off for now.  If you find sharing files from the other app into Mattermost isn't an option, please feel free to open a feature request on our [forum](https://mattermost.uservoice.com/forums/306457-general?category_id=158667) where it can be upvoted by yourself and others to increase it's popularity.
