### ISSUE TITLE
[Android] Team Edition: Emoji auto-completion list doesn't change on input

### ISSUE THREAD

**Issue by SmartHoneybee** [mattermost/mattermost-mobile#1573]
#### Summary
Emoji auto-completion list no longer changes on user input.

#### Environment Information
- OS Version: Android 7
- Mattermost App Version: 1.7.0 and 1.7.1
- Mattermost Server Version: 4.8.0

#### Steps to reproduce
* Prepare to write a message.
* Type `:` - emoji auto-completion list appears (suggesting ':100:`:100:`', ':1234:`:1234:`', ...)
* Type 'coffee'.

#### Expected behavior
Emoji auto-completion lists ':coffee: `:coffee:`'.

#### Observed behavior
Emoji auto-completion lists ':100:`:100:`', ':1234:`:1234:`', ...

![not updated](https://user-images.githubusercontent.com/18035422/38430802-98bd497a-39c2-11e8-8941-2074990135c1.png)

#### Possible fixes
Downgrading to 1.6.0 helps. (But that's no long-term solution.)

---
See also: https://pre-release.mattermost.com/core/pl/j1hgu14673ywufsjzju5kadnfc

**Comment by lindy65** [comment]
Hi @SmartHoneybee,

Thanks for your feedback,

I'm not able to reproduce your issue on v1.7.1, build 92, Mattermost server v4.9 (which released today - April 16th).

Could you let us know if this issue still reproduces for you once you have upgraded to the latest version of Mattermost server?

**Comment by SmartHoneybee** [comment]
Hi @lindy65,

sorry for the delay.
Yes, still able to reproduce after the upgrade to Mattermost Team Edition 4.9.0.

Regards,
Bee

**Comment by SmartHoneybee** [comment]
Thanks again, @lindy65.

No longer reproducible after upgrade to v1.8.0.

**Comment by lindy65** [comment]
Good to hear @SmartHoneybee  :)
