### ISSUE TITLE
iOS - Scrolling stutters

### ISSUE THREAD

**Issue by faxe78** [mattermost/mattermost-mobile#1575]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
ios app scrolling stutters.

#### Environment Information

- Device Name: iphone 7 plus
- OS Version: 113
- Mattermost App Version:  1.7.1
- Mattermost Server Version: 4.8.0

#### Steps to reproduce
i have a test channel with 30 messages and the scrolling is far away from smooth.

#### Expected behavior
if i try the same with safari on my iphone in the same chatroom it is completely smooth no stuttering.

**Comment by lindy65** [comment]
Hi @faxe78,

Thanks for your feedback,

You might want to try upgrading to the latest version of the [Mattermost server](https://about.mattermost.com/download/) to see if this resolves the scrolling issue for you.

**Comment by faxe78** [comment]
Hi,

Did the upgrade no change in the ios app. In mobile safari i see the dark theme in ios i see some white theme. Maybe the app should use the standard mobile theme?

Greetings

Markus

**Comment by lindy65** [comment]
Hi @faxe78 

Apologies, I'm totally confused, is your issue about scrolling issues or theme colour?

The scrolling issues are fixed in the latest app and server versions. 

If I change my theme in a browser (the actual setting to change it in the app is not yet available) it does display in the app (on Android and iOS).

Please help me understand if I'm not on the right path here :)

**Comment by sudheerDev** [comment]
Hey, @faxe78 are you saying that mobile app the scrolling stutters but on viewing the same channel in safari(i.e accessing webapp mobile version using a browser) the scrolling experience is better?

**Comment by faxe78** [comment]
yes that's i meant the scrolling with safari on an iphone is way better, with the app it stutters.

i was searching for the cause of the stuttering, the light and dark theme mobile code for safari and the code that the mobile app is using maybe there is the reason of the issue. i think safari and the webviews are not 100% the same on ios but i am not a dev.

**Comment by lindy65** [comment]
Thanks @faxe78 @sudheerDev 

I've created a [ticket](https://mattermost.atlassian.net/browse/MM-10291) to investigate the scrolling 
issue in the app.  

I'll close this issue off here for now and we can track via the ticket.
