### ISSUE TITLE
Add channel header modal to channel view

### ISSUE THREAD

**Issue by thomchop** [mattermost/mattermost-mobile#160]
This is an overlay modal which displays the current channel's header. It is triggered by the info icon button in the topbar. The icon button will need to be added.
A channel's header is a plain text field which may contain links or markdown. We won't worry about markdown or hyperlinking in this story.
This term is not to be confused with the topbar/navbar nor the channel dropdown menu (see #111), which are both sometimes referred to as (channel) headers.

![mm-mobile--channel-header-overlay](https://cloud.githubusercontent.com/assets/3317960/21870425/21586d6a-d811-11e6-9746-c420e2b61edb.png)

**Comment by enahum** [comment]
PR https://github.com/mattermost/mattermost-mobile/pull/164
