### ISSUE TITLE
need Sign up function in Mobile version 

### ISSUE THREAD

**Issue by junlicn** [mattermost/mattermost-mobile#1601]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

#### Environment Information

- Device Name:  
- OS Version:  
- Mattermost App Version:  Mobile version 1.7.1
- Mattermost Server Version:  mattermost-4.9.0-linux-amd64

#### Steps to reproduce
How can we reproduce the issue?
need sign up 

#### Expected behavior
Describe your issue in detail.
I have open the register function ion server console panel.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by lindy65** [comment]
Hi @junlicn 

Thanks for your feedback,

Can you try creating an account on our [nightly build server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and let me know if you can successfully log in?

**Comment by junlicn** [comment]
yes,  I have successfully log in with name lijun on my desktop computer.
How I could get a pre-build  mobile client release to test it on my android?

**Comment by lindy65** [comment]
Hi @junlicn 

To install and test on the Beta version you can go [here](https://github.com/mattermost/mattermost-mobile/blob/master/README.md#testing)

**Comment by junlicn** [comment]
In China,  Google Play doesn't work. would you please provide a  github download url like  normal release version: https://github.com/mattermost/mattermost-mobile/releases

**Comment by enahum** [comment]
The apk for the latest release can be found here https://github.com/mattermost/mattermost-mobile/releases/download/v1.7.1/Mattermost.apk and you can find the apk's for every release in https://github.com/mattermost/mattermost-mobile/releases

Sadly the published beta won't be published in the releases on this repo

**Comment by lindy65** [comment]
I'll close this issue off here for now...
