### ISSUE TITLE
Big amount of scrolling and jumping around when opening chat after an interval

### ISSUE THREAD

**Issue by SamSaffron** [mattermost/mattermost-mobile#1607]
#### Summary

When I open up the mattermost app in the morning, the chat window dances around while it catches up with all the chunks of messages overnight.

#### Environment Information

- Device Name: iPhone X
- OS Version: Latest

#### Steps to reproduce

- Open chat app
- Switch to another app
- Post 100 messages
- Open chat app

#### Expected behavior

- Messages do not "dance" focus is stable, UI is visually stable

#### Observed behavior

- For 5 to 10 seconds stuff jumps around and I am not sure what position I am at or will end at

#### Possible fixes

- Hold off on updating UI until you finish figuring out state of chat.

**Comment by lindy65** [comment]
Hi @SamSaffron 

Could you share which app version you have installed as well as which version of Mattermost server is running?

You can check this by tapping the 3-dot main menu >Settings >About Mattermost

**Comment by lindy65** [comment]
We have [this ticket](https://mattermost.atlassian.net/browse/MM-10317) open to address the jumping/scrolling.

**Comment by lindy65** [comment]
Hi @SamSaffron - is your issue resolved? (apart from the scrolling which is still under investigation by our engineers)

**Comment by SamSaffron** [comment]
It is still behaving very erratically every time I open it in the morning
but I guess you can close if you are tracking this elsewhere

**Comment by amyblais** [comment]
@SamSaffron Can you share which app version you are using as well as which version of Mattermost server is running?

**Comment by SamSaffron** [comment]
Hi Amy

Running app version 1.8.0 build 101 on iOS store and server version 4.9.2,
db is postgres

**Comment by amyblais** [comment]
Thank you for the additional information @SamSaffron! Does this ticket that we have open describe what you are seeing: https://mattermost.atlassian.net/browse/MM-10317? Would you have a screenshot / video to share about what you are experiencing?

**Comment by SamSaffron** [comment]
Yes that looks correct to me! It describes my issue.(does not take minutes
to stabilize just 5-15 seconds)

**Comment by amyblais** [comment]
Thanks for letting me know! We can track this issue with that ticket, I also added a link to this Github issue in the Jira ticket.

**Comment by amyblais** [comment]
Closing this issue for now as this can be tracked with the ticket https://mattermost.atlassian.net/browse/MM-10317.
