### ISSUE TITLE
I cannot find the function of language setting

### ISSUE THREAD

**Issue by AL-Cui** [mattermost/mattermost-mobile#1618]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
i found the react-native-i18n.but,I can not found the function of language setting in “mattermost-mobile/app/screens/settings/display_settings”

#### Environment Information

- Device Name: Android 7.1
- OS Version: 
- Mattermost App Version: Mobile version 1.7.1
- Mattermost Server Version:mattermost-4.9.0-linux-amd64

#### Steps to reproduce
build and run Mobile version 1.7.1 on Android device.

#### Expected behavior
I used the 'mattemost classic' on IOS device.But, I can not found the function of language setting in the source code.

**Comment by enahum** [comment]
@AL-Cui I do not know exactly what you mean, but in any case the translation files can be found here https://github.com/mattermost/mattermost-mobile/tree/master/assets/base/i18n let me know if this isn't what you mean

**Comment by AL-Cui** [comment]
Ok,I know the i18n.I want to say that I can not find the button of language setting

**Comment by lindy65** [comment]
Hi @AL-Cui 

If you're looking to change the language setting from within the UI, you'll need to change it in a browser first by going to the "hamburger menu", selecting "Account Settings" > "Display" > "Language".  This will change the language and then when you log in on mobile, the language will be what you changed it to.

We're still working on incorporating these settings into the mobile app.

**Comment by AL-Cui** [comment]
@lindy65 Hi,
I compiled the "mattermost-mobile" source code and run it on **Android device**.Then,I selecting "Account Settings" > "Display",i can not find the "Language". There is only one button,"Clock display"。

 Does the "language" function have not been done yet，or,I downloaded the wrong source code.I downloaded the source code from this link,"https://github.com/mattermost/mattermost-mobile.git".

Thank u vary much!

**Comment by lindy65** [comment]
Hi @AL-Cui 

The feature cannot be set on mobile yet.  You'll need to log into your account on browser, set the language and then log in on Android device.

**Comment by AL-Cui** [comment]
@lindy65 
OK,Thank u!
Do you know that how to download the "mattermost classic"source code.I found a APP named "mattermost classic" rather than "mattermost beta".The interface of this APP  is similar to the  browser that you said. And,this APP has the "Language Setting"function. Do you know this?And ,Do you know how to download the source code about mobile device.

**Comment by lindy65** [comment]
Hi @AL-Cui 

My pleasure,

You can find information on compiling your own apps [here](https://docs.mattermost.com/mobile/mobile-compile-yourself.html)

Hope this helps?

**Comment by AL-Cui** [comment]
@lindy65 
Thank you vary much!
I found the source code what I want from [here](https://github.com/mattermost/mattermost-android-classic)

**Comment by lindy65** [comment]
Fantastic, thanks for posting back @AL-Cui :)  I'll close this issue off here then ...
