### ISSUE TITLE
uws problem

### ISSUE THREAD

**Issue by underst00d** [mattermost/mattermost-mobile#1624]
#### Summary
[Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'

#### Environment Information

- Device Name: Mac
- OS Version: High Sierra
- Node: v10.0.0
- Xcode: Version 9.4 beta (9Q1004a)
- Mattermost App Version: latest (b7d58ed3eabe54aa4881def55289c603b1d1494c)
- Mattermost Server Version: N/A

#### Steps to reproduce
New to Mattermost. Just followed the official instructions to setup the dev env and make pre-run. then make start

#### Observed behavior
    make start
    Starting React Native packager server
    [RemoteDev] Start server...
    --------------------------------------------------------------------------------

       [Busy] Launching SocketCluster
    1524702441603 - Origin: Worker (PID 10465)
       [Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
        at native (/Users/abc/Desktop/work/mattermost-mobile/node_modules/uws/uws.js:38:19)
        at Object.<anonymous> (/Users/abc/Desktop/work/mattermost-mobile/node_modules/uws/uws.js:42:3)
        at Module._compile (internal/modules/cjs/loader.js:678:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
        at Module.load (internal/modules/cjs/loader.js:589:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
        at Function.Module._load (internal/modules/cjs/loader.js:520:3)
        at Module.require (internal/modules/cjs/loader.js:626:17)
        at require (internal/modules/cjs/helpers.js:20:18)
        at new SCServer (/Users/abc/Desktop/work/mattermost-mobile/node_modules/socketcluster-server/scserver.js:98:18)
    1524702441611 - Worker 0 exited - Exit code: 1

The log file mattermost-mobile/node_modules/uws/build_log.txt:

    In file included from ../src/addon.cpp:3:
    ../src/http.h:31:115: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
                        args.GetReturnValue().Set(String::NewFromOneByte(args.GetIsolate(), (uint8_t *) header.value, String::kNormalString, header.valueLength));

**Comment by enahum** [comment]
Hi @underst00d,

I had the same iasue happening for me yesterday where the uws dependency didn’t install correctly.

Have you tried a make clean and then run again?

**Comment by underst00d** [comment]
@enahum tried that and deleted node_modules folder. still no luck

**Comment by sherifelgafary** [comment]
I have the same issue on a machine running high sierra while on one running sierra it works fine could u please help me

**Comment by amyblais** [comment]
Hi @sherifelgafary, thank you for reporting this, 

Can you help provide more details on your Environment, any observed behaviour and any repro steps that you may have (or let me know if these match with the original reporter's information)?

**Comment by sherifelgafary** [comment]
thanks a lot for helping

my OS version is 10.13.4
XCode 9.3 (but it doesn't matter as the issue generated from terminal)

i just ran the commands : 
make pre-run
npm install
make start

and i had the same issue as the reporter's issues 

i tried cleaning the node-modues directory and re-installing using yarn also the issue still there  

while i tried the same project with the same steps on another machine with OS sierra and it works fine

**Comment by amyblais** [comment]
@sherifelgafary @underst00d Have you had a chance to check with https://github.com/uNetworking/uWebSockets?

**Comment by cburn11** [comment]
I received this error after following the mobile build environment guide. I solved it by specifically installing node@6 (instead of brew install node, which installed node@8)

**Comment by amyblais** [comment]
Hi @cburn11,

Is this the doc that you are referring to: https://docs.mattermost.com/developer/mobile-developer-setup.html?highlight=mobile%20build#development-environment-setup?

I'll check with our engineers whether there is something in our docs that should be adjusted.

**Comment by dbarden** [comment]
Yeah, downgrading from Node 10 should solve it. The steps I did were roughly:

```
brew install node@8
brew unlink node
brew link --overwrite --force node@8

rm -rf node_modules
npm cache clean --force

make pre-run
npm install

make run-ios
```

**Comment by nicolinuxfr** [comment]
I have the same problem and I'm also using node 10. So I guess I should downgrade as well ?

**Comment by enahum** [comment]
This is an issue from one of the RN dependencies and does not work with node 10, so any other version below 10 should solve this

**Comment by matterkit** [comment]
Thanks @dbarden  ...Can we have this in the ReadMe ? 

https://github.com/mattermost/mattermost-mobile/issues/1624#issuecomment-391249799

**Comment by yakimant** [comment]
Has the same, the downgrade of node helped.
