### ISSUE TITLE
EXC_BAD_ACCESS Attempted to dereference garbage pointer

### ISSUE THREAD

**Issue by JAStanton** [mattermost/mattermost-mobile#1626]
So, this is similar to my other ticket (https://github.com/mattermost/mattermost-mobile/issues/1625) in the sense that I was digging around your source to try to see if you fixed that issue and discovered you attempted to fix "EXC_BAD_ACCESS Attempted to dereference garbage pointer" by upgrading to react-native-sentry 0.34.0. I also am seeing this error (tracked officially here https://github.com/getsentry/react-native-sentry/issues/328), but I am curious if bumping to 0.34.0 did the trick for you or if you still see this exception?

If this isn't appropriate to post as a Github issue feel free to close it, but if it isn't a burden to check if the issue stopped after deploying it would help quite a bit :) thanks!

**Comment by koxen** [comment]
hi, our problems with exc_bad_access are related to this bug: https://github.com/facebook/react-native/issues/6117#issuecomment-379146076

**Comment by JAStanton** [comment]
@koxen thank you for this tip! Sounds like it's still unresolved :) I'll go ahead and close this ticket then. Thanks for letting me bug you!
