### ISSUE TITLE
Speed up

### ISSUE THREAD

**Issue by emresaracoglu** [mattermost/mattermost-mobile#1642]
Hello,

The average speed of opening the application is 5 seconds (On both platforms, iOS & Android). Could you shorten this opening speed for next versions?

Thank you.

**Comment by koxen** [comment]
Hi,
Most of the work to fix it have already been _done_(it's blazing fast with all patches applied :D) but we are now working on fully integrating it upstream, which is harder.
For example removing non-us locale files shrinks 1-2s from startup time, but we can't push such thing upstream, so we are working on a more complicated solutions for loading non-us locales. etc.
Here's one of the bigger pull request that I've been coworking on with guys from Uber: https://github.com/mattermost/mattermost-mobile/pull/1598, but it's work in progress.

**Comment by emresaracoglu** [comment]
Fantastic. I reviewed the link you sent. 
I hope this problem will disappear in a short time on both platforms.
