### ISSUE TITLE
"Return" button sets a new line in mattermost chat instead of sending the message

### ISSUE THREAD

**Issue by l0Op3r** [mattermost/mattermost-mobile#1678]
#### Summary
"Return" button sets a new line in mattermost chat instead of sending the message

#### Environment Information

- Device Name: iPad Pro
- OS Version: iOS 11
- Mattermost App Version: 1.8.0 (Build 101)
- Mattermost Server Version: 4.9.0

#### Steps to reproduce
How can we reproduce the issue?
1. Start a new chat with another person. 
2. Type a message, press return on Apple's official iPad keyboard.
3. Message does not send but goes to new line.

#### Expected behavior
Have an ability to configure the return button to send messages instead of going to a new line.

#### Observed behavior
"Return" button sets a new line in mattermost chat instead of sending the message.

#### Possible fixes
In Advanced Settings, set the ability for a user to allow the return button to send the message instead of having the user to click on the send message button.

**Comment by koxen** [comment]
I think the preferred way here is to use ctrl+enter.

**Comment by enahum** [comment]
There is a Help-Wanted ticket if you want to work on it ;)
https://github.com/mattermost/mattermost-server/issues/8797

**Comment by amyblais** [comment]
Hi @l0Op3r!

Thanks for the report! As Elias mentioned we have created a [Help Wanted issue here](https://github.com/mattermost/mattermost-server/issues/8797) and are looking for community's help. Would you be interested helping with a pull request?
