### ISSUE TITLE
Apps built from source don't receive push notifications; DeviceId column in Sessions table is empty

### ISSUE THREAD

**Issue by cburn11** [mattermost/mattermost-mobile#1687]
#### Summary
Android mobile apps compiled from source (following https://docs.mattermost.com/developer/mobile-developer-setup.html) built with "make build-android" & "make unsigned-android" don't receive push notifications. When apps built from source are signed in to the local server, they work. However they don't receive push notifications, and the sql table Sessions in the mattermost DB does not contain an entry in the DeviceId column. On the same phones, clients logged in to the same local server the client app from the play store do have a DeviceId entry in the Sessions table, and do receive push notifications if the server is set to use the push-test proxy.

#### Environment Information

- Device Name: Android
- OS Version: 7 & 8.1 
- Mattermost App Version: 1.8.0
- Mattermost Server Version: 4.8.1 & 4.10.0

#### Steps to reproduce
I have followed the guide: https://docs.mattermost.com/developer/mobile-developer-setup.html
and have signed and unsigned APKs built with a google-services.json file modified for my account. I have a a server running 4.10.0 running and pointed at custom push proxy which uses my google key. All of which seem to work without issue, except apps built from source don't receive push notifications.

I have attached the Sessions table from the mariadb which shows the clients that signed in using apps from the play store have entries in the DeviceId column and the client that is signed in with signed app built from source does not have an entry in the DeviceId column. 

Edit: After help from @koxen the issue seems to have been unique to my fork of the master branch, and does not exist when I clone directly from master.

[mattermost-db-table-Sessions.txt](https://github.com/mattermost/mattermost-mobile/files/2023790/mattermost-db-table-Sessions.txt)

**Comment by koxen** [comment]
> I have followed the guide: https://docs.mattermost.com/developer/mobile-developer-setup.html
and have signed and unsigned APKs built with a google-services.json file modified for my account. I have a a server running 4.10.0 running and pointed at custom push proxy which uses my google key. All of which seem to work without issue, except apps built from source don't receive push notifications.

works fine for me. did you follow the part with gcmSenderId?

**Comment by koxen** [comment]
if you think the Deviceid is wiped from sessions that might be caused by push proxy getting an "invalid api key" etc. response from google. please check what your push proxy log says

**Comment by koxen** [comment]
please check the push proxy log like I mentioned

**Comment by koxen** [comment]
after digging a little bit DeviceId == null seems to be caused by GCM registration error. please check what your android logcat says about this

**Comment by amyblais** [comment]
Hi @cburn11! Just checking in - did koxen's note above help?

**Comment by cburn11** [comment]
I have not been able to resolve the issue.

**Comment by amyblais** [comment]
@koxen Would you know how to troubleshoot this further, or just let me know if you're not sure and I can grab one of our devs to take a look at this!

**Comment by koxen** [comment]
@amyblais as I said I need the android logcat logs and in case they show nothing, then proxy log

**Comment by amyblais** [comment]
Thanks koxen! @cburn11 please help with the information requested above ^ or let me know any questions.

**Comment by cburn11** [comment]
According to the device logs, the application seems to get a device id from GCM:

[ 05-25 10:35:25.950 24599:24631 D/ReactNativeNotifs ]
GCM is refreshing token... instanceId=dJmSrjJVt2I

[ 05-25 10:35:25.953 24599:24631 I/ReactNativeNotifs ]
GCM has a new token: instanceId=dJmSrjJVt2I, token=eQ_R52X-BrI:APA91bEjVIxNWuP-3QX73ixZfyL4Nf9ru_3ZyWfeb4KEQfRikm0cOG3TWPnJ-EXnCjlgYO
KzWcfjV6b7n0wcJVdPrsTM1QxDC3YQYaLn7T2mvvkgKbnQFh_T9x1-N6ojxZck8U1TmGi5

However, the application never actual sends the device id to the application server. The traffic between nginx (10.0.0.118) and the application server (10.0.0.140) shows that the POST request to /api/v4/users/login contains a blank device_id field: {"device_id":"" ...

[nginx-mm-login.txt](https://github.com/mattermost/mattermost-mobile/files/2040465/nginx-mm-login.txt)

The issue is not with the push proxy server.

**Comment by cburn11** [comment]
Well I might have to take "The issue is not with the push proxy server." back. If I manually insert the deviceId from logcat into the db:

MariaDB [(none)]> update Sessions set DeviceId = 'android_rn:eQ_R52X-BrI:APA91bEjVIxNWuP-3QX73ixZfyL4Nf9ru_3ZyWfeb4KEQfRikm0cOG3TWPnJ-EXnCjlgYOKzWcfjV6b7n0wc
JVdPrsTM1QxDC3YQYaLn7T2mvvkgKbnQFh_T9x1-N6ojxZck8U1TmGi5' where UserId='kbfd56di8b8mifos5jqsyhswko';

And then do something to generate a push notification for that session:

[2018/05/25 11:26:40 PDT] [DEBG] Sending push notification to device eQ_R52X-BrI:APA91bEjVIxNWuP-3QX73ixZfyL4Nf9ru_3ZyWfeb4KEQfRikm0cOG3TWPnJ-EXnCjlgYOKzWcfjV6b7n0wcJVdPrsTM1QxDC3YQYaLn7T2mvvkgKbnQFh_T9x1-N6ojxZck8U1TmGi5 for user kbfd56di8b8mifos5jqsyhswko with msg of 'clifford: hello'

The push-proxy spits out:

2018/05/25 11:13:49 INFO Loading /opt/matter-push-proxy/config/config-push-proxy.json
2018/05/25 11:13:49 INFO Push proxy server is initializing...
2018/05/25 11:13:49 INFO Server is listening on :8067
2018/05/25 11:26:40 ERROR Missing platform property

**Comment by koxen** [comment]
do you have android_rn section in config?

 "AndroidPushSettings":[
   {
       "Type":"android",
       "AndroidApiKey":"xx"
   },
   {
       "Type":"android_rn",
       "AndroidApiKey":"xx"
   }
 ]

**Comment by cburn11** [comment]
Yes, the proxy config is setup the way described:

clifford@push-proxy-server:/opt/matter-push-proxy$ cat config/config-push-proxy.json

{
    "ListenAddress": ":8067",
    "ThrottlePerSec": 300,
    "ThrottleMemoryStoreSize": 50000,
    "ThrottleVaryByHeader": "X-Forwarded-For",
    "ApplePushSettings":[
           {
               "Type":"apple",
               "ApplePushUseDevelopment":false,
               "ApplePushCertPrivate":"",
               "ApplePushCertPassword":"",
               "ApplePushTopic":"com.mattermost.Mattermost"
           },
        {
            "Type":"apple_rn",
            "ApplePushUseDevelopment":false,
            "ApplePushCertPrivate":"",
            "ApplePushCertPassword":"",
            "ApplePushTopic":"com.mattermost.react.native"
        }
    ],
    "AndroidPushSettings": [
            {
                "Type" : "android",
                "AndroidApiKey": "XX[Legacy key]XX"
            },
            {
                "Type" : "android_rn",
                "AndroidApiKey": "XX[Legacy key]XX"
            }
    ]
}

Interestingly, when the proxy gives the message "2018/05/28 07:31:36 ERROR Missing platform property", the http request from the app server does contain {"platform":"android_rn" ...

[mmserver-proxy-http-push-notification.txt](https://github.com/mattermost/mattermost-mobile/files/2045440/mmserver-proxy-http-push-notification.txt)

**Comment by cburn11** [comment]
I can send a message directly to the GCM service and it gets delivered to the phone from which I pulled the deviceId from logcat:

clifford@Office-PC:/mnt/c/Users/Clifford$ curl -X POST --header "Authorization: key=XX[Legacy API key]XX" --Header "Content-Type: applicat
ion/json" https://fcm.googleapis.com/fcm/send -d "{\"to\":\"cS4qSV_9YFA:APA91bFSYdgl-nUfTEmXQzjc9RlsLIqZCZuJB6G6bkDUU5qXYkphkuzUTqhY7RdmnEIpUOTTSA5k7Gl9RVUL_
vQglg8S186jEzGzrGzYGyXNex-VNnPuZq0y978MpCukD7gY06HhWJvq\",\"notification\":{\"body\":\"Test Msg\"},\"priority\":10}"; echo

The response indicates success:
{"multicast_id":5070496320441294703,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1527523103142862%e1881a69e1881a69"}]}

and the notifcation shows up on the phone. 

So my first problem is definitely in the mobile app itself where the deviceid is never sent to the app server. And it looks like there is a second issue with the push proxy server.

**Comment by koxen** [comment]
you sure your mobile app is build from master?

**Comment by cburn11** [comment]
I forked the master branch 8 days ago and have been cloning drom that.On May 28, 2018 4:53 PM, Michał Odziemczyk <notifications@github.com> wrote:you sure your mobile app is build from master?

**Comment by koxen** [comment]
please try latest master.
If it still doesn't work you can add a breakpoint here https://github.com/mattermost/mattermost-mobile/blob/e8712f9199b8f8e337adae3391fd354f9ef83e85/app/screens/entry/entry.js#L148 and see what happens

**Comment by cburn11** [comment]
Good call. The issue is not present when I build from source cloned directly from the master branch rather than my fork. I have no idea what happened in my fork, and I am not really interested in investigating. Thanks for sticking with me. I appreciate your help.

**Comment by rAnAaRsl** [comment]
i am facing the same issue app does not update deviceid in the session however when i send notification from firebase console my app receives the notification

**Comment by rAnAaRsl** [comment]
i had cloned master just 2 days ago

**Comment by amyblais** [comment]
Hi @rAnAaRsl, sorry to hear that!

Here are some suggestions to further troubleshoot this:

Have you followed the documentation here: https://docs.mattermost.com/developer/mobile-developer-setup.html?

Can you provide any other information about your environment, e.g. device name, OS version, Mattermost App version, Mattermost Server version?

Can you help share your push proxy logs?

**Comment by uusijani** [comment]
A hint for anyone googling for this: make sure that the value of <code>gcmSenderId</code> in your <code>AndroidManifest.xml</code> still has <a href="https://github.com/mattermost/mattermost-mobile/blob/0af947476e31d8dac26950807c3cf49d93443a16/android/app/src/main/AndroidManifest.xml#L24">the trailing backslash (\\)</a> after you've changed the project number to your own. <a href="https://stackoverflow.com/questions/2154945/how-to-force-a-meta-data-value-to-type-string/2155358">Otherwise the value gets interpreted as int, when it should be a string</a>, which is one way to trigger the issue of devices being assigned empty/null IDs.

(<a href="https://developers.mattermost.com/contribute/mobile/build-your-own/#set-up-android-to-receive-push-notifications">The building instructions do have this documented in bold</a>, but it's still very easy to miss, I know I did. Complicating the debugging was my Nexus 5X, which kept getting a proper device ID even when all other devices using the same broken build failed to.)
