### ISSUE TITLE
make Command issue

### ISSUE THREAD

**Issue by rAnAaRsl** [mattermost/mattermost-mobile#1705]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

#### Environment Information

- Device Name: Motorola Turbo
- OS Version: Linux
- Mattermost App Version: 
- Mattermost Server Version:

#### Steps to reproduce
How can we reproduce the issue?
make build-android

#### Expected behavior
Describe your issue in detail.
UWebsocket issue of not compiling .cpp file because of the absence of c++11 compiler in linux  
#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by rAnAaRsl** [comment]
on windows 10

**Comment by amyblais** [comment]
Hi @rAnAaRsl! Thank you for reaching out.

I would need a little more information to troubleshoot the issue you are seeing, can you help fill in the above form? Let me know if you have any questions!

**Comment by rAnAaRsl** [comment]
i have editted my question

**Comment by amyblais** [comment]
Hi @rAnAaRsl, thank you for the additional information! 

Was there any specific documentation that you followed when trying to make build-android? 

Recently also [this issue](https://github.com/mattermost/mattermost-mobile/issues/1624) was opened, and it might be related to the issue you are seeing - can you help attach here what code you are using and whether you are using node10?

Let me know if this doesn't help and if you have any questions!

**Comment by amyblais** [comment]
Hi @rAnAaRsl! Was the issue resolved for you? Let us know if not and I can ask one of our engineers to further troubleshoot this.
