### ISSUE TITLE
Support self-signed certificate

### ISSUE THREAD

**Issue by aborderon** [mattermost/mattermost-mobile#1724]
#### Summary
Can not connect to server using self signed certificate

#### Environment Information

- Device Name: OnePlus 5T (Android 8)
- OS Version: Ubuntu 16.04
- Mattermost App Version: 1.8.0
- Mattermost Server Version: 4.10

#### Steps to reproduce
Set up a Mattermost server and point a domain to it that is using a self signed certificate

#### Expected behavior
The app should be able to connect to the server.

#### Observed behavior
I keep getting a message “Cannot connect to the server. Please check your server URL and internet connection.”

#### Possible fixes
I know very well that mattermost-mobile does not support self-signed certificate. I can not use let'encrypt because our mattermost server is in a private network not accessible from the outside.

Have you planned to support the self-signed certificate? If yes, how long?

Thank you

**Comment by aborderon** [comment]
Alright I understand. Because it is a real problem for use mattermost in a private network.

**Comment by amyblais** [comment]
Hi @aborderon! Sounds like there is nothing we can do at this point on our end, so I'll close this Issue for now.
