### ISSUE TITLE
OAuth not working when GitLab still requires acceptance of TOS

### ISSUE THREAD

**Issue by svelle** [mattermost/mattermost-mobile#1756]
#### Summary
When the GitLab instance that the user wants to OAuth with has a TOS that still needs to be accepted the mobile app will only return: ``` Could not parse auth data out of gitlab user object ```

#### Environment Information

- Device Name: LG Nexus 5X
- OS Version: Android 8.1
- Mattermost App Version: 1.9
- Mattermost Server Version: 4.9.1

#### Steps to reproduce
Enable some kind of TOS for the users to accept in the GitLab instance used for OAuth and try to login with the mobile app without having accepted the TOS

#### Expected behavior
I would expect some kind of screen to either tell the user what the problem is, or even give the user the possibility to accept the TOS from within the app.

#### Observed behavior
App only returns a screen that says:
``` Could not parse auth data out of gitlab user object ```

### Note
I'm not 100% sure this is the right place to post this as this could also be seen as an issue with the OAuth implementation that GitLab uses/the information GitLab returns when trying to authenticate using OAuth.

**Comment by amyblais** [comment]
Hi @svelle! Thank you for reaching out.

Next step is that I will test this out / ask a colleague to help test this.

**Comment by amyblais** [comment]
@svelle Came to my mind - which build version of 1.9 are you using?

**Comment by svelle** [comment]
@amyblais So this is still happening with the 1.9 stable release. On Android and iOS. Server Version is still 4.9.1

**Comment by amyblais** [comment]
@hmhealey Do you know if this is a known issue or would it help if I ask QAs to test it and then open a ticket if they can repro? Is this at all related to the ticket open here: https://mattermost.atlassian.net/browse/MM-10573?

**Comment by hmhealey** [comment]
It's the same issue as that, but this one affects the mobile app instead of the web app. I think we should file a separate ticket for this issue on mobile since it requires some more work than the web app which just needs better error text.

**Comment by hmhealey** [comment]
Thanks for the report @svelle and thanks for filing that @amyblais!

**Comment by hmhealey** [comment]
This was actually fixed in Mattermost 5.0 by https://github.com/mattermost/mattermost-server/pull/8949. If you're using the bundled Mattermost instance, the latest version of GitLab now ships with Mattermost 5.0
