### ISSUE TITLE
Unable to login with GitHub

### ISSUE THREAD

**Issue by jekil** [mattermost/mattermost-mobile#1774]
#### Summary
Usually I login to gitlab via openID with github. When trying to login via app, the openid login is not available.

#### Environment Information

- Device Name: iphone 6s
- OS Version: 11.4 (updated today)
- Mattermost App Version: 1.8.0 (updated today)
- Mattermost Server Version: dunno

#### Steps to reproduce
Create a gitlab account via openid with github.
Install and login via app.

#### Expected behavior
Login with my github credentials via openid

#### Observed behavior
Login is available only with gitlab credentials

**Comment by amyblais** [comment]
Hi @jekil! Thank you for reporting this.

You can find out your Server version by clicking the menu (three dots) on the right hand side > Settings > About Mattermost.

Also, do you see the same issue when you try to log in from the browser?

**Comment by jekil** [comment]
It is a first time install (setup from scratch, no upgrade).

**Comment by amyblais** [comment]
@enahum Can you help confirm if we support logging in to Gitlab via openID with Github?

**Comment by enahum** [comment]
The official support is for gitlab login, if your gitlab uses another auth method that is secondary to gitlab we do not officially support it

**Comment by amyblais** [comment]
@jekil It looks we don't officially support this yet - you can upvote this [feature request](https://mattermost.uservoice.com/forums/306457-general/suggestions/10197642-support-openid-connect) or open a new feature request! If you open a new feature request, please include a link back to this GitHub issue.

**Comment by amyblais** [comment]
Hi @jekil, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
