### ISSUE TITLE
No message previews shown in iOS push notifications

### ISSUE THREAD

**Issue by jfew** [mattermost/mattermost-mobile#1802]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Despite having configured Mattermost.app push notifications to always show a message preview in push notifications, they are never shown.

#### Environment Information

- Device Name: iPhone X
- OS Version: iOS 11.4
- Mattermost App Version: 1.9.0
- Mattermost Server Version: 4.10.1

#### Steps to reproduce
How can we reproduce the issue?
1. On an iOS 11.4 device with Mattermost installed, confirm under Settings > Mattermost > Notifications that "Show as Banners (Persistent)" is enabled.
2. Send a message to the Mattermost user signed into that device that would trigger a push notification per that user's settings on the server side.

#### Expected behavior
Push notification appears on iOS 11.4 device with message preview included.

#### Observed behavior
A generic push notification is shown (e.g. "User mentioned you").

#### Possible fixes
Unknown.

**Comment by amyblais** [comment]
Hi @jfew! Thank you for reporting this.

We added some push notification styling improvements in v5.0 and the message preview shows on that version (I just tested), so I'll need to ask the team about what is expected on v4.10. I'll let you know the feedback.

**Comment by enahum** [comment]
Can you share your server config? I’m interested in the push notification part

**Comment by amyblais** [comment]
Hi @jfew! This is the part of the config that Elias was referring to: https://docs.mattermost.com/administration/config-settings.html#push-notification-contents. Changing that setting might help with the issue you are seeing.

**Comment by amyblais** [comment]
Hi @jfew, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
