### ISSUE TITLE
docker-compose spins up Postgress, and broken docker ps -a

### ISSUE THREAD

**Issue by mabushey** [mattermost/mattermost-mobile#1807]
#### Summary
docker-compose does not bring up a healthy environment. Postrgess is running happy, but web_1 is pretty unhappy it cannot reach mysqladmin.

```
2018/06/22 21:08:39 [error] 9#9: *32 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.144.191.120, server: , request: "GET /phpMyAdmin.old/index.php HTTP/1.1", upstream: "http://172.20.0.4:8000/phpMyAdmin.old/index.php", host: "52.26.9.211"
192.144.191.120 - - [22/Jun/2018:21:08:39 +0000] "GET /phpMyAdmin.old/index.php HTTP/1.1" 502 166 "-" "Mozilla/5.0" "-"
2018/06/22 21:08:42 [error] 9#9: *32 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.144.191.120, server: , request: "GET /pma-old/index.php HTTP/1.1", upstream: "http://172.20.0.4:8000/pma-old/index.php", host: "52.26.9.211"
192.144.191.120 - - [22/Jun/2018:21:08:42 +0000] "GET /pma-old/index.php HTTP/1.1" 502 166 "-" "Mozilla/5.0" "-"
2018/06/22 21:08:45 [error] 9#9: *32 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.144.191.120, server: , request: "GET /claroline/phpMyAdmin/index.php HTTP/1.1", upstream: "http://172.20.0.4:8000/claroline/phpMyAdmin/index.php", host: "52.26.9.211"
192.144.191.120 - - [22/Jun/2018:21:08:45 +0000] "GET /claroline/phpMyAdmin/index.php HTTP/1.1" 502 166 "-" "Mozilla/5.0" "-"
2018/06/22 21:08:49 [error] 9#9: *32 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.144.191.120, server: , request: "GET /typo3/phpmyadmin/index.php HTTP/1.1", upstream: "http://172.20.0.4:8000/typo3/phpmyadmin/index.php", host: "52.26.9.211"
192.144.191.120 - - [22/Jun/2018:21:08:49 +0000] "GET /typo3/phpmyadmin/index.php HTTP/1.1" 502 166 "-" "Mozilla/5.0" "-"
192.144.191.120 - - [22/Jun/2018:21:08:52 +0000] "GET /phpma/index.php HTTP/1.1" 502 166 "-" "Mozilla/5.0" "-"
2018/06/22 21:08:52 [error] 9#9: *32 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.144.191.120, server: , request: "GET /phpma/index.php HTTP/1.1", upstream: "http://172.20.0.4:8000/phpma/index.php", host: "52.26.9.211"
192.144.191.120 - - [22/Jun/2018:21:08:55 +0000] "GET /phpmyadmin/phpmyadmin/index.php HTTP/1.1" 502 166 "-" "Mozilla/5.0" "-"
2018/06/22 21:08:55 [error] 9#9: *32 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.144.191.120, server: , request: "GET /phpmyadmin/phpmyadmin/index.php HTTP/1.1", upstream: "http://172.20.0.4:8000/phpmyadmin/phpmyadmin/index.php", host: "52.26.9.211"
2018/06/22 21:08:58 [error] 9#9: *32 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.144.191.120, server: , request: "GET /phpMyAdmin/phpMyAdmin/index.php HTTP/1.1", upstream: "http://172.20.0.4:8000/phpMyAdmin/phpMyAdmin/index.php", host: "52.26.9.211"
```

#### Environment Information

- Device Name: 
- OS Version: Ubuntu 18.04
- Mattermost App Version: 
- Mattermost Server Version:
mattermostdocker_db                                   latest              0f3808b4fe0a        24 minutes ago      387MB
mattermostdocker_app                                  latest              27688daa8416        27 minutes ago      228MB
mattermostdocker_web                                  latest              e03196406998        27 minutes ago      19.4MB

#### Steps to reproduce
Change user/passwords in docker-compose in both spots to match
      - POSTGRES_USER=pgsuser
      - POSTGRES_PASSWORD=xxxxxx

uncomment:
      args:
        - edition=team
        - PUID=1000
        - PGID=1000

Not sure what edition is for. My default user user has this UID and GID

#### Expected behavior
Three running containers.  App and Web containers talking to postgress.

#### Observed behavior
Only the DB is running. the _web is marked unhealthy, and app keeps restarting.

#### Possible fixes

Swap out db for Mysql, remove "support" for phpmyadmin.

```
docker logs mattermostdocker_web_1 
...
2018/06/22 21:08:22 [error] 9#9: *32 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.144.191.120, server: , request: "GET /phpmyadmin2/index.php HTTP/1.1", upstream: "http://172.20.0.4:8000/phpmyadmin2/index.php", host: "52.26.9.211"
```
The docker compose specifies Postgress, and that container comes up. 
While I'm happy that's failing as I don't have mysql or phpmyadmin on this server, I'd prefer it tries to talk to the DB it installs.

**Comment by amyblais** [comment]
Hi @mabushey! Thank you for reporting this.

@pichouk The reporter is referring to docker, so just wanted to check in whether this is something you are familiar with?

**Comment by pichouk** [comment]
I'm a bit confused, why is this open on `mattermost-mobile` repository ?
@mabushey Are you using the [`docker-compose.yml`](https://github.com/mattermost/mattermost-docker) provided on `mattermost-docker` repository ?  
Also, are you running other containers on your server ? It seems that your server receive other requests from the server `192.144.191.120`.

**Comment by mabushey** [comment]
> I'm a bit confused, why is this open on mattermost-mobile repository ?
My mistake.

I'm not sure what the problem was, maybe the fourth `docker-compose up` worked. I'll close it out.
