### ISSUE TITLE
IOS Client prompts for password / auth half of the time it is opened.

### ISSUE THREAD

**Issue by sadsfae** [mattermost/mattermost-mobile#1812]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Mattermost client for IOS forgets it's auth when opening every other time it's opened.  Session settings are set to 365 days, session time set to 10 minutes in MM server.  Re-opening the application connects you back most of the time.

Basically every other time it opens it prompts with login.

This is on two different Mattermost instances.

#### Environment Information

- Device Name: iPhone 7
- OS Version: IOS 11.4
- Mattermost App Version: 1.9.0 (Beta) and 1.9.0 (stable build 112)
- Mattermost Server Version: 

This happens on two of my servers only recently in the last IOS client updates.

- 4.10.1 (standalone team edition, Mattermost Auth, CentOS7, Apache reverse proxy)

- 4.9.1 (Gitlab CE bundled, Gitlab Auth, CentOS7, Apache reverse proxy)

#### Steps to reproduce
Connect to Mattermost with either the Beta IOS app or stable, 1/2 the time you get prompted for password or authentication.

#### Expected behavior
IOS app should not prompt for password then work again when closing and opening again.

#### Possible fixes

This seems to happen every other time.  Swiping the app closed and running it again connects usually.

**Comment by sadsfae** [comment]
Additional note here:  Bouncing my `4.9.1` (Gitlab CE) server this seems to have gone away, same with the `4.10.1` (standalone).  I've also upgraded my `4.10.1` to `5.0.0` to see if that makes a difference.

I didn't see anything in logs but this has happened for multiple people on IOS only.

**Comment by amyblais** [comment]
Hi @sadsfae! Thank you for reporting this. 

We just published a v1.9.1 dot release which includes a fix for this issue. Would you like to help upgrade, and then let us know if you still experience the same issue?

**Comment by sadsfae** [comment]
@amyblais thanks for the response, I did indeed just see that update and it hasn't occurred since.  I'm closing this issue now.
