### ISSUE TITLE
Arabic text encoding issue on Android

### ISSUE THREAD

**Issue by abdelrahmanrifai** [mattermost/mattermost-mobile#1815]
#### Summary
There an issue with Arabic text encoding on Android starting version 1.9.0, sometimes Arabic text appears correctly, however after clearing the app cache or uninstall and re-install again all Arabic text appears as following screenshot.

![mattermost](https://user-images.githubusercontent.com/4334778/41969294-3cbea29c-7a07-11e8-8745-8d9238acac6d.png)

#### Environment Information

- Device Name: Pixel 2XL
- OS Version: 8.1.0
- Mattermost App Version:  1.9.1 (Bulid 114)
- Mattermost Server Version: 4.5.0

#### Steps to reproduce
- Open Mattermost Android App >= 1.9.0
- Send any Arabic text message
- Open Settings, Advanced  Settings
- Reset Cache
- Check the Arabic text message you just sent

#### Expected behavior
Arabic text should render normally.

_Please note that everything is working fine on the web version._

**Comment by amyblais** [comment]
Hi @abdelrahmanrifai! Thank you for reporting this.

I'll test this today to see if I can repro, and I'll let you know what I find.

**Comment by amir-khalili** [comment]
We have this problem too! 
Please help us.... 
It`s urgent :(

**Comment by SHKonB612** [comment]
i have the same problem 
i would be thankful if you please solve it

**Comment by LidaEmadi** [comment]
We have The same Problem too
We're glad to help us faster because it's very important
thanks

**Comment by sorooshmh** [comment]
i have this problem,please check it.Thanks.

**Comment by melody80** [comment]
Please take action as soon as possible, it's urgent!
Thanks

**Comment by amyblais** [comment]
Hey all, thank you for reaching out - we have created a ticket to fix this: https://mattermost.atlassian.net/browse/MM-11055

Can you help confirm if you didn't see this issue on v1.8?

**Comment by Ahmed-Ayman** [comment]
it's working fine on 1.8 
this is before resetting the cache.
![before](https://user-images.githubusercontent.com/15092932/41931476-8111c9ee-797e-11e8-8846-7e7f7af652c6.png)

and this one after the reset!
![after](https://user-images.githubusercontent.com/15092932/41931477-813b2d02-797e-11e8-95d6-abcb09edae0c.png)

**Comment by amyblais** [comment]
Thank you! Update: we are working on a 1.9.2 dot release which includes a fix for this issue. I'll let you know when the dot release is out. Stay tuned!

**Comment by amyblais** [comment]
Hi all! v1.9.2 is now available!

**Comment by abdelrahmanrifai** [comment]
Thanks @amyblais for your cooperation. I can confirm that v1.9.2 is working fine!

Thanks again for the whole team for the prompt fix, well done! 🙌
