### ISSUE TITLE
iOS app can't type Chinese 

### ISSUE THREAD

**Issue by scrazy77** [mattermost/mattermost-mobile#1816]
#### Summary
Can't type Chinese .

#### Environment Information

- Device Name: iPhone 7
- OS Version: 11.4
- Mattermost App Version: 1.9.1(Build 114)
- Mattermost Server Version: 4.7.1(Build 4.7.3)

#### Steps to reproduce
Under chat channel, switch to Chinese input method.
Then type Chinese, we should select Chinese words, but it only shows Chinese symbols :
"， 。 ？ ！ 、 … " 
![img_7236 2](https://user-images.githubusercontent.com/100748/41847623-272ed5ce-78ad-11e8-8a4a-5e9b86bd7d0d.jpg)

#### Expected behavior
When type Chinese input character , we could get words list then continue typing, like:
![img_7237](https://user-images.githubusercontent.com/100748/41847532-d64e996e-78ac-11e8-8794-216c3f5612e4.jpg)

**Comment by amyblais** [comment]
Hi @scrazy77, thank you for reporting this 👍 

Letting you know that I've reported this to our engineers as there have been other reports related to Chinese not working on 1.9 and 1.9.1, so we are looking to fix this in a 1.9.2 dot release.

I'll update you on the progress / let you know whether we need any additional information.

**Comment by scrazy77** [comment]
@amyblais  thank you!

**Comment by amyblais** [comment]
Hi @scrazy77! v.1.9.2 was just released to the app stores, so it should be available within a day or two.

**Comment by AkaiWell** [comment]
Hi @amyblais v.1.9.2 still can't type Chinese.

**Comment by scrazy77** [comment]
@amyblais v.1.9.2 still can't type Chinese.

**Comment by amyblais** [comment]
Thanks! I've notified engineers about this.

**Comment by amyblais** [comment]
Hey all! Letting you know that v1.9.3 is now released to the app stores and will be available to download in the next few days.

**Comment by amyblais** [comment]
Hey all, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
