### ISSUE TITLE
unable to complile android app on windows

### ISSUE THREAD

**Issue by andyseubert** [mattermost/mattermost-mobile#1829]
#### Summary
unable to compile app

#### Environment Information

- Device Name: my pc
- OS Version: windows 10
- Mattermost App Version: latest available ANDROID app
- Mattermost Server Version: latest available

#### Steps to reproduce
1follow instructions to set up dev environment attempting to compensate for lack of description for windows environment

#### Expected behavior
I expect the application to compile successfully

#### Observed behavior
failed to compile with the following errors:
2018-06-25 14:31:25,575 [ thread 40]   INFO - .project.GradleProjectResolver - Gradle project resolve error 
org.gradle.tooling.BuildException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.14.1-all.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':app:_debugCompile'.
Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'default' not found.

2018-06-25 14:48:14,391 [ thread 55]   WARN - ect.sync.idea.ProjectSetUpTask - Configuration with name 'default' not found. 
2018-06-25 14:48:14,392 [ thread 55]   INFO - e.project.sync.GradleSyncState - Gradle sync failed: Configuration with name 'default' not found.

**Comment by andyseubert** [comment]
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN commonmark-react-renderer@4.3.3 requires a peer of commonmark@^0.27.0 || ^0.26.0 || ^0.24.0 but none was installed.
npm WARN react-native@0.55.4 requires a peer of react@16.3.1 but none was installed.
npm WARN react-native-doc-viewer@2.7.8 requires a peer of react-native@0.54.3 but none was installed.
npm WARN react-native-doc-viewer@2.7.8 requires a peer of react-native-fs@^2.3.2 but none was installed.
npm ERR! Linux 4.4.0-17134-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! mattermost-mobile@1.3.2 postinstall: `make post-install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mattermost-mobile@1.3.2 postinstall script 'make post-install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mattermost-mobile package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make post-install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mattermost-mobile
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mattermost-mobile
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/AndroidStudioProjects/mattermost-mobile/npm-debug.log

**Comment by andyseubert** [comment]
I tried again using the linux sub-system for windows and got this error
[npm-debug.log](https://github.com/mattermost/mattermost-mobile/files/2134940/npm-debug.log)

**Comment by andyseubert** [comment]
ok maybe progress; now unable to resolve dependencies:

Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-document-picker. Open FileShow Details |  
-- | --
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-keychain. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-doc-viewer. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-video. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-navigation. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-image-picker. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-bottom-sheet. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-device-info. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :reactnativenotifications. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-cookies. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-linear-gradient. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-vector-icons. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-svg. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-local-auth. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :jail-monkey. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-youtube. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-sentry. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-exception-handler. Open FileShow Details |  
Unable to resolve dependency for ':app@unsigned/compileClasspath': Could not resolve project :react-native-fetch-blob. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-document-picker. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-keychain. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-doc-viewer. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-video. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-navigation. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-image-picker. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-bottom-sheet. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-device-info. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :reactnativenotifications. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-cookies. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-linear-gradient. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-vector-icons. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-svg. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-local-auth. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :jail-monkey. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-youtube. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-sentry. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-exception-handler. Open FileShow Details |  
Unable to resolve dependency for ':app@unsignedUnitTest/compileClasspath': Could not resolve project :react-native-fetch-blob. Open FileShow Details |

**Comment by koxen** [comment]
this is not officially supported

**Comment by enahum** [comment]
What version of node and npm are you using? I have not tried this on Windows really so no clue but what I can say for sure is that node 10.x won’t work

**Comment by amyblais** [comment]
Hi @andyseubert, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
