### ISSUE TITLE
Hangs after bringing back from background 

### ISSUE THREAD

**Issue by pwec** [mattermost/mattermost-mobile#1862]
#### Summary
When try to bring back from open apps list (or even just coming back from the list without switching to any other app in a mean time) app completely hangs (see [picture](https://www.dropbox.com/s/qd58k7i36f54pfx/Screenshot_20180630-134647_Mattermost.jpg?dl=0)) and needs to be killed before reopening 

#### Environment Information

- Device Name: samsung galaxy note 8
- OS Version: android 8
- Mattermost App Version: 1.9.2 (Build 117)
- Mattermost Server Version:4.6.0 (Build 4.6.0)

#### Steps to reproduce
Happening every time I minimise it

#### Expected behavior
All in summary

#### Observed behavior
All in summary

#### Possible fixes
No clue

**Comment by koxen** [comment]
is the menu button responsive when the application bugs out?

**Comment by pwec** [comment]
Not at all. Only thing I can do is go to open apps list and close it, then
open it again from home screen.

**Comment by amyblais** [comment]
Hi all! Letting you know that we are working on a 1.9.3 dot release for this issue.

**Comment by pwec** [comment]
Excellent! Thanks.

**Comment by amyblais** [comment]
Hey @pwec! Letting you know that v1.9.3 is now released to the app stores and will be available to download in the next few days.

**Comment by pwec** [comment]
Thanks for info and for super quick reaction!

On 4 Jul 2018 23:46, "amyblais" <notifications@github.com> wrote:

Hey @pwec <https://github.com/pwec>! Letting you know that v1.9.3 is now
released to the app stores and will be available to download in the next
few days.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mattermost/mattermost-mobile/issues/1862#issuecomment-402568630>,
or mute the thread

**Comment by amyblais** [comment]
Hi @pwec, I'll close this Issue for now as there haven't been updates in the past few weeks.

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by pwec** [comment]
I can confirm that issue is solved for me. Thanks
