### ISSUE TITLE
Posts in groups on mattermost are incompletely displayed.

### ISSUE THREAD

**Issue by ejo60** [mattermost/mattermost-mobile#1877]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Mattermost hides a part of a posting on an iphone.+

#### Environment Information

- Device Name: iphone
- OS Version: iOS 11.4
- Mattermost App Version: 1.9.2
- Mattermost Server Version: 5.0.0.

#### Steps to reproduce
Simply browse through posts in a mattermost group, most posts will look fine, but, some of them only list a few lines, the message is not completely displayed. 

#### Expected behavior
An example of what you can expect is here: http://imgshare.free.fr/uploads/d114a8e829.jpg

#### Observed behavior
The observation is attached under expected behavior, no error messages of any sort are displayed.

#### Possible fixes
I'm not enough of a software guy to fix this, but I wanted to share what we found on the https://mattermost.pi9noz.ampr.org/hobbyscoop/channels server.

**Comment by ejo60** [comment]
I modified the image because it did not open the way I expected.

**Comment by ejo60** [comment]
I'm using an iphone 7

**Comment by amyblais** [comment]
Hi @ejo60! Thank you for reporting this.

I wasn't able to repro this but I'm on an v1.10 RC version - I'll check with the team on whether there is a way to test this on a 1.9 version.

I'll let you know the feedback!

**Comment by amyblais** [comment]
Hi @ejo60! 

I'm not able to reproduce this on the same environment - would you have any further details on the situation around the issue, e.g.

1. what types of channels you are seeing this on (DMs, public channels, etc.)?
2. does it happen when you come to the app after clicking on a push notification?
3. do those posts ever look normal, e.g. after a refresh or logging out?

**Comment by amyblais** [comment]
Hi @ejo60! Thank you for the additional details.

We are currently working on testing for 1.10 beta (and server v5.1), so I'll keep an eye on this for a few days (also on 1.9.x).

**Comment by amyblais** [comment]
Hi @ejo60! We haven't been able to repro this, would you like to update to the latest app version (v1.10, build 127) to see if the issue is resolved?

**Comment by ejo60** [comment]
Ok I will

**Comment by amyblais** [comment]
Hi @ejo60! Checking in - has the issue been reproducing on the latest version?

**Comment by ejo60** [comment]
Next I restarted the mattermost app, problem gone.

**Comment by amyblais** [comment]
Hi @ejo60, we did have this ticket open to investigate this but it was closed because we haven't been able to reproduce the issue: https://mattermost.atlassian.net/browse/MM-11573. I'll check with team if the ticket should be re-opened for further investigation.
