### ISSUE TITLE
PDF file download still possible when enableMobileDownload is set to false

### ISSUE THREAD

**Issue by avasconcelos114** [mattermost/mattermost-mobile#1895]
#### Summary
PDF files can still be downloaded when an user accesses the file through separate viewer

#### Environment Information

- Device Name: iPhone 6s 
- OS Version: iOS 11.4
- Mattermost App Version: 1.9.2 
- Mattermost Server Version: 5.0

#### Steps to reproduce
1. Set `enableMobileDownload` to `false` on the server's `config.json` file
2. Upload a PDF file on a channel
3. Through the mobile app, tap on the preview image section of the file (in channel's post list)
4. Once file viewer appears (both android and iOS), confirm that options to email and save file have appeared and can be accessed

#### Expected behavior
User should not have access to any options or features that would allow them to download a file

#### Observed behavior
Users can use separate apps or viewers to open PDF files outside of Mattermost and save/share files

#### Possible fixes
The library currently being used to open PDF files ([react-native-doc-viewer](https://github.com/philipphecht/react-native-doc-viewer)) does not seem to support the disabling of download functionality. Either forking/customizing that project to fit Mattermost's needs, or to find an alternate way to display pdf files in-app seem to be viable options for this

**Comment by amyblais** [comment]
Hi @avasconcelos114! Thank you for reporting this.

I'll ask our RN team about this.

**Comment by lindalumitchell** [comment]
@amyblais @avasconcelos114 we filed https://mattermost.atlassian.net/browse/MM-11286 to track this.

**Comment by amyblais** [comment]
The Jira ticket and associated PR are completed and we have tested internally that this works in v1.12 - feel free to re-open this Github Issue if the issue persists after upgrading to v1.12 (scheduled to be released in Sept. 14th).
