### ISSUE TITLE
Doesn't handle bad https

### ISSUE THREAD

**Issue by mzed** [mattermost/mattermost-mobile#1896]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
I can't connect to our private mattermost server via the android client.

#### Environment Information

- Device Name: Pixel
- OS Version: Android 8.1.0
- Mattermost App Version: 1.9.3, and Beta 1.10.0
- Mattermost Server Version: 4.10.1

#### Steps to reproduce
Try to connect to https://mattermost.doc.gold.ac.uk/ via the android app

#### Expected behavior
I would expect it to connect, or complain about a bad https certificate. (This is our fault.)

#### Observed behavior
I get a red "Cannot connect to server. Please check your server URL and internet connection" message

#### Possible fixes
The obvious fix is for our org to get an https certificate for mattermost.our.server, rather than re-using a certificate with the wrong name. However, the desktop client works fine with our current setup. And, we can enable browsers to ignore this misconfiguration.

The mobile app should throw a more detailed error about "bad https" or "insecure site" or the like. Ideally, it would let us accept this bad certificate manually.

**Comment by amyblais** [comment]
Hi @mzed! Thank you for reporting this.

I'll ask our RN team about this.

**Comment by amyblais** [comment]
Hi @mzed! I apologize for late reply!

For issues with "Cannot connect to server", it's usually an issue with either the server URL or the certificate - here is further information: https://docs.mattermost.com/mobile/mobile-troubleshoot.html#i-keep-getting-a-message-cannot-connect-to-the-server-please-check-your-server-url-and-internet-connection.

Here is further information on certificates - it works differently for mobile and desktop app which might be why you were mainly seeing the issue on mobile: https://docs.mattermost.com/deployment/ssl-client-certificate.html.

Let us know any further questions!

**Comment by bertramr** [comment]
Also a problem at our site.

**Comment by amyblais** [comment]
Hi @mzed, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by mzed** [comment]
IAs I said in my report, we did have a legitimately misconfigured certificate. As a feature request, it would be great if there was, at least, an error message to that effect. Ideally, users could continue on if they knew the certificate was ok.

**Comment by amyblais** [comment]
Hi @mzed - makes sense, would you like to help open [a feature request](https://mattermost.uservoice.com/forums/306457-general) and upvote it! I also found this [existing feature request](https://mattermost.uservoice.com/forums/306457-general/suggestions/13210239-ios-and-android-apps-should-allow-users-to-bypass) that sounds similar to what you are requesting.

**Comment by amyblais** [comment]
Hi @mzed, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
