### ISSUE TITLE
Back button does not close application on Android

### ISSUE THREAD

**Issue by paddatrapper** [mattermost/mattermost-mobile#1943]
#### Summary
Pressing the back button does not close the application

#### Environment Information

- Device Name: Samsung J5 Pro (SM-J530F)
- OS Version: Android 7.0
- Mattermost App Version: 1.10.0 (Build 127)
- Mattermost Server Version: 5.1.0

#### Steps to reproduce
Open the app, press the hardware back button

#### Expected behavior
It should close the application

#### Observed behavior
Nothing happens, the app does not close, not does it do anything else

**Comment by amyblais** [comment]
Hi @paddatrapper! 

This will be fixed in v1.11, here is a ticket you can follow for the fix: https://mattermost.atlassian.net/browse/MM-11381.

**Comment by paddatrapper** [comment]
@amyblais thanks a lot!

**Comment by paddatrapper** [comment]
Fixed in v1.11
