### ISSUE TITLE
Push notifications not reaching mobile devices when using cellular network

### ISSUE THREAD

**Issue by josh-torrey** [mattermost/mattermost-mobile#1946]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Push notifications are not reaching mobile devices (both iOS and Android clients) when using cellular data ONLY. Push notifications work normally when the device is connected to the internet via wifi, and old notifications that were missed (while using cellular data) come through to devices once a wifi network is joined. The issue has been reported by multiple users (at least 5) on our Mattermost account, though it is still unclear exactly how many users are affected on our server..

#### Environment Information

- Device Name: iPhone
- OS Version: 11.3.1
- Mattermost App Version: 1.10.0
- Mattermost Server Version: 4.9.0
- Push Notification Server: http://push-test.mattermost.com

#### Steps to reproduce
Send direct messages to a user with the mobile client/device where wifi is DISABLED, and no push notification appears on the device. Enable wifi and the missed notification pops up normally. When wifi is enabled all push notifications show up on mobile devices normally. 

FWIW - the system log shows the "missed" push notifications being sent normally, but they do not arrive on mobile devices that are connected to the web via cellular. 

#### Expected behavior
Push notifications show up on mobile devices that are connected to the internet via cellular network. 

#### Observed behavior
Push notifications DO NOT show up on mobile devices that are connected to the internet via cellular network

#### Possible fixes
After some troubleshooting I was able to fix the issue by **rebooting my phone.**

**Unsuccessful** attempts to fix the issue include:
- reset cache in mobile client
- delete file cache in mobile client
- remove active mobile sessions from the security settings on desktop (and re-logging on mobile)
- reinstalling mobile client

Unfortunately we cannot ask all of our users to reboot their mobile devices. We are looking for a server-side fix that will restore normal push notification functionality.

**Comment by josh-torrey** [comment]
Hi @amyblais - thanks for the quick follow-up. 

I can confirm that data usage was/is enabled for the Mattermost App on my device, which was affected by this push notification issue. 

We are experiencing a situation where push notifications were working normally for a while (on the 4.9 release), but at some point this changed. Unfortunately I cannot specify when exactly push notifications started to fail on cellular data.

**Comment by amyblais** [comment]
Thanks @josh-torrey! I'll test it out and see if I can repro.

**Comment by amyblais** [comment]
Hi @josh-torrey! I wasn't able to repro this on v5.0 and v5.1 - would you be able to do a few tests on our build server in case the issue is something to do with the server version: https://pre-release.mattermost.com/login.

Also, my OS version is 11.4, can you help confirm if all affected users are on 11.3 or if they have different versions?

**Comment by amyblais** [comment]
Hi @josh-torrey, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
