### ISSUE TITLE
Inline Images with a size constraint are not rendered

### ISSUE THREAD

**Issue by Thoro** [mattermost/mattermost-mobile#1951]
#### Summary
When posting an inline image link with a size constraint in a channel, the mobile app is rendering the plain text.

#### Environment Information

- Device Name: iPhone X
- OS Version: 11.4.1
- Mattermost App Version: 1.10.0 (Build 127)
- Mattermost Server Version: 5.1.0

#### Steps to reproduce
Insert a link like so into a post

```
![Mattermost](https://docs.mattermost.com/_images/icon-76x76.png =76x76 "Mattermost Icon")
```

#### Expected behavior
That the image is displayed in the asked format and that small images are shown on the same line.

#### Observed behavior
The original markup text is displayed instead of the image, when removing =76x76 it works.

#### Possible fixes
I guess the parser just doesn't know about the = part
More specifically the check is here https://github.com/mattermost/commonmark.js/blob/e5c34706cafa2924370772ff47937b833648a6de/lib/inlines.js#L689 which would need to be extended by the =witdthxheight markup 

Did the first step by adding the parsing options to the parser.

**Comment by amyblais** [comment]
Thanks for reporting this @Thoro! I'll test it out and report back if I can repro.

**Comment by amyblais** [comment]
@hmhealey PR here: https://github.com/mattermost/commonmark.js/pull/4

**Comment by hmhealey** [comment]
@Thoro Thanks for the report and PR. I'll take a look at those tomorrow morning. 

I wouldn't worry about getting the images to render on the same line as each other(RN doesn't like mixing text and non-text) or having them render at the specified dimensions on mobile due to the limited screen size, but as long as we can get them rendering at all, that'll be a big improvement

**Comment by Thoro** [comment]
Actually it would be really nice to get the size also working, my use case is to use mattermost as a deployment channel, and i‘m using icons with 2x res as images and would love to have crisp icons on the iphone

I tried to touch the react natice code, but have no idea what‘s going on, also it seems that not all tests are passing, which is even more confusing!

**Comment by hmhealey** [comment]
I submitted a PR to update CommonMark for the 1.13 of the mobile app

**Comment by hmhealey** [comment]
@Thoro Alright, this has been merged into the master branch, so it'll be available in 1.13, our October release. Thanks again for reporting and fixing this

If you happen to want to use this sooner, feel free to use the beta version of our app which should be updated with these changes in a couple weeks.

**Comment by hho** [comment]
This still doesn't work. :disappointed: 

* Android 9
* Mattermost App 1.16.1
* Mattermost Server 5.8.0

**Comment by Thoro** [comment]
Neither inline nor the size constraint work, BUT it now displays the image instead of the source code ;)

**Comment by hho** [comment]
It doesn't for me:
![Screenshot_20190313-103220-redacted](https://user-images.githubusercontent.com/478228/54268820-5d97c700-457c-11e9-9f78-b767bd06e73d.png)

**Comment by Thoro** [comment]
Yep, issue is that you have directly =100  -> so seems that's not covered

**Comment by hho** [comment]
Thanks for the workaround. I'd open a pull request, but as the scaling doesn't work anyway... ¯\\\_(ツ)_/¯
