### ISSUE TITLE
Can't connect on a subdirectory

### ISSUE THREAD

**Issue by Grummfy** [mattermost/mattermost-mobile#2016]
#### Summary
Install mattermost inside a subdirectory like https://example.tld/mattermost/ and the app will not be able to connect.

#### Environment Information
- Device Name: One Plus 5
- OS Version: Android 8.1.0
- Mattermost App Version: 1.11.0
- Mattermost Server Version: 5.1.0

#### Steps to reproduce
Install mattermost inside a subdirectory like https://example.tld/mattermost/ and the app will not be able to connect.

#### Expected behavior
Able to connect on a subdirectory.

#### Observed behavior
If I move it to the main directory, it's working perfectly.
Inside a subdirectory, it's working perfectly for the webversion.

**Comment by amyblais** [comment]
Hi @Grummfy, thank you for reporting this 👍 

I'm wondering if this is a backwards compatibility issue as I couldn't find a ticket related to this issue and this feature was well tested last release. I'll ask our QAs for help in testing this and we'll let you know the feedback.

**Comment by amyblais** [comment]
Hi @Grummfy,

Our QAs tested this and weren't able to repro the issue.

Are you seeing any errors in logs from around the time the issue occurs?

**Comment by Grummfy** [comment]
in fact, it's a network error, bad configuration from my side. Sorry for the error and thanks for the work
