### ISSUE TITLE
ui bug

### ISSUE THREAD

**Issue by coderafei** [mattermost/mattermost-mobile#2022]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
![image](https://user-images.githubusercontent.com/4183342/44322553-6c077f80-a480-11e8-93ed-a9dd39edc54c.png)

this is a black area appear on bottom of screen

#### Environment Information

- Device Name: Xiaomi 8
- OS Version: 
- Mattermost App Version: 1.10
- Mattermost Server Version:

**Comment by amyblais** [comment]
Hi @coderafei, thank you for reaching out.

I believe the black bar is the phone’s menu, not part of the Mattermost app. Example in the screenshot below - let me know if this makes sense.

![img_0084](https://user-images.githubusercontent.com/29708087/44344308-61d48980-a45e-11e8-922d-b7cde9157198.JPG)

**Comment by coderafei** [comment]
![image](https://user-images.githubusercontent.com/4183342/44345423-e73f5480-a4c5-11e8-9ee2-62ac00d528f3.png)
it just black area
blow is phone's menu

**Comment by amyblais** [comment]
What is your Mattermost server version (it can be found in the app settings)?

Also, we have just released app v1.11, which will be available to download in the next few days - would you like to test on that version (in case a bug related to this has been fixed on the latest version)? You can also sign up as a beta tester here to test on the latest version: https://play.google.com/apps/testing/com.mattermost.rnbeta.

**Comment by hmhealey** [comment]
Also, what device are you using, and what version of Android do you have?

**Comment by coderafei** [comment]
@amyblais ok, i will try new version
@hmhealey Xiaomi 8 with android 8.1.0

**Comment by coderafei** [comment]
new version not fix this

**Comment by amyblais** [comment]
Hi @coderafei,

Our QAs are not able to reproduce this - are other screens in the app showing the same issue (e.g. other than the channel view screen)?

**Comment by coderafei** [comment]
yes all screen

**Comment by amyblais** [comment]
Hi @coderafei, can you help take a look at the tips on this page for a possible solution: https://stackoverflow.com/questions/43126544/optimise-android-apps-for-phones-with-the-new-ratios-like-the-s8-18-59?

Here is also an article that seems to be related: https://economictimes.indiatimes.com/magazines/panache/the-189-display-dilemma-will-the-new-smartphone-screens-make-our-lives-easier-or-do-the-opposite/articleshow/62662023.cms.

**Comment by amyblais** [comment]
Hi @coderafei,

We created a ticket for this here: https://mattermost.atlassian.net/browse/MM-11846. 

Our devs are taking a look if they are able to fix it - however, since we're not able to reproduce the issue, we're not able to effectively test if the fix works. Hence, we're wondering if you'd be able to help with testing and/or fixing of the issue? We're able to send you an apk file and give guidance on how you can help if you're interested.

**Comment by amyblais** [comment]
Thank you! Do you have an idea on how to get started if you attempt to fix it?

One of our developers set up an emulator with a resolution of 1080x2160 and wasn't able to reproduce this yet.

**Comment by koxen** [comment]
@coderafei @amyblais you can fix it by going to 'fullscreen settings' in system settings (not sure how it's exactly in english locale) and switch on Mattermost :)

**Comment by coderafei** [comment]
@koxen amazing, it's "全面屏" in chinese at system setting, turn it on and fixed this 👍

**Comment by hmhealey** [comment]
Nice find, @koxen! I'm not surprised that it's a device-specific issue since those are hard to debug without owning the exact device, so huge thanks for your help.
