### ISSUE TITLE
Office 365 integration

### ISSUE THREAD

**Issue by prodigy7** [mattermost/mattermost-mobile#2027]
Maybe i'm too fast with my ticket (if yes, i think a small answere will solve it) but today we test mattermost 5.2 with O365 integration. So far, so good but in the mobile app I got not possibility, login with O365 account. I configured our system allow login by mail or O365 and got the message, I should login with O365 when I try my O365 mail address.
Feature already in the queue? Tried it with mattermost and mattermost beta android app.

**Comment by amyblais** [comment]
Hi @prodigy7, we haven't received an update for a while so I'll close this Issue for now.

Thank you for sharing this feature request!
