### ISSUE TITLE
Missing instructions for android build

### ISSUE THREAD

**Issue by bagage** [mattermost/mattermost-mobile#204]
The given instructions are not enough to build the Android application. First, `npm install` fails due to missing dependencies, so one have to run:

```
npm install intl-relativeformat
npm install intl-messageformat
```

But even with that, once you invoke `react-native run-android`, it fails with the following: 

```
:app:packageAllDebugClassesForMultiDex FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: org/webkit/android_jsc/R.class
```

**Comment by lfbrock** [comment]
We've added developer instructions for the mobile apps here: 

https://docs.mattermost.com/developer/mobile-developer-setup.html
