### ISSUE TITLE
Inactive users are not marked as such

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#2057]
#### Environment Information

- Mattermost App Version: 1.11.0
- Mattermost Server Version: 5.2.0

#### Steps to reproduce
Press + to start a private message

#### Expected behavior
See all users, inactive (disabled) ones should be marked with a `name-inactive`

#### Observed behavior
All user names look the same, unless you know who is inactive (disabled).

**Comment by amyblais** [comment]
Hi @licaon-kter! Thank you for reporting this.

What device and OS version are you using?

**Comment by licaon-kter** [comment]
Happens on any device.

**Comment by amyblais** [comment]
Thanks! I'll test this out today and report back if I can reproduce.

**Comment by amyblais** [comment]
@licaon-kter Apologies for the delay - I created a ticket for this here: https://mattermost.atlassian.net/browse/MM-11942.

**Comment by amyblais** [comment]
Hi @licaon-kter, the Jira ticket has been resolved and tested internally and the fix will be available in v1.12 release.

**Comment by licaon-kter** [comment]
> What device and OS version are you using?

I keep forgetting that this repo builds both iOS and Android, indeed my report was on Android. :)
