### ISSUE TITLE
[Android] Slash suggestions display command name instead of trigger

### ISSUE THREAD

**Issue by metaa** [mattermost/mattermost-mobile#2068]
#### Summary
When I summon the slash command completion for a *custom* slash command, the commands render with the slash following the command's **title**, not the **trigger** leading to a confusing autocompletion experience.

#### Environment Information

- Device Name: Nexus 5X
- OS Version: 8.1.0
- Mattermost App Version: 1.11.0
- Mattermost Server Version: 5.1.11

#### Steps to reproduce
Start typing a *custom* slash command.

#### Expected behavior
The command completion would show as `/<commandTrigger> ...`.

#### Observed behavior
The command completion shows `/<commandTitle> ...`.

#### Possible fixes
Display the correct string after the slash.

**Comment by amyblais** [comment]
Hi @metaa, thank you for reporting this.

I'll ask our QAs to help test this since I don't have an Android, and I'll let you know their feedback.

**Comment by kongr45gpen** [comment]
If it helps, I can also confirm this on Mattermost Server 5.2.1, App 1.11.0.

[pic 1](https://user-images.githubusercontent.com/720678/45036927-6ad07800-b066-11e8-85e0-841adcf73e0b.png), [pic 2](https://user-images.githubusercontent.com/720678/45036688-d1a16180-b065-11e8-87b8-3537c2678a0d.png)

**Comment by amyblais** [comment]
Hi all, we created a ticket for this here and a fix for it is already submitted for v1.12: https://mattermost.atlassian.net/browse/MM-11963.

**Comment by metaa** [comment]
@amyblais @kongr45gpen Awesome, thanks!

**Comment by amyblais** [comment]
I'll close this Issue for now as the above ticket has been resolved and tested internally - the fix will be available in v1.12 (scheduled release day is Sept. 14th).
