### ISSUE TITLE
Mattermost iOS UI tight / overlapping on iPhone XS

### ISSUE THREAD

**Issue by lannonbr** [mattermost/mattermost-mobile#2152]
#### Summary
The top UI of Mattermost on iOS on a iPhone XS is either tight or overlapping the system topbar & text box at bottom is being cut off due to rounded corners of the screen.

#### Environment Information

- Device Name: iPhone XS
- OS Version: iOS 12.0
- Mattermost App Version: 1.12.0 (Build 142)
- Mattermost Server Version: 5.1.0

#### Steps to reproduce
1) Open Mattermost on a iPhone XS
2) login to a server
3) Observe UI

#### Observed behavior
In the default view, the UI of Mattermost's header is close to the iOS UI

![img_0055](https://user-images.githubusercontent.com/3685876/45928189-8dd7a480-bf0d-11e8-8a05-e2e853fe0990.jpg)

When the sidebar is open it is overlapping the system UI

![img_0056](https://user-images.githubusercontent.com/3685876/45928190-8dd7a480-bf0d-11e8-9b9a-8e728525a09b.jpg)

Even though it can't be seen in the screenshot, the bottom text input box is at the bottom which is cut off since the iPhone XS has a curved edges at the corners

![img_0057](https://user-images.githubusercontent.com/3685876/45928191-8dd7a480-bf0d-11e8-885c-39716ef2c208.jpg)

#### Possible fixes
https://github.com/mattermost/mattermost-mobile/blob/master/app/components/safe_area_view/safe_area_view.ios.js#L34 is only checking for the iPhone X. Once rebeccahughes/react-native-device-info#499 is merged and published to NPM, this can be fixed.

**Comment by enahum** [comment]
Also let me know if you are interested in fixing and submitting a PR for this one ;)

**Comment by lannonbr** [comment]
@enahum I would be interested in helping out. Should be a fairly easy change in the code and then I'll just need to test it which shouldn't be too bad. I'm expecting the PR should be up likely the same day that PR from react-native-device-info is published to NPM.

As well, the other only screen that does this is the search screen.

**Comment by enahum** [comment]
@lennonbr that would be great although we do have use a fork from device-info and I’ll need to merge that PR into our fork, I could actually do it before they merge it in the lib

**Comment by enahum** [comment]
@lannonbr PR with the fix submitted

**Comment by lindy65** [comment]
Hi @lannonbr :)

The fix for this issue has been tested on simulator but we wondered whether you'd be interested in helping to test on your device?  You can sign up for beta testing [here](https://play.google.com/apps/testing/com.mattermost.rnbeta) if you don't already have access.  We'd really appreciate that!

**Comment by lannonbr** [comment]
@lindy65, just signed up for the Beta through iOS TestFlight. The build I downloaded was 1.12.0 Build 141. Is there a planned push to the beta program today that will include the fix that was merged last week (#2153)

**Comment by lindy65** [comment]
Hi @lannonbr :)

Sorry about that,

Build 145 (latest) has been pushed to TestFlight now so you should be able to access it there. Please let me know if you have further issues.

Thanks!

**Comment by lannonbr** [comment]
Hey @lindy65 So I downloaded Build 145 and I can confirm that the fix is in it and is now properly spaced out :tada:

**Comment by lindy65** [comment]
Fantastic @lannonbr :)

Thank you so much for helping to test!  Much appreciated!
