### ISSUE TITLE
could not upload any files to server via 5.3.1

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost-mobile#2198]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

#### Environment Information

- Device Name: Samsung Galaxy Note 8, iPhone SE
- OS Version: Android 8.0(oreo), iOS 12.1(beta)
- Mattermost App Version: 4.1.2 (Standard App Store/Google Play version)
- Mattermost Server Version: 5.3.1

#### Steps to reproduce
This issue started 5.3.1. (5.3.0 did not have same problem) I could not any files to server via Native Mobile Application. However, Windows/Mac/Web no problem. The server has not been modified.

#### Expected behavior
According to log, there is a noticeable part that "401".. 
{"level":"debug","ts":1538380801.3990445,"caller":"web/context.go:84","msg":"Invalid or expired session, please login again.","path":"/api/v4/files","request_id":"edm4bo61qf87fx9nsqxb4w859c","ip_addr":"0.0.0.0","user_id":"","method":"POST","err_where":"ServeHTTP","http_code":401,"err_details":"token=kjnbmdfe6iny3kq4wf7kfjysio Appears to be a CSRF attempt"}

I have never logged out. There is no problem sending messages afterwards. The logs below do not seem to be important.

{"level":"debug","ts":1538380801.6614313,"caller":"web/handlers.go:50","msg":"GET - /api/v4/websocket"}
{"level":"debug","ts":1538380801.8251636,"caller":"web/handlers.go:50","msg":"GET - /api/v4/license/client"}
{"level":"debug","ts":1538380801.863692,"caller":"web/handlers.go:50","msg":"GET - /api/v4/config/client"}
{"level":"debug","ts":1538380801.86379,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me/teams"}
{"level":"debug","ts":1538380801.8640678,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me/preferences"}
{"level":"debug","ts":1538380801.8663595,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me/teams/members"}
{"level":"debug","ts":1538380801.9037917,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me/teams/unread"}
{"level":"debug","ts":1538380801.9453824,"caller":"web/handlers.go:50","msg":"GET - /api/v4/channels/49mo6ta37i8pimkgyir9grjnye/posts"}
{"level":"debug","ts":1538380801.9912374,"caller":"web/handlers.go:50","msg":"GET - /api/v4/teams"}
{"level":"debug","ts":1538380801.9914238,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me/teams/wdmoty3ee7f5xxkbcfbju787to/channels/members"}
{"level":"debug","ts":1538380801.9916122,"caller":"web/handlers.go:50","msg":"GET - /api/v4/users/me/teams/wdmoty3ee7f5xxkbcfbju787to/channels"}
{"level":"debug","ts":1538380802.0621207,"caller":"web/handlers.go:50","msg":"POST - /api/v4/channels/members/me/view"}

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
![error](https://user-images.githubusercontent.com/20394843/46277052-f4f3f980-c59c-11e8-9490-2b07a45ee72c.png)

#### Possible fixes
Sorry, I can't. And, I'm not sure that this is a server issue or an application issue.

**Comment by enahum** [comment]
Hi @Gloriashield, thanks for the report this issue has been fixed in #2151 and will be shipped with the 1.13.0 release on Oct 16th

**Comment by amyblais** [comment]
Closing this as the referenced PR and Jira ticket have been resolved,
