### ISSUE TITLE
Android app not started on real device

### ISSUE THREAD

**Issue by sherifelgafary** [mattermost/mattermost-mobile#2211]
#### Summary
when i try to run the app on a device it gets only to the splash screen and never loads the JS files for the app to start

#### Environment Information

- Device Name: multiple devices
- OS Version:  multiple OS versions
- Mattermost App Version: 1.12
- Mattermost Server Version:

#### Steps to reproduce
1- cloning the code from github
2- cd clone directory
3- make pre-run
4- npm install
5- make start
6- open the android on android studio
7- adding these lines to the gradle.properties file
MATTERMOST_RELEASE_STORE_FILE=/Users/sherifkhaled/Downloads/StagingNon-TechDatamattermost-mobile-1.12.0/android/app/my-release-key.keystore
MATTERMOST_RELEASE_KEY_ALIAS=my-key-alias
MATTERMOST_RELEASE_PASSWORD=123456
8- run on simulator "everything runs as supposed to"
9- run on a device it loads only to the splash screen and never loads the js files to start

#### Expected behavior
the app loads the js files and starts 

#### Observed behavior
it loads only to the splash screen and never loads the js files to start

**Comment by enahum** [comment]
Hi @sherifelgafary have you tried this http://facebook.github.io/react-native/docs/running-on-device#method-2-connect-via-wi-fi ?

**Comment by sherifelgafary** [comment]
@enahum  i have tried to make the developer menu to show with many ways like shaking and using the command to trigger the developer menu event but without any success but i tried to make the app listens to the correct port using this command
adb -s <device name> reverse tcp:8081 tcp:8081
and it was successful but my main issue now is whenever i create a release apk file from android studio it crashes on launching and it doesn't show any crashing message so could you help me please

**Comment by enahum** [comment]
@sherifelgafary the developer menu should show if you deployed a debug build to the phone, if you run `make run-android` with the phone attached to your computer it should do it for you.

as for the release apk I never build it with Android Studio, so no idea why is it crashing for you, do you happen to have the logs? maybe it can give you an indication of why is it crashing.

to build the apps for Android I run the `make build-android` commands. We recently made some changes to the script that builds the app, you can take a look at the updated documentation in this PR https://github.com/mattermost/mattermost-developer-documentation/pull/169 and the current documentation here https://developers.mattermost.com/contribute/mobile/

**Comment by sherifelgafary** [comment]
@enahum  thanks a lot for your help indeed it worked when the apk file is generated using the make commands

**Comment by enahum** [comment]
@sherifelgafary awesome, good to know.

Going to close this issue as resolved.
