### ISSUE TITLE
iOS Share Extension crashes

### ISSUE THREAD

**Issue by powhu** [mattermost/mattermost-mobile#2236]
#### Summary

If `AppGroupId` was not set correct, iOS share extension crashes.

mattermost-mobile/share_extension/ios/extension.js
```
mattermostBucket.readFromFile('entities', props.appGroupId).then((value) => {
            this.entities = value || initialState;
            this.setState({init: true});
});
```

`this.entities = value || initialState;`
 must be 
`this.entities = value || initialState.entities;`

![extension](https://user-images.githubusercontent.com/1047661/46682307-c7075880-cc1f-11e8-8e6c-09c853fe1ef3.png)

#### Environment Information

- Device Name: all iOS device
- OS Version: Test on iOS 12
- Mattermost App Version: 1.12.0

**Comment by enahum** [comment]
Hey @powhu great catch, two questions
1. are you building the app yourself? we do have a fastlane script that should set the correct appGroupId
2. will you be willing to submit a PR to fix it?

**Comment by powhu** [comment]
#2242

**Comment by enahum** [comment]
PR submitted
