### ISSUE TITLE
App crashes when spamming emoji

### ISSUE THREAD

**Issue by redfast00** [mattermost/mattermost-mobile#2261]
#### Summary
App crashes when spamming emoji. If you don't get kicked from the channel after crashing, it keeps crashing when you open the app again.

#### Environment Information

- Device Name: Oneplus 2
- OS Version: Android 8.1.0
- Mattermost App Version: 1.13.0 (build 147) and 1.12.0 (build 142) 
- Mattermost Server Version: 5.3.1

#### Steps to reproduce
Just spam a lot of emoji in a message (I used `:belgium:`) 

#### Expected behavior
The app doesn't crash

#### Observed behavior
The app becomes unresponsive, crashes. When I restart the app, it goes to the same channel and crashes again, over and over

#### Possible fixes
?

**Comment by amyblais** [comment]
Thank you @redfast00, we are able to repro this and created a ticket here: https://mattermost.atlassian.net/browse/MM-12668.

**Comment by amyblais** [comment]
Hi @redfast00, letting you know that this a React Native, so we will open an Issue in their repo in the next upcoming days.
