### ISSUE TITLE
Disable view / download attachments 

### ISSUE THREAD

**Issue by sherifelgafary** [mattermost/mattermost-mobile#2266]
#### Summary
i have been trying to disable the users to view/download attachments with no success
#### Environment Information

- Device Name: iphone 8
- OS Version: 11.4
- Mattermost App Version: 1.12.0
- Mattermost Server Version: mattermost pre-release server

#### Steps to reproduce
i have changed https://github.com/mattermost/mattermost-mobile/blob/master/app/components/file_attachment_list/index.js#L21 

to false so it would ignore the server settings to always disable  

to be like  this

function makeMapStateToProps() {
    const getFilesForPost = makeGetFilesForPost();
    return function mapStateToProps(state, ownProps) {
        return {
            ...getDimensions(state),
            canDownloadFiles: false,
            files: getFilesForPost(state, ownProps.postId),
            theme: getTheme(state),
            filesForPostRequest: state.requests.files.getFilesForPost,
        };
    };
}

but the behaviour is still isn't applied 

#### Expected behavior
attachments view/download is disabled

#### Observed behavior
attachments view/download is still enabled

#### Possible fixes
https://github.com/mattermost/mattermost-mobile/blob/master/app/components/file_attachment_list/index.js#L21

**Comment by enahum** [comment]
You also need to set it as false here https://github.com/mattermost/mattermost-mobile/blob/master/app/screens/image_preview/index.js#L15

**Comment by enahum** [comment]
Did you solve the issue? Feel free to close this

**Comment by enahum** [comment]
Closing as it was reported as done in pre-release
