### ISSUE TITLE
Text is cut off (Marshall, Model „London“, Android 5.0.2)

### ISSUE THREAD

**Issue by oli-ver** [mattermost/mattermost-mobile#2267]
#### Summary
Text in the Mattermost mobile App is cut off in all channels and conversations.

#### Environment Information

- Device Name: Marshall, Model „London“
- OS Version: Android 5.0.2
- Mattermost App Version: 1.13.0 (Build 149)
- Mattermost Server Version: 5.3.0

#### Steps to reproduce
How can we reproduce the issue?
Install app, connect to server and receive and write a message

#### Expected behavior
Text is complete and not cut off anywhere

#### Observed behavior
![unadjustednonraw_thumb_346b](https://user-images.githubusercontent.com/965863/46921253-52566480-cff9-11e8-93be-0b6a73d1701c.jpg)
![unadjustednonraw_thumb_346c](https://user-images.githubusercontent.com/965863/46921257-61d5ad80-cff9-11e8-87db-d5f26097d68f.jpg)

This is how it should look like (iOS version of the same chat):
![unadjustednonraw_thumb_346d](https://user-images.githubusercontent.com/965863/46921339-5d5dc480-cffa-11e8-89be-fa5d9c8ca1cb.jpg)
![unadjustednonraw_thumb_346e](https://user-images.githubusercontent.com/965863/46921341-6189e200-cffa-11e8-9cd2-c7bc3d8093b3.jpg)

#### Possible fixes
Nothing yet.

**Comment by enahum** [comment]
Should be fixed with https://github.com/mattermost/mattermost-mobile/pull/2244

**Comment by oli-ver** [comment]
@enahum Thanks for the fast reply. Then I think this one here can be closed at duplicate of #2244. When will this version be released?

**Comment by enahum** [comment]
Sadly is scheduled to be released on Nov 16th but probably in a week or two you could get a beta app with the fix included

**Comment by oli-ver** [comment]
Ok thank you, I’ll let the Android users know.
