### ISSUE TITLE
Mattermost mobile app does not complete websocket connection with Blackberry Dynamics in BYOD deployment when AppDome is not used

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-mobile#2283]
#### Summary

Mattermost mobile app does not complete websocket connection with Blackberry Dynamics in BYOD deployment. 

Mobile app works when deployed with Blackberry Dynamics and AppConfig (non-BYOD), and it works with Blackberry Dynamics BYOD when AppDome is used, but not in BYOD without AppDome. 

#### Steps to reproduce

1. Download [Mattermost app](https://github.com/mattermost/mattermost-mobile/releases) 
2. Follow the steps in the [Blackberry Dynamics SDK](http://help.blackberry.com/en/blackberry-dynamics-sdk-ios/current/) to wrap the application in a BYOD configuration 
3. Create an account on a Mattermost test server, e.g. https://community.mattermost.com/signup_user_complete
3. Connect the wrapped app to a test server (e.g. https://community.mattermost.com) by signing in using test account credentials (See [instructions](https://docs.mattermost.com/help/getting-started/signing-in.html#email-address-or-username-sign-in))

#### Expected behavior

Mattermost mobile app works as normal after login. 

#### Observed behavior

App banner shows "Connecting..." indefinitely and server log reports `Failed to upgrade websocket connection` for client wrapped in BlackBerry Dynamics. 

#### Possible fixes

This issue appears only to appear in BYOD deployment scenario for Blackberry Dynamics. 

When using AppConfig (non-BYOD deployment) managed configurations for the Mattermost iOS app in Blackberry Dynamics, websockets work properly. 

When fusing the unsigned Mattermost mobile app found [here](https://github.com/mattermost/mattermost-mobile/releases) with AppDome and Blackberry Dynamics, the websocket connection is successful. 

We’re looking for help from people with experience deploying BlackBerry Dynamics apps in BYOD configurations, ideally with React Native to help: 

1. Track down the source of this error 
2. Share a link to a code sample where websockets are working in BYOD configuration
3. Share a link to a code sample with Blackberry Dynamics working with React Native 

Side note: We’ve talked to someone from Blackberry who suggested looking at 
https://github.com/daltoniam/Starscream

**Comment by it33** [comment]
FYI, now investigating "long pole" approach for self-compiled versions of mobile app that could address this issue.

**Comment by esethna** [comment]
Update: The Mattermost team is in discussions on a potential partnership with AppDome as a next step to address this issue.

**Comment by innovationhub-asia** [comment]
What was the outcome of this case at the end ?

**Comment by esethna** [comment]
@innovationhub-asia this issue is still open, however websocket connections are successful when using platforms such as [AppDome](https://www.appdome.com/platform/) or [BlueCedar](https://www.bluecedar.com/integration-accelerator-blackberry).

**Comment by larkox** [comment]
@esethna Is this still relevant, or should we close the ticket?

**Comment by esethna** [comment]
We can close and reopen as necessary
