### ISSUE TITLE
Korean characters not processing properly on iOS

### ISSUE THREAD

**Issue by avasconcelos114** [mattermost/mattermost-mobile#2286]
#### Summary
When typing Korean, characters do not properly form syllables if the user tries to re-edit the middle of a sentence.

#### Environment Information

- Device Name: iPhone 6s
- OS Version: iOS 12
- Mattermost App Version: 1.13.1 (Build 151)
- Mattermost Server Version: 5.4.0

#### Steps to reproduce
1. With a Korean keyboard enabled, type `테스트` (`ㅌ` + `ㅔ` + `ㅅ` + `ㅡ` + `ㅌ` + `ㅡ`) in the post textbox of any channel
2. Manually drag the caret (text cursor) to the middle of the word
3. Re-type the same word as step 1 (테스트)
4. Text seen in input box is now `테스ㅌㅔㅅㅡㅌㅡ 트`

#### Expected behavior
User should be able to freely add test in the middle of words

#### Observed behavior
Any Korean characters typed that aren't at the very end of the textbox aren't processed correctly 
![ios_korean_character](https://user-images.githubusercontent.com/29700158/47401507-b0631480-d77c-11e8-838b-72322684a110.PNG)

#### Possible fixes
It feels like when placing the caret in the middle, each keyboard press triggers the `handleTextChange` function and immediately sets a new `value` for the textbox, without giving the chance for users to complete the syllable.

**Comment by amyblais** [comment]
Thank you @avasconcelos114, I'll test this out today.

One of our developers said that this might also be an issue on the React Native side, so we'll see if we open an Issue on their repo as well.

**Comment by amyblais** [comment]
@avasconcelos114 I opened a bug ticket here: https://mattermost.atlassian.net/browse/MM-12813.

**Comment by amyblais** [comment]
Hi @avasconcelos114,

Letting you know that this is an RN issue and there is a bug report on their repo here: https://github.com/facebook/react-native/issues/19313.

I'll close this Issue here for now,
