### ISSUE TITLE
Sharing photo from photo library requires "take photos and record video" permission

### ISSUE THREAD

**Issue by jsha** [mattermost/mattermost-mobile#2296]
#### Summary
Sharing photo from photo library requires "take photos and record video" permission.

#### Environment Information

- Device Name: Pixel 3 
- OS Version: 9.0
- Mattermost App Version: 1.13.0 (Build 151)
- Mattermost Server Version: 5.1.0

#### Steps to reproduce
Tap the "+" icon to upload an attachment. Tap "Photo Library". A permissions prompt comes up asking to access files on your phone; say yes. Another permissions prompt asking to take pictures and record video; say no.

#### Expected behavior
There should be no prompt to take pictures and record video when asking to upload a photo from the photo library.

#### Observed behavior
The take pictures and record video permission was required.

**Comment by enahum** [comment]
Sorry @jsha  but this is required by Android and iOS as well and there is no way around that, if you don't explicitly grant permissions then the library will not be accessible.

**Comment by amyblais** [comment]
Hi @jsha,

This could be due to the fact that users on v1.13 should upgrade to v5.4 for compatibility reasons (file uploads on v1.13 only work on server v5.4). More details on the changelog: https://github.com/mattermost/mattermost-mobile/blob/master/CHANGELOG.md#v1130-release.

Would you be able to test on v5.4 if it helps with the issue? You can also test on our [community server](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676).

**Comment by jsha** [comment]
@enahum The app asks for two different permissions:

1) Storage
2) Camera

You can check these in the system settings page. When selecting "Photo Library", only "Storage" is needed, not "Camera." So there should be no prompt for the "Camera" permission.

At a minimum, granting the "Storage" permission but rejecting the "Camera" permission should allow the user to proceed with selecting an image from their Photo Library.

**Comment by enahum** [comment]
Hi @jsha this is cause the library that we use handles the permission request for us and they actually do request for both. see: https://github.com/react-community/react-native-image-picker/blob/v0.27.0/android/src/main/java/com/imagepicker/ImagePickerModule.java#L601 <- that is the code responsible in the library so perhaps best to report this in their repo? Sadly there's not much we can do here

**Comment by amyblais** [comment]
Hi @jsha, we haven't received an update for a while so I'll close this Issue for now.

If you have any further questions, please reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by jsha** [comment]
It looks like someone else has already reported this same issue on react-native-image-picker: https://github.com/react-community/react-native-image-picker/issues/828.
