### ISSUE TITLE
Enable "Show Password While Typing"

### ISSUE THREAD

**Issue by jsha** [mattermost/mattermost-mobile#2297]
#### Summary
Per the latest NIST 800-53 guidelines, "Show Password While Typing" is a [security and usability best practice](https://auth0.com/blog/dont-pass-on-the-new-nist-password-guidelines/).

#### Environment Information

- Device Name: Pixel 3
- OS Version: 9.0
- Mattermost App Version: 1.13.0 (Build 151)
- Mattermost Server Version: 5.1.0

**Comment by enahum** [comment]
Thanks @jsha would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

A PR would also be welcomed

**Comment by amyblais** [comment]
@jsha we haven't received an update for a while so I'll close this Issue for now.

If you have any further questions, please reopen this issue with the relevant information and we'd be glad to help you where we can. Thank you for considering adding this to the feature request forum!
