### ISSUE TITLE
Many Emoji Slows/Crashes App

### ISSUE THREAD

**Issue by tankerkiller125** [mattermost/mattermost-mobile#2298]
#### Summary
If you insert many emoji in messages (thing enough to fill the screen) it will cause the app to freeze up and sometimes even crash. In my testing, each emoji was different and not the same.

#### Environment Information

- Device Name: LG G6
- OS Version: Android 8.0
- Mattermost App Version: 1.13.0 (Build 151)
- Mattermost Server Version: 5.4.0

#### Steps to reproduce
Insert ALOT of emoji into the chat, preferably all different emoji and enough to entirely fill the screen. Once this is done close the app and then re-open it to the channel where the emoji are located, the app will freeze or completely crash

#### Expected behavior
App should continue working correctly.

#### Observed behavior
Freezes/Crashes the app

#### Possible fixes
Unknown

**Comment by amyblais** [comment]
Thank you @tankerkiller125,

This is a React Native issue, and we are planning to submit an Issue in their repo in the upcoming days.

**Comment by enahum** [comment]
Filed an issue in the react-native repo: https://github.com/facebook/react-native/issues/22038

**Comment by amyblais** [comment]
Closing this Issue as this can be followed via react native,
