### ISSUE TITLE
Sign up or register using mobile App

### ISSUE THREAD

**Issue by ChenZhaobin** [mattermost/mattermost-mobile#2299]

**Comment by amyblais** [comment]
Hi @ChenZhaobin, can you help fill in the form so we know what issue you're experiencing?

**Comment by ChenZhaobin** [comment]
@amyblais  sorry about that ,I want to allow my clients to registe their account from mobile app ,but I have not found this function in source code ,is this not completed or some other reasons?

**Comment by amyblais** [comment]
@enahum The user is compiling the app and cannot find the source code to add user sign-up / registration.

**Comment by enahum** [comment]
@ChenZhaobin @amyblais mobile app does not have the feature to sign-up / register, as of now the only way is to do it from the desktop/webapp or if SSO is enabled.

You can file a feature request or even better submit a PR ;)

**Comment by amyblais** [comment]
@ChenZhaobin we haven't received an update for a while so I'll close this Issue for now.

If you have any further questions, please reopen this issue with the relevant information and we'd be glad to help you where we can. Thank you for considering adding this to the feature request forum!

**Comment by prince-mishra** [comment]
Hi @amyblais,
With 2021 and all the discussions on online privacy and their violations thereof by the big corporations going on, Mattermost has become all the more important.
It is disheartening to see that the mobile app still does not have the ability to register users. 
Is there a plan to do so?

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @prince-mishra,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.
