### ISSUE TITLE
Jumbo emojis don't seem to work on mobile

### ISSUE THREAD

**Issue by Sloth-on-meth** [mattermost/mattermost-mobile#2305]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

Jumbo emojis don't seem to work on android using the latest release from github

#### Environment Information

- Device Name: OnePlus 5t
- OS Version: 8.0
- Mattermost App Version: 1.13
- Mattermost Server Version: 4.10

#### Steps to reproduce
How can we reproduce the issue?

Jumbo emoji

#### Expected behavior
Describe your issue in detail.

Larger emoji

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

No difference in emoji size

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
Hi @Sloth-on-meth,

Support for jumboemojis was added in server v5.4, so I believe you'll just need to upgrade and it will work.

**Comment by enahum** [comment]
There is a ticket for adding Jumbo emoji to the mobile app https://mattermost.atlassian.net/browse/MM-12353

**Comment by Sloth-on-meth** [comment]
Sorry, server version is 5.4.0.
https://mattermost.atlassian.net/browse/MM-12353
Closed
