### ISSUE TITLE
Tables do not render correctly on app

### ISSUE THREAD

**Issue by kjohannessen** [mattermost/mattermost-mobile#2306]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
The new app does not render tables correctly on Iphone. Wide tables look terrible.

Same tables render correctly on desktop / web and Classic App

#### Environment Information

- Device Name: Iphone
- OS Version: IOS12
- Mattermost App Version: Latest
- Mattermost Server Version: 5.4.0

#### Steps to reproduce
Render a table in mattermost

e.g

| Foo     | Bar         | Tag         | Sym  | Des                 | Product      | Qty      | Price  | MarketValue |
| :------- | :----------- | :---------  | :----   | :-------------------        | :--------         | --------:| ------:| -----------:|
| A1 | A | B | A.L | MN | E | -1470 | 157.35 | -3025 |
| A2 | A | B | V.L | MN | E | 6666 | 157.35 | 10489 |
| A3 | A | B | B.L | MN | E | 12210 | 157.35 | 19212 |

#### Expected behavior
column text wraps 1 character wide. Table does not have scrolling to the right as per the old mattermost iOS app.

![img_58f393a73298-1](https://user-images.githubusercontent.com/7603012/47860155-ccebf600-dde7-11e8-8ebe-8a970854559f.jpeg)

Renders correctly in Desktop App

<img width="760" alt="screen shot 2018-11-01 at 15 04 37" src="https://user-images.githubusercontent.com/7603012/47860222-f86ee080-dde7-11e8-9133-63c28f6d1ae4.png">

If you rotate the screen to landscape mode the table renders correctly.

#### Observed behaviour
This has always been the behaviour with the new app. I thought it would have been fixed by now.

#### Possible fixes
Haven't looked at the code sorry. Will update this with some screenshots

**Comment by enahum** [comment]
There is already a ticket for this https://mattermost.atlassian.net/browse/MM-11232

**Comment by kjohannessen** [comment]
OK .. didn't see that issue .. will close this one then
