### ISSUE TITLE
Node crashes during build

### ISSUE THREAD

**Issue by Rudloff** [mattermost/mattermost-mobile#2327]
#### Summary
When trying to build 1.13.1 on an F-Droid build VM, Node crashes during `bundleReleaseJsAndAssets`.

#### Steps to reproduce
The build recipe is available [here](https://gitlab.com/fdroid/fdroiddata/blob/2fae7a5f204314606dcdd707f6f1d381f18c5899/metadata/com.mattermost.rnbeta.yml) but except for the patching, we are basically running this:
```bash
make pre-run
gradle assembleRelease
```

#### Expected behavior
The app should build correctly.

#### Observed behavior
The build fails with this error:
```
DEBUG: buildserver > Execution failed for task ':app:bundleReleaseJsAndAssets'.
DEBUG: buildserver > > Process 'command 'node'' finished with non-zero exit value 137
```

#### Possible fixes
This error is probably caused by a lack of memory (our build VMs have 2 GB of RAM and I can't reproduce the issue on my computer with 12 GB of RAM).
Is there a way to limit the amount of memory used by the React Native build script?

(Also, I can't reproduce this with 1.11.0 so I suppose recent versions started to use more ressources.)

**Comment by saturninoabril** [comment]
@Rudloff Thanks for the report.  That's interesting but I thought 2GB is pretty low.  Honestly, I don't know if there's a way to limit memory usage while building the app.  Maybe try experimenting like upgrading the node version or the like.
Also can you try to revisit our [build documentation](https://developers.mattermost.com/contribute/mobile/build-your-own/), especially the build preparation and setting up environment variables and see if there's something that might be helpful in your case?

**Comment by Rudloff** [comment]
> 2GB is pretty low

I agree, but we use these VMs to build much larger apps like Firefox, and it is slow but does not crash like that. I think Gradle is smart enough to detect the available memory but Node does not seem to do that.

> Maybe try experimenting like upgrading the node version or the like.

I tried to use Node 10.13.0 but it does not change anything.
I see that Node has a `max-old-space-size` flag but I am not sure how to make Gradle use it when calling the React Native build script.

I also tried to play with this parameter but it did not work: https://github.com/mattermost/mattermost-mobile/blob/30cccafcd5eb2ff8af39f3c03d7774d89491f501/android/gradle.properties#L14
I guess it only applies to Gradle and not to Node.

>  Also can you try to revisit our build documentation, especially the build preparation and setting up environment variables and see if there's something that might be helpful in your case?

If I understand correctly, these environment variables are used by make or fastlane, but we call Gradle directly. Anyway, I had a look but did not find anything that could improve memory usage.

**Comment by Rudloff** [comment]
I found a way to limit the amount of memory Node can use:
```diff
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -75,7 +75,8 @@ import com.android.build.OutputFile
 project.ext.react = [
     entryFile: "index.js",
     bundleCommand: "ram-bundle",
-    bundleConfig: "packager-config.js"
+    bundleConfig: "packager-config.js",
+    nodeExecutableAndArgs: ["node", "--max-old-space-size=2048"]
 ]
 
 apply from: "../../node_modules/react-native/react.gradle"
```

I still wish this could be done automatically but at least we can build the app now :slightly_smiling_face:

**Comment by Rudloff** [comment]
It looks like I claimed victory too soon. Even with `--max-old-space-size`, Node uses too much memory (but not every time for some reason).

But instead of the 137 exit code, I get a more verbose memory allocation error:
```
:app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
Loading dependency graph, done.
BUILDING MODULES FOR android
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

[1576:0x34d1470]    86594 ms: Mark-sweep 994.3 (1067.3) -> 979.9 (1067.6) MB, 1948.2 / 0.1 ms  (average mu = 0.118, current mu = 0.063) allocation failure scavenge might not succeed
[1576:0x34d1470]    88715 ms: Mark-sweep 994.5 (1067.6) -> 983.2 (1066.1) MB, 2019.7 / 0.1 ms  (average mu = 0.083, current mu = 0.047) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x8e237edbe1d]
Security context: 0x1ceef269e6e1 <JSObject>
    1: push [0x1ceef2685851](this=0x2742b83217d1 <JSArray[0]>,0x0a4cbb1cdf19 <TraversalContext map = 0x3e96aaa9cbe9>)
    2: visitQueue [0x3c73e4440969] [/home/vagrant/build/com.mattermost.rnbeta/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:~96] [pc=0x8e238b38d28](this=0x0a4cbb1cdf19 <TraversalContext map = 0x3e96aaa9cbe9>,queue=0x0a4c...

 1: 0x8daaa0 node::Abort() [node]
 2: 0x8daaec  [node]
 3: 0xad73ce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xad7604 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xec4c32  [node]
 6: 0xec4d38 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xed0e12 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xed1744 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xed43b1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xe9d834 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x113cf9e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0x8e237edbe1d 
:app:bundleReleaseJsAndAssets FAILED
```

**Comment by amyblais** [comment]
Has this issue been resolved? If not, I encourage joining our [Mobile app channel](https://community.mattermost.com/core/channels/team-icu) on our community server to further troubleshoot this.

**Comment by Rudloff** [comment]
Unfortunately, I can still reproduce this issue with 1.15.2 and Node 10.15.0 :slightly_frowning_face:

**Comment by enahum** [comment]
Have you tried setting the following env var `export NODE_OPTIONS=--max_old_space_size=12000` ?

**Comment by Rudloff** [comment]
Isn't the correct option `--max-old-space-size` (see [here](https://nodejs.org/api/cli.html#cli_node_options_options))?

Anyway, setting `NODE_OPTIONS` in the build environment seems to be ignored. (I suppose Gradle does not pass environment variables when calling node?)
But as mentioned in https://github.com/mattermost/mattermost-mobile/issues/2327#issuecomment-436952935, I tried setting the same option in `nodeExecutableAndArgs` and it resulted in an OOM crash.

**Comment by enahum** [comment]
Are you using the make build-android command?

**Comment by Rudloff** [comment]
No, as mentioned quickly in https://github.com/mattermost/mattermost-mobile/issues/2327#issue-378354882, we use `make pre-run` to get the Node dependencies and then our build system calls `gradle assembleRelease` directly.
(This way we don't have to install Fastlane in our build VM and can reuse the automated process we use for other Gradle apps.)

Your Fastlane script seems to do basically the same thing: https://github.com/mattermost/mattermost-mobile/blob/d627f96589b4948de2cee9e13e462de544d11b64/fastlane/Fastfile#L457

**Comment by enahum** [comment]
@Rudolff sadly I don’t know why building the app that way is not working. Perhaps you should consider going through the fastlane route.

And perhaps is also the fact that your env var is using `dashes` instead of `underscores`? I think there is a difference between the cli option and the env vars

**Comment by Rudloff** [comment]
It turns out that, while our dev VM has only 2 GB of RAM, our production server has 6 GB.
It seems to be enough to build the app so I will close this issue.

(I am still interested in making it build with 2 GB though, because we use the dev VM to test new builds.)

**Comment by freerider7777** [comment]
I have the same problem... VM has 6GB of memory and gets out of memory error here...

**Comment by freerider7777** [comment]
But this is crazy, 6GB memory required to build mobile app...

**Comment by enahum** [comment]
@freerider7777 maybe you need to tweek the max-workers for gradle, if you are building in a CI consider disabling gradle daemon also you could try setting this env vars

```
JAVA_OPTS: '-Xms1024m -Xmx2g'
      GRADLE_OPTS: '-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError" -Dkotlin.compiler.execution.strategy=in-process '
```

and see if that helps

**Comment by freerider7777** [comment]
I'm building from command line "make run-android", ok, I'll try!
