### ISSUE TITLE
Issues building iOS application

### ISSUE THREAD

**Issue by samnazarko** [mattermost/mattermost-mobile#2346]
#### Summary
I am unable to run make build-ios

#### Environment Information

- OS Version: macOS Mojave

#### Steps to reproduce
Run make build-ios

#### Expected behavior
My Fastlane environment file is:

```
APP_NAME="OSMC Chat"
SYNC_IOS_PROVISIONING_PROFILES="true"
MAIN_APP_IDENTIFIER="tv.osmc.chat"
SUBMIT_ANDROID_TO_GOOGLE_PLAY="true"
SUPPLY_TRACK="beta"
BUILD_FOR_RELEASE="true"
SUBMIT_ANDROID_TO_GOOGLE_PLAY="false"
SUPPLY_PACKAGE_NAME="tv.osmc.chat"
EXTENSION_APP_IDENTIFIER="tv.osmc.chatShare"
IOS_APP_GROUP="group.tv.osmc.chat"
IOS_ICLOUD_CONTAINER="iCloud.tv.osmc.chat"
MATCH_USERNAME="myemail"
MATCH_PASSWORD="mypassword
MATCH_APP_IDENTIFIER="tv.osmc.chatShare,tv.osmc.chat"
SUBMIT_IOS_TO_TESTFLIGHT="true"
MATCH_TYPE="appstore"
IOS_BUILD_EXPORT_METHOD="appstore"
```

#### Observed behavior
When I try and build the app, I get:

```
[16:50:47]: ▸ === BUILD TARGET MattermostShare OF PROJECT Mattermost WITH CONFIGURATION Release ===
[16:50:47]: ▸ Check dependencies
[16:50:47]: ▸ Code Signing Error: No profiles for 'tv.osmc.chatShare' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'tv.osmc.chatShare'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
[16:50:47]: ▸ Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 12.1'
```

#### Possible fixes
I’m not sure why this is the case. I went in to XCode and temporarily renamed the app to tv.osmc.chatShare so that XCode would generate a profile. I see that this is now reflected under Certificates, Identifiers & Profiles on the Apple Developer page.

Many thanks

Sam

**Comment by amyblais** [comment]
I pinged our devs on this and they said that this might help: https://docs.fastlane.tools/codesigning/troubleshooting/.

**Comment by amyblais** [comment]
Hi @samnazarko, the other issue was closed a while ago, let me know if you are still experiencing this issue and need further help with this and we can re-connect with our devs.

**Comment by jasonblais** [comment]
Given the related issue was closed https://github.com/mattermost/mattermost-mobile/issues/2347, and there hasn't been recent activity, we'll assume that the problem is fixed or is no longer valid. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
