### ISSUE TITLE
Issues building Android application on macOS: dependencies unclear

### ISSUE THREAD

**Issue by samnazarko** [mattermost/mattermost-mobile#2347]
#### Summary
During make build-android; I receive a message telling me I need to install the JDK.

#### Environment Information

- Device Name: MacBook
- OS Version: macOS Mojave

#### Steps to reproduce
Install dependencies (Android Studio + SDKs) as advised in tutorial on a vanilla macOS install

#### Expected behavior
I am told to I need to install the JDK. I do not have java or javac in my path so it is clear it is not installed. I don't know which version of the JDK is appropriate. Will JDK11 suffice?

Thanks

Sam

**Comment by svelle** [comment]
JDK 8 will work 100%, can't give any guarantees about newer versions though. Maybe that should be added to the documentation to avoid confusion in the future.

**Comment by enahum** [comment]
When you run the command there are some files that get moved from `'/Users/samnazarko/Code/Git/mattermost-mobile/android/app/src/main/java/com/mattermost/rnbeta/`` to a folder with your package name, make sure those files are in the above folder before running the build command. you can make sure that is the case by resetting the git branch

**Comment by samnazarko** [comment]
git status shows that the files are untouched:

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ios/Mattermost/Mattermost.entitlements
	modified:   ios/MattermostShare/MattermostShare.entitlements

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	fastlane/env
	osmc_env.sh
```

````
 ls -l android/app/src/main/java/com/mattermost/rnbeta/
total 160
-rw-r--r--  1 samnazarko  staff  14985 19 Nov 13:45 CustomPushNotification.java
-rw-r--r--  1 samnazarko  staff   4902 19 Nov 13:45 InitializationModule.java
-rw-r--r--  1 samnazarko  staff   1077 19 Nov 13:45 InitializationPackage.java
-rw-r--r--  1 samnazarko  staff    941 19 Nov 13:45 MainActivity.java
-rw-r--r--  1 samnazarko  staff   4379 19 Nov 13:45 MainApplication.java
-rw-r--r--  1 samnazarko  staff   1921 19 Nov 13:45 MattermostManagedModule.java
-rw-r--r--  1 samnazarko  staff   1040 19 Nov 13:45 MattermostPackage.java
-rw-r--r--  1 samnazarko  staff    952 19 Nov 13:45 NotificationDismissService.java
-rw-r--r--  1 samnazarko  staff   1801 19 Nov 13:45 NotificationPreferences.java
-rw-r--r--  1 samnazarko  staff   4143 19 Nov 13:45 NotificationPreferencesModule.java
-rw-r--r--  1 samnazarko  staff   3293 19 Nov 13:45 NotificationReplyService.java
-rw-r--r--  1 samnazarko  staff   8618 19 Nov 13:45 NotificationsLifecycleFacade.java
```

**Comment by enahum** [comment]
@samnazarko perhaps you could join us in our community server and there I could help you a bit more, even others can jump in to help you. https://community.mattermost.com best place to talk about this would be the [ ~Native Mobile apps](https://community.mattermost.com/core/channels/native-mobile-apps) channel

**Comment by amyblais** [comment]
Has this issue been resolved? If not, I encourage joining our [Mobile app channel](https://community.mattermost.com/core/channels/team-icu) on our community server to further troubleshoot this as Elias suggested.

**Comment by samnazarko** [comment]
Unfortunately this hasn't been resolved.
I had a chat with @enahum but I didn't receive a response to recent messages.

My understanding is that the current documentation is out of sync; and I am still unable to properly build the Mattermost application for iOS.

**Comment by enahum** [comment]
@samnazarko perhaps you can join the mobile channel and ping me there my username is `@elias` and we could potentially jump into a screen sharing and see what can be the issue

**Comment by samnazarko** [comment]
I am in the mobile channel and we discussed this previously, although I can appreciate that you may have been busy at the time. I'll give you a ping shortly.

**Comment by enahum** [comment]
@samnazarko is it ok to close this issue now?

**Comment by samnazarko** [comment]
Yes. Thank you so much for your help!
