### ISSUE TITLE
Mattermost iOS deviceId something been "" or "null"

### ISSUE THREAD

**Issue by shawn111** [mattermost/mattermost-mobile#2349]
#### Summary
Mattermost iOS deviceId something been "" or "null".
Remove application from background and re-launch could fix the issue.

#### Environment Information
- Device Name: Iphone 8
- OS Version: iOS 12.1
- Mattermost App Version: 1.13.1 (Build 151)
- Mattermost Server Version: 5.2.1

#### Steps to reproduce
It happens randomly but it just happened on iOS. (We didn't find any android devices has this kind of issue.)

#### Expected behavior
The deviceId should be something like apple_rn:e61cac7a988e69ed8293a38643a220ec8a5d4e5f409653e4fa7d7bb5424bc123.

#### Observed behavior
```
mattermost=> select id, deviceid  from  sessions where props like '%"os":"iOS"%';
             id             |                                 deviceid                                  
----------------------------+---------------------------------------------------------------------------
 dobtx917xib5xfspbzqz4yam7w | 
 y8z6ab7sof8gijycy3a9w7yhea | 
 mhy5mqf5itgufx99khdzxui8ph | 
 xsip71hafjn79ga831iima7hoo | apple_rn:c6b78012c73eb3f25dc0bb45d3e3ed910871114a7d4a502c5fdf40b2dc00e123
 b4d6ma89w7ybddfanuygf61tzo | apple_rn:bc69d19134c3a06298b4e1361f271935fc23bb88599ecd837f2b2de56902a123
 zcicsb5amid5mge93x6ckmsqxw | apple_rn:687070936b269bf3e0d31856e279ea3a253f16575b5cf35a3ab5fe3695936123
 3nuwzd6spbbhdqdodcepwdemaw | apple_rn:ee13f4532310a5ed62648fa57502dd5a154f3cccb6ffae967c99a63eec33f123
 b6uh3t9dc78um81ejqbw47koir | apple_rn:e61cac7a988e69ed8293a38643a220ec8a5d4e5f409653e4fa7d7bb5424bc123
 kzq686rc4tnp5jpoapi4z3puzc | apple_rn:3c7123b18dd09005668ffca42225c13709a67ae02b40b56878a3699c21627123
 1sbemn3ddffzfb9iak6sr4jffr | apple_rn:002808c32bd2ea3901506d4b6912a4127876be9aa625dd4d5684d1c7cfefb123
 8bzcqd8w77d6uc8gxrdoszt6pa | apple_rn:4148f25736bb0ac7e8b194d9343f5be32de5b24ce9d8e52eaa7bc75821fbd123
```
#### Possible fixes
The issue might cause in configurePushNotifications.
We didn't capture the correct deviceId from APNs.

**Comment by enahum** [comment]
When the app opens it requests the device id, if it is the first time it will ask for permissions. 

If the permission is granted it will request the id and once it gets it will register the device Id on login or when opening the app at a later time, each time the app is opened it will do the same.

Please check:
* The permission was denied (in that case needs to be enabled manually in the device notification settings)

**Comment by shawn111** [comment]
Hi @enahum,
The notification permission was allowed.

![screenshot](https://chat.easystack.io/files/hkptddfupbrd3picjtifc1hrry/public?h=-XyQ8f9xend1VZ0qiK2gZuKFpIa2NNwHo44KxGZO5FE)

**Comment by amyblais** [comment]
Has this issue been resolved? If not, I encourage joining our [Mobile app channel](https://community.mattermost.com/core/channels/team-icu) on our community server to further troubleshoot this.

**Comment by amyblais** [comment]
Closing this as we haven't received an update on this for a while,

**Comment by shawn111** [comment]
@amyblais,
It been resolved, after upgrade to new version of mattermost-mobile.
Thanks
