### ISSUE TITLE
Build iOS and Android App using Google SSO

### ISSUE THREAD

**Issue by jacobgude** [mattermost/mattermost-mobile#2374]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Would like to build mobile iOS and android app using Google SSO. Documentation says to fill out an issue to begin process.

#### Environment Information

- Device Name: 
- OS Version: 
- Mattermost App Version: 
- Mattermost Server Version:

#### Steps to reproduce
How can we reproduce the issue?

#### Expected behavior
Describe your issue in detail.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
@jacobgude are you aware this will. We’d some development from your end, right? And perhaps once is done if you find a way to make it optional you could submit a PR to support this on build time ;)

**Comment by enahum** [comment]
Duplicate of #622
