### ISSUE TITLE
Playing audio attachments on iOS does not work

### ISSUE THREAD

**Issue by plattreuter** [mattermost/mattermost-mobile#2394]
#### Summary
Playing audio attachments on iOS does not work

#### Environment Information

- Device Name: Apple iPhone XS
- OS Version: 12.1
- Mattermost App Version: 1.14.0
- Mattermost Server Version: 5.4.0

#### Steps to reproduce
Tap on an audio file (e.g. mp3) inside a channel in the iOS app.

#### Expected behavior
The native file handler (iOS audio player) should appear and play the mp3.
On Android you're able to download audio files and play it on the device, at least.

#### Observed behavior
The default audio file preview image opens as if the attachment was an image file.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @plattreuter.  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Closing this as there hasn't been activity on this for a while,
