### ISSUE TITLE
What is the _exact_ version of npm required to build an app?

### ISSUE THREAD

**Issue by mgrebenets** [mattermost/mattermost-mobile#2398]
The instructions at https://developers.mattermost.com/contribute/mobile/developer-setup/ are saying 

> Your most likely using the wrong version of npm. Recommended is 9.3.0.

However, `npm` doesnt have version `9.3.0`, `node` does.
Maybe things like this are clear for JS devs, but it doesn't really help to someone who doesn't have experience with `node` and `npm`.
Even after installing `node` version `9.3.0` I still had issues with using `npm` version `5.x.x`, so I had to upgrade `npm` separately to `6.4.1`.
Is it even the correct version?

Shouldn't the documentation be more clear?

**Comment by enahum** [comment]
I’m using node 10.11.0 and npm 6.4.1

**Comment by mgrebenets** [comment]
Thanks @enahum.
I've got success with both node 9.3.0 and node 10.11.0.
And latest yarn, haven't had success with npm :(, fails to download packages with "end of stream" error.

Should the doco specify both node and npm version?
The default npm version for node 9.3.0 is 5.x.y (don't recall completely) and that version doesn't support `npm ci` command.

**Comment by amyblais** [comment]
Has this issue been resolved? If not, I encourage joining our [Mobile app channel](https://community.mattermost.com/core/channels/team-icu) on our community server to further troubleshoot this.

**Comment by amyblais** [comment]
Closing this as we haven't received an update on this for a while,
