### ISSUE TITLE
Bundle install and bundle update are missing from Makefile

### ISSUE THREAD

**Issue by mgrebenets** [mattermost/mattermost-mobile#2400]
While trying to `make build-ios` I get tons of errors with regards to missing gems.
The gems are listed in `fastlane/Gemfile`, but `Makefile` has no rule to install those gems.
Shouldn't there be another pre-build step in `Makefile` to run at least `bundle install && bundle update`?

**Comment by enahum** [comment]
@mgrebenets appreciate your input, right now our CI runs `bundle install` in a different step, but I'll be up to accept a PR that will include that step in the Makefile if you want to submit one ;)

note: there is no need to run `bundle update` after running `bundle install` as we don't want newer unproven version installed to build the app.

**Comment by mgrebenets** [comment]
Should `Gemfile` list specific versions of the gems then, so there's no unwanted updated happening?

Also, should `cocoapods` gem be part of the bundle too?
They have breaking changes from time to time.

On CocoaPods part, would it be even better to commit `Pods` directory which is the default recommended approach?
https://guides.cocoapods.org/using/using-cocoapods
> We recommend that you keep the Pods directory under source control, and don't add it to your .gitignore. 

I was lucky that I had CocoaPods installed and configured.
But if that's not the case, it may take quite a long time to run `pod setup` for the first time.
I'd really love to be able to clone repo and build the project right away (well, there's still the node packages, but at least I don't need to install pods).

Also, if pods are committed, I don't really need cocoapods gem.

**Comment by enahum** [comment]
I see your point on not having to install cocoapods to download the dependencies, maybe is worth it, and it looks like it is their recommendation although that same link mentions the fact the adding the pods or not depends on each project etc and they are benefits to check them in and benefits to ignore them.

I’m not against but it is a huge amount of data to be checked in and for me the reasons have to be very good and not only based on having to install cocoapods

**Comment by mgrebenets** [comment]
`ios/Pods` so far is 260K.
I was also negative about the approach, but later came to appreciate it.
Our CI servers are behind firewall and can't even install or update pods, so we had to do it out of necessity as well (an alternative would be to maintain internal copy of all the pods we use, which we did too and it wasn't pleasant either).

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
