### ISSUE TITLE
Documentation and examples are out of sync.

### ISSUE THREAD

**Issue by mgrebenets** [mattermost/mattermost-mobile#2401]
The https://github.com/mattermost/mattermost-mobile/blob/master/fastlane/env_vars_example and https://developers.mattermost.com/contribute/mobile/build-your-own/ are out of sync.

Example file has vars like `IOS_APP_NAME` while the page says it's `APP_NAME`.
Doesn't really help with building the app.

Helps even less for those who pay for E10 or E20 plans.

**Comment by enahum** [comment]
Thanks @mgrebenets I've submitted a PR #2402 to update the example env vars
