### ISSUE TITLE
make build-ios removes node_modules each time

### ISSUE THREAD

**Issue by mgrebenets** [mattermost/mattermost-mobile#2404]
Whenever I'm running `make build-ios` the `node_modules` folder is removed.
It seems like it's part of `npm ci` command.

Is there a better way for me to build and test incrementan changes without re-downloading all node packages?
I'm working behind a really bad proxy, it's so bad that it simply fails under load when I try to get all 350mb of node packages :/

I'd love to be able to download the node packages once as part of `pre-run` and then be able to rebuild only the iOS code changes.

Could that be achieved by moving iOS build step to a separate make rule?
E.g. `build-ios` is for CI "clean" builds and then there's another rule that doesn't try to install node packages and install pods?

**Comment by bezumkin** [comment]
> Is there a better way for me to build and test incrementan changes without re-downloading all node packages?

Run this command once
```shell
make pre-build
```

Then you can build app so many times as you need:
```shell
cd fastlane && BABEL_ENV=production NODE_ENV=production bundle exec fastlane ios build && cd ..
```

Works for me well
