### ISSUE TITLE
Getting "premature close" errors with npm install

### ISSUE THREAD

**Issue by mgrebenets** [mattermost/mattermost-mobile#2405]
Using node version 0.9.3 and npm version 6.4.1 I'm getting errors like this when running `make pre-run` or `make pre-build` or just `npm install`.

```
Unhandled rejection Error: premature closell extract invert-kv@2.0.0
    at PassThrough.onclose (/Users/bigmac/.nvm/versions/node/v11.3.0/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
    at PassThrough.emit (events.js:187:15)
    at emitCloseNT (internal/streams/destroy.js:59:8)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

The package name doesn't really matter.

I end up retrying again and again until I get that "lucky" run when all node packages are downloaded and extracted and I can proceed to next step.

Is there something wrong on my end?
I tried to connect via fastest network connection I have and there's no proxy in between.

**Comment by mgrebenets** [comment]
So it looks like `node` version has to be `9.3.0`.
`npm` version has to be `6.4.1` (I'm not sure what's the lowest version that can be used, but I know that default 5.x.x will not work).
Running `npm install` or `npm ci` commands directly did not work for me.
I had to use `make pre-run` instead 🤷‍♂️

**Comment by mgrebenets** [comment]
Running fresh `npm ci` command on 9.3.0/6.4.1 node/npm I occassionally get this:

```
npm WARN prepare removing existing node_modules/ before installation
npm ERR! path /Users/bigmac/dev/cba/mattermost-mobile/node_modules/mattermost-redux/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/bigmac/dev/cba/mattermost-mobile/node_modules/mattermost-redux/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bigmac/.npm/_logs/2018-11-30T01_50_41_935Z-debug.log
```

And `mattermost-redux` is exactly the package that's causing issues while running the app: https://github.com/mattermost/mattermost-mobile/issues/2407

**Comment by mgrebenets** [comment]
Same premature close when using node 10.11.0 and npm 6.4.1

Also, `make pre-run` fails with same error too, so it looks like I got one-off successful run :/

**Comment by mgrebenets** [comment]
So it looks like using `yarn` to install packages _may_ be the workaround.
Still both with `npm` and with `yarn` I end up having this issue: https://github.com/mattermost/mattermost-mobile/issues/2407

**Comment by amyblais** [comment]
Hi @mgrebenets, was this issue resolved earlier? If not, I encourage joining our [Mobile apps channel on our community server](https://community.mattermost.com/core/channels/native-mobile-apps) and our devs or other community members will be able to help.
