### ISSUE TITLE
My messages don't highlighted

### ISSUE THREAD

**Issue by swood** [mattermost/mattermost-mobile#2413]
Hello.

I'm using the application Beta on iOS of version 1.13.1.
And I sight that messages I wrote to any channels don't highlight whereas on the desktop or web version of the same chat 
Do you need some proof of that or it is known error? Or it is not a bug, and I have to solve it by myself?

**Comment by swood** [comment]
Hi, @hmhealey, you're right. Please, mention it. 
Also, I'd like to know why it was an intentional design decision?

**Comment by hmhealey** [comment]
I just asked some of our designers about it, and we're trying to cut down on the number of visual elements in the post list to make it easier to read. It's something we're trying out on the mobile app, and we're also considering removing that effect on the web and desktop apps as well.
