### ISSUE TITLE
Stay logged in

### ISSUE THREAD

**Issue by jsha** [mattermost/mattermost-mobile#2415]
I've noticed that the Mattermost Android app periodically logs out the user, presumably every 30 days. I would recommend using persistent sessions by default (i.e. "stay logged in"). When users get logged out periodically, they tend to choose weak passwords that are easy to remember and easy to type, particularly on mobile. So periodically logging out users can actually act as a detriment to security, not a benefit.

**Comment by enahum** [comment]
Hey @jsha thanks for the feedback in fact the session length is controlled by a server setting that the administrator can set in **System Console > Security > Sessions**

**Comment by jsha** [comment]
Awesome, thanks!
