### ISSUE TITLE
Support round icons

### ISSUE THREAD

**Issue by andrewbanchich** [mattermost/mattermost-mobile#2457]
Pixel Launcher (the default launcher for Pixel phones) uses circular app icons. Almost all of my apps support this, but Mattermost doesn't, so the icon becomes a white circle with a very small blue square inside.

It would look much better and be fairly easy to fix this.

**Comment by enahum** [comment]
@andrewbanchich thanks for the report.

We have a Help Wanted ticket https://github.com/mattermost/mattermost-server/issues/9758 just for this, would you be interested in doing the implementation?

**Comment by andrewbanchich** [comment]
I'm not sure how much free time I have at the moment, but I would like to get involved in contributing to Mattermost when I do have more time.

**Comment by JacobDB** [comment]
Just to add on to this – technically, Pixel phones use Adaptive Icons, not just circular. I have mine set to squircle at the moment. See [Google's documentation](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive).

**Comment by amyblais** [comment]
Closing this as there is a Help Wanted ticket to track this,

**Comment by enahum** [comment]
@amyblais can you link the help wanted ticket?

**Comment by amyblais** [comment]
Ticket here: https://github.com/mattermost/mattermost-server/issues/9758
