### ISSUE TITLE
The iPad version could use the desktop interface rather than smartphone

### ISSUE THREAD

**Issue by nicolinuxfr** [mattermost/mattermost-mobile#2463]
#### Summary
The iPad/tablet version of the app uses a bigger iPhone/smartphone interface, rather than using the desktop website. In particular, the sidebar with all channels is hidden by default and takes almost the whole screen when displayed :

![img_0126](https://user-images.githubusercontent.com/2078386/50091381-83c2fa80-020b-11e9-86bd-b24c2b20c29d.png)

![img_0129](https://user-images.githubusercontent.com/2078386/50091445-bbca3d80-020b-11e9-9f41-529d4df174c3.png)

#### Environment Information

- Device Name: iPad Pro 12,9 inch
- OS Version: iOS 12.1.1
- Mattermost App Version: 1.15.0 (Build 163)
- Mattermost Server Version: 5.5.0

#### Possible fixes

The desktop version of Mattermost is really great on the iPad : 

![img_0128](https://user-images.githubusercontent.com/2078386/50091488-d4d2ee80-020b-11e9-952b-d471337ef0b6.png)

I think the iOS app should behave the same way on an iPad.

**Comment by amyblais** [comment]
Closing this as there hasn't been activity here for a while,
