### ISSUE TITLE
[Android]Date of timeline is incorrect

### ISSUE THREAD

**Issue by tgly307** [mattermost/mattermost-mobile#2477]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
The showed date in a channel is incorrect, the date showed in app is earlier than current date. For example, current date is 2018-12-24, but the date showed in app is 2018-12-23.

#### Environment Information

- Device Name: HUAWEI MATE 20 pro
- OS Version:  Android 9.0
- Mattermost App Version: 1.15.0(build 165) 
- Mattermost Server Version: 5.3.1-rc1

#### Steps to reproduce

1. Download app from Google Play
2. Login the self-hosted server.
3. Check the date, compare the date with browser UI.

#### Expected behavior
The date showed will same with browser UI or IOS app.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
The date showed in Android app is earlier than current date.
The Browser screenshot(mobile mode on Chrome for compare):
![image](https://user-images.githubusercontent.com/25153311/50401637-2e6a8880-07cb-11e9-92c0-ddca132da709.png)

The app screenshot:
![image](https://user-images.githubusercontent.com/25153311/50401677-7093ca00-07cb-11e9-842d-86518dbacfef.png)

I also checked the IOS app and desktop app(windows 10), the date on these platform is correct. Only wrong date on Android app.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by tgly307** [comment]
@enahum Yes, I checked the device settings, the date is right. My server and clients are in the same time zone(UTC/GMT+08:00).
I have tried the android client on 2 phone,1 pad and android simulator on PC,  the date is all incorrect( They are all ahead of the day ). But when I access mattermost by browser on these devices, the date is correct.

**Comment by tgly307** [comment]
@amyblais I have upgraded my server to 5.6.2 and set ExperimentalTimezone enabled, it doesn't work.
I also try this on the community server, the issue still exists.

**Comment by jasonblais** [comment]
Hmm, would you happen to have any other apps on your Android device? Do they show the correct date?

Trying to think of reasons why the date would be incorrect on Android but correct elsewhere.

**Comment by tgly307** [comment]
@jasonblais I have check the date of telegram and nextcloud(I just find these show date information), it is correct.
I guess if this problem is related to the time zone. I don't have an Android environment in other time zones, so I can't test it. Have you tried it on your Android device? Is there the same problem?

**Comment by razbag** [comment]
I am also confirm that  current date is 2019-01-07, but the date showed in app is 2019-01-06.

Time is correct only problem with date 

Environment Information
Device Name: Xiaomi Mi 5
OS Version: Android 8.0
Mattermost App Version: 1.15.1(build 166)
Mattermost Server Version: 5.5.0

**Comment by hmhealey** [comment]
Does this happen with the experimental timezone setting disabled, or is it just when it is enabled? It might be something to do with that

**Comment by razbag** [comment]
> Does this happen with the experimental timezone setting disabled, or is it just when it is enabled? It might be something to do with that

I try with experimental timezone setting enabled

**Comment by tgly307** [comment]
@hmhealey Hi, I have tried to set `ExperimentalTimezone` true and false, then restart the server. But the issue still exists. 
I alse tried to set the timezone different, the displayed time changed, but the date is still wrong.

**Comment by tgly307** [comment]
> I also tried version [1.14.0](https://github.com/mattermost/mattermost-mobile/releases/download/v1.14.0/Mattermost.apk) like @razbag , and the date is correct. So this problem should be generated between 1.14 and 1.15, I hope this information helps.

I found the statement that the 1.14 version date is completely correct is wrong. I looked at the dates of all the channels in version 1.14 and found that some channel dates are correct and some are wrong. This is very strange. So this reason seems a bit complicated, it may be that there is some kind of defect before, but it is completely exposed in the 1.15 version.

**Comment by hmhealey** [comment]
We're still having trouble reproducing the exact issue, but maybe we can try to replicate what you're seeing as best we can. Can you answer all of the following?

1. What time zone is your phone using in the settings?
2. Do you have the experimental timezone setting currently enabled? If so, what timezone is your account using and is it set to automatically detect the timezone?
3. What are the dates and times of two posts that have the date line between them?

If we know these, we might be able to reproduce the exact scenario you're seeing locally so we can try to debug the issue

**Comment by cpajaron** [comment]
Hi, 
Is there a fix for this issue already? I am experiencing the same as well. Also my colleague experienced the same issue.
I have done the same troubleshooting. Android OS and apps have been updated to the latest version but no luck.

**Comment by razbag** [comment]
Hi @tgly307 I have update Mattermost Mobile to version 1.15.2 and  now in my side date and time is ok for now

**Comment by tgly307** [comment]
@razbag thx bro, it works! 
Thank you for your outstanding work guys. @amyblais @jasonblais 
I will close this issue.

**Comment by Reonaydo** [comment]
I have same problem with android application. All messages are in the previous day.
Version 1.21.2
Timezone: GMT+8

**Comment by amyblais** [comment]
@Reonaydo This issue has been fixed in upcoming v1.22 release.
