### ISSUE TITLE
Android minSdkVersion changed from 21 to 24 (Android 5/6 support dropped)

### ISSUE THREAD

**Issue by dbrgn** [mattermost/mattermost-mobile#2480]
In #2470, the `minSdkVersion` for Android builds was increased from 21 to 24.

What this means, is that Android 5 and 6 are not supported anymore, and Android 7+ is required.

Or, in other words, as of October 2018, you are cutting off support for over half (50.3%) of Android users.

https://developer.android.com/about/dashboards/#Platform

![img](https://tmp.dbrgn.ch/screenshots/20181225231012-ks9sfgdt.png)

I am asking you to reconsider this decision. I am aware that supporting older Android versions is inconvenient (I'm a regular contributor to a complex Android application that supports Android 4.1+), but this is quite a big change. I'm regularly compiling the Mattermost Mobile app for use in an association I'm involved in, and some of the users will not be able to use Mattermost on their mobile anymore.

**Comment by jasonblais** [comment]
Thank you @dbrgn for the feedback!

The decision to increase the minimum SDK version was due to a requirement by Google Play:

> In the second half of 2018, Play will require that new apps and app updates target a recent Android API level. This will be required for new apps in August 2018, and for updates to existing apps in November 2018. This is to ensure apps are built on the latest APIs optimized for security and performance.

https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

As a result, the Android 7+ requirement was applied for our December 16th release (1.15.0). Previous versions can, however, continue to use 1.14 on newer Mattermost servers without issues.

Let us know if you have any questions or if we can help clarify the decision.

**Comment by dbrgn** [comment]
Hi @jasonblais. This decision by Google only affects the targetSdkVersion, not the minSdkVersion. You can increase the targetSdkVersion without changing the minSdkVersion.

Cross-version compatibility can be done with the support library (now renamed to https://developer.android.com/jetpack/androidx/).

**Comment by enahum** [comment]
Hi @dbrgn that is true indeed, but we ended up bumping the `minSdkVersion` also cause the app is now using some specific API not available in SDK level 21-23 and was causing all those devices to crash at startup anyway.

Right now people with API levels lower than 24 will keep continue using 1.14 as the latest version and people with API level 24+ will get the updates.

In any case feel free to submit a PR to change the `minSdkVersion` but include a fix to remove specific notifications from the **NotificationManager** in a way that is supported on previous API levels.

do you think you can do that?

**Comment by dbrgn** [comment]
> do you think you can do that?

I can't promise anything, because I don't have much capacity for other projects at the moment.

The general way how this can be solved though, is by adding the `@TargetApi(Build.VERSION_CODES.O)` annotation to methods that use new APIs (notification channels), so that the app can be built for the old target SDK. To check whether the notification channels are supported, you can then use `Build.VERSION.SDK_INT >= Build.VERSION_CODES.O` in the code.

**Comment by sergeyzhukov** [comment]
@enahum I built the app from the master branch (version 1.19), lowered minSdkVersion to 23 and app runs without any issues or crashes. Able to log in, write a message, send image and etc. Haven't tested notifications.

**Comment by greenertux** [comment]
Could you please review the text on https://mattermost.com/download/#mattermostApps?
It states the Android App would work on "Android 8.0+" while "Android 7.0+" would be correct, right?

**Comment by jasonblais** [comment]
@greenertux Great, thanks for the catch! I'll queue the the note to be updated to Android 7+

@enahum more an FYI that iOS 10.3 is marked as supported on the README, but 11+ on our download page. I believe the intent is 11+ since earlier versions are not supported by Apple.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity

**Comment by AndreKR** [comment]
Closing it kind of suggests that it has been solved, but I don't think it has.

I was watching this issue because I'm on Android 5 and I'd like to use Mattermost in my company.

**Comment by enahum** [comment]
Sorry @AndreKR in fact we made a concious decision to support Android 7+, I can say we’ll not be supporting Android 5. I understand this can be a pain for some people, like yourself, but as you would understand supporting all versions of Android is a somewhat impossible task.

Sorry for the inconvenience :/

**Comment by fisforfaheem** [comment]
I want to know would could be the possible benefits of bumping the minsdk version from 21 to 25 ? will it improve the code, performance etc?
