### ISSUE TITLE
iOS notification badge stuck on unread messages

### ISSUE THREAD

**Issue by arsradu** [mattermost/mattermost-mobile#2502]
#### Summary
iOS notification badge stuck on unread messages, although all the chats are up to date (already read).

![image-1](https://user-images.githubusercontent.com/5080446/50962464-fa81a980-14d2-11e9-851b-3208f3031204.jpg)

#### Environment Information

- Device Name: iPhone 7
- OS Version: 12.1.3 Beta 3 (same issue on 12.1.2 though)
- Mattermost App Version: 1.15.1 (Build 166)
- Mattermost Server Version: 5.3.0 (Build 5.3.1)

#### Steps to reproduce
Well, just chat, receive a message notification, read the message, and notice the badge is still present, showing the number of unread messages, even after reading all the messages.

#### Expected behavior
If there are no unread messages, there should be no badge saying there are.

#### Observed behavior
Notification badge with the number of unread messages is still displayed even after reading all the messages, making things really confusing.

#### Possible fixes
I'll let you decide on that. :)

**Comment by amyblais** [comment]
Hi @arsradu,

This issue has been fixed and the fix will be available in the next Server release (v5.7): https://mattermost.atlassian.net/browse/MM-13600.

**Comment by arsradu** [comment]
Awesome. Thank you! :)

**Comment by weekscharlie** [comment]
Came here to report this if it hadn't been already.  Thanks for the quick ID and response on this!

**Comment by amyblais** [comment]
v5.7 and RN v1.15.2 have been released so I'll close this Issue for now.

If you sill see this issue, you may be hitting an edge case which we have a ticket for fixing in a future release: https://mattermost.atlassian.net/browse/MM-13722.
