### ISSUE TITLE
Not enough margin at the bottom of the message list

### ISSUE THREAD

**Issue by gigaherz** [mattermost/mattermost-mobile#2506]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
The mobile app doesn't have any margin between the end of the chat history and the message inputbox, giving the impression that there is more to scroll since it seems like the message is cut off.

#### Environment Information

- Device Name: Xperia Z5 Compact
- OS Version: Android 7.1.1
- Mattermost App Version: 1.15.1 (Build 166)
- Mattermost Server Version: 5.6.0 (Build 5.6.2)

#### Steps to reproduce
How can we reproduce the issue?

#### Expected behavior
There should be enough margin below the last post to indicate that the post isn't cut off

#### Observed behavior
![image](https://user-images.githubusercontent.com/685851/51044461-6c382100-15c1-11e9-8831-2fd5a32f8675.png)

#### Possible fixes
Add a bit more margin at the bottom.

**Comment by amyblais** [comment]
Hi @gigaherz,

Thank you for reporting this, I don't have an Android device to test this on so I'll ask our QAs to help test this.

**Comment by amyblais** [comment]
@gigaherz,

An update on this: our QA team hasn't been able to reproduce this, so it is possible that this an issue specific to the device / OS.

**Comment by MartB** [comment]
This seems to be an issue with my Mate 20 pro too, it looks super weird to have little to no space down there.

**Comment by asummers** [comment]
Can also reproduce on Pixel 3 which runs Google's stock Android. There should be a few pixels of padding added to the bottom of the list component. Very curious which Android device the QA person tested with that they're unable to reproduce.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity

**Comment by MartB** [comment]
This got fixed with the re-design of the input section down there anyway, so yeah right call to close this.
