### ISSUE TITLE
Text input looses focus with external keyboard

### ISSUE THREAD

**Issue by 2xB** [mattermost/mattermost-mobile#2512]
#### Summary
When an external keyboard is used, the chat input text field looses focus as soon as the on-screen-keyboard is hidden.

#### Environment Information

- Device Name: Samsung Galaxy Tab S2
- OS Version: 7.0
- Mattermost App Version: 1.15.1 (Build 166)
- Mattermost Server Version: 5.5.0

#### Steps to reproduce
Select the chat input text field to write text. The Android keyboard opens.
Enter any character via the bluetooth keyboard.

#### Expected behavior
The Android keyboard closes because another input method is used. The text field stays focused and accepts text input from keyboard.

#### Observed behavior
The Android keyboard closes and the text input field looses focus. Any character that is entered afterwards is ignored.

#### Possible fixes
Perhaps this is because the closing Android keyboard resizes the window, therefore triggering redraw?

**Comment by amyblais** [comment]
Hi @2xB,

I've passed this along for QA testing, but our developers gave a heads-up that this is currently expected as we don't have official support for external keyboards.

**Comment by amyblais** [comment]
Hi @2xB, since we don't officially support this yet, would you be open to creating a feature request for this?

**Comment by 2xB** [comment]
Although I do not quite see where this is a missing feature, because this is specific to all resizing on-screen keyboards and not only to the behaviour of on-screen keyboards in use with an external keyboard, I nevertheless created a feature request:
https://mattermost.uservoice.com/forums/306457-general/suggestions/36676618-support-external-keyboard
I also created a feature request for a probably linked problem:
https://mattermost.uservoice.com/forums/306457-general/suggestions/36676711-android-multi-window-support

**Comment by amyblais** [comment]
Closing this via https://github.com/mattermost/mattermost-mobile/issues/2521
