### ISSUE TITLE
SSO login page never loads with IOS-10

### ISSUE THREAD

**Issue by pesintta** [mattermost/mattermost-mobile#2514]
#### Summary
Current versions of mattermost-mobile cannot complete SSO login on IOS-10

#### Environment Information
- Device Name: iPad 4th gen
- OS Version: iOS 10.3.3
- Mattermost App Version: 5.6
- Mattermost Server Version: 5.7

#### Steps to reproduce
1. Install latest mattermost-mobile from app store
2. Open app and connect to server that supports SSO, e.g. SAML
3. Try to login using SAML. Observe that SSO login page load is never completed

#### Expected behavior
It is expected that the SSO web-page would load and credentials could be entered.

#### Observed behavior
The issue seems to be that react-native-cookies requires iOS-11 when run in WebKit-mode. This new API is apparently a performance enhancement. The cookie operations however are probably not a performance critical part of mattermost-mobile so old cookie API could be utilized instead.

When run using xcode the following log-output can be observed when the SSO login is attempted:
```
2019-01-20 13:34:19.931 [error][tid:com.facebook.react.JavaScript] 'Unhandled promise rejection', { [Error: WebKit/WebKit-Components are only available with iOS11 and higher!]
  line: 2868,
  column: 26,
  sourceURL: '/var/containers/Bundle/Application/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/Mattermost.app/main.jsbundle',
  framesToPop: 1,
  code: '',
  userInfo: null,
  nativeStackIOS: 
   [ '0   Mattermost                          0x0022df3f RCTJSErrorFromCodeMessageAndNSError + 104',
     '1   Mattermost                          0x001d3da5 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.218 + 184',
     '2   Mattermost                          0x0045805f -[RNCookieManagerIOS clearAll:resolver:rejecter:] + 284',
     '3   CoreFoundation                      0x1e770354 <redacted> + 68',
     '4   CoreFoundation                      0x1e6942b9 <redacted> + 300',
     '5   CoreFoundation                      0x1e697e87 <redacted> + 48',
     '6   Mattermost                          0x001d5823 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1806',
     '7   Mattermost                          0x0026ff05 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 640',
     '8   Mattermost                          0x0026fa89 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 176',
     '9   Mattermost                          0x0026f9d5 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 16',
     '10  libdispatch.dylib                   0x009f8467 _dispatch_call_block_and_release + 10',
     '11  libdispatch.dylib                   0x00a0466f _dispatch_queue_serial_drain + 988',
     '12  libdispatch.dylib                   0x009fba39 _dispatch_queue_invoke + 872',
     '13  libdispatch.dylib                   0x00a04b31 _dispatch_queue_override_invoke + 342',
     '14  libdispatch.dylib                   0x00a0676b _dispatch_root_queue_drain + 666',
     '15  libdispatch.dylib                   0x00a06471 _dispatch_worker_thread3 + 112',
     '16  libsystem_pthread.dylib             0x1dfee87d _pthread_wqthread + 1040',
     '17  libsystem_pthread.dylib             0x1dfee45c start_wqthread + 8' ],
  domain: 'RCTErrorDomain' }
```

#### Possible fixes
I'll create a pull-request for review

**Comment by amyblais** [comment]
Hi @pesintta, thank you for the PR!

**Comment by amyblais** [comment]
Closing this as the PR has been merged for v1.18 release.

@enahum @migbot Does this need a Jira ticket for QA testing now that the PR is merged?

**Comment by esethna** [comment]
@pesintta would you be open to testing to verify this is fixed with your PR? You can use this link to join our Beta app that has your fix. just click this link on your iOS device after installing the TestFlight app: https://testflight.apple.com/join/Q7Rx7K9P

**Comment by pesintta** [comment]
I tested with mattermost beta from testflight today and I am happy to report that the SSO login now works on my device as expected.
