### ISSUE TITLE
I can not add Emoji/reactions

### ISSUE THREAD

**Issue by Bables55** [mattermost/mattermost-mobile#2516]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
There is no pictogram input icon in the iPhone application. I do not see it even if I add a reaction by long pressing the sentence.

#### Environment Information

- Device Name: iPhone SE
- OS Version: iOS 12.1.2
- Mattermost App Version: .15.2 
- Mattermost Server Version: 5.6.3 / 5.7.0

#### Steps to reproduce
Touch the comment input field
Or press and hold a commented comment.
Then select the additional reaction menu and select emoji.

#### Expected behavior
I can not select emoji like desktop PC, and additional reaction does not work.

#### Observed behavior
Error log when touching additional reaction.
{"level":"error","ts":1548062026.8014987,"caller":"app/ratelimit.go:85","msg":"Denied due to throttling settings code=429 key=59.146.208.7"}
This occurs in a large amount in the log.

**Comment by amyblais** [comment]
Hi @Bables55,

I'm not able to reproduce this on a similar environment. Can you try do a long press on a post and you should see a drop-down menu appear?

**Comment by Bables55** [comment]
I may have solved it. I thought that it was a problem of "language", I changed the language of iOS from Japanese to English. Since then, I can add Emoji even in English environment and Japanese environment. And then I can add Emoji even if I return to the Japanese environment.
Restarting iOS did not solve it. Did I have a special accidental incident with My iPhone SE and the other iPhone8?

Is it possible to input normal Emoji instead of "Add reaction"? There is no Emoij insertion icon in the comment input field like the desktop version. In the case of us Japanese, we have a 2-byte character input mechanism (IME: Input Method Editor) so I can enter Emoji via it from the beginning.

**Comment by Bables55** [comment]
It recurred. 

`{"level":"error","ts":1548322322.2159781,"caller":"app/ratelimit.go:85","msg":"Denied due to throttling settings code=429 key="}`

**Comment by Bables55** [comment]
That is the only error sentence. Only the items of ts and key are different, but otherwise the same error is output for a considerable amount.

In my environment, this seems likely to occur in mobile origin. For a while, when the user is not using the "Add Reaction" function, it will almost certainly happen if mobile users use the function to add reactions. After that, when the PC user adds a reaction in the Web browser or the desktop application version, it seems that mobile users can do it after that.

About 2:
Currently we only need to use the desktop version to enter Emoji or via the Japanese keyboard by the OS of the mobile terminal. I do not know the function of Mattermost on the overseas version of the iPhone, but is it premised on using emoji for IME?

**Comment by hmhealey** [comment]
> That is the only error sentence. Only the items of ts and key are different, but otherwise the same error is output for a considerable amount.

Is that the only time you see that error message? The error message seems like it might not be related to reactions.

> After that, when the PC user adds a reaction in the Web browser or the desktop application version, it seems that mobile users can do it after that.

That is odd that the mobile app is able to add reactions after one is added by a user on the web or desktop apps. I'm not aware of any differences between how those work differently than mobile.

> I do not know the function of Mattermost on the overseas version of the iPhone, but is it premised on using emoji for IME?

I'm sorry, but I don't understand your question. The screenshot I sent is how I usually enter emoji on my phone, so I don't know if it's different than how you would enter them on a Japanese keyboard.

**Comment by amyblais** [comment]
Closing this for now as there haven't been updates on this for a while,
