### ISSUE TITLE
Adjust font size - too small

### ISSUE THREAD

**Issue by Bables55** [mattermost/mattermost-mobile#2522]
#### Summary
Font size is too small for some users.
The font size can not be adjusted.

There was dynamic size change in past articles, but I do not want that much. I want the font size to be changeable. It can be set with numbers or large, medium or small.

#### Environment Information

- Device Name:  iPhone SE, 7, 8, X, XS Max
- OS Version: iOS 12.1.2, 12.1.3
- Mattermost App Version: 1.15.2
- Mattermost Server Version: 5.7.0

**Comment by amyblais** [comment]
Hi @Bables55,

Would you be open to sharing this idea in the [Feature request forum here](https://mattermost.uservoice.com/forums/306457-general)?

**Comment by amyblais** [comment]
Thank you for adding the feature request!
