### ISSUE TITLE
Error in mutex.h file: Config.h file not found Xcode 10.1

### ISSUE THREAD

**Issue by ranamateen** [mattermost/mattermost-mobile#2546]
![screen shot 2019-02-04 at 5 33 59 am](https://user-images.githubusercontent.com/12171964/52233391-c5edeb80-28e0-11e9-9945-c28d38efdc5a.png)

I am getting this error "config.h file not found" in mutex.h file. I am using MacOS High sierra 10.13.6 and Xcode 10.1. In glog-0.3.5 folder I have already done the following solution but glog folder do not showing config.h file in it and it is used in the Mattermost-Mobile code as header file in mutex.h file as showing in attached image. 

Close Xcode.
2- cd <Project-Folder>/node_modules/react-native/third-party/glog-0.3.5
3- Run ./configure
4- Run make
5- Run make install
Open Xcode and try building the Project.

Can some one please guide me how to add config.h file in glog folder so this error can remove. Looking forward for your kind response.

**Comment by enahum** [comment]
have you installed the npm dependencies and the cocoapods dependencies by running `make pre-run`

**Comment by ranamateen** [comment]
> have you installed the npm dependencies and the cocoapods dependencies by running `make pre-run`

Yes I have installed npm dependencies and cocoapods dependencies by running 'make pre-run'.

When I run make run it is sending this error in terminal when running in xcode it says config.h file not found. Please see the attached screenshot.

![screen shot 2019-02-05 at 1 44 11 am](https://user-images.githubusercontent.com/12171964/52236184-f5ecbd00-28e7-11e9-9315-60c76ac32ca0.png)

**Comment by enahum** [comment]
anyone else seeing this? I'm definitely not seeing it

**Comment by ranamateen** [comment]
Anybody there to see this issue?

**Comment by ranamateen** [comment]
I removed glog folder from mattermost app and add a new glog folder in the directory by creating a new react native project and replace it with the old glog folder in mattermost code's directory. It worked for me.
