### ISSUE TITLE
Crash stacktrace view allow selection&copy

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#2561]
...so I can report it here.

v1.15.2

**Comment by enahum** [comment]
What is this about?

**Comment by licaon-kter** [comment]
When an error occurs I'm presented with a view where the stacktrace is seen....but I can't interact vith it...I can't copy that stacktrace to open an issue here.

**Comment by enahum** [comment]
Oh that is presented and handled by the OS we can’t do anything about it. What we normaly do is we take a screenshot and report the bug with it.
