### ISSUE TITLE
Mattermost android loses its session after some days

### ISSUE THREAD

**Issue by TheCapsLock** [mattermost/mattermost-mobile#2571]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary

Mattermost loses session on Android after some time. We must reconnect too often by using account/password this is hugely annoying

#### Environment Information

- Device Name: Fairphone 2
- OS Version: 8.1.0
- Mattermost App Version: Classic 3.10.3
- Mattermost Server Version: 5.6.4

#### Steps to reproduce
Login ; wait some time (days)

#### Expected behavior
I never need to enter my credentials again

#### Observed behavior
I need to enter my credentials on a regular basis

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by DSchalla** [comment]
Hi @TheCapsLock,
can you check whether the timeout behavior is related to your configured session length for mobile duration? The behavior you've described sounds like the server admin has it configured that way. See: https://docs.mattermost.com/administration/config-settings.html#session-length-for-mobile-apps-days

**Comment by TheCapsLock** [comment]
@DSchalla thanks for pointing out that peace of documentation, I'll give a try

**Comment by amyblais** [comment]
Closing this for now as there hasn't been activity on this for a while. Please re-open this issue if the problem persists.
