### ISSUE TITLE
[Android] Notification Dot not showing up 

### ISSUE THREAD

**Issue by ajdev6** [mattermost/mattermost-mobile#2619]
#### Summary
Notification Dot is not showing up on app icon.

#### Environment Information

- Device Name: OnePlus 6
- OS Version: 9
- Mattermost App Version: 1.16.1 
- Mattermost Server Version: 5.9.0

#### Steps to reproduce
How can we reproduce the issue?
When a user sends you a message and app is running in background, notification dot is not showing on app icon.

Show Notification Dot is enabled in app settings
 
#### Expected behavior
When a push notification is received and app is running in background , notification dot should appear on app icon.

#### Observed behavior
No notification dot shows up.
![whatsapp image 2019-03-04 at 18 47 17](https://user-images.githubusercontent.com/36064277/53735828-045dd280-3eae-11e9-9713-1fbe815b9058.jpeg)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
Hi @ajdev6, would you happen to know your Mattermost server version? You would normally find the information from Mattermost settings > About this App section.

**Comment by ajdev6** [comment]
> Hi @ajdev6, would you happen to know your Mattermost server version? You would normally find the information from Mattermost settings > About this App section.

5.7.0

**Comment by amyblais** [comment]
Hi @ajdev6,

Letting you know that this is not a bug as the badges on Android are only available on certain devices. Android officially added support for 8.0+ https://developer.android.com/training/notify-user/badges.

Would you like to share this idea on our feature request forum here: https://mattermost.uservoice.com/forums/306457-general?

**Comment by ajdev6** [comment]
Hi @amyblais,

I am testing on OnePlus 6 on Android 9. It supports notification badge. I have diagnosed the issue.
The issue is with mattermost-server payload.

I checked with the server payload in this file https://github.com/mattermost/mattermost-push-proxy/blob/master/server/push_notification.go

We need to update it according to the following docs:
https://firebase.google.com/docs/cloud-messaging/android/receive#sample-receive

https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages

Its not a feature request. The shortcutBadger is already implemented in react native notifications module. 

Hope this helps!

**Comment by amyblais** [comment]
Hi @ajdev6, our developers said that this is a new thing that we have never added support for. Only some devices have had this feature.

**Comment by amyblais** [comment]
Hi @ajdev6, letting you know that we've opened an improvement ticket for this here: https://mattermost.atlassian.net/browse/MM-14467. There is no need to open a feature request issue as we can track this via the Jira ticket. Thanks for reporting this!

**Comment by enahum** [comment]
@ajdev6 can you help clarify what is missing in the payload?

**Comment by amyblais** [comment]
Letting you know that the Jira ticket was closed since this is not supported yet.

Please share this idea on our feature request forum here: https://mattermost.uservoice.com/forums/306457-general.
