### ISSUE TITLE
Android won't compile - missing gradle and google services

### ISSUE THREAD

**Issue by txnathrt** [mattermost/mattermost-mobile#2636]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When attempting to build the Android app it fails with "Could not resolve all artifacts for configuration". It's looking for gradle 3.3.1 and google services 4.2 which don't exist as far as I can tell.

#### Environment Information

- Device Name: 
- OS Version: IDE running on Windows 10 
- Mattermost App Version: latest source code as of 3/7/19
- Mattermost Server Version: 4.10.2

#### Steps to reproduce
Downloaded the latest source, then build and it fails.

#### Expected behavior
I expect the app to compile without issue and run.

#### Observed behavior
A problem occurred configuring root project 'Mattermost'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.3.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.3.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:3.3.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve com.google.gms:google-services:4.2.0.
     Required by:
         project :
      > Could not resolve com.google.gms:google-services:4.2.0.
         > Could not get resource 'https://jcenter.bintray.com/com/google/gms/google-services/4.2.0/google-services-4.2.0.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/google/gms/google-services/4.2.0/google-services-4.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.google.gms:google-services:4.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.2.0/google-services-4.2.0.pom'.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.2.0/google-services-4.2.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

#### Possible fixes
In build.cradle it lists the dependencies:
        
[idea.log](https://github.com/mattermost/mattermost-mobile/files/2943244/idea.log)
classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.2.0'

**Comment by enahum** [comment]
Hi @txnathrt what branch are you trying to build?

**Comment by txnathrt** [comment]
I've tried 2 - master, and 1.16.1

The only difference is the version of missing gradle. Version 1.16.1 is looking for 3.1.4 while the master is trying for 3.3.1. None of which are available at jcenter,bintray.com.

**Comment by enahum** [comment]
gradle 3.3.1 should be available in google() repo and the google-services 4.2 should be available in maven

Can you make sure you have installed the SDK Tools for
* Google Play services
* Android Support Repository, rev 47
* Google Repository (version 58)

**Comment by txnathrt** [comment]
thx, installing them now

**Comment by enahum** [comment]
ok @txnathrt please report back.

**Comment by txnathrt** [comment]
installed google play, the 2 repositories were already there so part of the errors have been resolved

still missing gradle 3.1.4, looking around

**Comment by txnathrt** [comment]
same result on Gradle: 
> Could not resolve com.android.tools.build:gradle:3.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1/gradle-3.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1/gradle-3.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:3.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1/gradle-3.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1/gradle-3.1.pom'.

**Comment by txnathrt** [comment]
![Capture](https://user-images.githubusercontent.com/45575257/54130964-c6016f80-43e7-11e9-8f30-65dd65473698.PNG)

**Comment by amyblais** [comment]
Hi @txnathrt, was this issue resolved or do you need further help here? If you need further help, I recommend posting this issue on our [Mobile apps channel on our community server](https://community.mattermost.com/core/channels/native-mobile-apps) and one of our devs or other community members will be able to help.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
