### ISSUE TITLE
Podfile.lock not in sync

### ISSUE THREAD

**Issue by avm5689** [mattermost/mattermost-mobile#2643]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When compiling using "make build-ios", the following error appears while compiling:

error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

#### Environment Information

- Device Name: MacBook Pro
- OS Version: 10.14
- Mattermost App Version: N/A
- Mattermost Server Version: N/A

#### Steps to reproduce
Advise if you need to see a copy of the code. Nothing has changed except for my personal .env variables.

#### Expected behavior
When compiling using "make build-ios", the following error appears while compiling:

error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

#### Observed behavior
<img width="1142" alt="Screen Shot 2019-03-12 at 6 59 31 PM" src="https://user-images.githubusercontent.com/33432502/54242000-68f5de80-44f9-11e9-87bb-910b4bee94df.png">

#### Possible fixes
Unknown

**Comment by enahum** [comment]
Have you try updating cocoapods to version 1.5.3?

**Comment by amyblais** [comment]
There haven't been updates on this for a while so I'll close this issue for now.

Please re-open this issue if the problem persists,
