### ISSUE TITLE
Text input occasionally lags horribly

### ISSUE THREAD

**Issue by WGH-** [mattermost/mattermost-mobile#2647]
#### Summary
Sometimes, when entering text, the keyboard input lags horribly. There's a large delay between pressing a key and letter appearing. 

The following video illustrates the problem.  Visual keypress indications on the virtual keyboard represents actual touches pretty closely.

https://wgh.torlan.ru/ss/1552574716-yR.mp4

Note that video doesn't over-exaggerate the problem: lags are more or less the same whether I'm running `screenrecord` or not.

#### Environment Information

- Device Name: Redmi Note 4
- OS Version: 7.1.2
- Mattermost App Version: 1.15.2 (Build 170)
- Mattermost Server Version: 5.0.0

#### Steps to reproduce
Not sure about circumstances in which this problem appears. 

I have encountered this problem several times, and it certainly hasn't appeared just in the latest update.

Forcibly stopping the app clears this "condition".

#### Additional info
I have never seen it in any other app on my phone.

I tried watching system log (`adb logcat '*:V'`), but there doesn't seem to be anything particularly useful.

```
03-14 17:40:03.914 10810 10810 I Choreographer: Skipped 232 frames!  The application may be doing too much work on its main thread.
03-14 17:40:04.985 10810 10810 I Choreographer: Skipped 63 frames!  The application may be doing too much work on its main thread.
03-14 17:40:04.985 28905 28905 W RichInputConnection: Slow InputConnection: RELOAD_TEXT_CACHE took 1071 ms.
03-14 17:40:04.985 28905 28905 W InputLogic: Skipping unlearning due to slow InputConnection.
03-14 17:40:05.893 10810 10810 I Choreographer: Skipped 53 frames!  The application may be doing too much work on its main thread.
03-14 17:40:05.893 28905 28926 W RichInputConnection: Slow InputConnection: GET_TEXT_BEFORE_CURSOR took 907 ms.
03-14 17:40:05.918 28905 28905 W InputLogic: Skipping unlearning due to slow InputConnection.
03-14 17:40:05.918 28905 28905 I Choreographer: Skipped 55 frames!  The application may be doing too much work on its main thread.
03-14 17:40:07.136 10810 10810 I Choreographer: Skipped 55 frames!  The application may be doing too much work on its main thread.
03-14 17:40:07.901 28905 28926 W RichInputConnection: Slow InputConnection: GET_TEXT_BEFORE_CURSOR took 1625 ms.
03-14 17:40:08.988 10810 10810 I Choreographer: Skipped 110 frames!  The application may be doing too much work on its main thread.
03-14 17:40:09.923 28905 28926 W InputConnectionWrapper.ICC: Timed out waiting on IInputContextCallback
03-14 17:40:09.923 28905 28926 W RichInputConnection: Slow InputConnection: GET_TEXT_BEFORE_CURSOR took 2001 ms.
03-14 17:40:10.471 28905 28917 I InputConnectionWrapper.ICC: Got out-of-sequence callback 20 (expected 22) in setTextBeforeCursor, ignoring.
03-14 17:40:11.804 28905 28905 W InputConnectionWrapper.ICC: Timed out waiting on IInputContextCallback
03-14 17:40:11.804 28905 28905 W RichInputConnection: Slow InputConnection: RELOAD_TEXT_CACHE took 2000 ms.
03-14 17:40:11.804 28905 28905 E RichInputConnection: Unable to connect to the editor to retrieve text.
03-14 17:40:11.804 28905 28905 W RichInputConnection: Unable to connect to the editor. Setting caps mode without knowing text.
03-14 17:40:11.836 10810 10810 I Choreographer: Skipped 170 frames!  The application may be doing too much work on its main thread.
03-14 17:40:11.924 28905 28926 W InputConnectionWrapper.ICC: Timed out waiting on IInputContextCallback
03-14 17:40:11.924 28905 28926 W RichInputConnection: Slow InputConnection: GET_TEXT_BEFORE_CURSOR took 2000 ms.
03-14 17:40:12.500  2700  3839 W GraphicBufferSource: Dropped back down to Loaded without Executing
```

**Comment by amyblais** [comment]
Hi @WGH- ,

Thank you for the report. We're releasing v1.17 next week, would you be able to test then if the issue continues? If yes, then we'll continue to help investigate as we weren't able to reproduce this previously after a few users reported this some weeks ago.

Also upgrading your server version to the latest (v5.9) might help. You can test on our [community server](https://community.mattermost.com) if you see any difference (it's on the latest server version)

**Comment by enahum** [comment]
This is a react native issue, we are waiting for a fix upstream. https://github.com/facebook/react-native/issues/20119

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
