### ISSUE TITLE
mattermost mobile couldn't not be debugged using react-native-debugger.

### ISSUE THREAD

**Issue by mcuking** [mattermost/mattermost-mobile#2662]
React Native Debugger app version: [0.9.7]
React Native version: [0.58.5]
Platform: [ iOS]
Is real device of platform: [No]
Operating System: [macOS]

when I download the latest version mattermost app code, run npm i && make run-ios, and close the chrome debugger page, use rect-native-debugger to debug it. The button in the picture could not be clicked. And close react-native-debugger, using chrome debugger page, everything is ok.

![image](https://user-images.githubusercontent.com/22924912/54744715-a695ee00-4c02-11e9-97f3-b798419c0c46.png)

**Comment by enahum** [comment]
Thia sounds like a problem of react-native-debugger, have you reported this issue in their repo?

**Comment by mcuking** [comment]
@enahum yes, I don't know where the error is, so I reported this issue in your 2 repo at the same time yesterday.

By the way, do you have plan to create Mattermost mobile app with flutter?

**Comment by enahum** [comment]
@mcuking ok thanks.

We have no plans of building the app with flutter, we’ve taken a look at the technology, one of our members even started to play around with it.

The reality is that it would be a huge effort to start another project with flutter and we are still betting on react native at least for now.

Perhaps what can happen is that someone like you or even a group of people can start developing a Mattermost app with flutter and once it reaches maturity we can look at officially supporting the flutter app (obviously if it ends up being better than the RN one) like we did with the Desktop App.

**Comment by mcuking** [comment]
Thanks for your reply very much, I'll try to create a  flutter app with Mattermost.

**Comment by steedos** [comment]
+1 i can not use debugger too

**Comment by ajdev6** [comment]
+1 i can not use debugger too

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
