### ISSUE TITLE
Unable to create channels with non-Latin names

### ISSUE THREAD

**Issue by EugeneDae** [mattermost/mattermost-mobile#2673]
#### Summary
Name field validation error in the channel creation dialog when using non-Latin characters.

#### Environment Information

- Device Name: iPhone
- OS Version: 12.1.4
- Mattermost App Version: latest
- Mattermost Server Version: 5.9.0

#### Steps to reproduce
1. Tap + to create a new channel.
2. Type non-Latin (e.g. Cyrillic) chars into the channel name field.

#### Expected behavior
It should work.

#### Observed behavior
"Name must be 2 or more lowercase alphanumeric characters".

![screenshot](https://user-images.githubusercontent.com/980835/55025257-a71ef200-5011-11e9-9eb7-731449b78b5b.png)

**Comment by jwilander** [comment]
Hi @EugeneDae, thanks for the report. I have a JIRA ticket for this here https://mattermost.atlassian.net/browse/MM-14498 that I'll be working on shortly
