### ISSUE TITLE
Upgrade pop up doesn't appear

### ISSUE THREAD

**Issue by yakimant** [mattermost/mattermost-mobile#2675]
#### Summary
Upgrade pop up doesn't appear

#### Environment Information

- Device Name: iPhone SE
- OS Version: 12.1.4
- Mattermost App Version: 1.17.0
- Mattermost Server Version: 5.8.0

#### Steps to reproduce

1. Setup EnableMobileClientUpgrade, MobileClientUpgradeAndroidApkLink and MobileClientUpgradeIosIpaLink as described here: https://github.com/mattermost/mattermost-mobile/pull/948#
2. Compile with VERSION_NUMBER lower, than server's AndroidLatestVersion and IosLatestVersion
3. Open app
4. Upgrade screen appears before the login screen.
Tap ""Update later"
5. No pop up appears in messages screens

#### Expected behaviour
Pop up should appear at some moment

**Comment by amyblais** [comment]
Hi @yakimant,

Did this comment help: https://github.com/mattermost/mattermost-mobile/pull/948#issuecomment-477435248?

**Comment by amyblais** [comment]
Hi @yakimant, did the comment from ``csduarte`` in the pull request help or are you still experiencing this issue?

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
