### ISSUE TITLE
[Android] NullPointerException when receiving message

### ISSUE THREAD

**Issue by heapifyman** [mattermost/mattermost-mobile#2684]
#### Summary
Receiving a new message in Android Client causes:

> java.lang.NullPointerException: Attempt to invoke interface method 'void com.wix.reactnativenotifications.core.notification.IPushNotification.onReceived() on a null object reference
at com.wix.reactnativenotifications.gcm.FcmInstanceIdListenerService.onMessageReceived(FcmInstanceIdListenerService.java:29)
at
com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source: 60)
at
com.google.firebase.iid.zzg.run(Unknow Source: 4)
...

#### Environment Information

- Device Name: Fairphone 2
- OS Version: LineageOS for microG
- Mattermost App Version: 1.17.0
- Mattermost Server Version: 5.8.0 (included in gitlab 11.9.1)

#### Steps to reproduce
1. install LineageOS for microG (https://lineage.microg.org/)
1. install YALP Store (https://f-droid.org/de/packages/com.github.yeriomin.yalpstore/)
1. install Mattermost client via YALP
1. login to gitlab mattermost
1. receive direct message

#### Expected behavior
Message should be received correctly. 
Client App should not crash

#### Observed behavior
Client App crashes with above error.
Before the crash I briefly saw the notification "_contact_ is typing..." and then got a glimpse of the message my contact had sent.

I assume the problem is with google play services (or some other google stuff) not being available on my phone? But other messaging apps work fine on my phone, even with push notifications.
My colleagues with "normal" Android phones do not experience this problem.

P.S.: would be great, if you could offer the client on f-droid again

**Comment by amyblais** [comment]
Hi @heapifyman,

Here are more details about the progress on adding support for f-droid: https://github.com/mattermost/mattermost-mobile/issues/566#issuecomment-424379020.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
