### ISSUE TITLE
android app hangs when all the permissions app needs are not allowed

### ISSUE THREAD

**Issue by unistylist** [mattermost/mattermost-mobile#2706]
#### Summary
Android app hangs when all the permissions app needs are not allowed.
When mattermost app starts as a new process is okay but then after switch to other app then switch back to the mattermost app, the app hangs at the splash screen.

I found that this symptom is solved if you go to application setting and give the app all permissions that needs.

I think the app doesn't have a process to check the permission again when it needs and it's not allowed

#### Environment Information

- Device Name: Samsung Galaxy S9+, SM-G965N
- OS Version: Android 9
- Mattermost App Version: 1.17.0
- Mattermost Server Version: 5.7.0-rc2

#### Steps to reproduce
How can we reproduce the issue?
Disable all the permissions that are allowed to the mattermost app. and kill the mattermost app process. launch again and switch to other app and get back to the app.

#### Expected behavior
the app hangs forever

#### Observed behavior
no messages are shown

#### Possible fixes
giving all the permissions that the mattermost app needs will solve the problem

**Comment by amyblais** [comment]
Hi @unistylist,

Would you be open to checking if this also reproduces on v5.9?
Can you help specify what permissions you are referring to?

**Comment by unistylist** [comment]
Storage and Camera
And Floating permission

I think mattermost app doesn't check the status of the permissions and not inform to user about it

**Comment by DHaussermann** [comment]
Hi @unistylist  
I've tested with Android 9 and can't seem to repo this issue. I never get the app to hang on loading regardless of the state of the permissions. I tested on 1.17 and a build of 1.18.

If possible, can you try on the 1.18 beta to see if the issue reproduces?

**Comment by unistylist** [comment]
The thing is this happens randomly. Is there debug mode of this app? I wanna enable debug mode and save the log to check what is happening.

**Comment by DHaussermann** [comment]
You can use the Report a Problem option to send your session details which may containing helpful information.

**Comment by DHaussermann** [comment]
@unistylist 
I just repoed this. I will try and collect more details.  For now I have created https://mattermost.atlassian.net/browse/MM-15079 to investigate further.

**Comment by amyblais** [comment]
Hi @unistylist, the ticket was closed as we haven't been able to reproduce this anymore, are you still experiencing this issue on v1.20?

**Comment by amyblais** [comment]
I'll close this for now as there hasn't been updates on this for a while, but I hope you will re-open this issue with additional relevant information if the problem persists,
