### ISSUE TITLE
android mobile app has stopped at launch_screen

### ISSUE THREAD

**Issue by monkeydbobo** [mattermost/mattermost-mobile#2709]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
android mobile app has stopped at launch_screen

#### Environment Information

- Device Name: Neuxs5
- OS Version: Android7.0
- Mattermost App Version: 1.1.18
- Mattermost Server Version:

#### Steps to reproduce
How can we reproduce the issue?
make run-android
after mattermost-mobile has been installed on my device, launch MainActivity, it has been stopped at launch_screen forever.

**Comment by enahum** [comment]
Anything in the logs? Try using adb logcat and provide more information about the error/problem

**Comment by monkeydbobo** [comment]
BUILD SUCCESSFUL in 39s
450 actionable tasks: 398 executed, 52 up-to-date
Running /Users/wanghaobo/Library/Android/sdk/platform-tools/adb -s 0192b8b408eb4f30 reverse tcp:8081 tcp:8081
Starting the app on 0192b8b408eb4f30 (/Users/wanghaobo/Library/Android/sdk/platform-tools/adb -s 0192b8b408eb4f30 shell am start -n com.mattermost.rnbeta/com.mattermost.rnbeta.MainActivity)...
Starting: Intent { cmp=com.mattermost.rnbeta/.MainActivity }
 DELTA  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)BUILDING MODULES FOR android
 DELTA  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (2200/2200), done.

::ffff:127.0.0.1 - - [15/Apr/2019:11:56:02 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 200 - "-" "okhttp/3.12.1"
::ffff:127.0.0.1 - - [15/Apr/2019:11:56:17 +0000] "POST /symbolicate HTTP/1.1" 200 - "-" "okhttp/3.12.1"

it looks like success， but my device has stopped at launch screen(the mattermost logo), I tried to shake the device, the react-native debug option cannot be called out.

I have seen the following log in Error:
04-17 10:03:15.928 17011-17033/com.mattermost.rnbeta E/FirebaseInstanceId: Google Play services missing or without correct permission.
04-17 10:03:16.522 17011-17065/com.mattermost.rnbeta E/FirebaseInstanceId: Google Play services missing or without correct permission.
04-17 10:03:17.276 17011-17060/com.mattermost.rnbeta E/RNKeychainManager: No entry found for service: 
04-17 10:03:17.475 17011-17061/com.mattermost.rnbeta E/RNKeychainManager: No entry found for service:

**Comment by monkeydbobo** [comment]
E/ReactNativeJS: Error while starting app: Error: No icon defined for tab Entry
04-17 10:25:55.868 22680-22680/com.mattermost.rnbeta E/unknown:ReactNative: Unable to launch redbox because react activity is not available, here is the error that redbox would've displayed: console.error: "Error while starting app: Error: No icon defined for tab Entry"

**Comment by monkeydbobo** [comment]
thanks for your reply, I have solved the problem by setting  icon for tabs.  tab icon must be set on android platform when you use     Navigation.startTabBasedApp.
