### ISSUE TITLE
Weird ios-only SSO cookie bug

### ISSUE THREAD

**Issue by glebtv** [mattermost/mattermost-mobile#2722]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Gitlab SSO does not work on iOS

#### Environment Information

- Device Name: iPhone (any)
- OS Version: 10+
- Mattermost App Version: 1.17, master
- Mattermost Server Version: 5.10.beta

#### Steps to reproduce
Seems to be happening if mattermost is using a top level domain (no www, no subdomains)

#### Expected behavior
Gitlab SSO works

#### Observed behavior
Gitlab SSO shows {"status": "ok"}

#### Possible fixes
I have debugged my problem down to this line:
https://github.com/joeferraro/react-native-cookies/blob/master/ios/RNCookieManagerIOS/RNCookieManagerIOS.m#L137

currentCookie.domain has "mydomain.ru", and topLevelDomain has ".mydomain.ru" with a dot in front.
If I add a dot to currentCookie.domain, like this it starts to work without any problems:
``` 
for(NSHTTPCookie *currentCookie in allCookies) {
    NSString *domainWithDot = [NSString stringWithFormat:@".%@", currentCookie.domain];
    if([currentCookie.domain containsString:topLevelDomain] || [domainWithDot containsString:topLevelDomain]) {
        [cookies setObject:currentCookie.value forKey:currentCookie.name];
    }
}
```

**Comment by enahum** [comment]
Hi @glebtv thanks for the report, that seems to be an issue with the library, have you considered submitting a pull request to the library directly?

**Comment by glebtv** [comment]
There is one already:
https://github.com/joeferraro/react-native-cookies/pull/117

Unfortunately, as per the library's readme it is unmaintained.

If you are willing to use a fork, this fixes it:
```
"react-native-cookies": "github:bamlab/react-native-cookies#ae9b5bbc673f7e7a0adee31fd707fb786dc53b55",
```

**Comment by nlowe** [comment]
A few of our users were seeing this as well. Updating to the latest version available from the app store resolved it for them.

**Comment by arcdigital** [comment]
I'm still having this issue (where it just says status: ok) and I have the latest version of the app (released yesterday).

**Comment by enahum** [comment]
@arcdigital make sure your server url matches the SiteURL in the system console

**Comment by arcdigital** [comment]
It did, couldn't figure out how to fix it so we changed to a subdomain and it works now.

**Comment by glebtv** [comment]
Since the ios part of the cookie library is now pulled into mattermost-mobile for another issue, maybe fix this one there too?

this is a one-line fix, see my first post

**Comment by enahum** [comment]
@glebtv perhaps you could submit a PR for that?
