### ISSUE TITLE
How can I see network activity in the chrome debug mode

### ISSUE THREAD

**Issue by monkeydbobo** [mattermost/mattermost-mobile#2728]
i wanna to debug my mobile-app by chrome, but i can't see the network activity , I have add  'global.GLOBAL.XMLHttpRequest = global.GLOBAL.originalXMLHttpRequest || global.GLOBAL.XMLHttpRequest' in the app.js. How can I see network requests in the chrome debug

**Comment by enahum** [comment]
we are using rn-fetch-blob for the network requests, not sure if there is a way to make them available in the chrome network tab, if you find a way please share back

**Comment by amyblais** [comment]
Closing this for now as there hasn't been activity on this for a while,
