### ISSUE TITLE
Android crash in production mode on master

### ISSUE THREAD

**Issue by glebtv** [mattermost/mattermost-mobile#2729]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Android crashes in production mode build only, on Android.
Branch release-1.19 works fine
Development build works fine

Here is the log:
[crash.log](https://github.com/mattermost/mattermost-mobile/files/3098135/crash.log)

#### Environment Information

- Device Name: Oneplus 5t
- OS Version: 9
- Mattermost App Version: master
- Mattermost Server Version: 5.10

#### Steps to reproduce
env BUILD_FOR_RELEASE=true VARIANT=release make run-android  

#### Expected behavior
No crash

#### Observed behavior
Crash on start

#### Possible fixes
No idea

**Comment by cburn11** [comment]
Starting with https://github.com/mattermost/mattermost-mobile/commit/9c53852128df14e398c4d001de23b9f113069758 my release builds exhibit a similar crash.

**Comment by amyblais** [comment]
@hmhealey ^

**Comment by hmhealey** [comment]
Are either of you running the release builds on a device where the mobile app was previously installed?  If the development build works fine, was it also ran on a device where the app was previously installed, or was that on a clean environment?

That commit changed the structure of some data in the app, and we hadn't addressed the possibility that there might be migration issues yet. If you're seeing issues on devices that have stored data from previous versions, you could try clearing that data and seeing if that fixes it.

**Comment by cburn11** [comment]
I tried on running the crashing build on a device that had just been factory reset, and the same crash occured. I then tried a release build of https://github.com/mattermost/mattermost-mobile/commit/07c2fe40a1105bfa5314e45b66f228e5dac85c17 on that same device and it did not crash.

**Comment by ViktorVovk** [comment]
I have the same issue. test build perfect working but release build crashed after running on a device

**Comment by steedos** [comment]
+1

**Comment by steedos** [comment]
It's caused by recent update of mattermost-redux, rolled back mattermost-redux before this version will working.

https://github.com/mattermost/mattermost-redux/commit/db7995a01308c85c363ccb4b50ed09fa1126ea60
