### ISSUE TITLE
After build app I have infinity loading (splash screen)

### ISSUE THREAD

**Issue by yurastich** [mattermost/mattermost-mobile#2736]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.
After build app I have infinity loading (splash screen)

#### Environment Information

- Device Name: Samsung Galaxy S8
- OS Version: 9.0
- Mattermost App Version:  1.18.0
- Mattermost Server Version: 5.9.0
![2019-04-23 12 23 59](https://user-images.githubusercontent.com/15669093/56569982-b5d1d800-65c2-11e9-8f37-c6d374123156.jpg)

#### Steps to reproduce
How can we reproduce the issue?
git clone...
cd mattermost-mobile
make build-android

#### Expected behavior
Describe your issue in detail.
I give permission, trying in many devices, in virtual device worked all with notification etc

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

**Comment by enahum** [comment]
@yurastich, did you follow the docs found [here](https://developers.mattermost.com/contribute/mobile/build-your-own/) to build the apps?

**Comment by sergeyzhukov** [comment]
@yurastich you forgot to do make start in another tab

**Comment by saxon-y** [comment]
@yurastich I also encountered the same problem. Can you solve it before?

**Comment by amyblais** [comment]
Closing this as there hasn't been feedback for a while from the original reporter. Please re-open this issue if the problem persists.
