### ISSUE TITLE
iPhone doesn't display ephemeral attachment

### ISSUE THREAD

**Issue by scottleedavis** [mattermost/mattermost-mobile#2749]
#### Summary
iPhone doesn't display ephemeral attachment, the iphonex 12.2 emulator does.  Apologies If I am reporting something that is already fixed in the repo, but not yet in appstore.

#### Environment Information

- Device Name: iPhoneX
- OS Version: 12.2
- Mattermost App Version: 1.18.1
- Mattermost Server Version: 5.10.0

#### Steps to reproduce
Running the above device, _not as an emulator_, ephemeral post attachments do not appear.

#### Expected behavior
Ephemeral post attachments appear.

#### Observed behavior
Showing the view from the webapp.
<img width="597" alt="mattermost-webapp-master" src="https://user-images.githubusercontent.com/2914443/56874232-7570c080-69ed-11e9-9b3d-29996a272480.png">

And the view from the emulator
<img width="405" alt="emulator-ephemeral-attachments" src="https://user-images.githubusercontent.com/2914443/56874282-cb456880-69ed-11e9-8c73-4a43848d92b3.png">

The view from my phone shows no ephemeral attachment.
![ios-1 18 1-build 187 - iphonex 12 2](https://user-images.githubusercontent.com/2914443/56874289-d0a2b300-69ed-11e9-9a79-b513a3134364.jpg)

**Comment by enahum** [comment]
Fixed by #2710 and will be available in 1.19.0

**Comment by scottleedavis** [comment]
Thank you much.  :)
