### ISSUE TITLE
Mobile app is not limiting channel name length like the webapp and desktop client

### ISSUE THREAD

**Issue by ewwollesen** [mattermost/mattermost-mobile#2795]
#### Summary
Mobile app is not limiting channel name length like the webapp and desktop client do.

#### Environment Information

- Device Name: Seeing the issue in both Android and iPhone apps
- Mattermost Server Version: 5.9.1

#### Steps to reproduce
Create a channel in new channel in the desktop client or via a browser and it will limit the channel name length to 22 characters. Both iPhone and Android apps did not limit the name length.

#### Expected behavior
I would expect the mobile app and the desktop client/webapp to have the same limitations.

#### Possible fixes
I couldn't figure out where the mobile app code was for creating a new channel (I'm still kind of a newbie), but I found it for the webapp:

This creates new channel in webapp and set the limit - [new_channel_modal.jsx](https://github.com/mattermost/mattermost-webapp/blob/master/components/new_channel_modal/new_channel_modal.jsx)

with this line:
     `maxLength={Constants.MAX_CHANNELNAME_LENGTH}`

and that variable is set [here](https://github.com/mattermost/mattermost-webapp/blob/master/utils/constants.jsx) with this setting:
     `MAX_CHANNELNAME_LENGTH: 22,`

**Comment by amyblais** [comment]
Hi @ewwollesen, letting you know that I've asked our team to look at this.

Would you be open to opening a pull request to fix this?

**Comment by ewwollesen** [comment]
I would, but I'm not experienced/good enough to find where/how in the mobile app code it's creating channels and then how to put in the code to limit it. I found it in the webapp, but I wasn't able to find it here in the mobile app to add the constraint.

**Comment by amyblais** [comment]
Hi @ewwollesen, a fix for this has been submitted for v5.12 with this ticket: https://mattermost.atlassian.net/browse/MM-15310.

**Comment by amyblais** [comment]
I'll close this for now since this has been fixed for 5.12,
