### ISSUE TITLE
trouble running the android app

### ISSUE THREAD

**Issue by saxon-y** [mattermost/mattermost-mobile#2806]
#### Summary
I am having a trouble running the android app.

#### Environment Information

- Device Name: MI 8 Lite
- OS Version: mac 10.11
- Mattermost App Version:1.19.0  
- Mattermost Server Version:no

#### Steps to reproduce
Follow the official documentation step by step in China Net

#### Expected behavior
When the android app is launched, the interface will always freeze on the startup page, and the error shown in the picture will occur when debugging with the real machine.

#### Observed behavior
![1](https://user-images.githubusercontent.com/49136621/57991668-13364780-7ae3-11e9-8b8f-1224991701b1.jpg)
![2](https://user-images.githubusercontent.com/49136621/57991670-1598a180-7ae3-11e9-9b8e-d8d8950b85ab.jpg)

**Comment by enahum** [comment]
@dseawel can this be related to the changes you added?

**Comment by dseawel** [comment]
We reported issues with Android launching on 1.17 but addressed the issues in our own fork. So, no, this couldn’t be related to our changes since they didn’t make it upstream.
