### ISSUE TITLE
Ephemeral interactive buttons don't trigger actions

### ISSUE THREAD

**Issue by scottleedavis** [mattermost/mattermost-mobile#2807]
#### Summary
Ephemeral interactive buttons render but do not trigger ( as they do with the webapp.)

#### Environment Information

- Device Name: IPhonX
- OS Version:  12.2
- Mattermost App Version: 1.19.0
- Mattermost Server Version:  5.11.0

#### Steps to reproduce
1) Install bot test plugin https://github.com/scottleedavis/mattermost-plugin-bot-test/releases/tag/v0.1.5
2) run `/test-button-ephemeral `
3) click the button
4) no action happens.

#### Expected behavior
Steps 1-3 happen, but instead #4 is that `clicked button ephemeral` replaces the ephemeral post as it does in the webapp.

#### Observed behavior
I saw that on my phone, ephemeral buttons on the remindbot plugin did not appear to do anything on 1.19.0.  The same server, they work with the webapp.

**Comment by enahum** [comment]
@scottleedavis there is a ticket for this https://mattermost.atlassian.net/browse/MM-15084
