### ISSUE TITLE
Sliding interface stuck

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#2826]
#### Environment Information
- Device Name: AOSP 9 
- Mattermost App Version: 1.19.0
- Mattermost Server Version: 5.11.0

#### Steps to reproduce
Use the app, slide the left panel with Channels & Messages, at one point the team button will popup (erroneously, see #2593) and after using the app more I'd get stuck. I can't repro at will.

#### Expected behavior
Not get stuck

#### Observed behavior
![layouterrors](https://user-images.githubusercontent.com/2282799/58264209-0036a800-7d6d-11e9-931c-d25122f4c1b9.jpg)

The app is stuck like in the picture, I'll need to FC then reopen, and it might work ok then or start with the teams button visible then get stuck.

Now the numbers:
1 - the team selector should not be shown, or be usable, when this bug is triggered it is shown, not sure if this is related or part of https://github.com/mattermost/mattermost-mobile/issues/2593

2 - while the left slide is shown (and can't be dismissed) on screen every touch is sent to the layer below (no. 4), eg. touch a post will open that post for reply, the post is shown ok

3 - the menu button will trigger the menu, but the right slide popup will slide under the the left side (number 2), touching through 2 will open the correct option from 3 as expected

4 - this layer can be scrolled and receives touches through layer 2 as mentioned above

**Comment by ssolidus** [comment]
Can confirm, It seems that there are no bugs when the hamburger button is used to bring out and put away the menu, but when you slide it out, it seeems to slide out too far or not far enough, and then does not register inputs into the menu until you force it to back to the side.

**Comment by amyblais** [comment]
Hi @licaon-kter, letting you know that we haven't been able to reproduce this so far, but keeping an eye on it,

**Comment by licaon-kter** [comment]
@amyblais I think this needs https://github.com/mattermost/mattermost-mobile/issues/2593 to be triggered, and I guess you didn't test for that (yet?) but just move the issue between teams (https://mattermost.atlassian.net/browse/MM-14697)

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity

**Comment by licaon-kter** [comment]
Looks fixed, I thought this was closed. Thanks
