### ISSUE TITLE
App hangs/freezes when a large number of GIFs is posted.

### ISSUE THREAD

**Issue by MichaelGrupp** [mattermost/mattermost-mobile#2828]
#### Summary

A large amount of animated GIFs posted in a chat room can freeze the mobile app. 

#### Environment Information

- Device Name: Honor 10
- OS Version: Android 9
- Mattermost App Version: 1.19.0
- Mattermost Server Version: 5.10.0

#### Steps to reproduce

Post a large number of animated GIF emojis and open the app. A realistic scenario is shown here:
![parrotmania](https://user-images.githubusercontent.com/8985495/58269329-98418b00-7d87-11e9-93dc-5e5188da45f2.jpg)

Opening this chat room on mobile leads to strong lags, up to a complete freeze.

On the desktop web app, this "only" leads to an increased CPU usage.

#### Expected behavior

The app shouldn't freeze.

#### Observed behavior

* the app lags / freezes
* force quit & restart doesn't solve the problem because the same chat room is loaded again at startup
* workaround 1: clearing the app cache/data manually can fix the restart (if the default room is fine)
* workaround 2: getting pinged in another channel and then opening the notification (i.e., switching rooms before re-opening the app)

#### Possible fixes

~~not posting an excessive amount of GIFs~~ :stuck_out_tongue: 

Maybe limit the amount of simultaneously rendered GIFs, if possible?

**Comment by roman-89** [comment]
Same problem on:

Device Name: Samsung 9 (SM-G960F)
OS Version: Android 9 (One Ui 1.0)
Mattermost App Version: 1.19.0
Mattermost Server Version: 5.10.0

**Comment by mehditlili** [comment]
Also on:
Device Name: Huawei Mate 20 (HMA-L09)
OS Version: Android 9 (EMUI 9.0.0)
Mattermost App Version: 1.19.0
Mattermost Server Version: 5.10.0

Doesn't crash but the phone gets quite laggy an can only recover by switching away from the channel that contains the GIFs.

**Comment by amyblais** [comment]
Hi @MichaelGrupp, we opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-15792.

**Comment by MichaelGrupp** [comment]
Great, thanks!

**Comment by southa** [comment]
Hi @amyblais I don't think your ticket MM-15792 quite captures it.  For me the app hangs, and the only way out is Clear Application Data followed by logging back in and never looking at the problem message again.  Switching away from it is not possible.  Thought I'd mention so that ticket doesn't get filed as a won't fix.

**Comment by enahum** [comment]
This issue has been resolved

**Comment by MichaelGrupp** [comment]
Awesome!! Thanks a lot guys!
