### ISSUE TITLE
[Help Wanted] "Help" menu option should open help link in a mobile browser

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#283]
**Jira Ticket:** https://mattermost.atlassian.net/browse/PLT-5613

**Description:** When clicked on, the "Help" link in the main menu should open the "HelpLink" set in the server's config file in a mobile browser.

**Main Menu Screenshot:**

<img width="300" alt="screenshot 2017-02-21 09 37 37" src="https://cloud.githubusercontent.com/assets/9354841/23169402/a25ae5d2-f819-11e6-9c38-9c0217edec02.png">

**Comment by enahum** [comment]
@lfbrook can you update the specs on this ticket plz

**Comment by enahum** [comment]
@lfbrock can you update this ticket when you have the chance please

**Comment by cpanato** [comment]
@enahum what will be the update?

**Comment by enahum** [comment]
@cpanato there is a scene called `settings` the idea here is to add a new option for **Help** that will be shown only if the HelpLink is set in the configuration that we get from the server and it should open the URL in a browser

**Comment by cpanato** [comment]
@enahum I will talk with you in the pre-release in order to understand more :)

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/mattermost-mobile/pull/524
