### ISSUE TITLE
UWP Support [Universal Windows Platform]

### ISSUE THREAD

**Issue by SamuelEnglard** [mattermost/mattermost-mobile#286]
Using the [React Native plugin for Universal Windows Platform](https://github.com/ReactWindows/react-native-windows) making a UWP version for Windows desktop, mobile, and Xbox should be very easy.

**Comment by Sabartius** [comment]
this should be getting even easier with the new ReactXP-Framework: https://microsoft.github.io/reactxp/

**Comment by SamuelEnglard** [comment]
With the 1.0 release figured I give this a poke 😄

**Comment by enahum** [comment]
Looks to me that they're current RN support is for ver 0.42 we are in ver 0.44 and planing to upgrade soon so I really don't see this as an option perhaps the plugin is, is anyone interesting in building a sample?

**Comment by SamuelEnglard** [comment]
Around the time I first filed this issue I gave it a try and the main issue I had was the SVG library you use didn't support Windows. No idea what's changed since then though

**Comment by enahum** [comment]
Ok this thread has been open for a while without any new updates, I'm going to close it but feel free to re-open at any time if there is some progress with this.

Thanks
