### ISSUE TITLE
Hangs on logout (when disconnected)

### ISSUE THREAD

**Issue by Azero123** [mattermost/mattermost-mobile#2869]
#### Summary
The application waits for a server response on log out even when there is no connection to the server.

#### Environment Information

- Device Name: iPhone
- OS Version: 12.1.4
- Mattermost App Version: 1.19.0
- Mattermost Server Version: commit 9b275586113e77a9e92a50344c51be064a6cd2d8

#### Steps to reproduce

1) Launch a mattermost server, connect to mattermost using the local ip.
2) Logged on the same network.
3) Switch networks or deactivate the server so that the app can not access the server but still has network access. (simply toggling wifi on an iPhone will do.
4) Select the more/ellipsis then select the "Logout" button.

 I hit the more/ellipsis then I selected the "Logout" button. It dismisses the drawer but I remained logged in for some time. I was able to repeat opening the drawer and logging out a few times. Finally it logged me out taking me to the login screen

#### Expected behavior
Immediate log out so that I can now log in to a different server.

#### Observed behavior
I can repeat step 4 over and over before logging out.

**Comment by amyblais** [comment]
Hi @Azero123, what Mattermost server version are you on? Do you see any log errors in "Report a problem"?

**Comment by Azero123** [comment]
Sure thing I was working out of commit 9b275586113e77a9e92a50344c51be064a6cd2d8 @amyblais

**Comment by esbeeb** [comment]
I too experienced a hanging, when I tried to close the Linux desktop Mattermost client, but the server had been ungracefully terminated (as in, I "Paused" the VM where the Mattermost server was running, but clients still had connections open).  It seems as though the clients patiently wait for the server, even though the server can't communicate.
I've installed the latest current version of the Linux desktop client snap: ver 4.4.0
Server version is mattermost-team-5.21.0-linux-amd64.tar.gz

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
