### ISSUE TITLE
Android apk download from play store but deviceId column in Sessions table is empty

### ISSUE THREAD

**Issue by saxon-y** [mattermost/mattermost-mobile#2875]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
The server configured according to the official documentation,version is 5.5,and download apk from play store but deviceid column in sessions table is empty

#### Environment Information

- Device Name: different android device
- OS Version: android
- Mattermost App Version: 1.19.0
- Mattermost Server Version:5.5

#### Steps to reproduce
The deviceid record cannot be found in the database after normal login.
#### Expected behavior
Describe your issue in detail.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
Hi @saxon-y, would you be open to upgrading your server version to the latest (v5.11) to see if that fixes the issue? If not, can you help with more details on your Android version?

**Comment by saxon-y** [comment]
> Hi @saxon-y, would you be open to upgrading your server version to the latest (v5.11) to see if that fixes the issue? If not, can you help with more details on your Android version

**Comment by saxon-y** [comment]
Thanks for your reply,I have upgraded the server to latest version according to your suggestion,but the problem still exists.
And I have logged in to an account on a different android device(MI 8 Lite、M971Q), and I have not found the device_id in the database, but the strange thing is that the ios device is ok.
![image](https://user-images.githubusercontent.com/49136621/59323232-5ebbca00-8d0c-11e9-8c51-fd9edde66b53.png)

**Comment by saxon-y** [comment]
> Hi @saxon-y, would you be open to upgrading your server version to the latest (v5.11) to see if that fixes the issue? If not, can you help with more details on your Android version?

Thanks for your reply,I have upgraded the server to latest version according to your suggestion,but the problem still exists.
And I have logged in to an account on a different android device(MI 8 Lite、M971Q), and I have not found the device_id in the database, but the strange thing is that the ios device is ok.
![image](https://user-images.githubusercontent.com/49136621/59323258-90349580-8d0c-11e9-8004-0e75dc9ec6ec.png)

**Comment by saxon-y** [comment]
@amyblais Thanks for your reply,I have upgraded the server to latest version according to your suggestion,but the problem still exists.
And I have logged in to an account on a different android device(MI 8 Lite、M971Q), and I have not found the device_id in the database, but the strange thing is that the ios device is ok.
![image](https://user-images.githubusercontent.com/49136621/59323383-0a651a00-8d0d-11e9-8cca-1bb312c939e6.png)

**Comment by amyblais** [comment]
Hi @saxon-y, wondering if this earlier thread might help: https://github.com/mattermost/mattermost-mobile/issues/1687. If not, I'll ask our devs about this.

**Comment by saxon-y** [comment]
@amyblais Thanks for your reply, I hope to find the answer from the link.

**Comment by saxon-y** [comment]
Hi @amyblais ,I want to use my own push service, but I don't know where I should start from.

**Comment by amyblais** [comment]
Hi @saxon-y, you can find more information on our docs here:

- https://docs.mattermost.com/mobile/mobile-faq.html#how-do-push-notifications-work
- https://docs.mattermost.com/mobile/mobile-faq.html#what-are-my-options-for-securing-push-notifications

**Comment by saxon-y** [comment]
@amyblais Thanks for your reply. The links refers to the documentation of your official push service built by GCM. I want to build a push service myself, but I don't know how to integrate it into the mattermost. I hope you can give me some advice. I will really appreciate

**Comment by amyblais** [comment]
Hi @saxon-y, let me know if these docs might help:
 - https://docs.mattermost.com/mobile/mobile-compile-yourself.html
 - https://docs.mattermost.com/mobile/mobile-overview.html

**Comment by saxon-y** [comment]
Thanks for your reply, I have already read your documentation, but there seems to be no content about the push service I built. I feel that I urgently need a developer to help me solve the problem, but I don't know how to contact developer. I think you should be able to help me, I will really appreciate.

**Comment by saxon-y** [comment]
@amyblais ,thanks for your reply, I have already read your documentation, but there seems to be no content about the push service I built. I feel that I urgently need a developer to help me solve the problem, but I don't know how to contact developer. I think you should be able to help me, I will really appreciate.

**Comment by enahum** [comment]
@saxon-y just out of curiosity why do you need to build your own push notification service? and why this one https://github.com/mattermost/mattermost-push-proxy is not enough?

**Comment by saxon-y** [comment]
@enahum Most mobile devices in China cannot visit google, so GCM is unstable.I am very helpless to push notification service through Firebase.Can you give me some valuable advice?I will really appreciate.

**Comment by amyblais** [comment]
Hi @saxon-y, here is a link to a F-Droid project that some members of our community have forked, which does not rely on Google Play for notifications: https://github.com/mattermost/mattermost-mobile/issues/566. Would this be something you are able to consider?

**Comment by enahum** [comment]
@saxon-y these are the facts:
* The app in the Android Play Store uses firebase to receive push notifications
* The current push proxy server connects to firebase to send the push notifications
* The mattermost server sends a payload to the push proxy with the notification to be sent.

I believe that you'll need to make changes in the mobile app and the push proxy to use something else other than Firebase and probably the mattermost server. The reality is that I don't know of anything else that could work here but if you know any other solution we are definitely willing to have your work included it in the product if its proven to be reliable.

changes to the mobile app:
* get a device token to be able to send notifications to the device (currently you are getting the deviceId as null as this is provided by firebase)
* add a prefix alongside the device token so that the mattermost server knows this is a native mobile android session and the push proxy to know what service to use to send the notification to.

changes to the server/webapp
* make the changes to the sessions so it captures the mobile session as a natives app session.

changes to the push proxy:
* determine based on the prefix if the notification needs to be sent to firebase or the alternative that you will be adding
* send the notification

I hope this makes it a bit more clear.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
