### ISSUE TITLE
Cannot launch iOS app

### ISSUE THREAD

**Issue by jinaoh** [mattermost/mattermost-mobile#2886]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Cannot launch iOS app

#### Environment Information

- Device Name: iPhoneX
- OS Version: 12.3.1
- Mattermost App Version: 1.19.0
- Mattermost Server Version:5.11.0

#### Steps to reproduce
Launch the app

#### Expected behavior
App works.

#### Observed behavior
The app is forced to quit after showing the splash screen. 
Reinstalling the app will run normally.

**Comment by amyblais** [comment]
Hi @jinaoh, what do you see happen before you are forced to quit the app? Do you see any errors in the "Report a Problem" when you see this issue?

**Comment by jinaoh** [comment]
The app was forced to end after only the Mattermost splash screen was displayed.

**Comment by amyblais** [comment]
@jinaoh, are you able to reproduce this also on v1.20 version? Do you see any errors in the "Report a Problem" when this issue occurs?

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
