### ISSUE TITLE
Sometimes not all posts are displayed in threadview.

### ISSUE THREAD

**Issue by somenet** [mattermost/mattermost-mobile#2905]
#### Summary
Sometimes the threadview in the mobile app wont display all posts in a thread and closing threadview is required to read those posts.

#### Environment Information
- Device Name: N/A
- OS Version: Android Pie
- Mattermost App Version: 1.20.0
- Mattermost Server Version: 5.12

#### Steps to reproduce
Heisenbug. It doesnt happen allways, but it happened a few times now.

#### Expected behavior
Like in previous versions display all posts in the opened thread and not just very few. (2-3)

#### Observed behavior
most posts were missing from the opened thread.

Android app threadview content
![PhotoEditor_20190620_190907701](https://user-images.githubusercontent.com/5354356/59867750-52301500-938f-11e9-967f-e4b107eed9e1.jpg)

threadview on same device but in Webbrowser.
![PhotoEditor_20190620_192550109](https://user-images.githubusercontent.com/5354356/59868460-3ded1780-9391-11e9-9929-9e8fb4349ad3.jpg)

The red-circled post is the same one in both Screenshots. The threadview only shows my two posts, while the channelview which was blurred beyond readability shows that there are more posts in that thread. There are also more posts in that thread by me.
Sometimes it shows other's posts and none is mine.

This started happening since I updated the app from 1.19.x.

**Comment by enahum** [comment]
@somenet thanks for the report, we are cutting a dot release to be deployed really soon that will take care of this issue.

probably in a day or two

**Comment by amyblais** [comment]
Closing as this has been fixed in the dot release,

**Comment by somenet** [comment]
This is again an issue in 1.21.2 (215) and server 5.13.2.

now only the first and last message of a thread gets displayed in the threadview.
