### ISSUE TITLE
Channellist sorted inconsistently.

### ISSUE THREAD

**Issue by somenet** [mattermost/mattermost-mobile#2906]
#### Summary
Since the update to 1.20.0 the channel list is sorted inconsistently to the webapp, which causes confusion.

#### Environment Information
- OS Version: Android Pie
- Mattermost App Version: 1.20.0
- Mattermost Server Version: 5.12.0

#### Steps to reproduce
Create Channels named
+ ``~Test``
+ ``Test2``
+ ``#Test3``
+ ``(T)est4``

#### Expected behavior
Channels to be sorted in webapp the same as in the android app.
  + android app sorting behavior changed with the 1.20.0 update.

#### Observed behavior
Watch inconsistent sort of channels.

Android App
![image-0c2f76ed-44db-481c-8dd9-93e16372e983](https://user-images.githubusercontent.com/5354356/59871235-56603080-9397-11e9-86aa-f618902abd42.jpg)

Webapp
![screen-2019-06-20--20-00-52](https://user-images.githubusercontent.com/5354356/59871009-d89c2500-9396-11e9-8736-18b7adde0a06.png)

**Comment by amyblais** [comment]
Ticket here: https://mattermost.atlassian.net/browse/MM-16532.

**Comment by enahum** [comment]
Fixed by https://github.com/mattermost/mattermost-mobile/pull/2931
