### ISSUE TITLE
[Android] Push notifications not working

### ISSUE THREAD

**Issue by carlocanlas** [mattermost/mattermost-mobile#2921]
#### Summary
Unable to receive any type of push notification in Android App.

#### Environment Information
- Device Name: Nokia 7 Plus
- OS Version: Android 9 Pie
- Mattermost App Version: 1.20.1
- Mattermost Server Version: 4.10.0

#### Expected behavior
Expecting to receive push notifications

#### Observed behavior
No push notifications are reaching the device, regardless id using mobile data or wifi connection

**Comment by amyblais** [comment]
Hi @carlocanlas, would you be open to posting your push notification settings as well as take a look at our troubleshooting doc: https://docs.mattermost.com/mobile/mobile-troubleshoot-notifications.html?

**Comment by amyblais** [comment]
We haven't received feedback for a while so I'll close this issue for now. Please re-open this issue with additional information if the issue persists.

**Comment by divined** [comment]
The same:
But -> Under System Console > General > Logging > File Log Level 
I don't see any System console in my android APP. Please do screenshots for the process.

**Comment by divined** [comment]
I am not android developer. I am user with MM client. I don't have android notifications. When i click send test notification nothing happens.

**Comment by amyblais** [comment]
@divined The logs are normally are accessed via webapp/desktop. If you don't have access to the System Console you can ask your system admin to check the logs. I'd also recommend checking the push notification settings in System Console: https://docs.mattermost.com/administration/config-settings.html#push-notification-server.

**Comment by divined** [comment]
But notifications work well on desktop. It doesn't work on the mobile app only |(

**Comment by e-stonia** [comment]
I have the same issue. I'm sure it's not an issue with system console as on one latest updated MatterMost Android app on Android 9 push notifications work but on my other Android 9 also latest updated MatterMost app it doesn't work.

**Comment by dpanic** [comment]
I had same problem on Android 9 only! On Android 10 it worked well.

After debugging here is what I found:
- User set server url as http:// instead of https:// (even http->https redirection is enabled) 
- Push notifications are not set on Android 9

#### Regular user which had no issues:
> | qh7gtm1p9tgqbfdh8zb91zgndc | 4utmo1urobn77dz8m1umw9dith | 1594580801425 | 1613200241929 |  1610608244890 | k65dtitjgtfgbpcn6gyd1w5eke | **android_rn:fuD2JqWfxpE:APA91bH8KoBz-FEQmOPEmLCCzCCLILPghR6sU9hRh6lIAJEsGW8qwWKi[REDACTED]** | system_user |       0 | {"browser":"Chrome/83.0.4103","csrf":"hj8wpmxqtffa3kchx65u48wpqc","is_guest":"false","os":"Android","platform":"Linux"}                                                               |             0 |

User with issues, had no DeviceId set...
 
#### User with issues:
>  18p9e3q117r18eq4j4ewg3nomc | zddarwts7jb59k89w7iazz6ubo | 1609923090599 | 1613197563410 |  161
> 0608143418 | 3efsntwgi7r4tppq4ern5gn16y |          | system_user |       0 | {"browser":"Chrome/87.0.4280","csrf":"z7bjhipe5igxf8w53zhwno7gbo","isMobile":"false","isOAuthUser":"false","isSaml"
> :"false","is_guest":"false","os":"Android","platform":"Linux"}  
> 

**_Result: simple server url set to exact one, one without url redirections_**

![Screenshot from 2021-01-15 08-57-06](https://user-images.githubusercontent.com/346557/104700192-13ea0b80-5714-11eb-88a4-ae3faf1c5df5.png)

**Comment by enahum** [comment]
Can you guys please upgrade to 1.39 and report back? Thanks

**Comment by dpanic** [comment]
> Can you guys please upgrade to 1.39 and report back? Thanks

It was version 1.38.1
On version 1.39 it works...I can ask from my team people to check if this http->https thing is related to version if you want

**Comment by enahum** [comment]
@dpanic not really related as it will follow the redirection.

We did have a race condition to set the deviceId which resulted at times to be missed and got fixed in 1.39

**Comment by dpanic** [comment]
> @dpanic not really related as it will follow the redirection.
> 
> We did have a race condition to set the deviceId which resulted at times to be missed and got fixed in 1.39

That makes sense. Thank you.
I made mistake than by not checking this byself, by letting users to notify me :-)
