### ISSUE TITLE
Migrate to androidx

### ISSUE THREAD

**Issue by viralS-tuanlv** [mattermost/mattermost-mobile#2937]
Please migrate to androidx and update new version. Thanks

**Comment by enahum** [comment]
@viraS-tuanlv Migrating to androidx in our case requieres React Native upgrade to 0.60 that hasn’t yet been released as well as any other dependency of the project, but I’m very interested in understanding why you would want us to migrate?

**Comment by viralS-tuanlv** [comment]
> @viraS-tuanlv Migrating to androidx in our case requieres React Native upgrade to 0.60 that hasn’t yet been released as well as any other dependency of the project, but I’m very interested in understanding why you would want us to migrate?

I cloned this project for 1 month ago, and it work fine, until today i build it and fail for androidx, and then i clone this project again at version 1.20.0 and run again it fine. So i want to know how do you fix this? other projects i have to migrate to androidx to run it.

**Comment by enahum** [comment]
Oh we saw this at some point cause react-native-device-info had a google dependency that wasn’t locked to a fix version, and that caused it to requiere androidx. Once we updated the dependency they did lock the version and so androidx is no longer required.

Does that answer your question?

**Comment by viralS-tuanlv** [comment]
oh thanks, i see

**Comment by glunardi** [comment]
Ran into something similar (I presume). On my system, react-native updated itself to version ` "0.60.5" ` which suggests it is now released [1].

And right now, the build fails because of this:
 `mattermost-mobile/node_modules/@react-native-community/netinfo/android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java:12: error: package android.support.v4.net does not exist`

Could it be related and would you have a suggestion to fix the build environment?


[1] https://github.com/facebook/react-native/releases/tag/v0.60.0

**Comment by glunardi** [comment]
> Ran into something similar (I presume). On my system, react-native updated itself to version `"0.60.5"` which suggests it is now released [1].
 
> Could it be related and would you have a suggestion to fix the build environment?
After spending a few seconds on this myself, I realize it is kind of a silly question, I just forced a different version number in your package.json file and it picked that up. It just moved the issue to another compatibility problem (not building/finding mattermost-redux).

**Comment by glunardi** [comment]
Quick update here (for myself mostly): with the master branch, I can run ```make run-android``` vanilla and with my little patches and it works fine (served up using metro), including proxy push-notification.

But when I try to ```make build-android``` it fails with mattermost-redux package not found errors and then even ```make run-android``` fails after that.

Does that ring a bell with anyone please?

**Comment by enahum** [comment]
Nom is not running the prepare script of mm-redux you could do `cd node_modules/mattermost-redux && npm i`

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
