### ISSUE TITLE
Documentation and examples are out of sync - again

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-mobile#2938]
https://github.com/mattermost/mattermost-mobile/blob/master/fastlane/env_vars_example and https://developers.mattermost.com/contribute/mobile/build-your-own/environment-vars/ are out of sync, yet again - `NOTIFICATION_SERVICE_IDENTIFIER` this time.

There is a previously reported issue with the same theme at https://github.com/mattermost/mattermost-mobile/issues/2401

The two items were brought in sync when that issue was filed, but here we are, with the same problem.

I propose two solutions -

1. Just get rid of `fastlane/env_vars_example` all together so that no one has to update anything.
1. Keep `fastlane/env_vars_example` in sync with https://developers.mattermost.com/contribute/mobile/build-your-own/environment-vars/ so that people can build custom mobile apps without banging their heads against a wall with each release.

While the first solution eliminates the problem, the second one solves it.

**Comment by enahum** [comment]
@harshilsharma63 would you like to submit a PR?

**Comment by harshilsharma63** [comment]
@enahum I can, but the problem here is not the out-of-sync state at present but rather the multiple occasions when this has happened. Can we expect the two items to stay in sync starting next release?

**Comment by enahum** [comment]
The PR can be to remove the sample var and just follow the documentation. Is very easy to forget about the sample vars and imo is just that “a sample”.
