### ISSUE TITLE
New messages are often covered behind keyboard or text field 

### ISSUE THREAD

**Issue by nils-tekampe** [mattermost/mattermost-mobile#2940]
![IMG_0006](https://user-images.githubusercontent.com/10251788/60367693-2cd68300-99ef-11e9-88ee-65ef7297b980.jpeg)

Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
If I get a new message under iOS and open the app or switch to the channel, the message is often covered by the text field for answering.

#### Environment Information

- Device Name: iPad Pro 11 (also happens on my IPhone XS)
- OS Version: 12.3.1
- Mattermost App Version: 1.20.1
- Mattermost Server Version: 5.4.0

#### Steps to reproduce
Receive a new message while app is not open or while being in a different channel. Switch to app and channel to read message. Happens very often but not always. 

#### Expected behavior
I would like to see the message please 

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
Hi @nils-tekampe, we opened a PR for this here: https://github.com/mattermost/mattermost-mobile/pull/2943.

**Comment by nils-tekampe** [comment]
Good to know. Thanks!

**Comment by amyblais** [comment]
Closing as this was fixed for upcoming v1.21 release,

**Comment by bbodenmiller** [comment]
@amyblais still seeing this issue in 1.21 app release.

**Comment by amyblais** [comment]
Hi @bbodenmiller, there is a new PR open here: https://github.com/mattermost/mattermost-mobile/pull/3074.
