### ISSUE TITLE
Mattermost iOS client keeps message counter though no unread messages exist 

### ISSUE THREAD

**Issue by nils-tekampe** [mattermost/mattermost-mobile#2944]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Under iOS (iPad and iPhone) the Mattermost app keeps showing a message counter on the home screen even though there are no unread messages left.

#### Environment Information

- Device Name: iPad Pro 11
- OS Version: 12.3.1
- Mattermost App Version: 1.20.1
- Mattermost Server Version: 5.4.0

#### Steps to reproduce
See above 

#### Expected behavior
Message counter should disappear if no unread messages left

**Comment by amyblais** [comment]
@nils-tekampe This issue was fixed in server v5.7.0, so I recommend upgrading your server.

**Comment by hotlong** [comment]
Sometimes the push message may missed due to network problems, If the mobile app update badge number before hide, the badge will be more accurate

**Comment by nils-tekampe** [comment]
Updating the server seems to have solved the issue. My bad.
Thanks for your support!
