### ISSUE TITLE
iOS app is not launched

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#2950]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
After installing a new iOS app, I can not proceed with the app after push agreement

#### Environment Information

Device Name: iPhoneXR
OS Version: iOS 12.3.1
Mattermost App Version: 1.20.1
Mattermost Server Version:.5.7

#### Steps to reproduce
Delete the mattermost-mobile app
And install a new version

#### Expected behavior
After installing a new iOS app, I can not proceed with the app after push agreement.
The expected normal behavior should go to the screen to enter the server address.

#### Observed behavior
loading image shown only.
![die-no-launched](https://user-images.githubusercontent.com/42505950/60634020-3ecd8100-9e48-11e9-899e-ca389f9d6d78.gif)

#### Possible fixes
might be socket issue? socket hang up?

**Comment by aniac0105** [comment]
Me too.
Is there a solution?

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
