### ISSUE TITLE
RN App: Convert string refs to use callbacks

### ISSUE THREAD

**Issue by axemclion** [mattermost/mattermost-mobile#2958]
## Summary
String refs are deprecated, so need to move to callbacks or `React.createRef()`. May be needed when upgrading to RN version 0.60

#### Environment Information
N/A

#### Steps to reproduce
Upgrade to RN 0.60, see that ref errors show up. 

#### Expected behavior
No errors show up when app is upgraded to 0.60

#### Observed behavior
Redbox errors with RN 0.60 when string refs are used. 

#### Possible fixes
Use callbacks or  `React.createRef()` instead of strings.

**Comment by jasonblais** [comment]
Thanks @axemclion for submitting a PR for this :) https://github.com/mattermost/mattermost-mobile/pull/2959

**Comment by jasonblais** [comment]
As noted in the PR by Miguel, we're tracking changes via this ticket: https://mattermost.atlassian.net/browse/MM-17142

**Comment by enahum** [comment]
Fixed by #3217
