### ISSUE TITLE
UI error when iOS adjust to bigger text size

### ISSUE THREAD

**Issue by hotlong** [mattermost/mattermost-mobile#2971]
#### Environment Information

- Device Name: iPhone X
- OS Version: 12.3.1
- Mattermost App Version: 1.20.2
- Mattermost Server Version: 5.12.0

#### Steps to reproduce
How can we reproduce the issue?
- Settings -> Display & Brightness -> Text Size
- Select the biggest text size

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

Menu text should vertical-align to center 

![image](https://user-images.githubusercontent.com/50353452/61026963-7cea1800-a3e7-11e9-86cb-4d5ab62421f8.png)

![image](https://user-images.githubusercontent.com/50353452/61026981-896e7080-a3e7-11e9-8569-162c1e367864.png)

**Comment by amyblais** [comment]
Hi @hotlong, a fix for this will go in for v1.21 release.

**Comment by jasonblais** [comment]
v1.21 release is now live and available from the app store. If you're still experiencing issues on v1.21, please let us know!
