### ISSUE TITLE
[Android]Badge never clear by click notification directly

### ISSUE THREAD

**Issue by tgly307** [mattermost/mattermost-mobile#2978]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Open mattermost app by clicking notification in mobile notification bar directly will never clear the badge on app until next notification arrive.

#### Environment Information

- Device Name: HUAWEI MATE 20 pro
- OS Version: Android 9.0
- Mattermost App Version: 1.20.2(build 204)
- Mattermost Server Version: 5.12.4

#### Steps to reproduce

1. Make a notification with badge, for example from bot user or other user.
2. Click the notification message in mobile notification bar to open the specific channel in app directly.
3. Read the message on app side, ensure there is no unread message.
4. Then go back to mobile home page, the badge on app still exist.

#### Expected behavior
The badge should be clear.

#### Observed behavior
The badge still exists.

#### Possible fixes
Maybe the server should send a signal or something to app in this situation to clear badge, just like open app by click app icon & read message.

**Comment by hotlong** [comment]
I think it should be better if mobile app use some script to updates badge when opened yes, there is a badge count in redux store, not depending on the remote push message.

**Comment by jasonblais** [comment]
Hey @tgly307 @hotlong does this reproduce consistently for you? Do you belong to one or multiple teams in your Mattermost server?

**Comment by tgly307** [comment]
@jasonblais hi, there is only one team in my sever and I belong to it. I can reproduce this issue in the latest version app(1.21.1).

**Comment by enahum** [comment]
can you please share what launcher are you guys using?

**Comment by tgly307** [comment]
@enahum hi, I don't know the meaning of launcher you point.

**Comment by DHaussermann** [comment]
Hi @tgly307,
I'm curious if your still seeing this issue.  

I believe for your version of Android, that you should be able to verify what launcher you're using by going to _Settings >> Apps>> Default Apps>> Launcher_  

If you have not changed your launcher, it should say `Huawei Home` 
Let me know if this helps.

**Comment by tgly307** [comment]
@DHaussermann thx, I have check my settings.
@enahum hi, I checked my settings, it is default, `Huawei Home`.

**Comment by lindy65** [comment]
Hi @tgly307 

I tried to reproduce your issue on Huawei P30 Pro, Android 9 using Launcher "Drawer Home" (I have not changed this setting - it is the default I found when going to the setting) but am not able to reproduce. 

The notification dot on the Mattermost App icon clears once I have tapped on the notification in the notification bar.  I tested on server v5.15 release branch, mobile app v1.22 build 221.

I'm wondering whether updating to the latest server and mobile versions will resolve your issue?

There is a Jira ticket to address notifications on the app badge sometimes getting out of sync [here](https://mattermost.atlassian.net/browse/MM-17110) - not sure whether this might be what you're seeing?

**Comment by tgly307** [comment]
HI, @lindy65 , thx for your test. My server is v5.14 and app version is v1.22. This issue is still exist. The laucher and other system settings of my phone are all default. I make some gif to show my issue.
![2](https://user-images.githubusercontent.com/25153311/63423251-731fef80-c43e-11e9-91ea-4fb32473eca4.gif)
![1](https://user-images.githubusercontent.com/25153311/63422937-e37a4100-c43d-11e9-84ea-16abc543c4dd.gif)

**Comment by lindy65** [comment]
Thanks @tgly307 - I wasn't sure whether you had updated to the latest server/app versions as your original report stated

> Mattermost App Version: 1.20.2(build 204)
Mattermost Server Version: 5.12.4

The notification icon on the Mattermost app badge disappears almost immediately for me once I've viewed the message from the push notification.  Does the badge on your app icon not disappear at all or have you perhaps waited a little while to see if it disappears?

**Comment by tgly307** [comment]
Hi @lindy65 .
When I recieve message from other user, the badge (the number of unread message) will appear on app icon when the push notification arrives, and I click the notification to open the app from notification bar, the badge will not disappear at all whether the message is read or unread, even after I click the app icon to open the app,it still there ( just like second gif in my last reply ). The badge will exists until another notification arrive.

**Comment by lindy65** [comment]
Hi @tgly307 

Thanks for the feedback and steps showing how you can get the badge on the app icon to disappear. I'm sorry, but I am not able to reproduce your issue.

I'm wondering whether it is a Launcher issue...  I do not have any other options to change my Launcher to. I only have "Drawer Home" available to choose.  Do you have any other Launcher options available to choose from?

**Comment by tgly307** [comment]
@lindy65 Thanks for reply. I only have one option too. The system of Huawei P30 Pro should be same with Huawei mate 20 pro, the newest version is EMUI 9.1. I don't have any other Android 9 phone so I can't test this issue on other device. Maybe the system is different between phones in different areas?
It is so weird.

**Comment by lindy65** [comment]
Hi @tgly307 - yeah, it is really weird. I'm so sorry I can't help any further. Perhaps other people with a Huawei Mate 20 Pro can try to reproduce your issue and see what they find...

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
