### ISSUE TITLE
Syntax highlight not working

### ISSUE THREAD

**Issue by andrey-yantsen** [mattermost/mattermost-mobile#3007]
#### Summary

Code-blocks with defined syntax aren't highlighted on iOS app.

#### Environment Information

- Device Name: iPhone (issues exists on Android as well, checked on Samsung galaxy s8)
- OS Version: 12.1
- Mattermost App Version: 1.21
- Mattermost Server Version: 5.12

#### Steps to reproduce

Send message containing syntax highlight, e.g.

````
```php
$a = 'a';
```
````

#### Expected behavior

The syntax highlighted the same way as in webapp.

#### Observed behavior

The block displayed without any highlight.

**Comment by enahum** [comment]
@andrey-yantsen the syntax highlight feature was never implemented in the mobile app, would you like to work on it and submit a PR? We love contributions like this one ;)

**Comment by andrey-yantsen** [comment]
Uh... I'm not really good with React :) But I'll ask my colleagues whether anybody is interested.

**Comment by enahum** [comment]
Sounds good @andrey-yantsen thanks

**Comment by saturninoabril** [comment]
Thanks @cardoso for your contribution!
