### ISSUE TITLE
message timestamps displayed as utc0 when phone is set to gmt+7

### ISSUE THREAD

**Issue by jplemaire** [mattermost/mattermost-mobile#3049]
#### Summary
When phone is set to gmt+7 the message timestamps appears to be displayed as UTC (gmt+0), if we use other timezones such as gmt+8 or utc -4, the timestamps is properly displaying local time again.
Seems similar/related to an old issue: https://github.com/mattermost/mattermost-mobile/issues/1935

#### Environment Information

- Device Name: google pixel 3
- OS Version: android 9
- Mattermost App Version: 1.21.1
- Mattermost Server Version: 5.11
###
- Device Name: google pixel 1
- OS Version: android 9
- Mattermost App Version: 1.21.1
- Mattermost Server Version: 5.11
###
- Device Name: nokia 5
- OS Version: unknown atm
- Mattermost App Version: 1.21.1
- Mattermost Server Version: 5.11

#### Steps to reproduce
set timezone to gmt+7, reload application, check message timestamps, they will display as gmt0

#### Expected behavior
message timestamps should be displayed as gmt+7

#### Observed behavior
message timestamps appears as utc/gmt0

#### Possible fixes
Seems similar/related to an old issue: https://github.com/mattermost/mattermost-mobile/issues/1935

**Comment by amyblais** [comment]
Hi @jplemaire,

1. Are you by any chance currently traveling and the timezone didn't get changed correctly?
2. Does the server have the Experimental Time Zone flag enabled?

**Comment by jplemaire** [comment]
> Hi @jplemaire,
> 
>     1. Are you by any chance currently traveling and the timezone didn't get changed correctly?
Negative, the issue was sent to us by one of our user living remotely, we tested from gmt-4 timezone, changed manually our mobile timezone reference, restarted mattermost and application timestamps display as UTC.
If we manually set anything like like gmt+8, timestamps is properly displayed as gmt+8, this only seems to affect gmt+7.
>     2. Does the server have the Experimental Time Zone flag enabled?
Timezone in advanced/experimental is set to false. 

As such, only gmt+7 is impacted to our initial check, no issues with gmt+8, gmt+9, gmt-4, gmt-5, utc (timezone manually tested without changing any configuration server side).

**Comment by amyblais** [comment]
Hi @jplemaire, if you turn the timezone setting to true, do you see anything different?

**Comment by jplemaire** [comment]
Hi @amyblais 

> Hi @jplemaire, if you turn the timezone setting to true, do you see anything different?

No changes with the settings enabled and leaving the app mobile client timezone as "set automatically".

I enabled the Timezone experimental option to true, cleared app cache, set timezone to gmt+7, local time is currently 5:34 on phone and timestamp in application shows as 10:32.

If however I manually force it in the application to gmt+7 while disabling mobile application automatic timezone, the time shows correctly, this could provide a temporary workaround to enduser but as we have various users travelling and all timezone seems fine except gmt+7, is there any possibility to get this looked into in order to keep the set automatically option?

**Comment by jasonblais** [comment]
Hi @jplemaire, just letting you know that @amyblais is out of office this week but will get back to you afterwards, or escalate to dev team as needed.

**Comment by shawn111** [comment]
@jasonblais 

We have similar issue.

Server timezone: UTC+8 (CST)
Server: 5.2.0  (Build 5.2.1)

mattermost-mobile ios: 1.21.1 (Build210), good
mattermost-mobile android: 1.21.1 (Build210), bad, timezone show as UTC-6 (CST)
mattermost-mobile classic android: good

**Comment by enahum** [comment]
Have you checked the user settings for the Timezone? does the server has the timezone setting set?

**Comment by andreasarifin** [comment]
I have similar issue. I am using latest mattermost mobile app. My OS is Android 9, Pixel 3XL. Timezone setting in my phone is set to Western Indonesian Time (UTC+7). Changing to Japan time show the correct time.

**Comment by colorchestra** [comment]
Same here. The iOS app shows timestamp in UTC, the web client correctly shows CEST.

Client: iOS 12.3.1, Mattermost 1.21.1. Timezone set to CEST (UTC+2)
Server: Debian Stretch, Mattermost 5.13.0 Timezone also set to CEST (UTC+2).

**Comment by Riccorbypro** [comment]
Having a similar issue on my Xperia Z3 (Android 9.0, CarbonROM). Phone is set to UTC+2 (South African Standard Time) but all timestamps are displayed in UTC. 
Using Mattermost 1.21.2, Server is Mattermost 5.12.4

**Comment by amyblais** [comment]
Hi all, what is your Timezone setting set to in Mattermost > Account Settings > Display > Timezone?

Do you have this setting enabled on your server https://docs.mattermost.com/administration/config-settings.html#timezone?

**Comment by colorchestra** [comment]
Hi, on my Mattermost 5.13.0 installation I can't find a Timezone setting in Account Settings > Display... should it be there?

The `ExperimentalTimezone` feature is disabled.

**Comment by amyblais** [comment]
Hi @colorchestra, this setting should be enabled to see the Timezone setting in Account Settings: https://docs.mattermost.com/administration/config-settings.html#timezone.

**Comment by colorchestra** [comment]
Is this for debugging purposes, or a requirement to get the correct time shown? I don't feel really comfortable enabling a feature labelled "Experimental" on a production system...

**Comment by amyblais** [comment]
@colorchestra The timezones on your Mattermost will work properly when the timezone setting is enabled in the system console.

**Comment by amyblais** [comment]
Hi all, we're working on a fix for this here: https://github.com/mattermost/mattermost-mobile/pull/3126.
