### ISSUE TITLE
Can receive only test notification

### ISSUE THREAD

**Issue by pharshdev** [mattermost/mattermost-mobile#3071]
#### Summary
Built the app from master. Set-up the firebase and MPNS with the server key from Firebase. Enabled notification on console with MPNS. Send Test notification works fine, I receive the notification. But I don't receive any notification for messages. Running signed apk.

#### Environment Information

- Device Name: Xiaomi RN4 and OnePlus 6
- OS Version: Android 8.1.0
- Mattermost App Version: 1.22.0
- Mattermost Server Version: Mattermost Enterprise Edition 4.7.0

#### Expected behavior
Receive notification for messages.

#### Observed behavior
Not receiving any notifications except Test Notification from the app.

**Comment by amyblais** [comment]
Hi @pharshdev, would you be open to upgrading your server version? We require v5.9 or later version if you're on on v1.22 or other recent mobile app version. See changelog: https://github.com/mattermost/mattermost-mobile/blob/master/CHANGELOG.md#1211-release.

Have you also had a chance to take a look at our troubleshooting docs: https://docs.mattermost.com/mobile/mobile-troubleshoot-notifications.html?

**Comment by pharshdev** [comment]
Thank @amyblais for pointing this out. Will post after the server upgrade.

**Comment by pharshdev** [comment]
Ok server upgraded, on master now. Still can only receive test notification. Even this 

`http://127.0.0.1:8066/api/v1/send_push -X POST -H "Content-Type: application/json" -d '{"type": "message", "message": "test", "badge": 1, "platform": "PLATFORM", "server_id": "MATTERMOST_DIAG_ID", "device_id": "DEVICE_ID", "channel_id": "CHANNEL_ID"}'` 

with my values of course returns  `{"status":"OK"}` 

and I receive the notification on mobile. But notification is not received when someone messages. Enabled send notifications 'for all activity' and trigger push notifications when 'online, away or home' on both sender and receiver. Logs says notification sent

`{"level":"info","ts":1567489207.8751597,"caller":"app/notification_push.go:263","msg":"Notification sent","logSource":"notifications","ackId":"socj93mcmp818jb9wukjpkugaa","type":"clear","userId":"9q35k6ucofr4dpd36116uau1ta","postId":"","channelId":"4uj48gofebfgukep68ruxp5xjh","deviceId":"cQgeJwqy0b4:APA91bEXntcD8u8VwdMX3bL7pPfgt1eciGggw8UW_0aNcDRAATYZ7EpygV0AqQUIRNJQqGz1Aoi7OebDo8cmPDRm8jKdBnb1HIZJQS5jUyZUr3aevYnydpcH13SxgaXPKWrxdlWf9H2z","status":"Successful"}`

 Any ideas?

**Comment by amyblais** [comment]
@pharshdev Please confirm if you have followed this documentation and please send details on your push notification settings: https://docs.mattermost.com/mobile/mobile-compile-yourself.html.

**Comment by pharshdev** [comment]
Followed all the steps in the documentation.

Mattermost-push-proxy.json
`{
    "ListenAddress":":8065",
    "ThrottlePerSec":300,
    "ThrottleMemoryStoreSize":50000,
    "ThrottleVaryByHeader":"X-Forwarded-For",
    "EnableMetrics": false,
    "ApplePushSettings":[
        {
            "Type":"apple",
            "ApplePushUseDevelopment":false,
            "ApplePushCertPrivate":"",
            "ApplePushCertPassword":"",
            "ApplePushTopic":"com.mattermost.Mattermost"
        },
        {
            "Type":"apple_rn",
            "ApplePushUseDevelopment":false,
            "ApplePushCertPrivate":"",
            "ApplePushCertPassword":"",
            "ApplePushTopic":"com.mattermost.react.native"
        }
    ],
    "AndroidPushSettings":[
        {
            "Type":"android",
            "AndroidApiKey":"AAA***"
        },
        {
            "Type":"android_rn",
            "AndroidApiKey":"AAA***"
        }
    ]
}`

Mattermost config.json
`{
   "ServiceSettings":{
      "SiteURL":"https://mattermost.xyz.io",
      "LicenseFileLocation":"",
      "ListenAddress":":8065",
      "ConnectionSecurity":"",
      "TLSCertFile":"",
      "TLSKeyFile":"",
      "UseLetsEncrypt":false,
      "LetsEncryptCertificateCacheFile":"./config/letsencrypt.cache",
      "Forward80To443":false,
      "ReadTimeout":300,
      "WriteTimeout":300,
      "MaximumLoginAttempts":10,
      "GoroutineHealthThreshold":-1,
      "GoogleDeveloperKey":"",
      "EnableOAuthServiceProvider":false,
      "EnableIncomingWebhooks":true,
      "EnableOutgoingWebhooks":false,
      "EnableCommands":false,
      "EnableOnlyAdminIntegrations":true,
      "EnablePostUsernameOverride":false,
      "EnablePostIconOverride":false,
      "EnableAPIv3":true,
      "EnableLinkPreviews":false,
      "EnableTesting":false,
      "EnableDeveloper":false,
      "EnableSecurityFixAlert":true,
      "EnableInsecureOutgoingConnections":false,
      "EnableMultifactorAuthentication":false,
      "EnforceMultifactorAuthentication":false,
      "AllowCorsFrom":"",
      "SessionLengthWebInDays":30,
      "SessionLengthMobileInDays":30,
      "SessionLengthSSOInDays":30,
      "SessionCacheInMinutes":10,
      "WebsocketSecurePort":443,
      "WebsocketPort":80,
      "WebserverMode":"gzip",
      "EnableCustomEmoji":true,
      "EnableEmojiPicker":true,
      "RestrictCustomEmojiCreation":"all",
      "RestrictPostDelete":"all",
      "AllowEditPost":"always",
      "PostEditTimeLimit":300,
      "TimeBetweenUserTypingUpdatesMilliseconds":5000,
      "EnablePostSearch":true,
      "EnableUserTypingMessages":true,
      "EnableUserStatuses":true,
      "EnableChannelViewedMessages":true,
      "ClusterLogTimeoutMilliseconds":2000
   },
   "EmailSettings":{
      "SendPushNotifications":true,
      "PushNotificationServer":"https://mattermost.xyz.io",
      "PushNotificationContents":"generic",
      "EnableEmailBatching":true,
      "EmailBatchingBufferSize":256,
      "EmailBatchingInterval":30,
      "SkipServerCertificateVerification":false
   },
}`

Points I'm not sure of:
1) Mattermost is running in a docker whereas the Push service outside of the docker. Should this be a problem?
2) PushNotificationServer field is set to the mattermost site url.

**Comment by amyblais** [comment]
@pharshdev For 2, would you be open to trying with one of the examples in this doc: https://docs.mattermost.com/administration/config-settings.html#id4?

**Comment by pharshdev** [comment]
I did try the example in the doc, no luck. New information, we haven't renewed the enterprise license(for this same notification hassle unfortunately). So currently we're running enterprise without license but that shouldn't be the problem since you the notifications work even on team-edition.

**Comment by esbeeb** [comment]
Works for me, but not by default.

@pharshdev , check that you did the following:
On mobile app, 
- tap 3 dots in upper right
- tap Settings
- tap Mobile
- tap "Trigger push notifications when" 
Note that the default value is "Away, or offline".  Change it to "Online, away, or offline".
- tap Save
Back all the way out by tapping upper left corner thrice.

Now send a sample message to that phone where you'd like a notification to appear, which would cause a notification (for example, the message mentions "@user" specifically).

You should get an Android notification after a delay of, say, 10ish seconds.

Note: Notifications for the Mattermost app must not be blocked at the Android-level either. See Android Settings -> Apps and Notifications -> Mattermost -> Notifications -> "Show Notifications" is enabled.  That's where it was in my Android 10.

Bonus tip: Your hardware switch on the side of the phone (if it exists, and my Oneplus 6 has one) for "Silent" should probably not be switched on either.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
