### ISSUE TITLE
Android app bypasses local image proxy

### ISSUE THREAD

**Issue by cburn11** [mattermost/mattermost-mobile#3095]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
The android app directly requests image (inline image in a message attachment) instead of using the server's image proxy.

#### Environment Information

- Device Name: Pixel 2 xl
- OS Version: 9  
- Mattermost App Version: 1.21.0 (Build 204)
- Mattermost Server Version: 5.13.0

#### Steps to reproduce
Create a post with an attachment with an inline image in the attachment: 
  
`{"channel_id": "boqft1hp47b6bq66y8xbnnmrcr","message": "Zodiac 2007", "props": {"attachments":[{"title":"","fields":[{"short":true,"title":"","value":"![Zodiac](http://cgi-server.danger-rocket.com/posters/d843e9e60cc86d3699a01c9c0a3073c8-poster.jpg \"Jake Gyllenhaal, Mark Ruffalo, Anthony Edwards, Robert Downey Jr.\")"},{"short":true,"title":"","value":"In the late 1960s/early 1970s, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer, an unidentified individual who terrorizes Northern California with a killing spree."},{"short":false,"title":"","value":"Jake Gyllenhaal, Mark Ruffalo, Anthony Edwards, Robert Downey Jr."}]}]}}
`
#### Observed behavior
After creating the above post, when the post is viewed in the desktop client, tcpdump shows that the request for the inline image comes from the mattermost server local proxy (10.0.0.140 is the local address of the mattermost server; 10.0.0.160 is the local address of the image server):

`09:32:14.758060 IP 10.0.0.140.36768 > 10.0.0.160.80: Flags [P.], seq 20862:21769, ack 209013, win 2005, options [nop,nop,TS val 3971358385 ecr 403226186], length 907: HTTP: GET /posters/d843e9e60cc86d3699a01c9c0a3073c8-poster.jpg HTTP/1.1`

And the browser indicates the image url is: 
`https://mattermost.danger-rocket.com:8066/api/v4/image?url=http%3A%2F%2Fcgi-server.danger-rocket.com%2Fposters%2F75bda907597dd2c7c3f81821301a0774-poster.jpg`

However when the post is viewed with the android client, the request for the inline image comes directly from the client (the android host's network address is 10.8.10.6):
`09:33:02.168257 IP 10.8.10.6.38680 > 10.0.0.160.80: Flags [P.], seq 1:180, ack 1, win 343, options [nop,nop,TS val 343631665 ecr 60358056], length 179: HTTP: GET /posters/d843e9e60cc86d3699a01c9c0a3073c8-poster.jpg HTTP/1.1`

And the app indicates the image url is:
`http://cgi-server.danger-rocket.com/posters/d843e9e60cc86d3699a01c9c0a3073c8-poster.jpg`

The request bypassing the local proxy is problematic if the mobile host is on a network 
where the local image server is not reachable.

#### Expected behavior

I am hoping for the mobile client to use the local image proxy like the desktop client does.

**Comment by hmhealey** [comment]
Hi @cburn11,

Thanks for the report. It's a known issue that the mobile apps don't use the image proxy correctly in some circumstances, but I'll bring it up for discussion again to see if we can get it reprioritized.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
