### ISSUE TITLE
'AutoSelectServerUrl: true' Losing config.SiteName On Resume

### ISSUE THREAD

**Issue by philipborbon** [mattermost/mattermost-mobile#3110]
#### Summary
'AutoSelectServerUrl: true' causes to loss config.SiteName on resume.

#### Steps to reproduce
1. Set `AutoSelectServerUrl: true` and `DefaultServerUrl`
2. In login screen, press home to put app in background.
3. Open App again from overview using overview button.
4. SiteName and other config is gone.

#### Environment Information
Only happens on Android.

#### Possible fixes
Commenting out this line in `app/init/emm_provider.js` seems to resolve the issue.
```js
handleManagedConfig = async (store) => {
.....
line 96: dispatch(handleServerUrlChanged(LocalConfig.DefaultServerUrl))
```

**Comment by amyblais** [comment]
Hi @philipborbon, what Mattermost mobile app version are you on?

**Comment by philipborbon** [comment]
Version: `1.22.0`
Commit Hash: 21a790e820c7db67524fbd05ca74e905f181701c

**Comment by amyblais** [comment]
@enahum This seems to be an issue on master based on the comment above?

**Comment by enahum** [comment]
@amyblais please file a ticket unless @philipborbon is willing to submit a fix for it

**Comment by philipborbon** [comment]
@amyblais, I don't have the proper solution or fix for this issue.
```
// app/init/emm_provider.js
line 95:        if (LocalConfig.AutoSelectServerUrl) {
line 96:            dispatch(handleServerUrlChanged(LocalConfig.DefaultServerUrl));
line 97:            this.allowOtherServers = false;
line 97:        }
```
These lines of code is there for a reason. It might be an underlying issue in `handleServerUrlChanged`.

**Comment by enahum** [comment]
@philipborbon thanks for bringing this to our attention, it is actually a bug in 1.22 so you caught it in time.

@amyblais PR here https://github.com/mattermost/mattermost-mobile/pull/3125 awaiting cherry-pick approval
