### ISSUE TITLE
Sometimes not all posts are displayed in threadview. -> #2905

### ISSUE THREAD

**Issue by somenet** [mattermost/mattermost-mobile#3135]
#2905 is still/again an issue in 1.21.2 (215) and server 5.13.2.

Now only the first and last message of a thread gets displayed in the threadview.

**Comment by amyblais** [comment]
Hi @somenet, would you be able to help with more details such as repro steps? Can you help update to v1.22 when it is available in the app store to see if it still repros?

**Comment by somenet** [comment]
Doesnt seem to happen anymore/did not experience it since updating to 5.14.x + 1.22.1
