### ISSUE TITLE
Disabled users appearing in @mentions

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-mobile#3147]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Users who are disabled appear in the auto-complete when using @ to mention a user, this does not happen in the webapp or in the desktop app.

#### Environment Information

- Device Name: OnePlus
- OS Version: Android 9.0
- Mattermost App Version: 1.21.2
- Mattermost Server Version: 5.14

#### Steps to reproduce
How can we reproduce the issue?

1. Add a user to mattermost
2. Disable the user
3. Try to @mention the user and it will appear in the auto-complete list

#### Expected behavior
Describe your issue in detail.

A disabled user shouldn't appear in the auto-complete list as this doesn't happen in the web-app/desktop app either.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

Disabled users (all of them) were appearing in the @mention auto complete list which shouldn't happen.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by DHaussermann** [comment]
Hi @arjitc Thank you for reporting this issue. I have created an issue in our ticket tracker for this to be reviewed.

**Comment by amyblais** [comment]
Closing as this will be fixed in v1.24 release, to be released on October 16th,
