### ISSUE TITLE
[Android] mattermost app crash when launch

### ISSUE THREAD

**Issue by tgly307** [mattermost/mattermost-mobile#3165]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
mattermost app will crash when start it.

#### Environment Information

- Device Name: HUAWEI MATE 20 pro
- OS Version: Android 9.0
- Mattermost App Version: 1.22.0(build 221)
- Mattermost Server Version: 5.14.0

#### Steps to reproduce
1. Clean up the background of mobile phone to ensure that mattermost is not running in the background
2. Click app icon to start it.
3. After app interface load, the app crash and need to relaunch.

![image-4ff87409-ed07-49c4-824d-6db01fe2e789](https://user-images.githubusercontent.com/25153311/63486707-2dfdcb00-c4db-11e9-8ea6-1ce864481912.jpg)

**Comment by JtheBAB** [comment]
Maybe related to https://mattermost.atlassian.net/browse/MM-17971

**Comment by tgly307** [comment]
@JtheBAB thanks for the information. I tried switch language to english, and the app will start correctly. The app will crash when switch the language setting from desktop.

**Comment by JtheBAB** [comment]
Ok then it is this bug and there will be soon a 1.22.1 that fix that.

**Comment by enahum** [comment]
Yes there was an issue with `zh-TW` causing the app to crash, there is an already merged PR #3155 that fixes it, and we will be shipping a dot release soon.

In the meantime as a workaround you can change your language settings on the webapp/desktop to English and revert back to Chinese once 1.22.1 is out.

Sorry for the inconvenience .

Closing issue.
