### ISSUE TITLE
mattermost android app error when signing in with gitlab

### ISSUE THREAD

**Issue by huyp182** [mattermost/mattermost-mobile#3169]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
mattermost android app shows an error message when signing in with gitlab.
Error message: {"id":"api.user.authorize_oauth_user.invalid_state.app_error","message":"无效状态","detailed_error":"","status_code":400}

#### Environment Information

- Device Name: 360 N6 Pro
- OS Version: 360 OS V023 Based on Android 8.1
- Mattermost App Version: 1.22.0
- Mattermost Server Version: 4.0.0+

#### Steps to reproduce
sign in mattermost with gitlab on android devices.

#### Expected behavior
Describe your issue in detail.

#### Observed behavior
Error message: {"id":"api.user.authorize_oauth_user.invalid_state.app_error","message":"无效状态","detailed_error":"","status_code":400}

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
Hi @huyp182, would you be open to checking what server version you're on? v1.22 version requires being on v5.9+ server version so I just want to make sure the bug is not caused by an old server version. https://github.com/mattermost/mattermost-mobile/blob/master/CHANGELOG.md#1220-release

**Comment by huyp182** [comment]
> Hi @huyp182, would you be open to checking what server version you're on? v1.22 version requires being on v5.9+ server version so I just want to make sure the bug is not caused by an old server version. https://github.com/mattermost/mattermost-mobile/blob/master/CHANGELOG.md#1220-release

How can I know the server version?

**Comment by amyblais** [comment]
@huyp182 On iOS you can find out your server version from Mattermost > Main Menu > Settings > About Mattermost. It should be on a very similar place on the Android app as well.

**Comment by huyp182** [comment]
But I cannot sign in on android app, the mattermost client on windows is the newest version, 4.2.3.

**Comment by huyp182** [comment]
Yes, it‘s desktop app.

**Comment by huyp182** [comment]
Mattermost 版本： 5.13.2
数据库 Schema 版本： 5.13.0
数据库： postgres

**Comment by huyp182** [comment]
Mattermost Version： 5.13.2
Database Schema Version： 5.13.0
Database： postgres

**Comment by huyp182** [comment]
![微信图片_20190829103122](https://user-images.githubusercontent.com/22772980/63905919-686de780-ca48-11e9-8084-9492f34db3bb.png)
That's the screenshot.

**Comment by hmhealey** [comment]
I'm not aware of any new issues here.

@huyp182 Did Android login work on mobile before? Are you using the Mattermost app from the Play Store, or did you build it yourself?

**Comment by huyp182** [comment]
It's the first time I use the mobile app, it's from the Play Store.

**Comment by hmhealey** [comment]
And you can log into the server using GitLab from a browser?

Do you use the same URL to log into Mattermost on both the browser and in the mobile app? I know there's some people that use that setup, but it can cause problems sometimes

**Comment by huyp182** [comment]
Yes, I can log in on Chrome and desktop mattermost app. The mattermost server URL is http://gitpd.appdao.com:8065.
When I log in on desktop app, it shows "错误 无效状态 返回到 Mattermost", the translation is "Error. Invalid state. Go back to Mattermost". When I click "go back to Mattermost", I log in successfully.
But on Android, it shows "{"id":"api.user.authorize_oauth_user.invalid_state.app_error","message":"无效状态","detailed_error":"","status_code":400}", and there is no "go back to Mattermost" link.

**Comment by hmhealey** [comment]
That's strange that you get that error message on the desktop app as well. I wouldn't expect to see that error at all. When you click "go back to Mattermost" are you already logged in, or do you have to click on the GitLab button on the login page a second time? I've seen that happen a few times when something wasn't configured correctly.

Is there perhaps a redirect occurring when you're sent back from GitLab to Mattermost? Normally, after logging in on GitLab, the user should be sent back to something like `http://<mattermost>/login/gitlab/complete?state=<state>&code=<code>`, but it seems like the `state` is either invalid or missing when you're sent back to Mattermost

**Comment by huyp182** [comment]
When I click "go back to Mattermost" I'm already logged in, and I don't need to click on the Gitlab button a second time.
Oh, the reason is probably that the server's configuration is wrong. thanks.

**Comment by huyp182** [comment]
When I log in http://mm.paodingai.com/login on Chrome, the error doesn't appear, when I click on Gitlab button I log in, but when on Desktop and mobile APP, it occurs.

**Comment by hmhealey** [comment]
They'll be available in the Mattermost System Console under the Authentication > GitLab section. You'll want to make sure that:
1. The GitLab Site URL matches the URL that you access your GitLab instance from
2. The User API Endpoint, Auth Endpoint, and Token Endpoint should be set based off of that
![image](https://user-images.githubusercontent.com/3277310/64891581-4e372a80-d640-11e9-808a-03702289caac.png)

**Comment by huyp182** [comment]
I cannot use Mattermost System Console...

**Comment by amyblais** [comment]
@huyp182 Would you be able to contact the System Administrator on your server to check the settings?

**Comment by huyp182** [comment]
Solved.
