### ISSUE TITLE
Makefile build-android runs `npm install`

### ISSUE THREAD

**Issue by glunardi** [mattermost/mattermost-mobile#3198]
#### Summary
It seems build-android is meant to rely on `npm ci` only
but `make build-android` still runs `npm install`

#### Environment Information
mattermost-mobile master (20190827)

#### Steps to reproduce
Every time one runs `make build-android`

#### Expected behavior
There are so many version dependencies in node, react, react-native, etc... that it seems the build must rely on the provided `package-lock.json` to make all the planets align.

#### Observed behavior
`build-android:` in the Makefile carefully starts by running `npm ci` in npm-ci: but seconds later runs `npm install` on top of that when executing `node_modules:` as a dependency from `check-style:`

At least in my case it breaks build attempts very easily.

#### Possible fixes
Does `check-style:` really need to depend on `node_modules:` ?

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
