### ISSUE TITLE
concern fetchTeams

### ISSUE THREAD

**Issue by cipas** [mattermost/mattermost-mobile#32]
Hey guys,

https://github.com/mattermost/mattermost-mobile/blob/master/src/client/client.js#L203
should this be `/all_team_listings` ? I feel like it should be `/all`.

**Comment by mfpiccolo** [comment]
Possibly, however the web app currently returns teams in initial_load and /all_teams_listings in this view.

<img width="1272" alt="screen shot 2016-10-19 at 10 18 01 am" src="https://cloud.githubusercontent.com/assets/3249825/19529618/8ee33752-95e5-11e6-8ffc-33dc1fb83981.png">
<img width="1275" alt="screen shot 2016-10-19 at 10 17 24 am" src="https://cloud.githubusercontent.com/assets/3249825/19529617/8eda9962-95e5-11e6-855c-4044cd62793e.png">

**Comment by lfbrock** [comment]
Hi @cipas - thanks for your interest in the project!

It's still in the early stages, and a lot of changes are being made as we work on it. We're planning on releasing the beta version in Q1 of this year - after the beta release, the code base should be more stable and ready for community members to start contributing. 

We'll do an announcement to our mailing list when the beta version is ready, you can sign up [here](http://mattermost.us11.list-manage.com/subscribe?u=6cdba22349ae374e188e7ab8e&id=2add1c8034) if you'd like to be notified!
