### ISSUE TITLE
Error certificate Letsencrypt

### ISSUE THREAD

**Issue by miguellara999** [mattermost/mattermost-mobile#3207]
#### Environment Information

- Device Name: Samsung Galaxy S8+
- OS Version: Android 8
- Mattermost App Version: 1.22.1 
- Mattermost Server Version: 5.14.1

#### Expected behavior

We are testing Mattermost in a server where we installed another letsencrypt ceritficate and exist an apache running in 443 port.

The Mattermost is running on port 8065 and we set the .key file and .crt file from webgui, the option "Use Let's Encrypt" is disabled because is not running on port 80/443.

The web access with TLS working fine, desktop application for Windows working fine too and iOS application, but for Android we have a problem with certificate:

{"level":"error","ts":1567177896.6155794,"caller":"http/server.go:1794","msg":"http: TLS handshake error from X.X.X.X:49000: remote error: tls: unknown certificate","source":"httpserver"}

But the strange thing is that if I follow the next steps, I bypass the error and I can login into Mattermost but when I change the network we are out again:

- Trying with https://myserver.com:8065 -> Error
- Trying with https://mattermost.com -> Error
- Trying with https://myserver.com:8065 -> Success

We tested with two android mobile.

**Comment by amyblais** [comment]
Hi @miguellara999, this doc might help: https://docs.mattermost.com/mobile/mobile-troubleshoot.html#i-keep-getting-a-message-cannot-connect-to-the-server-please-check-your-server-url-and-internet-connection.

**Comment by hkuwabara3** [comment]
Android apps are still unavailable. Why not cure SSL failures?

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
