### ISSUE TITLE
com.mattermost.custom-attributes - does not work on mobile app

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-mobile#3210]
It seems that the mobile app is generally lagging behind alot.

#### Summary
No custom profile fields are displayed on the mobile app.

#### Environment Information
- Device Name: OnePlus 5t (irrelevant)
- OS Version: LOS 16 (irrelevant)
- Mattermost App Version: 1.22.1
- Mattermost Server Version: 5.14.1

#### Steps to reproduce
+ enable bundled plugins.
+ set custom profile fields.
+ verify custom profile fields via web-app.
+ launch andoid app and click on a username that has a custom profile field assigned.
+ dont see custom profile fields.

#### Expected behavior
Custom profile fields should be shown to users on android app.

#### Observed behavior
nothing was displayed.

**Comment by amyblais** [comment]
Hi @somenet, please see more details here: https://developers.mattermost.com/extend/plugins/mobile/.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
