### ISSUE TITLE
Could not create new channel

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost-mobile#3216]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
If you select "Combine all channel types" for channel grouping, you will not be able to create new conversations or channels.

#### Environment Information
- Device Name: Galaxy S9 / iPhone SE
- OS Version: 9.0 (same, any version)
- Mattermost App Version: 1.22.0, 1.22.1 
- Mattermost Server Version: 5.14.2

#### Steps to reproduce
1. Turn on "Sidebar Organization" function in management console.
<img width="895" alt="00 sidebar" src="https://user-images.githubusercontent.com/20394843/64242564-bac77080-cf40-11e9-841e-9ad236911178.png">

2. Change setting of channels grouping in "Account Settings"
<img width="790" alt="01 changesorttype" src="https://user-images.githubusercontent.com/20394843/64242633-daf72f80-cf40-11e9-8e4a-7047d345a54e.png">

3. Run Mattermost mobile app. (same iOS, Android) Create a new channel (or conversation).
![03 channel](https://user-images.githubusercontent.com/20394843/64242698-f6fad100-cf40-11e9-9f33-d36decd5323a.gif)

4. You can see blank page.

#### Expected behavior
Successful channel creation or conversation start.

#### Observed behavior
Already attached. 

#### Possible fixes
Probably because of react-native-navigation. This problem does not appear until 1.21.

**Comment by amyblais** [comment]
Thanks @Gloriashield, we opened a ticket here: https://mattermost.atlassian.net/browse/MM-18223.

**Comment by Gloriashield** [comment]
@amyblais Thank you for your quick response.

**Comment by Gloriashield** [comment]
Thank you!
