### ISSUE TITLE
Links with spaces break if using formatting syntax for links

### ISSUE THREAD

**Issue by Naticus** [mattermost/mattermost-mobile#3229]
#### Summary
Spaces in a link using the format [Text](Link) will break the link on mobile.

#### Environment Information
- OS Version: Android 9
- Mattermost App Version: 1.22.1
- Mattermost Server Version: 5.14.2

#### Steps to reproduce
How can we reproduce the issue?
Create a link such as `[test test test](https://google.com/search?q=test test test)` 

#### Expected behavior
Describe your issue in detail.
A link with the text "test test test"
#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
On desktop, the result is as expected.  On mobile, you will see it as an unformatted message.
Desktop:  ![image](https://user-images.githubusercontent.com/4529390/64481006-a930d380-d1a1-11e9-97e8-1639be1814d5.png)
Mobile:  
![image](https://user-images.githubusercontent.com/4529390/64481062-6d4a3e00-d1a2-11e9-8d0e-c8383fff602e.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.
Unknown, sorry!

**Comment by hmhealey** [comment]
Hi @Naticus,

The behaviour that you're seeing on the mobile app is actually the correct behaviour since we've been trying to standardize our Markdown to more closely match the [CommonMark](https://commonmark.org/) version used by other platforms such as GitHub. Similarly, if you paste that text in GitHub, you'll get the same behaviour as the mobile app.

> [test test test](https://google.com/search?q=test test test)

If you're wanting to use spaces in a link, you'll have to replace them with `%20` like the browser does if you copy a link with spaces from the address bar.

```markdown
[test test test](https://google.com/search?q=test%20test%20test)
```

> [test test test](https://google.com/search?q=test%20test%20test)

**Comment by Naticus** [comment]
Damn, I was REALLY hoping you weren't going to say something like that.  One issue we're having is that we're using Autolink to create things like search links.  So for example typing in
`Google:test test test`
Will result in
`[Google Search for <test test test>](https://google.com/search?q=test test test)`

The problem I am having is that I don't know if there's a good way to play with regex where I replace all those spaces with a %20 without breaking everything.

**Comment by hmhealey** [comment]
Perhaps something like a slash command might work better here? Writing a pattern that captures things like `Google:test test test` with spaces seems like it'd be difficult if there's any text in the post that you don't want to capture, and if that's the whole post, it might be easier to make a slash command that responds to `/google test test test` with a link instead.

Alternatively, there might be something we could do here with regex groups like joining each word `(?:(\S)*\s)*` together with a `%20`, but I don't know if that's possible with how the autolink plugin is configured. I haven't set it up myself

**Comment by Naticus** [comment]
Yeah I was thinking something like that with making a bunch of group designations and concatenating them with %20's.  Maybe give room for up to like 20 words.  I'll see if I can come up with a workable solution, thanks.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
