### ISSUE TITLE
In Android or any other plateform can we have direct forwarding the message to other chat recipient

### ISSUE THREAD

**Issue by RonakAndroid** [mattermost/mattermost-mobile#3294]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

#### Environment Information

- Device Name: 
- OS Version: 
- Mattermost App Version: 
- Mattermost Server Version:

#### Steps to reproduce
How can we reproduce the issue?

#### Expected behavior
Describe your issue in detail.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
You have the option to copy the message and then you could paste it to another channel, GM or DM.

What would be the use case to forward the message as in an email client or whatsapp?

**Comment by RonakAndroid** [comment]
yes, we can follow the forwarding process like whats app and email client.
do you you think it is remarkable to implement ?

**Comment by bezumkin** [comment]
@enahum We can copy only text, but not an attachments.

Which could very handy when you work in a company and you need share one document in different chats.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
