### ISSUE TITLE
No buttons on client upgrade screen during first run

### ISSUE THREAD

**Issue by yakimant** [mattermost/mattermost-mobile#3305]
#### Summary
If I install an app, which version is not latest - after choosing a server client shows and upgrade screen. But buttons are missing on it.

#### Steps to reproduce
Install a client with version higher than minimal, but lower than latest.
Enter a Server URL.
Update App screen appears.

#### Expected behavior
Should have Update and Skip buttons
![IMG_0045](https://user-images.githubusercontent.com/1529006/65533320-4a838d80-def5-11e9-9b74-1d82eebdaf6e.jpg)

#### Observed behavior
Doesn't include any buttons
![IMG_0046](https://user-images.githubusercontent.com/1529006/65533347-52dbc880-def5-11e9-9db1-0970c318301d.jpg)

#### Possible fixes
Looks like ```isUpgradeAvailable(this.state.upgradeType)``` return false (app/screens/client_upgrade/client_upgrade.js:232).

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
