### ISSUE TITLE
Can't build iOS app: "Could not find CFPropertyList-3.0.0 in any of the sources"

### ISSUE THREAD

**Issue by l112119** [mattermost/mattermost-mobile#3331]
#### Summary
I trying to build local iOS app using instruction on https://developers.mattermost.com/contribute/mobile/build-your-own/
On the final step `make build-ios` it freezes. 

#### Environment Information
- OS Version: macOS 10.13.6 
- ruby 2.3.7p456
- fastlane 2.131.0
- Mattermost App Version: latest

#### Steps to reproduce
I followed by instruction: https://developers.mattermost.com/contribute/mobile/build-your-own/
I created env_vars.env in fastlane directory:

> ############ VARIABLE VALUES ############
> #export MATTERMOST_WEBHOOK_URL=<set this to an incoming webhook url to get a notification when the build finishes>
> 
> export BRANCH_TO_BUILD=master
> export GIT_LOCAL_BRANCH=build
> 
> export APP_NAME="Mattermost_Beta"
> ############ MAKE GIT RESTORE THE BRANCH STATE ONCE BUILD FINISHES ############
> export COMMIT_CHANGES_TO_GIT=false
> export RESET_GIT_BRANCH=false
> 
> ############ NO NEED TO CHANGE AND THIS ENSURES THAT NODEJS DOESN'T CRASH WHILE BUILDING ############
> export LC_ALL="en_US.UTF-8"
> export NODE_OPTIONS=--max_old_space_size=12000
> 
> ############ MATCH IS USED TO SYNC THE IOS PROVISIONING PROFILES ############
> export MATCH_USERNAME=my apple id
> #export FASTLANE_PASSWORD=<>
> export MATCH_PASSWORD=my apple pass
> export MATCH_KEYCHAIN_PASSWORD=my local pass
> #export MATCH_GIT_URL=<private git repository to allow match sync the provisioning profiles>
> export MATCH_APP_IDENTIFIER=com.mattermost.rnbeta.NotificationService,com.mattermost.rnbeta.MattermostShare,com.mattermost.rnbeta
> export MATCH_TYPE=adhoc
> #export MATCH_SHALLOW_CLONE=true
> export MATCH_SKIP_DOCS=true
> #export FASTLANE_TEAM_ID=<itunes connect team ID>
> export SYNC_PROVISIONING_PROFILES=false
> 
> ############ NEEDED TO UPLOAD THE BUILD TO TESTFLIGHT ############
> #export PILOT_USERNAME=<itunes connect account>
> #export PILOT_SKIP_WAITING_FOR_BUILD_PROCESSING=true
> 
> ############ NEEDED TO UPLOAD THE BUILD TO GOOGLE PLAY ############
> #export SUPPLY_TRACK=alpha
> #export SUPPLY_PACKAGE_NAME=com.mattermost.rnbeta
> #export SUPPLY_JSON_KEY=<The path to the service account json file used to authenticate with Google>
> #export SUPPLY_VALIDATE_ONLY=false
> 
> ############ REPLACE ASSETS, BUILD IN RELEASE MODE ############
> #export BETA_BUILD=true
> export BUILD_FOR_RELEASE=false
> export REPLACE_ASSETS=false
> 
> ############ APP IDENTIFIERS ############
> export MAIN_APP_IDENTIFIER=com.mattermost.rnbeta
> export EXTENSION_APP_IDENTIFIER=com.mattermost.rnbeta.MattermostShare
> export NOTIFICATION_SERVICE_IDENTIFIER=com.mattermost.rnbeta.NotificationService
> export IOS_APP_GROUP=group.com.mattermost.rnbeta
> export IOS_ICLOUD_CONTAINER=iCloud.com.mattermost.rnbeta
> export IOS_BUILD_EXPORT_METHOD=adhoc
> 
> ############ SET TO TRUE TO UPLOAD THE BUILDS TO TESTFLIGH AND GOOGLE PLAY ############
> export SUBMIT_IOS_TO_TESTFLIGHT=false
> export SUBMIT_ANDROID_TO_GOOGLE_PLAY=false

#### Observed behavior
Final part of logs:

> Building iOS app
> mattermost-mobile@1.24.0 start /Users/autotestmts/Projects/MMMobile/mattermost-mobile
> node ./node_modules/react-native/local-cli/cli.js start
> Could not find CFPropertyList-3.0.0 in any of the sources
> Run `bundle install` to install missing gems.
> make: *** [build-ios] Error 7
> ┌──────────────────────────────────────────────────────────────────────────────┐
> │                                                                              │
> │  Running Metro Bundler on port 8081.                                         │
> │                                                                              │
> │  Keep Metro running while developing on any JS projects. Feel free to        │
> │  close this tab and run your own Metro instance if you prefer.               │
> │                                                                              │
> │  https://github.com/facebook/react-native                                    │
> │                                                                              │
> └──────────────────────────────────────────────────────────────────────────────┘
> Looking for JS files in
>    /Users/autotestmts/Projects/MMMobile/mattermost-mobile 
> Loading dependency graph, done.

While I try to 
`bundle install`
I've got:

> Using CFPropertyList 3.0.1
> Using public_suffix 2.0.5
> Using addressable 2.7.0
> Using atomos 0.1.3
> Using babosa 1.0.3
> Using bundler 2.0.2
> Using claide 1.0.3
> Using colored 1.2
> Using colored2 3.1.2
> Using highline 1.7.10
> Using commander-fastlane 4.4.6
> Using declarative 0.0.10
> Using declarative-option 0.1.0
> Using digest-crc 0.4.1
> Using unf_ext 0.0.7.6
> Using unf 0.1.4
> Using domain_name 0.5.20190701
> Using dotenv 2.7.5
> Using emoji_regex 1.0.1
> Using excon 0.67.0
> Using multipart-post 2.0.0
> Using faraday 0.15.4
> Using http-cookie 1.0.3
> Using faraday-cookie_jar 0.0.6
> Using faraday_middleware 0.13.1
> Using fastimage 2.1.7
> Using gh_inspector 1.1.3
> Using jwt 2.1.0
> Using memoist 0.16.0
> Using multi_json 1.13.1
> Using os 1.0.1
> Using signet 0.11.0
> Using googleauth 0.6.7
> Using httpclient 2.8.3
> Using mime-types-data 3.2019.0904
> Using mime-types 3.3
> Using uber 0.1.0
> Using representable 3.0.4
> Using retriable 3.1.2
> Using google-api-client 0.23.9
> Using google-cloud-env 1.2.1
> Using google-cloud-core 1.3.1
> Using google-cloud-storage 1.16.0
> Using json 2.2.0
> Using mini_magick 4.9.5
> Using multi_xml 0.6.0
> Using plist 3.5.0
> Using rubyzip 1.2.4
> Using security 0.1.3
> Using naturally 2.2.0
> Using simctl 1.6.6
> Using slack-notifier 2.3.2
> Using terminal-notifier 2.0.0
> Using unicode-display_width 1.6.0
> Using terminal-table 1.8.0
> Using tty-screen 0.7.0
> Using tty-cursor 0.7.0
> Using tty-spinner 0.9.1
> Using word_wrap 1.0.0
> Using nanaimo 0.2.6
> Using xcodeproj 1.12.0
> Using rouge 2.0.7
> Using xcpretty 0.3.0
> Using xcpretty-travis-formatter 1.0.0
> Using fastlane 2.131.0
> Using fastlane-plugin-android_change_package_identifier 0.1.0
> Using mini_portile2 2.4.0
> Using nokogiri 1.10.4
> Using fastlane-plugin-android_change_string_app_name 0.1.1
> Using fastlane-plugin-find_replace_string 0.1.0
> Using fastlane-plugin-versioning_android 0.1.0
> Bundle complete! 5 Gemfile dependencies, 71 gems now installed.
> Use bundle info [gemname] to see where a bundled gem is installed.

Help please. What else can I check?

**Comment by bradjones1** [comment]
This will occur if you install `fastlane` directly, instead of installing `bundler` first then running `bundle update && bundle install` inside the fastlane directory.
