### ISSUE TITLE
Text is truncated to 5 lines in certain cases.

### ISSUE THREAD

**Issue by vernonrj** [mattermost/mattermost-mobile#3350]
#### Summary
Some messages aren't fully displayed on the Android mobile app in certain circumstances - they should be 6 lines long, but are only showing the first 5 lines of the message.

#### Environment Information

- Device Name: Pixel 2, Pixel 3
- OS Version: Android 10
- Mattermost App Version: Mattermost Beta 1.24.0 (Build 233), Mattermost 1.23.1 (Build 234)
- Mattermost Server Version: 5.15.0

#### Steps to reproduce

Using one of the above devices, paste the following text in, and view it in the Android mobile app (everything within the backticks): `aaa aaa aaaaa aaa aaa aaaaaaaa aaa aaa aaaa aa a aaaa-aaaaaa, aaa aaa aaaaaaa aaaaa aaaaa aaaaaaaa-aaaa-aaaa-aaaaaa, aaaaaaaa-aa-aaaaaaa-aaaaa-aa-aaa aaa. aaa aaaaa. aaa aaaaa aaaaaaa a aaa'a aaaa aa aaaaaaaaaaaa aaaa.`

#### Expected behavior

The message is displayed in its entirety, up through the period at the end.

#### Observed behavior

The message was truncated to 5 lines, ending with `aaa'a aaaa aa`

Some messages are truncated to 5 rows when there should be 6 rows of text. The entire message cannot be seen unless the user does any of the following:

- edits the message (the entire message can be seen in the edit dialog)
- edits the message, adds whitespace to the end, and saves (the message is saved as edited, showing the `(edited)` at the end) - the presence of trailing whitespace does not affect the bug; it really does seem to be the addition of `(edited)`.
- opens the context menu and clicks "Copy text" (the entire message is copied into the clipboard)

I can't duplicate with arbitrary messages, but multiple different messages have exhibited this truncation bug. The above test message is one of the problematic messages with all the letters replaced with "a".

I was also able to duplicate by replacing the text with "b", "c", and "e". The entire message is shown if the text is replaced with "d".

You can see this in the attached screenshot. The lines with a period `.` at the end are displaying correctly. The other lines are not.

![bug](https://user-images.githubusercontent.com/1501374/65838997-137af680-e2be-11e9-8c51-ad89c22528bd.jpg)

The bug is still seen after performing these actions:

- restarting the phone
- Entering the app and going to Settings -> Advanced Settings -> Delete Documents & Data; and restarting the app.

#### Possible fixes

Unknown, but this looks to me like some sort of bug in the reflow code.

**Comment by enahum** [comment]
Hi @vernonrj this is a bug in React Native on Android Q here is the issue filed in their repo https://github.com/facebook/react-native/issues/25258 most probable is that we'll need to wait until this is fixed on their end.

**Comment by vernonrj** [comment]
Yes, that is definitely the bug I'm seeing. Thanks for looking into this.

**Comment by enahum** [comment]
Hey @vernonrj is this issue still true for you?

**Comment by vernonrj** [comment]
It looks like this has been fixed. The example text is correctly shown in both mattermost beta and stable apps. You're welcome to close if you'd like.

**Comment by enahum** [comment]
Thanks for confirming
