### ISSUE TITLE
App builds successfully, but not running for iOS

### ISSUE THREAD

**Issue by 00Spider47** [mattermost/mattermost-mobile#3381]
#### Summary
I am able to open files in .xcworkspace and build the app but it's getting stuck on start signalling the information that some modules are missing.

#### Environment Information

- Device Name: iOS Simulator
- OS Version: 12.1
- Mattermost App Version: Latest
- Mattermost Server Version: Latest

#### Steps to reproduce

1) Open the iOS folder and .xcworkspace.
2) Install the npm modules and cocoapods dependencies whatever necessary
3) Build the app,Builds successfully but gets stuck showing a red screen.

#### Expected behavior
The App should be in running state without errors and should move on to Login Screen.

#### Observed behavior
Please find the screenshot of the error thrown when it is run after build is success.
![image](https://user-images.githubusercontent.com/45037094/66371759-d3a0c700-e9c1-11e9-8da1-024fbfd89736.png)

#### Possible fixes
- Don't know the root cause of this error.Upon googling the choices made were to remove the node modules and reinstallation, downgrading versions of react-native module and rebuilding but the error stays that way.

**Comment by enahum** [comment]
On a terminal you can run `make dist/assets` to fix this issue. Maybe this helps https://developers.mattermost.com/contribute/mobile/developer-workflow/

**Comment by 00Spider47** [comment]
@enahum  : Ran the command 

![image](https://user-images.githubusercontent.com/45037094/66374536-e1a61600-e9c8-11e9-9b71-f2ac8f0eda05.png)

![image](https://user-images.githubusercontent.com/45037094/66374577-f682a980-e9c8-11e9-9e0d-f8299e5655c4.png)


and the folder is generated 

![Screen Shot 2019-10-08 at 12 42 01 PM](https://user-images.githubusercontent.com/45037094/66374657-15813b80-e9c9-11e9-9f4d-0bafdec861a7.png)

but the issue still exists :(

**Comment by enahum** [comment]
@00Spider47 is it the same issue? have you tried running the packager in the terminal as well? what about using `npm start -- --reset-cache` just to be sure. Also I would recommend not installing the pods or npm directly but running either `make start` or `make pre-run`.

**Comment by 00Spider47** [comment]
@enahum : Restarted the packager and ran the build from xcode.Got it working now
![Simulator Screen Shot - iPhone XR - 2019-10-08 at 13 20 36](https://user-images.githubusercontent.com/45037094/66377058-70696180-e9ce-11e9-9876-d308ef1a78e3.png)

**Comment by enahum** [comment]
Perfect.

Will close the issue then. Feel free to re-open it if needed.

**Comment by 00Spider47** [comment]
Thanks a lot buddy :)
