### ISSUE TITLE
Task :app:bundleReleaseJsAndAssets : Module `mattermost-redux/actions/users` does not exist in the Haste module map

### ISSUE THREAD

**Issue by ArnY** [mattermost/mattermost-mobile#3410]
#### Summary
When building release, during bundleReleaseJsAndAssets task, process fails with error:

```
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
Loading dependency graph, done.
BUILDING MODULES FOR android
error Unable to resolve module `mattermost-redux/actions/users` from `/root/mattermost-mobile/app/mattermost.js`: Module `mattermost-redux/actions/users` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.. Run CLI with --verbose flag for more details.
```
The suggested solution doesn't improve anything.

#### Environment Information

- OS Version: Debian 10.0
- Mattermost App Version: master branch

#### Steps to reproduce
my env:
``` bash
export APP_NAME="mattermost-univnantes"
export MAIN_APP_IDENTIFIER=com.univnantes.mattermost
export BUILD_FOR_RELEASE=true
export BETA_BUILD=false
export MATTERMOST_RELEASE_STORE_FILE=~/mattermost-univnantes-release.keystore
export MATTERMOST_RELEASE_KEY_ALIAS=mattermost-univnantes
export MATTERMOST_RELEASE_PASSWORD=xxxxxxxxx
export BRANCH_TO_BUILD=master
export REPLACE_ASSETS=true
```
nodejs: 10.16.0
npm: 6.9.0

I start building with the following command
``` bash
make build-android
```

**Comment by ArnY** [comment]
am I the only one having the problem?

**Comment by bezumkin** [comment]
@ArnY I have the same problem after fetching current code from upstream

**Comment by jackychanfox** [comment]
same issue. new repo doesn't include this file ```mattermost-redux/actions/users```
```

**Comment by simonpcook** [comment]
I'm also having this issue trying to build the app for iOS. Did any of you who had this before manage to solve it?

**Comment by vamsimudadla** [comment]
rm -rf node_modules
npm cache clean --force
npm i
This one worked for me

**Comment by ArnY** [comment]
> rm -rf node_modules
> npm cache clean --force
> npm i
> This one worked for me

Hello @valentijnnieman 
The make build-android process already remove the modules and clears the cache. This doesn't fix anything for me, unfortunately...

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
