### ISSUE TITLE
Pinging a mattermost instance behind Google IAP (or other authentication layer)

### ISSUE THREAD

**Issue by henricook** [mattermost/mattermost-mobile#3416]
#### Summary
When a mattermost instance is located behind Google's Identity-aware proxy the 'ping' endpoint gets redirected to a Google login page.

**Expected:** User sees a popup / open browser window to Google authenticate and enable transparent communication through the proxy

**Actual:** Ping fails, mattermost mobile claims the server is unconnectable

#### Environment Information

- Device Name: Google Pixel 3 XL
- OS Version: Android 10
- Mattermost App Version: Beta - 1.24.0
- Mattermost Server Version: N/A

#### Steps to reproduce
Our mattermost is behind IAP, a random example of an IAP URL is: https://zzz.qa.g.nakhoda.ai/

When you go to zzz.qa.g.nakhoda.ai you're redirected to a login page on accounts.google.com - once authenticated with a permitted google account you're returned to https://zzz.qa.g.nakhoda.ai/ with no indications a proxy is in place

#### Expected behavior
The mobile app says "cannot connect to the server. Please check your server URL and internet connection"

#### Possible fixes

In the core library where the ping is happening, handle a redirect and show it to the user in case it's for authentication, then follow login redirects and resume looking for the ping response

**Comment by redbaron** [comment]
from client side, IAP is quite similar to captive portals many free WiFi hotspots use: upon request redirect occurs, where user must do some actions on a page before redirected to originally requested URL.

Difference is that captive portals registry MAC address, so it is possible to "complete" them using another app (like browser), but for  IAP there must be shared cookie storage between app and IAP login window. It is unlikely that MM app can share cookies with installed browser, so login page should be displayed in-app.

**Comment by matthewtckr** [comment]
Stumbled across this using Azure AD Application Proxy, just wanted to share for awareness if anyone else tries to implement it on their Azure AD.

**Comment by amyblais** [comment]
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),
