### ISSUE TITLE
Not resizeable on samsung DeX

### ISSUE THREAD

**Issue by glebtv** [mattermost/mattermost-mobile#3427]
#### Summary
Not resizeable on samsung DeX mode

#### Environment Information
- Device Name: Samsung s10 plus
- OS Version: Android 9
- Mattermost App Version: master
- Mattermost Server Version:5.15

#### Steps to reproduce
Open mattermost-mobile in samsung DeX mode

#### Expected behavior
The app is resizeable

#### Observed behavior
The app is not resizeable

#### Possible fixes
Samsung has a guide: https://developer.samsung.com/samsung-dex/modify-optimizing

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @glebtv,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by glebtv** [comment]
If I enable ""Force activities to be resizable" in Dex Labs - Mattermost window becomes resizeable and works perfectly. (If you enable it, you need to restart dex mode)

So I think all is needed is to mark it as resizeable

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
