### ISSUE TITLE
iPad physical keyboard

### ISSUE THREAD

**Issue by damodon** [mattermost/mattermost-mobile#3510]
On an iPad using a physical keyboard you cannot send the message by hitting enter, instead needing to tap the send button on the screen.  Hitting enter should send the message.

#### Environment Information

- Device Name: iPad Pro with smart keyboard
- OS Version: iOS12x / iOS13x
- Mattermost App Version: 1.2X
- Mattermost Server Version: unknown

#### Steps to reproduce
Connect a supported iPad to Smart Keyboard and type into message field.

#### Expected behavior
Hitting the enter button should send the message

#### Observed behavior
Hitting the enter button moved down one line.

**Comment by amyblais** [comment]
@damodon There is a Help Wanted issue open for this here: https://github.com/mattermost/mattermost-server/issues/8797.

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
