### ISSUE TITLE
Profile images are not shown in Android notifications

### ISSUE THREAD

**Issue by dannyhanes** [mattermost/mattermost-mobile#3532]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Profiles images are not shown in Android notifications. Also, name shown is shortname and not display name. (homeassistant vs Home Assistant)

#### Environment Information

- Device Name: Pixel 3 XL
- OS Version: 10
- Mattermost App Version: Prod (1.24) Beta (1.24)
- Mattermost Server Version: 5.15.0

#### Steps to reproduce
Receive a notification from Mattermost on an android device. 

#### Expected behavior
Expected that instead of a placeholder image, I would see the image the user provided. 

#### Observed behavior
![Screenshot_20191108-120620](https://user-images.githubusercontent.com/3778687/68496947-6fbc2900-0221-11ea-899f-2e16694cb7ca.png)

![Screenshot_20191108-120630](https://user-images.githubusercontent.com/3778687/68496987-83678f80-0221-11ea-9a74-780e1b4c7638.png)

**Comment by amyblais** [comment]
@dannyhanes Does this happen with all users or only bots?

**Comment by dannyhanes** [comment]
@amyblais seems to be with all users including bots.

**Comment by amyblais** [comment]
@dannyhanes What are the following settings set to on your instance/account?

1. Account Settings>> Display>> Teammate Name Display
2. System Console > Site Configuration > Notifications > Push Notification Contents

Also, do you mean that the icon should be displaying an image and not an alphabetical letter?

**Comment by dannyhanes** [comment]
@amyblais - Here are the results. 

1. Show nickname if one exists, otherwise show first and last name. 
2. Send full message snippet. 

And yes, ideally the notification should show the image instead of the icon with an alphabetical letter.

**Comment by amyblais** [comment]
@dannyhanes Showing an image instead of icon would be a feature request.

The issue with the name shown is shortname and not display name can be fixed by changing Account Settings>> Display>> Teammate Name Display to "Show first and last name".

**Comment by dannyhanes** [comment]
@amyblais Ah ok. Then consider having the profile photo as a feature request :) 

As for the display name, here are my settings: 
    System Console >> Users and Teams >> Teammate Name Display: Show first and last name
    Account Settings >> Display >> Teammate Name Display: Show first and last name

Here are the notifications I see from various devices. It looks like the channel name "Home Assistant" is showing up as I would expect, but when referencing the user (bot) it shows the username versus the First and Last name despite my settings. Not sure if this is as designed or a bug.

I am trying to replace Pushbullet for notifications, so I am trying to get it as close to that as possible haha. 
![Screenshot_20191117-212019](https://user-images.githubusercontent.com/3778687/69019862-80d30b80-0980-11ea-9fb5-da33e2292ffe.png)

Here are some other notification screenshots on different platforms. I guess I am just wondering how (if possible) to get "homeassistant" to change to "Home Assistant". 

## Android - Displayed lowercase username
![Android](https://user-images.githubusercontent.com/3778687/69019011-ce4d7980-097c-11ea-9fc3-b3a4fa6b9da0.png)

## Android from within Mattermost - Displayed First & Last Name
<img width="382" alt="iOS" src="https://user-images.githubusercontent.com/3778687/69019112-2edcb680-097d-11ea-999d-a85e97d18000.png">

## macOS Notification - Displayed First & Last but also included @
![Within Mattermost](https://user-images.githubusercontent.com/3778687/69019073-ffc64500-097c-11ea-82d2-ebe27247b0fd.png)

## iOS Noticiation - Displayed First & Last
![Notification](https://user-images.githubusercontent.com/3778687/69019499-e7efc080-097e-11ea-9d5e-656dc9591089.png)

Thanks!!

**Comment by amyblais** [comment]
What is the bot's Display Name set to in Main Menu > Integrations > Bot Accounts?

**Comment by dannyhanes** [comment]
![home_assistant_mattermost](https://user-images.githubusercontent.com/3778687/69343698-13eb9a00-0c3c-11ea-9b4c-b12f14930d7b.PNG)

**Comment by DHaussermann** [comment]
Hi @dannyhanes thanks for the report. I have tested this and cannot reproduce your issue. The bot display name is correctly showing for me in the push notification both for DMs (as in your screenshot) and for mentions in other channels.    

This may have been fixed in 5.17. There was a related issue where the bot display name was not appearing correctly on the mobile app channel bar. This was fixed with this Jira issue here: https://mattermost.atlassian.net/browse/MM-18331 

Is there anyway you can confirm if this is still occurring for you on 5.17? Also curious if you're seeing this on Android or iOS.

**Comment by dannyhanes** [comment]
@DHaussermann Hey, I apologize for the late reply. 

I just upgraded to 5.17.1 and pushed a new notification via webhook, and here is what I am seeing. 

### VERSION
<img width="608" alt="Screen Shot 2019-12-13 at 8 07 12 AM" src="https://user-images.githubusercontent.com/3778687/70802521-aa186900-1d7f-11ea-9c54-081c04fc15f7.png">

### ANDROID NOTIFICATION
![Android](https://user-images.githubusercontent.com/3778687/70802599-e055e880-1d7f-11ea-95e0-5db3a09de6dc.png)

### WEB 
<img width="326" alt="Screen Shot 2019-12-13 at 8 06 09 AM" src="https://user-images.githubusercontent.com/3778687/70802537-ba304880-1d7f-11ea-8740-9162c3c1505b.png">

**Comment by DHaussermann** [comment]
Hey @dannyhanes,

I did not know this when I replied to you but, the issue with bot display name not updating on mobile was not properly resolved. I filed a follow-up ticket here to address the renaming issue. https://mattermost.atlassian.net/browse/MM-21066

Can you tell me more about the web app screen? Are you seeing that updates to the bot display name are not properly showing on WebApp? I don't know of open issues where the bot display name shows incorrectly on WebApp. If you're also seeing an issue here I can try to reproduce it for you and create a ticket. 

Regarding the bot profile image not showing on the notification, I can make sure we have a story to capture this enhancement.

**Comment by dannyhanes** [comment]
@DHaussermann , 

So yeah, the web screenshot I provided is showing the name "homeassistant" instead of the display name "Home Assistant" . 

Also when I hover over the bot, I get the following information. Not sure if this is as intended or not. 

<img width="289" alt="Screen Shot 2019-12-13 at 8 06 16 AM" src="https://user-images.githubusercontent.com/3778687/70822470-9daa0580-1dab-11ea-8a3b-541500624f30.png">

And yeah, having the image show up in the notification would be great! Seeing the icon helps me know immediately if I need to react quickly (Zabbix) or check it later (Plex).

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity

**Comment by dannyhanes** [comment]
@DHaussermann Is there someplace where I can track the progress of the enhancement request to have the bot profile image show up in notifications?

**Comment by DHaussermann** [comment]
Hi @dannyhanes, sorry for the late reply. 
It's possible that the team working on mobile has already considered this but, I was unable to find a Story in our ticket tracker that discusses the feature. 

I have created a story for it here https://mattermost.atlassian.net/browse/MM-30348 to see if the team is taking this under consideration fir a future release.
