### ISSUE TITLE
[App Version 1.24.0 (Build 239)] German text in the push notification system needs a correction

### ISSUE THREAD

**Issue by Wikinaut** [mattermost/mattermost-mobile#3544]
A text inside the Push-Notification-System should be corrected, this text is apparently not part of the mattermost translation system (pls. correct me, if I am wrong):

The incorrect text is:
```Diesist eine Test-Push-Benachrichtigung```

and should be corrected to
```Dies ist eine Test-Push-Benachrichtigung.```

**Comment by amyblais** [comment]
@Wikinaut What mobile app version are you on?

It seems to be already translated here and I'm not sure why it shows wrong:
 - https://translate.mattermost.com/de/mattermost/translate/web_static.po#unit=509444
 - https://github.com/mattermost/mattermost-mobile/blob/master/assets/base/i18n/de.json#L305

**Comment by Wikinaut** [comment]
@amyblais You are right with your strings, I did *not* find them but these are mostly correct.
I would however suggest to add a "dot" at the end of the messages and already submitted a corresponding change on https://translate.mattermost.com/de/mattermost/translate/web_static.po#unit=509444 .

The Android App version is 

App Version 1.24.0 (Build 239)
Build hash is 533c7bb3e....
EE Buld hash is eb940617d

**Comment by enahum** [comment]
Going to close this issue as it hasn’t had any recent activity
