### ISSUE TITLE
Right side menu tries to slide open when sending a message

### ISSUE THREAD

**Issue by thejacer87** [mattermost/mattermost-mobile#358]
#### Summary
When I try to send a message, the right side menu tries to slide open.

#### Environment Information

- Device Name: Galaxy S6

#### Steps to reproduce
Try to send a message with fat fingers.

#### Expected behavior
Send the message.

#### Observed behavior
Right side menu tries to slide open

**Comment by cornifex** [comment]
Having the same issue. Skinny fingers and Galaxy S7 Edge.

**Comment by lfbrock** [comment]
Hi, thanks for the report!

I filed a ticket here on the issue - I think the swipe to open sidebars might be too sensitive right now. 

https://mattermost.atlassian.net/browse/PLT-5996

**Comment by lfbrock** [comment]
@thejacer87 @cornifex 

We moved the settings menu location to the left hand side, and adjusted the swipe gesture to be less sensitive, so hopefully this issue should be fixed now. 

If there's still problems, let us know!
