### ISSUE TITLE
Android, "Critical Error Occured" crash

### ISSUE THREAD

**Issue by paalbra** [mattermost/mattermost-mobile#3589]
#### Summary
Android app crashes at random.

#### Environment Information

- Device Name: Huawei P9, EVA-L09
- OS Version: Android 7.0
- Mattermost App Version: 1.25.0
- Mattermost Server Version: 5.17.0

#### Steps to reproduce
1. Use the app as normal
2. Close the app
3. Reopen the app

#### Expected behavior
No crashes.

#### Observed behavior
Sometimes the app has crashed. I haven't been able to see a pattern in the crashes, but I don't think I've seen it crash "live"/with the app open.

EDIT: I do believe it happens if I get a notification (private message or thread reply) with the app closed. I've at least managed to reproduce this behavior. It crashes instantly if I ask someone to PM me. If I'm on the Android "dashboard"/app-menu the app is opened with the error message.

Attaching two screenshots of the app after crash. I can't copy-paste the details as text, and I can't get/click the "11 more" at the end.

![error](https://user-images.githubusercontent.com/265215/69329858-207aed00-0c52-11ea-9944-4ffa1eb1e903.png)
![detail_merge](https://user-images.githubusercontent.com/265215/69329855-207aed00-0c52-11ea-990c-1a26cc0a2148.png)

**Comment by atikhonchuk** [comment]
We have errors too, two users send me notifications that they have this error at different devices by android 7

**Comment by atikhonchuk** [comment]
We cleared cache, reinstalled application, but problem wasn't decide

**Comment by atikhonchuk** [comment]
Device Name:  redmi note 4
OS Version: Android 7.0
Mattermost App Version: 1.25.0
Mattermost Server Version: 5.15.0

**Comment by amyblais** [comment]
Hi @paalbra, can you help test the fix that was done for this (https://github.com/mattermost/mattermost-mobile/pull/3590) on mobile app build number 247 (we don't have Android 7 to test the fix).

You can become a beta tester via https://play.google.com/apps/testing/com.mattermost.rnbeta.

**Comment by paalbra** [comment]
@amyblais Hey. I just installed Mattermost Beta, but it looks like I got build 245. Do I have to do something more to get the newer build or isn't it available through Google Play yet?

**Comment by amyblais** [comment]
I'll ask one of our product managers,

**Comment by amyblais** [comment]
One of our QAs was actually able to test the fix, so we'll be submitting 1.25.1 dot release to app stores soon.

**Comment by amyblais** [comment]
Closing this for now as 1.25.1 has been released,
