### ISSUE TITLE
json string of submission of checkbox element

### ISSUE THREAD

**Issue by swallowave** [mattermost/mattermost-mobile#3598]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
when submitting interactive dialog via android/ios app v1.25b245, the json string of submission of checkbox element expected to be json-bool or -null value e.g. ..,"element-name"=true/false/null,.. , but we got a regular json-string value like  ..,"element-name"="true", ..

#### Environment Information

- Device Name: 
- OS Version: Android 9  and iOS 12.1.4
- Mattermost App Version: android-1.25, ios-1.25  
- Mattermost Server Version: 5.17

#### Steps to reproduce
- build a dialog containing checkbox element
- then fire the dialog from button press 
- in dialog, check the checkbox to "checked" and submit
- intercept the http request content which is a json string , then check the value of "submission"."element-name" 

#### Expected behavior
- result shall be json-bool value true

#### Observed behavior
- result is json-string "true"

#### Possible fixes
- slightly change the http post logic to fix this bug

**Comment by hanzei** [comment]
Thanks for the report @swallowave :+1: 

I've observed this behaviour a while ago, but wasn't able to reproduce it. I will reopen our internal JIRA ticket for this and we will investigate. I might reach out you if I fail to reproduce the bug. You can find the ticket at https://mattermost.atlassian.net/browse/MM-17519

**Comment by swallowave** [comment]
1. submit from android/ios client v1.25
![Screenshot_20191204-110509_Mattermost](https://user-images.githubusercontent.com/7712032/70109263-5a061c00-1686-11ea-93e7-4d245095537b.jpg)
![20191204_104913](https://user-images.githubusercontent.com/7712032/70109323-802bbc00-1686-11ea-8474-5d0c7a5d00ba.jpg)

2. submit from android client "Mattermost Classic" or PC Browser
![Screenshot_20191204-110535_Mattermost Classic](https://user-images.githubusercontent.com/7712032/70109410-c1bc6700-1686-11ea-85f4-66d2e415ad05.jpg)
![20191204_105114](https://user-images.githubusercontent.com/7712032/70109453-e44e8000-1686-11ea-83d8-e4a686fd4e1e.jpg)

**Comment by amyblais** [comment]
Closing as this was fixed in v1.28,
