### ISSUE TITLE
iOS status bar height is zero

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#3606]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
The height becomes zero after closing the image preview screen.

#### Environment Information

- Device Name: iOS
- OS Version: 
- Mattermost App Version: 1.25.1
- Mattermost Server Version: 5.16

#### Steps to reproduce
1. Image click in channel
2. Click the download button in the upper right corner of the image preview screen
3. The save or cancel image modal window pops up.
4. Click 'Save Image' or 'Cancel' to return to the channel window.
5. You can see that the status bar is broken.

#### Expected behavior
The status bar height must be maintained.

#### Observed behavior

The screen below is a normal screen.
![image](https://user-images.githubusercontent.com/42505950/69612453-09356880-1073-11ea-90b9-d6b6ca01f5ce.png)

The screen below is a error screen.
![image](https://user-images.githubusercontent.com/42505950/69612788-c4f69800-1073-11ea-807a-3df30ce80036.png)

#### Possible fixes
'setHeaderAndFooterVisible' in image_preview.js.....maybe...

**Comment by amyblais** [comment]
A ticket was opened here: https://mattermost.atlassian.net/browse/MM-20673.

**Comment by bitdessert** [comment]
thanks :)
