### ISSUE TITLE
Android App unable to send image "dimensions (8000 by 6000 pixels) exceed the limits"

### ISSUE THREAD

**Issue by perphilip** [mattermost/mattermost-mobile#3630]
#### Summary
The Android app was unable to post an image to the Mattermost server, apparently the image dimensions were too large.

#### Environment Information

- Device Name: 
- OS Version: 
- Mattermost App Version: 
- Mattermost Server Version: 5.16.2

#### Steps to reproduce
Try to upload a large image in the Android App. In our case it was a photo taken on the phone with resolution 8000x6000 pixels and size 15,06 MB.

#### Expected behavior
The Android app should be able to post "any" image to the Mattermost server.

#### Observed behavior
The Android app was unable to post an image to the Mattermost server, apparently the image dimensions were too large, and the app just silently failed with not message. Uploading a smaller version of the image worked fine. When checking the server logs they stated:
 {"level":"error","ts":1574947715.8050857,"caller":"mlog/log.go:174","msg":"P_20191128_105204.jpg dimensions (8000 by 6000 pixels) exceed the limits","path":"/api/v4/files","request_id":"3tpu1rgi1jbh7y6wdesioychuo","ip_addr":"A.B.C.D","user_id":"N/A","method":"POST","err_where":"uploadFileTask","http_code":400,"err_details":""}

#### Possible fixes
-

**Comment by amyblais** [comment]
What Mattermost mobile app version are you on? What Android version are you on?

**Comment by Azazeal90** [comment]
Mattermost app version: 1.25.1
Device name: ROG_PhoneII
Android version: 9

**Comment by enahum** [comment]
Sorry but this is a server restriction that prevents images with those dimensions, I believe it was added about 2 years ago to prevent image bombs.

If I’m correct you won’t be able to upload the image with any client.

**Comment by Ashitaka57** [comment]
Any news on that https://mattermost.atlassian.net/browse/MM-10166 ?

**Comment by wojtekw92** [comment]
Hello :) 
Are there any news on MM-10166? A lot of new phones have now bigger resolution than 24Mpixels.

**Comment by schweigel** [comment]
Hi there,

I have the same problem with a resolution of 4312x5760px.
For me an option to optionally down scale the image would be great.

Thanks

**Comment by schweigel** [comment]
Hi,

are there any news about this issue?

**Comment by streamer45** [comment]
> Hi,
> 
> are there any news about this issue?

@schweigel 

Yes. We are working on bumping the maximum accepted resolution for uploaded images.

**Comment by jasonblais** [comment]
Quick update: we have an open PR that adds a new `FileSettings.MaxImageResolution` setting to allow admins to set a custom limit to the dimension of uploaded images. We also raise the default limit to 33MP (8K resolution) which seems like a good compromise that should cover most cases. 

https://github.com/mattermost/mattermost-server/pull/17941

It is now undergoing QA review.

**Comment by jasonblais** [comment]
The PR was merged and is scheduled for Mattermost v6.0, releasing on September 15.
