### ISSUE TITLE
Connexion with the beta takes more than a minute

### ISSUE THREAD

**Issue by GolfSierra** [mattermost/mattermost-mobile#3674]
#### Summary
Connexion with the beta takes more than a minute.

#### Environment Information
- Device Name: Android (same problem on several devices)
- OS Version: Android 9
- Mattermost App Version: 1.26 build 249
- Mattermost Server Version: 5.17.1

#### Steps to reproduce
launch the app on the mobile

#### Expected behavior
connection in less than 3 seconds (as all previous beta or even last stable version)

#### Observed behavior
logo splash screen without movment for more than a minute

#### Possible fixes
don't know

**Comment by urbels** [comment]
Same issue. Tried to clear data. First login was slow but successful but after that same issue with white screen again.

**Comment by amyblais** [comment]
Fix: https://github.com/mattermost/mattermost-mobile/pull/3677.

**Comment by amyblais** [comment]
Closing as build 250 has been released for beta testers,
