### ISSUE TITLE
Button for desktop notifications is called "email"

### ISSUE THREAD

**Issue by R0one** [mattermost/mattermost-mobile#3694]
#### Summary
The button for setting the desktop notifications settings is called "email address" and has an email icon.

#### Environment Information

- Device Name: Xiaomi Mi 9T
- OS Version: Android 9 PKQ1
- Mattermost App Version: 1.25.1 build 247
- Mattermost Server Version: 5.16.0

#### Steps to reproduce
(translated from french)
* three little dots menu on the top right
* settings
* notifications
* e-mail address
* send desktop notifications

#### Expected behavior
Replace the e-mail icon and label with something else like a "desktop" icon, and add a real setting for e-mail notifications.

#### Observed behavior
![image](https://user-images.githubusercontent.com/18699331/70707069-99acb380-1cd7-11ea-86e8-48d8c8b761a1.png)

![image](https://user-images.githubusercontent.com/18699331/70707044-8dc0f180-1cd7-11ea-95c5-6ebeda71990d.png)

**Comment by wget** [comment]
Hello everyone.

I checked on [our translation server](http://translate.mattermost.com/) and I haven't been able to locate a single string called `Email`even by filtering to the `.mobile` nodes.

![Screenshot_20191215-221509](https://user-images.githubusercontent.com/2997662/70869433-4793b880-1f8b-11ea-8b2f-ab6c8fd31b48.jpg)

**Comment by jasonblais** [comment]
@R0one thanks for your report. The setting you're referring to actually does refer to email notifications. You can configure your desktop notifications on your desktop or browser via **Account Settings > Notifications > Send desktop notifications**.

Let us know if this is helpful, happy to clarify if you have any questions.

**Comment by R0one** [comment]
As a matter of fact, I thought this menu was for setting desktop (web) notifications because of the only button that appeared: «envoyer des notifications de bureau» which translates to "send desktop notifications".

So it's actually this string that should be fixed to something like «envoyer des e-mails» or «envoyer des courriels».

But this issue is old that I'm not even sure this button still exists... I can't test right now (I no longer have an Android platform, but on iOS there is no issue).

**Comment by jasonblais** [comment]
@R0one Thank you, I appreciate it 👍  I suspect this was fixed some time between your initial report and today, as this setting should be consistent with Android and IOS. 

I'll close this as resolved, but it can always be reopened if a current Android user experiences the issue.

Thanks again!
