### ISSUE TITLE
GIFs not displaying

### ISSUE THREAD

**Issue by amberbahm** [mattermost/mattermost-mobile#370]
#### Summary
GIFs display as the url instead of the actual graphic.

#### Environment Information
- Device Name: iPhone 6
- OS Version: 10.2.1

#### Steps to reproduce
Send/receive a GIF

#### Expected behavior
Expect to see the actual annimated GIF

#### Observed behavior
Instead of the animated GIF I see "'Username' searched for example https://media......"

![img_8609](https://cloud.githubusercontent.com/assets/24656642/24119356/1481bd52-0d6e-11e7-8245-9af3ae2678f7.PNG)

**Comment by lfbrock** [comment]
Thanks @amberbahm - we haven't added support for that yet, I created a ticket here to track the feature: https://mattermost.atlassian.net/browse/PLT-6060

**Comment by enahum** [comment]
This should be solved by #790 once v1.3 is released, feel free to re-open this issue by then if you find any problems
