### ISSUE TITLE
F-droid version is not up to date

### ISSUE THREAD

**Issue by ahangarha** [mattermost/mattermost-mobile#3701]
The app on Fdroid is not up to date.

The classic version is for a year ago and the beta version ia for six month ago. This is while the beta version on Google Play Store has been published just two days ago!

Whatbis the issue?

**Comment by enahum** [comment]
hi @ahangarha thanks for the report. The builds on F-droid are completely managed and maintained by community members, Mattermost does not directly maintain F-droid. Not even sure who is the owner of that :S

**Comment by ahangarha** [comment]
Does that mean you have non-free components on your app which cannot be directly published on f-droid?

**Comment by enahum** [comment]
@ahangarha sadly we are using google services for notifications
