### ISSUE TITLE
Network request failed error remains on screen

### ISSUE THREAD

**Issue by amberbahm** [mattermost/mattermost-mobile#371]
#### Summary
The 'Network request failed' error message remains at the top of the screen even when the app is working and I am sending/receiving messages.

#### Environment Information
- Device Name: iPhone 6
- OS Version: 10.2.1

#### Expected behavior
When the app is working I would expect that error to disappear on it's own.

#### Observed behavior
Even when the app is working and I am sending and receiving messages, this error will remain there. It only disappears when I hit the 'x' on the right hand side.

![img_8611](https://cloud.githubusercontent.com/assets/24656642/24120429/db03e998-0d71-11e7-86df-1578ac28014d.PNG)

**Comment by lfbrock** [comment]
Hi @amberbahm - thanks for the report!

We have a ticket here to not show the network request error message and we'll do something else for disconnects https://mattermost.atlassian.net/browse/PLT-5967
