### ISSUE TITLE
Restarted Android app hangs with white screen when switching channels even on demo server

### ISSUE THREAD

**Issue by brettle** [mattermost/mattermost-mobile#3737]
#### Summary
Restarted Android app hangs with white screen when switching channels even on demo server

#### Environment Information

- Device Name: OnePlus 3T (ONEPLUS A3000)
- OS Version: Android 9, OxygenOS 9.0.6
- Mattermost App Version: 1.26.0 (Updated on 12/16/29, did not experience issue before update)
- Mattermost Server Version: 5.7.0 (demo.mattermost.com)

#### Steps to reproduce
How can we reproduce the issue?

 1. Using desktop browser: create account on demo.mattermost.com.
 2. On phone, uninstall Android Mattermost app and install 1.26.0.
 3. Using app, sign in to demo.mattermost.com server. Town Square channel displays fine.
 4. Run the Development demo. Switching between the Development channel and Town Square works fine at this point.
 5. Close the app either by restarting the phone or swiping the app away from within the app manager.
 6. Restart the app.
 7. Try to switch to the Development channel.

#### Expected behavior

The Development channel should display.

#### Observed behavior

A white screen is displayed and the app is hung. I can't switch channels. Restarting the app, force stopping the app, and/or clearing the app's cache all fail to resolve the issue. If I reinstall the app, it will start me in Town Square which displays properly, but if I try to switch to the Development channel, I still get the white screen.

#### Possible fixes

None at this time.

**Comment by philippedeoliveira** [comment]
I got the exact same issue with Samsung S6 on Android 7

**Comment by brettle** [comment]
I hear that the issue is with the server version. The latest version of the apps require server version 5.9 or higher. We'll be upgrading our local server this weekend to see if that resolves the problem for us. Someone should probably upgrade demo.mattermost.com.

**Comment by jasonblais** [comment]
Thanks both for your report. Given this impacts an older mobile version and an older server version, I'll close this issue.

If anyone else stumbles upon this issue, please review the changelog to review the compatible server versions for the mobile app you are running: https://docs.mattermost.com/deploy/mobile-app-changelog.html
