### ISSUE TITLE
Archive channel action is at the wrong position 

### ISSUE THREAD

**Issue by nebulade** [mattermost/mattermost-mobile#3778]
#### Summary
We have had a couple of accidental channel archive actions being performed, since the archive action on the Android (not sure about iOS) app is at the very bottom, while the leave channel action is at the bottom of the menu on the web application. This is even made more confusing with the menu item separator.

#### Expected behavior
Have consistency across clients to avoid accidental actions.

Web:
![mattermost_web](https://user-images.githubusercontent.com/646768/71880871-8273b100-3131-11ea-8671-683c65db1319.png)

Android:
![mattermost_android](https://user-images.githubusercontent.com/646768/71880922-9a4b3500-3131-11ea-90d9-545750fd303c.jpg)

**Comment by larkox** [comment]
@matthewbirtch This is an old ticket, but is still valid (the order is different between mobile and web). Is this lack of consistency intended, or something to look into?

**Comment by matthewbirtch** [comment]
In v2 we've placed the two destructive actions (Leave and Archive) together on the channel info modal. So, from that standpoint it's intentional. I wonder if it might make more sense to change the webapp to align with what we've proposed on mobile instead of the other way around.

**Comment by larkox** [comment]
@matthewbirtch looking again at this, I see the webapp updated this, but there is still some lack of consistency, since on web we show first archive and then leave, and on mobile we show leave and then archive. Not sure where you want to fix it (if you want to fix it at all) but let me know and we can create the ticket and/or close this issue.

**Comment by larkox** [comment]
Ticket created here https://mattermost.atlassian.net/browse/MM-49626
Since this is no longer a problem on mobile, I am closing this issue.
