### ISSUE TITLE
Message "Device must be secured with a passcode" when passcode is set (iOS)

### ISSUE THREAD

**Issue by till44** [mattermost/mattermost-mobile#3779]
#### Summary
Message "This device must be secured with a passcode to use Mattermost" appears on managed iOS device even though a passcode is set. (See screenshot)

![Image from iOS_](https://user-images.githubusercontent.com/1992143/71885087-eac69080-3139-11ea-836f-68c631bbf22b.png)

#### Environment Information

- Device Name: iPhone 7
- OS Version: 13.3 (managed)
- Mattermost App Version: 1.26.1
- Mattermost Server Version: 5.17.1

#### Steps to reproduce
1. Install Mattermost app 1.26.1 from the app store
2. Start app for the first time
3. leave app (switch to another or home screen) and return

#### Expected behavior
No message about passcode, app can be used.

#### Observed behavior
The message described above appears and blocks the use of the app.
MM behaves normally when opened for the first time after app-(re-)installation. The problem occurs when I open or switch into the app for the second time and persists until the next re-installation. I have a password and touchID set up. The phone was recently upgraded to iOS 13.3. It's a managed iPhone 7.

#### Possible fixes
Just guesses:
The issue appeared with https://github.com/mattermost/mattermost-mobile/releases/tag/v1.26.1
Possibly caused by this commit https://github.com/mattermost/mattermost-mobile/commit/cd5fb7168148914eb9e6d3f0a64fa854e55776f4
may be related to `react-native-local-auth` which uses `react-native-passcode-status` which uses `UIDevice-PasscodeStatus`.

**Comment by svelle** [comment]
Hi @till44
thanks for reporting this. A fix for this has already been merged into master.
See for more info: https://github.com/mattermost/mattermost-mobile/pull/3773

We're testing it today and hope to have it released to the app stores soon with a 1.26.1 dot release.

**Comment by till44** [comment]
Great, thank you! Looking forward to try the new release then.

**Comment by deepakpawar80** [comment]
> Hi @till44
> thanks for reporting this. A fix for this has already been merged into master.
> See for more info: #3773
> 
> We're testing it today and hope to have it released to the app stores soon with a 1.26.2 dot release.

Hey could you please let us know when new release will be available on app store?

**Comment by KarinBerg** [comment]
Can confirm that the bug is fixed in the Beta App :) if you need the fix fast, sign up for beta testing

**Comment by till44** [comment]
I confirm that 1.26.2 solves the issue. Thanks!

**Comment by deepakpawar80** [comment]
Hi,
Let me know this issue has been fixed and new app version has been released?

**Comment by deepakpawar80** [comment]
> I confirm that 1.26.2 solves the issue. Thanks!

Thanks for the update.
This version has been released for iOS ?

**Comment by svelle** [comment]
> > I confirm that 1.26.2 solves the issue. Thanks!
> 
> Thanks for the update.
> This version has been released for iOS ?

@deepakpawar80 Yes the version has been released to the app stores already. 
Alternatively you can also download the ipa file here: https://github.com/mattermost/mattermost-mobile/releases

**Comment by sksole** [comment]
Hi! Getting same error on iOS App version 1.41.0. The device and App is managed by MobileIron, and this happens after the device is remotely "unlocked". (PIN and Face ID reset). New PIN and Face ID has been set on the device many times, but the App still refuses to open. The App has been deleted and reinstalled to no help. It seems that the App is not able to register in the "Face ID & Passcode" list on the device.

iOS 14.4.1
 
![image](https://user-images.githubusercontent.com/80952397/111760672-455f8e80-889f-11eb-9d2a-80890e160e9d.png)
