### ISSUE TITLE
Mattermost is getting blocked by MobileIron on iOS devices

### ISSUE THREAD

**Issue by deepakpawar80** [mattermost/mattermost-mobile#3780]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Mattermost is getting blocked by MobileIron on iOS devices.
Please see the attached snapshots.
![Screenshot_2019-12-27-16-29-13-813_com whatsapp](https://user-images.githubusercontent.com/59564199/71891468-c20bbe80-316c-11ea-8380-938b3b32c995.jpg)
![Screenshot_2019-12-27-16-30-06-683_com whatsapp](https://user-images.githubusercontent.com/59564199/71891470-c2a45500-316c-11ea-9d8d-45f8cf6d20b5.jpg)
![Screenshot_2019-12-27-16-28-03-835_com whatsapp](https://user-images.githubusercontent.com/59564199/71891471-c2a45500-316c-11ea-9779-260ce8b87341.jpg)
![Screenshot_2019-12-27-16-28-39-215_com whatsapp](https://user-images.githubusercontent.com/59564199/71891472-c33ceb80-316c-11ea-916e-099b1f24f3ad.jpg)

#### Environment Information

- Device Name: iPhone
- OS Version: iOS
- Mattermost App Version: 
- Mattermost Server Version: 

#### Steps to reproduce
How can we reproduce the issue?
1) Install MobileIron on you iPhone
2) Then download mattermost from appstore and install
try to open 
3) you will get error

#### Expected behavior
Describe your issue in detail.
Mattermost is getting blocked by MobileIron on iOS devices.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
From last two weeks. All error snap shot attached.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by JtheBAB** [comment]
Sound like this: https://github.com/mattermost/mattermost-mobile/issues/3779#issuecomment-571512172

**Comment by enahum** [comment]
Fixed by https://github.com/mattermost/mattermost-mobile/pull/3773 and a new release will ship out soon

**Comment by deepakpawar80** [comment]
Please let me know what actions  have to take?
