### ISSUE TITLE
ToDO's checkboxes not shown

### ISSUE THREAD

**Issue by Allineer** [mattermost/mattermost-mobile#3811]
#### Summary

ToDO's checkboxes not shown in the last beta.

#### Environment Information

- Device Name: Xiaomi Mi9SE
- OS Version: 9 PKQ1.181121.001
- Mattermost App Version: 1.27.0 (Build  257)
- Mattermost Server Version: 5.18.0 EE

![image](https://user-images.githubusercontent.com/1168049/72343348-b6297a80-36df-11ea-9991-73f33fb6e4b6.png)

**Comment by amyblais** [comment]
Are you using the Todo plugin from here https://github.com/mattermost/mattermost-plugin-todo/issues? Would you like to open an issue in the repo?

Plugins are not yet supported on mobile apps, not sure if that might be related to this issue.

**Comment by Allineer** [comment]
@amyblais, no, I'not.
I talk about general message formatting - https://docs.mattermost.com/help/messaging/formatting-text.html

**Comment by amyblais** [comment]
Did you format the list the same way as in the example?

```
- [ ] Item one
- [ ] Item two
- [x] Completed item
```

**Comment by amyblais** [comment]
I'm able to reproduce this, @enahum do you know if this is supported on mobile?

**Comment by enahum** [comment]
@amyblais They should work without the * at the beginning, if I’m right the behavior is the same on the webapp.

**Comment by enahum** [comment]
Correction not supported on the mobile app.

@hmhealey can you confirm?

**Comment by Allineer** [comment]
> @amyblais They should work without the * at the beginning, if I’m right the behavior is the same on the webapp.

Some message from webapp:
![Screenshot_2020-01-16-09-22-22-275_com android chrome](https://user-images.githubusercontent.com/1168049/72499012-c8bbc500-3841-11ea-89e3-962167680b8b.jpg)

**Comment by enahum** [comment]
@Allineer https://github.com/mattermost/mattermost-mobile/issues/3811#issuecomment-574928535

**Comment by Allineer** [comment]
@enahum nice.

**Comment by hmhealey** [comment]
@enahum That's correct that we don't support them on mobile. There's a ticket to add that here: https://mattermost.atlassian.net/browse/MM-9375

**Comment by Allineer** [comment]
@hmhealey how about replacing checkboxes via some pictures/icons?

**Comment by hmhealey** [comment]
That would still fall under the ticket that I linked. Currently, the app can't even recognize which list items should contain checkboxes.
