### ISSUE TITLE
Timezone resets to GMT 0 after upgrading to 1.27.x

### ISSUE THREAD

**Issue by xRahul** [mattermost/mattermost-mobile#3846]
#### Summary
For the same server, when using the app 1.27.0 or 1.27.1, the timezone in the app resets to GMT 0. Thich changes all the displayed time to reflect that and give false date time.

#### Environment Information

- Device Name: Pixel 2 XL
- OS Version: Android 10
- Mattermost App Version: 1.27.0, 1.27.1
- Mattermost Server Version: 5.19.0

#### Steps to reproduce
How can we reproduce the issue?
Using the app is causing this issue. reverting back to 1.26.2 fixed it

#### Expected behavior
It should use the timezone I'm in to calculate the display date/time(GMT+8)

#### Observed behavior
Seeing the time reflected with GMT 0 instead of GMT+8 where I'm in

#### Possible fixes
Not sure.

**Comment by amyblais** [comment]
@xRahul Do you have the timezone setting enabled on your server https://docs.mattermost.com/administration/config-settings.html#timezone?

**Comment by saturninoabril** [comment]
@xRahul Thank you for the report.  Additional question for use to replicate the issue.  
- What's your timezone setting at Settings > Display > Timezone (auto/manual, timezone value)?  Did it change after upgrading to 1.27.x?  If yes, was it different from the webapp? 
- Could you share screenshots on the unexpected behavior you're seeing?

**Comment by xRahul** [comment]
@saturninoabril 
I do not actually see the timezone option int he app's settings. There's only Settings > Display > Clock Display that I can see.
I have recently upgraded the server from 4.7 to 5.19. Could it be due to some new settings we should set?

![Screenshot_20200124-110206](https://user-images.githubusercontent.com/1639945/73041631-1e9df780-3e56-11ea-95cd-32f497c1cb05.png)

**Comment by xRahul** [comment]
Found the setting to enable it in experimental features. Will check and confirm!

**Comment by xRahul** [comment]
Enabled it, but still not seeing it in the app. It looks like the issue is not there in the official app though, so could be something we are doing wrong in our fork and not getting. We DID recently upgrade directly from 4.x to 5.19, so there could be artifacts missing also.

I don't think this should be a concern in the main repo though. Thanks for letting me know about this setting! Closing the ticket now.

**Comment by saturninoabril** [comment]
I've seen you closed this issue but I'm curious if you could give a try to test whether the fix at https://github.com/mattermost/mattermost-mobile/pull/3861 solves your issue.  Here is the link for Android app in case you're interested to test - https://pr-builds.mattermost.com/mattermost-mobile/build-pr-3861/Mattermost_Beta.apk

**Comment by andreasarifin** [comment]
@saturninoabril I am having the same problem. After installing the beta app, I can confirm the issue is fixed.

**Comment by saturninoabril** [comment]
Thank you @andreasarifin!

**Comment by xRahul** [comment]
@saturninoabril I did try both the 1.27.1 and 1.27.0 and am facing this issue in them both. I'll wait for the next version release and check in that.
@andreasarifin which beta version did you install? From app store, or built from this repo?

**Comment by andreasarifin** [comment]
@xRahul it is the beta that @saturninoabril have shared in his comment.
