### ISSUE TITLE
iOS Keyboard hides bottom portion of chat history

### ISSUE THREAD

**Issue by fritojay** [mattermost/mattermost-mobile#3853]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
iOS Keyboard hides the bottom section of the chat history.

#### Environment Information

- Device Name: iPhone XS
- OS Version: 13.3
- Mattermost App Version: 1.27.1
- Mattermost Server Version: 5.17.1

#### Steps to reproduce
How can we reproduce the issue?
- Kill the Mattermost App in iOS
- Have someone send you a direct message
- Click the notification
- Click the chat box to reply

#### Expected behavior
Describe your issue in detail.
The iOS keyboard hides a portion of the chat history when replying to a direct message. This sometimes doesn't happen, but it has become more frequent. You have to either dismiss the keyboard to see the full history or you need to swap to a different chat and swap back to get it to do the expected behavior.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
Will attach a screenshot later.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
@fritojay We have this ticket open and aim to fix it for next release: https://mattermost.atlassian.net/browse/MM-21276.

**Comment by fritojay** [comment]
@amyblais that is great news! Thank you!

**Comment by amyblais** [comment]
This is scheduled to be fixed in v1.29,
