### ISSUE TITLE
Android 8 Oreo Missing notification preferences

### ISSUE THREAD

**Issue by kwantumhab** [mattermost/mattermost-mobile#3880]
#### Summary
On Android Oreo 8 there is no vibration or sound selection settings...

#### Environment Information

- Device Name: Xiaomi Redmi 5A
- OS Version: 8.1.0 OPM1.171019.026 - MIUI Global 11.0.2 | Sable 11.0.2.0(OCKMIXM)
- Mattermost App Version: 1.27.1 Build 260
- Mattermost Server Version: 5.19.0 Build 5.19.1

#### Steps to reproduce
On the mentioned android OS there is only 3 options in notifications: 
In Notifications ->Mobile:
- Send notifications
- Trigger push notifications
- Send me a test notify....

#### Expected behavior
There is missing the sound, vibration and sound selection menu items... on the same model on my wife's android 7 it is shown but not on the mentioned Oreo Android 8.

Also notifications are arriving but no sound/vibration at all!!

#### Observed behavior
There is no menu items where they should be.

Any advice or ideas would  be welcome.... :\

**Comment by enahum** [comment]
sorry @kwantumhab but those features are only available on Android 7, Android O and above those not have those features.

**Comment by enahum** [comment]
you can change those features in the notification settings on the phone specific to each app

**Comment by kwantumhab** [comment]
Thank you for your response. :D
