### ISSUE TITLE
Inline base64 image is not displaying in mobile app

### ISSUE THREAD

**Issue by sag1** [mattermost/mattermost-mobile#3881]
#### Summary
Markdown inline image source in base64 strips the base64 content.

#### Environment Information

- Device Name: Huawei P20
- OS Version: Android 9
- Mattermost App Version: 1.27.1 (Build 260)
- Mattermost Server Version: 5.17.0 (Build 5.17.1)

#### Steps to reproduce
How can we reproduce the issue?

Insert an image with inline source

![Photo](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/
2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy
MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCACFAGQDASIAAhEBAxEB/8QA
HAAAAQUBAQEAAAAAAAAAAAAAAAIDBAUGBwEI/8QAORAAAQMCBAQDBAkDBQAA)

#### Expected behavior
Display the image in mobile app

#### Observed behavior
Displays the raw content 

![Photo](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/
2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy
MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCACFAGQDASIAAhEBAxEB/8QA
HAAAAQUBAQEAAAAAAAAAAAAAAAIDBAUGBwEI/8QAORAAAQMCBAQDBAkDBQAA)

**Comment by amyblais** [comment]
This sounds similar to https://github.com/mattermost/mattermost-server/issues/9274
Does the workaround suggested by the community member [at the bottom of the issue thread](https://github.com/mattermost/mattermost-server/issues/9274#issuecomment-416897628) help?

**Comment by sag1** [comment]
In my case, there is no space before and after comma. You can see the content above

**Comment by amyblais** [comment]
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),
