### ISSUE TITLE
Mattermost plugins doesnt work on Mobile app

### ISSUE THREAD

**Issue by aminzafarghandi** [mattermost/mattermost-mobile#3883]
Dears,
Some mattermost plugins like voice message , jira and ... doesnt work on mobile app . 
Do you have any plan to resolve this issue . and if your answer is positive , what is your estimated time ?

#### Summary
Mattermost doesnt support some plugins like voice on mobile client

**Comment by amyblais** [comment]
Mobile plugins is a planned feature, but we don't yet have a specific timeline for it.

**Comment by split-brain-83** [comment]
I really appreciate your hard work on MM mobile and hope this will get resolved soon. All the best!

**Comment by Asgoret** [comment]
Same here( We got a lot of plugins, but non of them worked on mobile (jitsi\raven\todo\playbooks\etc)...

**Comment by larkox** [comment]
The plugin support is still limited on mobile. Slash commands, Interactive Dialogs and Interactive Messages do work on mobile, but anything that implies changes in the client side (adding buttons to the interface or custom dialogs for example) do not work.

Nevertheless, the Apps Framework (https://developers.mattermost.com/integrate/apps/) will be able to add more integration with mobile. This will be specially noted by the ability of apps to create buttons in the interface.
