### ISSUE TITLE
Inline custom emojis not displaying in portrait mode

### ISSUE THREAD

**Issue by Retrospector** [mattermost/mattermost-mobile#3886]
#### Summary
Custom Emojis aren't shown when used inline, work fine when posted as single message

#### Environment Information

- Device Names: Motorola G6 Plus (Android 9) Google Pixel 3 XL (Android 10)
- OS Versions: See above
- Mattermost App Version: 1.27.1 (Build 260)
- Mattermost Server Version: 5.17.3 (Gitlab Omnibus Installation)

#### Steps to reproduce
* add custom emoji
* have phone in portrait mode
* use it in a sentence or with another emoji ( i.e. "Hi, I'm :custom:!", ":custom::joy:")

#### Expected behavior
The custom emoji gets displayed

#### Observed behavior
In place of the emoji only empty space is displayed. When I flipped the phone in landscape mode, the emojis displayed, and also stayed after flipping back to portrait.

#### Possible fixes
Sadly not, I'm just a user and no programmer :smile:

**Comment by lindy65** [comment]
Thanks @Retrospector - I've reproduced your issue and have filed https://mattermost.atlassian.net/browse/MM-22379 to address the issue

**Comment by amyblais** [comment]
This is scheduled to be fixed in v1.29,
