### ISSUE TITLE
Android 10 has a gap on top

### ISSUE THREAD

**Issue by dns2utf8** [mattermost/mattermost-mobile#3920]
#### Summary
There is dead space in the beta and stable app on android 10.

#### Environment Information

- Device Name: Nokia 8.1
- OS Version: Android 10
- Mattermost App Version: Beta
- Mattermost Server Version: 5.16.5 - 5.19.0

#### Steps to reproduce
How can we reproduce the issue?

Install the app

![Screenshot_20200213-140050](https://user-images.githubusercontent.com/739070/74438234-f9574480-4e69-11ea-80d9-da80c7497bc4.png)

#### Expected behavior
Use all of the available screen.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
Don't know.

**Comment by dbrgn** [comment]
This does not happen on my Pixel 3a with Android 10 and the stable app (version 1.27.1).

**Comment by enahum** [comment]
@dbrgn just to confirm that nokia model has a notch at the top? Gotta love different manufacturers

**Comment by dns2utf8** [comment]
@enahum yes, this has a notch. To be precise it is a wide notch. Roughly 2/3 of the width.

**Comment by dns2utf8** [comment]
Do you think the nozzle detection is broken?

**Comment by philipreimer** [comment]
Same problem here. Also on a Nokia 8.1.

It seems to be a problem related to the notch because - although it does not show on the screenshot - on my screen the upper right and upper left corners of the white gap space are rounded. Just like they would be if they were at the top of the screen.

Android 10
Mattermost 1.30.1

**Comment by larkox** [comment]
Closing due to the age of the issue. If you still see this issue in the latest versions of the app, feel free to reopen it.

**Comment by dns2utf8** [comment]
It is fixed with Android 12, so ... :shrug:
