### ISSUE TITLE
The GIF image disappears.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#3948]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
The GIF image disappears on iOS app

#### Environment Information

- Device Name: iPhone XR
- OS Version: 13.3.1
- Mattermost App Version: 1.28.0
- Mattermost Server Version: 5.20.1

#### Steps to reproduce
Send Image (GIF) to someone.
Scroll Up
Scroll Down
The GIF image disappears
The image is not visible, but there is an image area.

#### Expected behavior
The image should not disappear regardless of scrolling.

#### Observed behavior

![giftest](https://user-images.githubusercontent.com/42505950/74993042-2c628f00-548d-11ea-92ce-0f5863707162.gif)

**Comment by enahum** [comment]
@bitdessert can you share more details? Is it a gif from a link? A file attachment? Do you happen to know if there is an image proxy running?

So far I’ve been unable to reproduce

**Comment by bitdessert** [comment]
A file attachment

**Comment by bitdessert** [comment]
@enahum Attach the recording.

**Comment by enahum** [comment]
Is this still happening?

**Comment by larkox** [comment]
@bitdessert Closing because of the age of the issue. If you are still seeing this issue in the latest versions, feel free to reopen it.
