### ISSUE TITLE
Why 'Refreshing messages failed. Pull up to try again.' always showing?

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#3949]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
After pressing the 'Mark as Unread'  button in a conversation, the following message is always displayed.
The message 'Refreshing messages failed. Pull up to try again.'  always appears at the top.

#### Environment Information

- Device Name: iPhone XR
- OS Version: 13.3.1
- Mattermost App Version: 1.28.0
- Mattermost Server Version: 5.20.1

#### Steps to reproduce
Press the 'Mark as Unread'  button in a conversation.
The message 'Refreshing messages failed. Pull up to try again.'  always appears at the top.

#### Expected behavior
The message should not always appear.

#### Observed behavior
Mattermost from App Store
-> The message does not appear.

Mattermost(IPA) from the source(But, change bundleID)
-> The message always appears.

**Comment by enahum** [comment]
Hi @bitdessert is there anything else modified other than the bundleID?

**Comment by bitdessert** [comment]
No. just BundleID changed

**Comment by larkox** [comment]
Closing because of the age of the issue. If you are seeing this in the latest versions, feel free to reopen the issue.
