### ISSUE TITLE
Downloaded files on Android have the words `download successful` appended to their filenames

### ISSUE THREAD

**Issue by jbohren** [mattermost/mattermost-mobile#3959]
#### Summary
Downloaded files on Android have the words `download successful` appended to their filenames, which prevents file type identification from extension, and thereby prevents the file from being opened until it is renamed in the file manager.

#### Environment Information

Server Version: 5.19.0 (Build 5.19.1)
App Version: 1.28.0 (Build 268)
App Platform: android

#### Steps to reproduce
- Download an attachment from within the app

#### Expected behavior
Describe your issue in detail.

#### Observed behavior
Downloaded files on Android have the words `download successful` appended to their filenames *after* the extension.

#### Possible fixes
It's possible that the filename is not getting unpacked correctly:
https://github.com/mattermost/mattermost-mobile/blob/9096818003017c5ab97f5e1ec3cf14a89b6ba309/app/screens/image_preview/downloader.android.js#L65

**Comment by amyblais** [comment]
https://mattermost.atlassian.net/browse/MM-22687

**Comment by jbohren** [comment]
@hahmadia @migbot was this fixed in #3646?
https://github.com/mattermost/mattermost-mobile/pull/3646/commits/16f306d20410f77c48986796449a9a6cf9f6beb5

**Comment by hahmadia** [comment]
> @hahmadia @migbot was this fixed in #3646?
> [16f306d](https://github.com/mattermost/mattermost-mobile/commit/16f306d20410f77c48986796449a9a6cf9f6beb5)

@jbohren 
Hey! It doesn't seem that fixed the problem you had described. 
I have created a PR to fix this problem here https://github.com/mattermost/mattermost-mobile/pull/3970

**Comment by amyblais** [comment]
This is scheduled to be fixed in v1.29,
