### ISSUE TITLE
Sidebar swiping doesn't register all of the times

### ISSUE THREAD

**Issue by svelle** [mattermost/mattermost-mobile#3965]
>My beta mobile client shows 1.29.0 (build 271), and the behavior is improved - I can't get it to stick. The hit zone and angle for the pull out remains quite small though - most of the time I fail to swipe out the menu on my first attempt (and end up scrolling instead), then have to readjust my initial touch to the first couple of pixels on the left edge of the screen and be sure the resulting swipe is almost perfectly horizontal. This is rather uncomfortable when using my right thumb, as it requires me to reach effectively beyond the left end of the phone to start the swipe, and I have to fight the natural sleight upward arc of the thumb. Is there any plan to improve that?

_Originally posted by @cheald in https://github.com/mattermost/mattermost-mobile/issues/2897#issuecomment-591445540_

**Comment by svelle** [comment]
@cheald could you give a bit more info on what device you're seeing this on?

Device name and manufacturer as well as the OS version would be greatly appreciated.

I've also went ahead and tested this on my pixel 3 using all three of the available navigation methods and I can see some of the pain points you're describing:

- 3 buttons: sidebar slides out everytime, direction irrelevant
- 2 buttons: sidebar slides out 99% of times, was registered once as slide up by system
- full gesture nav: almost impossible to slide out navbar but this problem is [acknowledged by google](https://developer.android.com/training/gestures/gesturenav#back-gestures) and requires some more in-depth work on the used sidebar library by wix

**Comment by cheald** [comment]
This is on a Google Pixel 3 XL, Android 10, latest patches.

Here's a video showing two of the issues: https://drive.google.com/open?id=110utFNqnxtH0wv3EeqZg0A6mY0YlInnN

I show the gesture in Mattermost build 271, as well as Slack, for comparison.

1. The pullout is highly sensitive to *any* vertical movement in the initial part of the swipe. The first half inch or so has to be just nearly perfectly horizontal, or the drawer doesn't move, and instead a scroll event is registered.
2. Taking too long to swipe out results in a long-press registering on the element under the finger, which pops up the context menu over the sidebar menu. I wasn't able to reproduce this in Slack - either the menu slides out, or the long press registers, but never both.

These two issues combine to cause some frustration; I find myself swiping slowly and more deliberately to avoid the gesture from being read as a scroll, but if it's TOO slow then I pop up a context menu in addition to the sidebar, which then has to be dismissed before I can proceed.

The sticky sidebar problem going away has massively improved the experience, but if I can get the sidebar menu to come out regularly first try, it'll be even better! Let me know if I can provide more detailed information.

**Comment by svelle** [comment]
Fantastic, very helpful.

Just one more question. Which of the navigation options are you using? See image below.

![image](https://user-images.githubusercontent.com/7526550/75363138-fd4b8380-58b9-11ea-8eb4-daba77d4b9f7.png)

**Comment by cheald** [comment]
I'm currently using 2-button navigation.

**Comment by svelle** [comment]
> I'm currently using 2-button navigation.

Thanks, if that's the case even more of a reason to further look into this IMO.
