### ISSUE TITLE
Keyboard hides the message window

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost-mobile#3972]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Have anyone had the same experience? This problem only occurs on iOS devices. Reproduction methods are not clear, but often appear.  The keyboard hides the message window.

My friends using iPhone have a common experience. This problem also occurs in latest version. For solve it, restart Mattermost Mobile App or restart message. 

#### Environment Information
- Device Name: iPhone 11Pro, 11ProMax, 7, XR
- OS Version: 13.3.1 (7 is 13.1)
- Mattermost App Version: 1.28.0
- Mattermost Server Version: 5.20.1

#### Steps to reproduce
I don't know.  :( Please check video files below.

[Recorded Video #1](https://s3-ap-northeast-1.amazonaws.com/npd.mtglobalcdn.com/i/messagebox_case_01.gif)

[Recorded Video #2](https://s3-ap-northeast-1.amazonaws.com/npd.mtglobalcdn.com/i/messagebox_case_02.gif)

**Comment by enahum** [comment]
@Gloriashield fix for this https://github.com/mattermost/mattermost-mobile/pull/3921

**Comment by Gloriashield** [comment]
@enahum Thank you very much! If 1.29 will released, I will try it! Have a nice day!

**Comment by Gloriashield** [comment]
I applied Patch(patches/react-native-keyboard-tracking-view+5.6.1.patch) to Mobile App version 1.29. Previous problem was confirmed to be solved. Thank you.

However, a new problem occurred.

1. Send a message.
2. Sometimes scroll doesn't go up.
3. I must pull up the screen.

Fortunately, it doesn't have to be restarted. Please watch attachment video file 🗡 

[Recorded Video #3](https://s3-ap-northeast-1.amazonaws.com/npd.mtglobalcdn.com/i/messagebox_case_03.gif)

Best regards,
KIM

**Comment by enahum** [comment]
Hour third video is about the jira ticket I posted.

Note the following, before You receive the message, there is a `user is typing...` indicator above the text input area which animates up and down.

This animation behavior results in the post list changing its dimensions and conflicting with keeping the scroll position when new elements are added.

To confirm, please wait until the `user is typing...` disappears before sending the post.

**Comment by Gloriashield** [comment]
@enahum , Thank you for your prompt reply.

1. My friend typed a message to me.
2. Wait for "user is typing ..." to disappear.
3. He pressed a Send Message button.
4. The screen was still frozen.
5. I tried several times but it was the same.


However, if I turned off "Enable User Typing Messages" function, no problem. (wow!) I think that this is very useful function to everyone. Please do not give up this function.

Have a nice day!
KIM
