### ISSUE TITLE
[Android] App crashes after entering server url

### ISSUE THREAD

**Issue by Matmo10** [mattermost/mattermost-mobile#401]
#### Summary
The app "stops", aka crashes, after entering the server url.

#### Environment Information

- Device Name: Nexus 6
- OS Version: 7.1.1
- Mattermost App Version: 1.0
- Mattermost Server Version: 3.7.3

![screenshot_20170326-105858](https://cloud.githubusercontent.com/assets/2548215/24333833/36bf8b92-1214-11e7-9d3a-8beaeb95097b.png)

**Comment by lfbrock** [comment]
Hi @Matmo10 - thanks for the report! I think the issue should be fixed now, we just cut Build 20 which should fix the issue

**Comment by Matmo10** [comment]
Just updated - my app no longer crashes, it just says it can't connect now. The old app connects fine though to the same server.
