### ISSUE TITLE
Answering via notification makes future notification not get shown

### ISSUE THREAD

**Issue by pflanzenandi** [mattermost/mattermost-mobile#4020]
When answering an incoming message via notification (heads up), future replies of this specific recipient are not shown (no notifications), but log shows that they are pushed. Same happens when answering via GSconnect on Ubuntu.

- Device Name: MotoG5 plus
- OS Version: Android 9
- Mattermost App Version: 1.28.0
- Mattermost Server Version: 5.20.0

**Comment by amyblais** [comment]
@pflanzenandi Do you still experience this issue on v1.29.0?

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
