### ISSUE TITLE
Emoji picker selects wrong emoji. Possible off-by-one error?

### ISSUE THREAD

**Issue by th-joerger** [mattermost/mattermost-mobile#4039]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Emoji picker possible of by one error?

#### Environment Information

- Device Name: LG G7 ThinQ
- OS Version: Android 9, Kernel 4.9.112
- Mattermost App Version: 1.29.0 (Build 276)
- Mattermost Server Version: 5.19.0 (Build 5.19.1)

#### Steps to reproduce
- Start in a channel to type ``:shru``
- Auto-completion suggests emojis:
    - ``:man_shrugging:``
    - ``:woman_shrugging:``
    - ``:construction:``
    - etc ...
- Select ``:man_shrugging:`` by tapping on it
- ``:woman_shrugging:`` is displayed in edit bar

#### Expected behavior
- Take the emoji selected

#### Observed behavior
- Wrong emoji selected

#### Possible fixes
- None

#### Demo
![20200317_124501](https://user-images.githubusercontent.com/30830429/76853379-6e44e200-684d-11ea-88a5-72522995f133.gif)

**Comment by enahum** [comment]
Fix submitted
