### ISSUE TITLE
mattermost-mobile  configuration for windows 10

### ISSUE THREAD

**Issue by santoshzp** [mattermost/mattermost-mobile#404]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

how to setup mattermost-mobile on windows 10 machinse

#### Environment Information

- Device Name:  Lenovo ThinkPad
- OS Version: windows 10 pro
- Mattermost App Version: 
- Mattermost Server Version:

npm ERR! mattermost-redux@0.0.1 postinstall: `npm run build && mv lib/* ./ && rm -rf src lib`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mattermost-redux@0.0.1 postinstall script 'npm run build && mv lib/* ./ && rm -rf src lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mattermost-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && mv lib/* ./ && rm -rf src lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mattermost-redux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mattermost-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\mattermost-mobile-master\npm-debug.log

**Comment by enahum** [comment]
Can you try with [Cygwin](http://testingfreak.com/run-unixlinux-commands-in-windows/) to see if that helps?

**Comment by af913337456** [comment]
have you fix it?

**Comment by enahum** [comment]
yeah this should be working now

**Comment by enahum** [comment]
This thread has been inactive for a while, please feel free to re-open if needed

**Comment by rAnAaRsl** [comment]
how to do it with Cygwin ?
