### ISSUE TITLE
Almost evebody is called 'Someone' in 1.28.0

### ISSUE THREAD

**Issue by PanderMusubi** [mattermost/mattermost-mobile#4043]
#3968 ## Summary
Almost evebody is called 'Someone' since 1.28.0

#### Environment Information
- Mattermost App version: 1.28.0 via F-Droid

#### Steps to reproduce
Simply watch a chat

#### Expected behavior
Profile names are shown, like was before

#### Observed behavior

![IMG_20200318_081011](https://user-images.githubusercontent.com/198964/76934820-2d51d980-68f0-11ea-86a9-ef28305c8806.jpg)

**Comment by xRahul** [comment]
Working for me. Can you update the server you're using? Check what data is being returned? This looks like a fallback to me in case names are not there in the data

**Comment by PanderMusubi** [comment]
It works with the previous version of Mattermost beta and the current version of Mattermost classic.

Using Mattermost Enterprise Edition 5.7.0

**Comment by amyblais** [comment]
@PanderMusubi Would you be open to upgrading your server version to the latest (v5.21.0)? v5.7.0 is not a supported version anymore.

**Comment by PanderMusubi** [comment]
I'm not in control of the server but I can ask.

**Comment by PanderMusubi** [comment]
Server will be upgraded and I will retest. Will post result in here a few days. Thanks.

**Comment by esethna** [comment]
@PanderMusubi please also help upgrade to the latest mobile app version v1.29.0

**Comment by NaeiKinDus** [comment]
> @PanderMusubi please also help upgrade to the latest mobile app version v1.29.0

FYI the F-Droid repo does not have the v1.29.0 yet.

**Comment by PanderMusubi** [comment]
Build is requested at https://gitlab.com/fdroid/fdroiddata/-/issues/1987 Will report back when 1.29.0 is installed and our server has been upgraded.

**Comment by ATranDev** [comment]
When I click on an image, I do not display a detailed image. I'm checking the latest version, commit 3013 - Bump app build number to 280 (# 4139)

**Comment by PanderMusubi** [comment]
Can't retest as https://github.com/mattermost/mattermost-mobile/issues/4146 is blocking

**Comment by licaon-kter** [comment]
1.31.2 does not help?

**Comment by PanderMusubi** [comment]
Fxied, thanks
