### ISSUE TITLE
F-Droid Cannot send messages in 1.28.0

### ISSUE THREAD

**Issue by PanderMusubi** [mattermost/mattermost-mobile#4044]
#### Summary
Sending messages does not work  anymore

#### Environment Information
- Mattermost App Version: 1.28.0 via F-Droid

#### Steps to reproduce
Send a message 

#### Expected behavior
Send messages

#### Observed behavior
Message is not send, is shown only in gray with red exclamation mark in circle. Try again does not work.

**Comment by PanderMusubi** [comment]
At the moment discussed in https://github.com/mattermost/mattermost-mobile/issues/4043

**Comment by ilippert** [comment]
I confirm this behaviour.

**Comment by licaon-kter** [comment]
@PanderMusubi This was not fixed in the latest available version in F-Droid?

**Comment by ilippert** [comment]
I confirm this issue seems to be fixed.

**Comment by larkox** [comment]
Closing this issue since it seems to be fixed.
