### ISSUE TITLE
Images not shown in 1.28.0

### ISSUE THREAD

**Issue by PanderMusubi** [mattermost/mattermost-mobile#4045]
#### Summary
Images are not shown

#### Environment Information
- Mattermost App Version: 1.28.0 via F-Droid

#### Steps to reproduce
View chat with images

#### Expected behavior
Images are shown.

#### Observed behavior

![Screenshot_20200318-082045_Mattermost_Beta](https://user-images.githubusercontent.com/198964/76935469-735b6d00-68f1-11ea-861a-b240894cba88.png)

**Comment by PanderMusubi** [comment]
At the moment discussed in https://github.com/mattermost/mattermost-mobile/issues/4043

**Comment by AiTranXuan** [comment]
When I click on an image, I do not display a detailed image. I'm checking the latest version, commit 3013 - Bump app build number to 280 (# 4139)
![ezgif-4-1be578b93c6b](https://user-images.githubusercontent.com/15552410/78956127-8980d580-7b0b-11ea-889c-7b1f5c29567a.gif)

**Comment by lkraav** [comment]
On 1.29.0, app reinstall helped restore image display. Maybe cache clear would've worked but I forgot to try it first.

**Comment by PanderMusubi** [comment]
Can't retest as https://github.com/mattermost/mattermost-mobile/issues/4146 is blocking

**Comment by licaon-kter** [comment]
1.31.2 does not help?

**Comment by PanderMusubi** [comment]
Fxied, thanks
