### ISSUE TITLE
Markdown Code syntax highlighting does not work

### ISSUE THREAD

**Issue by euschn** [mattermost/mattermost-mobile#4056]
#### Summary
Syntax highlighting in Markdown code blocks does not work.

#### Environment Information

- Device Name: 
- OS Version: Android 9
- Mattermost App Version: 1.29.0 (Build 276)
- Mattermost Server Version: 5.17.0

#### Steps to reproduce
1.  Post a message with a syntax highlighted code snippet, e.g.:
``` java
public static void main(String[] args) {
  int x = 5;
   System.out.print.ln("hi");
}
```
2. Observe that in the browser client, the code is properly highlighted/colored
3. Observe that in the mobile client, there is no syntax highlighting

#### Expected behavior
The code block should have syntax highlighting.

**Comment by enahum** [comment]
Last time I tried to add syntax highlight feature it was terribly slow, specially on Android, so for now it won’t be added

**Comment by euschn** [comment]
Too bad. Any insights on why it was slow?

**Comment by dbogatov** [comment]
Slack seems to support it.
So it is possible to do in a right way (i.e. without performance degrade).

**Comment by enahum** [comment]
@dbogatov slack uses a totally different technology and approach. Can you think of alternatives on how to do this?

**Comment by karantin2020** [comment]
Hello. Is there any way to add syntax highlight to mobile version? It is very useful. May be need help?

**Comment by enahum** [comment]
@karantin2020 help is always appreciated :)

**Comment by larkox** [comment]
Closing as this should be already solved on V2.
