### ISSUE TITLE
Android app cannot connect to self-signed https/ssl/tls enabled server

### ISSUE THREAD

**Issue by Pavel-Sayekat** [mattermost/mattermost-mobile#4068]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Android app cannot connect to https/tls enable serverAndroid app cannot connect to https/tls enable server

#### Environment Information

- Device Name:  Android
- OS Version: 10
- Mattermost App Version: 1.29.0
- Mattermost Server Version: 5.21.0, 5.20.2

#### Steps to reproduce
Run a local mattermost instance, enable self-signed SSL/TLS certificate and add to the server in the "System Console" -> "web server" options and restart the service, mattermost will run on secure mode, if the port is 80 or 443 or even 8065, the android app cannot connect but it does connect on different port on insecure mode, I have tested that for port 8066, it connects.

#### Expected behavior
The android app should try to connect to the server and can offer choice or at least describe the issue as like web browsers.

#### Observed behavior
The android app does not connect and does not says what's the issue

#### Possible fixes
I don't know, up to you, you can chose not to fix or not adding this as a feature.

**Comment by enahum** [comment]
Self sign certs are not supported as specified in the changelog https://github.com/mattermost/mattermost-mobile/blob/master/CHANGELOG.md
