### ISSUE TITLE
After editing the message, the keypad does not disappear.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4070]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
After editing the message, the keypad does not disappear.

#### Environment Information

- Device Name: Android 
- OS Version: 
- Mattermost App Version: 1.29.0
- Mattermost Server Version: 5.21.0

#### Steps to reproduce
1. Send a message to someone
2. Edit the message you just sent.
3. Save after modification.

#### Expected behavior
After saving, the keypad should disappear.

#### Observed behavior
After saving, the keypad is popped up. 
The keypad does not disappear when I press the sidebar.

**Comment by amyblais** [comment]
@bitdessert Which Android version are you on?

**Comment by bitdessert** [comment]
What I tested was the Android 9 version, but I expect it to happen on other Androids as well.

**Comment by bitdessert** [comment]
@amyblais What I tested was the Android 9 version, but I expect it to happen on other Androids as well.

**Comment by lindy65** [comment]
Thanks for the report @bitdessert - I've reproduced your issue and have filed https://mattermost.atlassian.net/browse/MM-23609 to track.

**Comment by amyblais** [comment]
This was fixed for v1.31,
