### ISSUE TITLE
Android 10 Gesture Navigation Conflicts with Drawer

### ISSUE THREAD

**Issue by jrtberlin** [mattermost/mattermost-mobile#4117]
#### Summary
The Android 10 "back" gesture conflicts with the swipe gesture to open the channel drawer. This situation results in accidental app closes. 
The GIF shows the situation and a workaround (angled swipe):

<img src="https://user-images.githubusercontent.com/14153182/78338644-6d24ec00-7593-11ea-892a-b7847cc83b44.gif" alt="mattermost_android10_gestures" width="auto" height="500">

#### Environment Information

- Device Name: OnePlus 6t (fajita)
- OS Version: Android 10 (Lineage 17.1)
- Mattermost App Version: 1.30.0

#### Steps to reproduce
On Android 10 try to open the drawer with the swipe gesture.

#### Expected behavior
Swiping from the left edge should open the channel drawer.

#### Possible fixes
There are two possible improvements:

1. [setSystemGestureExclusionRects](https://developer.android.com/reference/android/view/View#setSystemGestureExclusionRects(java.util.List%3Candroid.graphics.Rect%3E)) for the side where the drawer is.

> Use this to tell the system which specific sub-areas of a view need to receive gesture input in order to function correctly in the presence of global system gestures that may conflict. For example, [...] a view such as a navigation drawer container can mark the left (or starting) edge of itself as requiring gesture capture priority using this API.

2. More recent phones are bigger and have a taller aspect ratio. If it is expected to use the button to open the drawer, the action bar should move to the bottom of the screen. (Users can read text on top, but not reach the top for interaction)

**Comment by enahum** [comment]
Hi @jrtberlin this is a know issue and sadly so far we haven't been able to do anything about this, would you be willing an try and contribute in order to fix it?

**Comment by jrtberlin** [comment]
@enahum Sorry, I dislike working with react native.
I thought that this should be documented publicly. Can you point into a component where changes are required? Maybe someone else picks this up.

**Comment by enahum** [comment]
No worries at all @jrtberlin thanks for bringing this up.

Initial work should be done in the dependency library  [react-native-navigation](https://github.com/wix/react-native-navigation) and then either submit a PR to that repo or patch it locally (preferably the former) then apply the needed changes in the mattermost app (update the dependency or apply the patch / Modify the navigation actions as needed in `app/actions/navigation`

**Comment by francislavoie** [comment]
Can another look be taken at this? Mattermost is practically unusable because of this issue when gesture navigation is enabled.

Other apps like Slack allow for the entire content view to be right-awipeable to open the navigation drawer. If mattermost did the same, it would completely resolve the problem. Right now, nothing at all happens when right-swiping in the middle of the screen, so it would only be beneficial.

**Comment by larkox** [comment]
Closing as this should not be applicable to V2.
