### ISSUE TITLE
Connection only possible to the first DNS-names, mentioned in Let's Encrypt certificate

### ISSUE THREAD

**Issue by Hartwin2342** [mattermost/mattermost-mobile#4119]
#### Summary
If a server key is signed by Let's Encrypt for more than one alterantive names (DNS-name), the android app will only connect successfully to the first mentioned alternative.

#### Environment Information

- Device Name: Samsung SM-T825
- OS Version: Kernel 3.18.115-17011592
- Mattermost App Version: 1.29.0
- Mattermost Server Version: 5.21.0

#### Steps to reproduce
* Create Server Key for two different third level domains of the same second level domain
* Let it be signed by Let's Encrypt
* deploy this to the mattermost server
* check for any problems of the cert with some of the well known webservices
* Try to connect the android app to the second DNS-name (it says something like could not connect to server, please check internet connection)
* Try to connect the android app to the first DNS-name (it works)
* Try to connect to the second DNS-name by webbrowser (it works)
* Try to connect to the first DNS-name by webbrowser (it works)

#### Expected behavior
The android app should be able to connect properly to all the DNS-names used as alternatives in server keys and certs. Not only to the first one.

#### Observed behavior
The android app only connects to the first of many DNS-names, used as alternatives in server keys and their certs. If you try to connect to an other valid DNS-name, there will be an error "Cannot connect to the server. Please check your server URL and internet connection."

Every ssl-checking service I tryed, told me there is no problem with this certificate.
All the browsers are able to connect and login to both DNS-names.
The windows desktop app is able to connect to both of the DNS-names.

**Comment by enahum** [comment]
Thanks for the report @Hartwin2342 

So checking the cert for primary and secondary domains return valid results, no broken chains and all good? How is the cert setup? Is it a cert with multiple domains or a multiple domain server with each domain holding its own cert? Just want to make sure I fully understand.

We are actively working on https://mattermost.atlassian.net/browse/MM-18642 but it has proven to be challenging so no specific deadline is set, target version is 1.31 or 1.32

**Comment by Hartwin2342** [comment]
> So checking the cert for primary and secondary domains return valid results, no broken chains and all good?

Try it:

https://1u1-office.trust-on.net:10117
https://mm.trust-on.net:10117

Both URLs seeing the same mattermost instance with the same key and cert.

> How is the cert setup? Is it a cert with multiple domains or a multiple domain server with each domain holding its own cert? Just want to make sure I fully understand.

It is a cert  with multiple domains. The mentioned URLs  are in the same order like DNS-names in the cert.

**Comment by enahum** [comment]
@Hartwin2342 both domains are working fine for me.
![DNS-names](https://user-images.githubusercontent.com/6757047/78671111-d87cff80-78ac-11ea-9c24-2b1ea9fd856e.gif)

**Comment by Hartwin2342** [comment]
Maybe the setup was an older one. The described problem was reported to me as a screenshot at the 15th of march. Maybe the mattermost android client was 1.28.0 or even 1.27.1. Maybe the adroid version was somewhat to old because the tablet was older than 3 years.
Using a brand new tablet (got yesterday, newest android) and mattermost client 1.29.0, I got the same result like @enahum
