### ISSUE TITLE
Beta App repeatedly requires user login

### ISSUE THREAD

**Issue by jonasdagefoerde** [mattermost/mattermost-mobile#4184]
#### Summary
Beta App requires me to login several times per day

#### Environment Information

- Device Name: iPhone 6s
- OS Version: 13.4.1
- Mattermost App Version: 1.30.0 (Build 282)
- Mattermost Server Version: 5.21.0

#### Steps to reproduce
1. Use the app
2. keep it in background for some time
3. open app again

May be it is important that I use the official MM App as well to login to another server. 

#### Expected behavior
It is a basic feat that the app keeps the login data. 

#### Observed behavior
Repeated server address entry and user login required. 

#### Possible fixes
Store server address and user credentials :)

**Comment by enahum** [comment]
@johnsenner please do upgrade to build 285

**Comment by enahum** [comment]
Closing this issue as this was resolved before release was published

**Comment by jonasdagefoerde** [comment]
How can I install Build 285? I checked for updates and reinstalled the beta app but only get 282.

**Comment by amyblais** [comment]
Sorry, I've published build 285 to Testflight now.

**Comment by sadamht** [comment]
hello @enahum  and @amyblais  i'am facing same issue

Environment Information
Device Name: iPhone XR & iPhone 6
OS Version: 13.5.
Mattermost App Version: 1.31.1
Mattermost Server Version: -
Steps to reproduce
Use the app
keep it in background for some time or closed the app
open app again

**Comment by enahum** [comment]
@sadamht are you using a custom build? or the one in the stores ?
