### ISSUE TITLE
All channels are showing as read only since v1.30.0

### ISSUE THREAD

**Issue by svanesveld** [mattermost/mattermost-mobile#4185]
#### Summary
Since version 1.30.0 was installed on my phone, all Mattermost channels are shown as read-only "This channel is read-only". I have confirmed with others that this is not unique to my phone.

#### Environment Information

- Device Name: Xiaomi Mi 9 Lite
- OS Version: 10 QKQ1.190828.002
- Mattermost App Version: 1.30.0
- Mattermost Server Version: 4.4.0

**Comment by amyblais** [comment]
@svanesveld Would you be open to upgrading your server version to a more recent version? Our supported server versions include v5.19.0 or later.

**Comment by svanesveld** [comment]
@amyblais Thanks for the quick response. Unfortunately I don't own the server side installation, so that's not possible at this moment. I'll forward the suggestion to the administrator. I've downgraded to v1.29.0 which resolved it for now. Might still be worth to check which particular changes would've broke this for older server versions? My hunch is it's related to pull request [#3904](https://github.com/mattermost/mattermost-mobile/commit/fbd7fedfbc5078138f453ae3ed20965ae9a73980)

**Comment by josexlito** [comment]
In our company have Mattermost Server 4.2.0 and Mattermost Mobile 1.30.0 (similar that @svanesveld mentioned), and my team have the same problem. The only solution that works are downgrade the app to 1.29.0.

What server version do you think will work properly with the lastest version of Mattermost mobile app?

**Comment by amyblais** [comment]
We support versions v5.19+,
 - https://github.com/mattermost/mattermost-mobile#mattermost-mobile
 - https://github.com/mattermost/mattermost-mobile/blob/master/CHANGELOG.md#1300-release

**Comment by josexlito** [comment]
> We support versions v5.19+,
> 
> * https://github.com/mattermost/mattermost-mobile#mattermost-mobile
> * https://github.com/mattermost/mattermost-mobile/blob/master/CHANGELOG.md#1300-release

Oh, reading this, I see that our Mattermost Server is very outdated hahaha

Sorry for the inconvenience, and thanks a lot for your help.

**Comment by amyblais** [comment]
Mobile v1.30.1 dot release has been released and will be available in the app stores soon.
