### ISSUE TITLE
Custom emoji images not shown

### ISSUE THREAD

**Issue by skhrshin** [mattermost/mattermost-mobile#4190]
#### Summary
Custom emoji images are not shown despite the registered emoji are available on the list of emoji. The images are shown on the desktop app properly.

#### Environment Information

- Device Name: SH-M12
- OS Version: Android 9
- Mattermost App Version: 1.30.0
- Mattermost Server Version: 5.21.0

##### Case 1

See custom emoji in someone's message.

##### Case 2

See custom emoji reaction on someone's message.

##### Case 3

1. Make the list of emoji pop up by putting : (colon) at the input text field.
1. Find your custom emoji by name.

#### Expected behavior
Images of custom emoji are shown.

#### Observed behavior
Images of custom emoji are blank.

**Comment by lindy65** [comment]
Hi @skhrshin,

Thanks for the report!

I have tried to reproduce your issue on v1.30, build 285, server v5.22, Android 9, Huawei P30 Pro and I am not able to.

Custom emoji appear for me on the mobile app in all 3 of the above scenarios you've mentioned.

![image](https://user-images.githubusercontent.com/13020833/79956160-10c13800-8480-11ea-94bf-2a17c1ad3593.png)

![image](https://user-images.githubusercontent.com/13020833/79956214-2171ae00-8480-11ea-9559-a3ee460545b1.png)

**Comment by skhrshin** [comment]
I noticed that the default custom emoji "mattermost" is displayed as usual. It doesn't look to be a matter of the image file, because the custom emoji with same image and different name is not displayed.

#### Desktop App
![custom_emoji_desktop](https://user-images.githubusercontent.com/28780681/79959937-bba51680-84bf-11ea-9342-b490a85966c1.png)

#### Android App
![custom_emoji_android](https://user-images.githubusercontent.com/28780681/79959980-cb245f80-84bf-11ea-92f5-f0c8003b7564.png)

**Comment by skhrshin** [comment]
It works fine after downgrading to 1.29.0.

**Comment by lindy65** [comment]
Hi @skhrshin 

I've retested by creating a totally new custom emoji called :pineapples: and am still not able to reproduce your issue.

![image](https://user-images.githubusercontent.com/13020833/80011362-10e72500-84cc-11ea-83a9-62426d611493.png)


What build were you on in v1.30 when you reproduced this? I tested on build 285.

**Comment by skhrshin** [comment]
> What build were you on in v1.30 when you reproduced this? I tested on build 285.

It's same. Build 285. Now I'm trying to build the app by myself so that I can do git bisect.

**Comment by lindy65** [comment]
Thanks! This is so strange.... Perhaps it has something to do with you being on server version 5.21 and I'm on v5.22

**Comment by jasonblais** [comment]
@lindy65 Have we tested if it reproduces for us on server version 5.21?

**Comment by skhrshin** [comment]
I could successfully build the app by myself and found a mysterious phenomenon.

At first, I made a branch pinning to v1.29.0, which was available on the history of v1.30.0 release tag.
```
$ git checkout 0f3ea72556a70025c7e03c7535ed0f6ec8929cb9 -b build-276
```
#### Case 1 (The issue is not reproducible)
```
$ git checkout build-276
$ make pre-run
$ make run-android
$ git bisect start v1.30.0 build-276

$ make pre-run
$ make run-android
$ git bisect good
$ make pre-run
$ make run-android
$ git bisect good
$ make pre-run
$ make run-android
$ git bisect good
... (repeat unless "the first bad commit" appears)

$ git checkout v1.30.0
$ make pre-run
$ make run-android
```
Even though I uninstall the beta app and run `make run-android` again, the issue is not reproducible.

#### Case 2 (The issue is reproducible)
```
$ git checkout build-276
$ make pre-run
$ make run-android
$ git checkout v1.30.0
$ make pre-run
$ make run-android
```
I tried uninstalling and running `make run-android` again. The issue was still reproducible.

One thing I'd like to mention is that the server address form appeared and I had to log in again to the server when I ran build 285 in case 2 whereas I didn't uninstall the app nor clear the storage data.

I'll keep investigating it and report if something new is found.

**Comment by skhrshin** [comment]
5a2bb0125b848435faf66c7b350cef17ce284437 seems to be suspicious on my environment. The following steps reproduce the issue:
```
$ git checkout build-276
$ make pre-run
$ make run-android
$ git checkout 5a2bb012
$ make pre-run
$ make run-android
```
I also tried the case without `make run-android` after checking out build-276, but it was mandatory.

The following steps don't reproduce the issue:
```
$ git checkout build-276
$ make pre-run
$ make run-android
$ git checkout 5a2bb012^
$ make pre-run
$ make run-android
```

**Comment by skhrshin** [comment]
> I also tried the case without `make run-android` after checking out build-276, but it was mandatory.

The thing which is mandatory may be not to run `make run-android` but to uninstall the app. Here is log of what I tried:
```
$ git checkout 5a2bb012^
$ rm -r node_modules/react-native-fast-image/
$ npm install
$ make pre-run
$ make run-android
```
Custom emoji was shown at this time.
```
$ git checkout 5a2bb012
$ rm -r node_modules/react-native-fast-image/
$ npm install
$ make pre-run
$ make run-android
```
Custom emoji was still shown.
```
$ adb uninstall com.mattermost.rnbeta
$ make run-android
```
Custom emoji was not shown at this time.

**Comment by lindy65** [comment]
Thanks so much for all the investigation @skhrshin 

Yes @jasonblais - I have tested on prev.test v5.21 and am still not able to reproduce the issue on Android 9, v1.30, build 285:

![image](https://user-images.githubusercontent.com/13020833/80074411-66ade280-8549-11ea-9908-e0ab80e96578.png)

![image](https://user-images.githubusercontent.com/13020833/80074465-7b8a7600-8549-11ea-9e5b-40610230dcd2.png)

**Comment by skhrshin** [comment]
I tried editing `node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageOkHttpProgressGlideModule.java` by my hand and got the following result.

At first, I checked out v1.30.0.
```
$ git checkout v1.30.0
$ rm -r node_modules/react-native-fast-image/
$ make pre-run
$ make run-android
```
Cleared the storage data, and then logged into my server. Custom emoji wasn't shown.

Then I opened FastImageOkHttpProgressGlideModule.java and commented out the line where `.cookieJar(new FastImageCookieJar())` was. Then I ran
```
$ make run-android
```
Custom emoji was shown at this time.

I uncommented the line I had commented out before and ran
```
$ make run-android
```
Custom emoji was still shown.

Once I cleared the storage data and logged into my server again, custom emoji wasn't shown.

From the above, what I guess are:

- Something related with Cookie which is needed for showing custom emoji image is not saved if `FastImageCookieJar` is used.
- Once the necessary thing is saved into the storage data without `FastImageCookieJar`, it can be loaded even with `FastImageCookieJar` unless the storage data is cleared.

I'm wondering why `FastImageCookieJar#saveFromResponse` does nothing. Of course I'm not familiar with this code at all, so it might not be close to the point of the issue. I'll try investigating my case more.

**Comment by skhrshin** [comment]
logcat has dumped this error.
```
04-23 19:24:34.390 32396 32396 W Glide   : Load failed for https://mattermost.flokart.dev/api/v4/emoji/wz8whbmccj8kbxrhwm1qjaw1ze/image with size [120x120]
04-23 19:24:34.390 32396 32396 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
04-23 19:24:34.390 32396 32396 W Glide   : There was 1 cause:
04-23 19:24:34.390 32396 32396 W Glide   : com.bumptech.glide.load.HttpException(Unauthorized)
04-23 19:24:34.390 32396 32396 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-23 19:24:34.390 32396 32396 W Glide   :   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
04-23 19:24:34.390 32396 32396 W Glide   : There was 1 cause:
04-23 19:24:34.390 32396 32396 W Glide   : com.bumptech.glide.load.HttpException(Unauthorized)
04-23 19:24:34.390 32396 32396 W Glide   :  call GlideException#logRootCauses(String) for more detail
04-23 19:24:34.390 32396 32396 W Glide   :     Cause (1 of 1): class com.bumptech.glide.load.HttpException: Unauthorized
04-23 19:24:34.391 32396 32396 I Glide   : Root cause (1 of 1)
04-23 19:24:34.391 32396 32396 I Glide   : com.bumptech.glide.load.HttpException: Unauthorized
04-23 19:24:34.391 32396 32396 I Glide   :      at com.bumptech.glide.integration.okhttp3.OkHttpStreamFetcher.onResponse(OkHttpStreamFetcher.java:71)
04-23 19:24:34.391 32396 32396 I Glide   :      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:216)
04-23 19:24:34.391 32396 32396 I Glide   :      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
04-23 19:24:34.391 32396 32396 I Glide   :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-23 19:24:34.391 32396 32396 I Glide   :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-23 19:24:34.391 32396 32396 I Glide   :      at java.lang.Thread.run(Thread.java:764)
```

**Comment by skhrshin** [comment]
I think I must explain about authorization steps of my Mattermost server, since it might be strongly related with the kinds of Cookie the client must hold.

My Mattermost server is set up with GitLab SSO. And my GitLab server is set up as a service provider of SAML. The identity provider of SAML is my Keycloak instance. So the login steps are below.
1. Enter the server address.
1. Mattermost asks whether to log in with ID and password or with GitLab SSO. Select GitLab.
1. Keycloak's login form is displayed. Enter ID and password.

**Comment by skhrshin** [comment]
At this code in `FastImageCookieJar#loadForRequest`,
```
        String cookie = getCookieManager().getCookie(url.toString());
```
my `cookie` value was like
```
experimentation_subject_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%3D--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; MMAUTHTOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxx; MMUSERID=xxxxxxxxxxxxxxxxxxxxxxxxxx; MMCSRF=xxxxxxxxxxxxxxxxxxxxxxxxxx
```
so multiple cookie must be returned, but it does just
```
        return Collections.singletonList(Cookie.parse(url, cookie));
```
I changed this code like below
```
        String[] pairs = cookie.split(";");
        List<Cookie> cookies = new LinkedList<Cookie>();
        for (String pair : pairs) {
            cookies.add(Cookie.parse(url, pair));
        }
        return cookies;
```
Then the custom emoji image was shown correctly.

**Comment by amyblais** [comment]
Would you be open to submitting a PR to update our react-native-fast-image patch to allow multiple cookies as you found?

**Comment by enahum** [comment]
@skhrshin thanks for the finding... @amyblais I have a PR coming up for 1.31 that is all about `FastImage` perhaps it would make sense to add @skhrshin findings in that PR as it will take about 5 mins to add it in.

Really appreciate this! and please continue to share, Also to the point @amyblais is making, feel free to submit a PR for bug fixes and Help Wanted tickets at any time ;)

**Comment by skhrshin** [comment]
Thanks, I'm looking forward to 1.31 :)
