### ISSUE TITLE
Back button causes logout from GitLab SSO

### ISSUE THREAD

**Issue by skhrshin** [mattermost/mattermost-mobile#4191]
#### Summary
Where I'm logging into my Mattermost server with GitLab SSO, the app logs out from the server when I close the app by the back button.

#### Environment Information

- Device Name: SH-M12
- OS Version: Android 9
- Mattermost App Version: 1.30.0
- Mattermost Server Version: 5.21.0

#### Steps to reproduce
1. Open the app.
1. Log in to the server with GitLab SSO.
1. Press the back button.
1. Open the app again.

#### Expected behavior
The session has been kept alive and messages are shown.

#### Observed behavior
The app has logged out from the server and the server address form is shown.

**Comment by amyblais** [comment]
@skhrshin Do you have "ExperimentalStrictCSRFEnforcement" setting enabled on your server?

**Comment by skhrshin** [comment]
@amyblais No, I don't. It was disabled.

**Comment by lindy65** [comment]
Thanks for the report @skhrshin :)

I am not able to reproduce your issue on Android app v1.30, build 285, server v5.22 Huawei P30 Pro.

After hitting the back button to put the app into the background and then reopening it, I am taken back to the channel I was viewing before hitting the back button.

**Comment by skhrshin** [comment]
This issue doesn't occur after downgrading to 1.29.0.

**Comment by skhrshin** [comment]
Uninstalling the app and installing 1.30.0 again seems to solve the issue.

**Comment by lindy65** [comment]
Good news! Thanks for the feedback @skhrshin :)

**Comment by amyblais** [comment]
Mobile v1.30.1 dot release has been released and will be available in the app stores soon.
