### ISSUE TITLE
When I'm typing a message, the last message from the other person is hidden by the keyboard.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4199]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When I'm typing a message in a chat window, when the other person sends me a message, the last message is hidden by my keyboard.

#### Environment Information

- Device Name: iphone xr, iphone 6
- OS Version: iOS 13.4.1
- Mattermost App Version: 1.30.0
- Mattermost Server Version: 5.22.0

#### Steps to reproduce
How can we reproduce the issue?

1. When I'm typing a message, the conversation partner also hits the message.
2. The message 'Someone is typing' is activated.
3. The last message sent by the other person is hidden by the keyboard I am typing.

#### Expected behavior

The last message sent by the other person should always be visible to me

#### Observed behavior

![image](https://user-images.githubusercontent.com/42505950/79962528-1be98780-84c3-11ea-9b4e-e80648c5a4d3.png)
(You can see from the above image that the last message sent by the other party is obscured.)

The last message sent by the other party is covered by the keyboard. Occasionally the last message is visible to me.
However, in most situations, the message is obscured by the keyboard.
Then suddenly, the last message sent by the other person is seen again.

I don't know how to reproduce accurately.
It only happens when I am typing a message and the other party is typing a message.

#### Possible fixes

A similar situation was found among the issues.

https://github.com/mattermost/mattermost-mobile/issues/3972

**Comment by jasonblais** [comment]
@bitdessert Sorry for not responding to you earlier.

We released a fix with v1.34, which shipped in August 2020. Jira ticket here for reference: https://mattermost.atlassian.net/browse/MM-21155

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
