### ISSUE TITLE
Orientation fixed in portrait

### ISSUE THREAD

**Issue by scanno** [mattermost/mattermost-mobile#420]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Since the latest play Store version, the app does not want to change orientation anymore. It stays fixed in portrait. This used to work pretty nice. Especially on tablets, landscape orientation is wanted. 

Could you please allow landscape orientation again, because without it, the app is useless for tablet use. And I use that a lot. 

#### Environment Information

- Device Name: Galaxy Tab S2 9.7 
- OS Version: Android 7.1.1
- Mattermost App Version: build 21
- Mattermost Server Version: 3.7.3

#### Steps to reproduce
Grab a tablet and try landscape mode

#### Expected behavior
When changing tablet orientation to landscape, the app should change its layout to landscape. 

#### Observed behavior
The orientation of the app stays in portrait no matter what orientation the tablet itself is in (also at startup of the app) 

#### Possible fixes
 https://github.com/mattermost/mattermost-mobile/commit/396bac389f9187485fc483cdc617c8bf473825f6

**Comment by lfbrock** [comment]
Hi @scanno - we turned it off for now since there were some bugs when switching back and forth between portrait and tablet view. 

We plan on adding it back in, but need to fix the bugs first. We would also like to do a different UI design for tablets, since right now I believe it just uses the same view as the mobile apps even though the screen size is larger. 

Are either of those things something you would be interested in helping with?

**Comment by scanno** [comment]
Hi @lfbrock  thanks for the quick reply. 
Sadly I will not have time to contribute. I already have way too many (open-source)  side projects I am working on in my free time. But since I use mattermost on a daily basis on both phone and tablet, I could help out with testing builds. 

This app has made big progress during the last few weeks and am looking forward to the things to come.

**Comment by enahum** [comment]
closing this issue as right now is working as expected and the issue hasn't been updated in a while, feel free to re-open the issue if necessary.

**Comment by scanno** [comment]
@enahum yeah checked it in the latest version and it is working. 

Thanks.
