### ISSUE TITLE
When sending a gif image, the preview is not visible

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4200]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary

The gif image does not appear in the preview.

#### Environment Information

- Device Name: iOS simulator, iphone xr
- OS Version: iOS 13.4.1
- Mattermost App Version: 1.30.0
- Mattermost Server Version: 5.22.0

#### Steps to reproduce

Press the fourth button to send the image.

#### Expected behavior

It should be previewed regardless of the image type.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

on the left is a gif
![image](https://user-images.githubusercontent.com/42505950/79954706-a973aa00-84b8-11ea-95cc-0636ba8df78a.png)

on the right is a jpg
![image](https://user-images.githubusercontent.com/42505950/79954733-b55f6c00-84b8-11ea-9803-4f35c8755a9f.png)

#### Possible fixes
......

**Comment by enahum** [comment]
@bitdessert is this happening to you with any `gif` image? I can't reproduce your issue, would you mind sharing the gif here so I can give it a try ?

**Comment by bitdessert** [comment]
@enahum Here is the image address I tested. https://i.pinimg.com/originals/5e/4b/21/5e4b2163c7c3f3383c22ecf282e8ad93.gif

**Comment by enahum** [comment]
Right it is definitely working for me.

![IMG_0754](https://user-images.githubusercontent.com/6757047/80045474-84416480-84d5-11ea-8cb8-58ef08f422d1.GIF)

**Comment by bitdessert** [comment]
@enahum Thank you. Then I'll test it more.
