### ISSUE TITLE
When I hit the 'Delete Documents & Data' button, the button to join the team disappears.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4209]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary

When I hit the 'Delete Documents & Data' button in  'advanced_settings.js' file, the button to join the team disappears.

#### Environment Information

- Device Name:  galaxy 9, Android emulator(Nexus 5X API 24)
- OS Version:  Android 9
- Mattermost App Version: 1.30.0
- Mattermost Server Version: 5.22.0

#### Steps to reproduce
How can we reproduce the issue?

1. Press the 'Delete Documents & Data' button in  'advanced_settings.js' file, 
2. You can see that the button to join the team disappeared.
(before)
![image](https://user-images.githubusercontent.com/42505950/80045723-49761580-8543-11ea-9a3e-80e80c08303a.png)

(after)
![image](https://user-images.githubusercontent.com/42505950/80046062-652deb80-8544-11ea-8fec-4ba7df0f7286.png)

#### Expected behavior
I think the functioning button should not disappear.

#### Observed behavior

I attached the image above.

#### Possible fixes
I don't know how, but the relevant files are:
advanced_settings.js
teams_list.js

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-24501.
