### ISSUE TITLE
[Help Wanted] Automatically convert usernames to lowercase on sign in

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#422]
If you're interested please comment here and come [join our "Native Mobile Apps" channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/mobile-developer-setup.html).

----
**Notes:** [Jira Ticket](https://mattermost.atlassian.net/browse/PLT-5668)

**Summary:** Automatically convert usernames to lowercase letters on sign in.

**Repro of issue:**
1) Create an account with username "Jason"
– username is converted to lowercase ("jason") in the database
2) Try to log in with that username

**Observed:** "We couldn't match your credentials" error

**Expected:** Username converted to lowercase ("jason") on sign in so login is successful

**Comment by cpanato** [comment]
I can try this one

**Comment by cpanato** [comment]
not repoduced in the current master

**Comment by enahum** [comment]
This issue has been resolved!
