### ISSUE TITLE
[Help Wanted] Remove download icon from file thumbnails

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#423]
If you're interested please comment here and come [join our "Native Mobile Apps" channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/mobile-developer-setup.html).

----
**Notes:** [Jira Ticket](https://mattermost.atlassian.net/browse/PLT-6140)

**Summary:** The file thumbnails have a download icon that doesn't do anything, and it would be too small to click to actually download the file. Remove the icon, and shift the file size text to the left to take its place. 

<img width="249" alt="screenshot 2017-03-29 13 24 00" src="https://cloud.githubusercontent.com/assets/9354841/24479160/bf1913b6-1492-11e7-878b-fb794d594229.png">

**Comment by cpanato** [comment]
I will try this one

**Comment by cpanato** [comment]
Pr: https://github.com/mattermost/mattermost-mobile/pull/507

**Comment by enahum** [comment]
done by #507
