### ISSUE TITLE
[Help Wanted] Swipe down to close keyboard

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#424]
If you're interested please comment here and come [join our "Native Mobile Apps" channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/mobile-developer-setup.html).

----
**Notes:** [Jira Ticket](https://mattermost.atlassian.net/browse/PLT-6034)

**Repro of issue:**
1. Click into the texbox to open the keyboard
2. Swipe down to scroll the channel, extending over top of the text input box

**Observed:** Keyboard stays open

**Expected:** Keyboard should close if the swipe action goes overtop the text input box. Do not close the keyboard if the swipe action is only on the channel, and not on the keyboard.

[See iMessage, FB messenger, most other apps for example]

**Comment by VeraLyu** [comment]
Hi, may I take this one?

**Comment by lfbrock** [comment]
Hi @VeraLyu - yes definitely! If you have questions, feel free to ask in the [Native Mobile Apps channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps).

**Comment by enahum** [comment]
@VeraLyu dunno if you already started with this but you could take a look at https://github.com/wix/react-native-keyboard-input

**Comment by VeraLyu** [comment]
I totally forgot this @enahum , sorry, but I will start this weekend. Thanks

**Comment by awitherow** [comment]
Hey @VeraLyu have you gotten started on this? 😄

**Comment by enahum** [comment]
@awitherow there's this PR #649 but we want to finish a few more UI designs for the emoji picker, that PR will take care of this

**Comment by g3d** [comment]
Hi guys, is that issue still open to pick up?

**Comment by enahum** [comment]
Yes it is ;)

**Comment by hanzei** [comment]
Maybe we should post this again on https://github.com/mattermost/mattermost-server?

**Comment by enahum** [comment]
This one is already being done by someone

**Comment by hanzei** [comment]
Can we then close this one and keep track of this issue in https://github.com/mattermost/mattermost-server/issues/9504?
