### ISSUE TITLE
[Q] Android 6 build

### ISSUE THREAD

**Issue by eadmaster** [mattermost/mattermost-mobile#4249]
is it possible to build an apk for Android 6?

I am stuck on an older build which now is failing to log into my private MM instance.

**Comment by amyblais** [comment]
We currently support Android 7+: https://docs.mattermost.com/install/requirements.html#mobile-apps.

**Comment by i23098** [comment]
I know this is closed, but I think it should be implemented... My phone broke and I have started using an older phone that only has Android 6. It would be nice to have a client for people on older phones.

**Comment by eadmaster** [comment]
As alternative I am actually using the Firefox browser to access MM, which is still updated on Android 6.
