### ISSUE TITLE
[Help Wanted] Accept Team URL on the Server URL page

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#425]
If you're interested please comment here and come [join our "Native Mobile Apps" channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/mobile-developer-setup.html).

----
**Notes:** [Jira Ticket](https://mattermost.atlassian.net/browse/PLT-3591)

**Repro of issue:**
1) Go to the Server URL page
2) Enter a Team URL instead of the Server URL

**Observed:** Error message "Cannot connect to server"

<img width="454" alt="screenshot 2017-03-29 15 33 38" src="https://cloud.githubusercontent.com/assets/9354841/24479640/192a1646-1495-11e7-8e70-33602e361608.png">

**Expected:** We should try to guess the server URL based on the team URL, to be forgiving as per our [design principles](https://docs.mattermost.com/developer/fx-guidelines.html#fast-obvious-forgiving).

**Comment by cpanato** [comment]
I will try this one

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/mattermost-mobile/pull/499

**Comment by enahum** [comment]
done by #499
