### ISSUE TITLE
iOS share screen channels view height

### ISSUE THREAD

**Issue by tuxity** [mattermost/mattermost-mobile#4259]
Hello,

#### Summary
I noticed something annoying when sharing a file to a MatterMost channel, the height of the view when choosing a channel is a bit small comparing to slack and I always end up not choosing the channel I want or clicking outside.

#### Environment Information
- Device Name: iPhone 11 Pro
- OS Version: iOS 13.4.1
- Mattermost App Version: 1.30.1
- Mattermost Server Version: 5.22.1

#### Steps to reproduce
Try to share any file to a mattermost channel and see the widget height

#### Observed behavior
![image](https://user-images.githubusercontent.com/31608/80988301-ed3fab00-8df8-11ea-9799-df7ce22eb3dd.gif)

#### Possible fixes
Increase height of sharing widget view

**Comment by amyblais** [comment]
What Mattermost mobile app version are you on? What Mattermost server version are you on?

**Comment by tuxity** [comment]
Mattermost-server: 5.22.1
Mattermost iOS: 1.30.1

I have edited first post to add this info

**Comment by enahum** [comment]
@esethna can you create a jira ticket for this, the implementation should be easy but I would prefer to have UX confirm the height and to determine if it also applies to the teams list.

**Comment by esethna** [comment]
+1! I'll let @matthewbirtch create a quick wins ticket for this and specify the height directly.

**Comment by matthewbirtch** [comment]
@esethna created https://mattermost.atlassian.net/browse/MM-24940

**Comment by tuxity** [comment]
Thank you guys 👍

**Comment by amyblais** [comment]
This is implemented in Mattermost Mobile V2 Beta. Please see more details here: https://mattermost.com/blog/mobile-beta-program-v2/.
