### ISSUE TITLE
[Help Wanted] Swipe up to close in-app notifications

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#426]
If you're interested please comment here and come [join our "Native Mobile Apps" channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/mobile-developer-setup.html).

----
**Notes:** [Jira Ticket](https://mattermost.atlassian.net/browse/PLT-6124)

**Observed:** Currently it's not possible to dismiss in-app notifications

**Proposed Change:** Add the ability to swipe up to dismiss the notification.

<img width="320" alt="screenshot 2017-03-29 16 06 09" src="https://cloud.githubusercontent.com/assets/9354841/24480509/a2a9b396-1499-11e7-927c-5fbeaa9b038b.png">

**Comment by enahum** [comment]
Closing this issue as it was done with the new navigation
