### ISSUE TITLE
LED/Vibration (in 'sound on' mode, not silenced) doesn't work for new messages on OnePlus 5, Android 9. 

### ISSUE THREAD

**Issue by daniel-nosachev** [mattermost/mattermost-mobile#4260]
#### Summary
LED indicator and vibration (in non-silent, sound-on mode) not working for any incoming messages.

#### Environment Information

- Device Name: OnePlus 5 (A5000)
- OS Version: Android 9
- Build Version: ONEPLUS A5000_23_200224
- Mattermost App Version: 1.30.1 (Build 287)
- Mattermost Server Version: 5.22.0 (Build 5.22.1)

#### Steps to reproduce
- Let the device lie, screen off.
- Receive any message.
- Observe the device.

#### Expected behavior
When I receive a new message, I should hear the notification sound with vibration. LED indicator flashing on the new message until I open and read it.

#### Observed behavior
When I receive a new message, I hear the notification sound, but no vibration, and LED light doesn't work on a new message (app not opened, message not read).

#### Possible fixes
I wish I could help, but I'm not a dev, unfortunately. 

Maybe it's some OxygenOS (stock OnePlus ROM, version 9.0.11) or Android 9 Pie conflict with the Mattermost mobile app or smth. I'm not sure if it's a bug though, but vibration and LED work as expected on other apps like Telegram, Viber. Didn't test on Slack.

Anyway, fixing this would be a great favor. Let me know if you have any questions and thanks in advance for considering and your help!

**Comment by enahum** [comment]
@daniel-nosachev aren't you able to customize the notification to vibrate/blink/change the sound in the android notifications settings for the app?

**Comment by daniel-nosachev** [comment]
@enahum I wish I could, but on Oxygen OS you can only switch notifications on/off and some extra settings for important to all messages and that's all. Vibrate/blink are not customizable for specific apps, unfortunately. See the screenshot attached.

![image](https://user-images.githubusercontent.com/54989757/81218962-b54a8a80-8fe7-11ea-9c07-7579ddc431a2.png)

Another odd thing is that if I switch all the notifications and ringer to silent-vibrate mode, when notifications arrive from Mattermost, the phone does vibrate and blink, but not when the phone is in normal (ringer and notification sound on) mode.

I guess that's the problem of Oxygen OS specifically, since on my other old phone, Meizu (Flyme OS), all the notifications from Mattermost worked absolutely fine (when I disabled background process kill, heh).

**Comment by enahum** [comment]
Sorry to hear that it may be an OS thing... I don't know what else to say/try

**Comment by daniel-nosachev** [comment]
I guess so too. No worries, I understand that likely it's not Mattermost's issue.

I'll close this one and hope maybe OS developers will fix such annoying bugs someday. And I'll consider changing the phone, again :D

Thanks a lot for responding, have a good one, and stay safe!
