### ISSUE TITLE
 [MM-T541 (1.0)] Mobile Push Notifications - Fails to send reply from notification when not online

### ISSUE THREAD

**Issue by nevyangelova** [mattermost/mattermost-mobile#4265]
#### Summary
Mobile Push Notifications - Fails to send reply from notification when not online
–––––––––––––––––––––––––
Available on iOS 13.3.1

#### Environment Information

- iPhone 7
- iOS 13.3.1
- Mattermost Beta v1.31.0 (291)
- community.mattermost.com

#### Steps to reproduce
- Have another user trigger a push notification for your RN app user
- Put your device into airplane mode / turn off wifi so your device does not have a connection
- Pull down push notification to reply
- Try to send a reply from the push notification
- Observe notification "Message failed to send"
- Turn off airplane mode, in Mattermost view the message that triggered the notification

#### Expected behavior
- "Local push notification" is received saying "Message failed to send"

#### Observed behavior
- "Local push notification" was not received ("Message failed to send")

**Comment by amyblais** [comment]
@nevyangelova You can open a Jira bug ticket for this :)

**Comment by enahum** [comment]
closing as this should be track in jira
