### ISSUE TITLE
iOS message doesn't scroll

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/mattermost-mobile#4292]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
This issue only occurs on iOS. It does not occur on the same version of Android. Turn on "Enable User Typing Messages" and "Type Typing Timeout" is 5000. If there is no problem without keypad. Touch input box to make keyboard visible. And someone type messages.

#### Environment Information

- Device Name: iPhone XR/11 Pro 
- OS Version:  XR(13.4.1), 11 Pro (13.4.1)
- Mattermost App Version: 1.13.1
- Mattermost Server Version: 5.22.1

#### Steps to reproduce
- Turn on "Enable User Typing Messages"
- "Type Typing Timeout" set 5000
- Touch input box to make keyboard visible
- Someone type messages

#### Expected behavior
- The screen does not go up.
- The messages is behind the keyboard. ("only iOS")

#### Observed behavior
Check out the video below, please.
- https://s3-ap-northeast-1.amazonaws.com/npd.mtglobalcdn.com/i/trim.A60C19B3-DBA8-4698-9FF6-2B652F7D3BB3.MOV

#### Possible fixes
- When the keyboard is visible, it is necessary to correct the position value.

**Comment by enahum** [comment]
@Gloriashield we have a ticket to track this issue for quite some time now https://mattermost.atlassian.net/browse/MM-21155 but so far we have not found a solution that does not involve a change in UX, this is happening because of animating the user is typing element.

**Comment by Gloriashield** [comment]
@enahum 
Thank you for your answer. If possible, I try to find a way to solve this problem and help. Please decide whether you want to end this ticket. Thank you :D

**Comment by jasonblais** [comment]
Thanks for your report! A fix for this issue was shipped in v1.34, released in the app stores in August 2020.

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

Jira ticket for reference: https://mattermost.atlassian.net/browse/MM-21155
