### ISSUE TITLE
 App loading forever in lazyload Channel screen when using mattermost 1.30.1 (App Store) 

### ISSUE THREAD

**Issue by AiTranXuan** [mattermost/mattermost-mobile#4298]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Critical error cannot use the app

#### Environment Information

- Device Name: iPhone XS Max
- OS Version: 13.4.1
- Mattermost App Version: 1.30.1

#### Steps to reproduce
- First, download the Mattermost app on AppStore.(now, version MM - 1.30.1)
- You login to a workspace. Then logout (The error will sometimes appear: "Tap relaunch to open the app again. After restarting, you can report the problem from the settings menu.")
- If you continue to login to that workspace, there is no error.
- If you login to another workspace, the App will access the Channel screen but will be loading forever in the lazyload state
-Kill the app and reopen it, it will be saved forever by lazyload screen, so the only way is to delete the application and download it again.

#### Observed behavior
- Image this bug:  ![IMG_5793](https://user-images.githubusercontent.com/15552410/81913782-a0c74d00-95fa-11ea-9f97-954fc8bc9bbc.PNG)
- Video this bug: [BugsLoadForeverVideo.zip](https://github.com/mattermost/mattermost-mobile/files/4627099/BugsLoadForeverVideo.zip)

#### Possible fixes
- Sorry, I have not found the cause of this problem!

**Comment by amyblais** [comment]
@AiTranXuan Do you have ``ExperimentalPrimaryTeam`` enabled on your server?
