### ISSUE TITLE
Break out MVP scenarios into smaller tickets/stories 

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-mobile#43]
Scenarios: 

Log in and “Hello world” hard-coded channel view: Login to server with basic email authentication and automatically log into first team, show Town Square channel with usernames, time stamp, usernames (looks like compact view with no profile pics), and plain text message contents. 

Switch channels: Add icon in top left of channel view to open lefthand sidebar to view list of public channels, private groups and direct messages. Scroll up and down channels. Switch channels by tapping on new channels. 

Channel notifications: Unread flag and mention count show on app icon, channel names and icon in top left of mobile view. (P2) “Unread post(s) above/below” indicators at the top and bottom of left-hand sidebar when channels with unreads are not in view. 

(P2) Push Notifications: Display push notifications on locked screen and when app is in the background, (P3) and remove push notifications after user reads the message on another device. Deep link from push notification to message. 

Basic Right Menu with logout: Add options menu button in top right of channel view, opening to right sidebar menu with logout option. 

(P3) Status indicators: Enable display of user status in DM headers in center channel and lefthand sidebar and on profile pics in channels

**Comment by hmhealey** [comment]
Tickets created
