### ISSUE TITLE
Android app is crashing after update to 1.31.0

### ISSUE THREAD

**Issue by denniskawurek** [mattermost/mattermost-mobile#4327]
#### Summary
After an update to version 1.31.0 on Android the apps starts to crash.

#### Environment Information

- Device Name: Motorola Moto G6 (XT1925-5)
- OS Version: Android 9
- Mattermost App Version: 1.31.0
- Mattermost Server Version: --

#### Observed behavior
When I open the app it freezes and closes automatically by the android system.

The behaviour can also be observed on other Android phones.

**Comment by enahum** [comment]
Any chance you can share resumts from logcat? This is the first report we get from the app crashing on cold start

**Comment by ghisleouf** [comment]
Hi there,

Same for me, and others in company :

**Environment Information**
Device Name: Huawei P20 Pro
OS Version: Android 9
Mattermost App Version: 1.31.0
Mattermost Server Version: 5.23.0

![image](https://user-images.githubusercontent.com/1439092/82681153-ab629180-9c4d-11ea-8b5a-ad4aa903e75a.png)

**Comment by amyblais** [comment]
@enahum ^

**Comment by enahum** [comment]
@amyblais the above issue with the screenshot is fixed by https://github.com/mattermost/mattermost-mobile/pull/4314

**Comment by denniskawurek** [comment]
I tried to wipe all data from the app and it worked for one channel. After switching the channel it crashed again or more like the screen stays black.

Below is my logcat for this.

![mattermostlogcat](https://user-images.githubusercontent.com/11777947/82683660-a69fdc80-9c51-11ea-91e1-241b559be7d9.png)

**Comment by amyblais** [comment]
@denniskawurek @ghisleouf We are considering this for a dot release. Would you be open to help test if v1.32 beta build fixes the issue?

**Comment by denniskawurek** [comment]
@amyblais Sure. Hit me up with further information as soon as the Beta is released.

**Comment by amyblais** [comment]
@denniskawurek You can sign up as a beta tester here: https://github.com/mattermost/mattermost-mobile#testing.

**Comment by ghisleouf** [comment]
Just installed and tested... Works fine!

**Comment by denniskawurek** [comment]
Yep, here is also everything fine.
