### ISSUE TITLE
Show progress indicator during login

### ISSUE THREAD

**Issue by blahah** [mattermost/mattermost-mobile#433]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When a user enters their login info and hits the sign in button, there should be some indication that the sign in is in progress.

#### Environment Information

- Device Name: Lenovo Vibe5
- OS Version: 6.0
- Mattermost App Version: 1.0 (according to app list in android settings)
- Mattermost Server Version: 3.7.3

#### Steps to reproduce
How can we reproduce the issue?

1. Install the Mattermost 2017 beta for Android
2. Open the app
3. Enter server URL and hit 'Proceed'
4. Enter login details and hit 'Sign in'
5. Observe app interface

#### Expected behavior
After hitting 'Sign in' there should be some indication that the app has registered the button press, and that the login process is happening. There is such an indicator after submitting the server URL and before the login screen loads - having the same indicator show during login would be good.

#### Observed behavior
The app doesn't respond visually in any way for a few seconds, after which the chat interface gradually loads.

#### Possible fixes
Copy the progress indicator from the URL submission process and add it to the login submission process.

**Comment by enahum** [comment]
Totally make sense

Would you be able and interested in making a pull request implementing this?

**Comment by blahah** [comment]
@enahum happy to if someone could point me to the right part of the codebase - I poked around but got a little lost

**Comment by blahah** [comment]
@enahum nevermind, found what I'm looking for in scenes, will send a PR

**Comment by enahum** [comment]
@blaha sounds good!

**Comment by enahum** [comment]
this should be fixed with #464 if the issue persists feel free to re-open this
