### ISSUE TITLE
Messages from Webhooks empty

### ISSUE THREAD

**Issue by realrolfje** [mattermost/mattermost-mobile#435]
#### Summary
Contents of build failure messages from incoming webhooks with markupare not rendered.

#### Environment Information

- Device Name: iPhone 5 SE
- OS Version: 
- Mattermost App Version: 1.0 (22)
- Mattermost Server Version: 3.7.3

#### Steps to reproduce
Configure incoming webhook for build notifications from Gitlab. Trigger a build. Receive the notification in iphone app.

#### Expected behavior
Build notifications should be rendered as a box with a vertical colored bar on the left, red for failure, green for succes.

#### Observed behavior
The notification is on the screen, but the contents is not rendered at all. See the three webhook messages in the center of the screenshot below.

#### Possible fixes
I suspect that rendering of this specific markdown or html is not yet supported in the native app beta.

<img width="640" alt="img_4794" src="https://cloud.githubusercontent.com/assets/3617571/24521577/ebd3ffba-158c-11e7-8493-027ba604060f.png">

**Comment by lfbrock** [comment]
Hi @realrolfje thanks for the report - we have a ticket here to track adding support for this: https://mattermost.atlassian.net/browse/PLT-5974

**Comment by lfbrock** [comment]
This should be fixed by this PR: https://github.com/mattermost/mattermost-mobile/pull/555

It will be available in beta apps build 31+
