### ISSUE TITLE
Tap on notification from android in slow network, not opening respective channel/direct message.

### ISSUE THREAD

**Issue by sabbir360** [mattermost/mattermost-mobile#4374]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Tap on notification from android in slow network, not opening respective channel/direct message.

#### Environment Information

- Device Name: Samsung Galaxy Note 9/10
- OS Version: Android 10 with one ui 
- Mattermost App Version: 1.31.2
- Mattermost Server Version:  5.22.0

#### Steps to reproduce
How can we reproduce the issue?
Stop mattermost application, or battery saver itself can do it sometimes, use 3G or lower speed internet. While you **TAP new notification** it will not open respective channel/direct message. 

#### Expected behavior
Notification should open respective channel/direct message.

#### Observed behavior
I believe its happen while mattermost app opened and connection with server not happened immediately. Also, in a case, where you are on a different channel and notification happened on another channel. 

#### Possible fixes
Should need some script/checking if current channel is not the channel notification came to, and open channel immediately its connected to server, if user interacted before channel operation done, should mark the channel as unread.

**Comment by enahum** [comment]
I’m afraid your suggestion in already happening here https://github.com/mattermost/mattermost-mobile/blob/master/app/actions/views/root.js#L67 and https://github.com/mattermost/mattermost-mobile/blob/master/app/actions/views/root.js#L118.

Does ir happen when the notification belongs to a channel in a different team or the same team?

**Comment by sabbir360** [comment]
Its happening for same team as well. Ok, looks like it's patched? 
I will observe more and get back.

**Comment by prcmt** [comment]
I had a user report this exact issue today.

### Environment Information
* Device Name: HTC U11
* OS Version: Android 9
* Mattermost App Version: 1.31.2
* Mattermost Server Version:  5.23.1

**Comment by sabbir360** [comment]
I am also found this happened again for my version.
### Environment Information
- Device Name: Samsung Galaxy Note 9/10
- OS Version: Android 10 with one ui
- Mattermost App Version: 1.31.2
- Mattermost Server Version:  5.22.0

**Comment by larkox** [comment]
Closing due to the age of the ticket and that it should be already solved in V2.
