### ISSUE TITLE
Why does the channel name look different?

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4380]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

#### Environment Information

- Device Name: iOS, Android
- OS Version: 
- Mattermost App Version: 1.31.2
- Mattermost Server Version: 5.23.0

#### Steps to reproduce

You can check it in the sidebar.

#### Expected behavior

It should look the same.

#### Observed behavior
Personal and group messages look different.
The name is shown in the personal message, and the ID is shown in the group channel.
In the previous version, the name was shown regardless of the channel type.

Below is a personal channel
![image](https://user-images.githubusercontent.com/42505950/83601565-ca491800-a5ab-11ea-8321-59494bc2865e.png)

Below is a group channel
![image](https://user-images.githubusercontent.com/42505950/83601577-cf0dcc00-a5ab-11ea-9f8b-aabb4b6664a0.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
@bitdessert do you have consistent repro steps? Cause I cannot reproduce

**Comment by bitdessert** [comment]
@enahum Just click on the top left hamburger button(drawer button). Create and compare 1:1 conversations and group(1:N) conversations. You can see that each chat room name is expressed differently

**Comment by amyblais** [comment]
@bitdessert Would you be able to help test if you see the same on v1.32 beta version?

**Comment by bitdessert** [comment]
@enahum Have you changed this option? 
Change the options in the desktop app as shown below.
Account Settings-> Display Settings -> Teammate Name Display -> Show first and last name
What I tested was after selecting the third option.
If you select the first or second option, it changes like the desktop app, but the third option does not change on the mobile.

**Comment by enahum** [comment]
@josephbaylon can you try and repro and file a ticket if needed?

thanks.

**Comment by bitdessert** [comment]
@enahum I tested it by pulling version 1.32 from git and it looks good.

**Comment by enahum** [comment]
Thanks for confirming... can we close this issue then?

**Comment by bitdessert** [comment]
@enahum Will it be patched in version 1.31? If not, when will 1.32 be released?

**Comment by enahum** [comment]
A new verdion is released every 16th of the month, so 1.32 will be released in 13 days from today (June 16th 2020)

**Comment by bitdessert** [comment]
@enahum So there are no patch plans in 1.31?

**Comment by enahum** [comment]
Right, no plans to have this in a dot release

**Comment by bitdessert** [comment]
@enahum OK, thanks :)
