### ISSUE TITLE
App shows wrong Userstatus (online/away users appear as offline)

### ISSUE THREAD

**Issue by ramsonline** [mattermost/mattermost-mobile#4381]
#### Summary
The UI of the Github App shows a different User status then the Desktop App / Webinterface.

#### Environment Information

- Device Name: 
Xiaomi Mi9
- OS Version: 
Android 10
- Mattermost App Version: 
App: 1.31.2 (Github Build)
- Mattermost Server Version:
Mattermost-Version: 5.23.0

#### Steps to reproduce
Setup an Instance with different Users
#### Expected behavior
The App and the Webinterface should show identical User Status icons.

#### Observed behavior
The Userstatus varies between Webinterface an Mobile-Application.
Some Users that are online/away are shown as offline Users.

#### Possible fixes
i dont know maybe some kind of missing status update ?

**Comment by amyblais** [comment]
@ramsonline Would you be able to help test if you see the same on v1.32 beta version?

**Comment by ramsonline** [comment]
Is there an APK download available somewhere ?
The F-Droid Build of "Mattermost Beta" had its last changes about 12 Month ago and i do not use the Play-Store. Otherwise i can build it myself but it might take some time.

**Comment by amyblais** [comment]
This is a link to the latest beta APK: https://releases.mattermost.com/mattermost-mobile-beta/1.32.0/298/Mattermost_Beta.apk

**Comment by ramsonline** [comment]
Thank you its installed now... ill test it and give feedback in a few days !

**Comment by ramsonline** [comment]
This problem seems to be already fixed in the new build. Thanks for your help !
