### ISSUE TITLE
File upload error when there is a space in the file name

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4407]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
File upload error when there is a space in the file name

#### Environment Information

- Device Name: Android Device
- OS Version: Android 10
- Mattermost App Version: 1.31.2
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
Download the file from the Mattermost app(aaa 123.docx)
The file is opened as an MS WORD.
When you download the file, the space changes to '%20'.(aaa%20123.docx)
Press the file upload button in the Mattermost app.
The file(aaa%20123.docx) is shown in the list.
However, it is not uploaded.

#### Expected behavior
It should be uploaded regardless of the file name.

#### Observed behavior
When I check it in development mode, I get an error that the file cannot be found.

#### Possible fixes
Character processing is required.
https://www.w3schools.com/tags/ref_urlencode.ASP

**Comment by enahum** [comment]
Hey @bitdessert thanks for the report, would you be open to submit a PR for this?

**Comment by bitdessert** [comment]
@enahum I just tested it and didn't modify the code.

**Comment by enahum** [comment]
@bitdessert thank you for that, I guess what I’m saying is that if you are willing to make the fixes and then submit a PR, that would be very much welcomed and appreciate it ;)

If you cannot, that is also fine... we’ll try and take care of it but no specific ETA on that :(

**Comment by bitdessert** [comment]
@enahum Thank you. I wish the error could be fixed.
