### ISSUE TITLE
Android App keeps saying it hasn't posted a message when it has

### ISSUE THREAD

**Issue by nikkilocke** [mattermost/mattermost-mobile#4408]
#### Summary
Often (particularly with a poor WiFi signal), the Android app (and, I hear, the iOS one too) claims it hasn't sent a message, offering the options to Try Again, Delete Message or Cancel. But the claim is not removed even when the message has been posted successfully. Clicking Try Again will often cause the message to be posted again (but still not make the claim go away!).

#### Environment Information

- Device Name: Nexus 5 phone
- OS Version: Andriod 9
- Mattermost App Version: 1.31.2
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
Tricky - go somewhere with a flaky WiFi connection, and post some messages?

#### Expected behavior
Message is either posted, or not. If posted, the icon saying it hasn't been posted should go away.

#### Observed behavior
This shows what happens when the app thinks the message hasn't been sent,
![Screenshot_20200604-072732](https://user-images.githubusercontent.com/684025/84252117-19400180-ab06-11ea-8215-b5a8f235e1d2.png)

This is what I see when I click on the (i)
![Screenshot_20200604-072749](https://user-images.githubusercontent.com/684025/84251415-404a0380-ab05-11ea-8e55-8fb5afba20ac.png)

This amusingly recursive shot shows the message (which actuall has been posted, followed by my screenshot, followed by the original notification that the message hasn't been posted, just to prove that the app is unable to detect that th message has been posted, even though it is happily displaying it 2 messages up!
![Screenshot_20200604-073336](https://user-images.githubusercontent.com/684025/84251405-3cb67c80-ab05-11ea-94a5-2dcfffce6774.png)

#### Possible fixes
Sorry, can't help there :-(

**Comment by nikkilocke** [comment]
You would have thought it would be easy enough to check the incoming
messages from Mattermost to see if there was one from me with exactly the
same text as the one that the app thinks hasn't been sent yet.

**Comment by larkox** [comment]
Closing this issue because of its age. Feel free to reopen it if you still see the same issues in V2.
