### ISSUE TITLE
Android app freezes when too many gifs in one message

### ISSUE THREAD

**Issue by svnoak** [mattermost/mattermost-mobile#4421]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Mattermost Android app slows down/gets unresponsive when many gifs in one message

#### Environment Information

- Device Name: Moto G7 Plus
- OS Version: Android 9
- Mattermost App Version: 1.31.2 (Build 296)
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
Created a single message with a lot of gifs included through markdown (about 9mb).
Markdown code: `![alt-text](gif-url)`
Going into channel with the message freezes/slows down the app.

"Delete Documents & Data" resolves the problem until joining the channel with the gif message.

#### Expected behavior
No freezing app.

#### Observed behavior
It works fine on the Linux desktop app, no peaks in CPU or RAM usage on the server.
 #2828 seems to be the same issue and fixed, but still the app still freezes.

#### Possible fixes
-

**Comment by amyblais** [comment]
Our devs mentioned that this is somewhat expected as the device runs out of memory. We will need to investigate if we can find an alternative where we have the server create a thumbnail for gifs in link previews / markdown images and we only play the gif in the gallery view.

**Comment by amyblais** [comment]
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),
