### ISSUE TITLE
[Android] Keep Stopping aka Force Closed After Add React Native Firebase

### ISSUE THREAD

**Issue by reposocial** [mattermost/mattermost-mobile#4430]
#### Summary
I want to add firebase v7. When i add @react-native-firebase (app/crashlytics/messaging) its work and finished installed but, Keep Stoping on Android

#### Environment Information

- Device Name: Nexus 5x emulator
- OS Version: API 29
- Mattermost App Version: 1.31.0
- Mattermost Server Version: Own Server

#### Steps to reproduce
How can we reproduce the issue?
add @react-native-firebase (app/crashlytics/messaging) 
set your gradle project depedencies for android like instruction documentation firebase
 and run it.

#### Expected behavior
Describe your issue in detail.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
by default i see mattermost has firebase messaging but old version. 
<img width="956" alt="Screen Shot 2020-06-19 at 15 51 11" src="https://user-images.githubusercontent.com/34335974/85136497-ea463000-b269-11ea-986f-763d7ffa67ec.png">

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
Hi @sadamht can you provide more details? and after replacing the google-services.json file have you edited the AndroidManifest.xml as well ?

**Comment by sadamht** [comment]
@enahum sorry i was change the subject bugs. any solution?

**Comment by enahum** [comment]
@sadamht I’m afraid I cannot be of much help as I haven’t ever used `react-native-firebase` Also your not providing any info that could allow anyone to try and tell you whats wrong with your implementation... if what you want is crash reports, maybe enabling Sentry (which is built in) is a better alternative?

**Comment by enahum** [comment]
I believe the underlying **react-native-notifications** is already implementinf _firebase-messaging_, maybe you have conflicting versions?

**Comment by sadamht** [comment]
@enahum  yah i now react-native-notifications has implementation firebase-messaging. but, i just want to add package @react-native-firebase(app/crashlytics). then,i configure like react native firebase documentation. boom. its conflict on android (Failed Launch aka Forced Closed) but, on iOS its no error and running well.

**Comment by enahum** [comment]
@sadamht Then maybe you need to go the extra mile and remove react-native-notifications and all related code and have it replaced with firebase, or you could find a way to have them co-exists. That my friend we cannot help you with.

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
