### ISSUE TITLE
[iOS] Didnt Received Notification but, Android Succesfull

### ISSUE THREAD

**Issue by reposocial** [mattermost/mattermost-mobile#4431]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Hello, i change all cert and key for iOS Notification its running well no error. but, while test some message [iOS] Didnt Received Notification Foreground,Backgorund or Closed App
#### Environment Information

- Device Name: 11 Pro Max Simulator / Real Device (iPhone 6 & iPhone XR)
- OS Version: 13.5.1
- Mattermost App Version: 1.32.0
- Mattermost Server Version: 5.16.3

#### Steps to reproduce
How can we reproduce the issue?
i following mattermost documentation about push notification ios.
certicate convert to .pem as tested and running well.

Note : there is a backend team handle about proxy and server.

No Error, Running well
While Running Has Alert/Modal Allow Notification
but, when message its not showing notif Foreground,Backgorund or Closed App
#### Expected behavior
Describe your issue in detail.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
![Screen Shot 2020-06-30 at 16 25 00](https://user-images.githubusercontent.com/34335974/86113474-80444b00-baf3-11ea-8859-9591d66d1d72.png)

![Screen Shot 2020-06-30 at 15 21 25](https://user-images.githubusercontent.com/34335974/86104053-bed40880-bae7-11ea-9972-e4b20d6bbaa6.png)
![Screen Shot 2020-06-30 at 13 48 51](https://user-images.githubusercontent.com/34335974/86104068-c3002600-bae7-11ea-9717-8ff5067b124c.png)
![Screen Shot 2020-06-30 at 13 47 50](https://user-images.githubusercontent.com/34335974/86104081-c7c4da00-bae7-11ea-97cb-cc53ed889984.png)
![Screen Shot 2020-06-30 at 13 44 02](https://user-images.githubusercontent.com/34335974/86104099-cc898e00-bae7-11ea-86cd-a15515b5cd88.png)
![Screen Shot 2020-06-30 at 13 48 16](https://user-images.githubusercontent.com/34335974/86113550-97833880-baf3-11ea-9f9d-661d55085b23.png)
![Screen Shot 2020-06-30 at 13 44 49](https://user-images.githubusercontent.com/34335974/86113190-23489500-baf3-11ea-81cb-26c31db8bbff.png)
![Screen Shot 2020-06-30 at 13 43 36](https://user-images.githubusercontent.com/34335974/86104146-d9a67d00-bae7-11ea-89b1-6dd059759631.png)
![Screen Shot 2020-06-30 at 13 49 24](https://user-images.githubusercontent.com/34335974/86104155-dd3a0400-bae7-11ea-82ef-17f6f7829e65.png)
![Screen Shot 2020-06-30 at 13 49 47](https://user-images.githubusercontent.com/34335974/86104166-e0cd8b00-bae7-11ea-8446-1dbda1f86dce.png)
![Screen Shot 2020-06-30 at 13 51 23](https://user-images.githubusercontent.com/34335974/86104175-e4611200-bae7-11ea-9172-c4af4b52a374.png)
![Screen Shot 2020-06-30 at 13 52 18](https://user-images.githubusercontent.com/34335974/86104182-e75c0280-bae7-11ea-8889-d9fd5ffbeff0.png)
![Screen Shot 2020-06-29 at 10 17 16](https://user-images.githubusercontent.com/34335974/86104195-eaef8980-bae7-11ea-8eef-5d65c727259b.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
have you deployed your own push proxy? can you share configuration files etc?

**Comment by sadamht** [comment]
hai @enahum thank you for response. 
i'am just a jr. mobile dev. 
backend or config server there is a person who handle this.

what do you need files to share here
<img width="353" alt="Screen Shot 2020-06-18 at 17 19 03" src="https://user-images.githubusercontent.com/34335974/85148013-d30f3e80-b279-11ea-87f4-b605a100f51d.png">

**Comment by enahum** [comment]
Sorry for the late response...

When you build the iOS app you need to sign it with your own provisioning profiles, that means that you’ll need your own APNS certificate installed in https://github.com/mattermost/mattermost-push-proxy and deploy that server. Then configure the MM server to use that push proxy instead.

More info here https://developers.mattermost.com/contribute/mobile/push-notifications/

**Comment by sadamht** [comment]
its okey. @enahum  i have updated some screenshoot ...
cert and convet its running well and successed.

about proxy and configure server there is a backend team to handle that...

**Comment by enahum** [comment]
@sadamht so, issue resolved?

**Comment by sadamht** [comment]
@enahum not yet, any solution ?

**Comment by enahum** [comment]
@sadamht reading the description in the issue, you  mention you  are using an iPhone simulator.. you do know that remote notifications do **not** work with the simulator and that you need a real device, right ?

**Comment by sadamht** [comment]
@enahum actuallly, we has tested on TestFlight for our team for testing. device (iPhone 6, iPhone XR, iPhone XS & iPhone 11

**Comment by enahum** [comment]
So, you’ve built the app successfully, then push it to test flight, configured the push proxy with the apns cert, pointed the MM to your push proxy, logged in to the server with the app, the session is being registered as iPhone Native App (meaning the session has the device id set in the database).

Sent a message that triggers a notification and no notification is received.

Ok lets say that is happening, what about server logs, push proxy logs? I’m 100% you or someone in your team is missing something, I would suggest going step by step following the documentation. Also it would be good if you have it working without any additional changes to the codebase, once you have that working start adding the changes as you need them. Then confirm your changes is not causing any other aide effects.

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
