### ISSUE TITLE
Very high cold load time in Android 10

### ISSUE THREAD

**Issue by sreekanthgs** [mattermost/mattermost-mobile#4449]
#### Summary
Very high cold load time in Android 10

#### Environment Information

- Device Name: Oneplus 5T
- OS Version: Android 10
- Mattermost App Version: 1.32.0
- Mattermost Server Version: 5.23

#### Steps to reproduce
Clear Mattermost mobile app from memory and do a fresh open. 

#### Expected behavior
App opens with short load time normal for react native apps. 

#### Observed behavior
Cold open times ahead of 10 seconds when app not in background. Suspend and reopen works normally. 

#### Possible fixes
Unknown

**Comment by hahmadia** [comment]
Also experiencing this. Using a Oneplus 5T Android version 9 and recently having upgraded my mobile app to latest one available on google playstore, it is taking noticeably longer to load the channels compared to previous versions. However, once things are loaded the app works fine.

**Comment by sreekanthgs** [comment]
Tried the same on mattermost server 5.24. Knew it can't be a server side issue, but still. No change.

**Comment by enahum** [comment]
This is being looked at here https://github.com/mattermost/mattermost-mobile/pull/4452

**Comment by enahum** [comment]
it would really help if you can test out  the APK posted in the PR link
