### ISSUE TITLE
iOS app bricked: Closing and restarting the app does not re-initialize.

### ISSUE THREAD

**Issue by realrolfje** [mattermost/mattermost-mobile#446]
#### Summary
The iOS version stopped fetching updates from the channel for an unknown reason. Restarting the app now shows a white screen with the mattermost logo for a long time, and then the server URL page. Pressing "proceed" gives a "Network Request Error".

#### Environment Information

- Device Name: iPhone 5 SE
- OS Version: iOS 10.2
- Mattermost App Version: 1.0 (22)
- Mattermost Server Version: 3.7.3

#### Steps to reproduce
I can not find what caused the app to stop fetching updates from the server, and I also have no means to see why it is not reconnecting after restart. I would be more than happy to provide logs or crash reports if I knew where to look for those.

#### Expected behavior
When closing the app (double tap on home button, swipe mattermost up on iPhone), and then restarting it, it should re-initialize enough of the content so that it reliably reconnects to the server.

#### Observed behavior
I noticed that the app did not fetch latest updates on a channel (the desktop app had newer posts than the iPhone app showed). Switching channels on the iPhone app did not help.

I decided to restart the iOS app by double-tapping home, swiping the app up, waiting a few seconds, and then tap the mattermost app icon.

The app starts but shows a white screen with the mattermost logo for a long time. Then it presents the URL screen, where the url of the mattermost server is pre-filled. I tap on "proceed". The app then tries to log me in but that too takes a long time. After a while it shows the login screen with "network request error".

I also tried rebooting the iPhone to see if it was the network stack in iOS, but after restarting the behavior did not change.

#### Possible fixes
I suspect that somewhere in the code which connects to the REST api or the network layer below that, something is permanently stored, and restarting the app and/or logging in does not clean that data.

**Comment by realrolfje** [comment]
Updating the OS to iOS 10.3 did not solve this problem or change the behavior.

**Comment by realrolfje** [comment]
Update: This bug was reported 1 hour ago. It is now 15:48, and the behaviour changed:
Opening the app shows the URL and the "proceed" button. I clicked "proceed". The login window shows. I typed in my username and password and was succesfully logged in.

It seems there is a timeout on the data that is stored, so that would point to some caching mechanism in the API Client or Network Layer of the app. If that is the case, it would be really easy to invalidate the cache on restart.

**Comment by realrolfje** [comment]
Changed title of this bug from "iOS app bricked: Closing and restarting the app does not re-initialize." to "Restarting the app does not invalidate cache."

**Comment by lfbrock** [comment]
Hi @realrolfje - we have a new build that's coming up that should fix the splash screen issue. 

I'm not sure about the network error - can you try connecting to https://pre-release.mattermost.com and see if you hit any similar issues? (You'll need to [sign up](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) on desktop if you don't already have an account).

**Comment by enahum** [comment]
can you try with build 24?

**Comment by enahum** [comment]
build 24 should have fix this and now there is build 26, if the issue persists please feel free to re-open this issue
