### ISSUE TITLE
The title disappears when an old message is pressed in a recent mention menu.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4470]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
The channel title disappears when I click on an old message in the recent mention.

#### Environment Information

- Device Name: Android emulator (api 24)
- OS Version: 
- Mattermost App Version: 1.32.0
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
1. click a settings drawer button
2. go to recent mention, flagged mention
3. click an old message
Then, you can see that the title has disappeared.

#### Expected behavior
Even if the conversation is old, the channel title should still be visible.

#### Observed behavior
Even if I click on an old conversation in the recent mention and join the conversation, the conversation is not visible in the left sidebar.

What I tested was that if the recent conversation was a week ago, the chat room disappeared.
I clicked on the message from the chat room in the recent mention menu and entered the lost chat room.

This error also occurred when I clicked a message in the Flagged Messages menu.

#### Possible fixes
You should check if the chat room is old and disappeared.

**Comment by jasonblais** [comment]
@bitdessert Sorry for the delay in responding to you. I just tried it but wasn't able to reproduce, that said I have an iOS device. Would you be open to let us know if this issue is still occurring for you?

**Comment by larkox** [comment]
Closing due to the age of the ticket. If it still reproduces on V2, feel free to reopen it.
