### ISSUE TITLE
When I close the 'channel more' modal, the keyboard does not disappear.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4471]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary

Click the Channel More button in the left sidebar. If you do nothing and close the modal(click left top button), the keyboard won't close.
#### Environment Information

- Device Name: android emulator 
- OS Version: 
- Mattermost App Version: 1.32.0
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
1. Click the Channel More button in the left sidebar. 
2. If you do nothing and close the modal(click left top button), the keyboard won't close.

On ios, when I close the modal, the keyboard disappears normally.
Regardless of the modal type, if the modal is closed while the keyboard is open, the keyboard should disappear.

#### Expected behavior
When the modal is closed, the keyboard should disappear.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-26490.
