### ISSUE TITLE
The theme is not applied well.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4472]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary

Changing the theme has problems rendering colors.
In dark mode, the background screen appears white.
After changing the theme, the color does not come out properly on the random screen.

#### Environment Information

- Device Name: android device
- OS Version: 
- Mattermost App Version: 1.32.0
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
Difficult to reproduce.
After changing the theme, the colors are not reflected properly on the screen.

The channel background looks white even though it is in dark mode

Here is what I tested:
Enter the theme change menu.
default : organization -> change : windows Dark
click the back button(left top button '<-')
Do nothing
Enter the theme menu again.
The background is white
![theme-error](https://user-images.githubusercontent.com/42505950/85385830-b9257280-b57d-11ea-89dc-769171ff832c.gif)

If this bug occurs, the theme is not reflected properly on other screens.

I don't know how to reproduce.

#### Expected behavior
Normal colors should be reflected depending on the theme.

#### Observed behavior
attached

**Comment by jasonblais** [comment]
@bitdessert Sorry for the delay in responding to you. Would you be open to let us know if this issue is still occurring for you?

**Comment by larkox** [comment]
Closing due to the age of the ticket. Feel free to reopen it if it still reproduces on V2.
