### ISSUE TITLE
Failed to login with Gitlab SSO using iOS app

### ISSUE THREAD

**Issue by shawnhwei** [mattermost/mattermost-mobile#4473]
#### Summary
Cannot proceed past the "Single Sign-On" screen using Gitlab SSO (with 2FA). After logging-in and completing 2FA a blank page is shown and the "Single Sign-On" is stuck. I have isolated the issue to app build 1.32.0 (302) and greater, not experiencing the issue on all prior versions down to 1.30.0.

#### Environment Information
- Device Name: iPhone XS/iPhone 7
- OS Version: 13.5.1
- Mattermost App Version: v1.32.0
- Mattermost Server Version: 5.23.1
- Gitlab Server Version: 13.1.0

#### Steps to reproduce
After fresh install of iOS app 1.32.0 build 302, attempt to login to Mattermost instance using Gitlab SSO.

#### Expected behavior
The "Single Sign-On" screen disappears and the default channel is shown.

#### Observed behavior
There are no errors in our request logs. I can see successful calls to Gitlab's `/api/v4/users` and MM's `/signup/gitlab/complete?xxxxx` route after completing the app login.

#### Possible fixes
I am guessing it is due to changes in #4422.

**Comment by sphr** [comment]
We're experiencing the same issue on both android and ios, but have 2FA disabled, downgrading the mobile client to anything lower than 1.32.0 works.

**Comment by amyblais** [comment]
@shawnhwei @sphr Are you able to reproduce this on the latest beta app version (version 305)? You can get the latest beta version via https://github.com/mattermost/mattermost-mobile#testing.

**Comment by sphr** [comment]
> @shawnhwei @sphr Are you able to reproduce this on the latest beta app version (version 305)? You can get the latest beta version via https://github.com/mattermost/mattermost-mobile#testing.
I can still reproduce the problem on beta client 1.32.1; getting stuck with a white page at "Single Sign-On" after login.

**Comment by shawnhwei** [comment]
> > @shawnhwei @sphr Are you able to reproduce this on the latest beta app version (version 305)? You can get the latest beta version via https://github.com/mattermost/mattermost-mobile#testing.
> 
> I can still reproduce the problem on beta client 1.32.1; getting stuck with a white page at "Single Sign-On" after login.

Still no good. Version 1.3.2 (301) is the last working build for me.

**Comment by amyblais** [comment]
Does the blank screen ever disappear, e.g. after waiting for 10 seconds?

**Comment by shawnhwei** [comment]
No, it seems to stay on the Single Single-On screen with a blank webview indefinitely.

**Comment by bill2004158** [comment]
I have got similar issue.
1. the server is deployed to url:  http://some.domain.com/mm  --> Note:  **/mm** 
3. thus the cookie's path is **/mm**
2. however, the sso trying to get the cookie from path **/**
`CookieManager.get(parsedUrl.origin, true)`  
the value of parsedUrl.origin is **http://some.domain.com**

**Comment by shawnhwei** [comment]
My case is also using a subdomain but at the root path. I cannot reproduce the issue on an Android 11 emulator, only on my physical iOS devices. Unfortunately I don't have a Mac to build for iOS. Is it possible to push a debug RN build to test flight so we can use the RN debugger?

**Comment by sphr** [comment]
This is true in our install as well, we run mattermost in a subdir in https://our.org/app

**Comment by enahum** [comment]
Thank @bill2004158 very helpful information. I believe I found the cause of this issue... running some tests... then we'll need to decide if this goes to a second 1.32 dot release or if its going to be shipped with 1.33.

@amyblais your call

**Comment by elyscape** [comment]
This is also affecting us. We're using SAML login rather than Gitlab SSO and we are not running Mattermost in a subdirectory.
