### ISSUE TITLE
cannot uploading files in Android

### ISSUE THREAD

**Issue by jn5010** [mattermost/mattermost-mobile#4478]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

#### Environment Information

- Device Name: Xiaomi Mi A2
- OS Version: Android 9
- Mattermost App Version: 1.32.0
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
Cannot uploading files with spaces in the name in Android.

#### Expected behavior
Describe your issue in detail.
1. Select the file to download on mattemost app
2. Open the file through the MS OFFICE app.
3. Save the file in MS OFFICE app.This changes the file name.(test 0123.xlsx -> test%01223.xlsx)
4. Upload downloaded files on mattermost
5. Failed to upload file.

#### Observed behavior
It should be uploaded regardless of the file name.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-26489.

**Comment by jasonblais** [comment]
Jira ticket reference: https://mattermost.atlassian.net/browse/MM-26489
