### ISSUE TITLE
Android app converts help URL to all lowercase

### ISSUE THREAD

**Issue by mthaddon** [mattermost/mattermost-mobile#4482]
#### Summary
In the Android app, Mattermost converts help URLs to all lowercase.

#### Environment Information

- Device Name: Huawei Honor 10
- OS Version: Android
- Mattermost App Version: 1.32.0
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
Set the help URL in a Mattermost instance to include upper and lower case characters. Visit the URL from android.

#### Expected behavior
The URL should not be converted to all lower case.

#### Observed behavior
User is sent to a lowercase version of the URL.

**Comment by hloeung** [comment]
It's probably https://github.com/mattermost/mattermost-mobile/blob/master/app/screens/settings/general/settings.js#L153

`const link = config.HelpLink ? config.HelpLink.toLowerCase() : '';`

**Comment by svelle** [comment]
I don't want to argue, just trying to understand why one would expect uppercase URLs?

[RFC2396](https://www.ietf.org/rfc/rfc2396.txt) states that 

>For example, the host names used in URL are 
actually case insensitive, and the URL <http://www.XEROX.com> 
is equivalent to <http://www.xerox.com>.

(see Page 22, section 6.)

**Comment by hloeung** [comment]
That's for host names / site names. So http://www.xerox.com/MyPage vs. http://www.xerox.com/mypage.

**Comment by nobuto-m** [comment]
> I don't want to argue, just trying to understand why one would expect uppercase URLs?

One example is that URLs with MoinMoin Wiki engine are case-sensitive.

http://moinmo.in/MoinMoinWiki -> ok
vs
http://moinmo.in/moinmoinwiki -> "This page does not exist yet."

**Comment by svelle** [comment]
@hloeung @nobuto-m thanks to both of you, totally forgot about these cases! makes a lot more sense now :)
