### ISSUE TITLE
Swift Bridging Header not being generated after changing project settings

### ISSUE THREAD

**Issue by dragosiancu0504** [mattermost/mattermost-mobile#4487]
Hey guys,
I'm having troubles building the latest version of iOS mobile app.

After downloading the code and running "make pre-run" and "make run" the app launches and everything is ok.

But the second I modify anything in the XCode project settings, the build stops working giving the following error:

> The following build commands failed:
> 	CompileC /Users/dragosiancu/Library/Developer/Xcode/DerivedData/Mattermost-brtupfchwikpmkcesuxefuxedsfu/Build/Intermediates.noindex/Mattermost.build/Debug-iphonesimulator/Mattermost.build/Objects-normal/x86_64/UIPasteboard+GetImageInfo.o /Users/dragosiancu/Downloads/mattermost-mobile-1.32.0/ios/Mattermost/UIPasteboard+GetImageInfo.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

This error is produced by line 11 of UIPasteboard+GetImageInfo.m because the Bridging Header is not generated and I can't figure out why.

I tried removing the Swift files and re-adding them to the project thinking the .pbxproj is missing some links. Tried restarting and cleaning a hundred of times but without any luck.

Can anyone help me, please?
Thank you,
D

**Comment by enahum** [comment]
The bridging header is already there https://github.com/mattermost/mattermost-mobile/blob/master/ios/Mattermost/Mattermost-Bridging-Header.h

Maybe you need to double check what is it that you are modifying

**Comment by dragosiancu0504** [comment]
Not that one.

The Mattermost-Swift.h bridging header is not generating.

I am modifying only the app name, bundle id and Signing certificates & profiles. That's it.

Any ideas?

**Comment by enahum** [comment]
> I am modifying only the app name, bundle id and Signing certificates & profiles. That's it.

Then why do you need it to create the bridging header I don’t really get it.

Have you tried doing that (app name, bundle id, profiles...) by building with the env variables + the command line to do so? Have you read https://developers.mattermost.com/contribute/mobile/build-your-own/ ?

**Comment by dragosiancu0504** [comment]
> Then why do you need it to create the bridging header I don’t really get it.
I don't, that's how xcode build works when you have swift code used inside obj-c code. It generates a "ModuleName"-Swift.h bridging header.

I have followed the steps shown here (https://developers.mattermost.com/contribute/mobile/developer-setup/run-on-device/)

> Have you tried doing that (app name, bundle id, profiles...) by building with the env variables + the command line to do so? Have you read https://developers.mattermost.com/contribute/mobile/build-your-own/ ?

Yes, and the build still fails for the same reason. Does it work for you?

Thanks

**Comment by dragosiancu0504** [comment]
So, for anyone encountering problems like this try using fastlane command from terminal instead of using the makefile commands cause it will give you a more specific error for you to correct.
Just run "fastlane" and then select the option you need.

Cheers,
D
