### ISSUE TITLE
Documentation for the setting up react native app in the windows machine

### ISSUE THREAD

**Issue by alexanderon** [mattermost/mattermost-mobile#4530]
#### Summary
Documentation for the windows machine is missing. Build is not property running while starting the local development. 

#### Environment Information
- OS Version: Windows 10
- Mattermost App Version : React Native 

#### Steps to reproduce
checkout the repo for the MM mobile. 
run the npx react-native run-android

#### Expected behavior
React Native Bundler should run without any error and should work for the running the app locally.

#### Observed behavior
App is not event starting and flooded with many errors in the console.

**Comment by enahum** [comment]
@alexanderon there is no windows documentation as the team uses mac internally, we would definitely welcome a PR for the documentation if you are up for it

**Comment by alexanderon** [comment]
@enahum , sure but here are some issue which needs to solved. When run `npm install` in the repo. following error occurs. 

![issue_with_npm_install](https://user-images.githubusercontent.com/14137097/86527527-32e22800-bebd-11ea-8df2-2e3fc3c284f9.PNG)

**Comment by enahum** [comment]
@alexanderon i think you need to enable “Windows Subsystem for Linux” which should be part of the doc

**Comment by alexanderon** [comment]
@enahum , https://developers.mattermost.com/contribute/server/developer-setup/windows-wsl/ this is for the server right ? How is this related to react native setup ?

**Comment by enahum** [comment]
@alexanderon We use a Makefile to run certain things like the post install scripts, having to run `make` is the existing relation

**Comment by jasonblais** [comment]
@alexanderon Since it's been a few months from last activity on this issue, we'll assume that the problem is fixed or is no longer valid. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you if we can, though as mentioned the internal team uses MacOS for development.
