### ISSUE TITLE
Notifications with new messages when I'm logged out

### ISSUE THREAD

**Issue by piotrfilipek** [mattermost/mattermost-mobile#4533]
#### Summary
App is sending notifications with new messages, although I'm logged out.

#### Environment Information

- Device Name: iPhone SE 2020
- OS Version: 13.5.1
- Mattermost App Version: v1.32.2

#### Steps to reproduce
1. Log in
2. Log out
3. Wait for new messages

#### Expected behavior
App can't showing notifications with new messages when I'm logged out.

#### Observed behavior
App is showing notifications with new messages when I'm logged out.

**Comment by enahum** [comment]
@danoxide when logging out probably there was a failure, thus the app logged you out the session remain active in the server.

This is intentional behavior to not have you be unable to switch servers and watnot...

To remove the session you can login to the webapp go to Account Settings -> Security -> View active sessions, and then force the logout for the device

**Comment by danoxide** [comment]
Okay, but IMO when I want to log out I'd expect that I'll be logged out and the notifications were stopped. I think "active session" should only provide possibility to close session remotely.

**Comment by enahum** [comment]
True, but to ensure that is the case we will need to block the “logout” until the server acknowledge which can be a problem as well cause of connectivity. Basically in your case you would’ve been “stuck” and would’ve needed to try and logout again and again until successful.

If we weight the two I think that the frustration of not being able to logout is grater than continue receiving notifications, specially cause sharing your device with another person is somewhat an edge case in my opinion.

**Comment by amyblais** [comment]
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),
