### ISSUE TITLE
The keypad does not disappear after 'add a comment' 

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4541]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

#### Environment Information

- Device Name: Android emulator / Android Device
- OS Version: API 24~
- Mattermost App Version:  1.32.2
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
1. click a post
2. add a comment

#### Expected behavior
After editing the message, the keypad disappears.(I know this has been fixed before.)
However, the keypad does not disappear after replying('Add a comment' action).

#### Observed behavior
It's as described. The keypad does not disappear.

#### Possible fixes

It seems to be related to below.
https://github.com/mattermost/mattermost-mobile/issues/4471

**Comment by enahum** [comment]
@bitdessert this is an issue with the navigation library https://github.com/wix/react-native-navigation/issues/5525 feel free to comment over there.

Closing.
