### ISSUE TITLE
Restrict channel creation to admin only

### ISSUE THREAD

**Issue by meaz** [mattermost/mattermost-mobile#4568]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
I'd like to restrict channel creation to admin only.
I've set `RestrictPublicChannelCreation": "system_admin"`, in `config.json` but users can still create channel. What am I doing wrong?

#### Environment Information

Debian Strect
Mattermost Version: 5.24.2
Database Schema Version: 5.24.0
Database: postgres

#### Steps to reproduce
edit `config.json` and set `RestrictPublicChannelCreation` to `system_admin`

#### Expected behavior
I would think that users could not create channels anymore.

#### Observed behavior
I can still create channel as a user.

**Comment by amyblais** [comment]
@meaz It seems the setting was deprecated in 2018: https://docs.mattermost.com/administration/config-settings.html#enable-public-channel-creation-for. Are you using Advanced Permissions?

**Comment by meaz** [comment]
I don't see any Advances Permissions... Is that in the pay version only? That is too bad...

**Comment by amyblais** [comment]
Yes, it's currently on Enterprise Edition.
