### ISSUE TITLE
App stuck at splash screen iOS

### ISSUE THREAD

**Issue by rousesDev** [mattermost/mattermost-mobile#4570]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
App is stuck at splash screen when selecting the run option.

#### Environment Information

- Device Name: iPad Pro 11-inch
- OS Version: 13.5.1
- Mattermost App Version:  1.33.0
- Mattermost Server Version: 5.9

#### Steps to reproduce
Opened project in Xcode
In Targets:
Changed Team to personal team
Changed bundle identifier to new app name
Changed App Groups to personal group
Went to Run the App got error and App will not proceed past the splash screen

#### Expected behavior
When trying to test run the app on my device through xcode the app does not proceed past the splash screen. Xcode says it is because of a issue with line 161 in ibMMKV.mm.

#### Observed behavior
Error Message: Assertion failed: (0), function +[MMKV mmkvWithID:cryptKey:relativePath:mode:], file /Users/aaron/mattermost-mobile/ios/Pods/MMKV/iOS/MMKV/MMKV/libMMKV.mm, line 161.

<img width="1148" alt="Screen Shot 2020-07-15 at 10 33 03 AM" src="https://user-images.githubusercontent.com/39060255/87564986-abe43b00-c686-11ea-8134-18a0d472dd26.png">

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
@rousesDev you'll need to update the app group Id in MMKV the file is `node_modules/react-native-mmkv-storage/ios/MMKVStorage.m`

**Comment by rousesDev** [comment]
Thank you for that @enahum that fixed my issue.
