### ISSUE TITLE
[iOS] Notification dots inconsistently used

### ISSUE THREAD

**Issue by olivier-magloire** [mattermost/mattermost-mobile#4589]
#### Summary
The Android and iOS app notification dots behave differently on general notifications (not mentions).

#### Environment Information

- Device Name: 
- OS Version: iOS 13.3
- Mattermost App Version: 1.32.0
- Mattermost Server Version: 5.19.0

#### Steps to reproduce
Setup:
* User A: Browser
* User B: Android app
* User C: iOS app
* All users in same private channel

App config for both users B and C:
* Mobile push
** Notifications for all activities
** Notifications on all states (online, away, offline)
* Mentions
** Username enabled
** Channel wide notifications enabled
* Private channel not muted

A writes to channel "Hey all"
* B gets a push notification and notification dot
* C gets a push notification but no notification dot

A writes to channel "Hey @here"
* B gets a push notification and notification dot
* C gets a push notification but no notification dot

A writes to channel "Hey @B"
* B gets a push notification and notification dot
* C gets a push notification but no notification dot

A writes to channel "Hey @C"
* B gets a push notification and notification dot
* C gets a push notification and notification dot

#### Expected behavior
With all notifications enabled I would expect both the Android and iOS app to show the notification bubble with every triggered notification, as long as the bubble is generally enabled.

#### Observed behavior
Apparently the iOS only shows the bubbles on direct mentions. Neither @here nor regular messages are trigger a notification bubble. On Android every push notification also triggers to notification bubble.

#### Possible fixes
Don't know how to fix this.

**Comment by olivier-magloire** [comment]
Manually created mentions seem to work as expected.

**Comment by josephbaylon** [comment]
@olivier-magloire @amyblais I can confirm the issue on iOS. On Android, the dot badge always appear. However for iOS, the badge appears intermittently for `@all / @here / @channel`

Single `@here` does not trigger badge. `@here --> @here` also does not trigger badge.

However, when user receives `@here --> @all --> @here`, then the badge appears for `@here`. The same goes for `@all --> @channel --> @all`, only then the badge for `@all` appears.

DMs and at-mentions seem to trigger the badge properly.

This issue is not a recent regression. Issue only occurs on iOS

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-27141.

**Comment by smirta** [comment]
Hi @amyblais, are there plans to implement this anytime soon? We have people waiting to get this resolved. This is quite crucial for working together.

**Comment by amyblais** [comment]
I don't have an ETA on this, the latest comment on the ticket is that one of the dev teams will address the ticket alongside work related to overhauling how unread counts work.

**Comment by malugiso** [comment]
Hey all
i just wanted to ask if this issue is still on the board to fix or if this is closed.
We still have the same issue, that the badges on IOS don't show up if a user receives an message which isn't directly addressed to him.
IOS: 14.4
MM: 1.40.0

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest mobile app version, feel free to re-open this issue.
