### ISSUE TITLE
Update android project (Target API level requirements from August 2020)

### ISSUE THREAD

**Issue by AiTranXuan** [mattermost/mattermost-mobile#4618]
#### Summary
Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance.

From August 2020, new apps must target at least Android 10 (API level 29).
From November 2020, app updates must target Android 10 (API level 29).

#### Environment Information

- Device Name: Android
- OS Version: Android
- Mattermost App Version: All
- Mattermost Server Version: All

#### Observed behavior
![Screen Shot 2020-07-28 at 11 09 26](https://user-images.githubusercontent.com/15552410/88630836-6c343f00-d0db-11ea-9925-6be4533135d4.png)

#### Possible fixes
Change your app's target API level.

**Comment by enahum** [comment]
Master branch already targets 29
