### ISSUE TITLE
Tables don't render on iOS mobile app

### ISSUE THREAD

**Issue by absynth47215** [mattermost/mattermost-mobile#4622]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Tables in chat messages seem to be rendered as ASCII in the iOS app.

#### Environment Information

- Device Name: iPhone SE 2020
- OS Version: iOS 13.5.1
- Mattermost App Version: 13.33.1 (Build 311) 
- Mattermost Server Version: 5.24.0 (Build 5.24.2) Enterprise trial

#### Steps to reproduce
1. create a slash command that posts a table according to the example at https://docs.mattermost.com/developer/slash-commands.html
1. Observe behavior in webapp and desktop app (correct)
1. Observe behavior in iOS app (renders as plain text)

#### Expected behavior
I used the weather example from the mattermost slash command introduction https://docs.mattermost.com/developer/slash-commands.html to write my own slash command. The table which is emitted by the command is rendered just fine in the desktop and webapp, but it renders as ASCII in the iOS version of the app. 

I would expect the table to be consistently rendered as rich text across all apps.

#### Observed behavior
Renders as plain text, see screenshots. 
![D98FDCAF-FC75-45B7-99CF-0025F186B0EA](https://user-images.githubusercontent.com/3737316/88890685-42e1f300-d242-11ea-83d2-c2a9d379362e.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by absynth47215** [comment]
According to feedback by a colleague, the table is plain ASCII in the current version of the Playstore Android app as well.

**Comment by absynth47215** [comment]
Sorry, that shouldn't have been closed.

**Comment by enahum** [comment]
@absynth47215 is working for me, maybe check your table formatting
![image](https://user-images.githubusercontent.com/6757047/88899234-cf2cef80-d21b-11ea-9ded-b294f4e77bfa.png)
![image](https://user-images.githubusercontent.com/6757047/88899255-d6ec9400-d21b-11ea-8bcd-48de031cb29d.png)

**Comment by absynth47215** [comment]
When I copy&paste the unformatted table into a chat message, it renders fine. However when my mattermost integration posts it, it doesn't render on iOS/Android. 
I will check for extra whitespace or something - maybe the desktop app has a more forgiving parser than the mobile app.

**Comment by absynth47215** [comment]
@enahum The table rows had extra whitespace at the beginning. The desktop parser seems to tolerate this but the mobile client does not. 
I'll close this here but in my opinion, it's at least worth taking a look at in the long run. Thanks!

**Comment by enahum** [comment]
Yes, indeed the parser for the desktop/web is different than the one used in the mobile app.

@hmhealey do you know why is more forgiving the one used in the webapp?

**Comment by hmhealey** [comment]
The webapp is using a much older Markdown parser from before Markdown was properly standardized as CommonMark, so it had to be looser with the rules because of that. That said, we usually reference GitHub's version of CommonMark, and they seem to support whitespace before tables, so the mobile app may still be incorrect here.

Like
```markdown
  | asdf | foo|
  | -- | -- |
  | aa| bb|
```

renders as 

  | asdf | foo|
  | -- | -- |
  | aa| bb|

so I'd expect the mobile app to also be able to render that.

@absynth47215 Are you able to provide the plain text for one of the tables that wasn't working in the mobile app?
