### ISSUE TITLE
Weird file crashes android app...

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-mobile#4632]
Someone uploaded this file (unzipped .mp4) to one of my instances: [birdsnotreal.mp4.zip](https://github.com/mattermost/mattermost-mobile/files/5008424/birdsnotreal.zip)

"file" says its actually a `MPEG transport stream data` (Therefore the correct extension would be `.ts`), but it still gets accepted/uploaded by mm as mp4.

When trying to play said file with the current andoid app, it reliably crashes the app.

#### Environment Information
- Device Name: OnePlus5t (happens on others too)
- OS Version: LOS 16 (happens on others too)
- Mattermost App Version: 1.33.1 (311)
- Mattermost Server Version: 5.25.0

#### Steps to reproduce
+ Upload the unzipped file to mattermost.
+ try to play said video.
+ enjoy your crash.

#### Expected behavior
Seeing a "bird" that doesnt flap its wings but flies around.

#### Observed behavior
![Screenshot_20200731-202113_Mattermost](https://user-images.githubusercontent.com/5354356/89065154-897f3c80-d36b-11ea-913a-19bfc2b32203.png)

#### Possible fixes
Dont trust filename extensions supplied by users and do your own magic-values-checks/content based mime detection.

**Comment by amyblais** [comment]
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),
