### ISSUE TITLE
Logo stretched in an ugly way on Android

### ISSUE THREAD

**Issue by kosimus** [mattermost/mattermost-mobile#465]
#### Summary
Mattermost logo is stretched in an ugly way when the app is loading

#### Environment Information

- Device Name: HTC 10
- OS Version: Android 6.0.1
- Mattermost App Version: 1.0 (Build 24)
- Mattermost Server Version: 3.8.0  (3.8.0-rc1) (the pre-release server)

#### Steps to reproduce
1. Open Mattermost and look at the logo while the app is loading

#### Expected behavior
The logo should be round.

#### Observed behavior
The logo is stretched vertically:
![stretched_logo](https://cloud.githubusercontent.com/assets/22074352/24797085/06ff0c40-1b90-11e7-82ce-95a9d8fc815c.png)

**Comment by enahum** [comment]
#466 should fix this as is using the images generated by http://apetools.webprofusion.com/tools/imagegorilla

**Comment by kosimus** [comment]
Oh yes, that looks like the same problem. Thanks!

**Comment by enahum** [comment]
this issue seems to be resolved with #466,  if the issue persists please feel free to re-open this issue
