### ISSUE TITLE
Crash when there is a message with attachment whose footer icon URL is unreachable

### ISSUE THREAD

**Issue by jfcastroluis** [mattermost/mattermost-mobile#4665]
#### Summary
Mobile application crashes turning to a black screen when there is a message with attachment whose footer icon URL is unreachable.

#### Environment Information
- Device Name: Samsung Galaxy Note 10+
- OS Version: Android 10 (Android security patch level 1 August 2020)
- Mattermost App Version: 1.31.1
- Mattermost Server Version: 5.25.2

#### Steps to reproduce
Create a post with an attachment whose footer icon URL is unreachable.

For example:
```
WEBHOOK="https://chat.example.com/hooks/XXXXXXXXXXXXXXXXXXX"

attachment=$(cat <<EOF
{
  "color": "#000000",
  "title": "title",
  "footer": "footer",
  "footer_icon": "https://example.com/unreachable.jpg"
}
EOF
)

message=$(cat <<EOF
{
  "attachments": [$attachment]
}
EOF
)

curl -i -X POST --data-urlencode "payload=$message" $WEBHOOK
```

#### Expected behavior
It is expected to show the typical broken image icon where icon should be (or perhaps show nothing)

#### Observed behavior
The mobile application crashes turning to a black screen while on desktop browser the typical broken image icon is showed.

**Comment by enahum** [comment]
@jfcastroluis Thanks for the report, I did tried to replicate but it seems to be working fine for me (no image rendered)

| iOS | Android |
|-------|-----------|
|![image](https://user-images.githubusercontent.com/6757047/90256272-7f514980-de13-11ea-9b8e-f5ae1f4198c3.png)| ![image](https://user-images.githubusercontent.com/6757047/90256498-d8b97880-de13-11ea-88d3-bd47e1dc3b12.png)|

**Comment by enahum** [comment]
@jfcastroluis Were you able to confirm that is in fact the wring image in the footer causing the issue? I’ve used your same example and seen no crash as my comment above shows

**Comment by jfcastroluis** [comment]
Hi @enahum 

Sorry about my delay answering to this issue :(

I checked again and I was wrong. The problem is when `footer_icon` is a relative URL. Something like `/api/v4/users/3c8qt6dce3ynz8yjm9z7eojo4w/image`

I understand that could not work properly because of the non-sense relative URL (actually now I concat the main domain before) but that causes a crash of the application turning to a black screen.

So, create a post with an attachment whose footer icon URL is relative:
```
WEBHOOK="https://chat.example.com/hooks/XXXXXXXXXXXXXXXXXXX"

attachment=$(cat <<EOF
{
  "color": "#000000",
  "title": "title",
  "footer": "footer",
  "footer_icon": "/api/v4/users/3c8qt6dce3ynz8yjm9z7eojo4w/image"
}
EOF
)

message=$(cat <<EOF
{
  "attachments": [$attachment]
}
EOF
)

curl -i -X POST --data-urlencode "payload=$message" $WEBHOOK
```

**Comment by larkox** [comment]
This should be solved on V2.
