### ISSUE TITLE
iOS app falsely shows "Server upgrade required"

### ISSUE THREAD

**Issue by colorchestra** [mattermost/mattermost-mobile#4667]
#### Summary
The iOS app shows a message saying "Server upgrade required", even though the server is already on version 5.19 and has been for a while.

#### Environment Information

- Device Name: iPhone 8
- OS Version: 13.6
- Mattermost App Version: 1.33.1 
- Mattermost Server Version: 5.19.1

#### Steps to reproduce
Log into a server using the same app and server versions as above, I think?

![Screenshot from 2020-08-13 16-16-11](https://user-images.githubusercontent.com/12461043/90146851-d73f7000-dd81-11ea-9086-bd446755b24c.png)

#### Expected behavior
I expect no warning, since the server is already running the required version.

#### Observed behavior
I see this, directly after logging in:

![IMG_0877](https://user-images.githubusercontent.com/12461043/90146760-bb3bce80-dd81-11ea-8d7a-9c4b7f6c8be5.PNG)

**Comment by enahum** [comment]
Resolved by https://github.com/mattermost/mattermost-mobile/pull/4608 and it should be available with v1.34.0 that was already shipped.

**Comment by enahum** [comment]
Btw I'd recommend upgrading your server as 5.19 is reaching EOL
