### ISSUE TITLE
[iOS]There is a problem with the file download progress bar.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4716]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary

It does not change from 0% when downloading a video file.

#### Environment Information

- Device Name: iOS device
- OS Version: 
- Mattermost App Version: 1.34.0
- Mattermost Server Version:5.26

#### Steps to reproduce
It changes from 0% to 100% when previewing the video
When downloading a video, 0% does not change.
However, the video file is downloaded.

#### Expected behavior
The progress circle should work.

**Comment by enahum** [comment]
@bitdessert I’m unable to reproduce it, its working as it should for me. Are you testing this on a remote server?

**Comment by bitdessert** [comment]
![video_progressbar](https://user-images.githubusercontent.com/42505950/93048450-dd36b280-f699-11ea-9c6d-80cd4c9a5678.gif)

prev video -> When downloading to preview the video, the progress bar works normally.
download video -> When I press the top right button icon to download a video, the progress bar does not work at 0%.

**Comment by amyblais** [comment]
I'm able to reproduce, opened a ticket: https://mattermost.atlassian.net/browse/MM-28820.

**Comment by amyblais** [comment]
Closing as https://mattermost.atlassian.net/browse/MM-22195 is completed.
