### ISSUE TITLE
Sidebar of the web app and the mobile app are not synchronized.

### ISSUE THREAD

**Issue by jn5010** [mattermost/mattermost-mobile#4723]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When using the experimental Sidebar Features function, the sidebar of the web app and the mobile app are not synchronized.

#### Environment Information

- Device Name: iOS device
- OS Version: 13.6.1
- Mattermost App Version: 1.34.0
- Mattermost Server Version:5.26.0

#### Steps to reproduce
Access Mattermost with a web app. 
Turn on the Experimental Sidebar Features function and edit the sidebar.
Access the mobile app and check the configuration status of the sidebar.

#### Expected behavior
The order of channels in the sidebar of the web app and mobile app must be the same.

#### Observed behavior
The sidebar of the web app and the mobile app are not synchronized.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
@jn5010 Sidebar feature is not available on mobile.

FYI @esethna

**Comment by jn5010** [comment]
Do you have plans to develop Sidebar features on mobile app?

**Comment by esethna** [comment]
@jn5010 yes we plan on making sure mobile respects the categories defined on webapp, however we are still in the design stage on mobile and don't have a timeline available yet. When we release the sidebar feature out of experimental it will have corresponding mobile support.

**Comment by ylluminate** [comment]
Are there any updates as to this yet? I'm not only having troubles with this, but generally the iOS app is having trouble keeping messages sometimes after sending messages. Overall it seems that there are a lot of problems with the iOS execution presently.

**Comment by esethna** [comment]
@ylluminate yes we plan on offering the sidebar categories on mobile for the January 16th 2021 release when we release the sidebar categories feature as general available (currently it's an experimental feature). You can follow the JIRA ticket here: https://mattermost.atlassian.net/browse/MM-28474

Can you share more about "having trouble keeping messages sometimes after sending messages" with our support team? feedback@mattermost.com

**Comment by jn5010** [comment]
New sidebar features have been released as the general feature in web app. (https://mattermost.com/blog/custom-collapsible-channel-categories/).  Are there any plans to update this feature in the mobile app?

**Comment by esethna** [comment]
@jn5010 yes, the mobile part of the feature unfortunately got a bit delayed, but we have a developer actively working on it now. Here's the spec if you're interested :)

https://mattermost.atlassian.net/wiki/spaces/CSO/pages/1198227475/Mobile+UX+-+Collapsable+Custom+Categories

**Comment by larkox** [comment]
Closing as this should be already done on V2.
