### ISSUE TITLE
[Help Wanted] Channel header info showing raw markdown text

### ISSUE THREAD

**Issue by saturninoabril** [mattermost/mattermost-mobile#474]
#### Summary
Channel header info showing raw markdown text.

#### Environment Information
- Device Name: LG-F620K
- OS Version: Android 5.1.1
- Mattermost App Version: 1.0(Build 24)
- Mattermost Server Version: 3.8.0 (Build 3.8.0-rc2)

#### Steps to reproduce
How can we reproduce the issue?
 - Click channel name on top of the screen (e.g. Native Mobile Apps)

Note: Not sure if this has been reported already or fix has been made to new build 26, just happened to see this issue after installing/testing Beta version.

#### Expected behavior
 - Should display correct text formatting

#### Observed behavior
 - Instead, it showed raw markdown text.

![5083011307769721622-account_id 1](https://cloud.githubusercontent.com/assets/5334504/24850153/e371ea50-1e09-11e7-8de1-3afd301a7784.png)

#### Possible fixes
Have not look at the source code yet. Just happened to see this issue after testing this Beta version.

**Comment by lfbrock** [comment]
Thanks @saturninoabril - we have a ticket here to fix this: https://mattermost.atlassian.net/browse/RN-40

I'm going to update this issue to a help wanted in case someone wants to work on it

**Comment by enahum** [comment]
this has been fixed by #580
