### ISSUE TITLE
It is recommended to support multi server and account login

### ISSUE THREAD

**Issue by jack9603301** [mattermost/mattermost-mobile#4752]
Just as slack supports multi workspace login, it is recommended to support multi server address and multi account login, so users can get the same experience as desktop app. At present, the desktop application of mattermost has been supported. Now, when will mobile phone software support it?

**Comment by enahum** [comment]
Hi @jack9603301 thank you for yor suggestion. Multi-server support is now planned for FY2021. It will come right after some major reachitecture of the mobile app.

**Comment by RooSoft** [comment]
Thanks for working on this... if you need any help, I may be tempted to try and contribute.

**Comment by larkox** [comment]
Closing since multi server is supported on V2. If you need multi account login (same server, different accounts) let's open a new ticket so we can discuss that particular issue.
