### ISSUE TITLE
The device_id is missing

### ISSUE THREAD

**Issue by gbonnefille** [mattermost/mattermost-mobile#4763]
#### Summary
Unable to connect: an error message report that device_id is missing in api/v4/users/sessions/device

#### Environment Information

- Device Name: Android/iOS
- OS Version: 
- Mattermost App Version: 1.34.1
- Mattermost Server Version: 5.25.2

Login is based on Gitlab SSO. Push Notification Service is active.

#### Steps to reproduce
Simply try to connect to server.

#### Expected behavior
Describe your issue in detail.

#### Observed behavior

```
device_id invalide ou manquant dans le corps de la requête
URL: https://webchat.odin.si.c-s.fr/api/v4/users/sessions/device
```
![Screenshot_20200901-161552_Mattermost](https://user-images.githubusercontent.com/14096450/92089885-05d3c800-edcf-11ea-9ba8-4ca1a68978e3.jpg)
![Capture d’écran   2020-09-01 à 16 32 02](https://user-images.githubusercontent.com/14096450/92089914-0ff5c680-edcf-11ea-8bf2-3f1d4f705dce.jpeg)

#### Possible fixes
![Screenshot_20200903_095420_com mattermost rnbeta](https://user-images.githubusercontent.com/14096450/92089431-70383880-edce-11ea-893e-1d35f6a0e0da.jpg)

**Comment by enahum** [comment]
@gbonnefille Can you make sure you are actually patching the dependencies? This looks like the rn-fetch-blob dependency is not being patched

**Comment by gbonnefille** [comment]
> @gbonnefille Can you make sure you are actually patching the dependencies? This looks like the rn-fetch-blob dependency is not being patched

I will check. But please, note that the previous captures are made with the official APK.

**Comment by enahum** [comment]
🤔 the official apk? So in the other thread you talked about fdroid, in this one I’m seeing the react native LogBox which is only available while developing. Now you mention is the official apk, so I’m lost...

I wonder if this is something specific to your deployment? 

You also mention that the request is empty, are you inspecting the request how? Charles proxy?

**Comment by gbonnefille** [comment]
> thinking the official apk? So in the other thread you talked about fdroid, in this one I’m seeing the react native LogBox which is only available while developing. Now you mention is the official apk, so I’m lost...

Yes, we are defenitively trying to propose a working APP for our users. So we checked many solutions.

* One of them is, naturally, the official APK provided via Google Play
* Another is the old (but signed and easy to install) APK provided by F-Droid
* The last one (orange capture screen) is from sources.

Do you prefer I remove this last part of the report?

> I wonder if this is something specific to your deployment?

Yes, we are also trying to identify the impact of our environment.

Currently, as it worked with official APK before july and as it works with F-Droid version (old) but don' work with latest official APK, the better suspect seems the APP :-)

> You also mention that the request is empty, are you inspecting the request how? Charles proxy?

tcpdump.

**Comment by matpascaud** [comment]
I am working with @gbonnefille and I tried to do the following steps.

1.  rm -rf node_modules
2. npm i --ignore-scripts
3. npx patch-package

But I keep getting the same error with the device_id.

```
MacBook-Pro-de-macbookpro-****:mattermost-mobile ****$ npx patch-package
patch-package 6.2.2
Applying patches...
react-native@0.63.2 ✔
react-native-button@3.0.1 ✔
react-native-device-info@5.6.5 ✔
react-native-elements@2.3.0 ✔
react-native-fast-image@8.3.2 ✔
react-native-haptic-feedback@1.10.0 ✔
react-native-image-picker@2.3.3 ✔
react-native-keyboard-tracking-view@5.7.0 ✔
react-native-local-auth@1.6.0 ✔
react-native-mmkv-storage@0.3.7 ✔
react-native-navigation@6.12.2 ✔
react-native-notifications@2.1.7 ✔
react-native-passcode-status@1.1.2 ✔
react-native-vector-icons@7.0.0 ✔
react-native-youtube@2.0.1 ✔
redux-persist@6.0.0 ✔
rn-fetch-blob@0.12.0 ✔
MacBook-Pro-de-macbookpro-*****:mattermost-mobile ****$ make run-android
```

**Comment by gbonnefille** [comment]
I finally succeeded doing more tests on another instance. And it worked. But this instance do not use push-notification-service.
So I disabled the push-notification-service on our primary instance and it worked.

So I really suspect a bug in the application when SSO + Push-Notification-Service activated.

**Comment by gbonnefille** [comment]
We did many many more tests with other deployments and... it worked.
So I fear it is something in our side, but quite tricky.

Sorry for the noise, I close here to limit enthropy.
