### ISSUE TITLE
select team page still trigger to load more even loaded all the teams

### ISSUE THREAD

**Issue by bill2004158** [mattermost/mattermost-mobile#4792]
#### Summary
select team page still trying to load more even no more team.
it seems still trigger load more if no more data.

#### Environment Information

- Device Name: Android
- OS Version: 8.0.0
- Mattermost App Version: 1.34.1
- Mattermost Server Version:

#### Steps to reproduce
1.  go to select team page
2. scroll down to the end after loaded,
3. and scroll down again 

#### Expected behavior
it should not trigger load more if loaded all the teams.

#### Observed behavior
still trying to load more even loaded all teams.

**Comment by enahum** [comment]
@bill2004158 Can you expand? Why is this a problem?

**Comment by bill2004158** [comment]
the problem is:
it may send many load requst to server, while which is not required.
not a big issue, but it is better avoid send useless request.

**Comment by enahum** [comment]
Although I totally agree with you in this scenario a new team can be created after the app fetched then “all” thus the newly created one will not appear.

What you suggest we do in other places like posts in a channels as we know for sure there are no more to load as we reached the older one.

If you have any suggestions on how to improve here that’ll be great. Even better if you want to contribute with the code as well ;)

**Comment by bill2004158** [comment]
>in this scenario a new team can be created after the app fetched them “all” thus the newly created one will not appear.

agree.
so when scroll to bottom, always trying to check if any new data.

how about add "throttle" for loading more?
because when scrolling, it may trigger multiple loading more request at same time.
when I test, I saw at least two requests were sent out.
I think only 1 is enough.

**Comment by enahum** [comment]
Yes, throtteling would be nice, are you willing to make that improvement and submit a PR?

**Comment by larkox** [comment]
This should not be applicable any more, since the way the team list works in V2 is slightly different.
