### ISSUE TITLE
Can't download TXT file in mobile app

### ISSUE THREAD

**Issue by jn5010** [mattermost/mattermost-mobile#4809]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Can't download TXT file in mobile app

#### Environment Information

- Device Name: Galaxy S8+
- OS Version: Android 8.0.0
- Mattermost App Version: 1.34.0
- Mattermost Server Version:5.26.1

#### Steps to reproduce
Open the TXT file in the mobile app.
The TXT file is opened in a preview. And the file cannot be downloaded to the device.

#### Expected behavior
TXT files should be able to be saved on the device.

#### Observed behavior
The TXT file is opened in a preview. 

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
I'm unable to reproduce this, are you still able to reproduce this on v1.35?

**Comment by jn5010** [comment]
I can open the TXT file as a preview on v.1.35. but There is no button to save files locally.
![Screen_Recording_20200917-151004_Mattermost](https://user-images.githubusercontent.com/35473594/93429071-84feeb00-f8fb-11ea-817d-18ff9a6a67e8.gif)

**Comment by amyblais** [comment]
Thanks, reproduced now. Ticket here: https://mattermost.atlassian.net/browse/MM-28821.

**Comment by larkox** [comment]
Solved on V2.
