### ISSUE TITLE
App crashes if space after mattermost url is inserted

### ISSUE THREAD

**Issue by fujexo** [mattermost/mattermost-mobile#481]
#### Summary
When I want to connect to our mattermost server and I add a space after the URL, the app crashes

#### Environment Information

- Device Name: android-phone
- OS Version: Android 7.0
- Mattermost App Version: 1.0
- Mattermost Server Version: 3.7.0

#### Steps to reproduce
* Install the Mattermost Beta App
* Enter the Server-URL
* Add a space after the url and click "Proceed"
* The app now closes.

#### Expected behavior
The app shouldn't crash and remove the white space instead or show an error message

#### Observed behavior
The app crashes without any errors

**Comment by enahum** [comment]
Thanks for the report @fujexo we'll take a look into this

**Comment by lfbrock** [comment]
Ticket filed here to track it: https://mattermost.atlassian.net/browse/RN-95

**Comment by lfbrock** [comment]
This should be fixed in Build 27, which will be released for testing soon
