### ISSUE TITLE
Fallback option is ignored in push notifications

### ISSUE THREAD

**Issue by Sakaala** [mattermost/mattermost-mobile#4816]
#### Summary
Fallback option from attachments is ignored in push notifications when post is created from webhooks or via server api

#### Environment Information

- Device Name: Xiaomi Mi Mix 2
- OS Version: Android 9 PKQ1.190118.001
- Mattermost App Version: 1.35.0 (Build 325)
- Mattermost Server Version: 5.26.0 (Build 5.26.1)

#### Steps to reproduce
Create post via webhook or api with [message attachment](https://docs.mattermost.com/developer/message-attachments.html) and empty `message` field

#### Expected behavior
Same behavior as desktop app has: push notification is using `fallback` field 

#### Observed behavior
Only author and channel are displayed

**Comment by amyblais** [comment]
@Sakaala Have you observed this issue on previous mobile versions or do you think this is a new issue?

**Comment by Sakaala** [comment]
@amyblais I don't really know but i think this issue has been around for a while

**Comment by amyblais** [comment]
@enahum Is this a known issue or would you like me to open a ticket?

**Comment by enahum** [comment]
@amyblais I think this has to be done on the server, when a notification is sent to include the right message, and if id-loaded is used, the set the right message when fetching from the server.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-28984

**Comment by enahum** [comment]
this https://mattermost.atlassian.net/browse/MM-28984 seems that it was already merged.
