### ISSUE TITLE
Keypad does not disappear when I reply and press the sidebar

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4817]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Keypad does not disappear when I reply and press the sidebar

#### Environment Information

- Device Name:  galaxy
- OS Version: android 9
- Mattermost App Version: 1.35.0
- Mattermost Server Version: 

#### Steps to reproduce
1.Write a reply to the conversation
2. Open the left sidebar after writing
3. Keypad does not disappear

#### Expected behavior
The keypad should disappear.

#### Observed behavior
Keypad does not disappear

**Comment by amyblais** [comment]
A ticket was opened here: https://mattermost.atlassian.net/browse/MM-28880.

**Comment by amyblais** [comment]
Closing, this was fixed in v1.45 release,
