### ISSUE TITLE
Cannot sign up for new beta user on Fastlane

### ISSUE THREAD

**Issue by artiya4u** [mattermost/mattermost-mobile#485]
Cannot sign for beta user on 
https://mattermost-fastlane.herokuapp.com/
![fastlane](https://cloud.githubusercontent.com/assets/3830524/25131906/bee3b362-2471-11e7-89c0-6b872a67a45c.png)

**Comment by lfbrock** [comment]
Thanks @artiya4u - Apple changed their testing program and it broke the tool we were using, so we're [waiting on a fix](https://github.com/fastlane/fastlane/pull/8871). 

In the meantime, you can sign up to [our team Mattermost site](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) and direct message me (username lindsay) your email if you would like to be added. 

I also made a [pull request](https://github.com/mattermost/mattermost-mobile/pull/486) to note that in our readme in case others hit this issue as well.

**Comment by lfbrock** [comment]
This should be fixed now!
