### ISSUE TITLE
The dimmed screen does not disappear when I click the Show More button.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4851]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When I receive a long message and click the More button, the dimmed screen does not disappear.

#### Environment Information

- Device Name: GALAXY 8
- OS Version:  android 10
- Mattermost App Version: 1.35.1 
- Mattermost Server Version:5.26.1

#### Steps to reproduce
1. click show more button -> popup long message
2. click long message
3. click show more button
4. click long message
5. The message pop-up disappears, but the dimmed screen remains.

#### Expected behavior
The message pop-up should disappear and the dimmed screen should disappear.

#### Observed behavior
The message pop-up disappears, but the dimmed screen remains.

If you press the back button, the dimmed screen will disappear.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-29095

**Comment by amyblais** [comment]
Closing, this has been completed,
