### ISSUE TITLE
Unable to click links whenever a default browser other than Safari is set in iOS 14

### ISSUE THREAD

**Issue by fritojay** [mattermost/mattermost-mobile#4858]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
After setting Firefox as the default browser in iOS 14, all links throw an error stating that the link was not found on the server.

#### Environment Information

- Device Name: iPhone XS
- OS Version: 14.0.1
- Mattermost App Version: 1.35.1
- Mattermost Server Version: 5.21.0

#### Steps to reproduce
How can we reproduce the issue?
Download Firefox for iOS.
Set Firefox as the default browser.
Open Mattermost and click a link in a message.
#### Expected behavior
The expected behavior is to open the link properly in the in-app browser or Firefox.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
Link Error: The link could not be found on this server.
#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.
https://github.com/mattermost/mattermost-mobile/blob/1324bfd0bf792b08b99a412645b8eb3ce11c4bf3/app/components/post_list/post_list.js#L188
I am not familiar with the code base, but maybe right here?
https://github.com/mattermost/mattermost-mobile/blob/1324bfd0bf792b08b99a412645b8eb3ce11c4bf3/app/utils/url.js#L101

**Comment by enahum** [comment]
Apparently this is an iOS14 bug? https://developer.apple.com/forums/thread/660241

**Comment by enahum** [comment]
@migbot can you try this and seeif removing the check and executing openURL works? Also I believe openURL will reject the promise if it fails
