### ISSUE TITLE
Selecting a Team should switch to the Channels Page

### ISSUE THREAD

**Issue by laktak** [mattermost/mattermost-mobile#4869]
#### Summary

When I select a team, the sidebar closes and I am in the channel I had open the last time. So I have to open the sidebar again to see which channels have new messages.

#### Environment Information

- Device Name: iPhone
- OS Version:  14.0
- Mattermost App Version: 1.35.1
- Mattermost Server Version: 5.27.0

#### Steps to reproduce

- open the sidebar
- switch to another team
- the sidebar closes

#### Expected behavior

- open the sidebar
- switch to another team
- the sidebar switches to the channel view
- I can select a channel that shows it has new messages

#### Observed behavior

I find that closing the sidebar is very disorienting.

The hierarchy is team - channels - messages, so I'm not sure why it skips channels and shows me the messages.

**Comment by larkox** [comment]
This behaves different in V2.
