### ISSUE TITLE
Login is broken on some types of mobile phones

### ISSUE THREAD

**Issue by Temirtator** [mattermost/mattermost-mobile#4890]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
If in override/config.json set DefaultServerUrl and set AutoSelectServerUrl to true, after login, channel data is not loading.

#### Environment Information

- Device Name: Samsung Galaxy S10 - SMG973F
- OS Version: Android 10
- Mattermost App Version: 1.36.0
- Mattermost Server Version: 5.28.0

#### Steps to reproduce
If in override/config.json set DefaultServerUrl and set AutoSelectServerUrl to true, after login, channel data is not loading. 

#### Expected behavior
Screen stopping on lazy loading and then nothing happens.

#### Observed behavior
**Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.**

![image](https://user-images.githubusercontent.com/10742084/95986729-43a12300-0e48-11eb-8ba9-64cfd4aa8eb9.png)

#### Possible fixes
If you try to remove clear settings in override/config.json, then you will try to write server url address by yourself without autoselection, server will load without any problem.

**Comment by amyblais** [comment]
@Temirtator Are you using the app in English or in another language?

**Comment by Temirtator** [comment]
> @Temirtator Are you using the app in English or in another language?

I am using application on russian language

**Comment by larkox** [comment]
@Temirtator Are you still seeing this issue with the latest version of the beta (V2)?
