### ISSUE TITLE
Unsupported Server Version

### ISSUE THREAD

**Issue by razbag** [mattermost/mattermost-mobile#4895]
- Device Name: 
- OS Version: Andriod 10
- Mattermost App Version: 1.36.0
- Mattermost Server Version: 5.23.1

#### Steps to reproduce
How can we reproduce the issue?
Upgrade from mobile version 1.35.1 to 1.36.0

#### Expected behavior
Dear Support team in your GitHub release page you mention that this version 1.36.0 is compatible with Mattermost servers v5.19+. but when I install it into my mobile and login to server it show me Unsupported version.
can you confirm if it is bug or not and when you will release new version for this fix 

![Screenshot from  2020-10-16 21-04-33](https://user-images.githubusercontent.com/18428312/96288114-f5c91e00-0ff3-11eb-8868-d00bc6cf14dc.png)

![Screenshot from  2020-10-16 21-10-22](https://user-images.githubusercontent.com/18428312/96288166-06799400-0ff4-11eb-80de-f9b245c5c9d8.png)

Thanks,
Razmik

**Comment by amyblais** [comment]
@razbag That was incorrect so I've updated the release page with v5.25.

I'm also updating the Readme file https://github.com/mattermost/mattermost-mobile/pull/4896.

**Comment by razbag** [comment]
> @razbag That was incorrect so I've updated the release page with v5.25.
> 
> I'm also updating the Readme file #4896.

Thanks for the reply Just one more thing can I permanently dismiss it from our users until we will test and upgrade our backend ?

BTW we don't receive any notification or email regarding this change or this type of warning will be shown if we do not upgrade our back-end 

Thanks,
Razmik

**Comment by amyblais** [comment]
I believe there isn't a way to permanently disable it.

We've sent emails to customers. The in-app notification that you received is a way for us to reach out to everyone to encourage upgrades.

**Comment by razbag** [comment]
> I believe there isn't a way to permanently disable it.
> 
> We've sent emails to customers. The in-app notification that you received is a way for us to reach out to everyone to encourage upgrades.

We didn't receive any email last email which we was received it about new release of the Server V 5.27 just for you info we are using EE and not Team Edition 

Thank you for your quick response
we will plan our back-end upgrade
