### ISSUE TITLE
Cannot change server URL

### ISSUE THREAD

**Issue by hank** [mattermost/mattermost-mobile#490]
#### Summary
Once the server URL is entered into the app and Proceed is tried (and fails), you cannot click the URL text to change it again - it's stuck like that.

#### Environment Information

- Device Name: Nuu Z8
- OS Version: 5.0
- Mattermost App Version: Beta, Latest
- Mattermost Server Version: 3.8.0

#### Steps to reproduce
Type in a server URL that's wrong, click proceed, watch it fail, try to change it again.

#### Expected behavior
Allow me to fix the URL

#### Observed behavior
See above.

#### Possible fixes
Make the text box editable after failure.

**Comment by lfbrock** [comment]
Hi @hank, thanks for the report - we've been trying to reproduce this but haven't had luck yet. 

Hopefully if other people can reproduce they'll comment here and it will help with tracking down the issue.

**Comment by enahum** [comment]
Haven't been able to reproduce this at all, I'm going to close this issue, but feel free to re-open if necessary
