### ISSUE TITLE
Cannot connect to server that uses HTTPS with alternative port

### ISSUE THREAD

**Issue by cassava** [mattermost/mattermost-mobile#494]
#### Summary
Because of proxy issues, my mattermost server uses HTTPS with a port > 1024; the android app seems to be unable to connect to it via the string `https://server.tld:27456`.

#### Environment Information

- Device Name: Moto G4
- OS Version: Android 7.0
- Mattermost App Version: Mattermost 2017 Beta (latest via Play Store)
- Mattermost Server Version: 3.8.2

#### Steps to reproduce
Try to log in to a server using HTTPS but with an alternative port.

#### Expected behavior
I would expect the App to be able to login to the server.

#### Observed behavior
With the browser I can log in to the alternative URL, but not with the app.

**Comment by lfbrock** [comment]
Hi @cassava - the new mobile apps only work with the latest server version, since they required some changes to the server to work. 

Would you be able to upgrade to the latest version?

**Comment by cassava** [comment]
Sorry! That was a typo on my part. I am using Mattermost Server Version 3.8.2. Double checked it again.

**Comment by lfbrock** [comment]
Ah okay thanks! Filed a bug ticket here to go look into it: https://mattermost.atlassian.net/browse/RN-98

**Comment by enahum** [comment]
@cassava I just tried this and I can connect just fine to https://elias.spinmint.com:27456 using the React Native apps for Android and IOS, is your certificate self-signed?

**Comment by cassava** [comment]
In General -> Configuration I had to click on "Purge All Caches", then it worked, thanks for the motivating example!
Would have been nice to know that before, though!

**Comment by cassava** [comment]
But now it doesn't work anymore and says it cannot connect to the server.. :-(
The address is https://iexu.de:62895

**Comment by enahum** [comment]
This thread has been inactive for a while, please feel free to re-open if needed
