### ISSUE TITLE
Are you getting ready for the iPhone 12 dpi?

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#4957]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
The statusbar goes up as shown below

https://github.com/mattermost/mattermost-mobile/issues/3606

#### Environment Information

- Device Name: iPhone 12 pro
- OS Version: 
- Mattermost App Version: 1.36.0
- Mattermost Server Version:

#### Steps to reproduce
After installing it on iPhone12 pro, you can see it immediately after turning it on.

#### Expected behavior
Appropriate spacing is required.

#### Observed behavior
The time part and the top status bar are very close.

#### Possible fixes
dpi?

**Comment by amyblais** [comment]
@josephbaylon Do you or someone else on QA have iPhone 12 to test this?

**Comment by enahum** [comment]
@amyblais a device is on its way in order for us to test this.

There is already a ticket to track https://mattermost.atlassian.net/browse/MM-30164 currently in the backlog until the device arrives.

**Comment by levidurfee** [comment]
The menu button is not clickable on the iPhone 12 mini. 

![66BE79D7-AE66-46A7-B585-527514410213](https://user-images.githubusercontent.com/10798199/99281325-5c627700-2800-11eb-917d-aa4600c02dbc.jpeg)

**Comment by enahum** [comment]
this is already resolved
