### ISSUE TITLE
Mattermost Classic is no longer working and Mattermost Mobile is not supporting Android 5 and 6

### ISSUE THREAD

**Issue by phpony** [mattermost/mattermost-mobile#4967]
### Summary
[Mattermost Android Classic](https://github.com/mattermost/mattermost-android-classic) is no longer working with latest [Mattermost Server](https://github.com/mattermost/mattermost-server) and [Mattermost Mobile](https://github.com/mattermost/mattermost-mobile) is not supporting Android 5.1 and 6. There's no way to use Mattermost on 11.5% + 16% = 27.5% of actual Android mobile devices...

#### Steps to reproduce
Ask any 4 people, one of them can't install working Mattermost App on his mobile phone.

#### Expected behavior
This app must support Android 5.1 and 6 or Mattermost Classic should be fixed.

#### Observed behavior
I have banking apps, messaging apps, games of all kinds working flawlessly on my Android 5.1. Slack? Yes. Telegram? Yes. Skype? Yes. Google Pay? Yes. Outlook? Yes. Discord? Yes. WhatsApp? Yes. Anything from top 500 on Google Play? Yes. Mattermost? No. Why? Yes, Lollipop and Marshmallow are 5 yo now. But does Mattermost Mobile rely on some kind of super specific API that was implemented only is Nougat? Vulkan 3D? Daydream virtual reality platform? I don't understand and is being stunned by fact that no one is bringing the strong reasons behind this strange unreasonable drop of 27.5% market share. Why Slack can provide a version for Android 5.1, and Mattermost can't? 

There's only one explanation provided:

> Android operating system 7+ [is required by Google.](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html)

And that is a lie. I've read this article back-and-forth and there's not a single word about "requirement of 7+" for apps.

#### Possible fixes
- Make Mattermost Mobile backwards compatible with 5+.
or
- Fix Mattermost Classic

**Comment by amyblais** [comment]
@phpony Can you help provide more details on the issues you're experiencing on the Classic App?

Does the newer app work https://play.google.com/store/apps/details?id=com.mattermost.rn&hl=en?

**Comment by phpony** [comment]
Classic app is stuck on loading screen after entering any server address.  Newer app can't be installed cause it don't support Android 5.1.

**Comment by larkox** [comment]
Closing as outdated. If this is still an issue, feel free to reopen it.
