### ISSUE TITLE
Unexpected emoji picker search results

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-mobile#4994]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Emoji search does not return the expected emojis

#### Environment Information

- Device Name: Samsun galaxy s10e
- OS Version: Android 10
- Mattermost App Version: 1.37.0 build 3000334
- Mattermost Server Version: 5.26.0 build 5.26.2

#### Steps to reproduce
1. Try to add a reaction to a message, click on the button to open the emoji search picker
2. Type `check` in the search field

#### Expected behavior
I would expect to see all emojis whose code contains `check`, and especially the `:white_check_mark:` as I always forget its full code.
 This expected behaviour is followed by the Mattermost webclient's emoji picker, that return the expected:
- `:checkered_flag:` 
- `:ballot_box_with_check:` 
- `:heavy_check_mark:` 
- `:white_check_mark:`

#### Observed behavior
On the Android app, the search results are as follow:
- `:checkered_flag:` 
- `:chicken:`

This list not only lacks the wished-for :white_check_mark:  emoji, but also throws in a mysterious, funny and yet sadly unwanted :chicken: .

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-30994

**Comment by amyblais** [comment]
> A small remaining concern if I may: why are the rest of the unmatched emojis still appearing in the popup list, sorted by alphabetical order? It messes with the ability to scroll quickly between matching emojis because you end up scrolling through unmatching emojis.

FYI @ashishbhate ^

**Comment by ashishbhate** [comment]
I've created a new ticket https://mattermost.atlassian.net/browse/MM-35620 for this follow-up issue.
