### ISSUE TITLE
Can not connect to server using self signed certificate

### ISSUE THREAD

**Issue by ws141** [mattermost/mattermost-mobile#500]
#### Summary
Can not connect to server using self signed certificate

#### Environment Information

- Device Name: iPhone 7
- OS Version: iOS 10.3.1
- Mattermost App Version: 1.0 (26) 
- Mattermost Server Version: 3.8.2

#### Steps to reproduce
Set up a Mattermost server and point a domain to it that is using a self signed certificate.

#### Expected behavior
The app should be able to connect to the server.

#### Observed behavior
The only thing I can see is an error message that looks like this.
![img_4577](https://cloud.githubusercontent.com/assets/1135081/25420667/74d3c6ca-2a59-11e7-8c93-d0ff560f19cd.PNG)

#### Possible fixes
Unfortunately not but the non beta version of the Mattermost app works fine towards the same server. 
Also I tested connecting the beta app towards https://pre-release.mattermost.com which works fine.
Additionally the Android beta app doesn't seem to have this issue with self signed certificates.

**Comment by Kinmarui** [comment]
Also doesn't work for cert issued by RapidSSL. I can send you domain I'm using in PM if you need it for tests. 
I can connect to server using web browser.

**Comment by lfbrock** [comment]
Hi @ws141 and @Kinmarui thanks for the report. 

We haven't added [support for self signed certificates yet](https://github.com/mattermost/mattermost-mobile/blob/master/CHANGELOG.md#beta-release), if anyone would like to look into what's necessary to get this to work it would be extremely helpful!

**Comment by Kinmarui** [comment]
@lfbrock thanks for response but since I had problem with cert issued by RapidSSL and not self signed and you didn't mention that it should not work for them I decided to create separate issue #519

**Comment by enahum** [comment]
@lfbrock can we add a help wanted ticket for this issue?

**Comment by naggie** [comment]
@Kinmarui I assume you've [added your self-signed CA certificate](https://stackoverflow.com/questions/42455377/how-to-install-self-signed-certificate-in-ios-10) to the iOS trusted store?

I assume the intention isn't to stop verifying the chain of trust to support self-signed certificates. HTTPS is pointless if you're not verifying the chain of trust.

-----


> Expected behavior
> The app should be able to connect to the server.

This is a _really_ bad idea -- if you mean blindly trusting the certificate.

**Comment by Kinmarui** [comment]
@naggie I only added intermediate certificate to server configuration for more info please read comment https://github.com/mattermost/mattermost-mobile/issues/519#issuecomment-299919312

I believe chrome probably had this intermediate certificate in his cert store that's why it worked on web but not mobile app. Mobile had missing link in chain where chrome had access to this intermediate cert even when I didn't added it to server configuration.

**Comment by naggie** [comment]
@Kinmarui that makes sense, thanks.

Nonetheless, I think mattermost should not allow connection to an unverified HTTPS URL.

**Comment by enahum** [comment]
Totally agree with @naggie here, you can always include support for that and build the app from source ;)

**Comment by gpr** [comment]
Self signed certificated and unknown CA chain should not be accepted by default but it should be possible to authorize them. Many companies manage their own certificates.

**Comment by enahum** [comment]
@grp you are more than welcome to add support for it ;)

**Comment by gpr** [comment]
@enahum I'm not so familiar with mobile app development but I would be happy to contribute I will have a look to the doc

**Comment by enahum** [comment]
We've decided that we are not going to add support for self signed certificates, if you need it please consider using something like lets encrypt or perhaps you'll want to include the support for it in your own custom build ;)

**Comment by ws141** [comment]
@enahum We've gone over to using a proper certificate but thanks for answering :)
