### ISSUE TITLE
Error occurred during build

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#5033]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Error occurred during build.

#### Environment Information

- Device Name: android
- OS Version: 
- Mattermost App Version: 1.37.0
- Mattermost Server Version:

#### Steps to reproduce
The build method we've been doing is as follows.
1. make pre-run
2. cd ./android && gradlew assembleRelease

but now, 
If I do the same as above, an error occurs.

> Task :react-native-webview:compileReleaseJavaWithJavac FAILED
/opt/mattermost-mobile/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:14: error: package android.support.annotation does not exist
import android.support.annotation.RequiresApi;
                                 ^

Here's how I built it now.
1. npm i
2. npm run ios-gems
3. npm run pod-install
4. npm run postinstall
5. cd ./android
6. ./gradlew assembleRelease

What is the correct order of build commands?

**Comment by enahum** [comment]
https://developers.mattermost.com/contribute/mobile/build-your-own/android/
