### ISSUE TITLE
Reflected XSS error in ios/Mattermost/AppDelegate.m

### ISSUE THREAD

**Issue by SayantanD** [mattermost/mattermost-mobile#5043]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
In security testing, getting Reflected XSS in ios/Mattermost/AppDelegate.m file, in line 123 and 126

#### Environment Information

- Device Name: N/A
- OS Version:  N/A
- Mattermost App Version: mattermost-mobile 1.38.0
- Mattermost Server Version: N/A

#### Steps to reproduce
Method - at line 123 of ios\Mattermost\AppDelegate.m gets user input for the url element. This element’s value then flows through the code without being properly sanitized or validated and is eventually displayed to the user in method - at line 123 of ios\Mattermost\AppDelegate.m. This may enable a Cross-Site-Scripting attack.

#### Expected behavior
Method - at line 123 of ios\Mattermost\AppDelegate.m gets user input for the url element. This element’s value then flows through the code without being properly sanitized or validated and is eventually displayed to the user in method - at line 123 of ios\Mattermost\AppDelegate.m. This may enable a Cross-Site-Scripting attack.

#### Observed behavior
In Security testing

#### Possible fixes
ios/Mattermost/AppDelegate.m:126
   return [RCTLinkingManager application:application openURL:url

ios/Mattermost/AppDelegate.m:123
   - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url

**Comment by enahum** [comment]
Hey @SayantanD i f you suspect you’ve found a vulnerability in the Mattermost mobile app, please report your findings to responsibledisclosure@mattermost.com. We ask you not to use public GitHub issues for reporting security issues.
