### ISSUE TITLE
Videos mp4 h.264 won‘t play anymore on iOS

### ISSUE THREAD

**Issue by justvanbloom** [mattermost/mattermost-mobile#5047]
#### Summary
Video in mp4 format encoded with h.264 does not start/play. Issue startet with latest Version of iOS Client. Bevor all was ok 

#### Environment Information

- Device Name: iphone
- OS Version: 14.3
- Mattermost App Version: 1.38 (build 337)
- Mattermost Server Version: 5.29.0

#### Steps to reproduce
1. Upload video on PC
2. Play on iOS

#### Expected behavior
Video starts playing

#### Observed behavior
Video play error

![8C6769A2-F1B8-45E6-BEE8-4D62060EF759](https://user-images.githubusercontent.com/1260205/102618657-77940f80-413b-11eb-8dc2-ec0462679656.png)

**Comment by amyblais** [comment]
This happens at times when the video cannot buffer correctly. We have a ticket open to improve on having the server perform better streaming of videos.

**Comment by capJavert** [comment]
Any updates on this?

**Comment by ellidi** [comment]
Bump.

**Comment by SilverFuzz** [comment]
Bump. We produce tons of videos and nothing works on ios, so we’re one week from trashing Mattermost after many years of use. What can we do?

**Comment by enahum** [comment]
@SilverFuzz as a work around in the gallery, you could attempt to "share" the video so it gets downloaded and played from the downloaded file instead of trying to stream it.

I'll look into adding an option to download the file in case the stream errors out, but that won't be included until the june release at the earliest.

**Comment by SilverFuzz** [comment]
That would be amazing! We have tried all sortsof waysto download videos via various browsers or VLC on ipad, but nothing works. I suppose there’s only a (broken) stream so nothing to download?

**Comment by larkox** [comment]
Closing as this should be solved already.
