### ISSUE TITLE
Mention Highlight Link Color

### ISSUE THREAD

**Issue by natewiebe13** [mattermost/mattermost-mobile#5081]
#### Summary
On mobile, then mention highlight text color is using the `Link Color` (`linkColor`) theme variable instead of `Mention Highlight Link` (`mentionHighlightLink`).

#### Environment Information

- Device Name: Pixel 5
- OS Version: Android 11
- Mattermost App Version: 1.38.1 (Build 3000338)
- Mattermost Server Version: 5.30.0 (Build 5.30.1)

#### Steps to reproduce
Set custom theme colors using the variables in the summary.

#### Expected behavior
Mention highlighting would use the `mentionHighlightLink` like the desktop client instead of using the `linkColor`.

#### Observed behavior
Mention highlighting is using the `linkColor` instead of the `mentionHighlightLink`.

Desktop (expected):
![Screenshot-20210105101459-264x100](https://user-images.githubusercontent.com/759228/103663412-104dcc00-4f3f-11eb-84d9-55b066b7a38a.png)

Mobile (observed):
![Screenshot-20210105101547-339x141](https://user-images.githubusercontent.com/759228/103663448-18a60700-4f3f-11eb-9054-d99dd7d3ebcf.png)

#### Other Note
On mobile the highlight also doesn't have a border radius, but that's less important than being able to read the mention.

**Comment by enahum** [comment]
FYI @matthewbirtch

**Comment by matthewbirtch** [comment]
> Mention highlighting would use the `mentionColor` like the desktop client instead of using the `linkColor`.

I believe you mean `mentionHighlightLink` rather than `mentionColor`?

**Comment by natewiebe13** [comment]
> > Mention highlighting would use the `mentionColor` like the desktop client instead of using the `linkColor`.
> 
> I believe you mean `mentionHighlightLink` rather than `mentionColor`?

Correct, I grabbed the wrong variable. I've updated the issue to reflect this.

**Comment by natewiebe13** [comment]
@matthewbirtch updated with screenshots as well to illustrate the issue.

**Comment by amyblais** [comment]
@enahum Would you like me to open a ticket for Mobile or UX?

**Comment by Dallasss7** [comment]
i have never contributed to this project but would like to start. may i please tackle this bug and have it assigned to me?

**Comment by enahum** [comment]
@Dallasss7 absolutely, maybe you can coordinate with @matthewbirtch so he can provide the right values to use in each use case.

@matthewbirtch would you be willing to open a ticket with the details and then we can generate the Help Wanted issue.

Thanks to both of you!

**Comment by enahum** [comment]
Hmmm not sure if @amyblais ended up opening the ticket. @amyblais can you please confirm?

**Comment by amyblais** [comment]
I haven't opened a ticket yet.

**Comment by matthewbirtch** [comment]
> @matthewbirtch would you be willing to open a ticket with the details and then we can generate the Help Wanted issue.

I created a Jira Ticket: https://mattermost.atlassian.net/browse/MM-31874. From what I can tell, this is only used in the post component when a username mention is highlighted. @enahum are you aware of any other location this occurs?

**Comment by enahum** [comment]
@matthewbirtch I wasn't talking about the location but as highlight when mention, or when a keyword other than a mention or who knows what else, I just want to make sure we cover all use cases

**Comment by matthewbirtch** [comment]
> @matthewbirtch I wasn't talking about the location but as highlight when mention, or when a keyword other than a mention or who knows what else, I just want to make sure we cover all use cases

From what I can tell we don't highlight for anything other than what triggers a mention. We don't currently highlight search terms in search results and I can't think of any use cases other than what user's have set as 'words that trigger mentions'
