### ISSUE TITLE
The downloaded image is not in the gallery

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#5101]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
The downloaded image is not in the gallery

#### Environment Information

- Device Name: Android
- OS Version: 
- Mattermost App Version: 1.38.1 
- Mattermost Server Version:5.30.1

#### Steps to reproduce
1. Touch an image in a conversation
2. Click the share icon at the bottom right
3.  Android sharing screen pops up
4. Click on gallery
5. Run Gallery, the Android default application
6. I just don't have that image

#### Expected behavior
Images shared to the gallery must be downloaded to the gallery.

#### Observed behavior

The downloaded image is not in the gallery

**Comment by amyblais** [comment]
@josephbaylon Are you able to reproduce this on Android?

**Comment by josephbaylon** [comment]
Depending on your Android device, the file share will not download the file to device directly anymore. Try sharing the file to either Google Photos or Google Drive and download from there.

**Comment by yewkay** [comment]
I've tested it on our colleague's Samsung Note 10 Plus, Samsung A41, Samsung Note 20 Ultra. It didn't appear in the gallery. 
We are trying to keep resources within our hosting environment and not wanting to reupload the files out of our servers, that's the whole premise of using Mattermost to have our privacy in our own control. Is there any other ways to let the files appear in the phone?

**Comment by amyblais** [comment]
> We are trying to keep resources within our hosting environment and not wanting to reupload the files out of our servers, that's the whole premise of using Mattermost to have our privacy in our own control. Is there any other ways to let the files appear in the phone?

Is this OS specific or is there any way we can improve this? // @enahum

**Comment by enahum** [comment]
@amyblais the functionality that we implemented in the gallery is to provide a way to share the files, regardless of the file type including images.

The OS provides the available options, we use to have a download option in the past but got replaced by sharing. We could ask UX to think about adding an option to save the files on top of sharing. iOS already gives the option to save them in the share options

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-32204

**Comment by daniel-jirca** [comment]
I too would like to have the option of downloading pictures sent via mattermost. The option to download is present in the web app, but not in the android app and it's very frustrating when you want to extract photos from a conversation.
