### ISSUE TITLE
PDFs don't open

### ISSUE THREAD

**Issue by tdittmar** [mattermost/mattermost-mobile#5102]
#### Summary
PDFs attached to a mattermost post do not open within the app. Instead, it displays the file name, "data" and information on the file size.

#### Environment Information

- Device Name: iPhone
- OS Version: iOS 14.3
- Mattermost App Version: 1.38.1 (Biold 338)
- Mattermost Server Version: 5.30.0 (Build 5.30.1)

#### Steps to reproduce
Attach a PDF to a post and try to open it by klicking the attachment.

#### Expected behavior
The PDF should be displayed.

#### Observed behavior
The PDF is not displayed, Instead, the app displays the file name, the file type "data" and information on the file size.

**Comment by amyblais** [comment]
@tdittmar Would you be open to sharing a screenshot of what you're seeing?

**Comment by tdittmar** [comment]
Of course. I've anonymized them a bit, but you will be able to see what I mean.

This screenshot shows the post that contains the PDF.

![IMG_3246](https://user-images.githubusercontent.com/4012492/104205819-22dc6f80-542f-11eb-8877-5dbdd70992d9.PNG)

When I tap on it, I see this:

![IMG_3247](https://user-images.githubusercontent.com/4012492/104205929-40113e00-542f-11eb-933d-a869f84d630b.PNG)

When I tap the "Open" button, I see this, instead of the preview.

![IMG_3248](https://user-images.githubusercontent.com/4012492/104205977-4c959680-542f-11eb-9c2a-6b902a3730b6.PNG)

The Android version of the app say there's no PDF viewer, even though I've installed Acrobat Reader in advance.

**Comment by amyblais** [comment]
This may be because of the dots in the filename. Would you be able to test by renaming the file on the mobile app by removing the dots from the filename?

**Comment by enahum** [comment]
I have a ticket related to this were we will attempt to open the file regardless of having multiple dots in the filename

**Comment by tdittmar** [comment]
OK, wow, it actually seems to work at least on the iPhone if I remove all the dots and just have a filename named "Separate Words.pdf". Thanks for the advice, still, it would be a great improvement to allow multiple dots and only consider the last part as the file extension.

**Comment by enahum** [comment]
Fixed by #5109
