### ISSUE TITLE
Login WebView on iOS doesn't support WebAuthn

### ISSUE THREAD

**Issue by vasimi** [mattermost/mattermost-mobile#5122]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
I can't login to the mobile app using SSO because I use WebAuthn key as a 2FA device and WKWebView doesn't support `navigator.credentials`

#### Environment Information

- Device Name: iPhone 12 Pro
- OS Version: iOS 14.4 Beta 2
- Mattermost App Version: 1.39.0
- Mattermost Server Version: 5.30.1

#### Steps to reproduce
Login with an SSO that requires you to use WebAuthn key (YubiKey etc.)

#### Expected behavior
`navigator.credentials` should be available so the SSO can use the WebAuthn key

#### Observed behavior
`navigator.credentials` isn't available because WKWebView doesn't support it as it isn't intended for authentication.

#### Possible fixes
https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession
I'm not an iOS dev, but I did some research and using ASWebAuthenticationSession instead of WKWebView should fix the issue (and it should also make the login smoother because it supports Keychain for entering credentials).

**Comment by enahum** [comment]
@anurag6713 will #5075 help resolve this?

**Comment by vasimi** [comment]
Looks like it could, Safari has no issues with using WebAuthn keys.

**Comment by anurag6713** [comment]
> @anurag6713 will #5075 help resolve this?

New implementation should solve this issue as the flow is in Safari now.

**Comment by vasimi** [comment]
Yup, Safari has no problems with using WebAuthn keys. Thanks, I hope this gets done soon! :+1:

**Comment by enahum** [comment]
Apparently this is resolved with #5075 feel free to re-open if it doesn't
