### ISSUE TITLE
App hangs/crashes

### ISSUE THREAD

**Issue by Faldoroc** [mattermost/mattermost-mobile#514]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
App locks/hangs/crashes when closing it with back-button

#### Environment Information

- Device Name: Samsung Galaxy S8
- OS Version: Android 7.0
- Mattermost App Version: 1.0(B 26)
- Mattermost Server Version: 3.7.0 (B 3.7.2)

#### Steps to reproduce
Open the app and hit back-button until the app closes. When opening the app again it just sits on the Mattermost logo forever.

#### Expected behavior
Have to go into app manager and force close the app and then restart it.

#### Observed behavior
No error, just hangs on the Mattermost logo

#### Possible fixes
Force close

**Comment by lfbrock** [comment]
Thanks @Faldoroc for the report - I think we have a fix for this issue, we're planning on releasing a build end of this week or beginning of next that should contain the fix.

**Comment by lfbrock** [comment]
This should be fixed now
