### ISSUE TITLE
Why do I have to log in every time I run it?

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#5145]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Each time I run the app, the login screen is launched.

#### Environment Information

- Device Name: iphone xr
- OS Version: 13.5.1
- Mattermost App Version: 1.39.0
- Mattermost Server Version: 5.30.0

#### Steps to reproduce
1. Pull the source with git. (or Download the compressed source code file with tar.gz.)
2. buid (I changed bundle identifier)
3. install
4. run the app

#### Expected behavior
The login status should be maintained regardless of the app exit.

#### Observed behavior
Mattermost received from the App Store is logged in even if you run it again after the app is closed.

However, if you download the source through git or download the source code and build it, you have to log in again every time you run the app.

**Comment by enahum** [comment]
@bitdessert what is it that you are changing in code that could cause this, cause there is no reson why it would happen to you if the app store version is using the same source code. I would advice for you to look closer to your changes as it sounds like a corrupted keychain, perhaps try removing the app from your device, restart the device and then go again?

**Comment by bitdessert** [comment]
1. git pull 1.39.0 or download the source code(.tar.gz)
2. npm i
3. open xcode
4. change bundle identifier
5. product->archive
6. Install the app on the iPhone
7. run->select server-> log in->success
8. Exit the app (running in the background) -> run the app -> Still logged in
9. Quit app (completely close even in background) -> run the app -> select server-> login

I think number 9 is an error. Not in previous versions (1.36.0, 1.38.0, 1.38.1.etc..)

**Comment by enahum** [comment]
Have you also updated the app group and keychain group in the entitlements? This is all done automatically if you use the scripts to build the app as stated in the docs

**Comment by bitdessert** [comment]
Of course. I also changed the app group and keychanin. All certifications were automatically completed.

**Comment by satryacode** [comment]
same here...

what I've done so far:
1. git clone https://github.com/mattermost/mattermost-mobile.git
2. cd Mattermost-mobile folder and then ran npm install
3. cd iOS and ran pod install
4. open project file in Xcode
5.  change bundle ids of app, share and notification. Changed App group, keychain sharing and iCloud containers.
6. Closed Xcode
7. ran the app to device via Xcode but error happens, said something related to connection error to 192.168.1.1:8081
8. add in package.json in script tag -> "build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'",
9. ran npm run build:ios
10. ran the app to device via Xcode but error happens again, said something related to connection error to 192.168.1.1:8081
11. then try to remove package related to notification like below
12. xcode -> target -> mattermost -> signing & capabilities -> delete push notification
13. xcode -> target -> mattermost -> signing & capabilities -> background modes -> uncheck remote notifications
14. then run the app to Xcode again, and it run successfully
15. Build -> Any iOS Device 
16. Product -> archive -> enterprise -> select elligible certificate
17. Prepare the OTA installer
18. Install successfully on a device
19. run the app -> login
20. quit the app from the background, and re-run the app, it needs to Login again

**Comment by satryacode** [comment]
![sign n capabilities](https://user-images.githubusercontent.com/1912381/106388185-f5705980-640f-11eb-90fc-972bf6e2630f.jpg)

here is my signing and capabilities section

**Comment by satryacode** [comment]
when running in debug mode,
I see this 
`[unspecified] log container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled`
But I have set the correct app group

**Comment by francislavoie** [comment]
Might not be exactly the same issue, but periodically on Android, I get kicked out of the app and need to sign in again. Sometimes it does it every time I kill the app until I reboot my device. Once rebooted, it continues to remember the auth token. I use Gitlab SSO to authenticate.

App Version: 1.39.0 (Build 3000341), from the play store.
Device: Pixel 4 XL, Android 11.

**Comment by satryacode** [comment]
> when running in debug mode,
> I see this
> `[unspecified] log container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled`
> But I have set the correct app group

I have resolved the issue with this change
the AppGroup is hardcoded in `ios/Mattermost/Info.plist`, `ios/MattermostShare/Info.plist` and `ios/NotificationService/Info.plist`
change the `AppGroupIdentifier` from `group.com.mattermost.rnbeta` to `YOUR_APP_GROUP`
then rebuild the app

**Comment by bitdessert** [comment]
thanks @satryacode, resolved

**Comment by softmastx** [comment]
@satryacode thanks a million!
