### ISSUE TITLE
Configured Push Notifications Do Not Create Notification Badge

### ISSUE THREAD

**Issue by Frichetten** [mattermost/mattermost-mobile#5176]
#### Summary
Push notifications when configured for "[Generic description with only sender name](https://docs.mattermost.com/administration/config-settings.html#push-notification-contents)" do not create a notification badge on the app icon.

#### Environment Information

- Device Name: iPhone 11
- OS Version: iOS 14.4
- Mattermost App Version: 1.39.0
- Mattermost Server Version: 5.30.0

#### Steps to reproduce
1. Configured the Mattermost application server for "Generic description with only sender name" notifications.
1 (a): As an administrator navigate to the System Console
1 (b): Navigate to Site Configuration > Notifications
1 (c): Under "Push Notification Contents" set it to "Generic description with only sender name"
1 (d): Click "Save" below
2. Setup the iOS app for notifications, and have someone in a channel say something to trigger a notification.

#### Expected behavior
A notification badge should be displayed on the Mattermost app icon to show a notification had been received.

#### Observed behavior
No such badge icon is received. The lock screen and banner notifications appear (both when the phone is locked and unlocked), and the notification sound also occurs. Additionally, I checked the Mattermost app settings and indeed badges is set to "on". 

#### Possible fixes
I'm unfortunately not familiar with the code base, and quite a bit of Googling has not shown any previous issues opened for this.

**Comment by amyblais** [comment]
I tested it but wasn't able to reproduce this, @josephbaylon would you be able to help test this?

**Comment by Frichetten** [comment]
If it helps at all, [here](https://www.youtube.com/watch?v=kvnzqk6ld1c&feature=youtu.be) is a video showing it. Note that I get the banner but no badge on the app icon. Additionally I should mention, the thing I'm doing to send the message is via the webhook integration. Under Integrations > Incoming Webhooks, I have a webhook that posts. Not sure if that makes a difference compared to another user.

**Comment by josephbaylon** [comment]
@amyblais @Frichetten I believe the app icon badge only increments with at-mention messages. I tried it on my device and it seems to work properly with at-mentions. Ordinary posts will not increment badge.

@Frichetten Can you please try sending an at-mention to the one receiving the message?

**Comment by Frichetten** [comment]
@josephbaylon, Yep that worked! Thank you for the information, I didn't know that at-mentions triggered the badge only. 

Is there a setting to enable badge incrementing for non at-mentions? I ask because, while I do get the banners in notification center, they kind of get lost in the backlog for me and I end up missing messages. For most apps the badge is what get's my attention to go in and check things out. No pressure if there isn't a way to do this!

**Comment by josephbaylon** [comment]
@Frichetten Thanks for testing the at-mention. Unfortunately, we currently don't have a configuration to increment non at-mentions.

If it's an important feature, it may be worthwhile to post to the public [Developers: Mobile](https://community.mattermost.com/core/channels/native-mobile-apps) channel to see if it can be done by mobile developers
