### ISSUE TITLE
ruby/config.h not found

### ISSUE THREAD

**Issue by matpascaud** [mattermost/mattermost-mobile#5181]
#### Summary
Cannot build with npm install, getting an error when installing json 2.5.1 with native extensions.
fatal error: 'ruby/config.h' file not found

#### Environment Information

- Device Name: iPhone X
- OS Version: 10.15.6
- Mattermost App Version: 1.40.0 (build 345)
- Mattermost Server Version:

#### Steps to reproduce
Run npm install with Xocde 12.4

#### Expected behavior
Should run without error

#### Observed behavior
Installing json 2.5.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"

**Comment by enahum** [comment]
Maybe take a look at this, was the first result after searching the web https://stackoverflow.com/questions/53135863/macos-mojave-ruby-config-h-file-not-found

**Comment by matpascaud** [comment]
I saw that and tried cd /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19 but could not make it work.
And using rbenv to install another version of ruby might lead to problem. If I do no find any other solution, I will try that.

**Comment by enahum** [comment]
I use rvm and works without issues

**Comment by matpascaud** [comment]
I used rvm to solve the problem :
`brew install rbenv ruby-build
echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile 
rbenv install 2.6.3
rbenv global 2.6.3`
