### ISSUE TITLE
iOS App cannot connect while on celluar

### ISSUE THREAD

**Issue by officiallymarky** [mattermost/mattermost-mobile#5184]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When off Wifi, the app no longer can connect.

#### Environment Information

- Device Name: iPhone X
- OS Version: 14.4
- Mattermost App Version: 1.39.0
- Mattermost Server Version: 5.30.0

#### Steps to reproduce
How can we reproduce the issue?

Disable wifi

#### Expected behavior
Describe your issue in detail.

Service as normal

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.

![image](https://user-images.githubusercontent.com/33408375/108613288-6d51f400-73be-11eb-8521-8b2ea2a9588f.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

Connect to wifi

**Comment by enahum** [comment]
As you can see in the attached screenshot I'm able to connect to our community server without wifi just fine!
[Uploading 108613335...]

**Comment by officiallymarky** [comment]
Oh if it works for you then I must be making it up.

**Comment by enahum** [comment]
It could just be that the request to get the teams you belong failed for some reason

**Comment by officiallymarky** [comment]
For sure it is some reason, that's what I'm trying to figure out
I turn off Wifi, I can't connect, turn it on, it works.

**Comment by officiallymarky** [comment]
You can see the behavior here.

https://www.youtube.com/watch?v=bFbi85yTaEY

**Comment by enahum** [comment]
If you go to your phone settings and look for Mattermost, is cellular data enabled?

![image](https://user-images.githubusercontent.com/6757047/108615418-a3a16a80-73e2-11eb-9867-52e6b275a369.png)

**Comment by officiallymarky** [comment]
Yes, and I toggled it to see if maybe it was somehow thinking it wasn't enabled.

**Comment by enahum** [comment]
Can you reach the server by entering the url in chrome or safari while on cellular network?

**Comment by enahum** [comment]
What about connecting to https://community.mattermost.com ?

**Comment by officiallymarky** [comment]
https://community.mattermost.com loads on Wifi and Cellular.
The server I'm trying to access only works on Wifi, off wifi if I go to the site directly I'm getting an SSL error.

**Comment by enahum** [comment]
Then it doesn't seem to be an app issue.. sadly can't say for sure what it could be

**Comment by officiallymarky** [comment]
resolved, looks like it was an ipv6 issue on the server
