### ISSUE TITLE
Bot message doesn't display content/attachment

### ISSUE THREAD

**Issue by CmdrSharp** [mattermost/mattermost-mobile#521]
#### Summary
When bots post a message containing only an attachment (which is what our integration does), it only displays an empty message in the app.

#### Environment Information

- Device Name: OnePlus 3T
- OS Version: Android 7.1.1, Oxygen OS 4.1.3
- Mattermost App Version: 1.0, Build 26
- Mattermost Server Version: 3.8.2

#### Steps to reproduce
Post a bot message with only an attachment.

#### Expected behavior
The message should display.

#### Observed behavior
An empty message is shown.

#### Possible fixes

**Comment by lfbrock** [comment]
Thanks @CmdrSharp - sounds like this is likely the same issue as #435, we have a ticket here to track the issue: https://mattermost.atlassian.net/browse/PLT-5974

I'll talk to the team today about increasing the priority of adding support for this, so people aren't missing message content when they use the app.

**Comment by lfbrock** [comment]
Plan is to get this added within the next couple weeks, closing this issue and will track with the other one (https://github.com/mattermost/mattermost-mobile/issues/435)
