### ISSUE TITLE
When 5 images are uploaded, sliding does not work.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#5217]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When 5 images are uploaded, sliding does not work.

#### Environment Information

- Device Name: galaxy s8+
- OS Version: android 9
- Mattermost App Version: 1.40.0(build 3000345)
- Mattermost Server Version: 5.32.1

#### Steps to reproduce
Upload 5 images( with gif image)
Click on any image to slide.
Sliding stops at the gif image.
But, It may not be a gif image problem. Sliding stops at the 3rd or 4th image.
The order of the title bar cannot be changed.

#### Expected behavior
It should be sliding.
With the same images, sliding works normally on Android 10.

#### Observed behavior
A gif file is included in the middle of the image.
The order of the images is as follows.
jpg -> jpg -> jpg -> gif -> jpg

jpg->jpg->jpg->jpeg->jpg

jpg->jpg->jpg->jpg->jpg

It slides up to the third image. Don't go on to the fourth.
Tapping the fourth image will slide to the fifth image. 
However, it slides forward and does not slide back.

**Comment by amyblais** [comment]
@josephbaylon Do we have Android 9 to test this on?

**Comment by amyblais** [comment]
Thanks, ticket: https://mattermost.atlassian.net/browse/MM-33671
