### ISSUE TITLE
Press the back button while sharing an image, the app crashes.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#5218]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Press the back button while sharing an image, the app crashes.

#### Environment Information

- Device Name: 
- OS Version: android 9
- Mattermost App Version: 1.40.0
- Mattermost Server Version: 5.32.1

#### Steps to reproduce
1. Upload 5 images.
2. Tap the image.
3. Click the Share button.
4. While the image is being prepared, press the back button.
5. When the pop-up disappears, tap another image.
6. The app freezes.

#### Expected behavior
When the back event occurs in Android, the image being prepared should be stopped.
Another image should open normally.

#### Observed behavior
The app freezes.

The above error does not occur for files that have already been prepared(downloaded).
Since the progress bar does not pop up for files that have already been prepared (downloaded), 
other images will open normally even if you click Back.

#### Possible fixes
It is shown related to the prepare_files.tsx file of the gallery component.

**Comment by enahum** [comment]
@bitdessert would you be willing to submit a PR to fix this?

**Comment by bitdessert** [comment]
Thank you for the suggestion @enahum, but I can't because I have a job.

**Comment by enahum** [comment]
Alright thank you

**Comment by amyblais** [comment]
@josephbaylon Are you able to repro this on Android, and can you open a ticket?

**Comment by amyblais** [comment]
@enahum Were you able to repro this?

**Comment by enahum** [comment]
@amyblais Yes

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-33778
