### ISSUE TITLE
iOS 1.41.0 Crashes Frequently As Documents and Data gets too large

### ISSUE THREAD

**Issue by ryankern43** [mattermost/mattermost-mobile#5243]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Users find the iOS app crashes frequently (more than Android) when uploading and sharing multiple pictures into private channels.

#### Environment Information

- Device Name: iPhone 12
- OS Version: 14.4.1
- Mattermost App Version: 1.41.0 (Build 347)
- Mattermost Server Version: 5.28.0 (Build 5.28.1)

#### Steps to reproduce
1. Create a private channel with lots of pictures and attachments already
2. Attempt to attach 4 more at the same time.
3. Send and eventually app times slows down and crashes when the cached documents and data gets too large. Seems to have noticeable slowdown and crashes after about 400-500MB of cached data (EDIT: 500MB seems to be a tipping point). Frequent crashes at around 900MB.

![IMG_2188](https://user-images.githubusercontent.com/79869579/112516345-8eb35080-8d6d-11eb-9562-1164fec4f116.PNG)

Can reach this within several days if users are regularly sharing pictures to a channel.

#### Possible fixes
Clearing cached data seems to help. Tapping "Delete Documents & Data" under Advanced settings frequently seems to help keep the app from crashing.

**Comment by ryankern43** [comment]
Our specific use that is causing this issue is our QA department sharing pictures from their patrols. They regularly take 4 pictures with their phones, three of them are one from each side, then a picture of the barcode. They share these four pictures to a channel for each line, and they do this patrol every two hours. 

A member of our QA team will share about 60 pictures from their phones a night. Which means this threshold where the app starts to slow and crash is hit fairly frequently.

**Comment by amyblais** [comment]
@ryankern43 What error message do you see when the crash occurs?

**Comment by ryankern43** [comment]
No error. It crashes to home screen. Reopening the app will resume as if nothing happened, but then crash again if you continue trying to upload pictures or scrolling the channel. Trying to capture video, but it crashes video capture as well.

**Comment by amyblais** [comment]
@migbot / @josephbaylon Can you reproduce / is this a known issue?

**Comment by josephbaylon** [comment]
@ryankern43 If you can, please recreate a private channel that will crash on iOS with the large documents in community.mattermost.com through the webapp/desktop and add the following users
- `@joseph.baylon`
- `@miguel.alatzar`
- `@elias`
- `@amy.blais`

**Comment by larkox** [comment]
@ryankern43 are you still seeing this issue in the latest beta? (V2)
