### ISSUE TITLE
Notifications from same user/channel stack on top of eachother instead of replacing

### ISSUE THREAD

**Issue by MattBred** [mattermost/mattermost-mobile#526]
#### Summary
Notifications stack on top of eachother, even from the same user/channel. If you get 4 messages, you get 4 notifications. This isn't ideal, as it can flood the notification bar.

#### Environment Information

- Device Name: Nexus 5
- OS Version: Android 6.0.1
- Mattermost App Version: 1.0 (Build 26)
- Mattermost Server Version: 3.7.0 (Build 3.7.1)

#### Steps to reproduce
Option 1) Set notifications to receive direct mentions, then receive a direct message twice from the same person. You'll get two notifications.

Option 2) Set notifications to receive all, and have someone post in the same channel twice. Or two seperate people. You get two notifications.

I am unsure if this problem exists on iOS.

#### Expected behavior
This is debatable, but I think notifications should be linked to a channel. If you get one notification from "Offtopic" from user A, and user B also posts in "Offtopic" channel, then user B's notification should over-write the notification from user A. Private messages would just overwrite.
Different channels should have different notifications, so you get some context.

#### Observed behavior
Every notification seems to be a completley new notification, never overwriting previous ones.

#### Possible fixes
I briefly went over the code, it appears to be using the react-native-push-notification library. You should be able to set an id for the message in it. I know it's possible to do this in Android, unsure of how in iOS. http://stackoverflow.com/questions/42703830/delete-previous-notifications-using-react-native-push-notification shows it possible to overwrite for Android by setting the "id".

**Comment by jnbt** [comment]
I think this would be a strange behavior compared to other messaging apps. E.g. in a WhatsApp group Chat you also receive push notifications for every message. They also stay in the Notification Center. This allows to follow the conversation w/o opening the app.

**Comment by MattBred** [comment]
Maybe an option to switch? I end up looking at my phone and there's 20 notifications from mattermost and I find it really annoying - especially when a lot of them are private messages.

**Comment by tbennun** [comment]
PR #624 should solve this issue, right?

**Comment by enahum** [comment]
Closed via #624 and soon to be improved with bigTextStyle
