### ISSUE TITLE
[Help Wanted] Update the formatting of markdown block quotes

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#529]
If you're interested please comment here and come [join our "Native Mobile Apps" channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/mobile-developer-setup.html).

----
**Notes:** [Jira Ticket](https://mattermost.atlassian.net/browse/RN-112)

Update the formatting for markdown block quotes (`> block quote`):

<img width="239" alt="screenshot 2017-05-02 10 36 08" src="https://cloud.githubusercontent.com/assets/9354841/25956045/bfce9f98-3638-11e7-9bc5-64524789b04f.png">

**Comment by cpanato** [comment]
I didnt found the icon `fa-quote-left` if come from where ?

**Comment by enahum** [comment]
fixed by #538
