### ISSUE TITLE
Add app icon files for iOS

### ISSUE THREAD

**Issue by thomchop** [mattermost/mattermost-mobile#53]
We'll copy over the existing app icons from the [android](https://github.com/mattermost/android/tree/master/app/src/main/res) and [ios](https://github.com/mattermost/ios/tree/master/Mattermost/Images.xcassets/AppIcon.appiconset) repos.

**Comment by hmhealey** [comment]
We also need to add icons for iOS 10 and iPhone 7

**Comment by thomchop** [comment]
Completed by #72. We can open another ticket for missing icons (iOS 10 / iPhone 7).
