### ISSUE TITLE
Push notifications on Mobile

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-mobile#5315]
I’m not receiving push notifications on my device ...

@Adovenmuehle @bryanculver  @rthill  @chikei  @phuihock 

I did all these steps :
https://docs.mattermost.com/mobile/mobile-testing-notifications.html

BUT ... But nothing happened ...

**Comment by amyblais** [comment]
1. Are you using any type of proxy in front of Mattermost or a load balancer?
2. What is the **Notifications** config set to on the mobile OS level (iOS and Android)?
3. What is the **Notifications** config set to on the Mattermost app level? - **Settings > Notifications > Mobile and Settings > Notifications > Mentions and Replies**.
4. What is the status of the user when the unread push notifications came in (Online / Away / Do Not Disturb / Offline?

**Comment by enahum** [comment]
Adding to the questions:
- what push proxy server is being used by your Mattermost server?
- if you inspect your user session using the webapp under **Account Settings -> Security -> View and logout of active sessions** do you see an active native app session?
- have you insoected the mattermost server logs and notification logs?

If you don't have access to your Mattermost admin console or logs, please ask an Administrator to do so for you

**Comment by majidit** [comment]
Thank you for your guidance
We are working on it
