### ISSUE TITLE
[Help Wanted] Add flag icon on flagged posts

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#532]
If you're interested please comment here and come [join our "Native Mobile Apps" channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/mobile-developer-setup.html).

----
**Notes:** [Jira Ticket](https://mattermost.atlassian.net/browse/RN-44)

This ticket is to add UI that shows when a post is flagged: 

- When a post is flagged, show a flag icon (see screenshot). 
- Clicking on the flag should unflag the post.
- When a post is unflagged, don't show any icon. 

![screenp 2](https://cloud.githubusercontent.com/assets/9354841/25957892/51c4e872-363d-11e7-98bc-77d5141ff79e.jpg)

**Comment by mkraft** [comment]
I'll take this one.
