### ISSUE TITLE
Send voice message

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-mobile#5326]
Hello to all dear friends
Why can't you send a voice message in the mobile version?
This is a basic need and our team users have requested it a lot

@Adovenmuehle @bryanculver @rthill @chikei @phuihock

**Comment by enahum** [comment]
For anyone interested this was answered here https://community.mattermost.com/core/pl/sxot6hjn9bbzixp474brwydtio

**Comment by alexander-potemkin** [comment]
@enahum , I followed the link and for the future reference of anyone looking for that feature, here is the content:

> <...> at times on mobile would be easier & faster just to send a voice message and that’s it. Truth of the matter is that it was a feature that never got prioritized or planned.
> 
> However there is a branch from a hackathon project done about 1.5 years ago here that has support for that feature.. perhaps you can find the time or someone on your team to work on it, basically the branch is to old, so porting the work done from there to the master branch would be easier than rebasing and obviously it would need to get polished and whatnot... if this is something you or your team cannot help contribute for any reason, then maybe it would be good to start a conversation with a PM in the ~Feature Proposals channel

It also links to https://github.com/mattermost/mattermost-mobile/tree/voice-message

As I heard on some of the thread, mobile client changes are coming - won't they include that one as well?

If not, how can I contribute this to the main source code? What will be required, so that I could estimate and commit, if I can manage that?

**Comment by alexander-potemkin** [comment]
and, btw, I understand, that server plugins (https://developers.mattermost.com/integrate/plugins/mobile/) - is another way of achieving this, paired with https://github.com/streamer45/mattermost-plugin-voice ?

**Comment by enahum** [comment]
Not a feature that I'm aware of, the branch you linked was a hackathon project and is extremely old and not near production ready. I'd recommend reaching out to a PM instead.

**Comment by alexander-potemkin** [comment]
any clue who is that and how to do that?

**Comment by enahum** [comment]
You can always join our clmmunity server at https://community.mattermost.com you'll gind most of the staff there and conversations about everything we are working on and all that. Feel free to get involve in the conversations :)

**Comment by alexander-potemkin** [comment]
Thank you, I'm in, actually...
What is the right channel or who is the right person to approach in my specific case, to get an understanding on what needs to be done to estimate the costs and probably implement it, is it something you can assist? Or shall I just shout on Town Square for that, @enahum ? =)

**Comment by enahum** [comment]
I would suggest the [Feature proposals](https://community-daily.mattermost.com/core/channels/feature-ideas) channel
