### ISSUE TITLE
Mattermost iOS v1.42.0 crashes at launch

### ISSUE THREAD

**Issue by mthld** [mattermost/mattermost-mobile#5336]
#### Summary
Mattermost iOS v1.42.0 crashes at launch.

#### Environment Information
- Device Name: Apple iPhone SE (2nd gen)
- OS Version: iOS v14.4.2
- Mattermost App Version: v1.42.0
- Mattermost Server Version: v5.33.3

#### Steps to reproduce
Update the iOS app from the appstore to the desired version, open it, see it crash.

#### Expected behavior
The app should be launching.

#### Observed behavior
First launch:
![IMG_2633](https://user-images.githubusercontent.com/41020854/115106097-1c482180-9f63-11eb-903c-0afa57713a66.PNG)

Tap Relaunch and wait:
![IMG_2635](https://user-images.githubusercontent.com/41020854/115106110-3a158680-9f63-11eb-8c15-ebed2677ebb1.PNG)

#### Possible fixes
No idea, really.

**Comment by lsochanowski** [comment]
+1

**Comment by zer0init1** [comment]
Hi all.
This is not server problem. I checked the network traffic and found that the error appears before the start of communication with the Mattermost server. The problem is present on IOS 14.4.2 and with the latest version of the Mattermost app v1.42.0 from the App Store. 

It only helps to remove the Mattermost application from the IOS device, and reinstall it from the App Store.

**Comment by lsochanowski** [comment]
> Hi all.
> This is not server problem. I checked the network traffic and found that the error appears before the start of communication with the Mattermost server. The problem is present on IOS 14.4.2 and with the latest version of the Mattermost app v1.42.0 from the App Store.
> 
> It only helps to remove the Mattermost application from the IOS device, and reinstall it from the App Store.

true it helps

**Comment by amyblais** [comment]
@enahum @migbot FYI

**Comment by amyblais** [comment]
We have pushed a v1.42.1 dot release to the app stores that fixes this issue. It should be available for download soon.
