### ISSUE TITLE
[Help Wanted] Adjust quality setting for images

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#535]
If you're interested please comment here and come [join our "Native Mobile Apps" channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/mobile-developer-setup.html).

----
**Notes:** [Jira Ticket](https://mattermost.atlassian.net/browse/RN-122)

Change the quality setting for images from 0.5 to 0.7.
https://github.com/react-community/react-native-image-picker#options

**Comment by cpanato** [comment]
PR: https://github.com/mattermost/mattermost-mobile/pull/537
