### ISSUE TITLE
[Help Wanted] Update animation on channel loading screen

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#536]
If you're interested please comment here and come [join our "Native Mobile Apps" channel](https://pre-release.mattermost.com/core/channels/native-mobile-apps) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/mobile-developer-setup.html).

----
**Notes:** [Jira Ticket](https://mattermost.atlassian.net/browse/RN-37)

Add an animation to the channel loading screen.

![animation 1](https://cloud.githubusercontent.com/assets/9354841/25966244/75126de8-3658-11e7-81c5-501972fa27f8.gif)

See https://github.com/TBouder/react-native-placeholder for reference.

**Comment by awitherow** [comment]
@lfbrock so the idea here is to create this these greyed out block placeholders to appear as multiple users "icon", "name" and "text"?

**Comment by enahum** [comment]
Yes this is something that we already have but without the animation, so the idea is to change it so it has an animation during the time it appears on screen while the posts for the loaded channel are fetched from the server

**Comment by sudheerDev** [comment]
I will take this up.

**Comment by koxen** [comment]
@sudheerDev I don't think re-adding this channel loading screen is a good idea. But if you could do kindof opacity transition between two loaded PostLists, that should look good :)
