### ISSUE TITLE
Easy switch between servers

### ISSUE THREAD

**Issue by adanielvv** [mattermost/mattermost-mobile#5370]
It should be easier to switch between servers on the app, or you need to be able to connect multiple servers.

Just like you can easily switch between gmail accounts. Only remembering the URLs is already a big improvement.

**Comment by esethna** [comment]
Hi @adanielvv, thanks for this. Multi-server support is the most requested feature for our mobile app and we're working on the infrastructure to support it in our mobile app v2, releasing in beta at the end of the year. Check out the designs here: https://www.figma.com/file/a9w2q3JnVvBwo2IScP8j3K/Phase-1-Design?node-id=110%3A3

**Comment by adanielvv** [comment]
Wow, looks real nice. For now I think we are going to use Discord, but Mattermost is a close second.
