### ISSUE TITLE
MessageSource is not respected when editing a message

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-mobile#5381]
#### Summary
When a post's `MessageSource` [(here's the server-side definition](https://github.com/mattermost/mattermost-server/blob/fc0dbe0ace7414bfad5ac76bb2ed02cc99612194/model/post.go#L86)) is present, it is not used by the app to prefill the edit box (the post's `Message` is used instead), contrary to the behavior of the webapp. 

While `MessageSource` is mainly used by the image proxy right now, this prop could be pretty useful for plugins&apps development, but only if it's behavior is coherent among all clients.

#### Environment Information
  - Device Name: Samsung Galaxy S10e
  - OS Version: Android 11
  - Mattermost App Version: 1.42.1
  - Mattermost Server Version: 5.33.2

#### Steps to reproduce
- Activate the local image proxy on the Mattermost server
- Using the app, write a new message that contains an inline image, eg. 
```
![this is an inline image](https://upload.wikimedia.org/wikipedia/en/0/0c/Grumpy_cat_on_landing.jpg)
```
- Post the message
- Use the menu to open the Edit box for this message

#### Expected behavior
The Edit box should be prefilled with the unaltered user input (=the `post.MessageSource`): 
```
![this is an inline image](https://upload.wikimedia.org/wikipedia/en/0/0c/Grumpy_cat_on_landing.jpg)
``` 

#### Observed behavior (that appears unintentional)
The Edit box is prefilled with the message edited by the proxy filter (=the `post.Message`)
```
![this is an inline image](https://yourmattermostserverurl.net/api/v4/image?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fen%2F0%2F0c%2FGrumpy_cat_on_landing.jpg)
```

#### Possible fixes
Applying [the webapp's logic](https://github.com/mattermost/mattermost-webapp/blob/e4503ab1169dad4f208647e37fd28dd78922d8ad/components/edit_post_modal/edit_post_modal.jsx#L79) in [edit_post](https://github.com/mattermost/mattermost-mobile/blob/b07fc7ef04ed84ae783f4fed547debf522138102/app/screens/edit_post/edit_post.js#L66) but we would also need to add the `message_source` prop everywhere it's needed, like in the `Post` [definition](https://github.com/mattermost/mattermost-mobile/blob/b07fc7ef04ed84ae783f4fed547debf522138102/app/mm-redux/types/posts.ts#L64).

**Comment by josephbaylon** [comment]
@amyblais I'm able to reproduce this. However, I'm not sure if it's expected for mobile. I'll let @enahum chime in.

**Comment by enahum** [comment]
@josephbaylon no this is not expected unless someone from a feature team made a change and did not reflect it on mobile.
