### ISSUE TITLE
App loses focus on text-field when specialcharacters are input with blackberrykeyboard

### ISSUE THREAD

**Issue by iameru** [mattermost/mattermost-mobile#5429]
#### Summary
Mattermost on Android escapes (or loses its focus) text-input-field when entering character using 'sym' key on blackberry key one with real keyboard (no touchpad).

### Environment Information
  - Device Name: blackberry key one
  - OS Version: android 8.1
  - Mattermost App Version: 1.43
  - Mattermost Server Version: 5.35 

#### Steps to reproduce
Should be reproducible using the device, maybe others from bb

#### Expected behavior
Happily input any text without getting thrown out of text-input and having to click on it again and again. 
(),*äü;  (these and many more very often used signs are accessed via sym-key)

#### Observed behavior (that appears unintentional)
In all other chat-apps this is not a problem and I can just happily type away in my language. Im using symkey alot to quickly type Ü Ä Ö and other "umlaute" and special characters. only mattermost kicks me out of the textfield after input of the chosen letter.

**Comment by amyblais** [comment]
@josephbaylon Are you able to reproduce?

**Comment by larkox** [comment]
@iameru Is this still an issue for you? Have you tried with the latest beta version (v2)?

**Comment by iameru** [comment]
> @iameru Is this still an issue for you? Have you tried with the latest beta version (v2)?

I dont own this device anymore. If you would like I could borrow it from a friend and try it again.

**Comment by larkox** [comment]
Always happy to have someone test it, but if it is much of an issue for you, we can close this issue now, and reopen it if someone have the same issue again in the future.
