### ISSUE TITLE
MM iOS share screen issues

### ISSUE THREAD

**Issue by alexander-potemkin** [mattermost/mattermost-mobile#5441]
#### Summary
iOS's share screen have an ugly halo; very small place to choose the destination.

### Environment Information
  - Device Name: iPad Pro 11, 12.9
  - OS Version: 14.4.2
  - Mattermost App Version: 1.43.0 (356 build)
  - Mattermost Server Version: 5.35.0 (build 5.35.2)

#### Steps to reproduce
Choose share anything on iOS, tap MatterMost, enjoy!

#### Expected behavior
No background 'halo', bigger screen allowing to choose the destination / address to share to.

#### Observed behavior (that appears unintentional)
Please, see attached.
![IMG_0237](https://user-images.githubusercontent.com/2323840/121320725-17c23880-c916-11eb-942f-b1d5760bbffe.PNG)
![IMG_0238](https://user-images.githubusercontent.com/2323840/121320830-2f012600-c916-11eb-9660-1401c3a09164.PNG)

#### Possible fixes
As per expected behaviour; Slack's share is pretty good also.

**Comment by amyblais** [comment]
We have a ticket here: https://mattermost.atlassian.net/browse/MM-31757.

**Comment by alexander-potemkin** [comment]
Thanks. I did GitHub issues search first, but not the Jira.
By the way, am I right in understanding that GitHub Issues is more like a support, while is used for the actual development planning?

**Comment by amyblais** [comment]
That's correct!

**Comment by alexander-potemkin** [comment]
Got it, thanks!
