### ISSUE TITLE
iOS - blank content after thread answer or adding photos with text

### ISSUE THREAD

**Issue by fpeterschmitt** [mattermost/mattermost-mobile#5463]
#### Summary

Each time i navigate in a discussion thread or try to upload more than one photo (after navigation), the app goes blank with only the "blue bar" displayed.

I have to restart the app completely in order to recover.

### Environment Information
  - Device Name: iPhone 7
  - OS Version: 14.6
  - Mattermost App Version: 1.44.0
  - Mattermost Server Version: 5.36.0

#### Steps to reproduce

 * Clean mattermost installation with no plugin
 * No proxy whatsoever, i setup a fresh installation on a LAN. **Please note that i have the same behaviour with or without a reverse proxy, and that this problem is happening for more than a year now.**
 * Configure the chat server to `http://<local.ip>:8065`
 * Successfully access the team
 * Send messages successfully
 * Replying to a thread or sending more than one photo triggers the bug

Two things:

1. The bug seems to trigger when exiting the thread after tapping the input field (showing the keyboard). Even if i collapse the keyboard, the bug still triggers.
2. For photos, tapping the "add photo" button while having triggered the keyboard trigger the bug.

#### Expected behavior

Still being able to navigate in the application, see messages etc…

#### After login:

![image](https://user-images.githubusercontent.com/4390126/122360525-ba9e3680-cf56-11eb-9a02-246fd523c51c.png)

#### Replying to a thread:

![image](https://user-images.githubusercontent.com/4390126/122360554-c25ddb00-cf56-11eb-961a-a3c2a3d5b292.png)

#### Message successfully sent in thread:

![image](https://user-images.githubusercontent.com/4390126/122360602-cc7fd980-cf56-11eb-91a7-45dc3f8fc860.png)

#### Exiting the thread to view the entire channel:

![image](https://user-images.githubusercontent.com/4390126/122360663-d9043200-cf56-11eb-8005-cfdffb01e51d.png)

#### Now switching channel:

![image](https://user-images.githubusercontent.com/4390126/122360692-e15c6d00-cf56-11eb-9c8c-8c5b79148580.png)

#### Switching channel again:

![image](https://user-images.githubusercontent.com/4390126/122360739-ea4d3e80-cf56-11eb-8d82-c7dbff73e3a2.png)

#### After restarting the app:

![image](https://user-images.githubusercontent.com/4390126/122361142-43b56d80-cf57-11eb-98bd-e90daef06aed.png)

**Comment by amyblais** [comment]
@josephbaylon Can you reproduce this?

**Comment by Leryan** [comment]
> @josephbaylon Can you reproduce this?

If there is a possibility to install and test with a "debugging version" of the app, i'll be more than happy to do so :)

**Comment by josephbaylon** [comment]
@amyblais I'm not able to repro this issue.

**Comment by amyblais** [comment]
cc @enahum if you have any thoughts on this.

**Comment by enahum** [comment]
This is the first time I'm seeing this, happening for more than a year? interesting... cause no one and I mean no one as had an issue like that.. Also I doubt is data driven as @Leryan says he is seeing this on a newly installed server.

@Leryan is this only happening to you on your iPhone 7? does it happen on other iOS devices or to anyone else using your deployment?

**Comment by Leryan** [comment]
> This is the first time I'm seeing this, happening for more than a year? interesting... cause no one and I mean no one as had an issue like that.. Also I doubt is data driven as @Leryan says he is seeing this on a newly installed server.

I also find this very strange indeed.

> @Leryan is this only happening to you on your iPhone 7? does it happen on other iOS devices or to anyone else using your deployment?

I'm alone having this problem, other iOS users have more recent iPhones than me :)

Could it be from the OS itself with consecutive upgrades?

If i'm alone having this, the chances it's from my device are quite high.

Any chance to get a debug build though?

**Comment by Leryan** [comment]
fyi, i've set zoom and text size to their default values, deinstalled the app, rebooted, reinstalled, and same behaviour. so it's not related to a "display" problem.

if having a "debug" build is impossible i'll reset the entire phone and retry 🤷

**Comment by enahum** [comment]
@Leryan the best way to get a "debug"  build is to clone the repo and run it in development mode.. "Debug builds" is not something that we can easily distribute

**Comment by Leryan** [comment]
I found the bug I think: in Accessibility parameters, Motion settings, enable "Reduce Motion" and "Prefer Cross-Fade Transitions"

It's 100% reproducible that way, and I don't have the problem if the last option is deactivated!

**Comment by enahum** [comment]
@Leryan in fact I was able to reproduce by enabling "Prefer Cross-Fade Transitions" on iOS 14 and iOS 15.

This seems to be a bug with the React Native framework https://github.com/facebook/react-native/issues/31484 the issue is already opened and we would need to wait until it gets resolved.

**Comment by Leryan** [comment]
Ah thanks! I guess the issue can be closed then, as you wish :)
