### ISSUE TITLE
can't join bigbluebutton meeting 

### ISSUE THREAD

**Issue by split-brain-83** [mattermost/mattermost-mobile#5464]
#### Summary
MM mobile app (ios and android) won't allow to join BBB meeting. Instead of showing 'join meeting' button and linking to the BBB session, it shows a couple of hashes and no link at all. MM desktop app, MM classic mobile app and web browsers has no problems integrating with BBB plugin.

### Environment Information
  - Device Name: iphone SE
  - OS Version: 14.5.1
  - Mattermost App Version: 1.44.0
  - Mattermost Server Version: 5.35.0

#### Steps to reproduce
Set up dedicated MM and BBB servers. In desktop MM app or web browser click 'Create a BigBlueButton Meeting', or type /bbb in any channel. 

#### Expected behavior
Be able to joing BBB meeting.

#### Observed behavior (that appears unintentional)
Instead of showing 'Join Meeting' button, there're some hashes displayed and no link to BBB session at all.

#### Possible fixes
I've no idea :(

![IMG_5718](https://user-images.githubusercontent.com/54268424/122390760-9cdeca80-cf72-11eb-89d6-edfdb085353d.PNG)

**Comment by larkox** [comment]
The issue here is that it is not showing the custom post type since the mobile app doesn't show it. This is like this by design, so the issue should be filed at the bigbluebutton plugin repo.
https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton
