### ISSUE TITLE
Markdown tables are not rendered on mobile application 

### ISSUE THREAD

**Issue by berenikaa** [mattermost/mattermost-mobile#5485]
#### Summary
Markdown tables are not rendered on mobile application 

### Environment Information
  - Device Name: Samsung A52
  - OS Version: Android 11
  - Mattermost App Version: 1.44.0
  - Mattermost Server Version: 

#### Steps to reproduce
Create a message with table using markdown syntax in web application. Check the message via mobile application

#### Expected behavior
Table is rendered

#### Observed behavior (that appears unintentional)
Table is not rendered - instead markdown "signs" are shown.

**Comment by enahum** [comment]
Hi @berenikaa can you share an example? Is very easy to mis-format a table.

Our parser for tables in the webapp are a bit more forgiving than the one used in the mobile app.

**Comment by berenikaa** [comment]
Hi @enahum 
Indeed our formatting was misleading - we were ending the headers with || instead of | - what renders correctly on web app but not on phone. Sorry not having spotted that earlier and thanks for your fast reply. Ticket can be closed.
