### ISSUE TITLE
scroll To Index out of range

### ISSUE THREAD

**Issue by ganpa3** [mattermost/mattermost-mobile#5500]
#### Summary
Bug report in one concise sentence
App crashed with error: scroll To Index out of range

### Environment Information
  - Device Name: Realme 3 Pro
  - OS Version: Android 10
  - Mattermost App Version: 1.44.0
  - Mattermost Server Version: 5.35.0

Installed the app. Joined a community. Read some messages. Opened the app after 10 days. Saw a blue banner at the top saying "445 unread message". Clicked on it. App crashed.

![Screenshot_2021-06-29-18-28-40-00_fb658ba01ce3ca3bdb5595ee8686f3ab](https://user-images.githubusercontent.com/58626718/123804041-7e7db500-d90a-11eb-97b4-5331abfd60d3.jpg)

**Comment by enahum** [comment]
@ganpa3 thanks for the report, I've submitted a fix to be included in the next release ;)
