### ISSUE TITLE
iOS app forces login after app terminated.

### ISSUE THREAD

**Issue by softmastx** [mattermost/mattermost-mobile#5531]
#### Summary
iOS app forces login after app terminated
Everything else works as expected and notifications work if the app is minimized and closed/removed from app tray.

### Environment Information
  - Device Name: iPhone 8 Plus
  - OS Version: iOS 14.6
  - Mattermost App Version:  1.45.0 build 362
  - Mattermost Server Version: 5.36.1
  - Database Schema Version: 5.36.1
  - Database: mysql
  
  Extend session length with activity: true
  Session Length AD/LDAP and Email (days): 30
  Session Length AD/LDAP and Email (days): 30
  Session Length AD/LDAP and Email (days): 30
  Cache a session : 10

#### Steps to reproduce
Re-install the app, re-login, terminate the app, re-open the app.

#### Expected behavior
Going to the main page after opening the app.

#### Observed behavior (that appears unintentional)
Taking to the login page again.

#### Possible fixes
Nope

**Comment by enahum** [comment]
@softmastx are you building the app yourself? Are you uaing the beta published in test flight?

This is definitely not reproducing on my end

**Comment by amyblais** [comment]
@josephbaylon @lindalumitchell Are you able to repro this on v1.45-beta?

**Comment by softmastx** [comment]
> @softmastx are you building the app yourself? Are you uaing the beta published in test flight?
> 
> This is definitely not reproducing on my end

I build the app in Xcode
https://www.linkedin.com/posts/softmastx_mattermost-activity-6820191886922412033-GAGm

**Comment by enahum** [comment]
@softmastx if you are building the app yourself I'd recommend to do it as described in the docs as there are a few things that the scripts take care of like properly assigning the app groups

**Comment by softmastx** [comment]
@enahum Can you confirm if the app groups setting or else was correct the app won't force re-logging in again when it has terminated on real device and Simulator? 

I'm having this issue only on mobile app and there is no issue for web browser!
Thanks

**Comment by enahum** [comment]
@softmastx yes the app group is used to store a session token in the keychain

**Comment by softmastx** [comment]
@enahum According to this link https://developers.mattermost.com/contribute/mobile/build-your-own/ios/

I'm just confusing on the step 2 saying:

```
- Follow the steps 1, 2, and 3 for Run on iOS Devices in the Developer Setup.
- After configuring the app in the previous step, ensure the bundle ID for each target of the mobile app remains the same as the one in the original mattermost-mobile GitHub repository (com.mattermost.rnbeta, com.mattermost.rnbeta.MattermostShare, and com.mattermost.rnbeta.NotificationService).
```

Let say that my app identifier is **com.softmastx.Mattermost** so, the app group, iCloud container and keychain would be 
**group.com.softmastx.Mattermost**, **iCloud.com.softmastx.Mattermost**, **com.softmastx.Mattermost** respectively.

 App Group and Keychain setting  for MattermostShare and NotificationService target would be **group.com.softmastx.Mattermost** and **com.softmastx.Mattermost**.

What I missed?
Thanks
