### ISSUE TITLE
Carriage Return / Line Feed appears to crash the app

### ISSUE THREAD

**Issue by PromoFaux** [mattermost/mattermost-mobile#5545]
1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary

Posting a message in any channel that contains a carriage return/line feed (`0D 0A`) causes the mobile app to crash. Web browser is fine.

### Environment Information
  - Device Name: Pixel 5
  - OS Version: Android 12 Beta
  - Mattermost App Version: 1.45.0
  - Mattermost Server Version: 5.37.0

#### Steps to reproduce

Copy/paste the below into a channel (make sure you copy both lines, don't just type it out)

```
:fire: :fire:       
:fire: :fire: :fire:
```

Attempt to load channel on mobile app.

#### Expected behavior

Channel loads, no issue.

#### Observed behavior (that appears unintentional)

Unexpected error occurs, looks like it might be quite a helpful message message to help debug :)

![image](https://user-images.githubusercontent.com/1998970/126061953-a3cb2cf9-ef67-4b00-9279-7e3e80b1aa4c.png)

![image](https://user-images.githubusercontent.com/1998970/126062079-d409c818-2b7c-4c38-8235-bb00797bd0a2.png)

(screenshot shows use of a custom emoji, but works with anything, really. It's the cr/lf that's the issue)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by enahum** [comment]
@PromoFaux thanks for the report.. We'll make sure to include a fix for this crash in the upcoming dot release.

**Comment by PromoFaux** [comment]
Confirmed working in latest release. Thanks for the speedy fix!
