### ISSUE TITLE
Android: Picture share from Gallery to mattemost is not working

### ISSUE THREAD

**Issue by snowowl78** [mattermost/mattermost-mobile#5560]
#### Summary
Android App Image Share from Gallery with no effect / Upload

### Environment Information
  - Device Name: Samsung Galaxy S20FE
  - OS Version: Android 11 / One Ui-Version 3.1
  - Mattermost App Version: 1.45.0
  - Mattermost Server Version: 4.6.2

#### Steps to reproduce
Open Samsung Gallery app 
Open picture you want to send
Hit share button
Select Mattermost from list
Now enter text or leave it empty 
Select organisation and channel to post to
Hit send button in upper right corner
App closes 
Nothing happens on the server

#### Expected behavior
I expect the share function to upload the image with the text provided.
Sending the same picture with text from within the Mattermost app works fine

#### Observed behavior (that appears unintentional)
Instead of sending the message with attachement to the server, nothing happens.

#### Possible fixes
Unfortunatly, I have no idea

**Comment by amyblais** [comment]
@snowowl78 We haven't been able to reproduce this, would you be open to upgrading your Mattermost server to the latest version (v5.37.0)?

**Comment by snowowl78** [comment]
@amyblais I am sorry the Server is not under my control. But I took a look again to the server version (via the app's information screen) So I provided the wrong version to you.  As you will see in the provided Screenshot, the cyrrent actual server version is already at 5.33.2,  maybe this helps to investigate further?
![Screenshot_20210722-063554_Mattermost](https://user-images.githubusercontent.com/17596877/126590905-6aab33f3-48fb-44fb-902c-ab216dfe695e.jpg)

**Comment by snowowl78** [comment]
@amyblais I am sorry the Server is not under my control. But I took a look again to the server version (via the app's information screen) So I provided the wrong version to you.  As you will see in the provided Screenshot, the current actual server version is already at 5.33.2,  maybe this helps to investigate further?
![Screenshot_20210722-063554_Mattermost](https://user-images.githubusercontent.com/17596877/126590905-6aab33f3-48fb-44fb-902c-ab216dfe695e.jpg)

**Comment by amyblais** [comment]
@snowowl78 Was this working with the previous v1.44 Mattermost app version?

**Comment by snowowl78** [comment]
I am sorry, I have never tried this before. This was the very first time I used this share function in combination with the mattermost app.

**Comment by amyblais** [comment]
@snowowl78 Are you the only one on your server seeing this issue or do you know if there are other people on the same server affected by this? 

If just one user is affected, it may be related to a connection instability.

**Comment by snowowl78** [comment]
I asked my colleagues to try to verify this behaviour.

On the other side do I not believe that this is related to a connection instability, because sharing from wihtin mattermost-app itself worked perfectyl fine.

I tried this more than ones now, and can still reproduce it every time.

**Comment by larkox** [comment]
@snowowl78 Does this still reproduce on the latest beta (V2)?

**Comment by snowowl78** [comment]
Sorry @larkox I can't tell
