### ISSUE TITLE
MFA login stopped working for Android app

### ISSUE THREAD

**Issue by Bobo357** [mattermost/mattermost-mobile#5565]
We've been running Mattermost server for a long time but recently we noticed that when MFA is enabled for a user then app stops after entering MFA token. It concerns multiple users and only Android app. One user that has both Android and iPhone confirmed that he is able to login using iPhone but not with Android.

Server version:
Version: 5.36.0
Build Number: 5.36.0
Build Date: Thu Jun 10 13:14:06 UTC 2021
Build Hash: ab85b70be324433456ebdfc0fd6d132da71cff7e
Build Enterprise Ready: false
DB Version: 5.36.0

Android app version: 1.45.0 and 1.45.1

Workflow:
1) Open app
2) Enter Mattermost server address, press Connect -> works OK
3) Enter Email and Password, press Sign in - > works OK
4) Enter MFA Token and press Proceed -> Proceed button disappears, MFA Token number is still displayed on screen, user is not logged in, nothing happens.

Nginx log excerpt from mattermost.log when "Proceed" button is pressed:
[my_ip_address] - - [21/Jul/2021:10:49:33 +0300] "POST /api/v4/users/login HTTP/2.0" 200 874 "-" "Mozilla/5.0 (Linux; Android 11; IN2023 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Mobile Safari/537.36" "-"

Same thing works correctly in iPhone app.

**Comment by amyblais** [comment]
@Bobo357 Was it working with the previous v1.44 Mattermost app version?

**Comment by Bobo357** [comment]
That kind of question is very hard to answer because:
1) you don't usually check for app version when you don't have problems
2) App asks for MFA very rarely because usually you are constantly logged in
All I know that first reports came in around last weekend and it's currently affecting at least 6 people.

**Comment by amyblais** [comment]
@migbot @streamer45 Elias wasn't able to reproduce this and he doesn't know why this is affecting Android but not iOS. Would you have any additional ideas on how to troubleshoot this?

**Comment by Bobo357** [comment]
@amyblais I could send you an invite to our server if it's any help.

**Comment by enahum** [comment]
@Bobo357 yes that could be helpful. Feel free to reqch out to me in our community server and we csn coordinate from there

**Comment by Bobo357** [comment]
One user sent me very detailed report what happened:
1. He updated MM app to version 1.45.0 (before this everything was working correctly)
2. After opening app it shows only MM logo on white background, it's not possible to do anything else. Notifications however worked (when someone tagged him in message, etc)
He tried the following to remediate the problem:
1. restart phone
2. MM app force stop
3. MM app clear cache and storage
4. MM app delete and reinstall
After reinstall he encountered exactly the same situation that I described in my very first post here.

**Comment by enahum** [comment]
It seems your deployment is setting an additional cookie called `Max-Age`, Android is complaining that this cookie contains an `Illegal character` for cookies, as far as my understanding goes an hyphen, dash is not valid in a cookie name. For some reason iOS is being a bit more forgiving than Android at their cookie parser implementation.

@Bobo357  I would advice the removal of the `Max-Age` cookie being set by your nginx reverse proxy or at least consider renaming it.

Hope this helps.

**Comment by Bobo357** [comment]
Thank you for quick response and solution! Removing the cookie helped.
