### ISSUE TITLE
Prevent the app logging out so frequently?

### ISSUE THREAD

**Issue by vext01** [mattermost/mattermost-mobile#5570]
#### Summary

App auto-logs you out every week or so.

### Environment Information
  - Device Name: Pixel 4a
  - OS Version: 11
  - Mattermost App Version: 1.45.1
  - Mattermost Server Version: unsure.

#### Steps to reproduce

Log in. Wait a week or so. You will be logged out.

This is awkward, since my password manager is on my PC at home, and I may not have immediate access to the password.

#### Expected behavior

The ability to stay logged in.

#### Observed behavior (that appears unintentional)

Logs you out.

#### Possible fixes

An option to stay logged-in forever? Or after a configurable time of inactivity?

My desktop browser session does not appear to have the same behaviour.

Thanks

**Comment by amyblais** [comment]
@vext01 
1. What is your [session length setting](https://docs.mattermost.com/configure/configuration-settings.html#session-length-for-mobile-apps-days) set to?
2. You can find your server version from main menu > About Mattermost.

**Comment by ghkc35** [comment]
@amyblais 

Having this issue as well on Android. We have our session length set to 30 days and server version is 5.31.4. We had to revert back to v1.43.0.

**Comment by amyblais** [comment]
cc @enahum Adding you here in case you have additional thoughts on this issue.

**Comment by enahum** [comment]
Is this a stock app or a custom build?
Do you see any 401 status codes in the server logs? if so, when?
Are we sure is the app? Have you tried the same repo steps logging into our community server?

**Comment by juska** [comment]
I experience this behavior too, with a more recent app and server version. I am using app version 1.46.0 (build 3000368) and server version 5.38.1 (build cern-ci) on an Android 11 device (Galaxy S10). The session length is set to 30 days.
My colleague using an Apple phone told be that also she has noticed this behavior.

**Comment by amyblais** [comment]
Would you be open to sharing more details based on the dev questions above 

1. Is this a stock app or a custom build?
2. Do you see any 401 status codes in the server logs? if so, when?
3. Have you tried the same repo steps logging into our [community server](https://community.mattermost.com/)?

**Comment by juska** [comment]
1. This is "CERN Mattermost Team Edition"
2. I have no idea. I'm a user.
3. No.

**Comment by amyblais** [comment]
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),
