### ISSUE TITLE
Mobile app takes like half a minute to load messages on cold start

### ISSUE THREAD

**Issue by alexander-potemkin** [mattermost/mattermost-mobile#5576]
#### Summary
Cold open the mobile app against self hosted server; it takes like 30 seconds for the app to display that there are new messages.

### Environment Information
  - Device Name: various iPhones
  - OS Version: latest iOS (14.7.1)
  - Mattermost App Version: 1.45.1
  - Mattermost Server Version: 5.37.0

#### Steps to reproduce
Cold open app on iOS, measure the waiting time till the channels will be updated.
Users with various iPhones reporting this behavior, but on my side I can see that it’s longer on iPhone 8 and seems to be faster on iPad Pro 12.9 4th generation - so it _might be_ because of the performance required to fetch all of the latest updates.

#### Expected behavior
Like Slack’s mobile client: I open it and the new updates appears almost instantly.

#### Observed behavior (that appears unintentional)
It takes like 15-30 seconds to load.
btw, internet is fast and stable.

#### Possible fixes
If it’s really due to the high requirements to the hardware and it can’t be changed, it would be nice to know that. But, ideally, improve things - if not in real (faster messages fetching), then at least visual: quickly first load the amount messages or if there are any new ones, show load indicator and load the rest of them at the meantime.

Because currently it looks like there are no new messages, which is confusing.

**Comment by alexander-potemkin** [comment]
just in case - it’s not the same on desktop app and quite a frustrating experience: you open the messenger and sees nothing, so you close it. Then it’s turned out, that there were messages in there, quite a lot of them, but you had to wait for an unknown period of time.

I guess, an element showing that things are in progress of being loaded would help a lot as a short term fix.

**Comment by amyblais** [comment]
cc @enahum Adding you here too in case you have additional thoughts on this issue.

**Comment by enahum** [comment]
No additional thoughts, not sure why is taking so long for them, it shouldn't take really more than 2 or 3 seconds on a slow connection even if it has to go through a few requests before it fetches new posts. @alexander-potemkin do you see the same results if you connect to our community server?

**Comment by jasonblais** [comment]
@alexander-potemkin in case you weren't sure, our community server is at https://community.mattermost.com

**Comment by alexander-potemkin** [comment]
@jasonblais , thank you - I didn't know indeed, that was of help!

@enahum , it seems to be Ok on community server - it's not exactly accurate, as not that many people are writing there and there are not active threads in there; but there is one more thing - it _seems_ like on my own server it started working faster after I re-loged-in, but not for a long time: just today, after a long conversation on computer I opened iOS client and it shown me zero new messages, I waited for ~5 seconds and then directly tapped on the channel that I knew that has new messages - app shown me the new messages in it immediately; so it's like the bug is more on the component showing updates on the channels.

I understand you need exact steps to reproduce, but not sure how to deal with it. Any clue?

**Comment by enahum** [comment]
@alexander-potemkin currently the mobile app does a lot of things when you first open it and any of them can be causing things to slow down for you.

Let me explain high level what happens:
1. As the app opens we fetch your updated data, this means: Your user, preferences, your teams, the number of unread messages in your teams.
2. The app opens up the channel screen, in here then we sync the channels your in that belong to the team you have selected (selection happens automatically), once this is done we then proceed to fetch the posts for the channel you'll be landing into.
    - One interesting aspect here is that our API's mandate that for every Group Message or Direct Message channel that you have, we should load from the server the profiles that are part of those channels so we are able to show them to you in your sidebar
    - Here as well as we load posts, for those authors that you may not have already loaded previously we need to fetch those users from the server as well so it displays who wrote the message <- this happens for new posts
3. At this point you are already in the channel and should have the newest posts for that channel (or at least incoming) and here we start to fetch the posts for the unread channels that you may have.

Fetching of posts is capped to 60 messages at a time, in theory all this should happen rather quickly, the more up to date your app is the faster it should get all data.

We are currently working on a new architecture that should allows us to sync data a bit faster (once we get it) and a few important changes on the business logic as of what gets loaded first. At this exact moment @migbot is working on it, but this won't be available until later this year as is on top of a new architecture and the entire mobile app needs to be ported to it before we are able to ship it.

Maybe with this long explanation you can have a sense of what is going on and see if in fact this are the things causing you the delays. Also it would be awesome to hear feedback on this as to try and adapt the business logic currently being implemented.

Side note: Some things on the logic would be block on further improvements until new API's to fetch data from the server are developed in a way that better fits our application clients behavior.

**Comment by alexander-potemkin** [comment]
@enahum , thank you very much for such a detailed explanation! I suspected something of the kind, but it looks like a lot, indeed =)

A few questions from my side:
- is there any way to introduce some 'Loading...' message somewhere on the interface, so that the user would be aware that what he/she sees, is not up to date (because that's the main problem now)?
- is there any estimate for the new architecture and things to be rolled out to mass users?
- is any way to do 'Loading...' message till new things are there?

Thanks in advance!

**Comment by alexander-potemkin** [comment]
@enahum , gentle reminder

**Comment by enahum** [comment]
@alexander-potemkin I'm sorry for the delayed response
> is there any way to introduce some 'Loading...' message somewhere on the interface, so that the user would be aware that what he/she sees, is not up to date (because that's the main problem now)?

There's nothing planned for this as of today, Also I'm curious if this happens in other servers like the community server, perhaps there is something else to be looked at here instead of just adding a loading indicator.

> is there any estimate for the new architecture and things to be rolled out to mass users?

This is a huge task and no promises are being made although the timeline is to roll out a beta version by Jan 2022, but keep in mind this can change if there are unforeseen delays.

> is any way to do 'Loading...' message till new things are there?

Same as the first question, but maybe you can use the `pull up to refresh` feature?

> how long should it take, at maximum, to load and update everything?

I guess this depends on your deployment and your network speed, for me at least (I live in Chile) when connecting to the community server (US) it just takes at most a couple of seconds to load everything.

**Comment by alexander-potemkin** [comment]
@enahum , no worries, thanks for the detailed responce.

I did indeed tested on community server [earlier](https://github.com/mattermost/mattermost-mobile/issues/5576#issuecomment-896917584), and from what I can see it's not a server specific.

And in my case it took much longer that a couple of seconds, for a muuuuch less loaded self-hosted server, and pull up to refresh doesn't help... =(

Having an indicator, showing the the app is busy refreshing things, I believe, is a good UX practice, anyway - it helps to avoid a lot of the confusion.

**Comment by larkox** [comment]
@alexander-potemkin A few improvement around this have been done on the latest beta (V2). Do you mind checking if you are still experiencing this issue with the latest beta?

**Comment by alexander-potemkin** [comment]
@larkox thanks for letting me know! We stopped using long threads due to the issues, so I can’t confirm or deny that, I’m sorry

**Comment by enahum** [comment]
Closing, if anyone is still seeing this in v2, do please re-open this issue
