### ISSUE TITLE
Join as guest not displayed correctly.

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-mobile#5633]
#### Summary
When guests join the app doesnt display it correctly.

### Environment Information
  - Device Name: Oneplus 5t
  - OS Version: LOS 18.1
  - Mattermost App Version: 1.46.0
  - Mattermost Server Version: 5.37

#### Steps to reproduce
+ let guests join any channel.
+ open channel in app.

#### Expected behavior
Guest joins getting dispalyed and squashed correctly.

#### Observed behavior (that appears unintentional)
guest joined, user added by our bot, another guest joined. There is no text besides the "system" displayed per guest.
![Screenshot_20210821-152204_Mattermost](https://user-images.githubusercontent.com/5354356/130323140-2b67549c-dd27-4f2f-be09-3878d36626e6.png)

**Comment by jasonblais** [comment]
Thank you @someone-somenet-org for the report!

I've reproduced the issue and created a ticket for our engineering team to triage and prioritize: https://mattermost.atlassian.net/browse/MM-38065

If anyone in the community is open to help with a contribution, let us know! Otherwise I'll post back here once the ticket is queued for a release.

**Comment by jasonblais** [comment]
(Really great details in your report, made it easy for me to reproduce and share with our engineering team, thank you! 👍 )

**Comment by someone-somenet-org** [comment]
Is there an eta on this?

Our channels currently look like this
![IMG_20210915_145943](https://user-images.githubusercontent.com/5354356/133437932-013f6eb3-20e3-4fc4-9090-391a9937382b.jpg)

**Comment by jasonblais** [comment]
@someone-somenet-org It is scheduled for the next mobile app release, v1.47.  This is planned for on or around Oct 13.
