### ISSUE TITLE
When I click on the settings menu, nothing happens.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#5652]
#### Summary
When I click on the settings menu, nothing happens.

### Environment Information
  - Device Name: galaxy
  - OS Version: Android 9
  - Mattermost App Version: 1.46.0
  - Mattermost Server Version: 5.38

#### Steps to reproduce
Settings -> Display -> Click on Mobile notifications -> Permission OK -> modal closed -> Click on Mobile notifications
 -> no response -> back button -> Display -> Click on Mobile notifications -> Normal operation

Settings -> Help -> Back button -> All menus unresponsive -> Back Button -> Settings -> Normal operation

#### Expected behavior
Settings -> Display -> Click on Mobile notifications -> Permission OK -> modal closed -> Click on Mobile notifications
-> responsive
Settings -> Help -> Back button -> All menus responsive

#### Observed behavior (that appears unintentional)
There was no problem in the previous version, but it happens in version 1.46.0.

#### Possible fixes
I think it has something to do with the store update.

**Comment by josephbaylon** [comment]
@amyblais I'm not able to repro this issue. Settings menu is responsive for me given the steps above.

**Comment by bitdessert** [comment]
@josephbaylon The expected behavior is as follows.
* Settings -> Display -> Click on Mobile notifications -> Permission OK -> modal closed -> Click on Mobile notifications
-> responsive 
Settings -> Help -> Back button -> All menus responsive

**Comment by josephbaylon** [comment]
@bitdessert @amyblais I'm now able to repro the unresponsiveness of the settings menu. I misunderstood the steps so I listed more detailed steps below.

A.
1. Settings > Notifications > Mobile
2. Tap on Allow for permissions, then modal closes
3. Attempt to tap on any of the Notifications options (Mentions and Replies, Mobile, Email)

Expected: User should be redirected to the appropriate views
Actual: Tapping on the options doesn't do anything, just stays in Notifications view

B.
1. Settings > Help
2. Tap on device back
3. Attempt to tap on the Settings options

Expected: User should be redirected to the appropriate views
Actual: Tapping on the options doesn't do anything, just stays in Settings view

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-38322.

**Comment by amyblais** [comment]
We couldn't reproduce this anymore. Please re-open the issue if the problem persists,
