### ISSUE TITLE
There seems to be a problem with uploading and downloading gif files.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#5653]
#### Summary
There seems to be a problem with uploading and downloading gif files.

### Environment Information
  - Device Name: galaxy
  - OS Version: Android 9
  - Mattermost App Version: 1.46.0
  - Mattermost Server Version: 5.38.1

#### Steps to reproduce
1. Use the image upload function of quick action
2. Select gif
3. Send
4. Check uploaded images
5. Uploaded image does not move
6. Even after downloading the uploaded image, it does not move

The above process works well in version 1.44.0.

#### Expected behavior
The uploaded gif file should work fine.

#### Observed behavior (that appears unintentional)
I uploaded a gif, but it looks like a still image like a normal jpg file.

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-38309.
