### ISSUE TITLE
ShareViewController crashes if managed config inAppPinCode is true

### ISSUE THREAD

**Issue by Gituser564738** [mattermost/mattermost-mobile#5657]
#### Summary
When trying to share a Document or image to Mattermost ShareViewController crashes

### Environment Information
  - Device Name: iPhone
  - OS Version: iOS 14.5.1
  - Mattermost App Version: 1.46.0
  - Mattermost Server Version:  5.37.0

#### Steps to reproduce
Set app config inAppPinCode = true
Try to share document or image to the app with iOS built in sharing feature to the mattermost app
observe nothing happening on device (Console log will show a lot of errors)

#### Expected behavior
It should not crash and open up the message ShareView "box" to add a message to the image and send it

#### Observed behavior (that appears unintentional)
Nothing happens on device when you press mattermost icon
Console log from device snippet
```
SLComposeServiceViewController got NSURL file:///var/mobile/Media/PhotoData/OutgoingTemp/068A7285-5210-4A7C-B44B-15FD175B87D1/IMG_2202.JPG for public.jpeg error: (null)
evaluatePolicy on LAContext[842:1] cid:3 returned Error Domain=com.apple.LocalAuthentication Code=-1004 "Caller is not running foreground." UserInfo={BiometryType=2, BiometryDatabaseHash={length = 32, bytes = 0xe6a94d33 c5d363bd d8e50162 03304d4a ... c463140e bc21efa7 }, AvailableMechanisms=(
    7,
    2
), NSLocalizedDescription=Caller is not running foreground.}
```

#### Possible fixes
I believe it is this line which is causing the crash
https://github.com/mattermost/mattermost-mobile/blob/c90d040b40015db6e8906ab9a96eaad137bd5832/ios/MattermostShare/ShareViewController.swift#L85
If i insert a  `self.loadData()` on line 89 it will continue sharing the image but this is not secure since we dont authenticate the user so a malicious actor could use this to send messages when even when not authenticated with "inAppPinCode" .

**Comment by Gituser564738** [comment]
Did some more research and it seems that the crash is because the LAContext deviceownerauthentication is called in background before Sharing is in foreground 
https://github.com/mattermost/mattermost-mobile/blob/c90d040b40015db6e8906ab9a96eaad137bd5832/ios/MattermostShare/ShareViewController.swift#L53

```swift
 if let inAppPinCode = config["inAppPinCode"] as? String, inAppPinCode == "true" {
      DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
      self.auth(vendor: config["vendor"] as? String)
      }
    } else {
      self.loadData()
    }
```
inserting a DispatchQueue solves the crash and presents the authentication window correctly **BUT** the keyboard does not appear on the sharing window causing you not to be able to write a message before posting your share.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-38299.
