### ISSUE TITLE
Android users not able to log in due to invalid or expired session

### ISSUE THREAD

**Issue by mantuko** [mattermost/mattermost-mobile#5667]
#### Summary
Multiple Users using the Android app get the message "Invalid or expired session, please login again." when trying to log in.

### Environment Information
  - Device Name: Mobile Android phone
  - OS Version: Android 11 RKQ1.200826.002 (will add other one later when I got info)
  - Mattermost App Version: 1.46.0
  - Mattermost Server Version: 5.38.2

#### Steps to reproduce
Unknown …

#### Expected behavior
After entering login credentials and hitting the 'Sign In' button the App should log the user in and show the default channel.

#### Observed behavior (that appears unintentional)
I set up the server yesterday on a clean Ubuntu Server 20.04 using Mattermost Omnibus. I got 3 users using the Android app. One has no problems the other two get the message "Invalid or expired session, please login again." (one English, the other the same message in German) displayed in red above the input for email or username. For the first user the web app and the desktop app worked. For the second user I only know about the web app working. But it seems to be a problem only with the Android app.

I've revoked all session for the first user via "System Console -> User -> Member (on the user) -> Revoke Sessions" without success. She uninstalled and reinstalled the app without success. She deleted the app's data and emptied its cache, then deleted the app, also without success. The second user tried the same thing with the same outcome.

The first user semmed to trigger the following log messages:

    {
        "level": "warn",
        "ts": 1630833385.5945237,
        "caller": "app/session.go:89",
        "msg": "Error while creating session for user access token",
        "error": "createSessionForUserAccessToken: Invalid or missing token., resource: UserAccessToken id: token=<26-character-token>"
    }
    {
        "level": "info",
        "ts": 1630833385.5952249,
        "caller": "mlog/log.go:237",
        "msg": "Invalid session",
        "error": "GetSession: Invalid session token=<26-character-token>, err=, "
    }
The token changed as expected after I revoked her sessions.

The second user with the same problems does not trigger the same error messages. Other than that his device language is set to German I don't see any difference in behaviour.

I'm aware of the following [post in the forum](https://forum.mattermost.org/t/invalid-or-expired-session-please-login-again-only-on-desktop-app/10326). But as the problem is not with the desktop app there are no developer tools that I'm aware of to clear any data and in addition to this we tried clearing data by deleting the app's data + cache + uninstall + reinstall.

As I'm new to Mattermost I've might have missed things to check. But as I myself have no Android device to reproduce the problem I'm pretty much out of ideas for now.

**Comment by jasonblais** [comment]
@mantuko Thank you for the detailed issue description! Really appreciate it.

Few questions about your environment:

1. Are you open to confirm that your server has email/password login enabled only? (I assume so based on your note "...in red above the input for email or username...", but wanted to confirm)
2. Does anything appear in the Mattermost logs when they try to log in? You may need to temporarily set "System Console > Logging > File Log Level" to "DEBUG", which will print more detailed log messages for debugging.
3. What are your session length settings set to https://docs.mattermost.com/administration/config-settings.html#session-lengths

The above will help give us some context to see if we can replicate/troubleshoot the issue further.

**Comment by mantuko** [comment]
@jasonblais Thank you for your response.

1. Yes, I email/password login is the only enabled option. No AD/LDAP, SAML, …
2. I just set the File Log Level to DEBUG and ask them to try to log in. I'll then post interesting log entries here.
3. Session length are (default as 95% as the other settings):
    - Extend session length with activity: false
    - Session Length AD/LDAP and Email (days): 180
    - Session Length Mobile (days): 180
    - Session Length SSO (days): 30
    - Session Cache (minutes): 10

**Comment by mantuko** [comment]
@jasonblais OK, my test users were quite fast. I like them :) I narrowed it down to to log messages each concerning the login. There's a gap of > 5 seconds to the previous and next log messages so I figured they have nothing to do with it. It's "Received HTTP request" with status 200 for loading the brand image or similar. So here are the logs:

    // 1st user - start
    {
        "level": "debug",
        "ts": 1631080608.1743386,
        "caller": "mlog/log.go:230",
        "msg": "Invalid or expired session, please login again.",
        "path": "/api/v4/users/login",
        "request_id": "<26-character-user-request-id>",
        "ip_addr": "<ip-v6-address>",
        "user_id": "",
        "method": "GET",
        "err_where": "",
        "http_code": 401,
        "err_details": "UserRequired"
    }
    {
        "level": "debug",
        "ts": 1631080608.1744807,
        "caller": "web/handlers.go:107",
        "msg": "Received HTTP request",
        "method": "GET",
        "url": "/api/v4/users/login",
        "request_id": "<same-26-character-user-request-id>",
        "host": "mattermost.mrmuli.de",
        "scheme": "https",
        "status_code": "401"
    }
    // 1st user - end
    
    // 2nd user - start
    {
        "level": "debug",
        "ts": 1631080700.4243014,
        "caller": "mlog/log.go:230",
        "msg": "Invalid or expired session, please login again.",
        "path": "/api/v4/users/login",
        "request_id": "<2nd-26-character-user-request-id>",
        "ip_addr": "<2nd-ip-v6-address>",
        "user_id": "",
        "method": "GET",
        "err_where": "",
        "http_code": 401,
        "err_details": "UserRequired"
    }
    {
        "level": "debug",
        "ts": 1631080700.4248614,
        "caller": "web/handlers.go:107",
        "msg": "Received HTTP request",
        "method": "GET",
        "url": "/api/v4/users/login",
        "request_id": "<same-2nd-26-character-user-request-id>",
        "host": "mattermost.mrmuli.de",
        "scheme": "https",
        "status_code": "401"
    }
    // 2nd user - end

One question though for posting logs: Does it make sense to remove the `request_ids` because it's used as a session id or auth token or is it really just a request id that changes with every http request and therefore no problem to post here?

Thanks in advance for helping.

**Comment by jasonblais** [comment]
@mantuko Thank you! This is excellent. It is okay to leave the `reqeuest_id` fields sanitized. I'll try and see if the team has any insights on this and get back to you.

**Comment by ahmaddanialmohd** [comment]
Hi, @mantuko 

I understand that you are facing this specifically on the Mattermost Android app and at this point, we have the following information to help us understand what the potential root cause is:

* "msg": "Invalid or expired session, please login again."
* "err_details": "UserRequired"

I could not find any specific reason as to why it is only affecting a specific mobile OS for now. 

As I understand it, https://mattermost.mrmuli.de/login is publicly accessible. Any chance that you can create a test user and send over the details to me on community.mattermost.com so I can test it on my Android device as well?

@enahum do you happen to have any idea why the `UserRequired` will only occur specifically on Android?

**Comment by mantuko** [comment]
@ahmaddanialmohd You now have an account on my server.

What I have to add it's not all Android users. I got three users with Android devices. One has no problems and two have the same problem which prevents them from logging in.

The one having no problems users also uses Android 11. I visited her yesterday and wie logged out an in without a problem.

**Comment by mantuko** [comment]
I just had a colleague try to login while standing next to her and solved the issue. I hat a redirect going from another domain and the ones who cannot log in used the redirected domain. The ones that can log in used the final url.

Sorry for wasting your time.

**Comment by jasonblais** [comment]
@mantuko Glad the issue got resolved!

**Comment by ahmaddanialmohd** [comment]
Hi, @mantuko 

All good. For transparency purposes, we had a conversation in your instance to confirm that I had no issues with logging in your server initially and I was able to communicate with you from there.

Happy to know that the issue is resolved now.
