### ISSUE TITLE
App doesn't notify about new messages after a few days.

### ISSUE THREAD

**Issue by cguckes** [mattermost/mattermost-mobile#567]
#### Summary
The android app does not notify about new messages, if it loses the login session or gets killed by the android system.

#### Environment Information

- Device Name: One+3T
- OS Version: Android 7.1.1
- Mattermost App Version: 3.6
- Mattermost Server Version: 3.3.0

#### Steps to reproduce
Start the app, then don't use it for about a week.

#### Expected behavior
I'd like the app to notify me if I get new messages via mattermost. At the moment, the app just falls silent once the session ends or the app gets killed by android. There should be some kind of service, that checks for new messages and that doesn't get killed by android, similar to other messengers.

#### Observed behavior
After not using the app for a while, it doesn't notify about new messages and it requires a new login.

#### Possible fixes
Not sure about lines but I seem to remember there being some flag you can set to tell android that the app is meant as a service that should run permanently. No idea if that applies here, though...

Will trade java coding time for a fix of this app, if you need any bugs/features in a java project fixed, however tedious they might be. ;-)

**Comment by enahum** [comment]
We are aware that if the app gets killed no push notifications are being received, we haven't found a solution for this so far nor the owners of the push notification library that we are using.

**Comment by enahum** [comment]
btw this app is meant to work with server version 3.8.2 and up, maybe you are confusing this app with https://github.com/mattermost/android, this is a new app in development using React Native

**Comment by lfbrock** [comment]
Hi @cguckes - are you still having this issue? 

Can you try out this version and let us know if you're still seeing the same thing? 
https://play.google.com/store/apps/details?id=com.mattermost.rn&hl=en

**Comment by cguckes** [comment]
I'm sorry, I didn't answer before. I have was indeed confusing the classic app with this one. You can close the issue, the problem isn't relevant to this app.
