### ISSUE TITLE
iOS Push Notification stopped working

### ISSUE THREAD

**Issue by LoneStudent** [mattermost/mattermost-mobile#5674]
All of a sudden, iPhones stopped receiving push notification. Android / desktop app still receiving notification. No server change.

### Environment Information
  - Device Name: iPhone 8 / X
  - OS Version: 14.7.1
  - Mattermost App Version: 1.46.0 (build 368)
  - Mattermost Server Version: 5.38.2

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

Send message from Android / desktop app to iPhone users.

#### Expected behavior
Describe your issue in detail

Users sees the message; however, no push notification

**Comment by amyblais** [comment]
@LoneStudent There was an issue with the push proxy for iOS devices but it is fixed now. Do you still experience this issue?

**Comment by LoneStudent** [comment]
Hi,

Its working again.

Thanks for taking the time to respond.
