### ISSUE TITLE
[iOS] app forces user to login after app has been closed.

### ISSUE THREAD

**Issue by rousesDev** [mattermost/mattermost-mobile#5679]
#### Summary
Mattermost app on iOS forces the user to login page when opening the app after closing it. This does not happen on the android version of the app.

### Environment Information
  - Device Name: iPad (7th gen)
  - OS Version: 14.7.1
  - Mattermost App Version: 1.4.6
  - Mattermost Server Version: 5.26.1

#### Steps to reproduce
Install the app, Login, close the app, remove it from running apps, re-open the app.

#### Expected behavior
Should be bring user back to their current session.

#### Observed behavior (that appears unintentional)
User is taking to login page again.

#### Possible fixes
Show post by user with a similar problem tried that didn't work. 
https://github.com/mattermost/mattermost-mobile/issues/5531

I am building the app myself using Xcode is their some setting I need to change in order to fix this?
All sessions variables server side are set to 30 days.

Extend session length with activity: true
Session Length AD/LDAP and Email (days): 30
Session Length AD/LDAP and Email (days): 30
Session Length AD/LDAP and Email (days): 30
Cache a session : 10

**Comment by amyblais** [comment]
@rousesDev Would you be open to upgrading to a more recent server version to see if the issue is improved? I'd recommend upgrading to v5.37.2 or later.

Do you see the same issue if you connect to our [community server here](https://community.mattermost.com/)?

**Comment by enahum** [comment]
@rousesDev if you are building the app without using the build scripts on every target Info.plist file you need yo update the app group identifier to match yours.

That said, I strongly suggest you use the scripts and follow the docs to avoid this or any other issues from happening

**Comment by rousesDev** [comment]
@enahum I forgot to add the group. part to the start of the appgroupidentifer when editing the info.plist as soon as I added that it resolved this issue.
