### ISSUE TITLE
Team icons not displayed in mattermost mobile for Android

### ISSUE THREAD

**Issue by florencebiree** [mattermost/mattermost-mobile#5682]
#### Summary
Team icons are not shown in Mattermost mobile android

### Environment Information
  - Device Name: Samsung Galaxy S5
  - OS Version: LineageOS 18.1 (Android 11)
  - Mattermost App Version: 1.46.0 (apk downloaded here on github)
  - Mattermost Server Version: 5.39.0

#### Steps to reproduce

When I open the team choice pannel in the mobile app, teams icon are not shown, only initials (see this mobile screenshot).
![mattermost-mobile](https://user-images.githubusercontent.com/1786791/133989030-fece688a-225d-48d1-a1fc-c2715219295a.png)

#### Expected behavior

The team icons should be shown (like this web browser screenshot).
![mattermost-web](https://user-images.githubusercontent.com/1786791/133989179-729b6678-022a-4f1a-9738-d1365b664b18.png)

#### Observed behavior (that appears unintentional)

This append on an up to date server which is not located at the root of the webserver. The mobile app show the team icons on another server with mostly the same setup, except it's located at the root of the webserver.

**Comment by amyblais** [comment]
@florencebiree Would you be open to testing if you can reproduce it on our subpath test server https://subpath.test.mattermost.com/mattermost/signup_user_complete? 

We haven't been able to repro this on our end.

**Comment by florencebiree** [comment]
It seems I need an invitation to create a account on this server, isn't it?

**Comment by amyblais** [comment]
@florencebiree The link I shared above should allow you to sign up / create a new account. What do you see when you click the link?

**Comment by florencebiree** [comment]
@amyblais I see a screen where I can create an account. When I fill the form for a login with e-mail and password, after the click on "Create account", a message appear: "This server does not allow open signups. Please speak with your Administrator to receive an invitation."

**Comment by amyblais** [comment]
Sorry about that, @josephbaylon would you be able to share an invite link with @florencebiree? (I don't have an account on the subpath server either)

**Comment by jasonblais** [comment]
@josephbaylon would you be open help share an invite link to join the subpath test Mattermost server at https://subpath.test.mattermost.com/mattermost?

**Comment by larkox** [comment]
This should be solved in V2. @florencebiree If you still see this issues in the latest beta (V2) feel free to reopen it.
