### ISSUE TITLE
App crashes during search for share targets.

### ISSUE THREAD

**Issue by daniel-jirca** [mattermost/mattermost-mobile#5693]
#### Summary
App crashes during search for share targets.

### Environment Information
  - Device Name Xiaomi Mi 9T:
  - OS Version: Lineage OS 17.1, September update
  - Mattermost App Version: 1.46.0
  - Mattermost Server Version: 
Mattermost Version: master
Database Schema Version: 6.0.0
Database: postgres
Build Hash: ef639973b7665d6f1d054359fe9569be6decc21f
EE Build Hash: none
Webapp Build Hash: 2c47234fca223d4948b4e1dd4a6930f9d6efff5a
Build Date: Fri Sep 24 15:59:49 UTC 2021

#### Steps to reproduce
1. Use the Android share function from an app to share a picture, url or any information and get to the **Share in Mattermost** screen;
2. Click on the **Channel** option to search for a channel;
3. Start typing until there are no results displayed;
4. Delete one letter at a time, slowly, and the app will crash.

#### Expected behavior
The app should not crash while searching for channels during the share operation.

**Comment by jasonblais** [comment]
@daniel-jirca Thank you for the report. For step 1, can you confirm from which app have you attempted to share a picture/url, which then resulted in a crash in step 4?

**Comment by daniel-jirca** [comment]
The source app does not matter. You can use any app, as I have specified in the report.

The crash happens during the search channel operation.

**Comment by amyblais** [comment]
Can we reproduce this? @josephbaylon cc @enahum @shazm

**Comment by enahum** [comment]
@amyblais yes this reproduces

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-38855
