### ISSUE TITLE
App crashes when clicking notification

### ISSUE THREAD

**Issue by jsimomaa** [mattermost/mattermost-mobile#5695]
#### Summary
App crashes when clicking notification

### Environment Information
  - Device Name: OnePlus 7T
  - OS Version: Android 11
  - Mattermost App Version: 1.46.0
  - Mattermost Server Version: 5.38.1

#### Steps to reproduce
Click notification

#### Expected behavior
Mattermost Mobile opens to channel where notification came from

#### Observed behavior (that appears unintentional)
App crashes

![signal-2021-09-27-140330](https://user-images.githubusercontent.com/4503494/134897149-c42361fa-c44d-4a15-9178-19c4af8fe644.jpg)
![signal-2021-09-27-140345](https://user-images.githubusercontent.com/4503494/134897183-0e011731-5112-4401-b247-63d0b69cacec.jpg)

**Comment by amyblais** [comment]
Can we reproduce this? @josephbaylon cc @enahum

**Comment by enahum** [comment]
@amyblais chances are high that this PR fixes it https://github.com/mattermost/mattermost-mobile/pull/5669
