### ISSUE TITLE
IOS15 mattermost app cannot receice msg notifications

### ISSUE THREAD

**Issue by kiroswu** [mattermost/mattermost-mobile#5697]
After upgraded to IOS15, the mattermost app cannot receice msg notifications. It's all fine in ios14 before ios upgrade. What should i do or how to fix it? Thx

Mattermost server version: 5.38.2 linux x64
Push Notification Server: https://push-test.mattermost.com
ios mattermost app version: 1.46.0(build 368)

Mobile notification is configurated for all activity and triggered when online away or offline.

The iphone configuration is same as before upgrade, i.g. closed don't disturb and opened notification for mattermost

**Comment by amyblais** [comment]
@enahum @josephbaylon Can we reproduce this?

**Comment by enahum** [comment]
As you can see in this screenshot attached is working totally fine for me
![image](https://user-images.githubusercontent.com/6757047/135099820-bf78facd-1db4-4bb8-8a5d-dd5117df0124.jpeg)

**Comment by kiroswu** [comment]
@jasonblais it comes back normal after exit app - restart iphone - reopen app. Thanks
