### ISSUE TITLE
npm install error!

### ISSUE THREAD

**Issue by af913337456** [mattermost/mattermost-mobile#572]
$ npm install
npm ERR! git submodule -q update --init --recursive: fatal: bad object 1a27df4e60152ea548650cb13bdfd8edf80060a7
npm ERR! git submodule -q update --init --recursive: fatal: remote did not send all necessary objects
npm ERR! git submodule -q update --init --recursive: fatal: clone of 'https://github.com/bitstadium/CrashProbe.git' into submodule path 'C:/Users/asus/AppData/Local/Temp/npm-59832-ad810b51/git-cache-8bcf57ad/8fcb7dfce03473b5619a486dfe5ec469e6682edf/ios/Sentry/Carthage/Checkouts/KSCrash/Source/CrashProbe' failed
npm ERR! git submodule -q update --init --recursive: Failed to recurse into submodule path 'ios/Sentry/Carthage/Checkouts/KSCrash'
npm ERR! git submodule -q update --init --recursive: Failed to recurse into submodule path 'ios/Sentry'
npm ERR! git submodule -q update --init --recursive:

Please give me some advice !!!

**Comment by af913337456** [comment]
by the way,i run this on windows 10 os.

**Comment by af913337456** [comment]
does some come and save my life？

**Comment by enahum** [comment]
can you try running the following
`npm install -g yarn`

then do
`make clean` and `make run-android`

**Comment by af913337456** [comment]
thanks man, can i use another cmd to replace the "make"? i run this on windows 10 os.

**Comment by enahum** [comment]
if you look inside the Makefile you'll have all the individual commands that are run within each make

**Comment by af913337456** [comment]
so i have to do this in linux or mac？and I don't want to install cygwin anymore

**Comment by af913337456** [comment]
i ran "npm install -g yarn" & "npm install",and got the same error.

**Comment by enahum** [comment]
why are you running `npm install` you should use `yarn install` and one other thing we're submitting a PR soon to remove sentry from the app as is causing many issues including the ERR you are reporting, fix is going to be submitted soon

**Comment by enahum** [comment]
this should be fix now, feel free to re-open if the error still persist

**Comment by af913337456** [comment]
by used cygwin,i fixed this
