### ISSUE TITLE
iPad with physical keyboard: enter key never sends message

### ISSUE THREAD

**Issue by jbozanowski** [mattermost/mattermost-mobile#5736]
Starting with first beta release of 1.47, pressing the physical enter key on my smart folio keyboard never sends the message, only inserts a newline (including using any modifiers like cmd, option, etc.). The only way to send the message seems to be to press the on-screen send button, which on iPadOS 15 is almost entirely obscured by system keyboard widgets for changing keyboard settings and dictation.

![image](https://user-images.githubusercontent.com/114900/136669254-02cc0ee2-f2ee-4641-96d0-ec39f1037527.jpeg)

Not sure if relevant, but the desktop app (Mac) has settings for sending with cmd+enter -- it seems like this setting applies only to the desktop app itself, but I double-checked it anyway and I've always had it set to use cmd+enter for send only for codeblocks, changed it completely to off just to be sure, but it had no effect on the iPad app.

I'm on iPadOS 15.0.1, but the problem was present on 15.0, too (not sure about 14.x). Also, this started happening on first beta release of 1.47 and persists with all builds so far (last tested on 372). Reverting to version 1.46 fixes the issue.
Server version is 6.0.0-rc1.

**Comment by enahum** [comment]
@amyblais this is a regression, apps built with Xcode 13 and running on iPad 15, requires us to set a new property called `WantsPriorityOverSystemBehavior`.

Will submit a PR tomorrow and cut a new build as a new RC

Thanks for reporting @jbozanowski
