### ISSUE TITLE
An obsession

### ISSUE THREAD

**Issue by af913337456** [mattermost/mattermost-mobile#575]
Why dont develop a native android client app for mattermost-mobile，i have checked this "[android](https://github.com/mattermost/android)", and it just a webview inside the project.

**Comment by lfbrock** [comment]
Hi @af913337456 - this is the repo for our new native mobile apps, which are built with React Native, so we are working on that. 

The apps [are in beta right now if you want to try them out](https://play.google.com/apps/testing/com.mattermost.react.native), and will be released in Google Play in July.

**Comment by af913337456** [comment]
thanks to reply，i know you are going go build an React Native App，but i hope you guys to build it with Java.
