### ISSUE TITLE
No internet/Connecting... Toast message is not removed After Connection app successfully with Internet/WiFi

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-mobile#5750]
#### Summary
User open the app 

### Environment Information
  - Device Name: - Redmi note 5
  - OS Version:- 8.1.0 
  - Mattermost App Version:- 1.47.0 (Build 3000374) & 1.46.0 (Build 3000368)
  - Mattermost Server Version: 6.0.0 

#### Steps to reproduce
1) Turn Off the internet/WiFi.
2) open the app.
3) in the Header section the user will see the Toast message as "No internet"
4) Turn ON the Internet/WiFi.
5) The Toast message should remove but its still there.

#### Expected behavior
After App Connect with internet, The Toast message should remove.

#### Observed behavior (that appears unintentional)
After App Connect with internet, The Toast message is still there.

![1634149335935](https://user-image

https://user-images.githubusercontent.com/89907719/137194905-24af8795-8f9f-4790-90ee-dbb39f77841f.mp4

s.githubusercontent.com/89907719/137194885-85c7d7f1-823b-42d3-8695-8e400f35f5b2.JPEG)

**Comment by josephbaylon** [comment]
@amyblais I'm able to repro on Android. Though it doesn't seem to be a recent regression since it's also happening on v1.46.

A workaround is to close and re-open app so that connection bar goes away.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-39338.

**Comment by amyblais** [comment]
We couldn't reproduce this anymore internally on the latest mobile version (v1.55).
There is a separate ticket to implement connection banners for v2: https://mattermost.atlassian.net/browse/MM-39764.
