### ISSUE TITLE
GIF emojis play at 4x speed with newest Mattermost mobile update on iPhone 13 Pro (120hz)

### ISSUE THREAD

**Issue by Elehiggle** [mattermost/mattermost-mobile#5757]
#### Summary
GIF emojis play at 4x speed with iPhone 13 Pro (120hz)

### Environment Information
  - Device Name: iPhone 13 Pro
  - OS Version: 15.0
  - Mattermost App Version: v1.47.0
  - Mattermost Server Version: 5.37.2 (happens on v5.31 too)

#### Steps to reproduce
Send any GIF emoji.
It worked perfectly normal before the Mattermost app update (old version 1.46.0)
A colleague has confirmed the same issue on his iPhone 13 Pro as well, and other colleagues don't own the new iPhone and can confirm that it does NOT happen to them
Happens even when "Limit Frame Rate" option is enabled in iOS settings which limits the display frame rate to 60. Does also NOT happen on iPad Pro with 120hz.

#### Expected behavior
GIF emojis play in normal speed: https://streamable.com/51ej8q

#### Observed behavior (that appears unintentional)
GIF emojis play quadruple / 4x speed: https://streamable.com/hv1y02

#### Possible fixes
Maybe this dependency update is responsible: https://github.com/mattermost/mattermost-mobile/commit/a28a3826fabbe01c334cc3d1f176a6f972f99411#diff-b7d85c35701918f25c9b2c418249f9b66fd9b067676e295a9eff493b73ee1752L370
But no idea really.

**Comment by enahum** [comment]
Hi @Elehiggle thanks for the report.

Sadly the iOS simulator for iPhone 13 and variations does not run at 120Hz or I haven't find a way to enable 120Hz on them, so  we are going to have to ask for a bit of time until we can get an actual device to try it on and see if we can find a fix for it, is probably something to do with `ProMotion` which was introduced very recently on iOS devices.

My hope is to have this fix as soon as possible but for that I need to get my hands on an actual device first. Again thanks for the report and your patience until we are able to fix this.

**Comment by jasonblais** [comment]
@enahum Would it be helpful to create a Jira ticket for internal tracking, or not until we have access to the device for further troubleshooting?
