### ISSUE TITLE
App crashes when hitting "Notifications" in preferences

### ISSUE THREAD

**Issue by bagage** [mattermost/mattermost-mobile#576]
#### Summary
When clicking "Notifications" items in Account preferences, it crashes with my custom server (but not on pre-release.mattermost.com).

#### Environment Information

- Device Name: emulator (real device too)
- OS Version: 7.1.1
- Mattermost App Version: git master and/or 1.0(version 30)
- Mattermost Server Version: 3.9.0

#### Steps to reproduce
Log in to your account -> open account Settings menu -> click on Notifications item

I don't think my server configuration makes sense at this point, but please tell me if additional info are needed.

#### Expected behavior
Notifications configuration activity pops up.

#### Observed behavior
Application crashes with the following error: `undefined is not an object (evaluating 'emailPreferences.get(_constants.Preferences.EMAIL_INTERVAL).value')`
![capture d ecran de 2017-05-28 21-23-29](https://cloud.githubusercontent.com/assets/1451988/26531572/0c275112-43ec-11e7-93bd-09ce414e74ed.png)

**Comment by bagage** [comment]
Obviously disabling `Enable Email Batching` in `System console -> Email` *fixes* the problem because we don't go in the problematic `if` anymore. I believe this is the reason why `pre-release.mattermost.com` does not crash.

**Comment by lfbrock** [comment]
Hi @bagage - thanks for the report! 

I filed a ticket here to track the issue: https://mattermost.atlassian.net/browse/RN-147

**Comment by lfbrock** [comment]
Fixed in Build 31+
