### ISSUE TITLE
Adjusting the text selection manipulates the underlying view on iOS

### ISSUE THREAD

**Issue by wezm** [mattermost/mattermost-mobile#5764]
#### Summary

Editing text with the newly released mobile app is a frustrating experience as grabbing the text selection handles also manipulates the underlying view.

### Environment Information

  - Device Name: iPhone 12 mini
  - OS Version: 15.0.2
  - Mattermost App Version: 1.47.0
  - Mattermost Server Version: 5.39.0

#### Steps to reproduce

1. Type several words in the message field
2. Double tap a word in the middle to select it
3. Grab either of the selection handles and slide right

#### Expected behavior

I should be able to change the text selection without it influencing the reset of the app.

#### Observed behavior (that appears unintentional)

The view is manipulated and the text selection is lost. Video:

https://user-images.githubusercontent.com/21787/137837303-9317abca-95a9-4092-a01f-970d24205bdb.mp4

In this video I'm tapping the left side text selection handle and dragging it right-to-left. As you can see the selection is dropped and the view moves around.

#### Possible fixes

Not sure.

**Comment by enahum** [comment]
A fix for this just got merged today and will be available on the next release this week. See https://github.com/mattermost/mattermost-mobile/pull/5762

**Comment by wezm** [comment]
All good, feel free to close.
