### ISSUE TITLE
Archived Channels reappears on v1.47.1 (Build 375)

### ISSUE THREAD

**Issue by acataluddi** [mattermost/mattermost-mobile#5777]
#### Summary
After having upgraded Mattermost, channels archived long time ago are showing again. Such channels are **only showing on mobile** and not visible on the desktop/web application, as expected. 
By clicking on it, the mobile client confirms that the channel is an archived one (see screenshot below):

![Archive-Bug](https://user-images.githubusercontent.com/8874358/138483909-34399e0e-38c2-4b2c-a512-3faa450f6fcc.png)

### Environment Information
  - **Device Name**: Apple iPhone 12
  - **OS Version**: iOS 14.8
  - **Mattermost App Version**: 1.47.1 (Build 375)
  - **Mattermost Server Version**: 6.0.0

#### Steps to reproduce

1. Archive a channel on Mattermost (desktopor web).
2. Open the Mattermost mobile client
3. Notice the archived channel showing,

#### Expected behavior
Having the archived channel hidden.

#### Observed behavior (that appears unintentional)
//

#### Possible fixes
//

**Comment by larkox** [comment]
There has been many changes about this in the last year, and I guess this should be solved in V2. @acataluddi if you are still seeing this issue with the latest beta (V2), feel free to reopen the ticket.

**Comment by acataluddi** [comment]
Thank you @larkox, great support!
