### ISSUE TITLE
Large Image File/Size Upload Fails - Small Image File/Size Upload Success - iOS or Android

### ISSUE THREAD

**Issue by trbolexis** [mattermost/mattermost-mobile#5818]
#### Summary
*Large* Image upload fails from mobile app. iOS or Android. Reduced image size uploads successfully.

#### Environment Information
  - Device Name: Raspberry Pi 4B+ ::: 4GB Ram
  - OS Version: Ubuntu 21.04 64Bit
  - Kernel: Linux 5.11.0-1017-raspi
  - Architecture: arm64
  - Mattermost Server Version: 6.0.2 (Build dev-linux-arm-v6.0.2)
  - Apache2 Reverse Proxy

#### Mobile Device for Testing
  - Device Name: Samsung Galaxy Z Fold 3
  - OS Version: Android 12
  - Mattermost App Version: 1.47.2 (Build 3000377)

#### Steps to reproduce
From the mobile app, open any chat/channel and attempt upload a photo sized 4000 x 3000 (or larger) ~2.4Mb.

#### Expected behavior
Expect the upload to succeed and then to post the image.

#### Observed behavior (that appears unintentional)
For a while a blue progress bar appears across the bottom of the thumbnail. After some time a 'retry' symbol appears on the image thumb. 

If you press "send" you are informed that the image was not uploaded and asked if you want to send the message anyway.

NOTE: If the image is resized to 20% or less of its original size, the upload completes successfully.

This issue persist on iOS or Android. Indiscriminate.

#### Additional Details

File uploads for the same failing content on the mobile app uploads successfully via PC or Mobile Web Browser.

Uploads from Mattermost Classic App work successfully.

**Comment by amyblais** [comment]
@trbolexis 
1. Do you or your admin have access to check if there are any errors in the server logs?
2. Has this issue happened in previous versions?
3. Do you see the same issue on our community server https://community.mattermost.com/?

**Comment by trbolexis** [comment]
Thank you for the comment. 


1. I do have admin login, and I am also unsure of details found in the logs. Nothing stands out to me, but I am no expert: https://pastebin.com/dCQEqRrZ
2. This is my first installation/implementation of Mattermost (self-hosted), So I am unable to speak about previous versions. 
3. I did **NOT** experience the same issue uploading to the community,mattermost.com server in my testing a moment ago.

This does seem to indicate a server issue, right?

**Comment by yukdumboobumm** [comment]
Reviving this issue as I have the same problem and (nearly) same setup.

Environment Information

- Device Name: Raspberry Pi 4B+ ::: 4GB Ram
- OS Version: ~~Ubuntu 21.04 64Bit~~ Raspberry Pi OS 32bit
- Kernel: ~~Linux 5.11.0-1017-raspi~~ 5.10.103-v7l+
- Architecture: arm64
- Mattermost Version: dev-linux-arm-v6.6.0
- Database Schema Version: 78
- Database: mysql
- Apache2 Reverse Proxy

Mobile Device for Testing

- Device Name: Iphone SE 2nd gen
- OS Version: ios 15.4.1
- Mattermost App Version:  1.51.0 (B391)

nothing interesting in the logs except some DEBUG messages about non-existent plugins (com.mattermost.apps and com.mattermost.calls)

Happy to poke around the server if there are any good ideas.

**Comment by larkox** [comment]
@yukdumboobumm We have seem issues like this before that had to do with the configuration of NGINX regarding timeouts. Could this be the issue here? (i.e. since it takes so long to upload the file, nginx just timeout the connection)

**Comment by helgehatt** [comment]
I am experiencing the same issue on multiple iOS devices when using the app to upload e.g. a 30 sec video or multiple images simultaneously. The error in the app is **URLSessionTask failed with error: The request timed out**. 

I am certain that the app is the problem and not the reverse proxy since uploading using the browser works perfectly fine.

App Version: 2.4.0 (Build 471)
Server Version: 7.8.6
OS: Ubuntu Jammy 64bit
Architecture: amd64
Reverse proxy: Caddy

**Comment by xmoov** [comment]
Same here, I also timed it at exactly 30 secs. No reverse proxy, same error message...

**Comment by larkox** [comment]
I think I pinpointed the issue. Will let you know when it is fixed.

**Comment by xmoov** [comment]
Looking forward to it. Clients are restless.

**Comment by larkox** [comment]
@xmoov The fix should be available in 2.7 (August release). It will probably be available in next Wednesday beta, so I would appreciate if you could verify the fix then.

**Comment by helgehatt** [comment]
@larkox I find it hard to believe that this fix resolves the actual issue. Maybe for @xmoov, but I’m having upload problems on iOS, and the OP also specifically states «This issue persist on iOS or Android. Indiscriminate.»

**Comment by enahum** [comment]
> @larkox I find it hard to believe that this fix resolves the actual issue. Maybe for @xmoov, but I’m having upload problems on iOS, and the OP also specifically states «This issue persist on iOS or Android. Indiscriminate.»

@helgehatt is the statement true when trying on our community server?

**Comment by helgehatt** [comment]
@enahum Okay, so I’ve tested on the community server now, and uploading a two minute video or ten images works fine and is much faster than on my server. However, when trying to upload multiple videos I get the exact same error. To me it seems like you can get away with bigger file sizes with higher upload bandwidth, but the underlying issue persists regardless. I’m getting the error when uploading four one minute videos. Should be fairly easy for you to reproduce the error yourselves.

**Comment by helgehatt** [comment]
I bet that if I was in an area with bad cellular reception (read: low upload bandwidth) I wouldn’t be able to upload a single one minute video to the community server either.

**Comment by eric-benjamin** [comment]
> I bet that if I was in an area with bad cellular reception (read: low upload bandwidth) I wouldn’t be able to upload a single one minute video to the community server either.

Did you time how long it took to fail? Was it 30 as previously reported?

**Comment by eric-benjamin** [comment]
> I bet that if I was in an area with bad cellular reception (read: low upload bandwidth) I wouldn’t be able to upload a single one minute video to the community server either.

Did you time how long it took to fail? Was it 30 seconds as previously reported?

**Comment by helgehatt** [comment]
@eric-benjamin It’s definitely not exactly 30 seconds. Somewhere between 30-40 seconds, and the uploads doesn’t necessarily fail at the same time.

**Comment by helgehatt** [comment]
I can send a screen capture if that would help.

**Comment by helgehatt** [comment]
Right now I’m in an area with mediocre cellular reception (about 10Mbps upload speed), and I am no longer able to upload ten images to the community server.

https://github.com/mattermost/mattermost-mobile/assets/12933913/a06b9d67-654c-45d1-8a52-bfbc7f711b3e

**Comment by enahum** [comment]
@larkox would you say this would be fixed with the recent changes about the timeout defaults?

**Comment by larkox** [comment]
@enahum Should be, yes.
