### ISSUE TITLE
[iOS] Mattermost consumed 18% of battery with just 1 min usage on screen

### ISSUE THREAD

**Issue by frandominguezl** [mattermost/mattermost-mobile#5834]
#### Summary
Excesive battery consume with really low usage on screen of the app

### Environment Information
  - Device Name: iPhone 13
  - OS Version: iOS 15.1
  - Mattermost App Version: 1.48.0 (Build 360)
  - Mattermost Server Version: 6.0.1

#### Steps to reproduce
I believe this is somehow related to notifications, since I didn't open the app yesterday but I did receive notifications.

#### Expected behavior
I received a few notifications, and with just 1 min of screen usage, the app consumed 18% of the battery of my phone.

#### Observed behavior (that appears unintentional)
(The screenshots are in spanish, please let me know if you don't understand something)

![ss2](https://user-images.githubusercontent.com/10365222/142391534-f7ded9e9-953c-489c-9913-d2e50bc5e72f.jpeg)
![ss1](https://user-images.githubusercontent.com/10365222/142391567-1a6e73ef-72ce-4ad4-a064-8a5f5e3ce6a4.jpeg)

**Comment by amyblais** [comment]
@enahum Similar has been reported before, is there a ticket for this or is this on track for V2?

**Comment by enahum** [comment]
@amyblais nothing is being done to determine what could cause the battery consumption really...

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-40183

**Comment by amyblais** [comment]
Closing as this is currently not a priority,
