### ISSUE TITLE
Android: Sending message often fails, retrying always fails.

### ISSUE THREAD

**Issue by adsche** [mattermost/mattermost-mobile#5835]
#### Summary
Sending a message almost always fails despite an active connection (receiving at the same time works). Resending ("try again") always fails. When refreshing (swiping up) the message is successfully sent and appears, however, as a duplicate; the failed message is still there.

### Environment Information
  - Device Name: Nokia 8.1
  - OS Version: Android 11
  - Mattermost App Version: 1.48.0 (Build 3000380) from Play Store
  - Mattermost Server Version: 6.0.1

#### Steps to reproduce
Select a channel and type a message. Even when a Wifi connection definitely works (I'm receiving mattermost messages in the same channel, no toast is active), sending fails every time with a freshly opened app. The message appears grey with a red (!). Tapping the (!), I can select "Try again". This has never once worked. However, when I wipe up, the message is sent and appears. (I know that it is only now sent, because it now also appears in the desktop app). The failed message remains there. 

The messages are also sent when I let the screen lock activate by just waiting and then unlock the phone. After that (unlocking with Mattermost active) all messages will be sent successfully!
This is currently for me the only way to get Mattermost to work properly.

#### Expected behavior
The messages should be sent, the connection is established.
"Try again" should succeed (sending is obvously possible because swiping up works)
After swiping up, the failed messages should disappear because they had been successfully sent.

#### Observed behavior (that appears unintentional)
see above.

**Comment by eklockare** [comment]
I get this all the time, very frustrating. At least let me copy the failed message, ending having to retype the entire thing. I don't use the app enough to remember to copy thr text before sending 😓

**Comment by adsche** [comment]
@eklockare hey, thanks for confirming my report. can I ask you a few questions? I've been trying to isolate myself where this bug comes from. are you the admin of your mattermost instance or do you maybe otherwise know whether you use mysql or postgres as database backend? also, do you use the new/experimental "collapsed reply threads" feature?

**Comment by larkox** [comment]
@adsche can you confirm if this is still happening on the latest version of the beta (V2)?

**Comment by adsche** [comment]
@larkox does not seem to happen with the beta.

**Comment by rikrdo89** [comment]
I am experiencing the same issue in V2.1.0 in android. Messages failed to send almost always when I first open the app, hitting retry again always send msg successfully.
