### ISSUE TITLE
Latex and inline-Latex not parsed in mobile app

### ISSUE THREAD

**Issue by someone-somenet-org** [mattermost/mattermost-mobile#5840]
#### Summary
Latex and inline-Latex not parsed in mobile app

### Environment Information
  - Device Name: OnePlus 5t
  - OS Version: LOS 18.1
  - Mattermost App Version: 1.48.0
  - Mattermost Server Version: 6.1.0

#### Steps to reproduce
+ Write some Latex and inline-Latex in webapp
```
Inline-rainbow
# $\color{red}r\color{orange}a\color{yellow}i\color{green}n\color{blue}b\color{Indigo}o\color{violet}w$

latex-codeblock
\```latex
X_k = \sum_{n=0}^{2N-1} x_n \cos \left[\frac{\pi}{N} \left(n+\frac{1}{2}+\frac{N}{2}\right) \left(k+\frac{1}{2}\right) \right]
\```
```
(backslashes before the code block were added here in github issue)

+ shows neatly in webapp
![image](https://user-images.githubusercontent.com/5354356/142910714-ccca761e-1ab9-402f-a0c2-f72e47015ca3.png)

+ try to read it in android app - not so neat
![image](https://user-images.githubusercontent.com/5354356/142910874-4dfadf3a-5cd6-45fa-acdf-f4c6b5c408f7.png)

#### Expected behavior
Latex and inline-Latex code being parsed in webapp and android app

#### Observed behavior (that appears unintentional)
The Android App doesn't parse the Latex and inline-Latex code.

**Comment by enahum** [comment]
This is yet to be merged https://github.com/mattermost/mattermost-mobile/pull/5651
