### ISSUE TITLE
Client reports incorrect server version 6.2.0

### ISSUE THREAD

**Issue by daniel-jirca** [mattermost/mattermost-mobile#5842]
#### Summary
Mobile client reports server version as being 6.2.0, when currently the latest release available is 6.1.0.

### Environment Information
  - Device Name: Xiaomi Mi 9T
  - OS Version: Android 11
  - Mattermost App Version: 1.48.0
  - Mattermost Server Version: Build Hash: fd8fea804bba2a9ffa0127e40e4d7cacb6698a5b

#### Steps to reproduce
Open settings in the mobile app and click the about menu entry.

#### Expected behavior
Correct server version should be reported.

#### Observed behavior
![Screenshot_20211123-231309_Mattermost](https://user-images.githubusercontent.com/2178486/143131464-1d6e9728-be86-4af6-94e4-5aa86a55889c.png)

**Comment by enahum** [comment]
It seems you are running the master branch, but regardless of that the mobile app just displays the server verdion that is sent by the server in the config, mobile app has nothing to do with the determine the server version.

**Comment by daniel-jirca** [comment]
The same version is shown even after a server update.
The web client shows 6.2.0 as a database schema version.
Afaik there is no 6.2.0 server version, that's why I suspect that the version might be taken from the wrong "source".
![Screenshot_20211124-095838_Firefox](https://user-images.githubusercontent.com/2178486/143198030-6fd90ce4-470d-4e07-9878-818463aee268.png)

**Comment by amyblais** [comment]
@daniel-jirca What steps did you take to download / upgrade to 6.1?

**Comment by daniel-jirca** [comment]
I run the `mattermost/mattermost-team-edition:master` docker image so I just did a `docker pull` and restart.
