### ISSUE TITLE
When will version 1.48 be released?

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#5863]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Bug report in one concise sentence

### Environment Information
  - Device Name:
  - OS Version:
  - Mattermost App Version:
  - Mattermost Server Version:

#### Steps to reproduce

After replacing the profile image, the dim screen does not disappear
It works normally in version 1.48 released on Google Play

#### Possible fixes

It works normally in react-native 0.66.
I think it may be a bug that occurs in react-native 0.65 (mattermost-mobile-1.47.2)

**Comment by amyblais** [comment]
cc @enahum

**Comment by enahum** [comment]
Thanks, publishing
