### ISSUE TITLE
Android APP cannot save images

### ISSUE THREAD

**Issue by Molyleaf** [mattermost/mattermost-mobile#5876]
#### Summary
There is only share and public link buttons, but not save to gallery in image preview screen.

### Environment Information
  - Device Name: All Andriod Phone
  - OS Version: From Android 11 to Harmony OS 3
  - Mattermost App Version: 1.4.8, the latest
  - Mattermost Server Version: 6.1.0, the latest

#### Steps to reproduce
Open image preview screen, you won't see download button.

#### Expected behavior
Download button appears on left bottom

#### Observed behavior (that appears unintentional)
Download botton not found

#### Possible fixes
# I've seen issues as early to Jan,2021, can't you fix the very very small problem in a year?

**Comment by amyblais** [comment]
Thank you for the feedback, we have a ticket here to track this: https://mattermost.atlassian.net/browse/MM-32204.

**Comment by Molyleaf** [comment]
> Thank you for the feedback, we have a ticket here to track this: https://mattermost.atlassian.net/browse/MM-32204.

will

**Comment by Molyleaf** [comment]
> #### Summary
> There is only share and public link buttons, but not save to gallery in image preview screen.
> 
> ### Environment Information
> * Device Name: All Andriod Phone
> * OS Version: From Android 11 to Harmony OS 3
> * Mattermost App Version: 1.4.8, the latest
> * Mattermost Server Version: 6.1.0, the latest
> 
> #### Steps to reproduce
> Open image preview screen, you won't see download button.
> 
> #### Expected behavior
> Download button appears on left bottom
> 
> #### Observed behavior (that appears unintentional)
> Download botton not found
> 
> #### Possible fixes
> # I've seen issues as early to Jan,2021, can't you fix the very very small problem in a year?
> ## Telegram can, Rock




> Thank you for the feedback, we have a ticket here to track this: https://mattermost.atlassian.net/browse/MM-32204.

It hurts a lot to user impressions.

**Comment by wicaodian** [comment]
It's so frustrating that Unable to download images

**Comment by gigawhitlocks** [comment]
Sharing (at least to Google Messages) no longer works, either, so there's no way to share an image from Mattermost to a text message without having a third party web service to upload the image to in the interim. 

I currently work around this by having a NAS that I can upload images to, and then I share images to other apps from my NAS's app.

**Comment by amyblais** [comment]
This is implemented in Mattermost Mobile V2 Beta. Please see more details here: https://mattermost.com/blog/mobile-beta-program-v2/.

**Comment by CptPlastic** [comment]
This is still broken after all this time. Was the fix ever pushed to the mobile app?
