### ISSUE TITLE
Android app cannot set status to never clear

### ISSUE THREAD

**Issue by rinkimekari** [mattermost/mattermost-mobile#5892]
When trying to set a custom status in the Android mobile app to never clear, it seems initially that it worked. However, the button then says "Failed to update status. Try again." The status falls back to what was there before, and when trying to set a new status to never clear, it doesn't have a status to fall back on, so it's nothing.

I will happily provide screenshots if needed, and I have a sneaking suspicion that the code is not properly checking for the "Don't clear" option because this happens after restarting the app and my phone, and I forgot about it for about a month and came back and tried again and it still didn't work.

My app version is v1.48.1 and the server version is V6.3.0 (the Mattermost community server).

Thank you to any and all who help! I would try to figure it out on my own but my JavaScript skills are abismal.

**Comment by amyblais** [comment]
We have a ticket for this here https://mattermost.atlassian.net/browse/MM-40206, and we are planning to release a fix for it soon.

**Comment by rinkimekari** [comment]
Ah thanks! I didn't see that site when I searched for the issue. I'll wait patiently for the fix!

**Comment by amyblais** [comment]
This has now been fixed in v1.48.2 dot release.

**Comment by rinkimekari** [comment]
Thanks! It's working perfectly.
