### ISSUE TITLE
There is a problem with the public link copy function.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#5904]
#### Summary
There is a problem with the public link copy function.

### Environment Information
  - Device Name: ios, android
  - OS Version: 
  - Mattermost App Version: 1.48.2
  - Mattermost Server Version:

#### Steps to reproduce
1. Upload multiple images.
2. Slide the image.
3. Press the 'Copy Public Link' button.
4. Paste it into your web browser address to confirm.
5. The first image before the image slide is rendered.

#### Expected behavior
The image address after sliding should be copied.

#### Observed behavior (that appears unintentional)
The first image before the image slide is rendered.

#### Possible fixes
There is a problem with the copypublicLink method in footer/index.tsx .
Even if the file property value is changed, the file.id value in the method is not changed.

Below is what I have edited.
summary/actions/action.tsx
const onPress = useCallback(async () => {
        setDisabled(true);
        action(() => {
            setDisabled(false);
        });
    }, [action]);    //add action to dept array

**Comment by amyblais** [comment]
@josephbaylon Are you able to reproduce this?

**Comment by amyblais** [comment]
I opened a ticket: https://mattermost.atlassian.net/browse/MM-41113.

**Comment by amyblais** [comment]
Closing as fixed,
