### ISSUE TITLE
Mattermost iOS uploads HEVC videos that don't play back in desktop Firefox

### ISSUE THREAD

**Issue by wezm** [mattermost/mattermost-mobile#5906]
#### Summary

A video uploaded in the iOS app does not playback on Firefox Linux

### Environment Information

- Device Name: iPhone 12 mini
- OS Version: iOS 15.1.1
- Mattermost App Version: 1.48.2 (Build 382)
- Mattermost Server Version: 6.3.0
- Firefox version 96.0 on Arch Linux

#### Steps to reproduce

1. Record a video with the iOS Camera app
2. Upload this video to a channel in Mattermost using the iOS Mattermost app
3. Attempt to watch the video in desktop Firefox on Linux (I did not try other OSes or browsers). My Firefox version is 96.0
4. The viewer pops up but only audio plays

#### Expected behaviour

It's expected that the video plays back in Firefox.

#### Observed behaviour (that appears unintentional)

This is what Mattermost looks like when trying to play the video

<img width="1154" alt="Screenshot from 2022-01-21 11-31-49" src="https://user-images.githubusercontent.com/21787/150449283-7001cb18-f53d-44cc-a76a-80f9641e23ac.png">

On this page: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#common_codecs Mozilla not that Firefox does not support HEVC in a Quicktime container, which is what the Mattermost iOS app uploaded.

The movie in question is attached here:

https://user-images.githubusercontent.com/21787/150449671-d9686d2d-7b98-4b42-a6fd-a4926bbb8997.mov

The issue is actually reproduced right there as the movie does not play back in Firefox here either.

This is the codec information from VLC:

<img width="673" alt="Screenshot from 2022-01-21 11-23-15" src="https://user-images.githubusercontent.com/21787/150451698-ceba46a7-13b4-4210-a324-412ed8ec5055.png">

#### Possible fixes

* Since iOS 11 (released 2018) iPhone started recording in HEVC (h.265) by default and exports these in a QuickTime (mov) container, which [Firefox does not support](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#common_codecs)
*The iOS app should use an export session to transcode the video when uploading to Mattermost to maximise compatibilty: https://stackoverflow.com/a/59879591/38820

**Comment by wezm** [comment]
#1015 is related, it's closed but perhaps they only dealt with images.

**Comment by amyblais** [comment]
@wezm Would you be open to test if you can reproduce this issue on our community server here https://community.mattermost.com?

**Comment by wezm** [comment]
Confirming the issue happens there too: https://community.mattermost.com/core/pl/9qyjaq1jr3dhifers4hcunwbsr

**Comment by wezm** [comment]
I just checked in Firefox on macOS and the behaviour is the same.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-41201.

**Comment by amyblais** [comment]
Closing as we haven't been able to reproduce this internally,

**Comment by maxsz** [comment]
This is still broken, please reopen, thanks.

**Comment by melloware** [comment]
I can reproduce this.  The trick is if someone with an iPhone sends you a Text message with a picture. Click on the picture and you try and share that picture right from the text in MatterMost it just shows it as an HEIC attachment.  

However if I save the photo to my Photos in iOS and share it from there it seems to work.    Hope that helps...
