### ISSUE TITLE
I want to download the excel file.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#5929]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Bug report in one concise sentence

### Environment Information
  - Device Name: emulator
  - OS Version: android os 11
  - Mattermost App Version: 1.48.2
  - Mattermost Server Version:

#### Steps to reproduce
Click the excel file in the message.

#### Expected behavior
Now, when I click on the file, the Excel app is launched. 
But I wish I could download the excel file.
I wish I could download it even if the Excel app is not installed.

#### Observed behavior (that appears unintentional)
The Excel app does not open or run.
![image](https://user-images.githubusercontent.com/42505950/152506673-af0135a7-7fd9-424b-a47d-773730bea1ff.png)

#### Possible fixes
I am unable to install the Excel app on my phone.
So the excel file cannot be executed.
Even if the Excel file does not open on the phone, is there any way to download it?

**Comment by amyblais** [comment]
@enahum Let me know if you have thoughts on if this is a bug.

**Comment by enahum** [comment]
@amyblais there is a story ticket for this

**Comment by amyblais** [comment]
Thanks, if you happen to know the link please post it here, I did a quick search and didn't find it now.

**Comment by enahum** [comment]
https://mattermost.atlassian.net/browse/MM-32204

**Comment by bitdessert** [comment]
@amyblais @enahum I wish I could directly download other files as well as images or excel files. 
May I know when the feature will be applied?
Which version are you planning to release?

**Comment by enahum** [comment]
@bitdessert a contribution is very much welcome ;) otherwise I don't think is going to happen soon

**Comment by amyblais** [comment]
This is implemented in Mattermost Mobile V2 Beta. Please see more details here: https://mattermost.com/blog/mobile-beta-program-v2/.
