### ISSUE TITLE
iOS share screen unnecessary scroll view

### ISSUE THREAD

**Issue by abel-vs** [mattermost/mattermost-mobile#5983]
#### Summary
When sharing a document, the share screen has an unnecessary scroll view over the whole content and thereby the "Channels" tab is partly covered.

### Environment Information
  - Device Name: iPhone 12 mini
  - OS Version: 15.1.1
  - Mattermost App Version: 1.48.2 (Build 382)
  - Mattermost Server Version: 6.3.2

#### Steps to reproduce
Try to share any file with Mattermost and scroll over the share screen.

#### Expected behavior
The share screen is only scrollable in the text field, and only when it is needed.
The "Channels" tab is completely visible.

#### Observed behavior (that appears unintentional)
When sharing a document, the share screen has an unnecessary scroll view over the whole content and thereby the "Channels" tab is partly covered. There is also a second scroll view for the text input field, which is necessary when the text height becomes too large.

https://user-images.githubusercontent.com/45075577/154498450-ba8b36d4-64a0-4e6f-8a4a-29fe8d038798.mov

#### Possible fixes
Remove the scroll function over the whole content and increase the height of the screen a bit such that the "Channels" tab is fully visible.

**Comment by Abel-VS** [comment]
I would like to solve this issue myself.

**Comment by larkox** [comment]
There has been many changes regarding this on V2. @abel-vs can you confirm if this is still happening in the latest beta version (v2)?
