### ISSUE TITLE
SVGs are abnormally large (original size) even with width and height specified

### ISSUE THREAD

**Issue by Thoro** [mattermost/mattermost-mobile#5994]
#### Summary
Since svgs are now displayed (#5869 , MM-40588) - and the mobile app does not appear to adhere to the size limits referenced here: https://docs.mattermost.com/messaging/formatting-text.html#in-line-images , svgs are displayed in their ?original? size. Which in my case is abnormally large.

### Environment Information
  - Device Name: iPhone 12
  - OS Version: 15.3.1
  - Mattermost App Version: 1.49.0 (Build 385)
  - Mattermost Server Version: 5.39.1

#### Steps to reproduce
Use a large svg with a url provided over the internet, and specify a width or a height in the formatting string. On mobile the image will be ~600 px large (original size), but on desktop it will be the specified size (50px) 

![Image](https://upload.wikimedia.org/wikipedia/commons/3/30/Vector-based_example.svg =x50 "Image")

Additionally the example for specifing the width, results in a parsing error (plain text displayed)

![Mattermost](../images/icon-76x76.png =50 "Mattermost Icon")

#### Expected behavior
Images should have the size specified in the markdown.

#### Observed behavior (that appears unintentional)
Images are their original size

#### Possible fixes
Correctly parse the width and height information and use it to scale the svgs.

**Comment by enahum** [comment]
@esethna can you please open this as Help Wanted?

@Thoro Would you be insterested in providing a fix for it?

**Comment by Thoro** [comment]
@enahum I will try, but can't promise anything - it's blocking my workflow. No doing anything regularly wit react / ios. 

Pointers on where to change would be appreciated.

**Comment by wandersiemers** [comment]
I can reproduce this

**Comment by esethna** [comment]
Opened a ticket for this here and set to HW: https://mattermost.atlassian.net/browse/MM-42220

**Comment by wandersiemers** [comment]
I'd be interested in working on this, however I first have to resolve some issues with building before I can.

**Comment by wandersiemers** [comment]
I have resolved the issues and would like to work on this issue.

**Comment by wandersiemers** [comment]
Okay, did some research on this. First of all, there are big differences in the rendering of markdown images between iOS and desktop. This syntax works on desktop for adding size information (in this case height=200) to the SVG: `![Image](svg_url =x200 "Image")`. However: it doesn't on mobile (that's the bug described in this issue): the image will just render at full size. But there are more differences: for example, `![Image](svg_url =200x "Image")` should add the size info (width = 200) to the image, but it render the full size image on iOS whereas the rendering fails on desktop.

To illustrate, the images below should have, respectively, height 50, then 200, then width 200. As you can see, the last image doesn't render, but I believe it should. On mobile, all images work but are full size.

I'm not quite sure what the spec for svg images in Mattermost is here. It seems that both desktop and mobile are wrong. Specifically, is the width syntax (`![Image](svg_url =200x "Image")`) supported?

**Comment by enahum** [comment]
There is a PR for this already. It now supports setting the size for example `=100`and `=100x` sets a width of 100, `=x100` does it for the height and `=100x80` would be a width of 100 and height of 80. This is applicable for all markdown images including SVG's

The reason svg where being rendered that big is that they do not have metadata in the post about its size, so if you added an svg with a huge viewport that was being used, now if not size is set, it will use the screen viewport as constraint.

Hope that clarifies and helps.

**Comment by wandersiemers** [comment]
Ah, hadn't seen the new PR, sorry for that! Thanks for the clarification @enahum, learnt something new :)
