### ISSUE TITLE
iOS Swipe back from navigation not working on Teams overview

### ISSUE THREAD

**Issue by CeesJol** [mattermost/mattermost-mobile#6006]
#### Summary
In iOS (possibly in Android too), swiping back from navigation to the channel - i.e., closing the hamburger menu, does not work, given that the user has swiped back to the "Teams" overview.

### Environment Information
  - Device Name: iPhone 12
  - OS Version: iOS 15.3.1
  - Mattermost App Version: 1.49.0 (Build 385)
  - Mattermost Server Version: 6.3.2

#### Steps to reproduce
1. Open a channel
2. Open the hamburger menu
3. Swipe right to the "Teams" overview
4. Try to remove the hamburger menu by swiping left (this should bring you back to the channel)

#### Expected behavior
Go back to the channel

#### Observed behavior (that appears unintentional)
Swipe is not possible: nothing happens

**Video:** first the observed behavior, second the expected behavior

https://user-images.githubusercontent.com/33723088/155543691-bd20ab57-3a04-41ed-b5d5-437fafbf7ee9.MP4

#### Possible fixes
n/a

**Comment by CeesJol** [comment]
I would like to solve this issue myself.

**Comment by amyblais** [comment]
@CeesJol Feel free to take the issue 👍

**Comment by larkox** [comment]
The navigation on V2 has changed, so this should not be valid anymore.
