### ISSUE TITLE
No visible @interface for 'UIKeyCommand' declares the selector 'setWantsPriorityOverSystemBehavior:'

### ISSUE THREAD

**Issue by Avi00001** [mattermost/mattermost-mobile#6013]
- Device Name: Iphone 11 Pro(Simulator)
  - OS Version: 14.4
  - Mattermost App Version: 1.49
![Screenshot 2022-02-28 at 10 44 41 AM](https://user-images.githubusercontent.com/100348868/155934283-b1c97672-800b-4607-9d66-1b991b73d7d0.png)

#### Steps to reproduce
At the time of compile the code on xcode

#### Expected behavior
when I am trying to compile the code on Xcode then build failed with this error
No visible @interface for 'UIKeyCommand' declares the selector 'setWantsPriorityOverSystemBehavior:'.

#### Possible fixes
Do I need to update my Xcode to 13 Version?

**Comment by enahum** [comment]
> Do I need to update my Xcode to 13 Version?

Yes!
