### ISSUE TITLE
Missing app for Windows 10 Phone

### ISSUE THREAD

**Issue by yareach** [mattermost/mattermost-mobile#6023]
There is no app for Window 10 Phone which is newer than Android 7. Moreover, a UWP app for Windows 10 desktop can be deployed on ARM-based Windows Phone device with very low effort.

**Comment by charan9999** [comment]
wait, who is using windows phone??

**Comment by yareach** [comment]
I am. Why would I buy a new one if it works? A lot of work to move all apps! BTW - Slack runs on it.
I could ask the same questions on any subject: Who is driving a 30-years old Porsche? Who is reading 2000-years old bible?
And I still have my Motorola V500 and Nokia N97. Nice small devices and both work. I use the latter to play fairy tales for my son. In the other hand iPhone 3 is in a box because it does not serve for anything. My only hope is I'll find a coleccionar who'll buy it. If you were interested, let me know. ;)

**Comment by charan9999** [comment]
It's not about wether you are interested in buying a new phone?? It's about the fact that people do use it other than the two major mobile operating system's which is Android and iOS. As it is not reasonable for developers to work on platforms with not much user base. Funny thing is you mentioned Bible, which is completely different scenario and not making any point. I'm not sure what you got so offended off. Lol.

**Comment by yareach** [comment]
I'm not offended. You'll have to try a lot harder if you want me to be. Don't confuse me me with a girl on Instagram who posted her 100th selfie today and you instead of just clicking like dared commenting on her lipstick color.
You remind me of conversation with a girl from Chile 20 years ago. Those times on ICQ. She told me she wanted to learn Catalan. I replied: "Why would somebody learn a language that is used by so low number of people? Isn't it better English, or Portuguese?" She replied me something in the sense that I can say one language is more important or better than the other just because of the number of users. And then she told me: "So why don't you start learning Mandarin?" Well, she was right. She liked that language and she wanted to learn it. BTW I started to learn Mandarin 10 years later but not because of the number of users. I just found it interesting and challenging.
And the "interesting" and "challenging" is something that I would look for in the open source software development. Because who is hunting for numbers are the marketers from big corporates.
And one more thing: You're right the OS is end of life. But if you check the UWP framework, you'll find out that you can use the same source code for Windows on PC and for Windows Phone. So if you write an app for Windows PC, there is no extra effort. And if you are worried about testing, just mark it as beta or ask me to test it for you. I don't need a perfect app, it's enough to have something just to see that somebody replied. I'm lazy to type on screen.

**Comment by Nixellion** [comment]
I am not developer of Mattermost but I am pretty sure its made with Electron, which basically runs its web version in a browser inside the app. This does not work with UWP. If windows app was made with UWP framework initially then it would not have required much effort to port. Assuming all APIs are available on mobile. But its not written with UWP and not even as a native C# or C++ app. Its a web browser that runs html and js, using Chromium or WebKit engine. I dont think it will work easily on Win Phone, unfortunately.

Win Phone is, sadly, end of life. You can not expect people to make new apps for it, unless its someone like you, who still uses it and would go into an effort to make one. And support it, it will need updates most likely.

**Comment by larkox** [comment]
We have no plans on short term to support Windows 10 Phone for Mattermost, unless we see a relevant increase of interest in this.
