### ISSUE TITLE
Svg images are not inlined

### ISSUE THREAD

**Issue by Thoro** [mattermost/mattermost-mobile#6048]
There‘s a issue, MM-40588, which has inline in the text, but it‘s just about supporting svg rendering, the inlineing doesn‘t work in newest beta 1.50

#### Summary
Svg images are displayed in the correct size, but are not inlines

### Environment Information
  - Device Name: iPhone 12
  - OS Version: 15.3.1
  - Mattermost App Version: 1.50 beta
  - Mattermost Server Version: 5.39.1

#### Steps to reproduce
Place multiple small svgs on a line.

```
![wiki](https://upload.wikimedia.org/wikipedia/commons/0/07/Wikipedia_logo_%28svg%29.svg =x16) ![wiki](https://upload.wikimedia.org/wikipedia/commons/0/07/Wikipedia_logo_%28svg%29.svg =x16) ![wiki](https://upload.wikimedia.org/wikipedia/commons/0/07/Wikipedia_logo_%28svg%29.svg =x16) ![wiki](https://upload.wikimedia.org/wikipedia/commons/0/07/Wikipedia_logo_%28svg%29.svg =x16)

```

#### Expected behavior
All svgs should be displayed side by side.

#### Observed behavior (that appears unintentional)
Svgs are displayed above/below each other

#### Possible fixes
Probably the rendering needs to be set to inline-block

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-42463.

**Comment by amyblais** [comment]
A response from a dev:
This is expected. Every inline image regardless of the type is not rendered side by side. Inline images differ from the webapp in this respect.

**Comment by Thoro** [comment]
Is it possible to test the v2 implementation?

i also noticed parsing irregularties if svgs (or images.. not sure) are used:

- last image not displayed
- Links not parsed and displayed

both work fine on the webapp

**Comment by amyblais** [comment]
We are planning a beta release of v2 in a few months from now.
