### ISSUE TITLE
$ $ causes the mobile app to crash

### ISSUE THREAD

**Issue by pinktrink** [mattermost/mattermost-mobile#6073]
#### Summary
A message containing the string $ $ will cause the mobile app to crash when visiting that channel

### Environment Information
  - Device Name: Pixel 5
  - OS Version: 11
  - Mattermost App Version: 1.50.0 (Build 3000387)
  - Mattermost Server Version: 6.3.0 (Build 6.3.0-nixpkgs)

#### Steps to reproduce
Post $ $ (an empty LaTeX block) to a channel and attempt to visit it in the mobile app

#### Expected behavior
The app shouldn't crash

#### Observed behavior (that appears unintentional)
A user had created a post with the text `;$ $(` in a joking reference to emoji. Any time anyone would visit said room via the mobile app it would crash. Removing the offending content caused the app to work again. We do have LaTeX support enabled.

**Comment by pinktrink** [comment]
![Screenshot_20220319-152205](https://user-images.githubusercontent.com/660917/159142589-c501bc17-ac07-449b-bed8-28ed0a5b056d.png)

**Comment by enahum** [comment]
Already fixed with https://github.com/mattermost/mattermost-mobile/pull/6064 which should ve release on monday

**Comment by pinktrink** [comment]
Perfect, thanks.
