### ISSUE TITLE
Latex doesn't get rendered on iOS mattermost app

### ISSUE THREAD

**Issue by harmeling** [mattermost/mattermost-mobile#6087]
#### Summary
Latex not rendered on iOS mattermost app.

### Environment Information
mattermost server: 6.4.2
mattermost app on iPhone: v1.50.1
iOS: 15.3.1 (iPhone 13) is not working.
Mattermost on macOS (11.6.4) is working fine and I can post and view messages as usual.

#### Steps to reproduce
Put some latex stuff like $x=\pi$ into a post.
On Mattermost on iOS it is **not** rendered.
On Mattermost on macOS it is rendered.

#### Expected behavior
Latex should render correctly on iOS
.
#### Observed behavior (that appears unintentional)
Latex does not render correctly on iOS.

#### Possible fixes
This might be related to the recent update which solved https://github.com/mattermost/mattermost-mobile/issues/6070

**Comment by enahum** [comment]
Sorry my friend. The issue is not related as Latex is not supported at this moment. There is someone attempting to add support as a contribution, see #5651 is been a bit stale, not sure why, but perhaps you or someone uou know can offer to help him?

**Comment by harmeling** [comment]
Ok!  Sorry, didn't that Latex was supported!  Thanks for your speedy response!
