### ISSUE TITLE
Re-login does not show SSO options in Mattermost Android

### ISSUE THREAD

**Issue by gudladona** [mattermost/mattermost-mobile#6183]
#### Summary
Re-login does not show SSO options in Mattermost Android

### Environment Information
  - Device Name: Google Pixel 6 Pro
  - OS Version: Android 12
  - Mattermost App Version: 1.51.0
  - Mattermost Server Version: 6.6.0

#### Steps to reproduce
Enable 2 SSO logins on MM server. Logout of mattermost app. 

#### Expected behavior
App login to mattermost server shows all available SSO options

#### Observed behavior (that appears unintentional)
User is prompted for user/pass, any credentials for the SSO accounts does not work.(obviously)

Open post in forum: https://forum.mattermost.com/t/re-login-does-not-show-sso-options-in-mattermost-android/13260

**Comment by amyblais** [comment]
@josephbaylon @enahum Are you able to reproduce on Android and is it a regression? Could it be related to https://mattermost.atlassian.net/browse/MM-42868?

**Comment by gudladona** [comment]
FWIW, iOS users are experiencing the same in my org.

**Comment by gudladona** [comment]
https://github.com/mattermost/mattermost-mobile/blob/55b1fa5c55bd6912550adfb69745d621603e9039/app/screens/select_server/select_server.js#L262 -- seems to  be the issue. Code seem to assume the login by email/username is enabled. We dont have any such thing. We only allow login by SSO, as most orgs do now a days.

**Comment by enahum** [comment]
@gudladona can you confirm that you have only SSO enabled but MORE than one at the same time ?

**Comment by gudladona** [comment]
We have 2 SSO enabled Gsuite and Office365

**Comment by enahum** [comment]
@amyblais then the answer is yes, this would be caused by the ticket you linked.

**Comment by amyblais** [comment]
@enahum I created a ticket https://mattermost.atlassian.net/browse/MM-43607. I think this is a candidate for a dot release if you agree.

**Comment by enahum** [comment]
Submitted a PR to fix it #6185 in the PR there will be a link posted for the Android build that you could use to try it out while we go through the whole release process.

Thanks for reporting.
