### ISSUE TITLE
login field lacks cursor on first run (even after clicking) on android

### ISSUE THREAD

**Issue by caryoscelus** [mattermost/mattermost-mobile#6321]
#### Summary
on the first run application asked to login , but the login field wasn't visually in focus (lacked cursor)

### Environment Information
  - Device Name: android
  - OS Version:
  - Mattermost App Version: 1.52
  - Mattermost Server Version: 6.3.3

#### Expected behavior
login field should be in focus and display cursor on first login or at least when clicked on it

#### Observed behavior (that appears unintentional)
i tried clicking on "login/email" field many times, changing focus to password and back and it never showed any visual signs of getting focus . however when i realized that the keyboard is present , i started entering login credentials and it worked fine so the issue is just about being visually confusing rather than non-functional

**Comment by amyblais** [comment]
@caryoscelus 
1. What Android version are you on?
2. Can you (optionally) share a screenshot or a short video of what you're seeing?

**Comment by caryoscelus** [comment]
1. 10
2. i can try , but entering a password on the screen is so painful so i'd rather keep myself logged in for a bit

**Comment by amyblais** [comment]
I don't have Android to test this. @enahum @saturninoabril Are you able to help test this on Android?

**Comment by amyblais** [comment]
@jgilliam17 Would you be open to help test this one as well?

**Comment by jgilliam17** [comment]
@amyblais I've tested on v1.52 (398) on Galaxy A52, Android 12 
I've removed the app and started the flow from the beginning download/install, add server and use email and password to login.
Observed: The user name field is not focused, but tapping on the field focuses it and adds a visible cursor.

**Comment by amyblais** [comment]
@caryoscelus Do you see this issue on our community server https://community.mattermost.com/ (it is on the latest server version)?

**Comment by amyblais** [comment]
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),
