### ISSUE TITLE
Cannot set status on mobile (android)

### ISSUE THREAD

**Issue by brynwhyman** [mattermost/mattermost-mobile#6326]
#### Summary
Unable to set a profile status in the Android mobile app.

App version: 1.52.0
Server version: 6.7.0

#### Steps to reproduce
1. Open mobile app, choose option to 'Set a status'
2. Choose a status from the 'Recent' list
3. Confirm with the 'Done' action

#### Expected behavior
Your status should reflect the changes made

#### Observed behavior (that appears unintentional) 
Your status does not change, the action had no effect.

**Comment by amyblais** [comment]
@brynwhyman What Android version are you on?

**Comment by jgilliam17** [comment]
@amyblais I've checked on v1.52 (398) on Galaxy A52, Android 12 and can set status from Recents

**Comment by amyblais** [comment]
@brynwhyman Do you see this issue on our community server https://community.mattermost.com/?

**Comment by brynwhyman** [comment]
Hi, I've just tried to recreate the issue and I can't. I just upgraded to Android 12 (from 11), but not sure if that would have affected this or not anyway?

Either way, happy to close this. Thanks for the quick response!
