### ISSUE TITLE
Wrong input hints leading to wrong keyboard appearance

### ISSUE THREAD

**Issue by aol-nnov** [mattermost/mattermost-mobile#6408]
#### Summary

Input field has wrong hints, which leads to wrong keyboard type: .com/.net/.org quick button instead of emojis button, emails auto completeion, no typos auto correction. Mattermost client 2.0.0, Gboard. It worked fine before client update, but now it freaks me out every time I'm typing a message!

### Environment Information
  - Device Name: oneplus nord
  - OS Version: 11
  - Mattermost App Version: 2.0.0
  - Mattermost Server Version:

#### Steps to reproduce
While filing a bug I've managed to reliably reproduce it. Actually, keyboard opens with correct hints, but if you type a single character and immediately press backspace, quick buttons in the bottom row and the whole behavior changes as described above.

#### Expected behavior
![Screenshot_20220619-091044](https://user-images.githubusercontent.com/43190/174468259-5fdce356-4d51-4eec-b47e-d25cc0d212ac.jpg)

#### Observed behavior (that appears unintentional)
![Screenshot_20220619-091018](https://user-images.githubusercontent.com/43190/174468276-822941ba-1d58-4db1-be67-f610dcf52333.jpg)

**Comment by kpd200081** [comment]
I can confirm this, I am using Yandex.Keyboard.

Device Name: Mi 9 T Pro
OS Version: 11
Mattermost App Version: 2.0.0

**Comment by enahum** [comment]
Hey @aol-nnov @kpd200081 first of all thank for testing our v2 beta app 🎉 definitely appreciate bug reports like this one.

Yes, at times bugs can be annoying, we'll try to update this version weekly to minimize bugs as we move forward with the addition of other missing features.

The whole idea behind making this v2 beta version of the app publicly available is to receive bug reports like this one and all types of feedback as well, which you could share in our [Feature Mobile v2 channel at the community server](https://community.mattermost.com/core/channels/ship-gekidou--mobile-v2), it would be great if you guys can join and share as much feedback as you want.

Also, you can install our more stable version, still v1 from the play store in case there is a bug on the beta app that prevents you from doing what you need to do while is being fixed or address in the v2 beta app.

Again a massive thank you for this bug report, keep em coming! And hopefully we can see you around in the channel to hear more!

**Comment by enahum** [comment]
One thing I forgot to mention, we already submitted a fix for this bug to React Native https://github.com/facebook/react-native/pull/33924 which should be available in their next release, so as soon as that happens and we are able to upgrade, this issue should be resolved.

**Comment by aol-nnov** [comment]
@enahum thanks for the prompt reply! Glad to hear you've sorted it out already!

To be frank, I was using beta for ages and could bear with almost all sort of bugs (and reported them through appstore) but this one is beyond good and evil! Hope, you'll roll out an update any time soon!

Best,
Andrey

**Comment by enahum** [comment]
Fixed by #6409
