### ISSUE TITLE
Cannot build for release with with Sentry enabled

### ISSUE THREAD

**Issue by PhilippeWeidmann** [mattermost/mattermost-mobile#6410]
#### Summary
When Sentry is enabled the command `npm run build:ios` fails.

### Environment Information
  - Device Name: -
  - OS Version: macOS 12.4
  - Mattermost App Version: 1.53
  - Mattermost Server Version: -
  - NPM version: I tried 7.24.2 and 8.5.5
  - Node version: Tried 15 and 16.15.0

#### Steps to reproduce
Simply enable Sentry in the fastlane env
```
export SENTRY_ENABLED=true
export SENTRY_ORG=myorg
export SENTRY_PROJECT_IOS=projectnameios
export SENTRY_DSN_IOS=dsnios
export SENTRY_PROJECT_ANDROID=projectnameandroid
export SENTRY_DSN_ANDROID=dsnandroid
export SENTRY_AUTH_TOKEN=token
```

Then do `npm run build:ios`

#### Expected behavior
I expect to be able to build the app with Sentry enabled.
 
#### Observed behavior (that appears unintentional)
The first error I had was because Sentry couldn't download the CLI utility when doing `npm install` because scripts are disabled by default.
To fix it, I modified `/scripts/build.sh` -> ln43 I removed the `--ignore-scripts` flag. 
But know I get the following error while building.

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/cli.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

#### Possible fixes
As mentionned above, part of the fix is removing the flag `--ignore-scripts` to go further with the build process but it is still not working.

**Comment by enahum** [comment]
Hi @PhilippeWeidmann we've stopped building with sentry enabled for almost a year, so perhaps there are a few thing that need aome tweaking. A PR would be very much welcome

**Comment by PhilippeWeidmann** [comment]
Thanks, sadly I'm very new to the project and I have never developed an app using React Native. 
Apart from the first fix I added, I didn't manage to get it working 😔

If this is not a priority you can go ahead and close the issue as I don't think I will be able to fix it.

One thing I was wondering is how do you handle the client crash / errors if they are not reported on Sentry ?

**Comment by enahum** [comment]
At the moment we do not have sourcemaps so is a bit complicated (until we re-enable it again), so we basically look at the reports on testflight and the play console.

there are plans to enable this in Q3, not sure if is going to be sentry or another service, but it will be on our v2 app which is currently in open beta. The `gekidou` branch is the main branch for v2

**Comment by PhilippeWeidmann** [comment]
Thanks for the answer 😌
Not sure if you want to close the issue but it's fine for me 👍

**Comment by larkox** [comment]
This should be solved for V2.
