### ISSUE TITLE
Mattermost Changing SwiftKey Keyboard Without User Input

### ISSUE THREAD

**Issue by Orga84** [mattermost/mattermost-mobile#6418]
#### Summary
Mattermost changing SwiftKey keyboard

### Environment Information
  - Device Name: Samsung Galaxy S22 Ultra
  - OS Version: Android 12 / OneUI 4.1
  - Mattermost App Version: 2.0.0
  - Mattermost Server Version: 6.7.2

#### Steps to reproduce
Type text into any channel and insert it. Once the send button has been pressed, the keyboard layout will automatically change.

#### Expected behavior
Whenever I first enter a channel and bring up the keyboard, the layout is correct. As soon as I send any text, the keyboard layout will break and remain broken until such time as I go to a new channel.

#### Observed behavior (that appears unintentional)
Please contact me for a direct video link to the video.

#### Possible fixes
Unknown.

**Comment by Clegko** [comment]
Similar issues are happening to me, as well. I also have the Mattermost Beta (2.0.0) and server 6.7.2, but I am on a OnePlus 9 using GBoard. 

GBoard also doesn't recommend words for auto-correct. It's like the text input field is tagged incorrectly and the keyboard doesn't know how to handle it?

**Comment by enahum** [comment]
This has already been fixed, will be avilable on the next beta build in a weeks time
