### ISSUE TITLE
For some users of the iOS app in v1.53.0 no images, avatars, icons are displayed

### ISSUE THREAD

**Issue by christianhueserhzdr** [mattermost/mattermost-mobile#6424]
#### Summary
When using the newest iOS app in version 1.53.0 no images, avatars, icons are displayed when inspecting posts.

### Environment Information
  - Device Name: -
  - OS Version: iOS
  - Mattermost App Version: 1.53.0
  - Mattermost Server Version: 6.6.1

#### Steps to reproduce
Add Mattermost server in iOS app, become member of a team, inspect posts in channels.

#### Expected behavior
Images, avatars, icons should be displayed.

#### Observed behavior (that appears unintentional)
Broken images, avatars, icons are displayed.

#### Remarks
I expect that this behaviour is a bug because it occurs for several users of the iOS Mattermost app in v1.53.0 independently. First time we noticed this behaviour was some 4 months ago, but the problem still persists. Is this a known behaviour and is it possible to get around this? Thank you very much in advance for your feedback.

**Comment by amyblais** [comment]
This other issue might help: https://github.com/mattermost/mattermost-mobile/issues/4486.

https://github.com/mattermost/mattermost-mobile/issues/4486#issuecomment-1109302515

**Comment by christianhueserhzdr** [comment]
> This other issue might help: #4486.
> 
> [#4486 (comment)](https://github.com/mattermost/mattermost-mobile/issues/4486#issuecomment-1109302515)

Dear Amy @amyblais, thank you very much for pointing to this issue. I think you are right that these issues are related. I will post a comment there as well to ask for a fix for this issue.

**Comment by amyblais** [comment]
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),
