### ISSUE TITLE
Camera app doesn't open on android

### ISSUE THREAD

**Issue by p-baum** [mattermost/mattermost-mobile#6457]
#### Summary
Camera app doesn't open on android

### Environment Information
  - Device Name: Samsung Galaxy s7
  - OS Version: Android 8.0.0
  - Mattermost App Version: 1.53.0 (Build 3000404)
  - Mattermost Server Version: 7.0.1

#### Steps to reproduce
1. touch the camera icon to send a picture
2. Grant all requested permissions
4.  touch camera or video symbol

#### Expected behavior
Camera app/window opens

#### Observed behavior (that appears unintentional)
camera and video icon selectors withdraw and nothing happens

#### Possible fixes
unknown

I was trying to convince my boss to let us start using mattermost when he asked me to send him a photo.  This stopped the show. 

Classic app works btw.

**Comment by amyblais** [comment]
@josephbaylon Are you able to reproduce this on Android?

**Comment by josephbaylon** [comment]
@amyblais It works for me using the app and server versions above. However, I tested on Pixel 3 XL (Android 12). Maybe they might want to try on Android 11 and above.

**Comment by p-baum** [comment]
Yes.  It asks for camera permission, which I grant, and proceeds to do nothing. Repeating after the permission flow also fails to display a camera.

**Comment by larkox** [comment]
@p-baum Just to confirm, it is still with the same device, same version? Have you been able to try with a different device / different android version?

**Comment by larkox** [comment]
@p-baum This should be solved in the latest beta. Do you mind checking?
