### ISSUE TITLE
No voicemail in iOS app

### ISSUE THREAD

**Issue by kaksikanaa** [mattermost/mattermost-mobile#646]
In android user can record a voicemail to another user straight forward but this is not possible in the iOS app and you cant even attach a voice recording from the voice recorder library? You can add photos or video to the chat but no MP3 sound/voicemail.

We need a cross platform compatible videos (MP4) and sounds (MP3).

**Comment by kaksikanaa** [comment]
Just noticed that in this beta version user cannot download a mp3 file and listen it if someone sends you one.

**Comment by lfbrock** [comment]
Hi @kaksikanaa - we haven't added downloading files yet, we have a ticket here but it currently only covers images for iOS: https://mattermost.atlassian.net/browse/RN-80

Would you mind sharing a bit more about your use case? Do you send videos and sound files often on mobile? 

A couple questions: 
1. Do you have an example of other apps that allow you to upload and download MP3 files - Would it be uploading from iCloud? Where do the files download to? 
2. Can you open [a feature request](https://mattermost.uservoice.com/forums/306457-general) for adding the ability to voice record in the app?

**Comment by enahum** [comment]
This thread has been inactive for a while, please feel free to re-open if needed
