### ISSUE TITLE
NFE when uploading file on mattermost beta app

### ISSUE THREAD

**Issue by O5ten** [mattermost/mattermost-mobile#6482]
#### Summary
NFE when trying to upload a file, image or otherwise on OnePlus 9 nord pro

### Environment Information
  - Device Name: OnePlus 9 pro (LE2123)
  - OS Version: Android 12
  - Mattermost App Version: 2.0.0 (BETA)
  - Mattermost Server Version: 7.0.1

#### Steps to reproduce
Open a channel
Upload a file or an Image
Get exception thrown in face

#### Expected behavior
I expect my file to be uploaded

#### Observed behavior (that appears unintentional)
![Screenshot_2022-07-17-15-39-34-35_54b3de6ee54af4857dd823b6cb3a47b6](https://user-images.githubusercontent.com/3242379/179401687-67153748-a56b-44dd-a5d3-f24f6d896fad.jpg)

#### Possible fixes
Use the browser to access mattermost on either mobile or desktop.

**Comment by enahum** [comment]
@O5ten Thanks for reporting, we'll address the crash for sure.

**Comment by enahum** [comment]
Also, can you share the locale of your device?

**Comment by O5ten** [comment]
> Also, can you share the locale of your device?

The locale is swedish. Inget an error that it is missing a swell when i login, but it doesn't seem to affect anything.

**Comment by O5ten** [comment]
> Would you be able to reproduce and share the entire stack trace?

Happens every time for me. Here is the complete stack trace. Here i uploaded an image.
![Screenshot_2022-07-17-19-45-00-57_54b3de6ee54af4857dd823b6cb3a47b6](https://user-images.githubusercontent.com/3242379/179418211-8b25bf9a-b8bc-4b53-8c74-5a76d3674d86.jpg)

**Comment by enahum** [comment]
Thanks I'll check it out

**Comment by enahum** [comment]
@O5ten Can you confirm if you change your device language to english and see if the error persist?

Thanks

**Comment by O5ten** [comment]
> @O5ten Can you confirm if you change your device language to english and see if the error persist?
> 
> Thanks

Nope. The problem is gone then. As is the error message at the start. I did not think they were related. Attaching the startup error below. 

![Screenshot_2022-07-18-09-32-34-15_54b3de6ee54af4857dd823b6cb3a47b6](https://user-images.githubusercontent.com/3242379/179463953-69a5753f-c3d4-485e-a5d5-2f3df19fc7fb.jpg)
![Screenshot_2022-07-18-09-32-39-93_54b3de6ee54af4857dd823b6cb3a47b6](https://user-images.githubusercontent.com/3242379/179464012-da167054-1059-4f2f-83f6-429ee1e7d258.jpg)
![Screenshot_2022-07-18-09-32-45-87_54b3de6ee54af4857dd823b6cb3a47b6](https://user-images.githubusercontent.com/3242379/179464034-1e637a8f-495c-4a09-98fa-bc4f16e4c8b9.jpg)

**Comment by larkox** [comment]
Closing since the original issue seems fixed. The other issue mentioned should also be fixed in the latest version.
