### ISSUE TITLE
Mattermost beta does not appear in list of apps to share to

### ISSUE THREAD

**Issue by schmitts** [mattermost/mattermost-mobile#6495]
Hi!

Using the Mattermost beta, the Mattermost app on Android does not appear in the list of apps to share to using the Twitter client's share button. The current/old Mattermost app did and I used it regularly.

Thanks,

Sebastian

PS: confirmed by https://community.mattermost.com/core/pl/ty4saz5m13g93getf7fzqbaowo

**Comment by enahum** [comment]
Going to close this issue, you can keep track of the progress made here https://mattermost.atlassian.net/browse/MM-39945
