### ISSUE TITLE
Back to last channel in Mattermost beta

### ISSUE THREAD

**Issue by schmitts** [mattermost/mattermost-mobile#6496]
Hi!

Using the Mattermost beta on Android. After opening the list of channels I don't see a way to get back to the last channel I had open. This was possible in the current/old app by just swiping the channel list (checking for unread messages) and then swiping it again to get back to the channel I was following last. It would be good to have a "back to last channel" feature in the new app.

Thanks,

Sebastian

**Comment by avinashlng1080** [comment]
Thanks Sebastian for your feedback.

The beta app - aka v2 app - is a redesign and yes, the navigation flow is a bit different.

@esethna I'm assigning you to this issue.  IIRC, you were looking into this together with @matthewbirtch ?

**Comment by esethna** [comment]
100% agree @schmitts, we should be supporting swiping gestures to return to the last viewed channel. I will open a tix for this: https://mattermost.atlassian.net/browse/MM-45904

**Comment by esethna** [comment]
@schmitts how is the rest of your experience with the app. Please share any feedback you have in our development channel: https://community.mattermost.com/core/channels/ship-gekidou--mobile-v2
