### ISSUE TITLE
German locale module unknown in Mattermost beta on Android

### ISSUE THREAD

**Issue by schmitts** [mattermost/mattermost-mobile#6506]
Hi!

Starting Mattermost beta on Android, I get the following error (see attached screenshot):

`Requiring unknown module "./locale/de".`

I get the option to restart after which the application starts.

Thanks,

Sebastian

![Screenshot_20220721-153051](https://user-images.githubusercontent.com/1502412/180806409-d53eac3e-3b0f-4b71-b2f0-638567237120.png)

**Comment by enahum** [comment]
@schmitts What build are you on?

**Comment by schmitts** [comment]
> @schmitts What build are you on?

2.0.0

**Comment by enahum** [comment]
> > @schmitts What build are you on?
> 
> 
> 
> 2.0.0

That is the version, I'm talking about the build number.

You can see the build number in the about screen (account -> settings -> about) or at the bottom of the new server screen

**Comment by schmitts** [comment]
Sorry. When doing "account -> settings -> about" I get a different error:

`Text strings must be rendered within a <Text> component.` (see attached)

and I'm back to the account menu.
![Screenshot_20220725-172653](https://user-images.githubusercontent.com/1502412/180816289-c0ed1ccb-19cb-4ec4-882f-87d7b30a403e.png)

**Comment by enahum** [comment]
> Sorry. When doing "account -> settings -> about" I get a different error:
> 
> 
> 
> `Text strings must be rendered within a <Text> component.` (see attached)
> 
> 
> 
> and I'm back to the account menu.
> 
> ![Screenshot_20220725-172653](https://user-images.githubusercontent.com/1502412/180816289-c0ed1ccb-19cb-4ec4-882f-87d7b30a403e.png)
> 
> 

Ok cool we can deal with this one separately, in the meantime try getting the value from the server screen, "add" a new server, close the keyboard and look at the number on the lower left of the screen then cancel the addition of the server

**Comment by schmitts** [comment]
> Ok cool we can deal with this one separately, in the meantime try getting the value from the server screen, "add" a new server, close the keyboard and look at the number on the lower left of the screen then cancel the addition of the server

It's build 6000413.

**Comment by enahum** [comment]
@josephbaylon I'm unable to reproduce the problem with `de` locale, can you please give it a try ?

**Comment by josephbaylon** [comment]
@enahum I'm able to reproduce. It only affects Android.

**Comment by enahum** [comment]
> @enahum I'm able to reproduce. It only affects Android.

@josephbaylon did you try the PR with the "fix"

**Comment by josephbaylon** [comment]
@enahum Not yet, I'm still building it. I'll try in the next few minutes
