### ISSUE TITLE
Beta crash when opening Threads

### ISSUE THREAD

**Issue by francislavoie** [mattermost/mattermost-mobile#6590]
A fraction of a second after tapping on "Threads", I get this error popup. If I tap on relaunch, I get stuck with a blank screen and I need to kill the app and relaunch it. I'm not able to copy the stack trace, it's not selectable in the dialog.

I'm guessing what happened was my coworker deleted the root comment from a thread sometime last week when there was one reply to it. This could have left a dangling comment that the app doesn't know how to deal with. Probably only noticed it now because it was the weekend etc.

![Screenshot_20220822-093637.png](https://user-images.githubusercontent.com/2111701/185935185-6ebed30e-60a0-4984-845e-c5e7a2f3347d.png)

![Screenshot_20220822-094105.png](https://user-images.githubusercontent.com/2111701/185935302-c3b2aca0-6307-4453-ba61-0cfe3e1b56cc.png)

**Comment by amyblais** [comment]
This looks to be related to https://mattermost.atlassian.net/browse/MM-46098? cc @anurag6713

**Comment by francislavoie** [comment]
Yeah, that looks about right. There's probably more than one way to make a comment no longer reachable, and the issue happens in that case.

**Comment by anurag6713** [comment]
https://mattermost.atlassian.net/browse/MM-46098 is about not having access to the `channel` data. This issue seems to be about the `post`.

Is it continuously crashing every time you navigate to the threads screen?

**Comment by francislavoie** [comment]
Yes, I can't access the threads screen at all on mobile. Not a huge deal for me right now because I spend 95% of my time on my PC, just using the app to catch stray notifications.

**Comment by amyblais** [comment]
@anurag6713 Do we create a new ticket for this issue?

**Comment by anurag6713** [comment]
I have created a ticket already. 

https://mattermost.atlassian.net/browse/MM-46531

Fix will be in with this PR

https://github.com/mattermost/mattermost-mobile/pull/6592

**Comment by amyblais** [comment]
Closing as the PR is merged,

**Comment by francislavoie** [comment]
Yep, confirmed, I don't see the crash anymore :+1: I'm on build `6000421`
