### ISSUE TITLE
login: Phabricator support

### ISSUE THREAD

**Issue by okias** [mattermost/mattermost-mobile#6597]
#### Summary
Support login though Phabricator.

#### Possible fixes
MR will follow.

**Comment by mkraft** [comment]
@glunardi If you'd be willing to adapt your previous PR to the new mobile v2 codebase and help us with testing, I think we could work together to get this into the core code so that you don't have to maintain this change yourself ongoing. How does that sound?

**Comment by glunardi** [comment]
> @glunardi If you'd be willing to adapt your previous PR to the new mobile v2 codebase and help us with testing, I think we could work together to get this into the core code so that you don't have to maintain this change yourself ongoing. How does that sound?

Thanks for the reply @mkraft!  I will talk to @okias right away and see how we can get this done quickly.

**Comment by okias** [comment]
@mkraft Hello! I adapted the patch and currently using the apk built from CI.

**Comment by m1lt0n** [comment]
Hello @okias @glunardi 

First of all, I'd like to thank you for the time you've invested in adding support for Phabricator in the mobile app and adapting your PR for mobile v2.

After some further internal discussions and given that Phabricator is not maintained and that we don't have more requests for supporting it, unfortunately at this point, we will not move forward with merging the relevant PR and maintaining the functionality on our side.

Sorry for the inconvenience. In case something changes in the future, we will keep you in the loop.
