### ISSUE TITLE
Sign in with LDAP/AD

### ISSUE THREAD

**Issue by Speed03** [mattermost/mattermost-mobile#660]
With beta version, I can't sign in with my LDAP account.
The displayed form is used by standard authentication.

With production version, it works good

**Comment by enahum** [comment]
Hi @speed can you explain a little bit more please

**Comment by Speed03** [comment]
We use Gitlab SSO to authenticate us on mattermost.
With android beta app, we could'nt use this mechanism.

But, with the last update, it works.
