### ISSUE TITLE
Direct Messages not showing up then disappearing from history after tapping notification

### ISSUE THREAD

**Issue by cgonzales2679** [mattermost/mattermost-mobile#6655]
#### Summary
Message notification pops up, is tapped, then app does not load and needs to be restarted, leading to the message not showing up in the recent message history.

### Environment Information
  - Device Name: iPhone 14 Pro
  - OS Version: Latest (16.0.2)
  - Mattermost App Version: 1.55.1
  - Mattermost Server Version: 7.0.1

#### Steps to reproduce
- Send a message to a user who has the above environment.
- Have the user tap the notification to get to the message.

#### Expected behavior
The new message tab opens after the application loads, and the message shows up in recent message history.

#### Observed behavior (that appears unintentional)
The notification is tapped, the screen turns completely white, and the application does not load. Notification is cleared, but application needs to be restarted. Upon restart, the message does not show up in the recent history for the user.

#### Possible fixes
Exact cause unknown at this time. Notification and message number in Mattermost is cleared, so possibly after calling that method. Maybe something when loading the application display since it just stays white.

**Comment by amyblais** [comment]
@josephbaylon Are you able to reproduce this on the above environment? (I wasn't able to repro on V1 or V2 but I'm on an older device and OS version). cc @enahum

**Comment by cgonzales2679** [comment]
@amyblais Bumping this issue. Have you found any good leads for the issue, maybe a fix?

**Comment by amyblais** [comment]
@cgonzales2679 I haven't been able to reproduce this on my end. Some things you could try out:

1. Delete and re-install the app.
2. Upgrade your server version to the latest (v7.3.0).
3. Try out our new v2.0 Beta app to see if the issue persists there too - instructions are here on how to sign up as a tester: https://mattermost.com/blog/mobile-beta-program-v2/.

**Comment by cgonzales2679** [comment]
Looked into it, update to 7.3 fixed it, rolling out the update soon.
Will send another issue for further problems.
