### ISSUE TITLE
Emojis cropped when selecting a reaction

### ISSUE THREAD

**Issue by leitmori** [mattermost/mattermost-mobile#6680]
#### Summary
Emojis are cropped when selecting a reaction to a message.

### Environment Information
  - Device Name: iPad Air 4
  - OS Version: iPadOS 15.7
  - Mattermost App Version: 1.55.1
  - Mattermost Server Version: 7.2.0

#### Steps to reproduce
Select reaction to a message.

#### Expected behavior
Emojis are not cropped.

#### Observed behavior (that appears unintentional)
Emojis are cropped.
![IMG_0195](https://user-images.githubusercontent.com/29522608/195402103-a4324263-6236-4f80-8cdf-8b956c505dea.PNG)

**Comment by amyblais** [comment]
@josephbaylon Do you or someone on QA have iPad Air to test this?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-47526.

**Comment by amyblais** [comment]
This is fixed in Mattermost Mobile V2 Beta. Please see more details here on how to sign up as a beta tester: https://mattermost.com/blog/mobile-beta-program-v2/.
