### ISSUE TITLE
App on Ipad only in iPhone resolution

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/mattermost-mobile#670]
#### Summary
Only shows in iPhone resolution on iPad

#### Environment Information

- Device Name: 
iPad Air
- OS Version:
Latest iOS 10.3.2 
- Mattermost App Version:
1.0 (34) 

- Mattermost Server Version:
3.10.0

#### Steps to reproduce
Open App on Ipad Air and it will open in iPhone resolution (with the option to zoom in)

#### Expected behavior
Open in native iPad resolution. Maybe as of now that is expected behaviour but  I have not found any restrictions in the hardware requirements or such.

![img_0173](https://user-images.githubusercontent.com/8283684/27516292-a878c86c-59b7-11e7-8506-36382b548f07.PNG)

**Comment by lfbrock** [comment]
Thanks @Twilek-de! 

We haven't added support for tablets yet, we would like to in the future but the timeline will depend on how many people need support for this. 

Would you be able to help upvote this feature request so we can track demand more easily? 

https://mattermost.uservoice.com/forums/306457-general/suggestions/20082079-add-a-tablet-ipad-version-of-second-generation-m

**Comment by enahum** [comment]
This thread has been inactive for a while, please feel free to re-open if needed
