### ISSUE TITLE
Case sensitive URLs corrupted in posts

### ISSUE THREAD

**Issue by tsipizic** [mattermost/mattermost-mobile#671]
If a user posts a case sensitive URL 
http://imgur.com/a/AaAa
the app will try to open 
http://imgur.com/a/aaaa
corrupting the link.
The most possible cause for this problem is Line 22 in the following file
https://github.com/mattermost/mattermost-mobile/blob/master/app/components/markdown/markdown_link.js#L22

**Comment by hmhealey** [comment]
Thanks for the report, @tsipizic. Looks like [making the protocol lower case to make Android happy](https://mattermost.atlassian.net/browse/RN-143), backfired. I'll submit a fix for this shortly, so that it'll be in for our 1.0 release next week
