### ISSUE TITLE
resize image upload

### ISSUE THREAD

**Issue by yousefg** [mattermost/mattermost-mobile#6718]
#### Summary
 images should be compressed and resized before upload to server.

### Environment Information
  - Device Name: iPhone 13 Pro - Asus  Zenfone Max Plus
  - OS Version: 16.1 - Android 7
  - Mattermost App Version: 1.55.1
  - Mattermost Server Version: 7.0.1

#### Expected behavior
the image should be resized on the client BEFORE uploading automatically (eg. like whatsapp)

**Comment by esethna** [comment]
Hi @yousefg, thanks for the feedback. Can you help me understand why this is desirable? 

To shed some context here, we previously used to compress images but received negative feedback about the reduced image quality. We've since uploaded images at full size to maintain high quality when accessed via the computer or shared outside mattermost.

**Comment by esethna** [comment]
Got it, can you help a feature request on our idea forum so we can track it there? Agree it should be optional. 
https://mattermost.uservoice.com/forums/306457-general

**Comment by yousefg** [comment]
there is a request submitted on 2017!

https://mattermost.uservoice.com/forums/306457-general/suggestions/18343426-resize-image-upload

**Comment by esethna** [comment]
Thanks @yousefg, are you open to contributing an improvement like this? I am envisioning a system console setting where the admin can decide the default behaviour for the server (ie compressed or uncompressed)

**Comment by yousefg** [comment]
Yes I’ll do my best, but I think client side compressing has better performance than server side. user can choose quality of images for upload(like Microsoft Teams). although admin already can limit Maximum File Size.

**Comment by esethna** [comment]
@yousefg can you share the settings or options you're referring to in Teams?

**Comment by esethna** [comment]
@Rishselva looping you in here as it relates to the investigation you were doing on max image dimensions and max file size defaults. I wonder if there's a solution here that solves both these use cases? I'll leave this in your hands to take over.

**Comment by yousefg** [comment]
Thanks @esethna for your consideration.

**Microsoft Teams Image upload quality screenshot:**
![ab7f102378944d368220bfe37250e150](https://user-images.githubusercontent.com/21288086/199825772-258b5e7f-b1e3-4e55-8d45-ae8dc5e67584.jpg)

**Comment by larkox** [comment]
@esethna There was any decision on this?

**Comment by esethna** [comment]
Certainly open to a contribution that implements this behaviour: https://github.com/mattermost/mattermost-mobile/issues/6718#issuecomment-1302565779

Otherwise, let's close this to track in the uservoice request.
