### ISSUE TITLE
channels in search should be sorted by activity

### ISSUE THREAD

**Issue by tmotyl** [mattermost/mattermost-mobile#6749]
#### Summary
Search box for channels and private messages should show them using last activity order (like it is on desktop and web)
Right now alphabetical order is shown.
This is especially painful when you have old conversations with person with name starting with "A". I have several inactive users starting with A, so conversations with them are shown on the top of the list. Which makes me scroll a lot :)

### Environment Information
  - Device Name: Iphone 13
  - OS Version: IOS 15.7
  - Mattermost App Version: 1.55.1
  - Mattermost Server Version: 7.2

#### Steps to reproduce
1. open mobile app on ios
2. tap on the "Find channel" input field
 

#### Expected behavior
Direct messages and channels are shown in "last activity" order.

#### Observed behavior (that appears unintentional)
Direct messages are shown in alphabetical order.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by esethna** [comment]
Hi @tmotyl, I'd encourage you to opt-in to our beta program to try the Mobile app v2.0 where we've resolved this:  https://mattermost.com/blog/mobile-beta-program-v2/

**Comment by tmotyl** [comment]
Thanks @esethna! the beta app works fine. No issues so far (ios)
