### ISSUE TITLE
OpenID not supported on Android

### ISSUE THREAD

**Issue by ados8** [mattermost/mattermost-mobile#6794]
#### Summary
Appears according to documentation that only web interfaces support OpenID.
Using mobile platform, in this case Android, there is no option to see/use the OpenID provider; option is plain missing.
Using the community Team Edition.

#### Steps to reproduce
Configure OpenID, visually see it in the web and able to login.
Open the mobile app and sign in page has no option other than username/email login.
Once OpenID is configured you can no longer use username/email to authenticate.
This renders OpenID useless if you want to use the mobile app.
Signing in on the mobile app first and then link your account to OpenID subsequently signs you out on mobile.

#### Expected behavior
Implement support for OpenID for Android or at least allow multiple sign-ins such as OpenID and username/email login.

#### Observed behavior (that appears unintentional) 
N/A

#### Possible fixes
N/A

**Comment by amyblais** [comment]
Our upcoming Mobile V2 release will support OpenID in Team Edition: https://github.com/mattermost/mattermost-mobile/pull/6755. The release is currently scheduled for December 15th.

**Comment by ados8** [comment]
> Our upcoming Mobile V2 release will support OpenID in Team Edition: #6755. The release is currently scheduled for December 15th.

Thats excellent, thank you for the swift response.
Look forward to the feature.

**Comment by ados8** [comment]
I have been looking out for the new feature but instead noticed its now completely removed from the Teams Edition.
Thought I was going nuts and then review the guide: https://docs.mattermost.com/onboard/sso-openidconnect.html
Its gone from authentication, has this now been removed?

**Comment by ados8** [comment]
I have been looking out for the new feature but instead noticed its now completely removed from the Teams Edition.
Thought I was going nuts and then review the guide: https://docs.mattermost.com/onboard/sso-openidconnect.html
Its gone from authentication, has this now been removed?

**Comment by amyblais** [comment]
This is scheduled to be added for Team Edition for v7.7 and Mobile v2 releases (January 16th releases).

**Comment by ados8** [comment]
New ETA on this? 😊

**Comment by plant99** [comment]
Hey @ados8 , OpenID support isn't available in Team edition as of today. Apologies for any confusion the docs caused!

**Comment by amyblais** [comment]
@ados8 Feel free to share this feature request on our feature request forum here https://mattermost.com/suggestions/.

**Comment by ados8** [comment]
How is it suddenly not supported when it was mentioned above it was about to release??

**Comment by amyblais** [comment]
I don't know the full context, but there was an initial plan to add this to the Free version, but it was later reverted.
