### ISSUE TITLE
Ping server after server url is selected

### ISSUE THREAD

**Issue by thomchop** [mattermost/mattermost-mobile#68]
We have implemented an action to do this, but we've commented out where it's being called in `SelectServer`. I presume that we still want to do so.

**Comment by enahum** [comment]
I think instead of ping we should use `/general/client_props` as we can use that to set the client config while testing that the server responds.

We could potentially add in the response the values to identify if the app is valid or if it should upgrade before continue.

**Comment by enahum** [comment]
this is is done
