### ISSUE TITLE
on iOS cannot reply via notification or share while the app is closed

### ISSUE THREAD

**Issue by recsdj** [mattermost/mattermost-mobile#6802]
#### Summary
Two long-standing bugs on iOS. They manifest whenever MM app is closed, regardless of login status. If the app is running in background, everything works as expeced. No other chatting app exhibits such behaviour, *even WeChat works properly* in both scenarios.

- Replying via force-touch on a notification fails with "Message failed to send" 
- Sharing a file fails with "Authentication required. Please first login using the app" 

### Environment Information
  - iPhone X, but any really
  - iOS 16, but this bug has been round forever
  - Latest, but it never worked
  - Server 7.2.0, but same was with 5.x and 6.x

#### Steps to reproduce
- Close MM app (don't leave it running in background), 
- receive a notification and use force-touch to reply, OR
- try sharing a photo/file using iOS standard share menu.

#### Expected behavior
no errors, just works. 

#### Observed behavior (that appears unintentional)
see screenshots and videos attached

![IMG_3527](https://user-images.githubusercontent.com/85218635/204795390-63ca2815-3ab0-4212-b4da-5084e8c608c1.jpg)

https://user-images.githubusercontent.com/85218635/204795752-a642e3a3-3447-44d9-9014-39bdcdf4ec7d.mp4

![IMG_3525](https://user-images.githubusercontent.com/85218635/204795489-7456285d-856f-477e-b675-d96560cea58d.PNG)

https://user-images.githubusercontent.com/85218635/204795417-21148f83-0115-484c-90b2-9aad58b2d5d3.MP4

#### Possible fixes
Tried re-logging in, did not help. Updating / reinstalling did not help either.  These bugs been around for years, just recently I managed to understand that background app status is important to reproduce the bug.

**Comment by amyblais** [comment]
@recsdj Would you be open to testing if you also see these bugs in our upcoming V2 app? You can get access to the beta version via the instructions here https://mattermost.com/blog/mobile-beta-program-v2/.

**Comment by larkox** [comment]
@recsdj Were you able to check if this is still a problem?

**Comment by recsdj** [comment]
Hello, thanks for following up. Mattermost Beta seems to be fine, I have
been testing it since your offer and haven’t encountered the bug. Thanks
heaps!
