### ISSUE TITLE
Can't run android app on Macbook M1

### ISSUE THREAD

**Issue by rain9x** [mattermost/mattermost-mobile#6891]
#### Summary
Can't run android app

### Environment Information
  - Device Name: Macbook M1
  - OS Version: MacOS monterey
  - Mattermost App Version: v2
  - Mattermost Server Version:

#### Steps to reproduce
Step1: npx react-native run-android
=>> Build fieled with message **Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.**

#### Expected behavior
Pls help to run android app or any document to setup and can run android app. Thanks

**Comment by enahum** [comment]
@rain9x Please help attaching the segment of the log where it says what went wrong

**Comment by rain9x** [comment]
> @rain9x Please help attaching the segment of the log where it says what went wrong

Thanks @enahum. I'm update some packages version and solved problem.
