### ISSUE TITLE
Can't build android app base on version 1.55.1 released

### ISSUE THREAD

**Issue by rain9x** [mattermost/mattermost-mobile#6908]
#### Summary
Hi everyone, I'm downloading source code from **Mobile Version 1.55.1** released, but I'm can't build android app. Can anyone help me? Thank for all

### Environment Information
  - Device Name: Macbook pro M1
  - OS Version: Macos Monterey
  - Mattermost App Version: 1.55.1

#### Steps to reproduce
**Step 1:** Dowload source code from Mobile Version 1.55.1 released
**Step 2:** run: npm install
**Step 3:** run: react-native run-android

#### Expected behavior
Can run android app on simulator

#### Observed behavior (that appears unintentional)
```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.appcompat:appcompat:1.4.1.
     AAR metadata file: /Users/hungnguyen/.gradle/caches/transforms-3/f6cf9637d2f604e9f80955c01bd68647/transformed/appcompat-1.4.1/META-INF/com/android/build/gradle/aar-metadata.properties.
```

If manual fix with remove minCompileSdk = 31 from **aar-metadata.properties** after that re-run `react-native run-android` command and another file will encounter the same problem.

**Comment by larkox** [comment]
@rain9x Is there any reason why you cannot compile with the SDK31?

**Comment by amyblais** [comment]
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),
