### ISSUE TITLE
Channel loading issue with iOS 10.3.2

### ISSUE THREAD

**Issue by indrekpihor** [mattermost/mattermost-mobile#691]
#### Summary
While using mattermost iOS app, in landscape mode, it lags a lot and when changing a channel, it keeps loading for long time. This does not happen if tablet is used in portrait. 

#### Environment Information

- Device Name: iPad
- OS Version: 10.3.2
- Mattermost App Version: latest, 3.5
- Mattermost Server Version: server version 3.10

#### Steps to reproduce
Turn tablet into portrait mode and try changing channels or open direct chats with persons you have in your list.

#### Expected behavior
Should work fast as on portrait, load right away and show contents. 

#### Observed behavior
Constant loading... on screen

**Comment by lfbrock** [comment]
Hi @indrekpihor - is this the new Beta mobile app, or the one available on the Appstore? 

(If you're not sure, would you be able to provide a screenshot of the app?)

**Comment by indrekpihor** [comment]
It's the one in app-store. But works on IPad Pro - just tested it. But i guess there is an performance issue on regular iPad.

**Comment by enahum** [comment]
Closing as this is related to the classic app
