### ISSUE TITLE
Release 2.0.0 Not Tagged and Not Published on GitHub

### ISSUE THREAD

**Issue by francisco-core** [mattermost/mattermost-mobile#6918]
#### Summary
Release v2.0.0 is available in the [Play Store](https://play.google.com/store/apps/details?id=com.mattermost.rn&hl=fi&gl=US), but that release is missing from [Github releases](https://github.com/mattermost/mattermost-mobile/releases).

#### Steps to reproduce

Open [Github releases page for the project](https://github.com/mattermost/mattermost-mobile/releases).

#### Expected behavior
The current latest release on Github is 2.0.0 along with a `2.0.0` tag.

#### Observed behavior (that appears unintentional)
The current latest release on Github is 1.55.1 and there there are no newer git tags.

#### Possible fixes
The solution can doing a release on GitHub for `2.0.0` and adding this step to your internal release procedures to make sure it [doesn't happen again](https://github.com/mattermost/mattermost-mobile/issues/5792).

**Comment by enahum** [comment]
@francisco-core V2 has not been released yet. If you see it in the play store is cause you subscribed as a beta tester.

**Comment by francisco-core** [comment]
Ah, I see. Sorry for the confusion. I guess I saw the release date on dec. 15th in some mattermost communication material somewhere and that lead me to conclude it was already released. But you're right, on the play store I was checking for the beta version.

Good luck on the release!
