### ISSUE TITLE
How to set the current language?

### ISSUE THREAD

**Issue by 1622145167** [mattermost/mattermost-mobile#6941]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
I want to change the current display language, instead of English.

### Environment Information
  - Device Name: iOS and Android
  - OS Version:
  - Mattermost App Version:
  - Mattermost Server Version:7.5.2

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Software display in other language, such as Japanese, French or Chinese, instead of in English. Because my users are not native speakers of English.

#### Observed behavior (that appears unintentional)
It displays in English, though my system displays in other language.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by 1622145167** [comment]
But when I launch the program without adding any server, how to solve it?

**Comment by 1622145167** [comment]
> @1622145167 You can do this via webapp or desktop app through this setting https://docs.mattermost.com/channels/channels-settings.html#language.

But when I launch the app without adding any server, how to solve it?

**Comment by larkox** [comment]
@1622145167 For the select server screen, it should recognize your phone configuration. What language do you have in your phone? (to double check if the translations are in place and we can debug it)

**Comment by 1622145167** [comment]
> 

Chinese.

**Comment by 1622145167** [comment]
> @1622145167 For the select server screen, it should recognize your phone configuration. What language do you have in your phone? (to double check if the translations are in place and we can debug it)

Chinese.

**Comment by larkox** [comment]
It seems that we still haven't catch up with the Chinese translation. Other translations like German, Spanish or Japanese seem to have the needed strings already translated so you can see the result changing your phone language to any of those, but since we don't have those strings yet for Chinese, it defaults back to English.

If you are interested in the localization process and want to contribute in any language, you can take a look at this link: https://handbook.mattermost.com/contributors/join-us/localization

**Comment by larkox** [comment]
Closing as a non-issue. If you have more comments about this, or any other request, feel free to reopen.
