### ISSUE TITLE
Mattermost crashing after opening 

### ISSUE THREAD

**Issue by deepblue597** [mattermost/mattermost-mobile#6942]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Bug report in one concise sentence
Mattermost will crash after I try to open it 

### Environment Information
  - Device Name: Xiaomi mi 10 
  - OS Version:
  - Mattermost App Version: x
  - Mattermost Server Version:

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
1. Press the app
2. app tries to open 
3. crashes 

#### Expected behavior
Describe your issue in detail
should open 

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages, screenshots and/or video recordings.
![324494548_465278578948354_7781433200449181354_n](https://user-images.githubusercontent.com/61558523/211378109-367db627-e6ed-4bdc-b7ab-09c2bd47aa82.jpg)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@deepblue597 What Mattermost server version are you on? What Mattermost mobile app version are you on? Do you see the same issue after re-installing the app?
