### ISSUE TITLE
New message not showing in DM's 

### ISSUE THREAD

**Issue by mariaInvozone** [mattermost/mattermost-mobile#6976]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Bug report in one concise sentence

### Environment Information
  - Device Name: Pixel 3
  - OS Version:
  - Mattermost App Version: 2.0.0
  - Mattermost Server Version: 

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
-Click on plus and 'Open a Direct Message'
-Select multiple people from list (Note:New Created group should not already exists)
-After Start Conversation , send a message
-It will not appear on DMs until we refreshes the app. 

#### Expected behavior
-Click on plus and 'Open a Direct Message'
-Select multiple people from list (Note:New Created group should not already exists)
-After Start Conversation , send a message
-It should be in DMs without refreshing. 

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages, screenshots and/or video recordings.

https://user-images.githubusercontent.com/111849328/212635161-1feb84be-7576-4ed2-89e6-221a4a195b93.mp4

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@josephbaylon Are you able to reproduce this on Android?

**Comment by jgilliam17** [comment]
@amyblais I can reproduce on v2, build 452
Ticket link: https://mattermost.atlassian.net/browse/MM-49693

**Comment by mariaInvozone** [comment]
hi @amyblais  @jgilliam17 .Its still Unassigned. Can you please check.

**Comment by jgilliam17** [comment]
Thanks for the ping @mariaInvozone I'll take a look today and update the ticket.

**Comment by alzee** [comment]
I have the same issue.
For me, when I toggle the unread button next to `Find channels` , new DM shows in `UNREADS`. Open it and back, toggle off, new DM now shows in DMs.
