### ISSUE TITLE
Chat text not displaying in mattermost beta app

### ISSUE THREAD

**Issue by feinom** [mattermost/mattermost-mobile#698]
#### Summary
Chat text is not displaying in any channels.

#### Environment Information
We are using gitlab authentication.

- Device Name: Huawei P10 (also a problem on Huawei P9)
- OS Version: EMUI v 5.1 / Android v 7.0
- Mattermost App Version: 1.0 (Build 34)
- Mattermost Server Version: 3.10.0

#### Steps to reproduce
Log in and try to view text.

#### Expected behavior
Chat text should be visible.

#### Observed behavior
All channels appear empty. See screenshot for example.

![image](https://user-images.githubusercontent.com/439885/27760029-6e63cf2e-5e3e-11e7-81eb-01c9c2caddfd.png)

#### Possible fixes
n/a

**Comment by brumle80** [comment]
Build 39 still has the same issue.

**Comment by cfko** [comment]
Just to bump; experiencing this with my Huawei Honor 8.

**Comment by enahum** [comment]
Same as #733
