### ISSUE TITLE
Icons not rendered correctly on Mattermost-App (MobilePhone)

### ISSUE THREAD

**Issue by DVTrast** [mattermost/mattermost-mobile#6981]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

### Environment Information
  - Device Name: Nokia 6.1  & iPhone6
  - OS Version: Android 10 & iOS 12.5.6
  - Mattermost App Version: 1.55.1 (Build 3000423) & 1.55.1 (Build 423)
  - Mattermost Server Version: 7.2.0

#### Steps to reproduce
Create a message with Icon´s

#### Expected behavior
The Icon´s should rendered/displayed (correctly) in the App

#### Observed behavior (that appears unintentional)
The Icon´s aren`t displayed in the app

**View on PC:**
![Mattermost-PC](https://user-images.githubusercontent.com/61227869/212825456-17e23b07-5761-456b-9025-a72c53633da4.png)

**View on MobilePhone:**
![Mattermost-Mobile](https://user-images.githubusercontent.com/61227869/212825452-2d6c7745-2063-44fa-bb5d-d94096b47995.png)

**Comment by DVTrast** [comment]
@amyblais  I´ll try it with v2.0 and will give you a feedback.

**Comment by DVTrast** [comment]
@amyblais the problem still exist in v2.0

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-49917.

**Comment by amyblais** [comment]
Closing as there is a Help Wanted issue open for this,
