### ISSUE TITLE
App crashes on pdf upload. 

### ISSUE THREAD

**Issue by mariaInvozone** [mattermost/mattermost-mobile#6982]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Bug report in one concise sentence

### Environment Information
  - Device Name: Pixel 3
  - OS Version: 
  - Mattermost App Version:2.0.0
  - Mattermost Server Version:

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
-Open any dm or channel
-Click on attachment icon (Works fine on Pictures but crashes on pdf)
-Select any PDf from mobile.
-App will crash

#### Expected behavior
How can we reproduce the issue (what version are you using?)
-Open any dm or channel
-Click on attachment icon (Works fine on Pictures but crashes on pdf)
-Select any PDf from mobile.
-It should attach the selected file

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages, screenshots and/or video recordings.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

https://user-images.githubusercontent.com/111849328/212833298-3608ef6b-1d0d-4881-bdcd-88c74f3f0917.mp4

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-49707
