### ISSUE TITLE
Messages sent in bold are displayed as regular font-weight

### ISSUE THREAD

**Issue by luc-ass** [mattermost/mattermost-mobile#6983]
#### Summary
Messages sent in **bold** do not display as such on Mattermost Mobile v2 (iOS, v2.0.0)

### Environment Information
  - Device Name: iPhone 14 Pro
  - OS Version: iOS 16.2
  - Mattermost App Version: 2.0.0
  - Mattermost Server Version: 7.7

#### Steps to reproduce
1. Send message as bold, for example `__bold__`
2. Message displays as regular on Mattermost Mobile v2, but bold on web and desktop client

#### Expected behavior
Text formatting should look the same across all platforms

#### Observed behavior (that appears unintentional)
Expected:
![Bildschirm­foto 2023-01-18 um 09 31 59](https://user-images.githubusercontent.com/3263257/213123122-d2711243-1136-4515-bd91-25e6e69c48b0.jpg)
Actual behaviour:
![IMG_7CB0CE14B8EB-1](https://user-images.githubusercontent.com/3263257/213123221-40c25396-5319-4386-a8f3-08c5ec3a917f.jpeg)

#### Possible fixes
none found as of now

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-49734.
