### ISSUE TITLE
Android app 2.0.0 crashes when opening channel with non-existing user.

### ISSUE THREAD

**Issue by mmslkr** [mattermost/mattermost-mobile#6989]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Android app 2.0.0 crashes when opening channel with non-existing user.

### Environment Information
  - Device Name: OnePlus 6
  - OS Version: OxygenOS 11.1.2.2 (Android 11)
  - Mattermost App Version: 2.0.0
  - Mattermost Server Version: 7.1.5 EE

#### Steps to reproduce
Open a channel that contains a user that somehow does not exist anymore.
I do not know exactly how the login is configured on the server, or how users are offboarded. I know that it uses LDAP to authenticate against an active directory.

#### Expected behavior
The channel can be opened as usual.

#### Observed behavior (that appears unintentional)
App crashes with error "Record User#.... not found" as seen in the screenshot. 
![Screenshot_20230118-171145](https://user-images.githubusercontent.com/57526005/213234141-d7c1165b-3bd6-4c29-89d7-7486213d922b.jpg)

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-49741.

**Comment by mmslkr** [comment]
Additional information: clearing cache and restarting the app seems to have resolved the issue.
