### ISSUE TITLE
BLOCKED BY MATTERMOST jailbroken devices are not trusted by mattermost please exit the app

### ISSUE THREAD

**Issue by dvalencia11** [mattermost/mattermost-mobile#7008]
BLOCKED BY MATTERMOST jailbroken devices are not trusted by mattermost please exit the app

**Comment by enahum** [comment]
@dvalencia11 a few questions:

Device model and OS version?

Is your device enrolled in an EMM/MDM?

Is your device rooted?

Are you mocking your location?

**Comment by dvalencia11** [comment]
Android 13 Samsung ultra 22. Yes it's enrolled in an EMM/MDM. No my device is not rooted. I believe this happened with the latest version of mattermost. No I am not mocking the location. Also this happened to other pixel devices in my company as well.

**Comment by enahum** [comment]
This PR just got merged #7005 which we hope solves the problem and will be released with 2.1 on Feb 16.

With that said, in the meantime you could disable the check for jailbreak in your EMM managed configuration by changing the setting for `jailbreakProtection` to `"false"` as a temporary work around.

Also it would be incredible if you can help us validate the fix in the PR by adding the beta app that we will publish this upcoming Friday, Jan 27 in your EMM/MDM and check if the jailbreak protection doesn't throw false positives.

Thank you for the report and your help.

**Comment by dvalencia11** [comment]
Ok il go on the MDM cloud and change the configurations. We are using Ivanti MDM cloud. Il let you know if thst fixes the issue. Appreciate the help

**Comment by dvalencia11** [comment]
Hey it worked all android devices are able to connect now after I set it to False. Thank you soo much
