### ISSUE TITLE
"Already connected" when adding server

### ISSUE THREAD

**Issue by pstray** [mattermost/mattermost-mobile#7013]
#### Summary
Adding the second of two servers uder same domain results in "You are already connected to this server".

### Environment Information
  - Device Name: iphone
  - OS Version: 16.2
  - Mattermost App Version: 2.0.0 (452)
  - Mattermost Server Version: 7.7.1

#### Steps to reproduce
After adding one of my job servers, adding the second one results in "You are already connected to this server". They ar definitely two separate servers. 

#### Expected behavior
Be able to add the second server. 

#### Observed behavior (that appears unintentional)
Unable to add server, resulting in previously stated error.

**Comment by amyblais** [comment]
Do those separate servers share the same diagnostic ID?

**Comment by amyblais** [comment]
@pstray Do those separate servers share the same diagnostic ID?

**Comment by pstray** [comment]
Separate installs, so I would assume no, but if you tell me where to look i can check

**Comment by amyblais** [comment]
The ``diagnosticId`` lives in the Systems table on the server database and each server must have a unique identifier. (Please don't share the IDs here as it's sensitive data).

**Comment by pstray** [comment]
Ok, will check when I get to my laptop.

**Comment by pstray** [comment]
yep, they were the same... just replace one with a similar value?

**Comment by amyblais** [comment]
Yes, that works.

**Comment by pstray** [comment]
Updating the id, restarting the service, and logging out and in again did the trick.

**Comment by pstray** [comment]
We probably cloned one of the servers from the first... I'll keep that in mind if we try to do that again :)
