### ISSUE TITLE
Notifications showing internal channel id

### ISSUE THREAD

**Issue by pstray** [mattermost/mattermost-mobile#7014]
#### Summary
Notifications are showing the internal channel id, not the channel name. 

### Environment Information
  - Device Name: iphone
  - OS Version: 16.2
  - Mattermost App Version: 2.0.0 (452)
  - Mattermost Server Version: 7.7.1

#### Steps to reproduce
Wait for a notification om the phone

#### Expected behavior
Notification showing channel name or conversation participants. 

#### Observed behavior (that appears unintentional)
Notification displays internal id of channel/conversation.

**Comment by amyblais** [comment]
What is your setting set to for System Console > Notifications > Push Notification Contents?

**Comment by pstray** [comment]
It is currently " General description with only sender name".

**Comment by pstray** [comment]
Changing it to the second choice fixed the channel names, so closing this issue...
