### ISSUE TITLE
inactive member appear in the app

### ISSUE THREAD

**Issue by fredao** [mattermost/mattermost-mobile#7019]
### Environment Information
  - Device Name: Samsung A52s
  - OS Version: 13
  - Mattermost : 2.0.0 13.01.2023
  - Mattermost Server Version: 7-4-0
  
Inactive members appear and cannot be deleted

![grafik](https://user-images.githubusercontent.com/1868849/214608592-a51aac82-e3fa-4143-85a1-2412380418e6.png)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-49966.

**Comment by amyblais** [comment]
This is fixed in a recent release,
