### ISSUE TITLE
Calling Town Square breaks down with an error message

### ISSUE THREAD

**Issue by fredao** [mattermost/mattermost-mobile#7020]
Environment Information
    Device Name: Samsung A52s
    OS Version: 13
    Mattermost : 2.0.0 13.01.2023
    Mattermost Server Version: 7-4-0

Unfortunately, I can't send the complete report via the app because it doesn't work. See next issue. 

![grafik](https://user-images.githubusercontent.com/1868849/214610711-aac6db54-8972-4c1a-a320-b275d97183d9.png)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-49967.
