### ISSUE TITLE
Android app version 2.0.0: online status not displayed correctly

### ISSUE THREAD

**Issue by FM4E** [mattermost/mattermost-mobile#7022]
Hello,

since the Android app version 2.0.0, the online status of the members is not displayed correctly. For example, user X is shown as online according to the Android app, but user X is not online according to the Windows app. Everything worked correctly before the design change, now it doesn’t.

I emptied the app cache, I also deleted the complete app data, set up the app again and logged in again. Unfortunately, that didn't change anything.

Hope you can investigate this internally and fix this issue.

Server Version: 7.7.0
App Version: 2.0.0 (Build 6000452)
App Platform: android (Samsung Galaxy S21 Ultra 5G, Android 13)

**Comment by afle** [comment]
Same for me. 

App version: 2.0.0
Server: 7.1.5
Android 13

**Comment by leitmori** [comment]
Same with iOS (App 2.0.0, Server 7.7.0)

**Comment by ChristianCiach** [comment]
Same issue on Android 13:

```
App Version: 2.2.0 (Build 6000462) 
Server Version: 7.7.1
```

No issues with the android app version 1.55.1.
