### ISSUE TITLE
Text is not selectable on About Mattermost page

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-mobile#7031]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
The About page contains information that need to be copied in order to give context when creating bug issues, but the text is not selectable.

### Environment Information
  - Device Name:
  - OS Version: Android 12 
  - Mattermost App Version: 2.0.0
  - Mattermost Server Version: 7.5.2

#### Steps to reproduce
Go to the About Mattermost page, try to select text

#### Expected behavior
I can select and copy-paste the version info

#### Observed behavior (that appears unintentional)
I cant select the text and thus cant copy-paste

**Comment by enahum** [comment]
Thanks for reporting this, it was never the intention to make it selectable but contributions are always welcome. Do you want to submit a PR for this?

**Comment by moussetc** [comment]
No, sorry.
(The long answer is that, not being an Android developer, I do not have a environment setup for Android development and, after looking at the setup instructions for Linux, I do not have the motivation to actually install all of the many required stuff before even getting to work on the issue).

Thank you for the fast answer.

**Comment by Willyfrog** [comment]
Created a ticket for it: https://mattermost.atlassian.net/browse/MM-50053

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this !?

**Comment by Willyfrog** [comment]
of course, I just assigned it to you! Thanks!

**Comment by Sudhanva-Nadiger** [comment]
@Willyfrog how about providing a small copy to the clipboard button in the about section so all of 4 info get copied once? Thanks.

**Comment by Willyfrog** [comment]
Sounds right! that was my proposal in the linked ticket :)

**Comment by Sudhanva-Nadiger** [comment]
@Willyfrog Do I need to write test for this ?

**Comment by Willyfrog** [comment]
if possible, that would be awesome

**Comment by amyblais** [comment]
This is scheduled for v2.7 release (August 16th),
