### ISSUE TITLE
Android App: blank screen for every login related page

### ISSUE THREAD

**Issue by FPtje** [mattermost/mattermost-mobile#7053]
#### Summary
After updating to the latest version of the android app I had to log in again. After the "select server" screen, I see a blank page with just the mattermost background.

### Environment Information
  - Device Name: OnePlus 7T Pro
  - OS Version: Android 11, Oxygen OS 11.0.9.1.HD01BA
  - Mattermost App Version: 2.0.0
  - Mattermost Server Version: 7.1.5

#### Steps to reproduce

- Clear app storage
- Start App
- On Welcome screen, press "Sign in"
- On the "Let's connect to a server" screen, enter a valid server
- Press Connect
- Oberve the following:
 ![mattermost_bug](https://user-images.githubusercontent.com/1202014/215338318-c05092c9-afab-43c1-9d27-a5a45a143aa8.jpg)
  Above screen shows indefinitely. I waited for several minutes to see if this would change.
- Press Home
- Re-open app
- See "enter email/password" screen
- Enter email/password
- AGAIN see the blank page
- Press home
- Re-open app
- See MFA Token screen (if enabled of course)
- Enter MFA token 
- Press Continue
- Be logged in

#### Expected behavior

I never would expect to see empty screens.

#### Observed behavior (that appears unintentional)

See above

#### Possible fixes

A most likely cause here is that I have disabled animations in the developer settings of my phone. When I enable these, the login sequence works as expected.

Reproducing _should_ be easy after setting Developer options -> under drawing -> these three settings:

![mattermost bug 2](https://user-images.githubusercontent.com/1202014/215338763-bac14851-5048-4260-8dd0-d5221043e627.jpg)

**Comment by larkox** [comment]
Should be fixed by #7055

**Comment by Pyroluk** [comment]
This problem exists again with Server Version: 11.6.1 + Android App 2.39.0 ! :( !
