### ISSUE TITLE
zh-TW translation will cause the software to crash

### ISSUE THREAD

**Issue by 337077418** [mattermost/mattermost-mobile#7063]
The translation of Samsung mobile phone is not consistent with the native language. My character is traditional and the software recognition is "en". The code change locale=zh-TW translation will cause the software to crash.
 
and Through const deviceLocale=getLocales() [0]. languageTag; The correct native language is obtained
 const locale = getLocaleFromLanguage(lang);  Is wrong, always "en"

ERROR  ：
Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`., js engine: hermes
 ERROR  [Error: [@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "en" in Intl.NumberFormat. Using default locale: "en" as fallback. See https://formatjs.io/docs/react-intl#runtime-requirements for more details
]
 ERROR  [Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting default message for: "mobile.session_expired", rendering default message verbatim
MessageID: mobile.session_expired
Default Message: Please log in to continue receiving notifications. Sessions for {siteName} are configured to expire every {daysCount, number} {daysCount, plural, one {day} other {days}}.
Description: undefined

  
OS Version: Android 12
Mattermost App Version: versionCode 454
  versionName "2.0.0"
Mattermost Server Version: 7.5.2

**Comment by 337077418** [comment]
I can provide a new language translation for mattermost and improve a translation. What should I do

**Comment by 337077418** [comment]
I can provide a new language translation for mattermost and improve another translation. What should I do

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-50163.

**Comment by amyblais** [comment]
The ticket was closed as this issue only exists during development since the translation is missing. Production does not show the alert or the crash.
