### ISSUE TITLE
No Push Notifications since v2 (Android)

### ISSUE THREAD

**Issue by Luensche** [mattermost/mattermost-mobile#7077]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
No more push notifications since update

### Environment Information
  - Server Version: 7.5.1 (Build 7.5.1)
  - App Version: 2.0.0 (Build 6000454)
 - App Platform: android
 - Device Model: kona

#### Steps to reproduce
Receive a direkt message

#### Expected behavior
Get a push notification

#### Observed behavior (that appears unintentional)
I don't get push notifications any more. I looked in the settings and everything looks okay. But if I look in the app settings I see the following:
![IMG_20230202_113739](https://user-images.githubusercontent.com/17471658/216302271-b2d287e0-bcab-4a18-8935-845387ad4df0.jpg)
![Screenshot_2023-02-02-11-36-45-93_8142442b4340f41fb3bd44535ad8f76b](https://user-images.githubusercontent.com/17471658/216302295-23cc0b6c-2b18-4d5f-9b68-630f89d63602.jpg)
The log from "Fehler melden" shows nothing special.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by trbolexis** [comment]
I have this same issue.

The one thing I see with all other App that notify is the "Notification" setting under the Allowed heading when looking at App Permissions.

The Mattermost Beta App says "No Permissions Denied", however, there is no "Notification" setting listed under Allowed

**Comment by esethna** [comment]
> I have this same issue.

> The one thing I see with all other App that notify is the "Notification" setting under the Allowed heading when looking at App Permissions.

> The Mattermost Beta App says "No Permissions Denied", however, there is no "Notification" setting listed under Allowed

Hmm, interesting, thanks for this info. Do we know why our app might be treated differently in respect to notification permissions @enahum or @larkox?

**Comment by enahum** [comment]
There is a bug where it fails to request the notification permissions on Android (fixed for the dot release and 2.1). If you go to your App Notification settings in your device, you can enable notifications for Mattermost

**Comment by delpiero224** [comment]
I also had to manually allow notifications via Android settings. But even after doing so, I am only receiving notifications for like 1 out of 4 messages. I've checked Huawei's energy saving options, but looks like it is not their fault.

**Comment by Luensche** [comment]
After enabling by myself I still get not push notifications.

**Comment by teamfighter** [comment]
+1 for that issue for mattermost v2.0.1 from Play Market.
Notifications mechanism looks like completly broken.
My phone is Samsung S21 FE.

In the notification settings menu, notifications for this app are off and can't be turned on (can toggle on but just goes straight back to off again). It's also classed as a system app which doesn't seem right. 
I've made sure that the battery setting for the app is unrestricted, I've cleared it's data, uninstalled, rebooted, reinstalled from Google play (so it's definitely up to date) and it's the same. All permissions for the app are enabled, but Notifications permission missing in settings. 
The app works fine in all other ways, it's just that the phone is blocking notifications from it, with no way to stop this.

**Comment by enahum** [comment]
submitted a fix for this and will release shortly

**Comment by Luensche** [comment]
I updated to 2.0.1 and just now I got my first notification after a long time. Thanks for your fix #7099.

**Comment by Luensche** [comment]
I'm a bit confused. In the app, I still see version 2.0.0 (Build 6000456).

**Comment by larkox** [comment]
@Luensche If you are on the beta app, yes, it is expected. 4.0.1 should be only on the release app.
