### ISSUE TITLE
iPad App 2.0.0 - Landscape View

### ISSUE THREAD

**Issue by ZW-WR** [mattermost/mattermost-mobile#7096]
After latest update iPad App version 2.0.0 (Build 452), will not display in Landscape mode. 

Using iPad Pro (11-inch) model number MTXN2LL/A.

The portrait mode on iPad is inconvenient to use.   Would greatly appreciate if this is fixed in the next App update (or advise me on how to make it display in Landscape view).

Thank you

**Comment by amyblais** [comment]
This is fixed in the latest v2.0.1 release,

**Comment by ZW-WR** [comment]
Excellent!  Thank you!
