### ISSUE TITLE
Crash when tapping on any image (iOS)

### ISSUE THREAD

**Issue by nmatt** [mattermost/mattermost-mobile#7106]
#### Summary
Mattermost crashes consistently on iOS when tapping on an inline image in a post.

### Environment Information
  - Device Name: iPhone 13 mini
  - OS Version: 15.7.1
  - Mattermost App Version: 2.0.1
  - Mattermost Server Version: 7.1.5

#### Steps to reproduce
In any channel, create a post with an image. After submitting, tap on the image.

#### Expected behavior
Mattermost should show the image enlarged, and not crash.

#### Observed behavior (that appears unintentional)
Mattermost immediately crashes when tapping on the image.

**Comment by imtoanle** [comment]
I got this issue too

Environment Information
- Device Name: iPhone 11 Pro Max, iPhone 12 Pro Max
- OS Version: 15.6.1
- Mattermost App Version: 2.0.1 (Build 445)
- Mattermost Server Version: 7.7.1
- Database: postgres
- Database Schema Version: 100

This is bug from version 2.0.1 (Build 445).
Version 2.0.0 (Build 452) still working on my iPhone X

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-50457.

**Comment by enahum** [comment]
Thanks for the report, PR has been submitted and fix will be included in the next release 2.1
