### ISSUE TITLE
Keyboard visibility is not kept when cycling through other apps

### ISSUE THREAD

**Issue by kuon** [mattermost/mattermost-mobile#7107]
#### Summary
When cycling apps, the keyboard visibility is not kept.

### Environment Information
  - Device Name: moto g100
  - OS Version:  android 12
  - Mattermost App Version: 2.0.1
  - Mattermost Server Version: 7.7.1

#### Steps to reproduce
Start typing a message, keyboard shows, then switch app, then come back.

#### Expected behavior
Keyboard should be visible and cursor should be at the position where I left it

#### Observed behavior (that appears unintentional)
Keyboard is hidden

As you can see in this animation, when I come back from home screen, keyboard is hidden and I have to re-focus the text field.

![mattermost](https://user-images.githubusercontent.com/160200/218235852-4b780b41-375b-438a-81c8-8128aa2e66da.gif)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-50455.
