### ISSUE TITLE
Application is not respecting system wide preference for disabled animation

### ISSUE THREAD

**Issue by kuon** [mattermost/mattermost-mobile#7108]
#### Summary
Animation are not disabled in the app while they should because I have animation disabled in system accessibility settings.

### Environment Information
  - Device Name: moto g100
  - OS Version:  android 12
  - Mattermost App Version: 2.0.1
  - Mattermost Server Version: 7.7.1

#### Steps to reproduce
Check the "disabled animations" option under accessibility, then use the app.

#### Expected behavior
App should have no animations except those triggered by direct user input (like scrolling). The most disturbing one is when posting a message, the new message should be added at the end instantly without animations. Other animations that should be disabled is expanding collapsing channel list...

#### Observed behavior (that appears unintentional)

Animation plays at regular speed.

### Notes

In css, the media request is `prefers-reduced-motion`, but I do not know if this is exposed in react native. 

This SO answer should provide a solution for android API: https://stackoverflow.com/questions/66891508/how-to-check-status-of-remove-animations-accessibility-setting-programmatically

**Comment by larkox** [comment]
@kuon There has been many updates in the app that may or may have not improved this behavior. Any chance you can take a look and verify if you are still seeing too many animations?

**Comment by larkox** [comment]
Closed because of age and lack of activity.

This should be already solved with the different version updates. If there is any other particular problem, please create a new issue.
