### ISSUE TITLE
Users receiving an error message: "Unable to reset your password"

### ISSUE THREAD

**Issue by sarge-m** [mattermost/mattermost-mobile#7118]
#### Summary
Users on both the Mattermost public version and beta version are receiving an error message: "Unable to reset your password". However, at least for the beta version, the email sends successfuly but the error is still shown. On the mobile web app version and on desktop, no issue is present.

### Environment Information
  - Device Name: iPhone 12
  - OS Version: 16.2
  - Mattermost App Version: 2.0.0 (Build 455)
  - Mattermost Server Version: 7.1.5 (Build 7.1.5)

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

1. Use either Mattermost stable release or current beta release
2. Connect to a valid Mattermost server
3. Attempt to reset your password

#### Expected behavior
Upon attempting to reset the user password, an error is produced which displays an error message that the user cannot reset their password and must contact a system admin. However, the reset email pushes through successfully. On the stable release, it has not been tested if this email still pushes through regardless of the same error produced.

#### Observed behavior (that appears unintentional)
![IMG_6847](https://user-images.githubusercontent.com/6889423/218833102-b6a1122d-ccd5-447f-b6cb-aaa091bb72a4.PNG)

#### Possible fixes
https://github.com/mattermost/mattermost-mobile/blob/7aa5bd0611e89e2d20b8bbfdfc589cd20de94ede/app/screens/forgot_password/index.tsx#L146

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-50501.

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this ?

**Comment by Sudhanva-Nadiger** [comment]
It was happening because we were using response.data which we won't get as a result from the server, we get response.status, so response.data = undefined and the code goes to setError block but the server sends email.

#

![image](https://user-images.githubusercontent.com/93595710/219100909-1800ad09-f767-4d82-bbeb-8866e19f207d.png)

# 

https://user-images.githubusercontent.com/93595710/219104712-5a2205e9-7820-47e8-8e27-d0907279598b.mp4

**Comment by Sudhanva-Nadiger** [comment]
Shall I send pr ?

**Comment by enahum** [comment]
Response from server has no data? That is weird.. yes please submit a PR and I'll take a look at it as soon as I can

**Comment by Sudhanva-Nadiger** [comment]
it returns an object
response = {
    status : "ok",
    error: undefined
}

like this 


but we were using response.data instead of response.status

**Comment by enahum** [comment]
fixed via #7135
