### ISSUE TITLE
 Helpers.class   convertMapToJson()    case Null:    Missing break       

### ISSUE THREAD

**Issue by 337077418** [mattermost/mattermost-mobile#7122]
com.mattermostreactnativeturbolog     Helpers.class   convertMapToJson()    case Null:    Missing break
      

Will cause the official release to crash

**Comment by enahum** [comment]
Will you be submitting a PR?

**Comment by enahum** [comment]
No need, already fixed.. will release a new version soon.

Have you found cases where the current mobile app is affected?

**Comment by 337077418** [comment]
> 不需要，已经修复了.. 很快就会发布新版本。
> 
> 您是否发现当前移动应用程序受到影响的情况？

"stacktrace-parser": "^0.1.3"  to 0.1.4  It is recommended to upgrade this, release app or the save interface will crash

**Comment by 337077418** [comment]
Slide the message list to the top
![Screenshot_20230215-190432_Rocket](https://user-images.githubusercontent.com/10607980/219014538-1c848fc1-6217-421f-8d0b-d5272385bf85.jpg)

 android:12.0

**Comment by enahum** [comment]
> Slide the message list to the top
> 
> ![Screenshot_20230215-190432_Rocket](https://user-images.githubusercontent.com/10607980/219014538-1c848fc1-6217-421f-8d0b-d5272385bf85.jpg)
> 
> 
> 
>  android:12.0

Well in truth this seems related to latex, so a proper reproduction steps would be great

**Comment by 337077418** [comment]
A and B chat normally, and A swipe to view the history message

It seems that he appeared three times in the afternoon by accident

**Comment by 337077418** [comment]
A and B chat normally, and A swipe to view the history message

It seems that he appeared three times in the afternoon by accident

**Comment by enahum** [comment]
Already fixed with #6938
