### ISSUE TITLE
Login Button (SAML) always shows the default button text 

### ISSUE THREAD

**Issue by webr0ck** [mattermost/mattermost-mobile#7123]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Login Button (SAML) always shows the default button text 

### Environment Information
  - Device Name: Samsung s22, iPhone 14
  - OS Version: latest
  - Mattermost App Version: 2.0.1
  - Mattermost Server Version: 7.1.2

#### Steps to reproduce
Open the login form page on the mobile phone

#### Expected behavior
SAML button has the same name which configured on the server side (Authentication -> SAML 2.0 -> Login Button Text)

#### Observed behavior (that appears unintentional)
SAML button has the default name (SAML 2.0)
![2023-02-15 15 01 18](https://user-images.githubusercontent.com/30629042/218955568-e2d39b44-0ac1-445a-af8b-97d7005addaa.jpg)

**Comment by enahum** [comment]
This was fixed and will be available in 2.2 release in march or next week with the next Beta app.
