### ISSUE TITLE
Continuous clicking on the top button will cause app deadlock

### ISSUE THREAD

**Issue by 337077418** [mattermost/mattermost-mobile#7139]
Click the button on the top right corner of home continuously, and the top right corner of the chat interface will cause app deadlock

#### Summary
Bug report in one concise sentence

### Environment Information
  - Device Name:SANSUNG Huawei
  - OS Version:android 12 harmonuOS
  - Mattermost App Version:2.0.0

**Comment by 337077418** [comment]
It seems that every function involving the bottom frame will be deadlocked, and the setting of online status will also be deadlocked

**Comment by enahum** [comment]
What version of the app are you running? As that was fixed with https://github.com/mattermost/mattermost-mobile/pull/7078

**Comment by 337077418** [comment]
> 您运行的是什么版本的应用程序？因为这是用[#7078修复的](https://github.com/mattermost/mattermost-mobile/pull/7078)

C:\Users\Administrator>react-native --version
react-native-cli: 2.0.1
react-native: 0.71.0

**Comment by enahum** [comment]
I'm talking about the app not the version if react native...

It looks like you are running in developer mode, so fetching the latest main branch should resolve it or just cherry pick the PR I just linked

**Comment by 337077418** [comment]
> 如果反应本机，我说的是应用程序而不是版本......
> 
> 看起来你在开发者模式下运行，所以获取最新的主分支应该可以解决它或者只是挑选我刚刚链接的 PR

[Mobile Version 2.0.1]   It seems that your test machine will also appear

**Comment by enahum** [comment]
No

**Comment by 337077418** [comment]
> 不

Excuse me, how does the APP change password appear

**Comment by enahum** [comment]
What is this issue about.. this seems to random. Closing

**Comment by 337077418** [comment]
> 这个问题是关于什么的……这似乎是随机的。关闭



> 这个问题是关于什么的……这好像是随机的。关闭

Sorry to trouble U，   I downloaded the latest client code and found that as long as you quickly click the menu in the upper right corner, the deadlock will still occur. The frequency of clicking 20 times a second app screens navigation. ts export async function dispissModal() will not be triggered. Pay attention to whether the pop-up box at the bottom is closed.

**Comment by 337077418** [comment]
Normal click will have "dismissionModal", and quick click will not trigger

function onCommandListener(name: string, params: any) {
    switch (name) {
        case 'setRoot':
            NavigationStore.clearScreensFromStack();
            NavigationStore.addScreenToStack(params.layout.root.children[0].id);
            break;
        case 'push':
            NavigationStore.addScreenToStack(params.layout.id);
            break;
        case 'showModal':
            NavigationStore.addModalToStack(params.layout.children[0].id);
            break;
        case 'popToRoot':
            NavigationStore.clearScreensFromStack();
            NavigationStore.addScreenToStack(Screens.HOME);
            break;
        case 'popTo':
            NavigationStore.popTo(params.componentId);
            break;
        case 'dismissModal':
            NavigationStore.removeModalFromStack(params.componentId);
            break;
    }

**Comment by 337077418** [comment]
like this：

https://user-images.githubusercontent.com/10607980/219575852-c29472d0-4555-4d7b-a0c2-495ce18e5bc2.mp4

That mask will never be removed
