### ISSUE TITLE
Without member manage function

### ISSUE THREAD

**Issue by keisukelin** [mattermost/mattermost-mobile#7146]
There is still having Member manage and invite member function with Android version 1.3.9.
![image](https://user-images.githubusercontent.com/6444112/219517912-b614d30e-1b15-4d42-ba30-0a9737453a64.png)
But It seems without these function since v2.0.
![image](https://user-images.githubusercontent.com/6444112/219518049-deb3755f-cac9-4e40-9826-dd4a2892ebc7.png)

**Comment by larkox** [comment]
This should be available in 2.1, which should be already available in the stores. Can you confirm?

**Comment by larkox** [comment]
The member list should be available.
Adding new members is not still available, but you can add members by `@`mention them.

**Comment by bitdessert** [comment]
@larkox So when is that going to go live, do you have an approximate timeframe?

**Comment by enahum** [comment]
Target would be 2.3 in april unless something else changes the priority.

That said, as our team is dealing with many different things, I wonder if there is anyone wanting to contribute the feature in that timeframe :)

**Comment by bitdessert** [comment]
@enahum It looks like 2.3.0 hasn't added this feature yet. Do you have any idea when this will be added?

**Comment by enahum** [comment]
As far as I'm aware is included

![image](https://user-images.githubusercontent.com/6757047/233876334-8a7ee504-9343-468c-aafb-506feb0600a1.png)
