### ISSUE TITLE
Markdown images not displaying

### ISSUE THREAD

**Issue by theme1256** [mattermost/mattermost-mobile#7158]
#### Summary
Images sendt as markdown do not display anything in the mobile app.  
Originally reported here: [mattermost-plugin-memes#issue41](https://github.com/mattermost/mattermost-plugin-memes/issues/41)

### Environment Information
  - Device Name: Sony xperia 5 III
  - OS Version: Android 13
  - Mattermost App Version: 2.1.0
  - Mattermost Server Version: 7.5.2

#### Steps to reproduce
Send an image (jpg/png) using markdown eg.
```
![kitten](http://placekitten.com/200/300)
```

#### Expected behavior
The image should be displayed.  
Currently it works fine for gif's, but normal images do not.

#### Observed behavior (that appears unintentional)
The image does not appear in app.

#### Possible fixes
I tried sending the image as an attatchment instead, which worked for an uploaded file, but not for a url-linked image.

**Comment by enahum** [comment]
@Willyfrog can you please open a ticket for the server as the example above does not add any metadata to the post.

**Comment by Willyfrog** [comment]
Am I doing something wrong? I get the image to display with the steps above in community server.

![IMG_2B5D1EBB3A91-1](https://user-images.githubusercontent.com/1515906/221167043-71cc8a56-53f5-4191-84b9-fbc60729a4c5.jpeg)

**Comment by theme1256** [comment]
I'm using a self-hosted server.

**Comment by enahum** [comment]
@Willyfrog i did test in localhost and got the post without metadata, not sure if it is related to the image proxy or something

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-50827.

**Comment by streamer45** [comment]
@theme1256 From what I can see, the issue you are reporting may be happening when accessing Mattermost from a different URL than the one configured in `ServiceSettings.SiteURL`. Could you confirm whether this is the case? 

Also, I am not sure how different image types would affect this, assuming they are all posted the same way (i.e. using markdown). Do you have an example of an image that works under the same conditions?

**Comment by theme1256** [comment]
The images don't show, no matter the domain. I have three domains connected to the server and it doesn't work on either domain.  
It also doesn't work for external images. In my original post I linked to an external image, but images generated from the meme-plugin on the server also don't work. That's what I was originally trying to fix.

I've only tried sending jpg's and gif's, and gif's work.  
I tried rewriting the meme-plugin to send the generated images as attatchments, but that gives the same results.

**Comment by streamer45** [comment]
@theme1256  Alright thanks, I'll try with the plugin then. To confirm, these images are working fine when connecting from web or desktop through the same domain but fail to display on mobile only.

**Comment by theme1256** [comment]
Yes, fine through web and desktop-app.  
And, fine regardless of domain.

**Comment by gitgt** [comment]
I am not sure if this is the same, but I do not see images in Android app, nor I can download them.
Images are png, from screenshot pasted to MM.

**Comment by gitgt** [comment]
@streamer45 I hope this is not unpolite to call you, but since you referenced this in a PR: 
I still have my problem above with app v 2.5.1 - but I do not know for sure that is the same issue as for others.

**Comment by amyblais** [comment]
The PR fix attached to this issue is scheduled for an upcoming server release v8.0.
