### ISSUE TITLE
e: C:\Users\Rrezon-PC\Desktop\mattermost-mobile-viva\mattermost-mobile-main\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\tasks\BundleHermesCTask.kt: (138, 11): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'

### ISSUE THREAD

**Issue by festimii** [mattermost/mattermost-mobile#7167]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 24
        compileSdkVersion = 30
        targetSdkVersion = 30
        supportLibVersion = "31.0.0"
        kotlinVersion = "1.7.21"
        kotlin_version = "1.7.21"
        firebaseVersion = "23.1.1"
        RNNKotlinVersion = kotlinVersion

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        mavenCentral()
        mavenLocal()
        google()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:7.3.1')
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath('com.google.gms:google-services:4.3.15')
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            url "$rootDir/../node_modules/detox/Detox-android"
        }
    }
}

subprojects {
    afterEvaluate { subproject ->
        if(subproject['name'] == 'react-native-create-thumbnail'){
            def myAttribute = Attribute.of("com.android.build.api.attributes.BuildTypeAttr", String)
            dependencies.attributesSchema {
                attribute(myAttribute)
            }
            configurations {
                implementation {
                    attributes {
                        attribute(myAttribute, "release")
                    }
                }
            }
        }
    }
}

**Comment by enahum** [comment]
????

**Comment by festimii** [comment]
This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)
I get this error while building apk sorry for the worng description
