### ISSUE TITLE
Markdown link in the shape of [text](url) written in the web-version of Mattermost couldn't be opened in the app.

### ISSUE THREAD

**Issue by Oluwoye** [mattermost/mattermost-mobile#7177]
#### Summary
Markdown link in the shape of \[text](url) written in the web-version of Mattermost couldn't be opened in the app.

### Environment Information
  - Device Name: Galaxy S20 FE
  - OS Version: Android 11
  - Mattermost App Version: 2.1.0
  - Mattermost Server Version:

#### Steps to reproduce
When writing a link in the format of \[ŧext](url) on my desktop PC (Ubuntu 22.04.2 LTS) in the web version of Mattermost, the link couldn't be opened by another user and myself in the app. The link does work in the web version of Mattermost on my mobile device as well as on my desktop PC and the system of the other user.

#### Expected behavior
The linked website should open

#### Observed behavior (that appears unintentional)
I wrote a link in the Mattermost web-version but it couldn't be opened in the app with the following error message:

"Fehler: Link kann nicht geöffnet werden"

I use the German interface, so I suppose the original message reads something like

"Error: Link couldn't be opened"

The issue was reproduced by a second user on a separate system.

**Comment by enahum** [comment]
maybe share the exact text of your input, cause links with that format do work. Just tested.

**Comment by Oluwoye** [comment]
The link in question was \[my personal website](timcech.de)

**Comment by enahum** [comment]
try adding the protocol, on web the browser defaults to use `http` as the protocol, not the case on the mobile app.

**Comment by Oluwoye** [comment]
That did the trick. Thanks.
