### ISSUE TITLE
Build faild Android v2 :app:createBundleReleaseJsAndAssets

### ISSUE THREAD

**Issue by vigstudio** [mattermost/mattermost-mobile#7178]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/34742453/222380827-9d713e09-e985-4d78-b7e9-5ffba5a23069.png">

use Node 18 and npm 8.5.5

**Comment by enahum** [comment]
I'm using node 18.7.0 and npm 8.18.0 without issue

while building
![image](https://user-images.githubusercontent.com/6757047/222382549-ccf41ce8-85be-454d-a8c8-4bd26aeefb83.png)

and it ends up building just fine
![image](https://user-images.githubusercontent.com/6757047/222383237-81eb281a-4eb9-4b05-bbfd-6597e20c3f1f.png)

Have you made any changes to the code?

**Comment by vigstudio** [comment]
> I'm using node 18.7.0 and npm 8.18.0 without issue
> 
> while building ![image](https://user-images.githubusercontent.com/6757047/222382549-ccf41ce8-85be-454d-a8c8-4bd26aeefb83.png)
> 
> and it ends up building just fine ![image](https://user-images.githubusercontent.com/6757047/222383237-81eb281a-4eb9-4b05-bbfd-6597e20c3f1f.png)
> 
> Have you made any changes to the code?

i clone origin form master and run it. I don't changes any code

**Comment by vigstudio** [comment]
> I'm using node 18.7.0 and npm 8.18.0 without issue
> 
> while building ![image](https://user-images.githubusercontent.com/6757047/222382549-ccf41ce8-85be-454d-a8c8-4bd26aeefb83.png)
> 
> and it ends up building just fine ![image](https://user-images.githubusercontent.com/6757047/222383237-81eb281a-4eb9-4b05-bbfd-6597e20c3f1f.png)
> 
> Have you made any changes to the code?

![image](https://user-images.githubusercontent.com/34742453/222622973-8fc0f693-5b22-4f53-99d6-d7eaa83dc942.png)
i update versioning_android. and nothing
