### ISSUE TITLE
Application won't start on android emulator

### ISSUE THREAD

**Issue by dkoode** [mattermost/mattermost-mobile#7180]
When i tried to start app on android emulator it gives me this error.

![image](https://user-images.githubusercontent.com/81515348/222442656-9824cdce-0d4a-4b89-ba10-72ee8b0f1f63.png)

Im working on a windows machine. 

When i try to "npm install" then it gives me this error,
![image](https://user-images.githubusercontent.com/81515348/222443245-5072afda-cc4e-4286-94e9-5ee9603c9f1d.png)

can anybody help?

**Comment by Sudhanva-Nadiger** [comment]
![Screenshot_2023-03-02-21-42-27-49_54b3de6ee54af4857dd823b6cb3a47b6](https://user-images.githubusercontent.com/93595710/222485661-054df785-2d13-4499-b7d3-0317bbc8dfbb.jpg)
![Screenshot_2023-03-02-21-43-13-17_54b3de6ee54af4857dd823b6cb3a47b6](https://user-images.githubusercontent.com/93595710/222486448-9f39fa7d-0ef9-41fd-a307-2534ee1e1670.jpg)
