### ISSUE TITLE
Android app crash every time trying to view image in markdown table

### ISSUE THREAD

**Issue by svenssonaxel** [mattermost/mattermost-mobile#7189]
#### Summary
Android app crashes every time trying to view a markdown table that contains an inline image. Perhaps related to #2568?

### Environment Information
See screenshot

#### Steps to reproduce
Send a message containing a markdown table that contains an inline image. View that channel in the Android Mobile App.

#### Expected behavior
Table and image is shown

#### Observed behavior (that appears unintentional)
See screenshot

**Comment by svenssonaxel** [comment]
![Screenshot_20230307-172305](https://user-images.githubusercontent.com/163858/223486347-1d26fccd-9989-426c-a6bf-0dc4fd12de9f.png)


![Screenshot_20230307-171604](https://user-images.githubusercontent.com/163858/223486643-b14e6b01-b176-46c8-9cde-9c4e3b00f2e8.png)

**Comment by amyblais** [comment]
@svenssonaxel Are you open to downloading the Beta app (instructions here https://mattermost.com/blog/mobile-beta-program-v2/) to see if the issue reproduces on our latest build (build number 460)?

**Comment by svenssonaxel** [comment]
Reproduced.

![Screenshot_20230307-182120](https://user-images.githubusercontent.com/163858/223503526-8d687fe5-3ef1-458f-b109-1307743d9bfa.png)

![Screenshot_20230307-182038](https://user-images.githubusercontent.com/163858/223503552-ffa21e8c-9e5c-414d-bae2-ea16e18c296d.png)

**Comment by enahum** [comment]
Just as a sanity check, does the inline image shows up in a regular message?

**Comment by svenssonaxel** [comment]
@enahum Turns out, that was a good sanity check!

### Test message contents

Test 1:
```
![](/api/v4/files/w35t17xzu3875mpn54taqrsmuo/thumbnail)
```

Test 2:
```
![](https://domain.name.redacted/api/v4/files/w35t17xzu3875mpn54taqrsmuo/thumbnail)
```

Test 3:
```
![](https://domain.name.redacted/api/v4/files/w35t17xzu3875mpn54taqrsmuo)
```

Test 4:
```
|A|B|C|
|-|-|-|
|a|![](/api/v4/files/w35t17xzu3875mpn54taqrsmuo/thumbnail)|c|
```

Test 5:
```
|A|B|C|
|-|-|-|
|a|![](https://domain.name.redacted/api/v4/files/w35t17xzu3875mpn54taqrsmuo/thumbnail)|c|
```

Test 6:
```
|A|B|C|
|-|-|-|
|a|![](https://domain.name.redacted/api/v4/files/w35t17xzu3875mpn54taqrsmuo)|c|
```

Test 7:
```
![](/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character-thumbnail.jpeg)
```

Test 8:
```
![](https://domain.name.redacted/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character-thumbnail.jpeg)
```

Test 9:
```
![](https://domain.name.redacted/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character.png)
```

Test 10:
```
|A|B|C|
|-|-|-|
|a|![](/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character-thumbnail.jpeg)|c|
```

Test 11:
```
|A|B|C|
|-|-|-|
|a|![](https://domain.name.redacted/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character-thumbnail.jpeg)|c|
```

Test 12:
```
|A|B|C|
|-|-|-|
|a|![](https://domain.name.redacted/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character.png)|c|
```

Test 13:
```
|A|
|-|
|![](/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character-thumbnail.jpeg)|
|![](/api/v4/files/w35t17xzu3875mpn54taqrsmuo/thumbnail)|
```

Test 14:
```
|A|
|-|
|![](https://domain.name.redacted/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character-thumbnail.jpeg)|
|![](https://domain.name.redacted/api/v4/files/w35t17xzu3875mpn54taqrsmuo/thumbnail)|
```

Test 15:
```
|A|
|-|
|![](/api/v4/files/w35t17xzu3875mpn54taqrsmuo/thumbnail)|
```

Test 16:
```
|A|
|-|
|![](https://domain.name.redacted/api/v4/files/w35t17xzu3875mpn54taqrsmuo/thumbnail)|
```

Test 17:
```
|A|
|-|
|![](/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character-thumbnail.jpeg)|
```

Test 18:
```
|A|
|-|
|![](https://domain.name.redacted/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character-thumbnail.jpeg)|
```

### Results

In tests 1-3:
- The web app on desktop shows a message with both text and picture.
- The Android beta app shows a message with text but no picture.

In tests 4-6:
- The web app on desktop shows a table with a picture in one of the cells.
- The Android beta app shows a table with the corresponding cell empty rather than a picture.

In tests 7-9:
- The web app on desktop shows a message with both text and picture.
- The Android beta app shows a message with both text and picture.

In test 10:
- The web app on desktop shows a table with a picture in one of the cells.
- The Android beta app shows a table with the corresponding cell containing a broken-image symbol.

In tests 11-12:
- The web app on desktop shows a table with a picture in one of the cells.
- The Android beta app shows a table with a picture in one of the cells.

In tests 13-14:
- The web app on desktop shows a table with two pictures in the same column.
- The Android beta app **crashes** upon opening the channel.

In tests 15-16:
- The web app on desktop shows a table with a picture in one of the cells.
- The Android beta app shows a table with the corresponding cell empty rather than a picture.

In test 17:
- The web app on desktop shows a table with a picture in one of the cells.
- The Android beta app shows a table with the corresponding cell containing a broken-image symbol.

In test 18:
- The web app on desktop shows a table with a picture in one of the cells.
- The Android beta app shows a table with a picture in one of the cells.

### Summary
- The crash is only reproduced in tests 13 and 14.
  Notably, I could not reproduce the crash with just one image.
- The Android app works as expected in tests 7, 8, 9, 11, 12 and 18.

### Test images
For reference, the test images are as follows:

|URI|Path as used in the examples|SHA256 sum|
|-|-|-|
|https://user-images.githubusercontent.com/163858/223685408-f5621269-8d79-4391-b784-3ecf5ab25b43.jpg|/api/v4/files/w35t17xzu3875mpn54taqrsmuo/thumbnail|6d336b79eb88a2235d9cbfefdf67af3c1991fd5f1e4c2f6f26375b1227241c03|
|https://user-images.githubusercontent.com/163858/223685410-3bce0d9e-aadb-43cd-91f8-02753630f2a6.jpg|/api/v4/files/w35t17xzu3875mpn54taqrsmuo|7abdb589b2ac1fb7cc9f857bf946bf6c80f588d7aa132dab8ba079fb09ed3f4c|
|https://user-images.githubusercontent.com/163858/223685401-95ef49a6-bb90-46c7-9d16-071083495e95.jpeg|/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character-thumbnail.jpeg|0001d4d21b83b288dd55c0d26d70e590c3f193a89cc883777148555e264b9656|
|https://user-images.githubusercontent.com/163858/223685415-c52315fd-c1b8-4429-a40c-7caae21f1322.png|/plugins/com.axelsvensson.mattermost-plugin-character-profiles/character.png|177c8a94bc3c09ed82da70096c98e7940f0eb7ab2c1c2dd74a1db8e93e239d50|

### Potentially separate bugs
- In the test cases above, I've created/edited the message on desktop while the Android app showed the channel list, and only thereafter opened the channel on Android.
  Some of the behaviors above turn out differently if the channel on Android remains open while the messages are edited.
- When the Android app crashes, there's a button to `RELAUNCH`. Clicking this button produces a permanently white screen, and the app has to be killed and restarted manually.

**Comment by svenssonaxel** [comment]
@amyblais @enahum Any update?

**Comment by svenssonaxel** [comment]
Android app doesn't crash anymore, but there is still discrepancies between web app and android app. For example:
```
|A|
|-|
|![](https://user-images.githubusercontent.com/163858/223685401-95ef49a6-bb90-46c7-9d16-071083495e95.jpeg)|
```
This shows an image in the web app but the android app shows nothing.
