### ISSUE TITLE
Selecting custom emoji inserts additional colon

### ISSUE THREAD

**Issue by wezm** [mattermost/mattermost-mobile#7194]
#### Summary

When typing a prefix, then selecting a custom emoji the colon from the prefix is not stripped, leading to a colon being rendered before the emoji.

### Environment Information
  - Device Name: iPhone 14 Pro
  - OS Version: 16.3.1
  - Mattermost App Version: 2.1.0 (Build 457)
  - Mattermost Server Version: 7.8.0

#### Steps to reproduce

- Type a prefix that matches a custom emoji: E.g. `:matt`
- Tap on the matching emoji

The video below shows the behaviour:

https://user-images.githubusercontent.com/21787/223578051-467476f0-b3bc-4920-ac96-ba6f3c7aa80a.mp4

#### Expected behavior

- The emoji is inserted, replacing the typed prefix. E.g. for a `:mattermost:` emoji typing `:matt` and selecting the emoji should result in the aforementioned text.

#### Observed behavior (that appears unintentional)

- In the example above an additional colon is present. I.e. after selecting the emoji the text looks like: `::mattermost`, which when rendered puts a colon before the emoji.
- This does not seem to happen with Unicode/non-custom emoji

#### Possible fixes

Not sure

**Comment by enahum** [comment]
It's been fixed by https://github.com/mattermost/mattermost-mobile/pull/7132 and will be available next release.

Thanks for reporting

**Comment by wezm** [comment]
Great, thank you.
