### ISSUE TITLE
UX Bug: Full screen width for chats is now only available in threads

### ISSUE THREAD

**Issue by quantumpotato** [mattermost/mattermost-mobile#7200]
#### Summary
iOS App Update introduces a UX bug by removing the ability to hide the channel side bar.
Full screen width for chats is now only available in threads, instead of for main channel chats + threads as was previous.

### Environment Information
  - Device Name: iOS
  - OS Version: iPadOS 15.2
  - Mattermost App Version: v2.1.0
  - Mattermost Server Version: N/A

#### Steps to reproduce
Open iPad Mattermost app.
Observe that the channel side bar does not collapse. Previously, swiping left and right could open and close the channel sidebar

#### Expected behavior
Swiping on the sidebar should close it so the chat takes full screen width.

#### Observed behavior (that appears unintentional)
Loss of functionality.

#### Possible fixes
Restore the swipe to close/open functionality on the sidebar.

**Comment by larkox** [comment]
@asaadmahmood @matthewbirtch  :point_up:

**Comment by asaadmahmood** [comment]
@quantumpotato @larkox Thanks for raising the issue. We definitely understand that there can be a usecase, and a benifitial one for allowing users to collapse the LHS. It can allow more space for the center channel content, and not only that, it can perhaps even allow both the center channel, and the thread right hand sidebar to be open at the same time.

So this is something we'll definitely be thinking about.

However for now, there is no immediate resolution to this, as we have other more higher priority things that we're working on at the moment, and maybe if we get more user/customer feedback on this, we may reevaluate the priority of this.
