### ISSUE TITLE
Add option to use bluetooth headset during call

### ISSUE THREAD

**Issue by dominik59** [mattermost/mattermost-mobile#7204]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Bug report in one concise sentence

### Environment Information
  - Device Name: Android
  - OS Version: 13
  - Mattermost App Version: 2.1.0, 2.0.0
  - Mattermost Server Version: 7.8.0

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
- Connect bluetooth earphones
- Start a call to anyone

#### Expected behavior
Describe your issue in detail
I should be able to speak using my headset

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages, screenshots and/or video recordings.
Mattermost app doesn't recognize my headset Nothing ear (1) and play sound using build-in speaker or loud speaker

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by larkox** [comment]
@streamer45 :point_up:

**Comment by JackPala** [comment]
Also experiencing this issue, the latest updated stopped bluetooth calls android from breaking but it also appeared to prevent bluetooth as a call option.

**Comment by cpoile** [comment]
Mobile version 2.4.0 is shipping soon with much better bluetooth support on Android. Hope you enjoy it!
cc @JackPala @dominik59

**Comment by cpoile** [comment]
Closing for now, if there are any new issues calls-relate please let me know and tag me (or `@streamer45`).
