### ISSUE TITLE
Emoji picker freezes the app

### ISSUE THREAD

**Issue by Nick-Su** [mattermost/mattermost-mobile#7219]
#### Summary
When I open the emoji picker on my iPhone, the app freezes completely, and I am forced to do a hard reload in order to continue using the app. But it works perfect on Android.

### Environment Information
  - Device Name: iPhone Xs (probably any iPhone)
  - OS Version: iOS 15.6 (probably any iOS)
  - Mattermost App Version: v2.1.0
  - Mattermost Server Version: v7.8

#### Steps to reproduce
- Long press on a channel/private message
- Tap emoji picker
- Try to scroll and pick an emoji

#### Expected behavior
I can open and close the emoji picker, as well as scroll through all available emojis

#### Possible fixes
Totally no idea

**Comment by heumann** [comment]
Thanks for filing this, @Nick-Su!  I was coming here to file this exact issue.

**Comment by amyblais** [comment]
Does this reproduce on the latest Mobile app version (v2.2.0)?

**Comment by heumann** [comment]
This version appears to solve the issue for me.

**Comment by Nick-Su** [comment]
I confirm. v2.2.0 solves the issue. Yay!
