### ISSUE TITLE
Differing timezones cause app to display messages in the wrong order

### ISSUE THREAD

**Issue by CmdrSharp** [mattermost/mattermost-mobile#722]
#### Summary
Observed when the device timezone is different from the server zone (although not verified if it exists with the same timezone), the app displays messages in the wrong order or even the wrong message on the wrong sender.

#### Environment Information

- Device Name: OnePlus 3T
- OS Version: Android 7.1.1, OxygenOS 4.1.6
- Mattermost App Version: 1.0 (Build 34)
- Mattermost Server Version: 3.10.0

#### Steps to reproduce
1. MatterMost Server Timezone: CDT
2. App on device with Timezone: GMT
3. Have someone post a message to you
4. Post messages back

#### Expected behavior
Your messages (from step 4) should appear at the bottom of the conversation

Equally, an integration that posts attachments should always display the content of these attachments under its own post.

#### Observed behavior
Your messages (from step 4) often appear above the messages sent to you (in step 3).

Equally, an integration that posts attachments often show the content of the attachment under another attachments title.

#### Possible fixes
Can't find the line of code, but forcefully closing and reloading the app when in the channel you wish to view appears to fix the wrong message displaying under the title of a message. It does not however fix the incorrect ordering of messages.

**Comment by lfbrock** [comment]
Does anyone still see this issue? (@CmdrSharp?)

I think we fixed some bugs on the server a while ago where System Admins could sometimes have this happen, are people still seeing it on mobile?

**Comment by andersaamodt** [comment]
This is happening to me now. Moving through lots of time zones, right now I think I am in the same time zone as the server, but message timestamps are two hours in the future. My system clock is correct & I don't know how to fix this :(. I'm an admin so I need correct times!

**Comment by rudiv** [comment]
Why is this issue closed? This is still an issue.

System Admins get sporadic messages appearing out of order (1 hour behind) despite identical timezones between client and server.

For example when sending 3 messages ("a", "b" and "c"), the first message would show in the history at, for example 14:00 (current local time and server time), but the second message would show at 13:00, the third message would then also show correctly at 14:00.
