### ISSUE TITLE
Mattermost Beta is behind mainline

### ISSUE THREAD

**Issue by francislavoie** [mattermost/mattermost-mobile#7238]
I just noticed that Mattermost Beta on Android is still at 2.1.0 but the mainline one on the play store is at 2.2.0.

Is the Beta now deprecated? I didn't see a notice about that. The store listing should be updated to mention it if so.

**Comment by enahum** [comment]
Beta app is always in front of release, the important bit is the build number not the actual version number

**Comment by francislavoie** [comment]
The beta is currently at build 6000461 and the mainline is at 6000462.

The beta is behind. The release date on the play store agrees with this, saying the last update for the beta is on March 7th, whereas mainline was on March 17th.

**Comment by enahum** [comment]
Have a read to https://github.com/mattermost/mattermost-handbook/pull/1192

**Comment by francislavoie** [comment]
Noted, there's a change in release process.

But I just want to point out that the current reality is different than what you suggested, i.e. beta is not _always_ in front of release, as evidenced by what's on the app store right now.

**Comment by enahum** [comment]
> Noted, there's a change in release process.
> 
> 
> 
> But I just want to point out that the current reality is different than what you suggested, i.e. beta is not _always_ in front of release, as evidenced by what's on the play store right now.

Trust me, it is... they should be on the same number but someone who was cutting the last release build bumped the number by mistake, but code wise the beta is ahead, specially the one the is going to be opened for public beta tomorrow

![image](https://user-images.githubusercontent.com/6757047/228396040-706ac1ff-1f0d-460d-8d8e-a2910f77772f.png)
