### ISSUE TITLE
Get beta?

### ISSUE THREAD

**Issue by herohamp** [mattermost/mattermost-mobile#725]
I clicked the get beta for ios entered my info and got 
![image](https://user-images.githubusercontent.com/8162992/27932265-1a415ae8-626b-11e7-9c95-a012824e520e.png)

Hampton Moore, hampmoe@icloud.com

**Comment by MarauderXtreme** [comment]
I think you don't need to sign up anymore since the official release.  
https://itunes.apple.com/us/app/mattermost/id1257222717?mt=8

**Comment by lfbrock** [comment]
Yes thanks! Apps are officially released now, and you can get them from App Store / Google Play.

If anyone would still like to help test beta versions before we release updates to the app store, you can sign up here: 
- [iOS](https://mattermost-fastlane.herokuapp.com/)
- [Android](https://play.google.com/apps/testing/com.mattermost.rnbeta)
