### ISSUE TITLE
after logging out of a server there is no button to remove it

### ISSUE THREAD

**Issue by erfantkerfan** [mattermost/mattermost-mobile#7272]
since its a simple case I'm not going to bother,
here is the scenario:
if you have 2 servers and log out of one, the there is no option to remove it after (I haven't tested with a single server)
[pic](https://file.io/SSTdG8SXw2Qj)

**Comment by enahum** [comment]
Picture is not available, please attach to this thread.

Btw: I could not reproduce

**Comment by erfantkerfan** [comment]
![Screenshot_20230408_064616_Mattermost.jpg](https://user-images.githubusercontent.com/37825504/230700983-fcf8d6ae-85cf-4a3a-9050-011751e60b21.jpg)

There is no option to remove the second server

**Comment by enahum** [comment]
Swipe the second one to the left

**Comment by erfantkerfan** [comment]
Thanks
