### ISSUE TITLE
Bug? Can't attach multiple documents simultaneously

### ISSUE THREAD

**Issue by arladmin** [mattermost/mattermost-mobile#7273]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
I'm able to attach multiple image files in one go. But, I'm not able to do the same for attaching documents. 

### Environment Information
  - Device Name: ?
  - OS Version: Ubuntu (Cloudron)
  - Mattermost App Version: 2.2.0
  - Mattermost Server Version: 7.9.1

#### Steps to reproduce
Try for any chat, using the latest Android app.

#### Expected behavior
I expected to be able to attach multiple files simultaneously, to any chat.

This is actually one of the features due to which I'm switching over to Mattermost, as users often need to share multiple files and our previous chat app didn't allow attaching multiple files in one message.

This functionality is quite necessary.

**Comment by arladmin** [comment]
Anyone?

**Comment by larkox** [comment]
https://mattermost.atlassian.net/browse/MM-52145
