### ISSUE TITLE
LaTeX rendering clipped on Android

### ISSUE THREAD

**Issue by svenssonaxel** [mattermost/mattermost-mobile#7274]
#### Summary
LaTeX rendering clipped on Android

### Environment Information
  - Mattermost App Version: 2.3.0 (Build 6000464)
  - Mattermost Server Version: 7.1.5

#### Steps to reproduce
Send a message containing `$\frac{1}{5}$`.

#### Expected behavior
Message list shows a fraction line with number `1` above and number `5` below it.

#### Observed behavior (that appears unintentional)
On Android, the `5` is clipped; only half of it is shown.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52150.

**Comment by svenssonaxel** [comment]
You probably meant https://mattermost.atlassian.net/browse/MM-52151
