### ISSUE TITLE
Mobile App is crashing once I click on anything after launch

### ISSUE THREAD

**Issue by Imabql** [mattermost/mattermost-mobile#7276]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https:/

### Environment Information
  - Device Name: pixel 3a
  - OS Version: 10
  - Mattermost App Version: the newest one on play store
  - Mattermost Server Version: unable to confirm as the app is crashing
Attached screenshots with error

#### Steps to reproduce
Open the app and click on anything

#### Expected behavior
App should not crash

#### Observed behavior (that appears unintentional)
![Screenshot_20230410-172256](https://user-images.githubusercontent.com/130384530/230933435-3463c5d4-377e-44fa-9216-49534e847d0c.png)
![Screenshot_20230410-172253](https://user-images.githubusercontent.com/130384530/230933441-e067cb40-da6f-4f99-bdc7-e190c86df76f.png)

**Comment by larkox** [comment]
Seems to be the same as this one: https://mattermost.atlassian.net/browse/MM-51959

Do you remember anything particular around the time you started seeing this issue?

A quick fix while we figure out why the app get into that state is login out and back in the server. If you cannot log out for any reason (you should be able to log out or remove the server from the server list), you can uninstall and reinstall the app.
