### ISSUE TITLE
[iOS] The thread doesn't open from the push notification. The error is "Cannot compare to undefined in a Query. Did you mean null?"

### ISSUE THREAD

**Issue by Nick-Su** [mattermost/mattermost-mobile#7281]
#### Summary
When I tap on the push notification on the lock screen (that opens a thread) I get an error. The thread does not open and I see an error log.

### Environment Information
  - Device Name: iPhone Xs
  - OS Version: iOS 15.6
  - Mattermost App Version: 2.2.0
  - Mattermost Server Version: 7.10.0

#### Steps to reproduce
User A and User B are needed. It is necessary to include collapsed chains of responses.

1. User A opens a direct message with User B and writes message ``#1``. User A also writes message ``#2`` in response to message ``#1`` (starts a thread under message ``#1``).
2. User B opens direct messages and goes to the thread started by User A in step 1. Important! User B leaves the thread open and locks the phone / turns off the screen.
3. User A writes message ``#3`` in a public channel (where User B is present) and mentions User B.
4. User A starts a thread under message ``#3`` (writes message ``#4`` in response to message ``#3``). Important! User A writes in the thread until a push notification appears on User B's locked phone.
5. User B clicks on the push notification, which will open the thread in the public channel (and unlock the phone).
6. An attempt is made to change the thread and an error appears.
7. User B clicks the "Restart" button in the error modal. Opens the thread in direct messages with User A and locks the phone.

The bug is erratic. The described steps can lead to an error in 50-70% of cases, but sometimes, by executing these steps, the application enters a state in which each subsequent execution of steps 4-7 will consistently lead to an error (100% probability of reproduction).

If this does not result in an error, you can try this. User B opens the thread with User A and locks the phone. User A writes to User B in direct messages and in the thread in the public channel until 2 push notifications appear on User B's screen. Then User B performs step 5.

#### Expected behavior
I'm able to click on a push notification and see the message

#### Observed behavior (that appears unintentional)
I get an error "Unexpected error occurred. Tap relaunch to open the app again. After restart, you can report the problem from the settings menu. Cannot compare to undefined in a Query. Did you mean null?"

![IMG_0024](https://user-images.githubusercontent.com/29861468/231755977-191c15e2-a832-4ac8-815e-79def118c149.jpg)

#### Possible fixes
No idea, sorry.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52150.

**Comment by Nick-Su** [comment]
I'm here to clarify that the issue is still reproducible in v2.3.0
