### ISSUE TITLE
can't add server (with new TLD in Android app)

### ISSUE THREAD

**Issue by mxa** [mattermost/mattermost-mobile#7313]
#### Summary
The android app can't connect to a Mattermost server with a .audio domain name. Works on the web, the Linux desktop app and on iOS.

### Environment Information
  - Device Name: Nokia 6.2
  - OS Version: 11
  - Mattermost App Version: 2.3.0
  - Mattermost Server Version: 7.10.0

#### Steps to reproduce
try add a server that has a .audio domain . (I suspect that's the culprit of the issue)

#### Expected behavior
I can't login on the device. It works on the web, the Linux desktop app and on iOS

#### Observed behavior (that appears unintentional)
![grafik](https://user-images.githubusercontent.com/1220707/234377535-1c33d78e-bb17-4f04-bacb-aa10c1ce6fc7.png)

**Comment by fragger1991** [comment]
Are you sure that the Domain is the problem? We have such Problems too with .de Domain. For me it looks more like a general Problem with mattermost and the App. See the last zwo issues posted here.

**Comment by enahum** [comment]
Have you check that the SSL cert and its chain is fully valid? You can try ssllabs.com to validate

**Comment by mxa** [comment]
OK, will investigate. If that's the culprit, it means that the desktop client and the iOS app don't bother about a fully valid SSL cert?

**Comment by mxa** [comment]
even with Grade A SSL security it's not working.

**Comment by enahum** [comment]
If you can, please share you server url with me over DM in our [community server](https://community.mattermost.com).. my username there is `@elias` so I can investigate the cause

**Comment by mxa** [comment]
It's fixed. Admin fixed it with a docker-update, something related to IPv6.

**Comment by fragger1991** [comment]
This is really very strange. I was able to solve the problem for us, it was also a problem with IPv6 for us. With us, the server generally no longer responded to IPv6. This only happened shortly after the Mattermost update.

**Comment by Stromduster** [comment]
Same problem here, since last week. Our server is running in a lxc container on Proxmox. I disabled IPv6 on both just to be sure, but nothing work son the mobile Android app. Has someone figured out what was the source issue ?

**Comment by mxa** [comment]
A restart of the phone possibly helped resolve the issue.

**Comment by fragger1991** [comment]
> Could someone be a little more precise what had to be fixed with IPv6 to have it running again?

As I wrote before, IPv6 just didn't work correctly overall. A reboot of the VM finally solved the problem.

So make sure that the server actually responds to IPv6 and delivers content. Many of the online tools only check whether an AAAA record exists and only output the IPv6 address or ping it, but do not return any concrete results, e.g. B. the web server actually delivers the page via IPv6.
