### ISSUE TITLE
Cannot read property 'nickname' of undefined

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/mattermost-mobile#7315]
Good afternoon
When starting MM on ios, an error appears:
![ios](https://user-images.githubusercontent.com/109951790/235104978-becdfd32-575f-4db4-86fc-1a40e6c817b1.png)

MM version: 7.9.2
MM mobile: 2.3.0
IOS: 16.4.1

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-52598.

**Comment by KakEgorka** [comment]
> `Teammate Name Display` a
Teammate Name Display:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/109951790/235585814-00233b23-f098-41ad-a916-760fad431b6f.png">

Users have not been deleted from the database before.


I noticed that this error began to appear in the general channels. And it helps to go to another channel and come back. Then the chat is loaded.

**Comment by larkox** [comment]
Does this happen when moving to a channel and when going to the profile? I have heard of a similar issue, and may be related with the `currentUser` (or `currentUserId`) not being available in the database for some unknown reason.

The app should load fine, but moving to a channel where you have written or the profile should break. Could you confirm this is the behaviour you are seeing?

**Comment by KakEgorka** [comment]
Today there was another error.
![IMG_1922](https://user-images.githubusercontent.com/109951790/236113712-fe70bdb0-cb6f-4f52-a1ac-eb1220c6c719.png)
The actions were like this. Were talking in a thread. When the notification came, the application was reopened and everything worked fine. But once it gave such an error in the same thread where it had not been before. The users in the thread did not change.

**Comment by larkox** [comment]
This is a different issue we are also tracking down. @enahum take a look here, in case this give you more data points on this issue.

**Comment by enahum** [comment]
Thanks, the last one about the null query is being investigated at the moment with similar repro steps if not the same
