### ISSUE TITLE
Markdown tables are won't be rendered

### ISSUE THREAD

**Issue by sedrubal** [mattermost/mattermost-mobile#734]
#### Summary
Markdown tables are won't be rendered.

#### Environment Information

- Device Name: Nexus 5
- OS Version: Android 7.1.2
- Mattermost App Version: 1.0
- Mattermost Server Version: 3.10.0

#### Steps to reproduce
Write this:

```md
| A | B |
|---|---|
| a | b |
```

#### Expected behavior
This should be rendered (like in the Mattermost web app):

![correct markdown table](https://user-images.githubusercontent.com/5571650/28096129-c0786098-66a6-11e7-993f-32a68d79b335.png)

#### Observed behavior
This will be rendered:

![broken table](https://user-images.githubusercontent.com/5571650/28096214-56960d1e-66a7-11e7-9b3c-e3cc1496ef65.jpg)

#### Possible fixes
I think marked can render tables. Maybe you have to enable table support: https://github.com/chjj/marked#tables

**Comment by lfbrock** [comment]
Thanks @sedrubal! 

We still need to add support for tables - we have a ticket here to track the issue: https://mattermost.atlassian.net/browse/RN-175

**Comment by kirsanau** [comment]
also is not working in ios
we rely on that feature a lot, and forced to use "classic" version of the app, where it works

**Comment by brightsparc** [comment]
it also appears that markdown images are not supported as well.

**Comment by enahum** [comment]
Markdown tables and images are scheduled to be included with release 1.3. Im closing this issue but feel free to re-open if needed

**Comment by Kelloggs** [comment]
On iOS, table still aren't rendered. Did this work in the past and is regression?

**Comment by enahum** [comment]
@Kelloggs sadly markdown tables are still not supported, it was originally planed to be included in 1.3 but other things have taken priority

You can keep track of the progress for markdown tables by following this ticket https://mattermost.atlassian.net/browse/ICU-601
