### ISSUE TITLE
Calls. Blank screen after ending a call and exiting its thread

### ISSUE THREAD

**Issue by Nick-Su** [mattermost/mattermost-mobile#7377]
#### Summary
Blank screen after ending a call and exiting its thread

### Environment Information
  - Device Name: iPhone XS
  - OS Version: v15.6
  - Mattermost App Version: v2.4.0
  - Mattermost Server Version: v7.8

Notice: also reproducible on Android 12

#### Steps to reproduce
1. Start a call
2. Expand call screen
3. Tap "three dots" button
4. Tap "Call Thread"
5. End the call
6. Tap back button in top left corner
7. Blank screen appears

#### Expected behavior
I can see a previous screen after ending a call and leaving its thread.

#### Observed behavior (that appears unintentional)
Totally blank screen.

#### Possible fixes
No idea.

**Comment by amyblais** [comment]
cc @streamer45 @cpoile

**Comment by cpoile** [comment]
Thanks @Nick-Su for the report, I've made a make a ticket and will investigate: https://mattermost.atlassian.net/browse/MM-52949
