### ISSUE TITLE
GitLab login not working on server v3.10+

### ISSUE THREAD

**Issue by lfbrock** [mattermost/mattermost-mobile#738]
GitLab login should work on servers v3.10 and above, but we've had a few reports of it not working. 

If anyone is having issues with GitLab login, can you help us track down the issue by reporting: 

**Environment Information:**
Device Name: 
OS Version: 
Mattermost App Version: 
Mattermost Server Version: 

It would also be helpful to know if other people on your server see the same issue, or if there is anyone who is able to sign in with GitLab with their device.

**Comment by jpivarski** [comment]
Device: Nexus 5X
OS: Android 7.1.2
Mattermost app version: current and 2017
 beta (both)
Mattermost server: mattermost.web.cern.ch (as of today)

GitLab authentication is on and I can log in through the web (only, which limits my use of Mattermost). In both the current (as of today) main app and 2017 beta app, it claims "invalid credentials" (slightly different message in the two versions). Is like to try setting an explicit password to test that, but I don't think I can do that as a user.

**Comment by artlbv** [comment]
I +1 @jpivarski for this issue on the same server which runs MM 3.9.0.

Device: iPhone SE
OS: iOS 10.3.2
Mattermost app version: current 1.0 (classic works)
Mattermost server: https://mattermost.web.cern.ch

**Comment by enahum** [comment]
This should be fixed with the 1.0.1 release on the app. 

Note: it needs server 3.10 or grater.

Closing this, feel free to re-open if the issue persist

**Comment by artlbv** [comment]
Hi @enahum, I've upgraded to version 1.0.1, but I still cannot login to the server with the same error message of wrong password.
The old app used to show the Gitlab login page (same as browser/Mac behaviour), while this one shows its own login page – could this be a problem?
