### ISSUE TITLE
Can't connect from Android app

### ISSUE THREAD

**Issue by YusukeMasuda36** [mattermost/mattermost-mobile#7391]
Can't connect to server from android app

### Environment Information
  - Device Name:Xperia5Ⅳ
  - OS Version:Android13
  - Mattermost App Version:2.4.0
  - Mattermost Server Version:7.10.2

**Comment by amyblais** [comment]
Hi @YusukeMasuda36, what error are you seeing?

**Comment by YusukeMasuda36** [comment]
Thank you @amyblais 
Fixed by restarting the server.
