### ISSUE TITLE
The server name disappears.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#7395]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
After logging out, the value of displayName in the initial server selection screen seems to change to server url.

### Environment Information
  - Device Name: 
  - OS Version:
  - Mattermost App Version:  2.4.0
  - Mattermost Server Version:

#### Steps to reproduce
Log out.

Review the server selection screen.

Log in, then log out again.

Check the server selection screen. 

#### Expected behavior
Logging out should not replace the server display name with the server url

#### Observed behavior (that appears unintentional)
When you log out, the server display Name is replaced with the server url

**Comment by amyblais** [comment]
What OS and version are you on? What Mattermost server version are you on?

**Comment by bitdessert** [comment]
@amyblais Sorry, I see it now. iOS 16, server 8.1

**Comment by amyblais** [comment]
@bitdessert I haven't been able to reproduce this. Does this still happen in mobile app v2.8.0, and is there are any other information about your environment that could help me reproduce it?

**Comment by bitdessert** [comment]
@amyblais Can you put the value of AutoSelectServerUrl as true inside the Config.json file and test it? 
When the value of AuthSelectServerUrl is false, it seems to work fine.
But after setting it to true, the logout menu shows the subtext "Log out at {url}". 
Also, when logged out, the url is entered in displayName field of the server information screen.

**Comment by bitdessert** [comment]
@amyblais Check out the handleconnect method in the screens/server/index.tsx file. 
If the autoconnect value is true, the displayName value inside the handleConnect method is an empty value; if the autoconnect value is false, the displayName value is set when the handleConnect button is called

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54533.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
