### ISSUE TITLE
Android: Cannot connect to the server

### ISSUE THREAD

**Issue by JoeMurray** [mattermost/mattermost-mobile#746]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Using same url as works for Android Mattermost Classic app, get cannot connect error

#### Environment Information

- Device Name: Samsung Galaxy 5
- OS Version: Android 6.0.1
- Mattermost App Version: Android Mattermost Beta
- Mattermost Server Version: 3.6

#### Steps to reproduce
How can we reproduce the issue? Try to connect to https://chat.civicrm.org (a couple of us have had same error)

#### Expected behavior
Describe your issue in detail. See above.

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
Cannot connect to the server. Please check your server URL and internet connection.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
@JoeMurray the app needs at least a 3.8+ server

**Comment by mickadoo** [comment]
It might be nice to improve the error message here, but if the problem is just the server version this should be alright to close.

**Comment by enahum** [comment]
Closing per request
