### ISSUE TITLE
Display got cut off in desktop mode / Samsung dex

### ISSUE THREAD

**Issue by rvbd** [mattermost/mattermost-mobile#7511]
When running matter most in Samsung Dex mode, somehow the interface got cut off at the top. I have attached the screenshot with this issue.

To reproduce, use any supported Samsung device like S22, S23, Tab Lite S6, etc and open matter most in Samsung Dex.![Screenshot_20230821_084634_Samsung DeX home.jpg](https://github.com/mattermost/mattermost-mobile/assets/1558550/73bca83e-013d-47ea-859d-4e6ff45ba699)

Hopefully there is a way to fix, thanks all!

**Comment by amyblais** [comment]
@lindy65 @yasserfaraazkhan Do we have a similar test environment to see if this reproduces?

**Comment by lindy65** [comment]
@amyblais I researched how to run the mobile app in DeX mode and it seems an HDMI cable and external monitor are required, neither of which I have, sorry...

https://developer.samsung.com/samsung-dex/how-it-works.html

**Comment by amyblais** [comment]
@larkox @enahum Should I create a Jira ticket for this even if we don't have a similar environment to test this?

**Comment by enahum** [comment]
> @larkox @enahum Should I create a Jira ticket for this even if we don't have a similar environment to test this?

Yes Amy, we should

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54324.

**Comment by larkox** [comment]
There is already a help wanted ticket here for a similar issue. Made a comment there, and will close this one as duplicated of the other. https://github.com/mattermost/mattermost/issues/25452
