### ISSUE TITLE
Slash commands do not work in new iOS app

### ISSUE THREAD

**Issue by tofi86** [mattermost/mattermost-mobile#752]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Slash commands liek `/away` do not work in new iOS app.

#### Environment Information

- Device Name: iPhone 6s
- OS Version: latest stable
- Mattermost App Version: 1.0 (39)
- Mattermost Server Version: 3.10.0

#### Steps to reproduce
Send a slash command like `/away` or `/offline`

#### Expected behavior
Should work like in browser and desktop apps.

#### Observed behavior
Slash command is posted as text.

#### Possible fixes
???

**Comment by lfbrock** [comment]
Thanks @tofi86 - we still need to add support for slash commands, created a ticket here to track: https://mattermost.atlassian.net/browse/RN-272

**Comment by timrsmith** [comment]
Came here to post same issue. Slash commands don't appear to work. Nor do other commands like the "+:thumbs_up:" on replies to add emoticons.

**Comment by enahum** [comment]
Slash commands should be implemented for release 1.3 emojis are already supported since 1.1 I think.

Im going to close this issue but feel free to re-open if needed.

**Comment by clemenskroell** [comment]
Any update on this? 1.3 is out and it’s not fixed.

**Comment by enahum** [comment]
We needed to shift priorities and it might make it for 1.5
