### ISSUE TITLE
Mattermost for android - HEIC Image from gallery does not auto convert to jpg and just uploads a HEIC file.

### ISSUE THREAD

**Issue by ageekhere** [mattermost/mattermost-mobile#7546]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

#### Summary
Mattermost for android - HEIC Image from gallery does not auto convert to jpg and just uploads a HEIC file.

### Environment Information
  - Device Name: Galaxy A73 5G
  - OS Version: Android 13
  - Mattermost App Version: 2.7.0
  - Mattermost Server Version: 7.10.4

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
First make sure high efficiency pictures is enabled in the camera settings and using Mattermost for android from the play store (2.7.0) and Mattermost Version: 7.10.4 take a picture on the android device and use the upload an image icon and select a HEIC picture. 

#### Expected behavior
The image should show within the chat

#### Observed behavior (that appears unintentional)
The HEIC picture is uploaded as a file

![Screenshot 2023-09-16 173403](https://github.com/mattermost/mattermost-mobile/assets/13173133/3e580e3e-bd45-4831-aa28-35d1f5e35490)

#### Other notes
The current work around is to take a picture from Mattermost using the camara icon, this creates an image that can show up in the chat.

**Comment by amyblais** [comment]
@lindy65 Are you able to reproduce this on Android?

**Comment by ageekhere** [comment]
I updated to mattermost android to app v2.8 and mattermost server to Mattermost Version: 8.0.1 (I use gitlab)
The issue is still there, the HEIC file uploads as an attachment for android.

**Comment by lindy65** [comment]
Thanks for the feedback @ageekhere 

@amyblais - perhaps someone with an Android that uses HEIC format (maybe a similar device to the reporter - Galaxy A73 5G) can try to reproduce?

**Comment by enahum** [comment]
No need to reproduce, this is in fact 100% true, we never made any improvements on HEIC, server does not modify the file nor the Android client, iOS is able to render heic files natively

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54521.
