### ISSUE TITLE
App crash from push notification

### ISSUE THREAD

**Issue by wispoz** [mattermost/mattermost-mobile#7549]
#### Summary
App crash on open chat from push notification

### Environment Information
Current User Id: hqbsubpqrpfnmd68fufoeptw5r
Current Team Id: 7wa4x4791prcjdksawkdxgo4he
Server Version: 7.10.4 (Build 7.10.4)
App Version: 2.8.0 (Build 6000484)
App Platform: android
Device Model: trinket

[com.mattermost.rn-latest.log](https://github.com/mattermost/mattermost-mobile/files/12681278/com.mattermost.rn-latest.log)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54534.

**Comment by Fischmuetze** [comment]
same here 

Environment Information

Device Name: iPad Air 4th gen
OS Version: 17
Mattermost App Version: 2.8.0
Mattermost Server Version: 8.1.0
Steps to reproduce

![IMG_4145](https://github.com/mattermost/mattermost-mobile/assets/19834496/c8c1d15c-9142-42fc-8620-45b195ba40c2)

**Comment by gergoradeczki** [comment]
We noticed the same issue as well. What is weird is that only one Team in our self hosted instance has this issue. For example, clicking on a notification from a different team, we can't reproduce the issue. Also, sometimes it does not show up when clicking on a notification from the "infected" Team.

**Comment by larkox** [comment]
This issue must be related to a "malformed" post, so notifications to the same channel, should always create this.

That being said, I am going to add some defensive code to this, and should fix it.
