### ISSUE TITLE
Tutorial doesn't work on iOS17.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#7558]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Tutorial doesn't work on iOS17.

### Environment Information
  - Device Name: iphone 12 pro
  - OS Version:  17.0.2
  - Mattermost App Version: 2.8.0
  - Mattermost Server Version: 8.1

#### Steps to reproduce
1. View a list of members
2. Tutorials containing the message 'Long-press on an item to view a user's profile' did not render correctly

#### Expected behavior
Tutorials containing the message 'Long-press on an item to view a user's profile' should render correctly

#### Observed behavior (that appears unintentional)
Not rendered, does not recognize any touch. The app is dead

But, works fine on Ios16 

#### Possible fixes
Appears to be a rendering issue in Ios17

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54575.

**Comment by adityasonel** [comment]
I'd tried to reproduce this bug on iOS 17.0.2, but the flow is seems like working as expected. Steps I followed:

1. Navigated to the members list
2. Tutorial dialog containing long-press on an item to view a user's profile shows up
3. Clicked on random point on the screen to hide/disable the tutorial dialog
4. Then long-pressed on few member to view the user's profile info


https://github.com/mattermost/mattermost-mobile/assets/28022451/9d28ee95-a994-4d86-b6d4-85d27185b1b9

**Comment by bitdessert** [comment]
@adityasonel Have you tested it on 17.0.3? I updated to 17.0.3 and did a clean install of mattermost and it reproduces.

**Comment by fallingrock** [comment]
This should be fixed by #7599
