### ISSUE TITLE
Magic Keyboard doesn’t work after iOS 17 update

### ISSUE THREAD

**Issue by Gujs** [mattermost/mattermost-mobile#7567]
#### Summary
Not possible to use Apple Magic Keyboard with iOS 17 with latest Mattermos Chat app installed. This problem only accoures when app is running in full screen. App competely freezes and can only be used again if restarted.
I have discovered that Magic Keyboard works if Mattermost app is only on half screen with any other app using second half of the screen. But app also freezes after some time.

### Environment Information
  - Device Name: iPad 12.9 2022 and Magix Keyboard
  - OS Version: iPad OS 17.0.1 and 17.0.2
  - Mattermost App Version: v2.8.0
  - Mattermost Server Version: 8.1.0

#### Steps to reproduce
Start an app in full screen and try to type a message to channel or person. When focus of text field is selected app freezes and is not usable any more until it is forced killed. Apple Magic keyboard is needed to reporduce this issue.

#### Expected behavior
Typing should work with magic Keyboard.

**Comment by enahum** [comment]
This is already resolved and to be fixed in the 2.9 release unless @amyblais decides to include it for the upcoming 2.8.1 release

**Comment by amyblais** [comment]
This will be included in v2.8.1, which will release in the next couple days.
