### ISSUE TITLE
No notifications at all

### ISSUE THREAD

**Issue by Progdrasil** [mattermost/mattermost-mobile#757]
#### Summary
There are no notifications at all when others post in threads I'm following or even in private messages. this is whether the app is open, in background or closed.

#### Environment Information

- Device Name: moto Z Play
- OS Version: 7.0
- Mattermost App Version: 1.0 build 39
- Mattermost Server Version: 3.10.0

#### Steps to reproduce
- fresh install of mattermost on server and Android phone, 
- enabled all notifications in android app, 
- setup mattermost sso with seperate install of gitlab on same server

#### Expected behavior
Notification when a message is send, even when app is closed

#### Observed behavior
no notifications at all

**Comment by nicolinuxfr** [comment]
Same here, with iPhone running iOS 10 or iOS 11. We did a custom build for our Mattermost server and notifications still work on desktop so I guess there is a bug in the app.

**Comment by enahum** [comment]
Does you server has push notifications enabled and configured? What about your user preferences?

**Comment by nicolinuxfr** [comment]
Sorry about that, it was a configuration mistake on our side.

**Comment by Progdrasil** [comment]
sorry, it was a configuration mistake on our end as well i followed the instructions in [this documentation](https://docs.mattermost.com/deployment/push.html)

**Comment by enahum** [comment]
Good to know
