### ISSUE TITLE
Android app can't connect if server isn't listening on IPv6

### ISSUE THREAD

**Issue by a-gerhard** [mattermost/mattermost-mobile#7576]
We recently had the same issue as @n-gao in https://github.com/mattermost/mattermost-mobile/issues/6643#issuecomment-1482755439_ – The only thing we saw was that the Android app was having trouble most of the time, while all other apps as well as web browsers (even on Android) did not have any issue, and the only message we got was "failed to connect". This made it pretty hard to debug.

Debian 11 currently has a docker version (20.10.5) which only publishes IPv4 addresses when publishing a port globally (the related GitHub issue can be found [here](https://github.com/moby/libnetwork/issues/2607)). This means that this faulty configuration could easily be deployed by anyone using Mattermost's official docker-with-nginx installation guide on a Debian 11 server.

It appears that the iOS app, the Desktop app, as well as web browsers will retry the connection on IPv4 if IPv6 fails, but the Android app doesn't. Hence, the connection issue only in the Android app, and only when it's inside an IPv6-enabled network.

I suggest fixing this issue in the Android app, and until then, adding this to the [debugging guideline](https://docs.mattermost.com/deploy/mobile-troubleshoot.html#i-keep-getting-a-message-cannot-connect-to-the-server-please-check-your-server-url-and-internet-connection)

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
