### ISSUE TITLE
Cannot read property 'centerChannelColor' of undefined

### ISSUE THREAD

**Issue by fallingrock** [mattermost/mattermost-mobile#7577]
Downloaded the latest version from apple App Store (2.8.1), launched app, and got this error. 

Tapped relaunch button but got blank white screen. 

Killed app and launched again. 

App launched, but forgot server information. Had to renter url and server name. 
![image](https://github.com/mattermost/mattermost-mobile/assets/4029821/7af5e611-dd04-4120-afa8-e4f9271361e4)

I've received this error in previous versions, but didn't create a ticket. 

Unexpected error occurred
Tap relaunch to open the app again.
After restart, you can report the problem from the settings menu.
Cannot read property
'centerChannelColor' of undefined
TypeError: Cannot read property
'centerChannelColor' of undefined at anonymous (/Users/runner/ Library/Developer/Xcode/DerivedData/ Mattermost-bkusffojapjudtaczuk-
micpffbrx/Build/Intermediates.noindex/ Archivelntermediates/Mattermost/ BuildProductsPath/Release-iphoneos/ main.jsbundle:659023:72)
at anonymous (/Users/runner/ Library/Developer/Xcode/DerivedData/ Mattermost-bkusffojapjudtaczuk-
micpffbrx/Build/Intermediates.noindex/ Archivelntermediates/Mattermost/ BuildProductsPath/Release-iphoneos/ main.jsbundle:81283:65)
at Server (/Users/runner/Library/ Developer/Xcode/DerivedData/ Mattermost-bkusffojpjudtaczuk-
micpffbrx/Build/Intermediates.noindex/ Archivelntermediates/Mattermost/ BuildProductsPath/Release-iphoneos/ main. jsbundle:659079:31)
at renderWithHooks (/Users/runner/ Library/Developer/Xcode/DerivedData/ Mattermost-busffojqpjudtaczuk-
micpffbrx/Build/Intermediates.noindex/ Archivelntermediates/Mattermost/ BuildProductsPath/Release-iphoneos/ main.jsbundle:19925:24)
at henin|ork$1 //lIcers/runnerl

Current User Id: zbfyf5wfj7r85rg4t6ot6594my
Current Team Id: q18i5xqckffx3cpibfqu3yqmdh
Server Version: 7.1.5 (Build 7.1.5)
App Version: 2.8.1 (Build 487)
App Platform: ios
Device Model: iPhone16,1
[com.mattermost.rn 2023-09-24--16-45-51-194.log](https://github.com/mattermost/mattermost-mobile/files/12784335/com.mattermost.rn.2023-09-24--16-45-51-194.log)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54710.

**Comment by fallingrock** [comment]
I received this error again with the latest version 

Server Version: 7.1.5 (Build 7.1.5)
App Version: 2.11.0 (Build 497)
App Platform: ios
Device Model: iPad13,4


2023/09/11 09:10:48:213 DEBUG Setting the badge count based on database values to 0
2023/09/11 09:10:58:995 DEBUG Setting the badge count based on database values to 0
2023/09/11 09:11:03:564 INFO websocket closed wss://mattermost.oreillyauto.com/api/v4/websocket?connection_id=ne8anmwec7b55e57af6hkki56o&sequence_number=16
2023/09/13 18:51:47:348 INFO Launch app in Home screen
2023/09/13 18:51:47:353 INFO websocket connecting to wss://mattermost.oreillyauto.com/api/v4/websocket?connection_id=&sequence_number=0
2023/09/13 18:51:47:355 INFO websocket connecting to wss://mattermost.oreillyauto.com/api/v4/websocket?connection_id=&sequence_number=0
2023/09/13 18:51:47:359 INFO channel switch to Retail Hardware 43jewihqitf7fkgqs7jezzd5je 16 ms
2023/09/13 18:51:47:366 INFO Running "Home
2023/09/13 18:51:47:652 DEBUG Setting the badge count based on database values to 0
2023/09/13 18:51:47:659 INFO Running "ReviewApp
2023/09/13 18:51:47:795 DEBUG error on fetchPostsSince Invalid or expired session, please login again.
2023/09/13 18:51:47:795 DEBUG error on fetchPostsForChannel Invalid or expired session, please login again.
2023/09/13 18:51:47:803 DEBUG error on fetchChannelStats Invalid or expired session, please login again.
2023/09/13 18:51:47:804 DEBUG error on markChannelAsRead Invalid or expired session, please login again.
2023/09/13 18:51:47:804 DEBUG error on fetchBindings Received invalid response from the server.; JSON could not be serialized because of error:
The data couldnât be read because it isnât in the correct format.
2023/09/13 18:51:47:804 DEBUG error on fetchConfigAndLicense Received invalid response from the server.; Request explicitly cancelled.
2023/09/13 18:51:47:806 INFO websocket connected to wss://mattermost.oreillyauto.com/api/v4/websocket?connection_id=&sequence_number=0
2023/09/13 18:51:47:807 DEBUG error on getChannelTimezones Invalid or expired session, please login again.
2023/09/13 18:51:47:809 WARNING An empty "rawValues" array has been passed to the handleRecords method for tableName Config
2023/09/13 18:51:47:904 DEBUG error on fetchMyPreferences Invalid or expired session, please login again.
2023/09/13 18:51:47:904 DEBUG error on fetchStatusByIds Received invalid response from the server.; Request explicitly cancelled.
2023/09/13 18:51:47:905 DEBUG error on fetchMyPreferences Received invalid response from the server.; Request explicitly cancelled.
2023/09/13 18:51:47:912 WARNING An error occurred logging out from the server https://mattermost.oreillyauto.com Received invalid response from the server.; Request explicitly cancelled.
2023/09/13 18:51:47:913 WARNING An error occurred logging out from the server https://mattermost.oreillyauto.com Received invalid response from the server.; Request explicitly cancelled.
2023/09/13 18:51:47:971 WARNING Handling Javascript error Failed updateDraftMessage 0
2023/09/13 18:51:47:971 ERROR Failed updateDraftMessage {
    jsEngine = hermes;
}
2023/09/13 18:51:47:972 DEBUG error on fetchMyTeams Received invalid response from the server.; URLSessionTask failed with error: cancelled
2023/09/13 18:51:47:973 DEBUG error on fetchMyChannelsForTeam Received invalid response from the server.; URLSessionTask failed with error: cancelled
2023/09/13 18:51:47:974 DEBUG error on fetchMe User not found
2023/09/13 18:51:47:974 WARNING An error occurred logging out from the server https://mattermost.oreillyauto.com Received invalid response from the server.; URLSessionTask failed with error: cancelled
2023/09/13 18:51:47:974 WARNING Handling Javascript error cancelSessionNotification 0
2023/09/13 18:51:47:974 ERROR cancelSessionNotification {
    jsEngine = hermes;
}
2023/09/13 18:51:47:974 DEBUG error on fetchMyTeams Received invalid response from the server.; URLSessionTask failed with error: cancelled
2023/09/13 18:51:47:975 DEBUG error on fetchMyChannelsForTeam Received invalid response from the server.; URLSessionTask failed with error: cancelled
2023/09/13 18:51:47:975 DEBUG error on fetchMe User not found
2023/09/13 18:51:47:975 DEBUG Setting the badge count based on database values to 0
2023/09/13 18:51:48:003 INFO Running "Server
2023/09/13 18:51:48:036 INFO Running "Server
2023/09/13 18:51:48:036 WARNING Handling Javascript error TypeError: Cannot read property 'centerChannelColor' of undefined

This error is located at:
    in Server
    in Provider
    in EmmProvider
    in IntlProvider
    in IntlEnabledComponent
    in RCTView
    in Unknown
    in GestureHandlerRootView
    in gestureHoc
    in WrappedComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes 0
2023/09/13 18:51:48:036 ERROR TypeError: Cannot read property 'centerChannelColor' of undefined

This error is located at:
    in Server
    in Provider
    in EmmProvider
    in IntlProvider
    in IntlEnabledComponent
    in RCTView
    in Unknown
    in GestureHandlerRootView
    in gestureHoc
    in WrappedComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes
2023/09/13 18:51:48:036 WARNING Handling Javascript error {
    componentStack = "\n    in Server\n    in Provider\n    in EmmProvider\n    in IntlProvider\n    in IntlEnabledComponent\n    in RCTView\n    in Unknown\n    in GestureHandlerRootView\n    in gestureHoc\n    in WrappedComponent\n    in RCTView\n    in Unknown\n    in RCTView\n    in Unknown\n    in AppContainer";
    isComponentError = 1;
    jsEngine = hermes;
} 1
2023/09/13 18:51:48:075 DEBUG error on fetchUserOrGroupsByMentionNames https://mattermost.oreillyauto.com database not found
2023/09/13 18:51:56:246 INFO Running "Server
2023/09/13 18:52:13:138 INFO Running "Login
2023/09/13 18:52:25:635 INFO websocket connecting to wss://mattermost.oreillyauto.com/api/v4/websocket?connection_id=&sequence_number=0
