### ISSUE TITLE
Automatic update to version 2.8.1 breaks the application work for iPhone 5s

### ISSUE THREAD

**Issue by Zeratyl06** [mattermost/mattermost-mobile#7581]
#### Summary
On iPhone 5s, install the update to 2.8.1. Application won't start.

### Environment Information
  - Device Name: iPhone 5s
  - OS Version: 12.5.7
  - Mattermost App Version: 2.8.1
  - Mattermost Server Version: 8.1.2

#### Possible fixes
Publish version 2.8.0 for iPhone 5s (12.5.7) in the Apple Store and limit compatibility to this version.

**Comment by amyblais** [comment]
@enahum Was this an intentional change? I've opened https://mattermost.atlassian.net/browse/MM-54726.

**Comment by Zeratyl06** [comment]
I saw the changelog, the problem is that the App Store says version 2.8.1 is compatible with iphone 5s (maximum available ios version is 12.5.7) and installs version 2.8.1 (which requires ios version 13.4). After installing version 2.8.1 on iPhone 5s, it is not possible to roll back to version 2.8.0; the application becomes inoperable.

**Comment by amyblais** [comment]
Ah, I didn't realize that the iPhone version is also affected. I'll update docs.

**Comment by Zeratyl06** [comment]
Will it be possible to install version 2.8.0 via the App Store on iPhone 5s devices with iOS 12.5.7?

**Comment by enahum** [comment]
I'll check if I can patch it to work on iOS 12.4 and in that case we could release 2.8.2

But your better alternative is to subscribe to the beta builds with testflight and install 2.8.0 from there listed in the previous builds section

**Comment by Zeratyl06** [comment]
I'll hope for version 2.8.2. Because not all company employees can connect to beta builds.

**Comment by enahum** [comment]
I've been unable to test it on an iPhone 5s as I do not own one but more importantly XCode does not have the Simulators available any more as it reached EOL.. going to try something (that could break my dev environment) to try and add the simulators from an old definition file that I found.

If this does not work, then we will have to come up with a different solution.

@amyblais we should fix 2.9 before releasing so that the minimum OS version is reflected in the App Store to avoid this from happening again

**Comment by amyblais** [comment]
> we should fix 2.9 before releasing so that the minimum OS version is reflected in the App Store to avoid this from happening again

@enahum Are the action items for me, or are you referring to fixing https://mattermost.atlassian.net/browse/MM-54726 for v2.9?

**Comment by enahum** [comment]
@amyblais let's see if we keep the support to iOS 12.4, just need to make sure the app runs without issues but I cannot find a way to test it yet.. we could just cut a build, push it to testflight (external testers) and have someone with an iPhone 5s test out the beta build

**Comment by enahum** [comment]
@Zeratyl06 would you be willing to try out a Beta version that we can publish on TestFlight to see if it works ok? let me know as soon as you can so that I can proceed to publish it. You can enroll in TestFlight by clicking [this link](https://testflight.apple.com/join/Q7Rx7K9P) from your iOS device

**Comment by Zeratyl06** [comment]
Unfortunately, I won't be able to test it. TestFlight is only available on iOS 14 and higher.
![image](https://github.com/mattermost/mattermost-mobile/assets/19567341/b88f54d6-f769-41a3-a1a5-80ea6c62d7bd)

**Comment by Zeratyl06** [comment]
I can try installing a signed .IPA application file via iMazing. If possible.

**Comment by enahum** [comment]
> I can try installing a signed .IPA application file via iMazing. If possible.

do you know if this is a regular app store signature ?

**Comment by Zeratyl06** [comment]
Don't know. Probably yes, because I can save the current version of the application from the App Store to an .IPA file and install it later.

**Comment by enahum** [comment]
Try [this ipa file](https://community.mattermost.com/files/6enfzem7efrkfqaufoq1fhfg9o/public?h=OLaYOQD-z_f3fCE-iqmtXjA2-YwvCmuOiQ7brq_N46E)

**Comment by Zeratyl06** [comment]
Failed with error `A valid provisioning profile for this executable was not found.`

**Comment by enahum** [comment]
weird, as it was build the same way we distribute the app in the app store. So I guess there is no easy way for us to test it.. I have tested in newer OS versions an seems to be working fine, maybe we can risk it but not sure.. @amyblais thoughts?

**Comment by amyblais** [comment]
@enahum It sounds tricky, but since you feel mostly confident, then I have confidence too to move forward.

**Comment by amyblais** [comment]
Queued for v2.8.2 dot release,

**Comment by Zeratyl06** [comment]
Thank you! Works!

**Comment by enahum** [comment]
> Thank you! Works!

Awesome!
