### ISSUE TITLE
Android Bad Image Resolution

### ISSUE THREAD

**Issue by icsarisakal** [mattermost/mattermost-mobile#7596]
If you've found a bug--something appears unintentional--please follow these steps:

#### Summary
Android image view bad resolution

### Environment Information
  - Device Name: OPPO A55
  - OS Version:ColorOS 13.0 / Android 13
  - Mattermost App Version: 2.8.1
  - Mattermost Server Version: 8

#### Steps to reproduce

1. Upload a detailed image like an excel screenshot.
2. Click the photo on chat and view the photos at two phone

#### Expected behavior
- Even if the thumbnails have to be correctly viewed.

#### Observed behavior (that appears unintentional)
- On OPPO, after the opened thumbnails, try zoom and you will see the resolution getting worse
- On Iphone or another phone , after the opened thumbnails, try zoom and you will see the resolution is good.

What did you see happen? Please include relevant error messages, screenshots and/or video recordings.
Same photos as screenshot
- Zoomed On OPPO
![image](https://github.com/mattermost/mattermost-mobile/assets/65347625/4d20805e-a2ec-43c1-932a-979bc701ece7)

- Zoomed On iPhone
![image](https://github.com/mattermost/mattermost-mobile/assets/65347625/24b47a48-4813-49dd-9c05-d570cacab549)

#### Possible fixes
Actually, I don't know 😕

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54859.

**Comment by amyblais** [comment]
Closing older issues as our team hasn't been able to prioritize this,
