### ISSUE TITLE
HPNS Push Notification Issue built for iOS.

### ISSUE THREAD

**Issue by wdkk-kengo** [mattermost/mattermost-mobile#7617]
### Summary
I have built mattermost-mobile ver 2.7.0 ~ 2.9.0. I have encountered a push notification issue with these versions of the iOS builds. Notifications from the self-hosted push notification server (HPNS) are not arriving and the following dialog appears.

~~
Title: Notifications cannot be received from this server
Message: Due to the configuration for this server, notifications cannot be received in the mobile app.
~~

The dialog appears when specifying the server and when opening the workspace after login, with a red alert mark to the right of the server name.

However, **in the same version of the Android App, the HPNS notification is received**. The settings of the connected mattermost server are exactly the same. This leads me to believe that the HPNS push notifications for the iOS App have been disabled for some reason.

And I have confirmed that HPNS notifications succeed on both Android and iOS when using version 1.55.0 of the mattermost-mobile app, so it does not appear to be a push notification server issue.

After some research, I believe that the verification process performed by the v4 REST API of the Mattermost server, such as "ping", is not working properly with mobile app ver 2.7.0 for iOS.

Please let me know if you know how to solve this problem.

### Environment 
- Mattermost Mobile App
  - ver 2.9.0
- Mattermost Server
  - Using docker repository (GitHub - mattermost/docker)
    - Mattermost Version: 9.1.0
    - Database Schema Version: 113
    - Database: postgres
    - with nginx
- Push Notification Server
  - Using HPNS (GitHub - mattermost/mattermost-push-proxy)
  - version 5.26.0
  - Using https

In addition, I have the same question in Forum.
https://forum.mattermost.com/t/hpns-push-notification-issue-using-mattermost-mobile-app-built-by-myself-ios-only/17038

Thanks and best regards.

**Comment by enahum** [comment]
If you build your own copy of the mobile app you'll need to deploy your own push proxy as seen in this doc https://developers.mattermost.com/contribute/more-info/mobile/push-notifications/ios/ and then you should do the same for [android](https://developers.mattermost.com/contribute/more-info/mobile/push-notifications/android/)

**Comment by wdkk-kengo** [comment]
Thank you, @enahum, for your help.

I followed the document you gave me, obtained the Apple push service certificate and Firebase SDK files, installed them on a self-hosted push-proxy server and used them.

In fact, with ver 1.55.0 of the mobile App, I am able to receive push notifications on iOS and Android. Therefore, I believe the notification server is working properly. Or, did ver 2.x or later of the App require different certificates and settings for the push notification server?

Please let me know if there is any mistake. Thank you in advance.

**Comment by wdkk-kengo** [comment]
@enahum 
Yes, we are using the latest (ver 5.26.0) push proxy server currently available on Github. In line with this, we are changing the Key as well as the certificate for iOS and the Firebase API SDK from legacy APIKey for Android.

After setting up, we tested notifications with App ver1.55.0. Notifications were received on both iOS and Android. However, only ver 2.7.0 and 2.9.0 iOS Apps have disabled notifications and do not receive them.

**Comment by enahum** [comment]
When you connect to the server and see the alert, have you check the server and push proxy logs to see if the test notification is being sent? And also check if the logs show that the delivery failed?

**Comment by wdkk-kengo** [comment]
@enahum

Thank you, I have checked the logs of the mattermost and push-proxy servers after trying to connect to the server from iOS ver 2.9.0 and getting an alert, and I see that the ackId is empty when the push-proxy server is trying to do a test notification. The problem seemed to be that the ackId was empty at the time the push-proxy server was about to perform the test notification.
Is the ackId an access token?

I don't know why it is empty, but it could be that the v4 API on the mattermost server is failing to issue an access token, or that the App is failing to pass the token to the pusy-proxy.

Is there anything I can do?

[mattermost server logs]
```
{"timestamp":"2023-10-19 07:45:57.915 Z","level":"warn","msg":"Error while creating session for user access token","caller":"app/session.go:90","error":"createSessionForUserAccessToken: Invalid or missing token., resource: UserAccessToken id: token=dgxftucbtfry9g8ure3qcju9qh"}
{"timestamp":"2023-10-19 07:47:03.391 Z","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:96","worker":"ExpiryNotify","job_id":"w6z7ijr38by88j33qi1d7porjc"}
{"timestamp":"2023-10-19 07:57:11.031 Z","level":"warn","msg":"Error while creating session for user access token","caller":"app/session.go:90","error":"createSessionForUserAccessToken: Invalid or missing token., resource: UserAccessToken id: token=ju7fiskqhbge5dt7q3nq44nghy"}
{"timestamp":"2023-10-19 07:57:11.038 Z","level":"warn","msg":"Error while creating session for user access token","caller":"app/session.go:90","error":"createSessionForUserAccessToken: Invalid or missing token., resource: UserAccessToken id: token=ju7fiskqhbge5dt7q3nq44nghy"}
{"timestamp":"2023-10-19 07:58:03.464 Z","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:96","worker":"ExpiryNotify","job_id":"r3rtbb6qmib7bgzn93kfhq55ur"}
{"timestamp":"2023-10-19 08:09:03.552 Z","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:96","worker":"ExpiryNotify","job_id":"jy8ywt4um3b35gddippo8mukkh"}
```

[pusy-proxy logs]
```
Oct 19 07:45:25 xxx-xxx-xxx-xxx mattermost-push-proxy[553478]: INFO: 2023/10/19 16:45:25 logger.go:59: Sending apple push notification for device=apple_rn type=test ackId=
Oct 19 07:45:25 xxx-xxx-xxx-xxx mattermost-push-proxy[553478]: INFO: 2023/10/19 16:45:25 logger.go:59: Failed to send apple push sending remove code res ApnsID=6EEA0AD7-FDBC-8E9C-C48B-5EB3DC7D548
```

**Comment by enahum** [comment]
The ackId is only needed for message notifications and clear notifications.

The logs on the proxy show that the deviceToken is not valid, so double check your certs and rebuild the app.

You can use iOS Api keys instead of certs if you want, not sure if that is documented

**Comment by wdkk-kengo** [comment]
Thanks for the advice about the log.

I tried changing the push-proxy setting to the iOS Api Key, but it did not solve the problem with app ver 2.9.0. ver 1.55.0 receives notifications, so I think the Api Key is working properly.

By the way, I have enabled "Apple Push Notifications service (APNs)" in the Api Key settings, but do I need to enable other features such as "DeviceCheck"? Do I need to enable other features such as "DeviceCheck"?

**Comment by wdkk-kengo** [comment]
This issue has been resolved. The reason.
It was due to a BadToken error caused by the difference between the development/production version of the device token for push-proxy.

Until mattermost-mobile ver 1.55.x, notifications were sent to the development version of the App even with the production version of the push-proxy token, but since ver 2.7.x, notifications are no longer sent to the development version of the App.

Thank you very much.
