### ISSUE TITLE
Direct Messages do not post if an error is encountered

### ISSUE THREAD

**Issue by ionbasa** [mattermost/mattermost-mobile#762]
#### Summary
DMs that do not post get 'stuck', clicking the error symbol and "try again" does not post the message.
#### Environment Information

- Device Name: iPhone 7
- OS Version:  iOS 10
- Mattermost App Version: 1.0.0 
- Mattermost Server Version: 3.10.0

#### Steps to reproduce
Not sure, a team member notified me of the issue. I think it may happen when a user loses connection or has no reception, thus the message never posts and stays perpetually failed.

#### Expected behavior
DMs that fail to post should properly post when clicking "Try Again".

#### Observed behavior
Screenshot: https://i.imgur.com/zM7VdEn.jpg

#### Possible fixes
Not sure.

**Comment by Hanzei** [comment]
Same for me on Android 7

**Comment by enahum** [comment]
@jarredwitt can you take a look at this?

**Comment by enahum** [comment]
@Hanzei or @ionbasa can you try and get repro steps?

I just tested this and is working fine for me

**Comment by Hanzei** [comment]
I can figure out the exact repro steps out, but the issue happend while I had a bad internet connection and tried to reload a channel

**Comment by ionbasa** [comment]
@enahum I can not reproduce reliably on my end, but the screenshot does show that the issue does exist. Again, I didn't have this problem, but rather a user reported it to me (since I run the mattermost instance on a production server).

I'm not sure what may have caused, but on my particular device, I can try and resend and it works properly, so maybe it is an intermittent issue? Is there anything I can look for in server logs or rather on team members app for more info?

My team member had to delete the whole direct message 'channel' and re-create a new one, at which point it worked properly.

**Comment by enahum** [comment]
Can you ask the teammate to go into settings and the click on report a problem and then send the email?

Maybe we can see something in the app failure logs

**Comment by enahum** [comment]
This thread has been inactive for a while. I'm closing it but feel free to re-open if needed.
