### ISSUE TITLE
There seems to be an issue with video(.mp4) on Ios17.

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#7631]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Bug report in one concise sentence

### Environment Information
  - Device Name: iphone 12 pro
  - OS Version: 17.0.3
  - Mattermost App Version: 2.9.0
  - Mattermost Server Version: 8.1

#### Steps to reproduce
Attach a video.
Press Play or attempt to download the video.

#### Expected behavior
The video should download, play, or preview.

#### Observed behavior (that appears unintentional)
There seems to be a problem with the features listed above for MP4. 

#### Possible fixes
Everything works fine on ios16 devices. My device is also an XR. 
However, there seems to be an issue with video in iOS17. 
The files I've seen are mp4 files, but there may be issues with other video files.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55147.

**Comment by bitdessert** [comment]
@amyblais In iOS 17.0.1, some behavior seems normal. 
But still, sometimes the mp4 file you select in Attach Photo doesn't upload, and thumbnails don't show up for large files.

**Comment by bitdessert** [comment]
@amyblais Everything seems to be fixed in 17.1.  Download, play, and preview all work fine. However, for the preview, it takes 2 download attempts to see the preview, and I checked the cause and it's a permission issue. The authtoken seems to be missing in the header, are there any issues with this? 
The file is located at video_file.tsx and the source code is the following
`const videoUrl = buildFileUrl(serverUrl, data.id!);`

I changed this to 
`const publicLink = await fetchPublicLink(serverUrl, data.id!);  
  const videoUrl = publicLink.link;`

**Comment by bitdessert** [comment]
@amyblais Is it possible to make the video preview visible or invisible on the channel or the direct message itself, depending on your server settings?

**Comment by amyblais** [comment]
I'll let @larkox take a look at these questions.

**Comment by bitdessert** [comment]
@larkox It's hard to tell which settings make such a difference. In the pure version, the default thumbnail resolves the filename, while in the customized version, only the thumbnail is visible. Can you give me a variable name or method to indicate which setting values are affected?

**Comment by larkox** [comment]
@bitdessert If you want to track down the code, the logic is in `app/components/files/file.tsx`. There it decides whether to show it as a video attachment or a file attachment depending on:
- Whether it is a video file (based on the mime)
- Whether public links are enabled

After that it calls some native functions to create the thumbnail.

Regarding the public links enabled variables, it just check the config for `EnablePublicLink`.

**Comment by bitdessert** [comment]
@larkox Thank you. I think this is because the pure server setup has a publicLinkEnabled value of false, and my customized server has a value of true. I think we can fix it so that the thumbnail is not visible regardless of whether it is a public link or not.
