### ISSUE TITLE
Visual Error with Samsung Multi Window View

### ISSUE THREAD

**Issue by PG-Fuury** [mattermost/mattermost-mobile#7633]
The top of the Mattermost window's rendered elements gets an offset that, eyeballed, seems to be as far from the top of the window as the edge of the window from the edge of the screen. Without looking at the code it seems like the app is trying to prevent rendering culled elements by implementing a "blanking interval" at the top, but the window view renders everything into the window.

**Comment by amyblais** [comment]
Hi @PG-Fuury, what Mattermost mobile app version and Mattermost server version are you on? What Samsung version are you using? Can you help share a screenshot of what you're seeing?

**Comment by PG-Fuury** [comment]
Server: WeTalk 8.1.3 hosted by the CAU Kiel
mattermost-mobile 2.9.0 as downloaded from Google Play
Android 13 with OneUI 5.1
![Screenshot_20231027_104254_Firefox](https://github.com/mattermost/mattermost-mobile/assets/32613315/40bae0d8-559c-44c4-9b03-b52cc28aa546)

**Comment by PG-Fuury** [comment]
one thing to note is that the offset gained persists statically through window movement and even leaving windowed mode entirely

**Comment by amyblais** [comment]
Thank you, opened https://mattermost.atlassian.net/browse/MM-55179.

**Comment by larkox** [comment]
@PG-Fuury I have been trying to reproduce, but I have not been able. Any other notes on how I may be able to reproduce this?

**Comment by larkox** [comment]
@PG-Fuury I see it now. For some reason in my device the blanked area is smaller, but hopefully the same root cause.

I will create a help wanted ticket, so if it is something you would be willing to look into, let me know!

**Comment by amyblais** [comment]
A Help Wanted issue was opened here https://github.com/mattermost/mattermost/issues/25452
