### ISSUE TITLE
stuck in channel info window

### ISSUE THREAD

**Issue by shadowwwind** [mattermost/mattermost-mobile#7638]
#### Summary
Clicking the info button at the start of a channel quickly twice opens the menu twice and you can't close it again.

### Environment Information
  - Device Name: Google Pixel 6a
  - OS Version: Android 14
  - Mattermost App Version: 2.9.0
  - Mattermost Server Version: 9.1.1

#### Steps to reproduce
Navigate to the start of a channel (or create a new one) and tap the info button in the chat quickly twice.

#### Expected behavior
Info menu opens once and you can exit it by using androids back navigation or the 

#### Observed behavior (that appears unintentional)
Once the info menu is open twice you can't exit it. Bit with android's back navigation and bit with the close button. The easiest way I found to close it is stopping the app in androids settings.

#### Possible fixes
Only allow one info menu at a time and if the back button leads to the same window that is currently open, make it lead to the previous window instead.

**Comment by harshilsharma63** [comment]
Most likely its missing the `preventDoubleTab` function on that button.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this https://github.com/mattermost/mattermost/issues/25233.
