### ISSUE TITLE
Unexpected keys "analytics", "teamAnalytics" found in previous  state received by the reducer

### ISSUE THREAD

**Issue by ReDetection** [mattermost/mattermost-mobile#764]
#### Summary
Cannot start app, instantly displays error, [nothing more happens](https://user-images.githubusercontent.com/458005/28448208-429d6e78-6e00-11e7-8cf1-ada2192e0775.png) if dismissed. So I can't check #735 anymore

#### Environment Information

- Device Name: iPhone 5s with iOS 10.3 in iOS Simulator Version 10.0 (SimulatorApp-745.10)
- OS Version: Sierra 10.12.5 (16F73)
- Mattermost App Version: master, ef2cddd65dfd29fa7341b35cdb4f84654fc88184 currently
- Mattermost Server Version: 3.10.0  (3.10.2)

#### Steps to reproduce
Build and run app from master

#### Expected behavior
App starts without errors

#### Observed behavior
[Red Yellowbox saying ](https://user-images.githubusercontent.com/458005/28448156-c9eaedfc-6dff-11e7-8bf1-55fbfbbe0261.png)
```
console.error: "Unexpected keys "analytics", "teamAnalytics" found in previous 
state received by the reducer. Expected to find one of the known reducer keys 
instead: "logs", "audits", "config", "complianceReports", "clusterInfo", "samlCertStatus". 
Unexpected keys will be ignored."
```
[Full log in gist](https://gist.github.com/ReDetection/1c6cac405801e783871aa0b97257660c)

**Comment by enahum** [comment]
@ReDetection you will get that error everytime there are changes in the redux store in dev mode but dismissing that error screen should me more than enough, if that is not happening to you even after reloading the app then I'm afraid we need more details from your end

**Comment by ReDetection** [comment]
Apparently, just removing `node_modules` is not enough, `make clean` helped. Thanks!
