### ISSUE TITLE
Cannot copy Text from a Code Block

### ISSUE THREAD

**Issue by theAkito** [mattermost/mattermost-mobile#7659]
#### Summary
Cannot copy text from a rendered code block.

### Environment Information
  - Mattermost App Version: `2.9.0 (Build 48903)` from F-Droid
  - Mattermost Server Version: `9.0.0`

#### Steps to reproduce
1. Send a formatted message like this.
    ````
    ```nim
    echo "Hello World"
    ```
    ````
2. Open the message & this code block.
3. You cannot copy its text.

#### Expected behavior
I can copy the code.

#### Observed behavior (that appears unintentional)
Cannot copy the code.

#### Possible fixes
Make it copyable or at least add a Copy button in the top right corner, just as in the Web UI.

**Comment by enahum** [comment]
You ahould be able to copy the entire code block by long oressing instead of pressing

**Comment by theAkito** [comment]
> You ahould be able to copy the entire code block by long oressing instead of pressing

Okay, now I get it.

I was always opening the code, reading it, then tried to copy it. Never worked. Not even with long press. Just tested again, right now, with the same problem.

Long press only works on the not yet opened code block.

Might this be implemented into the code view, when viewing it full screen?

**Comment by francislavoie** [comment]
+1, this is also a problem I frequently run into. I often get shown a code block and I want to copy a part to edit and reply but not being able to select makes it very tricky to manage because then I need to copy the whole message and remove everything around it instead. Very tedious.

**Comment by francislavoie** [comment]
@amyblais could this get triaged? I think it's not "Awaiting Submitter Action".

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56802.
