### ISSUE TITLE
App crashes when displaying the following table

### ISSUE THREAD

**Issue by sebastian-boecker** [mattermost/mattermost-mobile#7694]
The following table crashes my MM Android app:

| A | B | C | | | 
| :--------------------------------: | :----------------------------: | :----------------- --------------: | :-----------: |:-----------: |
|D | E | F | G | H |
| | J | K | | |

The important parts seem to be a) the blank between the dashes in the second line, and b) the empty last cell. The web-based version also has problems with this table, it does not show anything in the last cell. You can get a slightly different result if you vary the number of dashes, sometimes the Android app simply displays it as text (not a table) instead of crashing.

I am running Android 14 on a Google Pixel 6a. The App version is 2.10.0, server version is 7.10.2.

First time it freezes, if you then restart it you get a long crash report, "maximum regex stack depth reached". After that it freezes again. If you restart one more time, you are back into channel selection.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55972.
