### ISSUE TITLE
App can't connect to server on mobile connection

### ISSUE THREAD

**Issue by TheZoker** [mattermost/mattermost-mobile#7696]
#### Summary
When I try to connect to my mattermost instance on a mobile connection via the app, the app tells me, that the connection failed. 
When I'm on wifi, it works. When I'm on a mobile connection and open my instance within a browser, it works. 
Only mobile connection and app does not work.

I also checked this guide:
https://docs.mattermost.com/deploy/mobile-troubleshoot.html#i-keep-getting-a-message-cannot-connect-to-the-server-please-check-your-server-url-and-internet-connection

But my SSL certificate is fine (provided by Let's Encrypt). For my setup I use a reverse proxy (traefik). 

### Environment Information
  - Device Name: Samsung Galaxy S23+
  - OS Version: Android 14
  - Mattermost App Version: 2.10.1
  - Mattermost Server Version: 9.2.3

#### Steps to reproduce
1. Download app
2. Use mobile connection
3. Connect to server

#### Expected behavior
Work on mobile connection

#### Observed behavior (that appears unintentional)
Error is: Cannot connect to the server

#### Possible fixes
?

**Comment by enahum** [comment]
Havr you checked your server IPv6 support? It may be related

**Comment by TheZoker** [comment]
Thanks for the hint!
Is there any good way to test this? 

If this is the issue, why is there no IPv4 fallback in the app then?
