### ISSUE TITLE
DM Info page shows NaN

### ISSUE THREAD

**Issue by ionbasa** [mattermost/mattermost-mobile#772]
#### Summary
Created a DM with 5 other people, navigating to info screen shows |NaN| in member list

#### Environment Information

- Device Name: iPhone 5s
- OS Version: 10.3
- Mattermost App Version: 1.0 
- Mattermost Server Version: 3.10.0

#### Steps to reproduce
Create DM with 5 other users. Navigate to info screen for DM.

#### Expected behavior
I think it should show the number of users other than yourself?

#### Observed behavior
Shows "|NaN|". Probably due to some variable being not a number but rather a string maybe?

Screenshots:
"|NaN|" on info page: https://i.imgur.com/PeJS741.png
Number of users shown in sidebar: https://i.imgur.com/bXHXaK3.png

#### Possible fixes
Not sure.

**Comment by enahum** [comment]
Thanks @ionbasa for the report, I opened a ticket to fix this
https://mattermost.atlassian.net/browse/RN-281

**Comment by enahum** [comment]
Closed via #775
