### ISSUE TITLE
Feature request: a "Mark read" choice in push notifications

### ISSUE THREAD

**Issue by uusijani** [mattermost/mattermost-mobile#7722]
#### Summary
A "Mark read" choice in push notifications about new messages, as seen in many IM apps, would be handy in Mattermost Mobile too. Currently the message can only be marked read by tapping the message to open the app (which is slow).

### Environment Information
  - Device Name: Samsung Galaxy A9
  - OS Version: Android 10
  - Mattermost App Version: 2.11.0
  - Mattermost Server Version: 9.3.0

#### Steps to reproduce
1. Receive a message notification on the Android app. 
2. Pull down the notifications.
3. Expand the received notification.

#### Expected behavior
Have a "Mark read" option underneath the expanded notification.

#### Observed behavior
No "Mark read" option, only "Reply".

**Comment by uusijani** [comment]
Hi @amyblais,

I could post this on the feature idea forum, but I can't figure out how the signup on the site works. When I click on "Create an account", I get a prompt to verify my email address, and having done that, a page saying "Go back to Production to finish logging in". I don't know what "Production" is, and at no point was there any actual  way to set up a password, so I can't log in.

**Comment by amyblais** [comment]
@uusijani Ah, sorry to hear that. I just tested creating an account with my personal email and I didn't face any issues. Maybe this troubleshooting doc might help https://help.uservoice.com/hc/en-us/articles/360061995974? Perhaps you can try again, or use a different email address if you have another?

**Comment by uusijani** [comment]
@amyblais Alright, I finally managed to get through the signup. [Here's my suggestion](https://mattermost.uservoice.com/forums/306457-general/suggestions/47617325-provide-a-mark-read-choice-in-mobile-push-notifi), although it's in moderation for now.

**Comment by amyblais** [comment]
Awesome!
