### ISSUE TITLE
Feature: Add PIN/PW authentication to app opening

### ISSUE THREAD

**Issue by baek-sang** [mattermost/mattermost-mobile#7723]
Unlock with password, PIN CODE, biometrics (FaceID, fingerprint, etc.) when opening the app

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @baek-sang,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Yes, I'd recommend commenting on Uservoice. Our product teams review feature requests there, but it looks like this particular feature hasn't yet been prioritized on the roadmaps.
