### ISSUE TITLE
2.11.0 APKs can't be downloaded

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#7727]
https://github.com/mattermost/mattermost-mobile/releases/tag/v2.11.0

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>...</RequestId>
<HostId>
...
</HostId>
</Error>
```

**Comment by andyylin** [comment]
I also have this issue.

**Comment by amyblais** [comment]
Opened a ticket for our DevOps team to take a look.

**Comment by amyblais** [comment]
This issue has now been fixed.

Note that there’s one URL which does still not work, the "Mattermost Universal" build, but it was also not working for the previous release, so it seems to be a separate issue. We have opened a separate ticket to fix that.
