### ISSUE TITLE
The search bar moves up. 

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost-mobile#7728]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
The search bar moves up. 

### Environment Information
  - Device Name: galaxy s22
  - OS Version: android 13
  - Mattermost App Version: 2.11.0
  - Mattermost Server Version: 8.1

#### Steps to reproduce
1. Search for anything. 
2. And delete (X button for clear)
3. The search bar moves up.

#### Expected behavior
The search bar should be fixed.

#### Observed behavior (that appears unintentional)
iOS is fixed and immobile.

#### Possible fixes
It seems to be caused by changes in lockValue or header offset.
When searching, ios increases the lockValue and android decreases the locaValue.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56391.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
