### ISSUE TITLE
websocket closed after push notifications

### ISSUE THREAD

**Issue by rguthor2** [mattermost/mattermost-mobile#773]
#### Summary
After tapping a push notification on Android, the websocket connection was closed if the app was left via the home-button before. The websocket connection was not closed if the app was left via the back-button. Same behavior on IOS app.

#### Environment Information
- Device Name: Android + IOS
- OS Version:  Android 6.0.1, IOS 8.3
- Mattermost App Version: 1.0.1
- Mattermost Server Version: 4.0.0 (build 4.0.1)
- Mattermost Push Proxy Version: 3.10.0

#### Steps to reproduce
- Account A: leave app with home button
- Account B: send message to Account A
- Account A receives and displays push notification
- Account A taps on notification
- Account A app is opened, channel with new message is displayed
- Account A websocket is closed
- Account B send new message to Account A
- Account A message only visible after manual reload
Android logcat excerpt:
`I/ReactNativeJS: Running application "Channel" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID7","navigatorID":"navigatorID1_nav","navigatorEventID":"screenInstanceID7_events"},"rootTag":51}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
I/ReactNativeJS: websocket closed`

#### Expected behavior
The app should stay connected after tapping a notification regardless if the app was left by back-button or home-button. 

#### Observed behavior
- when leaving the android app by back-button, it works as expected
- when leaving the android app by home-button, websocket connection is lost
- when leaving the IOS ap by home-button, websocket connection ist lost

#### Possible fixes
As a workaround I deleted the closeWebsocket call in app/screens/channel/channel.js in componentWillUnmount() {
        const {closeWebSocket, stopPeriodicStatusUpdates} = this.props.actions;
        EventEmitter.off(\leave_team\, this.handleLeaveTeam);
        NetInfo.isConnected.removeEventListener('change', this.handleConnectionChange);
        // closeWebSocket();
        stopPeriodicStatusUpdates();
    }

The app behavior is as expected in the above situations, but I'm not sure if this workaround is in the right direction.

**Comment by enahum** [comment]
Hi @rguthor2 

Both Android and IOS apps will close the websocket connection when sending the app to the background, that is the default behaviour of the OS' the only difference between the two is that on Android the app running in the background will leave the WS connection open for a few more minutes.

On Android there is a difference between sending the app to the background with the `Home` button and the `Back` button:
* `Home` sends the app to the background
* `Back` works like you quit the app therefore is "closed"

So it actually is the expected behavior in both cases.

Hope this helps

**Comment by rguthor2** [comment]
That's OK. But the sequence is

- leave the app via the home button
- Device receives the push notification
- user taps on notification item
- app is opened
- the channel is changed according to the notification
- websocketclose is called in componentWillUnmount

If this is the wanted behavior, how will the websocket connection be reestablished?

**Comment by enahum** [comment]
This is working as expected. I'm closing this issue but feel free to re-open if needed.
