### ISSUE TITLE
User filter not working with non-latin names

### ISSUE THREAD

**Issue by bogdanovr** [mattermost/mattermost-mobile#7747]
#### Summary
Mobile app can't find user by typing name in cyrillic.

### Environment Information
  - Device Name: Honor Magic 5 pro / Apple Iphone 15
  - OS Version: Android / IOS
  - Mattermost App Version: 2.11.0
  - Mattermost Server Version: 9.3.0

#### Steps to reproduce
Try enter any non-cyrillic user's first or last name characters.
Web version works better, but can't find user by case insensitive first or last name.

#### Expected behavior
Search the user with any corresponding case insensitive input: first name, last name, ldap login-name/email.

#### Observed behavior (that appears unintentional)
User not found
![photo_5255771001197809624_y](https://github.com/mattermost/mattermost-mobile/assets/15323451/c4d55768-3e1f-4491-95c6-a798d6cb9c78)
![photo_5255771001197809626_y](https://github.com/mattermost/mattermost-mobile/assets/15323451/7edcf009-0b6a-4c2f-813e-7073af6f3528)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56514.

**Comment by amyblais** [comment]
Closing as a Help Wanted issue was opened for this.
