### ISSUE TITLE
2.12.0: Android client fails to display any popovers, like emoji selectors, channel context menu, maybe more

### ISSUE THREAD

**Issue by lkraav** [mattermost/mattermost-mobile#7764]
#### Summary
After 2.12.0 update, emoji icon wouldn't react on any message. Downgrading back to 2.11.0 immediately restored functionality.

### Environment Information
  - Device Name: Xperia 10 III
  - OS Version: Android 11 AOSP
  - Mattermost App Version: 2.12.0
  - Mattermost Server Version: 8.1.6 self-hosted

#### Steps to reproduce
I think just installing 2.12.0 should kill all ability to emoji any messages.
In channel view, vertical "..." context menu also fails to appear.

#### Expected behavior
Popovers are able to appear.

#### Observed behavior (that appears unintentional)
See above.

#### Possible fixes
N/A

**Comment by amyblais** [comment]
Hi @lkraav,
1. Do you see this issue also on our community server https://community.mattermost.com/?
2. Does uninstalling and re-installing the app help at all?

**Comment by lkraav** [comment]
> Hi @lkraav,
> 
>     1. Do you see this issue also on our community server https://community.mattermost.com/?

N/A, but I now signed up on 2.11.0 so I can be ready to test an alternative server in the future.

>     2. Does uninstalling and re-installing the app help at all?

I had to uninstall 2.12.0, and re-installed 2.11.0 fresh. Is there a way to juggle between versions without uninstalls wiping my sign-in info? It's a real pain to sign back into everything.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56582.

**Comment by amyblais** [comment]
> Do you see this issue also on our community server https://community.mattermost.com/? Does uninstalling and re-installing the app help at all?

@lkraav If you're open to testing these scenarios on the Mobile v2.12 version, it would be helpful data.

**Comment by lkraav** [comment]
I ate the :frog: and did the up/down installation + sign-in dance again.

* 2.12.0: Community server 9.5.0 exactly the same result, no popovers appear.
* 2.11.0: Everything works everywhere. (Has worked regression-free through updates for at least a few years straight. :raised_hands: :tada:)

Additionally

* 2.12.0: iOS client popovers seem to work fine.

So this looks like an Android-specific regression :thinking:

**Comment by amyblais** [comment]
Thank you!

**Comment by mkaraki** [comment]
Dear @larkox 

I also has this problem.

Can I send you my logs in community server?

Here is message that I originally posted in [another issue (#7771)](https://github.com/mattermost/mattermost-mobile/issues/7771#issuecomment-1902633236)

Thanks.

> Me too. In my case, I also couldn't open reaction list (Long press reactions) and message menu (Long press messages).
> 
> My Environment:
> 
> * Device: Xperia 5 IV (Japan docomo Edition)
> * Android: 13
> * App version: 2.12.0 (Build 6000499) and 2.12.0 (Build 6000501, Beta Edition)
> * Server version: 9.3.0 (Team Edition), 9.4.1 (Enterprise Edition Free) and 9.5.0 (Enterprice Edition, Mattermost Community Server)

**Comment by larkox** [comment]
@mkaraki Sure, feel free to contact me in the community server :smile:

**Comment by Fischmuetze** [comment]
> Additionally
> * 2.12.0: iOS client popovers seem to work fine.
> 
> So this looks like an Android-specific regression 🤔

Nope! I'm on iOS 17.2.1, App Version: 2.12.0, Mattermost Server Version: 9.2.2 (community) and have the same issues - no popovers, a lot of buttons does not work

**Comment by lkraav** [comment]
> Nope! I'm on iOS 17.2.1, App Version: 2.12.0, Mattermost Server Version: 9.2.2 (community) and have the same issues - no popovers, a lot of buttons does not work

Very interesting, we have the same iOS phone here where everything works. What could be the environment difference?

**Comment by mkaraki** [comment]
@larkox 

In my case:

1. I tried clear storage and re-install stable edition of app from Google Play Store. But not works
2. I also tried Mattermost Beta App from Google Play Store. But it not works.
3. I tried 3 server. Docker's community version, Ubuntu Repo's Enterprise version, and Community Server. all of them are not working
4. From Google Play Store.

**Comment by lkraav** [comment]
> In my case:

All same here.

I also inspected 2.12.0..2.11.0 commit log and literally nothing stood out as a change that could have this effect, but I'm not super familiar with this codebase or packaging pipelines.

**Comment by Fischmuetze** [comment]
For me (iOS 17.2.1, App Version: 2.12.0:

1 .
The issue appeared with the last update App Version: 2.12.0 on the Apple iOS App Store
Installation and reinstallation did not help. Since I'm looking more or less daily for updates I'm sure the issue appears only with the last update.

My original installation was configured for accessing two servers 

a)
Mattermost Version: 9.2.2
Database Schema Version: 113
Build Number: 6801073174

b)
Enterprise
Mattermost-Version: 8.1.7
Database Schema Version: 113
Build-Nummer: 7025434773

After uninstalling and installing again it's not longer possible to configure a second server so that I'm using currently only server a)

2.
Not sure what you mean 

3.
From the Apple iOS App Store

**Comment by mkaraki** [comment]
In my Android, I set `Window animation scale` and `Transition animation scale` in developer option to `x1` (it must be default) and resolve this issue.

**Comment by Fischmuetze** [comment]
me: 
By default I“m using the setting reduced animations in iOS Accessibility. Setting this to the default -> full animations is removing the issue after restarting the app. 

Cheers
Steffen

> Am 23.01.2024 um 09:43 schrieb Daniel Espino García ***@***.***>:
> 
> Is there any chance anyone else suffering of this problem has some accessibility animation setting different from the default? I was able to reproduce in both iOS and Android by "removing the animations" options, but I want to verify this is the root cause for everyone.
>

**Comment by felibb** [comment]
Disabling **Reduce Motion** and relaunching the app fixed the symptoms on iPhone 17.2.1. Re-enabling the setting brought the symptoms back. iPhone is unusable to me in this state however, reduced animation is an important feature to me.

As an experiment, I tested 2.12.0 fresh install, it works perfectly fine on an iPad Pro with iOS 17.2 and Reduce Motion enabled. Unlike my iPhone, the iPad never had MM app installed, which may or may not make any difference.

**Comment by davirond** [comment]
I confirm the workaround (disabling reduce motion) works on iOS 15.8 / app 2.12.0 (tested with servers on 9.3.0 and 8.1.6).

**Comment by cathya57** [comment]
I also confirm the workaround on iOS 17.3 with MM 2.12.0

After the MM update, I could only access the last server I had been using - I wasn't able to switch between them using the filebox icon top left as usual (I don't know if it's a filebox - it's what my ancient eyes perceive it as, but it might be a rack of servers?).

If I clicked on either that 'switch servers' icon or the "+" symbol, nothing happened other than a sort of screen flick that went nowhere (as if the app was trying to give me access to something, but failing).

When I logged out of that one server I could access, MM took me into the logged-in chat in one of the other two.  Logging out of that one took me to the third.  Logging out of that one took me to a screen where I had to set up a new server from scratch (I logged into the one I use the most often).  Still the same symptoms however - just not possible to switch servers.

I tried the workaround - disabled reduce motion - restart MM app.

Now it all works again - and also had 'remembered' my three servers.  I've logged into all three and all is good - although I really would like to reenable reduce motion!

**Comment by larkox** [comment]
I pushed a PR that I expect will make it to 2.13.

This PR makes so the bottom sheet still shows animations. I know that is not the best, and I hope we can spend time addressing this in a proper way.

Also, I would appreciate that if you see any other weirdness around animations when using these settings you create a ticket. We will look into it :smile:
