### ISSUE TITLE
Word plugins in path of an external link

### ISSUE THREAD

**Issue by Sadisms** [mattermost/mattermost-mobile#7768]
#### Summary
When you click on an external link that has path /plugins/, it takes you to add new MM server window.

### Environment Information
  - Device Name: all
  - OS Version: all
  - Mattermost App Version: 2.12.0
  - Mattermost Server Version:  9.3.0 self-hosted

#### Steps to reproduce
Send a message with a link with plugins path (for example: http://test/plugins/test). Click on link.

#### Expected behavior
I'd like to open link in browser.

#### Observed behavior (that appears unintentional)
In description.

#### Possible fixes
Didn't find it.

**Comment by amyblais** [comment]
@Sadisms Are you able to reproduce this issue on our community server https://community.mattermost.com/?

**Comment by Sadisms** [comment]
Hi, @amyblais, the problem is also present on your server. I understand the mobile client does not see in the list of servers with the server with the link domain and offers to add it, because of /plugins/ it thinks that this link is for a plugin of another MM server. 

https://github.com/mattermost/mattermost-mobile/assets/63108004/e1d3e11b-cd27-434b-a068-f2482f3835d8

**Comment by amyblais** [comment]
Thank you, opened https://mattermost.atlassian.net/browse/MM-56592.
