### ISSUE TITLE
Breaking change in version 2.12.0 hinders communications with non-HTTPS servers

### ISSUE THREAD

**Issue by TheIdiom** [mattermost/mattermost-mobile#7800]
#### Summary
The change introduced in commit [edef4ec](https://github.com/mattermost/mattermost-mobile/commit/edef4ec4a3f3676a061a615c4b9e18cb83681473) breaks communications with non-HTTPS servers by changing the value of "NSAllowsArbitraryLoads" to **false** in `Info.plist`.   If this change was intentional we can no longer use Mattermost in our organization and it should have been made prominent in the Release Notes.

### Environment Information
  - Device Name: N/A
  - OS Version: **iOS 17.3**
  - Mattermost App Version: **2.12.0**
  - Mattermost Server Version: **9.4.1**

#### Steps to reproduce
Using any Mattermost iOS client later than 2.12.0 try to connect to a server that is NOT utilizing HTTPS.

#### Expected behavior
It used to, always has, and always should work unless a "ONLY HTTPS from now on" decision has been made, in which case that should have been made public.

#### Observed behavior (that appears unintentional)
The app will appear to connect but no messages can be retrieved or sent, but the notifications still work (since the **NotificationService** module did not get this change).

#### Possible fixes
Change "NSAllowsArbitraryLoads" back to **true** in the `Info.plist` file.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56725.
