### ISSUE TITLE
Can't connect to https instance (PS version 1.0.1)

### ISSUE THREAD

**Issue by PipoloyJo** [mattermost/mattermost-mobile#782]
Hi,

I am trying to connect to our new https mattermost instance running Version : 4.0.0  (4.0.1).
I am using the RN Android app and I am stuck on the Server URL screen (MainActivity from what the adb logcat suggests). Here are some lines from logcat that shows an error but I don't think it is related:

```

07-25 11:44:37.383 14210 14228 I ReactNativeJS: Running application "Root" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID2","navigatorID":"navigatorID1_nav","navigatorEventID":"screenInstanceID2_events"},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
07-25 11:44:37.465 14210 14228 I ReactNativeJS: Running application "SelectServer" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID3","navigatorID":"navigatorID1_nav","navigatorEventID":"screenInstanceID3_events"},"rootTag":11}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
07-25 11:44:37.529 14210 14229 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
07-25 11:45:44.429 14210 14838 I WebViewFactory: Loading com.google.android.webview version 59.0.3071.125 (code 307112500)
07-25 11:45:44.554 14210 14838 I asset   : Successfully loaded resource /system/framework/oxygen-framework-res.apk
07-25 11:45:44.628 14210 14838 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
07-25 11:45:44.640 14210 14838 I cr_LibraryLoader: Time to load native libraries: 0 ms (timestamps 7923-7923)
07-25 11:45:44.666 14210 14838 I chromium: [INFO:library_loader_hooks.cc(144)] Chromium logging enabled: level = 0, default verbosity = 0
07-25 11:45:44.667 14210 14838 I cr_LibraryLoader: Expected native library version number "59.0.3071.125", actual native library version number "59.0.3071.125"

```

I am not the only one experiencing this issue on Android (version 1.0.1 of app com.mattermost.rn) in my company.

I'll try to compile and run the app to see if I get more info.

**Comment by lfbrock** [comment]
Thanks @PipoloyJo, any more info you have would be great. 

Do you get any errors shown in the UI for the Server URL screen, or does it just not work?

**Comment by PipoloyJo** [comment]
I see a red error label below the 'Proceed' button.

> Cannot connect to the server. Please check your server URL and internet connection

Which I did of course.

**Comment by PipoloyJo** [comment]
We have solved this issue; this was due to a wrong SSL certificate configuration. It was not obvious at first since, the web and iOS app were working fine. Seems like Android is less cooperative.

Maybe the error message could be more more specific to point in the right direction faster. But it may not be possible depending on the error you receive from your network stack.

**Comment by lfbrock** [comment]
Thanks @PipoloyJo glad you got it sorted out, I'll talk to the team and see if a better error message is possible here, or at the very least better troubleshooting docs for people who hit similar issues.

**Comment by enahum** [comment]
Yes the error returned by this is **Network Failure** so it will be even less specific, we should add this to the troubleshooting section in the docs

**Comment by lfbrock** [comment]
Updated troubleshooting section here for now, open to feedback: https://github.com/mattermost/mattermost-mobile/pull/836

Will move to docs.mattermost.com soon as well

**Comment by enahum** [comment]
This thread has been inactive for a while. I'm closing it but feel free to re-open if needed.
