### ISSUE TITLE
Password input is not "private" on phone keyboard

### ISSUE THREAD

**Issue by lolcabanon** [mattermost/mattermost-mobile#7820]
The password input for login to a server act like a simple text input for my keyboard. In other apps (or in browser incognito mode) the keyboard switch to "private" mode when I enter a password. This means that autocompletion does NOT record what I enter to suggest it later.

Now if I sign in in the Mattermost app, my password gets **saved as a suggestion**. That means if I type the first characters, **I can see my whole password in plaintext**, and it is also probably (definitely) shared also in plaintext to whoever is the developer of my keyboard. (I use SwiftKey, shame on me, so Microsoft has it. Plot twist, they probably already had it, but thats not a reason to send it once again, unencrypted.)

I might be wrong, but I am pretty confident that this is controlled by the app itself. Most of the apps I use have the desired behavior.

# versions

Version de l'application : 2.12.1 (Build 6000505)
Version du serveur : 9.3.0 (Build 7014621505
Base de données : postgres
Version du schéma de base de données : 114

**Comment by amyblais** [comment]
What OS and version are you using?

**Comment by lolcabanon** [comment]
Android 10

**Comment by marianunez** [comment]
@lolcabanon I'm on Android as well and I see the password input masking properly the password. Can you share what you are experiencing (screenshot or video)?

![Screenshot_20240220_134122_Mattermost](https://github.com/mattermost/mattermost-mobile/assets/936315/446ee17f-9ac7-4767-b611-e996562f41e9)

**Comment by lolcabanon** [comment]
@marianunez Hello! Thanks for the follow-up.

The password input is masking properly indeed. The problem is with the "keyboard mode" I would say.

In many other apps, when I enter a password, my keyboard "detect" that it is writing in a private field, and activate "private mode". While in private mode, it stops recording typing data for typing suggestion.

If the "private mode" of my keyboard does not trigger (as this is the case with Mattermost app), my keyboard will register my input and suggest it later. So for example, if my password is "MyVeryStrongPa$$word" and I log in to Mattermost app, as soon as I will type "my" in any other text field on my phone, the autocorrect will suggest "MyVeryStrongPa$$word" as a known word.

As I stated earlier, I am not 100% sure if it has to do with the actual implementation, the library used to create the app or the system itself, but I mainly wanted to raise the issue in case it can be solved on your end.

I will send screenshots shortly. :)

**Comment by lolcabanon** [comment]
Ok I just realised something : in the Mattermost app, the password suggestion happens only when the password is **not** masked (i.e. when I click the eye icon).

However, it does not happen in the browser with an `<input type="text" name="password" />` (password input turned into a text input with js to reveal password). (I know how the code behave as I coded the login form you will see in the screenshots myself.) 

See screenshots below :

Expected behavior :

![Screenshot_20240220-205815__01__01.jpg](https://github.com/mattermost/mattermost-mobile/assets/90099349/5f7e8a4b-5157-49a4-b342-14e072729d53)

![Screenshot_20240220-210004__01__01.jpg](https://github.com/mattermost/mattermost-mobile/assets/90099349/0179c711-50ed-414a-96cc-aa2da5f56806)

Mattermost :

![Screenshot_20240220-211435.jpg](https://github.com/mattermost/mattermost-mobile/assets/90099349/2665ab15-dcad-4e9b-917f-982d844aebfc)

![Screenshot_20240220-211440.jpg](https://github.com/mattermost/mattermost-mobile/assets/90099349/014d00b6-ad3a-435c-bc26-79e40a2b496c)

**Comment by lolcabanon** [comment]
Maybe the Mattermost app is not the faulty one. I was just shocked that my password appeared in my keyboard suggestion after logging into Mattermost, so I checked the app and saw that.

I'll let you judge if it needs more attention. Feel free to close the issue if you don't feel you can make this better.

Cheers ✌️

**Comment by lolcabanon** [comment]
Thanks! Have a good day :)

**Comment by DSchalla** [comment]
@lolcabanon Removing this public issue while we triage it internally as it may fall under our responsible disclosure policy. Feel free to reach out to responsibledisclosure@mattermost.com or our HackerOne program so that we can keep you updated on this issue.
