### ISSUE TITLE
Notification do not show up.

### ISSUE THREAD

**Issue by fachex** [mattermost/mattermost-mobile#783]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Notification will not show up on the notification tray on top. They, at times, show up as a number on the icon.

#### Environment Information

- Device Name: Samsung Galaxy Note 5
- OS Version: Android 7.0
- Mattermost App Version: 1.0.1 (Build 41) 
- Mattermost Server Version: 4.0.0 (Build 4.0.1)

#### Steps to reproduce
Just sent a message to the user of this device.

#### Expected behavior
A notification (sound and display) should ring/show up.  

#### Observed behavior
Notification does not show up. I have to say that It could be that the btrfs system issues and also because this VM is in a NAS and it is awful slow.  

#### Possible fixes
I will move my VM to a SSD storage to see if that improve that speed and solve this problem.

**Comment by fachex** [comment]
Yea, I just moved the server to an SSD storage. Mattermost is under a container in Cloudron.  All is working well, except NO notification in the "Shade" or "tray". I tested in a Samsung Galaxy Note 5 and a Moto Z both ander Verizon. No luck.

**Comment by fachex** [comment]
Another thing is that the app doesn't seem to stay in the background but it closes when focus is switched.

**Comment by lfbrock** [comment]
Hi @fachex - are there any errors in the server logs about push notifications? 

Can you also share the push notification settings for: 

1) The server - are you using your own push notification server, or one of ours? (eg push.mattermost.com)

2) Your notification settings: 
<img width="400" alt="screenshot 2017-07-26 16 41 31" src="https://user-images.githubusercontent.com/9354841/28648256-5aa8365e-7221-11e7-96d9-62cd4bcba17d.png">

3) Your phone - did you receive a prompt for allowing notifications? Can you check the phone settings to confirm if the app has permission?

**Comment by enahum** [comment]
Maybe check the server logs to see if the push notifications are being sent

**Comment by fachex** [comment]
You hit in the target @enahum. mattemost is installed in a container via Cloudron.  I spoke with Cloudron engineers and didn't know that they shipped the container  with push notification disable (false). But when I tried to enable the container doesn't work at all. I guess it's because it is missing the notification server. I didn't figure it out how to set that up yet. Can anybody point me to the right documentation? 
Thanks!

**Comment by enahum** [comment]
take a look at this to see if that help https://docs.mattermost.com/administration/config-settings.html#mobile-push

**Comment by enahum** [comment]
This thread has been inactive for a while. I'm closing it but feel free to re-open if needed.
