### ISSUE TITLE
Enter key on hardware android keyboard does not post message

### ISSUE THREAD

**Issue by estama** [mattermost/mattermost-mobile#784]
#### Summary
Enter key on hardware android keyboards does not post messages. Right now enter key changes line **inside** the message which is not useful at all while in conversations. 

#### Environment Information

- Device Name: Google Pixel C + Keyboard
- OS Version:  Android 7.1.2
- Mattermost App Version: Latest Mattermost Android client as well Latest Mattermost Beta Android
- Mattermost Server Version: 4.0

#### Steps to reproduce
In Android, try to post a message using enter hardware keyboard key. You'll need a hardware keyboard to replicate.

#### Expected behavior
Enter should post the message and Shift-Enter should change line inside the message (like on desktop clients)

#### Observed behavior
Android hardware keyboard Enter key changes line inside a message. Shift-Enter does the same.

**Comment by lfbrock** [comment]
Hi @estama thanks for the feedback - I'm not sure if we would be able to detect which devices have a hardware keyboard or not to control this setting, would you have any thoughts on how to approach that? 

Otherwise maybe we should consider making it shift enter for all mobile devices, or having a setting users can use to control what enter does.

**Comment by enahum** [comment]
This thread has been inactive for a while. I'm closing it but feel free to re-open if needed.

**Comment by erinarbleizez** [comment]
hi,

I would like to reopen the ticket because the problem is present on Samsung Dex... The app work fine on Samsung Dex except for the enter key :'(

**Comment by estama** [comment]
I think that using the same actions that other mobile chat clients use (e.g skype) where enter posts and shift-enter changes line makes sense. 

Enter posting as a default action makes sense. The great majority of the time one wants to post compared to changing line which happens very infrequently. So by default coupling post action to Enter makes sense on either soft- or hardware keyboards. 

In any case, at least allow an option to toggle between Enter posting or changing line, so that Mattermost becomes usable on mobile platforms. You can even do a poll to see which action users would prefer to be a default for Enter.

**Comment by estama** [comment]
Please reopen the ticket, it was closed due to one (summer) month's inactivity. This is too short of a duration to close a ticket for inactivity.

**Comment by Maxim-Filimonov** [comment]
Same problem here. Neither shift or alt enter work - forced to use my fingers to touch the button
Device Name: Apple iPad 12.9" + Apple Smart Keyboard
OS Version: 11.2
App Version: 1.7.0(88)
Mattermost Server Version: 4.8

**Comment by lindy65** [comment]
Hi @estama @erinarbleizez @Maxim-Filimonov 

If one of you or anyone in the community is interested in submitting a pull request for this feature, we'd welcome your help!

**Comment by Maxim-Filimonov** [comment]
I can have a look at it when i'm back from my trip on 28th. Unless someone else is keen to jump in before that.

**Comment by lindy65** [comment]
Thanks @Maxim-Filimonov !

That will be great!

**Comment by lindy65** [comment]
Hi @Maxim-Filimonov 

Hope you had a good trip!?  Have you had time to look at submitting a pull request for this feature?

**Comment by Maxim-Filimonov** [comment]
Hey, sorry didn't have a chance. Our instance of mattermost is shutdown now as I'm not sure how to even test it anymore. We have switched to telegram for simplicity sake.

**Comment by lindy65** [comment]
Hi @Maxim-Filimonov 

Thanks for letting us know and sorry to hear you're not using Mattermost anymore...

@enahum - should we open a Jira tix to look at implementing this some time in the future?

**Comment by enahum** [comment]
Perhaps best to ask @esethna about this

**Comment by esethna** [comment]
Thanks @lindy65, yes let's open a ticket for this and queue for triage.

**Comment by lindy65** [comment]
Ticket here: https://mattermost.atlassian.net/browse/MM-10601

**Comment by amyblais** [comment]
Hi @estama and everyone!

We have created a [Help Wanted issue here](https://github.com/mattermost/mattermost-server/issues/8797) and are looking for community's help. Would you be interested helping with a pull request?
