### ISSUE TITLE
Messages order is mixed-up when server time and client time differ

### ISSUE THREAD

**Issue by kemenaran** [mattermost/mattermost-mobile#785]
#### Summary

When the phone time is a bit late relative to the Mattermost server time, messages posted from the phone appear in the past, above the last message and among other messages. This often cause the recipient not to read the message at all.

#### Environment Information

- Device Name: iPhone
- OS Version: iOS 10
- Mattermost App Version: 1.0.1
- Mattermost Server Version: 4.0.1

#### Steps to reproduce

1. Set the phone time to be a few minutes late relative to the server time (e.g. if the time on the server is 10:00 am, set the phone time to 9:57 am).
2. From Mattermost on the **web**, post a message "A" on a public channel
3. Then from Mattermost on the **phone**, post a message "B" on the same public channel

#### Expected behavior

- The message "B" should be displayed after the message "A" (as it was sent later).
- The message "B" displayed timestamp should be the time of the server (as the server time is the only central authority for time).

#### Observed behavior

- The message "B" is displayed above the message "A".
- The displayed time of message "B" is the time as it was on the phone – which means if clients disagree on the exact time, the message order will be wrong.

#### Possible fixes

I don't know exactly what causes the issue – but what is sure is that all times ever handled should be given by the server, and not provided by the clients (which may be unreliable and disagree between each others).

For instance the message time could be updated on the client once the server acknowlegement is received.

**Comment by kemenaran** [comment]
The offending code is probably this one : https://github.com/mattermost/mattermost-redux/blob/master/src/actions/posts.js#L23-L31

It seems that here the client itself sends the `created_at` timestamp. Instead the `created_at` value should be left blank by the client in the request, and updated later with the value provided by the server in the response data.

**Comment by lfbrock** [comment]
Hi @kemenaran - is the account that this is happening to System Admin on the server? 

I filed a ticket here for the bug: https://mattermost.atlassian.net/browse/RN-286

**Comment by kemenaran** [comment]
@lfbrock yes, the account this is happening to is System Admin on the server indeed.

Is that related?

**Comment by enahum** [comment]
It is related but is being fixed for the next build

**Comment by lfalkenburg** [comment]
Environment Information

Device Name: iPhone
OS Version: iOS 10
Mattermost App Version: 1.0.1
Mattermost Server Version: 4.0.1

Its not only an iOS matter - we realized the same on the Desktop-/Webclient today.

**Comment by mmarif4u** [comment]
We also noticed this on our tests today on Android client. Where the messages are mixed up and hard to find the new message sometime.

Any possible release time for this issue?. seems to be a showstopper.

**Comment by enahum** [comment]
Have you tried app 1.1 and server 4.1?

**Comment by lfalkenburg** [comment]
I realized, it was a timeissue but from the client side. After time on all clients were corrected everything worked fine.

Irrsinnige Grüße
Lutz Falkenburg

Von unterwegs gesendet

**Comment by mmarif4u** [comment]
@enahum we have 1.1 and 4.1 now, seems to be no issue on Android so far.

**Comment by kemenaran** [comment]
@enahum I have 1.1 on iOS and 4.1 on the server, and the issue seems to be fixed. When one of the device is not perfectly synchronized with the server time, the message sent is adjusted to the server time when the server response is received (I can see the displayed time changing slightly). Which means the messages are displayed in the correct order 👍

**Comment by enahum** [comment]
So it looks like this is solved then, going to close the issue.

Feel free to re-open if needed.
