### ISSUE TITLE
iOS app: image upload missing a preview

### ISSUE THREAD

**Issue by felibb** [mattermost/mattermost-mobile#7853]
#### Summary
When uploading an image either via gallery picker or pasting to input field, no preview is generated.

### Environment Information
  - Device Name: iPhones 13 Pro
  - OS Version: 17.3.1
  - Mattermost App Version: 2.13.0 (Build 507)
  - Mattermost Server Version: 8.1.8 (Build 7225530887
 - Database: postgres
 - Database Schema Version: 113

#### Steps to reproduce
 * disable "Reduce motion" setting in the phone's accessibility settings
 * open any channel in Mattermost
 * tap image picker, select image from gallery, tap Add
 * "Send" button becomes active.

#### Expected behavior
A tiny image preview is displayed near text input field to indicate that an image has been attached, and is waiting to be sent.

#### Observed behavior (that appears unintentional)
The screen blinks for a second, the input field says "Write to [channel name]", no preview is visible, therefore no indication that there is an image to be sent besides the now-active "Send" button.

#### Notes
This definitely used to work properly. Might have started with that hot fix version released a while ago (for broken emoji reactions and server switching), but I don't remember 100%. Happened after reinstalling on aforementioned iPhone, on freshly installed testing iPhone 6s Plus / iOS 15.8.1, and on random user devices within our organization.

**Comment by amyblais** [comment]
Hi @felibb, I wasn't able to reproduce this just now. Are you able to reproduce this on our community server here https://community.mattermost.com/? Are there any errors in your server's logs?

**Comment by felibb** [comment]
@amyblais yep, see https://community.mattermost.com/core/pl/fnd5zc7ahbdj9des496eiibhhh (tagged you there as well).

I think it has been dragging on even after #7764, and the fix/PR 7786 did not fix it everywhere. Acceptable for a hot fix, but a little sloppy for a long-term solution IMO.

**Comment by amyblais** [comment]
Thanks, I'll ask the team to try reproduce this. I wasn't able to reproduce with the "Reduce motion" setting enabled or disabled, maybe it has to do with my OS version (iPhone 13, not Pro).

**Comment by felibb** [comment]
One intermediate action that might make a difference when reproducing is to force quit the app (via the app switcher) between toggles of "Reduce motion".

**Comment by amyblais** [comment]
@felibb A note from our team: this reproduces when creating a photo as raw, and sharing it into a channel from photos. There is no preview, but that would be expected as it is a RAW image (.dng in this case).

**Comment by felibb** [comment]
@amyblais I don't even use RAW. Definitely tested with a JPEG file, but HEIF (default iOS photo format) also works, but only with disabled "Reduce motion" setting. Did they test with server 8.1.8 by the way? Maybe the reason is there.

Anyway we cannot possibly try every setting and format combination, and figure out how to make the app work again the way it used to work, don't have time for this, sorry. The QA team, not users, should hunt for edge cases like this. If they cannot reproduce, well, too bad for us, feel free to close the issue. Maybe it will disappear once we upgrade the server to 9.5.

**Comment by amyblais** [comment]
Thank you, I've shared your feedback with the team. I'm sorry that we've had trouble reproducing this. We haven't tested this specifically on a v8.1.8 version since you had reproduced the issue on our community server (which is running on the latest version).

**Comment by amyblais** [comment]
Good news! Another teammate was able to reproduce it. Opened https://mattermost.atlassian.net/browse/MM-57114.
