### ISSUE TITLE
Portrait -> Landscape Rotation is not working properly

### ISSUE THREAD

**Issue by halb9** [mattermost/mattermost-mobile#786]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Portrait -> Landscape Rotation is not working properly

#### Environment Information

- Device Name: Samsung Galaxy S5 klte
- OS Version: LineageOS 14.1-20170719-NIGHTLY-klte
- Mattermost App Version: 1.0.1 (Build 41)
- Mattermost Server Version: 4.0.0 (Build 4.0.1)

#### Steps to reproduce
When I'm in portrait mode I turn my phone to landscape mode. But mattermost does not recognize it and stays ins portrait mode. 

#### Expected behavior
Turn to landscape mode. 

#### Observed behavior
The only way to trick mattermost is by switching to another app which has no problems with landscape (VLC in this example). You then turn your phone to landscape, VLC recognize it and turns as well. While beeing in landscape you then switch back to mattermost. 
I have this Problem with two phones (the other is a Galaxy S4 Intl). 
Both are running LineageOS. 14.1-20170719-NIGHTLY at time of writing to be exact. A colleague of mine has the same problem. He is running LineageOS as well. Don't know the version though. 
Others seems to have no problems with landscape. As far as I can tell they're not running LineageOS. 

If you imagine holding a phone in your hands it would look a bit like this. 

![01](https://user-images.githubusercontent.com/18451020/28621633-e17d7398-7211-11e7-94bb-4d902d07a09a.png)
![03](https://user-images.githubusercontent.com/18451020/28621640-e83c472c-7211-11e7-9a06-c8f6b6ad7f68.png)
![04](https://user-images.githubusercontent.com/18451020/28621641-e85b0bf8-7211-11e7-9914-68714e2b05d1.png)
![05](https://user-images.githubusercontent.com/18451020/28621642-e85ce2a2-7211-11e7-9e39-3a5c6da55f32.png)
![06](https://user-images.githubusercontent.com/18451020/28621643-e85d64b6-7211-11e7-97c2-8f4e1b6d43d5.png)
![07](https://user-images.githubusercontent.com/18451020/28621644-e85d9f94-7211-11e7-89bd-29da2a02f436.png)

#### Possible fixes
It looks like it has something to do with LineageOS. I try to find a phone with Stock ROM to test it.

**Comment by lfbrock** [comment]
Hi @halb9 - we have landscape mode disabled right now, we'll need to test landscape view thoroughly, and then fix a few bugs with the rotation before we enable it. 

Would you be interested in helping would you be interested in helping contribute fixes for that?

**Comment by halb9** [comment]
I'm more than happy to help by testing and submitting detailed bug reports. 
I'll have to pass on the coding part since I have no experience whatsoever unfortunately. Sorry.

**Comment by enahum** [comment]
Closing as this feature is yet to be implemented, feel free to re-open if needed.
