### ISSUE TITLE
Unable to connect to the voice call: timed out waiting for peer connection

### ISSUE THREAD

**Issue by iamsadjad** [mattermost/mattermost-mobile#7889]
#### Summary
Getting an error when starting a call

### Environment Information
  - Device Name: Samsung A54
  - OS Version: Android 14
  - Mattermost App Version: 2.14.0
  - Mattermost Server Version: 9.6.1

#### Expected behavior
This error is displayed when I start calling in the mobile application:
`ERROR: Unable to connect to the voice call: timed out waiting for peer connection`

#### Observed behavior (that appears unintentional)
![Screenshot_20240331_132520_Mattermost](https://github.com/mattermost/mattermost-mobile/assets/151030813/26deccb1-59d1-4cfc-8912-6646095c5b79)

#### Possible fixes
This problem did not exist on another mobile phone with Android 9 and Mattermost version 2.10.0

**Comment by amyblais** [comment]
Hi @iamsadjad, would you be open to re-creating this issue in the Calls repo here https://github.com/mattermost/mattermost-plugin-calls/issues?

**Comment by amyblais** [comment]
Does the solution posted here help https://github.com/mattermost/mattermost-plugin-calls/issues/451#issuecomment-1672116187?
