### ISSUE TITLE
Calls not enabled

### ISSUE THREAD

**Issue by spbdimka** [mattermost/mattermost-mobile#7893]
### Environment Information
  - Device Name: ios/android
  - OS Version: avtual
  - Mattermost App Version: 1.24.0
  - Mattermost Server Version: 9.6.0

#### Steps to reproduce
Try to init voip call

#### Expected behavior
voip call. while official app from appstore can make calls connected to my self-hosted server, calls plugin enabled and i can call via browser

#### Observed behavior (that appears unintentional)
Error "Calls not enabled"

Maybe i missed any parameter due building apps or calls plugin answers incorrect (can i test it by curl some context?)

**Comment by amyblais** [comment]
Hi @spbdimka, would you be open to re-creating this issue in the Calls repo here https://github.com/mattermost/mattermost-plugin-calls/issues?
