### ISSUE TITLE
Android client showing "Invalid SSL certificate" with https server on non-standard port.

### ISSUE THREAD

**Issue by cball01** [mattermost/mattermost-mobile#7894]
Android 14.0
App 2.14.0
Server 9.4.1

I'm running the server on port :444, the android client is telling me that I have an invalid cert (3 different android phones tested)
Chrome and Firefox* on the phones have no issue with the certificate, nor do those browsers on windows, linux or the respective desktop apps on those OSes.  If the android client is using a different CA from everything else, the port thing could be a red herring but it seems edge casey and the android app is the only thing I can find that is mad about the certificate.  Popup box tells me I'm at risk and allows no way to carry on regardless.

*firefox only tested on one phone.

Certificate issuer is ZeroSSL retrieved from Let's Encrypt.

**Comment by enahum** [comment]
Have you checked if your cert chain is complete? Maybe check ssllabs.com

**Comment by cball01** [comment]
ssllabs doesn't seem to like non-standard ports and points me to some paid service or at least something that wants to harvest my email addr.

www.sslshopper.com works with non-standard ports and seems fine with the caveat that there could be some browsers where I need an intermediate chain certificate.  That seems out of my pay grade and really a zerossl/letsencrypt issue.

Certainly the various desktop clients are happy as are chrome/firefox across the board.

**Comment by enahum** [comment]
Well the app also needs the intermediate chain to be set in order to get rid of the warning

**Comment by cball01** [comment]
So the app is using a different CA list than chrome and Firefox on Android?  I'm by no means an ssl expert or an android one for that matter but I thought the OS supplied the certificate management on android (settings->security and privacy->more security settings->view security certificates) so if one thing worked they all should, should they not?

The cert chain chrome shows on android is:  mysite -> zeroSSL ECC Domain Security Site CA -> USERTrust ECC Certification Authority.

**Comment by enahum** [comment]
Is not about a different CA, is about your SSL cert not being fully trusted as is missing a part. You should configure your webserver to serve the fullchain.pem instead of the cert.pem

I believe there are many results about how to do this with a quick web search or in the let's encrypt forums

**Comment by cball01** [comment]
Groovy cool, thank you.

Swapping the fullchain.cer for the [site].cer on the mattermost server and restarting MM has fixed me up.  I'm still kinda confused how this is unnecessary for the web browser connections and desktop clients to be content but not the android app but I can't argue with results.  Thank you again.
