### ISSUE TITLE
User frustration due to lost Server URL and user name

### ISSUE THREAD

**Issue by be-glass** [mattermost/mattermost-mobile#7939]
#### Summary
Client should always remember Server URL and user name

### Environment Information
  - Device Name: any
  - OS Version: any
  - Mattermost App Version: latest
  - Mattermost Server Version: latest

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

- Connect client to Mattermost server
- log in
- Wait until the log in expires

#### Expected behavior
- User needs to enter password for authentication
- The client shows the last used server URL(s). 
- The client shows the last used user name(s).

#### Observed behavior (that appears unintentional)
After session expiry, the user is presented with blank fields for Server URL and user name.

Many users don't remember the server URL, and don't bother to ask the administrator. This causes a large number of users to abandon the platform, due to inexperience or lack of motivation.

#### Possible fixes
Let the client remember Server URL and user name and save the users from having to remember them.

**Comment by amyblais** [comment]
Closing as a duplicate of https://github.com/mattermost/mattermost-mobile/issues/7076.

**Comment by abourget** [comment]
This is an important hindrance to usability, and a basic one to address in my opinion.

It creates lots of friction for my community.

 Are there some design issues that need to be addressed or could it be simply implemented?
