### ISSUE TITLE
The app fails to render hashtags with a minimum length of 2 after modifying the setting in the system console

### ISSUE THREAD

**Issue by eli-yip** [mattermost/mattermost-mobile#7961]
### Summary

Bug report: The app fails to render hashtags with a minimum length of 2 after modifying the setting in the system console.

### Environment Information

  - Device Name: iPhone 15 Pro
  - OS Version: iOS 17.5
  - Mattermost App Version: 2.16.0
  - Mattermost Server Version: 9.8.0

### Steps to reproduce

1. Open the Mattermost system console.
2. Navigate to the database settings.
3. Change the minimum hashtag length to 2.
4. Attempt to use a hashtag with a length of 2 in the app.

### Expected behavior

The app should correctly render hashtags with a length of 2 after changing the minimum hashtag length setting.

### Observed behavior (that appears unintentional)

The app does not render hashtags with a length of 2. It still only supports hashtags with a length of 3 or more. 

### Possible fixes

Potential issue in the codebase where the hashtag length validation still enforces a minimum length of 3. Consider checking the validation logic for hashtags in the app's code.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-58365.

**Comment by larkox** [comment]
Closing in favor of the Help Wanted ticket opened in the main repo:
https://github.com/mattermost/mattermost/issues/27220
