### ISSUE TITLE
Attached images not displayed

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#797]
#### Summary
...only seeing default image icon in both preview and on open

#### Environment Information

- Device Name: Samsung
- OS Version: 6.0.1
- Mattermost App Version: 1.0.1
- Mattermost Server Version: 4.0.1

#### Steps to reproduce
Have/upload an image.

#### Expected behavior
Be able to see it..

#### Observed behavior
Not able to see it.

#### Possible fixes
Use a Sony 5.1.1 device, it works fine there. :)

**Comment by enahum** [comment]
Does this happen every time? Do you know if others with the same device are seeing the same issue? What type of image is it?

I've tried to reproduce myself but is working just fine for me

**Comment by licaon-kter** [comment]
All the images show like that, JPEGs.

I'll try to get others to tell me, as several have the exact same model.

**Comment by lfbrock** [comment]
Hi @licaon-kter - just following up on this, are you still seeing this issue?

**Comment by licaon-kter** [comment]
You mean with app version 1.1.0 (build 47)? Yes, still an issue.

**Comment by licaon-kter** [comment]
Not fixed in 1.2.0 (build 49) either.

**Comment by licaon-kter** [comment]
Updated server to 4.2.0, logged out of the app on the device with the issue, re-login... now it's fixed.
