### ISSUE TITLE
Issue when executing the building command on Android

### ISSUE THREAD

**Issue by tevincent** [mattermost/mattermost-mobile#7993]
Hey there,

I was just wondering if this is a normal behavior. I'm trying to add some native Android Views under the `com.mattermost.rnbeta` package, but when I execute the command `npm run build:android`, it creates a new folder with my package name and moves every class from `com.mattermost.rnbeta` to this newly created folder. I'm not sure if this is clear enough.

Is this normal?

My problem is that I have created some classes inside the `com.mattermost.rnbeta` package that need some resources from `strings.xml` (inside the `CustomPushNotification` class). Because all the classes change directory after executing `npm run build:android`, resources cannot be resolved anymore. My guess is to move classes that need resources outside the `com.mattermost.rnbeta` package to avoid this problem, but I'm not sure of the impact.

Thanks for your help,
Vincent

**Comment by enahum** [comment]
Yes, during build we move all the files under that package to the packgeId of the application.

Perhaps you could create another package with your changes instead

**Comment by tevincent** [comment]
I need to move the CustomPushNotification class and this one was moved to another package. I just want to make sure it will not cause a side effect.

**Comment by enahum** [comment]
Should not be a problem as long ad you make the changes to import the new package

**Comment by tevincent** [comment]
Just tried and it doesn't work. The issue is the R (com.mattermost.rnbeta.R) is not existing anymore after running the command. I need to use some resources (images, etc.). Is there a way to avoid that problem?

Thanks
