### ISSUE TITLE
Push notification broken on 2.17.0

### ISSUE THREAD

**Issue by Maoulkavien** [mattermost/mattermost-mobile#8028]
#### Summary
On android release 2.17.0, mattermost does not display push notifications if app in not at least in the background

### Environment Information
  - Device Name: Fairphone FP3
  - OS Version: 14
  - Mattermost App Version: 2.17.0
  - Mattermost Server Version: 9.5.2-0 and 9.6.1-0

#### Steps to reproduce
Start the app to ensure you are logged in, go to home screen, and "soft close" the app (not sure how it's named, when you swipe background apps to the side of the screen so they are no longer displayed in running apps).

Have someone do something that triggers a push notification (I even set my app to notify me on all activity). 

#### Expected behavior
I should be receiving a push notification

#### Observed behavior (that appears unintentional)
I no longer recieve push notification.

#### Possible fixes
Having the app still run in background allow it to display the push notifications (e.g. : not swiping the app out of the phone after returning to home screen) . I already tried disabling battery optimisation for this app to no avail

#### Additionnal information
I rolled back to 2.16.0 and everything works again as expected (though I got an odd message saying that "this app is not compatible with the last android version" or something, which I forgot to screenshot, my bad)

**Comment by Wignasty07** [comment]
Also having issues: Android users are the ones affected

**Comment by amyblais** [comment]
https://mattermost.atlassian.net/browse/MM-58818

**Comment by Maoulkavien** [comment]
Hello again ! 

I see that the bug was identified and will be fixed in 2.17.1, any (even vague) idea as to when 2.17.1 will be out on the Play Store ?

**Comment by amyblais** [comment]
We are waiting for Google Play store to review and approve the latest release build. Hopefully they will review it soon. Once approved, we are able to release it to production.

**Comment by amyblais** [comment]
Mobile v2.17.1 dot release has started to roll out this morning,
