### ISSUE TITLE
where is DefaultServerUrl?

### ISSUE THREAD

**Issue by Aimn** [mattermost/mattermost-mobile#806]
Hi
I have downed all project,but i can't find the config.secret.json
I try add config/config.secret.json into ../ or ../app/ ,but still connected 10.0.2.2:8081
How can i edit DefaultServerUrl to develop?
thanks

**Comment by Aimn** [comment]
Body:
                                                  {"from":"D:\\mattermost-mobile-master\\app\\mattermost.js","to":"../dist/assets/config","message":"Unable to resolve module `../dist/assets/config` from `D:\\mattermost-mobile-master\\app\\mattermost.js`: Directory D:\\mattermost-mobile-master\\dist\\assets\\config doesn't exist","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}

**Comment by Aimn** [comment]
@hmhealey THX!
I also found  some performance problems.In Android, React app spends 10s~40s  in showing pages on webview.React Native app spends 10s in showing pages.whatever in React app or in React Native app,it takes long time to render js page when it is in white screen.
Do you have some good suggestion about this?

**Comment by lfbrock** [comment]
Hi @Aimn - when you say 10-40s, can you let us know what screens it's happening on? 

For example is it it after logging in, loading the app after putting it to background, switching channels when you already have the app open?

**Comment by Aimn** [comment]
As you said,it takes long time from after logging to showing channels,when it is on the white screen

**Comment by enahum** [comment]
Is this happening in dev mode or release mode? 

In dev mode is expected

**Comment by Aimn** [comment]
both release mode and dev mode

**Comment by lfbrock** [comment]
Going to close this issue - we've been working on making improvements to load times and will continue to do so. If other people have reports of slowness, please comment on this forum post with info about what you're seeing? 

https://forum.mattermost.org/t/reports-of-slowness-in-mattermost-mobile-apps/3827
