### ISSUE TITLE
Android: Crashes when sharing images

### ISSUE THREAD

**Issue by polygon0323** [mattermost/mattermost-mobile#8081]
#### Summary
Crashes when sharing images

### Environment Information
  - Device Name: Pixel 7a
  - OS Version: 14 AP2A.240705.004
  - Mattermost App Version: 2.17.1
  - Mattermost Server Version: 9.9.1

#### Steps to reproduce
1. Share image from Gallery app, etc. to the Mattermost app
2. enter text and post

#### Expected behavior
Image will be posted

#### Observed behavior (that appears unintentional)
Mattermos app are crashed

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
https://mattermost.atlassian.net/browse/MM-52807
