### ISSUE TITLE
Unhandled JS Exception on startup

### ISSUE THREAD

**Issue by alexissmirnov** [mattermost/mattermost-mobile#81]
Followed the instructions in README (also I have other RN apps running on my machine)

The app shows `Unhandled JS exception` at startup

`react-native log-ios` shows
```
Nov 25 11:41:34 honey Mattermost[5335] <Error>: Module name prefixes should've been stripped by the native side but wasn't for RCTJSCExecutor
Nov 25 11:41:34 honey Mattermost[5335] <Notice>: 'Failed to print error: ', 'Requiring module "41", which threw an exception.'
Nov 25 11:41:34 honey Mattermost[5335] <Critical>: Unhandled JS Exception: Invariant Violation: Module name prefixes should've been stripped by the native side but wasn't for RCTJSCExecutor
```

**Comment by enahum** [comment]
Hi @alexissmirnov,

Sorry, the README is probably misleading, this is a repo that is not yet stable. It's under active development. [The initial plan is on the forums](http://forum.mattermost.org/t/roadmap-for-next-generation-mobile-apps-in-react-native/2339), and our priorities have varied a bit. 

We'll be updating the README to avoid this confusion and we'd love to have your help once we finish some of the core infrastructure. 

Thank you so much for your interest, we're excited to build you a fantastic product (and have your help as well, if you're interested)

**Comment by alexissmirnov** [comment]
Ok no worries. FYI dialogue.co is running MM open-source. We've build an Ionic/Angular messaging prototype (for both mobile app for patients and web app for practitioners) and are working on React Native impl on mobile. Next week we're starting to plug in websockets in RN app. If someone is also working in that part, I'd love to sync up.
