### ISSUE TITLE
New mattermost android app not connecting to 4.0 instance

### ISSUE THREAD

**Issue by gdureuil** [mattermost/mattermost-mobile#813]
#### Summary
New mattermost android app not connecting to 4.0 instance

#### Android Environment Information

- Device Name: Zenfone 3 Laser
- OS Version: 7.1.1
- Mattermost App Version: Latest Mattermost on Google Play
- Mattermost Server Version: 4.0.0

#### Mattermost Environment Information

- OS Version: Debian 9 
- Mattermost Server Version: 4.0.0
- Mattermost URL : https://team.dureuil.info
- Apache 2.4.25 as proxy on mattermost, MariaDB 10.1.23

#### Apache2 vhost with proxy

```
<VirtualHost *:443>
    Include /home/www-data/conf/apache2/conf-default.conf

    ServerName team.dureuil.info
    ServerAlias team.dureuil.info
    DocumentRoot "/home/www-data/www/dureuil.info/team/"
    
    SSLProxyEngine on
    ProxyPreserveHost On
    ProxyRequests Off
    AllowEncodedSlashes NoDecode
    
    <Location />
    ProxyPass http://127.0.0.1:8065/
    ProxyPassReverse http://127.0.0.1:8065/
    Require all granted
    </Location>
    
	#Allow Let'sEncrypt access for renew
    <Location /.well-known>
    ProxyPass !
    </Location>

    <Location /api/v4/websocket>
    ProxyPass ws://127.0.0.1:8065/api/v4/websocket
    ProxyPassReverse ws://127.0.0.1:8065/api/v4/websocket
    Require all granted
    </Location>
    
    RewriteCond %{REQUEST_URI} ^/api/v4/websocket [NC,OR]
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC,OR]
    RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
    RewriteRule .* ws://127.0.0.1:8065%{REQUEST_URI} [P,QSA,L]
    RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
    RewriteRule .* http://127.0.0.1:8065%{REQUEST_URI} [P,QSA,L]
    RequestHeader set X-Forwarded-Proto "https"

    
    CustomLog /home/www-data/logs/apache2/team.dureuil.info-ssl-access.log combined
    ErrorLog /home/www-data/logs/apache2/team.dureuil.info-ssl-error.log
    
    AccessFileName .htaccess
    
    <Directory "/home/www-data/www/dureuil.info/team/">
        DirectoryIndex index.php index.html
        Options FollowSymLinks
        AllowOverride All
        Order Deny,Allow
        Allow from all
        Require all granted
    </Directory>
        
    <IfModule mod_ssl.c>
        SSLEngine on
        SSLCertificateFile "/etc/letsencrypt/live/dureuil.info/cert.pem"
        SSLCertificateKeyFile "/etc/letsencrypt/live/dureuil.info/privkey.pem"
        SSLCertificateChainFile "/etc/letsencrypt/live/dureuil.info/chain.pem"
        Header always set Strict-Transport-Security "max-age=31556926; preload"
    </IfModule>

</VirtualHost>
```

#### Steps to reproduce

Use android app, enter mattermost instance URL.

#### Expected behavior

Connecting correctly to mattermost instance and ask for credentiels.

#### Observed behavior

Android app is not connecting to instance. When entering url "https://team.dureuil.info", the loading animation runs endlessly, never showing login screen.

Android app "Mattermost Classic" is working.

**Comment by enahum** [comment]
Yes I can definitely reproduce, the network request start but it never finishes (at least on android) I wonder if you can take a look at your Apache logs and see if there is something weird going on there

**Comment by gdureuil** [comment]
I checked logs and saw nothing. But i found the problem.

My vhost conf in cluding a defaut file

`Include /home/www-data/conf/apache2/conf-default.conf`

This has the following content, for HTTP/2 support

`<IfModule http2_module>
  Protocols h2 http/1.1
</IfModule>`

This is the problem.

HTTP/2 enabled
- Works in "Mattermost Classic"
- Not works in "Mattermost"

HTTP/2 disabled
- Works in "Mattermost Classic"
- Works in "Mattermost"

But, i still have a problem (http2 disabled actually). I can login to the new app, but there is always a banner saying "Connecting..." on top of screen. Any idea ?

**Comment by enahum** [comment]
can you share what do you get in the Mattermost logs about the websocket?

**Comment by gdureuil** [comment]
I just checked Mattermost logs. Just got this, while using phone (displaying chat ok but still "Connecting..." message).

```
[2017/08/03 18:38:00 CEST] [EROR] Erreur de la connexion websocket : websocket: origin not allowed
[2017/08/03 18:38:00 CEST] [EROR] /api/v4/websocket:connect code=500 rid=XXXXX uid=XXXXX ip=XXX.XXX.XXX.XXX Failed to upgrade websocket connection [details: ]
```
Redacted rid, uid and ip.

These messages do not appear when using "Mattermost Classic" (tested).

**Comment by enahum** [comment]
Ok so the reason is working on Mattermost Classic is because that app is just a WebView.

I just want to confirm a few things.
does the server url used in the app matches the `SiteURL` setting in your config.json?
do you have the `AllowCorsFrom` value set to anything else than an empty string?

As far as I can tell the server url used in the app has to match the `SiteURL` or any of the values set in `AllowCorsFrom`

**Comment by gdureuil** [comment]
Checked config.json

SiteURL is a match : "https://team.dureuil.info"
AllowCorsFrom is not empty, same as SiteURL.

I replaced it with an empty string, restarted mattermost, and now the "Mattermost" app is connecting ok. Green bar on top saying "Connected", and no error in Mattermost log.

Thank you very much for your help ! This issue is now closed.
