### ISSUE TITLE
Enter key on hardware keyboards no longer sending message on iOS (Ipad) after today's update

### ISSUE THREAD

**Issue by anomaly256** [mattermost/mattermost-mobile#8150]
#### Summary
Prior to today's update, hitting 'enter / return' after typing a new message with an ipad hardware keyboard would sent it immediately.  This seems to no longer be the case.

### Environment Information
  - Device Name: Ipad Pro (M4) with Magic Keyboard case
  - OS Version: latest
  - Mattermost App Version: v2.19.0
  - Mattermost Server Version: n/a

#### Steps to reproduce
Use an iOS device with a hardware keyboard to compose a message to a channel then hit enter to attempt to send it

#### Expected behavior
The message is sent upon pressing the enter key

#### Observed behavior (that appears unintentional)
The message is not sent (nor is a newline added).  It appears pressing enter does nothing.

#### Possible fixes
Unknown

Thanks

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-60220.
