### ISSUE TITLE
2.19.0 release links broken

### ISSUE THREAD

**Issue by x4e-jonas** [mattermost/mattermost-mobile#8154]
The release links for 2.19.0 on https://github.com/mattermost/mattermost-mobile/releases/tag/v2.19.0 are broken. For example, https://releases.mattermost.com/mattermost-mobile/2.19.0/545/Mattermost-arm64-v8a.apk returns "AccessDenied".

**Comment by mvitale1989** [comment]
Hello @x4e-jonas , thank you for raising!
It seems there was an error in our process. I have fixed the links now :+1:
