### ISSUE TITLE
login with otp on same device fails

### ISSUE THREAD

**Issue by KlavsKlavsen** [mattermost/mattermost-mobile#8155]
I installed latest mattermost mobile app on android 14 - and when it redirects me to gitlab - and as part of that I need 2factor from my freeotp app - then the login popup disappears - so I can't go back to enter the TOTP number and hence I was only able to login, by getting otp generated on my computer instead and type it without leaving login popup.

Also -it said login succeeded with gitlab and then redirected me - and app said it had failed.. but then when I just went "back" in mattermost twice - I WAS logged in just fine.

**Comment by amyblais** [comment]
Hi @KlavsKlavsen,

1. What Mattermost App Version are you on?
2. Mattermost Server Version are you on?
3. What are the reproduction steps?

**Comment by KlavsKlavsen** [comment]
1. v2.19.0 from 6th of august
2. server version 5.4.2 (team edition)
3. simply install mobile app on android 14, and try to login using gitlab

**Comment by amyblais** [comment]
2. v5.4.2 is quite an old version. We currently support versions v9.5 and newer https://docs.mattermost.com/about/mattermost-server-releases.html#latest-releases. Would you be open to upgrading to a newer version to rule out a server issue?

**Comment by amyblais** [comment]
2. It's also possible that v5.4.2 is your desktop app version, not your server version. 
- You can find the server version from Main Menu -> About Mattermost.
- The latest desktop app version is v5.9 and I recommend updating https://docs.mattermost.com/about/mattermost-desktop-releases.html#latest-releases.

**Comment by KlavsKlavsen** [comment]
ahh.. 5.4.2 is my desktop app version - sorry

**Comment by KlavsKlavsen** [comment]
server runs on k8s - mattermost-team-edition:9.4.2 is the docker image used.
