### ISSUE TITLE
Auto capitalization not working after last update 

### ISSUE THREAD

**Issue by alfonsocasadodiez** [mattermost/mattermost-mobile#8165]
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Auto-capitalization no longer works

### Environment Information
  - Device Name: Samsung S21 Ultra
  - OS Version: OneUI 6.1 (Android 14)
  - Mattermost App Version: 2.19.0 (build 6000544)
  - Mattermost Server Version: 9.11.0 (build 10163357270)

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Try to type on any text field
#### Expected behavior
Auto Capitalization is no longer working on Mattermost

https://github.com/user-attachments/assets/3c22b82e-41ed-46a5-8f47-d41011d43a0c

#### Observed behavior (that appears unintentional)
What did you see happen? Please include relevant error messages, screenshots and/or video recordings.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by pkostiuk** [comment]
Same issue here.

**Comment by razerbeans** [comment]
Was bitten by this as well. Doesn't bode well when trying to make a case for migrating to Mattermost. :(

**Comment by amyblais** [comment]
A ticket is open and a fix queued for v2.19.1 https://mattermost.atlassian.net/browse/MM-60263.

**Comment by amyblais** [comment]
Scheduled for v2.19.1 dot release,
