### ISSUE TITLE
SSO page connection not open browser page

### ISSUE THREAD

**Issue by darkweizer** [mattermost/mattermost-mobile#8206]
Hey !

Since last update of app (2.19.2 build 6000554), the page of connection via browser does not open after display Redirection page.
Version of server : 7.10.3

For the reproduction steps :

- Open app
- Click on the server
- Ok on popin notification
- Click on Gitlab button
- Page for connection via browser does not open.

Thanks.
Best regards.

**Comment by amyblais** [comment]
v7.10.3 is quite an old version. We currently support versions v9.5 and newer https://docs.mattermost.com/about/mattermost-server-releases.html#latest-releases. Would you be open to upgrading to a newer version to rule out a server issue?

**Comment by PlaneNuts** [comment]
amyblais - I encountered the same issue running the latest Android build

App Info - 2.19.2 (Build 6000554)
Server Version 9.11.0 (Build 10163357270)
Database: mysql
Database Schema Version: 124

In my case starting with a clean installation of the app.

  - Open MM --> enter server URL --> Connect via our Auth service--> get redirected to login
  - In the past this redirection to login would open my default browser, while now it appears the page opens in WebView.
  
  The problem for this with me is auth flow requires an MFA token, which is also on my phone. And when changing the app focus 
 (or even pulling up the app switcher) that WebView window closes and my session fails. 
 
 To bypass this I've had to click the three dot menu and select "Open in Chrome" for the window to be able to stay open

**Comment by darkweizer** [comment]
Ok ! So for me, no WebView is displayed 🫤.
I reset my app and same issue, no WebView is displayed.

**Comment by amyblais** [comment]
Opened for investigation: https://mattermost.atlassian.net/browse/MM-60515

**Comment by enahum** [comment]
Out of curiosity, what browsers are available on your phone? And which is set as the default?

**Comment by PlaneNuts** [comment]
> Out of curiosity, what browsers are available on your phone? And which is set as the default?

I have the build in Samsung browser, Chrome (set a default), and Firefox installed. 

I did also try making the Samsung browser default (and confirmed in WebView that's what was rendering page on a subsequent attempt), but had the same behavior.

**Comment by enahum** [comment]
> I did also try making the Samsung browser default (and confirmed in WebView that's what was rendering page on a subsequent attempt), but had the same behavior.

@PlaneNuts can you clarify what this means? I'm afraid I did not understand.

Also thanks for listing your browsers, will check if this has an impact and why.

**Comment by PlaneNuts** [comment]
> @PlaneNuts can you clarify what this means? I'm afraid I did not understand.

Going into Android setting --> applications --> default apps --> changing the default browser from Chrome to Samsung Internet. This told me it wasn't a browser issue

This page is when I'm redirected after selecting to sign in with gitlab. This used to open up in an actual browser window


![20240912_232512-COLLAGE](https://github.com/user-attachments/assets/9423b20e-9466-42a7-88bf-e98b06fbfdf1)

**Comment by enahum** [comment]
So in your case it takes you to that website and then nothing happens?

The original report says that the window does not even open, your case is a bit different?

**Comment by PlaneNuts** [comment]
Yeah, my case is a bit different. I was kind of rushing to get out the door and one of the guys on my team pointed me to this ticket. 

The problem I have is that I have to authenticate with a token that's also on my phone, and as soon as I pull up the all switcher the login window closes and I get an error when returning to Mattermost. 

Also confirmed this is an Android only problem. On iOS it does open normally in a browser window and you can switch to a different app and come back to the login page.

**Comment by enahum** [comment]
Pk good thanks for explaining.. I'll look at that scenario too

**Comment by darkweizer** [comment]
> Out of curiosity, what browsers are available on your phone? And which is set as the default?

@PlaneNuts already answered but i use Dolphin (old fork of Chrome) but I set Samsung browser in default browser in setting of phone and I have the same issue : no window open.

@enahum I hope that the #8220 will fix the problem 🤞🏻. Thank you for your responsiveness (and @PlaneNuts also)

**Comment by enahum** [comment]
@darkweizer can you give this [apk](https://pr-builds.mattermost.com/mattermost-mobile/8220/merge/Mattermost_Beta.apk) a try and see if it works for you ?

**Comment by darkweizer** [comment]
@enahum Yeeees ! It's work 💪🏻. Perfect. Thank you.
