### ISSUE TITLE
Clickable images do not work inside tables

### ISSUE THREAD

**Issue by bergerkiller** [mattermost/mattermost-mobile#8208]
### Environment Information
  - Device Name:
  - OS Version: Both iOS and Android
  - Mattermost App Version: 2.19.2
  - Mattermost Server Version: Unsure

#### Steps to reproduce
Send the following formatted message:
```
| Header |
| :----: |
| [![Mattermost Logo](https://i.imgur.com/LZl7hpw.png)](https://mattermost.com) |
```

The image can be clicked on desktop, but not on the mobile app version.
It does work on mobile outside of tables, but then there is no way to align clickable images side-by-side horizontally.

#### Expected behavior
Clicking the image visits the link

#### Observed behavior (that appears unintentional)
Magnifies the image as if the link did not exist

**Comment by panoramix360** [comment]
hey!

Can I work on this one?

In fact, I already have the fix, will create a PR once you approve that I work on it :)

Thanks!

**Comment by amyblais** [comment]
> hey!
> 
> Can I work on this one?
> 
> In fact, I already have the fix, will create a PR once you approve that I work on it :)
> 
> Thanks!

Yes, thank you!

**Comment by panoramix360** [comment]
Done!

Fix is in here:
https://github.com/mattermost/mattermost-mobile/pull/8215
