### ISSUE TITLE
 Error when opening a specific channel in the mobile application (iOS/Android).

### ISSUE THREAD

**Issue by lsibilev** [mattermost/mattermost-mobile#8234]
Summary
Error when opening a specific channel in the mobile application (iOS/Android). The issue only occurs with one specific channel. Changing the ID in the URL or the channel name does not resolve the problem.

Environment Information
Server Version: 9.4.2 (Build 7586560796)
App Version: 2.20.0 (Build 556)
App Platform: ios
Device Model: iPhone

How can we reproduce the issue (what version are you using?)

Open the Mattermost mobile app.
Navigate to the affected channel.
Observe the error upon trying to access the channel.
Expected behavior
The channel should open normally without causing an error.

Observed behavior (that appears unintentional)
An error is encountered when attempting to open a specific channel. Below is the error message from the mobile application:

Malformed decodeURI input

URIError: Malformed decodeURI input at decodeURIComponent (native) at FileInfo (/Users/runner/Library/Developer/Xcode/DerivedData/Mattermost-bkusffojqipudtazcukmipcffbrx/Build/Intermediates.noindex/ArchiveIntermediates/Mattermost/BuildProductsPath/Release-iphoneos/main.jsbundle:695080:39) at renderWithHooks (/Users/runner/Library/Developer/Xcode/DerivedData/Mattermost-bkusffojqipudtazcukmipcffbrx/Build/Intermediates.noindex/ArchiveIntermediates/Mattermost/BuildProductsPath/Release-iphoneos/main.jsbundle:28953:24) at beginWork (/Users/runner/Library/Developer/Xcode/DerivedData/Mattermost-bkusffojqipudtazcukmipcffbrx/Build/Intermediates.noindex/ArchiveIntermediates/Mattermost/BuildProductsPath/Release-iphoneos/main.jsbundle:32025:34) at performUnitOfWork (/Users/runner/Library/Developer/Xcode/DerivedData/Mattermost-bkusffojqipudtazcukmipcffbrx/Build/Intermediates.noindex/ArchiveIntermediates/Mattermost/BuildProductsPath/Release-iphoneos/main.jsbundle:33491:36) at workLoopSync (/Users/runner/Library/Developer/Xcode/DerivedData/Mattermost-bkusffojqipudtazcukmipcffbrx/Build/Intermediates.noindex/ArchiveIntermediates/Mattermost/BuildProductsPath/Release-iphoneos/main.jsbundle:34002:22) at performSyncWorkOnRoot (/Users/runner/Library/Developer/Xcode/DerivedData/Mattermost-bkusffojqipudtazcukmipcffbrx/Build/Intermediates.noindex/ArchiveIntermediates/Mattermost/BuildProductsPath/Release-iphoneos/main.jsbundle:34841:15) at runWithPriority$1 (/Users/runner/Library/Developer/Xcode/DerivedData/Mattermost-bkusffojqipudtazcukmipcffbrx/Build/Intermediates.noindex/ArchiveIntermediates/Mattermost/BuildProductsPath/Release-iphoneos/main.jsbundle:36854:27) at scheduler_flushTask (/Users/runner/Library/Developer/Xcode/DerivedData/Mattermost-bkusffojqipudtazcukmipcffbrx/Build/Intermediates.noindex/ArchiveIntermediates/Mattermost/BuildProductsPath/Release-iphoneos/main.jsbundle:29005:18) at timerAPIs.getTimerPriority (/Users/runner/Library/Developer/Xcode/DerivedData/Mattermost-bkusffojqipudtazcukmipcffbrx/Build/Intermediates.noindex/ArchiveIntermediates/Mattermost/BuildProductsPath/Release-iphoneos/main.jsbundle:36990:28) at callback (/Users/runner/Library/Developer/Xcode/DerivedData/Mattermost-bkusffojqipudtazcukmipcffbrx/Build/Intermediates.noindex/ArchiveIntermediates/Mattermost/BuildProductsPath/Release-iphoneos/main.jsbundle:28989:26)
![image](https://github.com/user-attachments/assets/f2857ed4-7e01-4886-90bf-f00a95e8e7c3)
![image](https://github.com/user-attachments/assets/83fe5dcb-2963-4a3f-8fb9-d2c9f2421bfe)
![image](https://github.com/user-attachments/assets/c63fcf3e-43ab-44cd-ac6e-340f70ffb1d0)

**Comment by Playa2070** [comment]
![image](https://github.com/user-attachments/assets/b4b4d98a-c51b-4bbd-8cd9-0c6f09748b58)
Similar issue

**Comment by apug** [comment]
Same problem.
Mattermost v2.20.0 for ios
![344B4B75-3A96-4D05-AC57-88EAFCE6ECAC](https://github.com/user-attachments/assets/3ac0eeeb-d43b-47dd-9905-1b6c8fff62c7)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-60879.

**Comment by seoch-web** [comment]
![Screenshot_20241008_133925_Mattermost](https://github.com/user-attachments/assets/f104c5ca-5596-4763-8c60-cc3c160ce7ff)   
me too. similar issue.

**Comment by Zhoglik** [comment]
Similar problem on Android. Maybe, because of attachment in thread/conversation.
In my situation it was big HTMl-file (report) in conversation with person. Deleted it from Desktop and all back to normal
