### ISSUE TITLE
Not Able to Sign in on Android Device

### ISSUE THREAD

**Issue by sumbo-e** [mattermost/mattermost-mobile#8236]
#### Summary
There seems to be a glitch on the Android app - I am able to get through the first screen where I enter the server name and display name - it then authenticates me - but then says unable to sign me in. However it works on the web and on windows.

### Environment Information
  - Device Name: Google Pixel 9
  - OS Version: Android 14
  - Mattermost App Version:  2.20.0 (Build 6000556)
  - Mattermost Server Version: (not sure where to find this)

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
On my pixel 7 with the same version of Android (14) - I am able to login using the same process with no problems at all.

#### Observed behavior (that appears unintentional)
Immediately after authentication it seems like it doesn't connect to the webpage and just defaults to an error and says it can't log on.

I would appreciate any help with this. Thanks.

**Comment by rahimrahman** [comment]
@sumbo-e that's quite odd, especially when it works well with Pixel 7.

Are you authenticating with username/passwords or MFA?

If possible, can you record a video.  Image speaks 1000 words and even more with video.  So any little bit will help.
