### ISSUE TITLE
virtual keyboard blocking input field for mfa login  on android phone

### ISSUE THREAD

**Issue by SoundGoof** [mattermost/mattermost-mobile#8291]
#### Summary
virtual keyboard blocking input field for mfa login  on android phone

### Environment Information
  - Device Name: samsung s23 ultra
  - OS Version: android 14, one ui 6.1, security patch 2024-08-14
  - Mattermost App Version: 2.21.0
  - Mattermost Server Version: 9.10.1

#### Steps to reproduce
increase the font size for people with impaired vision
login with mfa on phone
try to paste the mfa token into the input field

#### Expected behavior
the mfa input field should not be covered by the virtual keyboard

#### Observed behavior (that appears unintentional)
![image](https://github.com/user-attachments/assets/845f89d2-df4d-4f0b-9106-29b7d03f0344)

**Comment by Luizrebelatto** [comment]
i will be working on this issue

**Comment by enahum** [comment]
Should be fixed by https://github.com/mattermost/mattermost-mobile/pull/8340

**Comment by Luizrebelatto** [comment]
thanks for letting me know, I'll look for another one
