### ISSUE TITLE
User update error

### ISSUE THREAD

**Issue by tahyku1812** [mattermost/mattermost-mobile#83]
Hello!
I tried to update user with users/update POST request, but received error.
Unfortunately, no such issues was founded.
The error is:
{ URL: https://......../api/v3/users/update } { status code: 400, headers {
    Connection = "keep-alive";
    "Content-Length" = 159;
    "Content-Type" = "application/json";
    Date = "Fri, 25 Nov 2016 23:06:31 GMT";
    Server = "nginx/1.10.1";
    "X-Ratelimit-Limit" = 10;
    "X-Ratelimit-Remaining" = 9;
    "X-Ratelimit-Reset" = 1;
    "X-Request-Id" = cmwp1oan1ibeuf5dasm6o7njfe;
    "X-Version-Id" = "3.4.0.3.4.0.9dbd3614caa0e137fc768bb3ae09b055";
} }, NSLocalizedDescription=Expected status code in (200-299), got 400}
{\"id\":\"api.context.invalid_param.app_error\",\"message\":\"Invalid user parameter\",\"detailed_error\":\"\",\"request_id\":\"cmwp1oan1ibeuf5dasm6o7njfe\",\"status_code\":400}"

Thanks in advice!

**Comment by enahum** [comment]
Hi @tahyku1812,

Sorry, the README is probably misleading, this is a repo that is not yet stable. It's under active development. [The initial plan is on the forums](http://forum.mattermost.org/t/roadmap-for-next-generation-mobile-apps-in-react-native/2339), and our priorities have varied a bit. 

We'll be updating the README to avoid this confusion and we'd love to have your help once we finish some of the core infrastructure. 

Thank you so much for your interest, we're excited to build you a fantastic product (and have your help as well, if you're interested)
