### ISSUE TITLE
EXIF-rotated images are cut-off in messages

### ISSUE THREAD

**Issue by I-Al-Istannen** [mattermost/mattermost-mobile#8308]
#### Summary
Image attachments (`post.metadata.images`) do not take EXIF rotation into account and are heavily - and wrongly - cropped.

I did not find a matching *open* bug report.

### Environment Information
  - Device Name: FP5
  - OS Version: Android 13
  - Mattermost App Version: c5171418b634ad8111c170bb02a5d62be10952b9
  - Mattermost Server Version: 9.5.9

#### Steps to reproduce
1. Upload a message with an exif-rotated image (or post a link to one, e.g. `https://github.com/recurser/exif-orientation-examples/blob/master/Portrait_5.jpg?raw=true`).
2. Observe the result in the webapp ![grafik](https://github.com/user-attachments/assets/1f73d643-555a-405f-9204-85737dd8be47)
3. Observe the result on mobile <br/> <img src="https://github.com/user-attachments/assets/90a1addb-57c9-4786-b149-5d742eb8e977" height="300px"/>
4. Observe the result on mobile after clicking on it (image gallery) <br/> <img src="https://github.com/user-attachments/assets/d2be41db-9947-4c12-98be-9c86c11d166f" height="300px"/>

#### Expected behavior
The image is displayed completely

#### Observed behavior (that appears unintentional)
The image is resized to fit the raw image bytes aspect ratio, cutting of basically the whole image.

#### Possible fixes
Somewhere, these two should be converted/swapped:
https://github.com/mattermost/mattermost-mobile/blob/2a02a61b6bf25fffa8f385da0b7cdeabd6e2d26a/types/api/posts.d.ts#L42-L43
Probably not in the API request, but on their way to the image viewer components. Maybe the server should do this, it is currently kind of lying :P

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-61477.
