### ISSUE TITLE
android-classic: TPNS notifications do not work

### ISSUE THREAD

**Issue by cpfeiffer** [mattermost/mattermost-mobile#831]
#### Summary
Using the mattermost-android-classic app from Play Store, we never receive push notifications from the TPNS.

#### Environment Information

- Device Name: Multiple Android devices, Samsung Bq, OPO
- OS Version: 6.0, 7.1
- Mattermost App Version: 3.10.0
- Mattermost Server Version: 4.0.0

#### Steps to reproduce
- Configure your server to use TPNS
- Configure a user's account settings to receive push notifications
- Provoke a push notification by sending a direct message, for example

(We tried all combinations, all settings to no avail).

#### Expected behavior
Mobile phone receives and displays the push notification.

#### Observed behavior
The server log file shows that the push notification is delivered to the TPNS.
iOS-classic clients *do* receive the push notification. Just Android-clients don't.

**Comment by lfbrock** [comment]
Hi @cpfeiffer - a couple questions: 

1. Is this all Android devices, or only certain ones? 
2. Can you try uninstalling and reinstalling the app to see if the issue persists?

**Comment by cpfeiffer** [comment]
@lfbrock

1.  I didn't find a single device where it worked.
2.  These are brandnew installations that we just set up for evaluation purposes. So there's no old cruft laying around. We tried different installations and different devices over several days, so the issue definitely persists.

I can still try again tomorrow, to see if something has changed.

**Comment by saisyamd** [comment]
I also have the same issue. I tested it just now but no luck.

**Comment by enahum** [comment]
well I just tested it and is working just fine for me on both iOS and Android (did not test the classic ones)

**Comment by saisyamd** [comment]
@enahum Can you please tell on which Android devices you tested it? Notifications are working in iOS but not in Android.

**Comment by enahum** [comment]
Android 6.0.1 Samsung J5
Android 7.0 Emulator
Android 7.1.1 Emulator

all of them running the apps from this repo, as I said didn't test on the classic apps

**Comment by saisyamd** [comment]
@enahum I re-installed the app and this time it started working. Don't know why it was not working earlier. Anyways thanks for the help
