### ISSUE TITLE
The mobile client crash due to the file name in the channel

### ISSUE THREAD

**Issue by Yosh11** [mattermost/mattermost-mobile#8359]
#### Summary
The application crashes with the error 'Unexpected error occurred' when there is a file with a name like '*%.xlsx'.

### Environment Information
  - Device Name: iPhone 14 Pro
  - OS Version: ios 17.6.1
  - Mattermost App Version: 2.22.0 (Build 574)
  - Mattermost Server Version: 9.11.3 (Build 11258453163
  
#### Steps to reproduce
A file with a name like '*%.xlsx' is attached to the message, after which the application on the iPhone crashes when trying to access this channel with this file. No errors are observed in the desktop application; however, such a file is absent in the 'View info > Files' tab. The indexing may be breaking.

#### Expected behavior
No error when entering the channel from the iPhone.

#### Possible fixes
If the file is removed from the channel, the problem disappears, and the same error also goes away if the same file is sent but with the '%' sign removed before the period.

#### Observed behavior (that appears unintentional)
![Screenshot of the error.](https://github.com/user-attachments/assets/b1df591c-8e92-40c7-9ff5-994f56f9d6d0)

**Comment by enahum** [comment]
@larkox can you link your PR to close this issue?

**Comment by oleynikd** [comment]
Confirmed: This issue occurs specifically when uploading PDF files with "%" characters in the filename.

Steps to reproduce:
1. Upload a PDF file containing "%" in filename (example file attached) from desktop app
2. Open this channel on Android or iOS app
3. Observe the error

Additional testing notes:
- Consistently reproducible with PDF, XLSX, CSV files
- No problems observed when uploading image files with "%" in filename

[Mattermost_logo_%_vertical_black.pdf](https://github.com/user-attachments/files/17852983/Mattermost_logo_._vertical_black.pdf)

**Comment by simevo** [comment]
same here!
