### ISSUE TITLE
Add support for AES256 ciphers

### ISSUE THREAD

**Issue by sedrubal** [mattermost/mattermost-mobile#840]
#### Summary
I'm not completely sure about the cryptographic backgrounds, but as far as I understood mattermost mobile currently does not support ciphers with AES256 (such as `ECDHE-RSA-AES256-GCM-SHA384`, `ECDHE-RSA-CHACHA20-POLY1305`, `ECDHE-RSA-AES256-SHA384`).

#### Environment Information

- Device Name: Nexus 5
- OS Version: Android `7.1.2`
- Mattermost App Version: `1.1.0`
- Mattermost Server Version: `4.0.2`

#### Steps to reproduce
We used a nginx reverse proxy with following tls configuration:

```nginx
ssl_protocols TLSv1.2;
ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384';
ssl_prefer_server_ciphers on;
ssl_ecdh_curve secp384r1;

add_header strict-transport-security "max-age=15768000; includeSubDomains" always;

ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;

ssl_stapling on;
ssl_stapling_verify on;
```

#### Expected behavior
The app should be able to connect to the server.

#### Observed behavior
The app couldn't connect to the server. It was 'connecting...' all the time or gave a vague error message after entering the url to our mattermost instance in login screen (afaik it was "Cannot connect to server. Please check your server URL and internet connection". BTW, can you give a more useful notification on ssl errors?)

#### Possible fixes
We could fix this problem by adding `ECDHE-RSA-AES128-GCM-SHA256` to the ciphers list. So we're assuming that mattermost mobile does not support `AES256` ciphers.

**Comment by enahum** [comment]
I don't know much about these ciphers but I do see it listed [here](https://developer.android.com/reference/javax/net/ssl/SSLEngine.html) which are the supported ciphers by android and [this](https://square.github.io/okhttp/3.x/okhttp/okhttp3/class-use/CipherSuite.html) is the list of ciphers that the underline library is using.

If you try and connect with an iOS device, does it work?

**Comment by sedrubal** [comment]
I'm sorry, I don't have any iOS device atm.

I didn't find out if the latest version of okhttp is used by mattermost app. I reported an issue in another project which could fixed by updating the version of okhttp...

**Comment by enahum** [comment]
In our case it has to be done by the react native team which is what we are using to build the app

**Comment by enahum** [comment]
going to close this issue as there hasn't been a response in more than 30 days, feel free to re-open if necessary.
