### ISSUE TITLE
Cache reset doesn't refresh custom emotes from server

### ISSUE THREAD

**Issue by cybershambles** [mattermost/mattermost-mobile#841]
#### Summary
after you clear cache.. it doesn't refresh the custom emotes list.... `:` is only showing the default emotes

#### Environment Information
- Device Name: iPhone 7 Plus
- OS Version: iOS 
- Mattermost App Version: 1.1.0 - 47
- Mattermost Server Version: 4.0.2

#### Steps to reproduce
log into server
post a chat with a custom emote
reset the cache
1) notice the custom emote is not rendering
2) notice the custom emotes are missing from the emote list

#### Expected behavior
custom emotes working as expected

#### Observed behavior
custom emotes are forgotten about. simply rendering text

**Comment by enahum** [comment]
Awesome find, we need to fix this.

Thanks

**Comment by enahum** [comment]
Closed via #854
