### ISSUE TITLE
Deleting chat in web app doesn't delete on the mobile app

### ISSUE THREAD

**Issue by cybershambles** [mattermost/mattermost-mobile#842]
#### Summary
Deleted lines are not removed in webapp without clearing/resetting cache... 

#### Environment Information

- Device Name: iPhone 7 plus
- OS Version: iOS
- Mattermost App Version: 1.1.0-47
- Mattermost Server Version: 4.0.2

#### Steps to reproduce
1) make a few lines in webapp
2) refresh the mobile app
3) delete lines in webapp
4) refresh the mobile app
5) notice the deleted lines still exist

#### Expected behavior
deleted lines removed from mobile

#### Observed behavior
deleted lines stales/kept in cache

**Comment by enahum** [comment]
You don't see a `(message deleted)` message for those that have been removed on the desktop?

**Comment by enahum** [comment]
going to close this issue as there hasn't been a response in more than 30 days, feel free to re-open if necessary.
