### ISSUE TITLE
Doesn't support apiv4 only

### ISSUE THREAD

**Issue by cybershambles** [mattermost/mattermost-mobile#843]
#### Summary
I disabled apiv3 on 4.0.2 server and the mobile app stopped working.

#### Environment Information

- Device Name: iPhone 7 plus
- OS Version:  iOS
- Mattermost App Version: 1.1.0-47
- Mattermost Server Version: 4.0.2

#### Steps to reproduce
Enable apiv3
log into app - success
disable apiv3
log into app - failure

#### Expected behavior
apiv3 is being decommed.. expected app to work with newest apiv4

#### Observed behavior
Application failed

**Comment by enahum** [comment]
The ping request to the server to identify if you need a server upgrade is being done with APIv3 for now, this will change very soon but no ETA so far

**Comment by enahum** [comment]
Closin via #862
