### ISSUE TITLE
Messages with `actions` in their `attachments` are not displayed correctly since version 2.23.0

### ISSUE THREAD

**Issue by Augustin-FL** [mattermost/mattermost-mobile#8435]
Hi @larkox 

I am facing the same issue as @Kvark1205 on [#8422](https://github.com/mattermost/mattermost-mobile/issues/8422#issuecomment-2549185600): messages from `AlertManager` component of `Prometheus` are not displayed correctly on the mobile app of mattermost since release v2.23.0

I tried to debug what's going on: the issue seems related to `actions` object of `attachments` in messages. As soon as one `action` is present, Mattermost mobile does not display the message correctly.

I am opening a separate Github issue because I believe the bug is not directly related to interactive dialogs (please let me know if I'm wrong).

Here is a python script that can reliably trigger the issue:
```
import requests
response = requests.post(
    f"http://localhost:8065/hooks/3fobp3dduifmtx9cdnbedsi6cy",
    json={
        "username": "NotificationsBot",
        "attachments": [
            {
                "text": "Service AAA went down. Please check",
                "actions": [{"id": "765dguyjij8mbdzc1xwwmuei7c", "type": "button"}],
            }
        ],
    },
)
```

When executing the code, Mattermost desktop app displays the message correctly: 

 ![Mattermost desktop](https://github.com/user-attachments/assets/e629e16b-0bc0-47e5-9c58-135013f19dff)

However, Mattermost mobile does not:

![Mattermost mobile](https://github.com/user-attachments/assets/3e112c57-0773-408e-8eab-36624cf6c553)

Also, I do confirm that the issue is still present on the current codebase (as of 32453b320c31ec98a8936b9d4192c41d90fd050a ).
 
I did a test build of the mobile APK, it is still affected by the issue.

**Comment by larkox** [comment]
@Augustin-FL Can you verify if adding a name to the actions fix the issue? Name is supposed to be a required field for actions.

**Comment by Augustin-FL** [comment]
Indeed, 
When adding a name to all actions, everything works correctly.

The issue seems to be on `AlertManager` side then: 
When sending a Mattermost message, AlertManager doesn't add a `name` field to actions, even when an action `name` [is configured](https://prometheus.io/docs/alerting/latest/configuration/#action_config) correctly in AlertManager's config (`alertmanager.yml`)

I am closing this issue, given it is not directly related to the mattermost mobile app. Feel free to re-open it if needed
