### ISSUE TITLE
minor UX bug: "refreshing messages failed" doesn't seem to be removed

### ISSUE THREAD

**Issue by cybershambles** [mattermost/mattermost-mobile#844]
![image](https://user-images.githubusercontent.com/7995198/29150588-f5ac56be-7dbe-11e7-9020-70a031580754.png)

#### Summary
This failed to connect.. then connected and the bar was stuck.

#### Environment Information

- Device Name: iPhone 7 Plus
- OS Version: iOS
- Mattermost App Version: 1.1.0-47
- Mattermost Server Version: 4.0.2

#### Steps to reproduce
Have not been able too.

#### Expected behavior
That error is removed on successful connection?

#### Observed behavior
error is static.

**Comment by enahum** [comment]
If the app fails to fetch posts after it has retried twice that bar should be visible until you pull to refresh or change channels. It was design to be static.

The bar that is removed when connection is restored is the one that says "coneccting..."

**Comment by cybershambles** [comment]
No. notice how it's half shown... I was connected. I was refreshed. it didn't go away..

it was just stale.

**Comment by enahum** [comment]
Im not able to repro this, do you have repro steps?

**Comment by mkozjak** [comment]
@enahum: Just keep on switching channels and refreshing messages (slide down) and you'll hit it easily.

**Comment by el-moalo-loco** [comment]
Could this be related to #1106 and/or #1050?

**Comment by lindy65** [comment]
This issue is fixed in the latest release so I'll close it off for now.  Please feel free to open a new issue if the problem persists after upgrading to the [latest version](https://about.mattermost.com/download/#mattermostApps).
