### ISSUE TITLE
Unusual high power drain of the mattermost App on iOS

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/mattermost-mobile#845]
The native App seems to drain a lot of energy. Two users report unusual high power usage of Mattermost.

I use Mattermost 4.1 RC and the users the latest version of the app.

![img_1205](https://user-images.githubusercontent.com/8283684/29157043-49794820-7da5-11e7-9acf-30c7f55fb0e0.PNG)
![img_1894](https://user-images.githubusercontent.com/8283684/29157055-5b897c92-7da5-11e7-99f4-b46299855444.PNG)

**Comment by enahum** [comment]
Hi @Twilek-de sorry for the delayed response, can you please share more information on this like how long was the app running in the background, in the foreground, what kind of actions are you taking, did you share an image taken from the camera?

every single little detail that you share might let us pinpoint the issue a little bit better.

**Comment by Twilek-de** [comment]
Ah I have discussed this on the forums and forgot about this ticket. One user is the only one to suffer from this (I myself cannot reproduce this problem). On the second users phone the power usage dropped after some time. The user on whoms phone the problem remains has connection problems to the server I am running Mattermost on, so that every couple of minutes the connection is dropped. I think that this is to blame because the app has to reconnect often. The user is not willing to further investigate the problem so I guess the problem is closed....
