### ISSUE TITLE
Emoji reactions not working with "+" in reply

### ISSUE THREAD

**Issue by timrsmith** [mattermost/mattermost-mobile#874]
#### Summary
Emoji reactions are not working as expected when replying with a "+", e.g. `+:thumbsup:` 

#### Environment Information

- Device Name: iPhone 6S+
- OS Version: 10.3.3
- Mattermost App Version: 1.1.0 (build 47)
- Mattermost Server Version: 4.1.0

#### Steps to reproduce
In Mattermost mobile, reply with a `+:thumbsup:`
![fullsizerender 3](https://user-images.githubusercontent.com/1857984/29977053-ef674e92-8ef0-11e7-90f0-95b24133c50c.jpg)

#### Expected behavior
The 👍 should show as an emoji reaction, like so:
<img width="236" alt="screen shot 2017-09-01 at 8 32 19 am" src="https://user-images.githubusercontent.com/1857984/29977083-0c7dca7e-8ef1-11e7-9138-baf174eea857.png">

#### Observed behavior
Instead, it shows as a reply of "+👍 "
![fullsizerender 2](https://user-images.githubusercontent.com/1857984/29977113-26185062-8ef1-11e7-96d7-2fa9c3c817e0.jpg)

**Comment by lfbrock** [comment]
Hi @timrsmith - thanks for the report, we've added it as a known issue to the [changelog](https://github.com/mattermost/mattermost-mobile/blob/master/CHANGELOG.md#v12-release) for this release and will look at fixing in the next release

**Comment by enahum** [comment]
Closed via #920
