### ISSUE TITLE
Connect websocket

### ISSUE THREAD

**Issue by hmhealey** [mattermost/mattermost-mobile#88]
The websocket should support:
1. POSTED/EPHEMERAL_MESSAGE - new post
2. POST_EDITED/POST_DELETED - post updated
3. NEW_USER - user added to team
4. LEAVE_TEAM
5. USER_ADDED/USER_REMOVED - user added/removed from channel
6. USER_UPDATED
7. CHANNEL_DELETED
8. PREFERENCE_CHANGED
9. HELLO
10. DIRECT_ADDED

We won't initially support:
1. TYPING
2. CHANNEL_VIEWED
3. STATUS_CHANGED
4. WEBRTC
5. REACTION_ADDED/REACTION_REMOVED

**Comment by enahum** [comment]
PR is here https://github.com/mattermost/mattermost-mobile/pull/144

It does not support
1. HELLO
2. TYPING
3. WEBRTC
5. REACTIONS
