### ISSUE TITLE
The app does not render Base64-encoded images correctly

### ISSUE THREAD

**Issue by anton-johansson** [mattermost/mattermost-mobile#884]
#### Summary

The app does not render Base64-encoded images correctly

#### Environment Information

- Device Name: iPhone 6S
- OS Version: 10.3.3
- Mattermost App Version: 1.1.0 (Build 47)
- Mattermost Server Version: 4.1.0

#### Steps to reproduce

Post a message containing a base64 markup, like this:
```
Red dot: ![red dot](data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)
```

You'll see the red dot in the web application (including the old classic iOS app, of course), but you won't see it in this iOS or Android app.

#### Expected behavior

I expect to see the red dot image in this iOS/Android app.

#### Observed behavior

I am not seing the red dot image. Instead, I am seeing the raw markdown, like this:
> **Anton Johansson**
> Red dot: ![red dot](data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)

#### Possible fixes

Sorry, can't provide one. :(

**Comment by lfbrock** [comment]
Hi @anton-johansson - thanks for the report, I think this is because we haven't added support for inline images yet. 

We have a ticket here to fix the issue: https://mattermost.atlassian.net/browse/RN-173

**Comment by anton-johansson** [comment]
Aha, sorry, my bad!

Would it be possible that you close this issue once your internal issue is closed?

**Comment by lfbrock** [comment]
@anton-johansson - yes for sure, we can leave this open + close it once the Jira ticket gets closed

**Comment by anton-johansson** [comment]
Much appreciated!

**Comment by lfbrock** [comment]
@anton-johansson - v1.5.1 of the app should fix this

**Comment by anton-johansson** [comment]
It works indeed! However, a newline is generated before and after each image, unlike in the browser, where I can include an embedded icon in the middle of the line.
