### ISSUE TITLE
Login to app using gitlab is impossible on Xiaomi Redmi Note 4

### ISSUE THREAD

**Issue by ImagoPL** [mattermost/mattermost-mobile#891]
#### Summary
Wiem I try to log in to standalone installation od Mattermost via GitLab, I see only "status: ok" and nothing more. 

#### Environment Information

- Device Name: Xiaomi Redmi Note 4
- OS Version: Android 7.0
- Mattermost App Version: 1.2.0
- Mattermost Server Version: I'm not sure but I think newest stable

#### Steps to reproduce
1. Try to login to standalone installation of Mattermost on http server via standalone installation of GitLab.

#### Expected behavior
After submiting login data, app displays "status: ok" on white screen

**Comment by lfbrock** [comment]
Hi @ImagoPL - a couple questions: 

1. Do you know if other people on your server have the same issue on different devices? 
2. If you have an account on https://gitlab.com/, can you try signing into https://ci-windows-mysql.mattermost.com using the mobile app to see if you hit the same issue?

**Comment by lfbrock** [comment]
@ImagoPL - haven't heard back so I'm going to close this issue, if you're still seeing it please re-open?
