### ISSUE TITLE
Mattermost APP iOS 11 (beta) and iOS 10.x no inline rendering

### ISSUE THREAD

**Issue by lfalkenburg** [mattermost/mattermost-mobile#894]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
On the iOS 1.1 Client PDFs, GIFs, JPGs etc. could be viewed in the Client.

#### Environment Information

- Device Name: iPhone 7+, iPad pro
- OS Version: iOS 11 and 10
- Mattermost App Version: 1.2
- Mattermost Server Version: 4.0.2

#### Steps to reproduce
Just post an URL (no preview), GIF, JPG, PDF (you can't even download them anymore) in any chat.

#### Expected behavior
Preview (URL), pictures shown, PDF preview or download.

#### Observed behavior
see above

#### Possible fixes
Just make it work like in the past ;-)

**Comment by enahum** [comment]
Hi @lfalkenburg in-line rendering is going to be included with the 1.3 release next Oct 5th.

You can check #890 to see what is included as lets say PDF files won't be supported yet

**Comment by enahum** [comment]
Closed via #890
