### ISSUE TITLE
Mattermost APP iOS 11 new images in HEIC-Format

### ISSUE THREAD

**Issue by CrEaK** [mattermost/mattermost-mobile#900]
#### Summary
New taken pics with iOS11 will be send in the new HEIC-Format and is not viewable in the same client and not in other clients as well.

#### Environment Information

- Device Name: iPhone 7
- OS Version: iOS 11 GM
- Mattermost App Version: 1.2.0 (Build 49)
- Mattermost Server Version: 4.1.0

#### Steps to reproduce
Take a new picture with an iOS 11-Device and send it via mattermost. 

#### Expected behavior
Image should be converted to a viewable format

#### Observed behavior
Preview on iphone: ![image](https://user-images.githubusercontent.com/513850/30371131-dead4eb6-9879-11e7-8d28-8438362f1f98.png)
View on Mattermost-Client: 
![image](https://user-images.githubusercontent.com/513850/30371163-f890af30-9879-11e7-90b7-6009ed0c2390.png)

#### Possible fixes
https://developer.apple.com/videos/play/wwdc2017/511/

**Comment by enahum** [comment]
Hi @CrEaK we haven't officially supported iOS 11, but I've added a ticket here https://mattermost.atlassian.net/browse/RN-355 to track this.
