### ISSUE TITLE
Mattermost App shows to be connecting all the time

### ISSUE THREAD

**Issue by FlorianGiantmonkey** [mattermost/mattermost-mobile#906]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Issue in one concise sentence.

Despite showing messages correctly and sending notifications, the app shows to be connecting non stop.

![img_1007](https://user-images.githubusercontent.com/31950189/30416370-2a2956d4-992c-11e7-9a3f-8bbfb76cd834.PNG)

#### Environment Information

- Device Name: apple iphone 6s+
- OS Version: iOS 10.3.3
- Mattermost App Version: 1.2.0 (Build 49) 
- Mattermost Server Version: 4.0.0 (Build 4.0.3)

#### Steps to reproduce
How can we reproduce the issue?
Install app, connect to server

#### Expected behavior
Describe your issue in detail.
After deleting mattermost classic I installed the new mattermost app and connected to my account. The app works finde now, but keeps on showing the grey bar in the top that reads "connecting...".

#### Observed behavior
What did you see happen? Please include relevant error messages and/or screenshots.
No error messsages
Messages are delivered properly (Send and receive)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment]
have you check that your server is configured to allow websocket connections using the APIv4? do you have access to the server logs to see if there's anything being logged related to this?

have you tried connecting to https://pre-release.mattermost.com, if so, does it still happen?

**Comment by enahum** [comment]
actually this looks like a dup of #742 feel free to continue the conversation there.
