### ISSUE TITLE
Team sidebar

### ISSUE THREAD

**Issue by hmhealey** [mattermost/mattermost-mobile#91]
Add a team sidebar similar to the one on the webapp

**Comment by tobihagemann** [comment]
I'm not sure if this feature request is being considered right now. Just tried out the latest beta 1.0 (19) and this is the first thing I've noticed missing. On our Mattermost server we have 3 teams and I find the team sidebar extremely convenient for quickly switching between them. Currently, it feels like that team selection is hidden behind the settings gear icon and too hard to reach.

I don't necessarily think that a team sidebar is the only and correct solution. I can totally understand that an additional sidebar makes the UI cluttered on mobile devices. I don't mind copying this one from Slack's mobile app. :wink: Make team selection available if you tap on the team name (or maybe add a team icon) or swipe inside the navigation screen (or both).

**Comment by enahum** [comment]
@lfbrook we need to figure out how are we going to approach this

**Comment by enahum** [comment]
@lfbrock we need to figure out how are we going to approach this

**Comment by enahum** [comment]
this has been fixed by #577
