### ISSUE TITLE
Add support for basic HTTP authentication

### ISSUE THREAD

**Issue by Sharuru** [mattermost/mattermost-mobile#910]
#### Summary
Please add support for basic HTTP authentication on mobile apps

#### Environment Information

- Device Name: Sony G8242
- OS Version: Android 7.1.1
- Mattermost App Version: 4.0
- Mattermost Server Version: 4.1.0

#### Steps to reproduce
Deploy a mattermost service behind a basic HTTP authentication protected gateway.

Try login it.

#### Expected behavior
Should support server address like `http://username:password@service.address.etc`

Or, like the desktop version, popup a new window asking username and password.

#### Observed behavior
Login failed, ask me to check the service.

When disabled the authentication, everything goes well.

#### Related issue
https://github.com/mattermost/desktop/issues/56

**Comment by enahum** [comment]
Why would you want basic authentication to access Mattermost? I just want to understand the reason behind this.

My concern is that you are going to be sending your credentials in plain text and that is highly insecure let alone using a mobile device that can be connected to a public wifi etc..

**Comment by Sharuru** [comment]
Thanks for the reply!

The reason is we are exploding our internal service though ngrok and SSL connection deployment are on the way.

At this moment, we still looking for the 'safer' connection 😅

**Comment by chumbalum** [comment]
Hi,

we have exact the same requirement in our company. We don't publish any service to public without at least some security measurements which prevent the publicity to access that service. And basic auth is the minimum requirement.

I don't see why this would be a new security issue since it is one more wall to deal with. With SSL enabled, the basic auth will also be sent encrypted. 

The desktop client already does support basic auth parameters in the server url. The feature would be useful for the mobile apps as well.

**Comment by pixelbrackets** [comment]
Same here. At our company we hide every service to the public with a Basic Auth, as this keeps away automatic attack bots very well.

The app should at least allow Basic Auth via URL (http://user:password@example.com), or preferably provide input fields for advanced connection settings.

**Comment by pixelbrackets** [comment]
@enahum Could you please re-open the ticket or say why it should be closed?

**Comment by jespino** [comment]
I'm taking a look to this and sounds difficult to implement, Basic auth use Authorization header, and mattermost use Authorization header too for send the user token. It's possible to use multiple "blocks" in the Authorization header, but looks like not very standard. This thread have some information about it https://stackoverflow.com/questions/29282578/multiple-http-authorization-headers

**Comment by lindy65** [comment]
I'll close this issue off for now as it doesn't seem that we'll be supporting this feature in the near future.

**Comment by jayDevel** [comment]
Are there any plans for implementing it after all? We would love this feature on our team, as this would be much more convenient than using the web-browser.
