### ISSUE TITLE
iOS Client Stuck on DM when switching from LTE to WiFi

### ISSUE THREAD

**Issue by ionbasa** [mattermost/mattermost-mobile#916]
#### Summary
Was in the middle of a DM with someone else, phone was on LTE. During the middle of the DM, phone connected to WiFi. While still in the DM I exited the Mattermost App (double clicked home button and closed the app). Later in the day I re-opened the MM app and was stuck in the previous DM and could not navigate out of it.

#### Environment Information

- Device Name: iPhone 5s
- OS Version: 10.3.3
- Mattermost App Version: 1.2.0 (Build 49)
- Mattermost Server Version:  4.2.0 (Build 4.2.0)

#### Steps to reproduce
Was not able to reproduce except for 1 time as described above.

#### Expected behavior
Should be able to exit DM and not be stuck.

#### Observed behavior
From in app error reporting, was emailed back to oppen issue ticket:

```
Current User Id: yfien7wkbireme9ioz1r7ffobh
Current Team Id: igf7n7mpxjbtxj1tumn8xeqauc
Server Version: 4.2.0 (Build 4.2.0)
App Version: 1.2.0 (Build 49)
App Platform: ios

Errors:
Date: Wed, 13 Sep 2017 01:32:55 GMT
Message: Network request failed
Stack trace:
onerror@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:431:6987
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:421:1505
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:420:6394
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:420:2974
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:346:1285
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:326:2883
file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:326:824
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:326:2284
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:326:796
value@[native code]

Date: Sat, 16 Sep 2017 07:26:25 GMT
Message: Custom emoji have been disabled by the system admin.
Stack trace:


Date: Sat, 16 Sep 2017 17:18:44 GMT
Message: Network request failed
Stack trace:
onerror@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:431:6987
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:421:1505
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:420:6394
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:420:2974
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:346:1285
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:326:2883
file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:326:824
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:326:2284
value@file:///var/containers/Bundle/Application/13016A74-118C-4BDE-B9FB-2468230BB564/Mattermost.app/main.jsbundle:326:796
value@[native code]
```

#### Possible fixes
Was able to fix by disabling WiFi and restarting the app. I was no longer stuck in the DM. I then re-enabled WiFi and everything worked as expected.

Side note: Please feel free to ask me server related questions, I'm the server admin for a ~100+ user team.

**Comment by enahum** [comment]
looks to me that the phone was in a weird state as you said you're not able to repro this.

Anyway we are currently doing some refactor around the connecting state and channel switching to improve performance, perhaps that will prevent it from happening again.

As you can understand is really difficult to reproduce this without concrete steps and by the logs that you shared I can only see that the network was disconnected while making a request to the server, but if it happens to you again please don't hesitate to tell us.

**Comment by lindy65** [comment]
This issue is fixed in the latest version so I'll close it off here for now.  Please feel free to open a new issue if the problem still exists after upgrading to the [latest version](https://about.mattermost.com/download/#mattermostApps).
