### ISSUE TITLE
Chinese language before login is not working

### ISSUE THREAD

**Issue by lin493369** [mattermost/mattermost-mobile#935]
#### Summary
Chinese language before login is not working.

#### Environment Information

- Mattermost App Version: 0.0.1

#### Expected behavior
In select server and login page,the language should be right.

#### Observed behavior
In select server and login page,the language is always Enlish,but my system is ZH environment.
After user login success,the language show right.

#### Possible fixes
Does  something wrong in intl component?

**Comment by lfbrock** [comment]
Hi @lin493369 - when you say your system is in ZH environment, do you mean your Mattermost server? 

What language is your device set to?

**Comment by lindy65** [comment]
Hi @lin493369 

Please check the translations on the translation server or look for the translations in the localized file.

If the translation is there then we should see why is it happening as it is then most likely a bug.

**Comment by lindy65** [comment]
I'll close this issue off here for now due to inactivity.  If you're still experiencing problems, please feel free to open a new issue and we'll help troubleshoot further.  Thanks!
