### ISSUE TITLE
No sound nor banner alerts in the iOS (and Android?) apps 

### ISSUE THREAD

**Issue by kaksikanaa** [mattermost/mattermost-mobile#936]
#### Summary
iOS app has no sound nor banner alert for incoming messages.

#### Environment Information

- Device Name: iPhone 5
- OS Version: 10.3.3.
- Mattermost App Version: 1.2.0 build 49
- Mattermost Server Version: 4.2.0 Team edition

#### Steps to reproduce
Check one or more incoming messages.

#### Expected behavior
There should be some kind of a sound and banner alert when the message arrives even in the closed start screen if the app is still open on the device. The settings for the Mattermos app is allow sound and banner alerts on the device settings.

#### Observed behavior
No sound nor banner alerts show up.

This is a team edition server without push notification settings configured. 

If I understand right, the push notification server is only needed for alerts to the clients which are not open on the device, but if the client is open on the device, it should able to show alerts without the push notification server support, right? 

This works for example with SpreedME app + server very nicely without the push notification server configured.

**Comment by lfbrock** [comment]
Hi @kaksikanaa - when you say "when the client is open on the device", do you mean while the app is running? Or when it is in background? 

We have two types of notifications in the app right now. 

1. Push notifications, which require push notifications to be set up on the server. I believe these are currently used for all notifications except when you have the app open. 

2. In-app / local notifications that show up while you are using the app. 

It sounds like you are suggesting we send local notifications more often so a push notification server is not required? Or are you suggesting something else?

**Comment by kaksikanaa** [comment]
Hi,
I've meant both situation or status of the app, while using it and while in background (but still open).
At the moment at least in our configuration, the only notification for incoming messages is the red number on the left corner of app screen (if the user is in another channel than were the new message was arriving (btw the Unreads at the top of the channel list is very handy, thank for that). But even the app is open and in front of you, there is no sound alerts nor banner alert. At least (user configurable on or off) sound alert should be played when new message arrives.

And yes, I would think that it would be nice if it is possible to avoid the push server setup + the recompiling your own apps if possible. Majority of people seems not to be bothered to leave the app open in the background if they want to be available while actually enjoying the possibility to stop all work(?) related communication by shutting the app totally.

**Comment by lfbrock** [comment]
For anyone interested in notifications without a push server, please upvote the feature here: https://mattermost.uservoice.com/forums/306457-general/suggestions/16853752-support-mobile-web-push-notifications

**Comment by Pavelioso** [comment]
I have the same issue. Is there any resolve for this? Just get the number next to the app, but no sound.

**Comment by steinhh** [comment]
I have this issue as well - still. Extremely irritating for an app called *matter*most, since if it really matters, you shouldn't use it... I see the issue was closed, but with no fix?
