### ISSUE TITLE
Post time format does not respect user display setting

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#955]
#### Environment Information
- Device: Sony/Samsung 6.0.1
- Mattermost App Version: 1.2.0
- Mattermost Server Version: 4.2.0

#### Steps to reproduce
Set Android time format as 24h in Settings

#### Expected behavior
All posts times in app are in 24h format

#### Observed behavior
Post times are in 12h format (am/pm)

**Comment by enahum** [comment]
This is a Mattermost specific setting, you can change it in the Desktop or Webapp

![image](https://user-images.githubusercontent.com/6757047/31077381-b5d55c24-a754-11e7-9ccb-44e3cfdc94fc.png)

**Comment by licaon-kter** [comment]
Desktop/Webapp is already in the correct format, as selected in Settings, as 24h.

But not the **mobile** app...

**Comment by enahum** [comment]
Oh that is definitely a Bug, thanks for the report

**Comment by enahum** [comment]
closed via #977
