### ISSUE TITLE
Android 4.4.2. The app crashes on opening.

### ISSUE THREAD

**Issue by drholera** [mattermost/mattermost-mobile#969]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Trying to open Mattermost app. Click on icon. See "In application "Mattermost" an error has accured". Click OK. Try to re-open - catch the same error.

#### Environment Information

- Device Name: HTC Desire 816G
- OS Version: 4.4.2
- Mattermost App Version: Mattermost (not classic)
- Mattermost Server Version: 4.1

#### Steps to reproduce
Trying to open Mattermost app. Click on icon. See "In application "Mattermost" an error has accured". Click OK. Try to re-open - catch the same error.

#### Expected behavior
The app opens and I can enter credentials.

#### Observed behavior
The app crashes with "In application "Mattermost" an error has accured" error.

**Comment by enahum** [comment]
Because we added support for Android for Work the min API required is 21 meaning that only Android devices with OS version 5.0+ are supported. this PR #976 will make it more clear

**Comment by enahum** [comment]
closed via #976
