### ISSUE TITLE
Support for hashtags

### ISSUE THREAD

**Issue by dohliam** [mattermost/mattermost-mobile#972]
#### Summary
The mobile app does not appear to have support for hashtags.

#### Environment Information

- Device Name: All
- OS Version: All
- Mattermost App Version: 1.2.0
- Mattermost Server Version: 4.0.2

#### Steps to reproduce
Post a message containing a \#hashtag (any word preceded by a # character).

#### Expected behavior
The hashtag should become a blue link. Existing hashtags should be clickable and lead to a list of posts with the same tag.

#### Observed behavior
Hashtags are treated as plain text and are not clickable.

#### Possible fixes
Are there any plans to support hashtags in the mobile app in the near future?

**Comment by lindy65** [comment]
Hi @dohliam @fuedhdf 

Thanks for your feedback,

We've created [this ticket](https://mattermost.atlassian.net/browse/MM-10273) to implement the hashtag feature in the app.

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the above-linked ticket.
