### ISSUE TITLE
Channel URL's posted in chat don't link to the app

### ISSUE THREAD

**Issue by Shygar** [mattermost/mattermost-mobile#982]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When someone posts a URL in a chat that is the web browser link to a channel, it opens up in my mobile browser instead of the app

#### Environment Information

- Device Name: Galaxy S8
- OS Version: 7.0
- Mattermost App Version: 1.2.0 build 49
- Mattermost Server Version: 4.0.0 (4.0.3)

#### Steps to reproduce
1. Form a URL like this: https://<company>-mattermost.com/<company>/channels/mattermost
2. Paste that in the chat in a different channel than the one in the link.
3. Click the URL. It automatically goes to the web browser.

#### Expected behavior
I would expect in Android for it to give me the option to open up these URL's directly in the app itself.

#### Observed behavior
Browser window opened instead of app

#### Possible fixes
I didn't look through the code but I suspect some intent needs to register for that URL

**Comment by enahum** [comment]
Hi @Shygar this feature hasn't been implemented yet

**Comment by lindy65** [comment]
Hi @Shygar 

This feature is now implemented and you can upgrade to the latest version [here](https://about.mattermost.com/download/#mattermostApps).
