### ISSUE TITLE
Menu option in Android too sensitive

### ISSUE THREAD

**Issue by Shygar** [mattermost/mattermost-mobile#983]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
When you go to add a photo to a chat with the plus + sign, it appears to do nothing a lot of the times. But if you look closely, you can see if you're not careful you are slightly trying to slide out the menu from the left.

#### Environment Information

- Device Name: Galaxy S8
- OS Version: 7.0
- Mattermost App Version: 1.2.0 build 49
- Mattermost Server Version: 4.0.0 (4.0.3)

#### Steps to reproduce
How can we reproduce the issue?
1. Open the Android app.
2. Attempt to press the + sign on the bottom left when chatting in a channel.
3. Sometimes it will not work and if you look closely you can see the menu is slightly moving to the left.

#### Expected behavior
Plus + sign works every time you press it

#### Observed behavior
Menu appears to be trying to open. It's too sensitive

#### Possible fixes
I'd expect a half second delay or something like that to open the menu to prevent this. Or don't let the selectable region go all the way down to the chat bar of the screen in terms of activating the menu.

**Comment by enahum** [comment]
Hi @Shygar thanks for this we've made a PR #1029 that should take care of this and will be available in version 1.4

Feel free to re-open the issue if that's not the case for you
