### ISSUE TITLE
Gitlab SSO not working on v1.2 Mattermost Android 

### ISSUE THREAD

**Issue by david10sing** [mattermost/mattermost-mobile#989]
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Gitlab SSO goes to a blank white page

#### Environment Information

- Device Name: Galaxy S8 SM-G950F
- OS Version: Android 7.0
- Mattermost App Version: 1.2 
- Mattermost Server Version: 4.2

#### Steps to reproduce
Enable Gitlab SSO in Mattermost system console in web app. Click on Gitlab sign in button on mobile.

#### Expected behavior
On mobile should go to Gitlab sign in page.

#### Observed behavior
Loads Single Sign-on screen with a loading spinner. After a few seconds spinner goes away and screen is blank with the header.

**Comment by enahum** [comment]
Hi @david10sing have you tried with App version 1.3?

**Comment by mindo** [comment]
This bug still exists on 1.3.

**Environment Information**

- Device Name: Xperia Z3
- OS Version: Android 6.0
- Mattermost App Version: 1.3
- Mattermost Server Version: 4.2

**Comment by enahum** [comment]
hi @mindo we haven't been able to reproduce this, @lindy65 and @lindalumitchell can you confirm?

**Comment by lindy65** [comment]
Thanks @enahum @mindo 

As `enahum` mentioned, we haven't been able to reproduce your issue.  

Could we have your help upgrading to the [latest version](https://about.mattermost.com/download/) of Mattermost to see whether your issue still reproduces?

Thanks!

**Comment by mindo** [comment]
Hi @lindy65,

On my side the issue appear to be sorted out. We're using mattermost bundled with Gitlab and (at least) from their latest version (10.1) this no longer happens.

**Comment by lindy65** [comment]
Awesome!  Good to hear @mindo :)

**Comment by lfbrock** [comment]
Closing this issue, if anyone runs into it again please re-open!
