### ISSUE TITLE
Unable to send a message on iPad (IOS11) - Safari and Mattermost Classic App

### ISSUE THREAD

**Issue by mtraunau** [mattermost/mattermost-mobile#992]
#### Summary
It is not possible to send a message on the iPad because the return key just adds a line and there is no send button anywhere

#### Environment Information

- Device Name: iPad Pro 2017 12.9"
- OS Version: IOS 11.0.1
- Mattermost App Version: Safari, Mattermost Classic 3.10.1
- Mattermost Server Version: 4.2.0

#### Steps to reproduce
Log in to Mattermost, tap on the text field, type something and press return

#### Expected behavior
Message will be sent to the channel. Or a button "Send" would appear when typing starts.

#### Observed behavior
Just a new line is added, there is no way to send the message

**Comment by enahum** [comment]
Hi @mtraunau, thanks for bringing this to our attention. but this is a bug with the classic app and the webapp and not related to this project.

I've created this ticket https://mattermost.atlassian.net/browse/PLT-7876 so you can track the progress on that being fixed.

I'm going to close the issue, but feel free to open one in the `mattermost-server` repo ;)
